### ISSUE TITLE
Increase gap limit

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#10]
Trying to import a wallet but its not detecting the latest addresses used and because the earlier in the derivation path are have no UTXOs it doesn't find

Example
- m/44'/0'/0'/0/18 has 2 past transaction but no UTXO — Reads as empty and unused
- m/44'/0'/0'/0/406 has 1 transaction and 1 UTXO — i looks like its too far out that its not scanned

Is there a place to in crease the gap limit to look for more addresses deeper in the derivation path and also detect previously used addresses?

When importing to electrum it scans everything because I was able to increase the gap limit.

<img width="1275" alt="Screen Shot 2020-09-08 at 2 58 24 PM" src="https://user-images.githubusercontent.com/807505/92517176-3f983a80-f1e4-11ea-98ff-1e5f422dbc0d.png">

**Comment by craigraw** [comment]
This would be a code change right now, albeit a simple one. I will add support for it as a configuration setting.

**Comment by craigraw** [comment]
It's unclear why the m/44'/0'/0'/0/18 derivation is not pulling in earlier transactions though. It does not matter that there is no UTXO for this script hash. Assuming Electrum and Sparrow are talking to the same Electrum server instance, the RPC call is the same. Assuming the wallet is setup correctly and the addresses it is generating are correct, this call should return the same result.

Also, it looks like there are many addresses in this wallet that have had previous transactions with spent outputs - like most wallets Sparrow will keep incrementing the derivation path if it finds there are previous transactions until the gap limit is reached, regardless of whether those transaction outputs are spent or not. Is this behaviour consistent with what you're seeing?

**Comment by craigraw** [comment]
Wallet configurable gap limit added in https://github.com/sparrowwallet/sparrow/commit/38b27bb0916278c34360d0f652e1f3bd0382bc95 through an 'Advanced' dialog on the Settings panel.
