### ISSUE TITLE
Proposal: Color coding of transactions in transaction view

### ISSUE THREAD

**Issue by tychsen** [sparrowwallet/sparrow#100]
I propose to color code the transaction depending on the 3 states:

- Grey: unconfirmed (already implemented)
- Green: received transaction
- Red: sent transaction

![trans](https://user-images.githubusercontent.com/42609900/114320832-23f96780-9b18-11eb-8adc-965978ba5743.png)

**Comment by craigraw** [comment]
Thanks for the suggestion and clear mockup.

I am cautious of adding too much colour, so I've started off with just red text on the negative amounts. This matches Electrum's approach, I think it might be enough:

<img width="805" alt="Screenshot 2021-04-12 at 09 09 41" src="https://user-images.githubusercontent.com/862166/114354886-1de2a580-9b6f-11eb-8086-e551c7770847.png">

<img width="808" alt="Screenshot 2021-04-12 at 09 10 23" src="https://user-images.githubusercontent.com/862166/114354942-2dfa8500-9b6f-11eb-9363-30c33ec29b3d.png">

Implemented in 31fb527. Happy to consider further though.

**Comment by tychsen** [comment]
I have same concerns - like to keep it simple and clean. Still with a fast visual "feeling" of how much is incoming and outgoing...

If you choose to make unconfirmed colored too consider doing it by making a transparency - so no unconfirmed numbers have exact same color as confirmed ones.

**Comment by craigraw** [comment]
> I have same concerns - like to keep it simple and clean. Still with a fast visual "feeling" of how much is incoming and outgoing...

Will consider this further.

> If you choose to make unconfirmed colored too consider doing it by making a transparency - so no unconfirmed numbers have exact same color as confirmed ones.

This is actually the case - but I agree it's more difficult to see in the red color. I've reduced the opacity from 80 to 70% on unconfirmed transactions:

<img width="804" alt="Screenshot 2021-04-12 at 16 23 10" src="https://user-images.githubusercontent.com/862166/114410243-818ac400-9bab-11eb-817d-f5df5017ed07.png">

**Comment by tychsen** [comment]
This is already implemented right :) Lets close it.
