### ISSUE TITLE
Updating gap limit loses frozen state of UTXOs

### ISSUE THREAD

**Issue by BTCAlchemist** [sparrowwallet/sparrow#1000]
I am using the latest Sparrow version 1.7.7. When I update the gap limit in advanced settings, the wallet refreshed the transactions, but it unfroze all previously frozen UTXOs. I reproduced this with a second wallet file. This is difficult if a wallet has many UTXOs because the user must again analyze UTXOs to determine which needs to be frozen.
<img width="394" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/56145569/def889f6-5539-41a0-8673-5ae29df17e4b">

**Comment by craigraw** [comment]
Thanks for the report - as of https://github.com/sparrowwallet/drongo/commit/d5abf351bedc2e4234f14a1f3883feb9de6803be retaining the frozen status of a UTXO through a wallet refresh is now supported.

**Comment by RequestPrivacy** [comment]
Congratulations to issue #1000
