### ISSUE TITLE
[Bug] Import non-standard descriptor ignores values between angle brackets

### ISSUE THREAD

**Issue by KayBeSee** [sparrowwallet/sparrow#1002]
I am trying to import a wallet using a descriptor with a non-standard external/change path:

`sh(wsh(sortedmulti(2,[34ecf56b/0/0]xpub661MyMwAqRbcFPDVCyhqAHfTsUEF4BKMmCm5qQV3SCX3PjiSp2Hsoy3nSCS2v9Vp5k3LYvRk6WBU6tihioTBpbP6AHgvhTKw5dnkCG9akvG/<10;11>/*,[34ecf56c/0/0]xpub661MyMwAqRbcGxq9Aw9soQhEQenjzWm6n9YkAG9xeyfA9kRoN1Eg3x1hoMi3uNHyhQLnh1yvR5wCSNzcYKtmW8tN2E7M6bc28eEiTUoBqBj/<10;11>/*,[34ecf56a/0/0]xpub69UNYRpfNhhyk5RSZY8yaSunJM6P7BPp1d3LYikMNbAbxj5YPCvM4c5MYsupCHSv45aBty9z9vHk4buaTPRZLqHMk8NEZXEWy6anGYsL7eZ/<10;11>/*)))`

When I go to File > Import Wallet > Output Descriptor > Import File...

It accepts the file with the descriptor, but the addresses differ from what I would expect. I went into the settings and clicked to edit the descriptor to verify it was imported correctly, but the descriptor in the textbox is different from above. It seems it strips out those custom `<10;11>` values and replaces them with `<0;1>`.

`sh(wsh(sortedmulti(2,[34ecf56b/0/0]xpub661MyMwAqRbcFPDVCyhqAHfTsUEF4BKMmCm5qQV3SCX3PjiSp2Hsoy3nSCS2v9Vp5k3LYvRk6WBU6tihioTBpbP6AHgvhTKw5dnkCG9akvG/<0;1>/*,[34ecf56c/0/0]xpub661MyMwAqRbcGxq9Aw9soQhEQenjzWm6n9YkAG9xeyfA9kRoN1Eg3x1hoMi3uNHyhQLnh1yvR5wCSNzcYKtmW8tN2E7M6bc28eEiTUoBqBj/<0;1>/*,[34ecf56a/0/0]xpub69UNYRpfNhhyk5RSZY8yaSunJM6P7BPp1d3LYikMNbAbxj5YPCvM4c5MYsupCHSv45aBty9z9vHk4buaTPRZLqHMk8NEZXEWy6anGYsL7eZ/<0;1>/*)))#j77jk3su`

Is this functionality supported?

Related tickets
https://github.com/sparrowwallet/sparrow/issues/666
https://github.com/sparrowwallet/sparrow/issues/817

**Comment by craigraw** [comment]
Not a bug, this is not supported. Sparrow follows BIP32 wrt derivation paths.
