### ISSUE TITLE
Import from Private Key

### ISSUE THREAD

**Issue by kerner1000** [sparrowwallet/sparrow#1005]
Hi,
I have a private key starting with `L5`..
Sparrow expects a key to start with xprv/ zprv, see screenshot.
Is there a way I can import that wallet?
<img width="465" alt="Screenshot 2023-06-27 at 19 04 32" src="https://github.com/sparrowwallet/sparrow/assets/13817521/8441c458-d46f-46ad-ae27-c24fc16128e7">

**Comment by craigraw** [comment]
You can’t import it as a wallet, but you can sweep the funds into any HD wallet in Sparrow using Tools > Sweep Private Key.
