### ISSUE TITLE
1.7.7 Cannot parse QR code into a seed several times

### ISSUE THREAD

**Issue by tadeubas** [sparrowwallet/sparrow#1008]
Version 1.7.7 introduced the mnemonic QR code, I tried loading a QR code with 12 words with spaces only, commas only, spaces and commas, line break only... none of them worked, Sparrow said: `Cannot parse QR code on a seed.` . Later, I don't know why, it worked right away (only with words with spaces)

Here are the images:

![mnemonic-scanQR](https://github.com/sparrowwallet/sparrow/assets/5518496/5ad0df6b-b5dd-4c2f-b402-b6663aab5076)

![mnemonic-scanQR2](https://github.com/sparrowwallet/sparrow/assets/5518496/5c68a70c-53b5-4c92-b333-70349cfebf33)

**Comment by craigraw** [comment]
Probably a lighting change that made the QR code easier to read. Given the code is deterministic, I'm not sure there's anything to action here, so closing this off in favour of other issues around QR code reading. If you have a QR that consistently displays this behaviour, please add it below.
