### ISSUE TITLE
incrrect script type

### ISSUE THREAD

**Issue by zhangjun725** [sparrowwallet/sparrow#101]
Nested Segwit  script type shold be  "P2SH-P2WPKH" not "P2SH-P2WSH"

<img width="506" alt="pic" src="https://user-images.githubusercontent.com/5784767/114356524-4d130a00-9ba3-11eb-8532-e43e852c40db.png">

**Comment by craigraw** [comment]
Thanks! Fixed in https://github.com/sparrowwallet/drongo/commit/428054d375b638bb7e08133fdffe6f1dd438cca9.
