### ISSUE TITLE
Multiple output labels are not shown in the transaction history

### ISSUE THREAD

**Issue by Giszmo** [sparrowwallet/sparrow#1010]
In the "Transactions" view, each transaction has just one "Label" even though the transaction spent to multiple addresses with differing labels.

Looking at the :mag: details, output labels are not shown at all.

Sparrow 1.7.6 that is.

**Comment by craigraw** [comment]
This was addressed recently in https://github.com/sparrowwallet/sparrow/commit/5105b503ea276c5d8c71fde0c76cbf49bfc0a27a - when multiple payments are made, the transaction label will be a comma separated list of the individual payment labels.
