### ISSUE TITLE
Sparrow not updating balances 

### ISSUE THREAD

**Issue by prital01** [sparrowwallet/sparrow#1011]
I sent a small amount to my address of cc. 

Sparrow shows zero in transactions yet it shows correctly on blue wallet. What gives? Using a mac

**Comment by craigraw** [comment]
You have provided so little information it is impossible to answer this. What server are you connected to? Does the address with the funds appear in the wallet? Is the wallet loading correctly?

Please seek support in the Telegram chat: https://t.me/SparrowWallet
