### ISSUE TITLE
Bug - xpub QR exports unexpected deriv path

### ISSUE THREAD

**Issue by citizenanalog** [sparrowwallet/sparrow#1012]
Using Sparrow v1.7.7 with BIP39 single sig Native Segwit:

Using the xpub / zpub QR export feature, xpub is imported into BlueWallet with m/44'/0'/0' derivation path instead of m/84'.

zpub export works as expected.

**Comment by craigraw** [comment]
Indeed, but this is a problem with Blue Wallet and not Sparrow. xpubs should not be assumed to be representing legacy wallets. We have moved on from SLIP-132 to using output descriptors, where there is logical separation between script type and key information.

I suggest reading https://github.com/BlueWallet/BlueWallet/issues/2958#issuecomment-1567236915.
