### ISSUE TITLE
[Feature -Request] - Send to many copy-paste

### ISSUE THREAD

**Issue by TinF0ilHat1** [sparrowwallet/sparrow#1014]
Once _Send to Many_ windows is open sparrow does not allow to copy -paste from the background windows. Allowing it could make the workflow (of data copy paste) smoother, instead of solely relying on .csv

![image](https://github.com/sparrowwallet/sparrow/assets/127325867/4f84c013-2e16-415c-8658-c7c07561d9ec)

**Comment by craigraw** [comment]
As of 4c408ac7 the Send to Many dialog is non-modal (can move to the background). If the menu command is used with an existing dialog in the background, it is moved to the foreground.
