### ISSUE TITLE
Cant Spend UTXO's from my "Change Address" in Sparrow

### ISSUE THREAD

**Issue by HiJonesHere** [sparrowwallet/sparrow#1016]
Hi. 
![Skærmbillede 2023-07-08 kl  12 55 50](https://github.com/sparrowwallet/sparrow/assets/138984429/1fa25f63-3529-4f70-88a2-03f2a40b9907)
I have some Bitcoin in a "Change Adress" and i can't seem to spend it or send it out. It's in Sparrow Wallet. It doesnet give me the option to broadcast the transaction i can only save it localy on my computer. I Dont have any transactions stuck in the mempool so i dont understand it.  picture attached

**Comment by craigraw** [comment]
Sparrow needs to be connected to broadcast. See the toggle in the bottom left corner.

**Comment by HiJonesHere** [comment]
Where
![Skærmbillede 2023-07-08 kl  14 56 18](https://github.com/sparrowwallet/sparrow/assets/138984429/a8434969-b86d-4118-8d5d-fe9581a1405e)

**Comment by craigraw** [comment]
The yellow toggle in the bottom left corner.

Please don’t use Github for support requests.

**Comment by HiJonesHere** [comment]
Oh okay i got it Thanks!
