### ISSUE TITLE
Setting to limit batch size for fulcrum servers.

### ISSUE THREAD

**Issue by nostitos** [sparrowwallet/sparrow#1017]
When synching a large wallet or one with many complex transaction the resource limit for a batch on a fulcrum with default value can be reached.

Default : max_buffer = 8000000 and max_batch = 345
https://github.com/cculianu/Fulcrum/blob/master/doc/fulcrum-example-config.conf

I have my own fulcrum wallet so I was able to edit those values, but someone who doesn't might not be able to sync it's wallet unless he starts it by using a server that doesn't support batching.

**Comment by craigraw** [comment]
Sparrow does page batched requests, and there is already a config variable to change the page size, called `maxPageSize` in the `config` file. [By default it is set to 100](https://github.com/sparrowwallet/sparrow/blob/c9d6bb350d77b14c7fb68f9b24f7b9576370dd64/src/main/java/com/sparrowwallet/sparrow/net/PagedBatchRequestBuilder.java#L22). The default settings on Fulcrum are therefore higher and should not be reached by any Sparrow user with default configuration in both applications.

> unless he starts it by using a server that doesn't support batching

This will make no difference - batching is detected and configured for every new server connection.

**Comment by nostitos** [comment]
I think large transaction use much more of the buffer.

I've tried every max_buffer setting in 1,000,000 increment, 
Works at 16,000,000 fails at 15

Client.18499 BatchProcessor.20598 (100): cost for this IP (12043456) exceeds limit (12000000), killing batch processor
Client.18499 BatchProcessor.20598 (100): cost for this IP (12201212) exceeds limit (12000000), killing batch processor
Client.18499 BatchProcessor.20598 (100): cost for this IP (12429384) exceeds limit (12000000), killing batch processor
Client.56781 BatchProcessor.64629 (100): cost for this IP (14083180) exceeds limit (14000000), killing batch processor
Client.36338 BatchProcessor.38867 (100): cost for this IP (15033028) exceeds limit (15000000), killing batch processor

**Comment by craigraw** [comment]
If it's your own Fulcrum server, why not just turn this arbitrary throttling off entirely with `subnets_to_exclude_from_per_ip_limits`.

**Comment by nostitos** [comment]
I made the issue for other people who may not have direct access to changing their server's config.

To conclude I tested setting back the default fulcrum buffer config and edited the page size to 40 and that worked.

Thank you.

In summary, a wallet that participated in with Wasabi conjoins needs to have either sparrow page size reduced or fulcrum buffer increased in config file.

Closed.
