### ISSUE TITLE
automatic addition of utxos in input on RBF in v1.7.7

### ISSUE THREAD

**Issue by oldbreeze079** [sparrowwallet/sparrow#1019]
Steps to reproduce. 
Using x86-64 - Mac intel
server - private electrum 
fee rate source - mempool.space

- select 1 utxo (I took 500k sats) and send 100k sats. Use min fee ( I used 2 sats vb)
- select rbf 
- v7.6 shows only 1 (original utxo as input)
- v7.7 shows additional utxos as input 

While its possible to remove the additional inputs (by hovering over them in smaller labeled  utxo set wallet, but impossible when a large set of unlabelled utxos are added automatically for example postmix utxos)

**Comment by craigraw** [comment]
Thanks for the bug report. The structure of this transaction did cause an issue with overselection of UTXOs during RBF. Fixed in ebfdfc0c.

**Comment by oldbreeze079** [comment]
You rock Craig ! 🫡
