### ISSUE TITLE
Acronis (True Image Home or Cyber Protect Home) blocking USB link to Trezor

### ISSUE THREAD

**Issue by Roberden** [sparrowwallet/sparrow#1021]
Acronis works well by itself whether Sparrow is installed or not. Sparrow works well, and accesses Trezor (via USB connection), when Acronis is not installed. However, if both Acronis and Sparrow are installed simultaneously, Sparrow cannot communicate with Trezor. Attempting to sign a transactions fails as Sparrow just continues to scan for Trezor. Uninstalling Acronis makes Sparrow come to life.

I have disabled, AV, the firewall, changed from private to public networks, tried on different computers, to no avail. Something in Acronis is blocking Sparrow (or so I conclude). Contacted Acronis and they see Acronis working as it should (like I do) but it is Sparrow that cannot communicate by USB to Trezor. I like both programs and would hope for a solution that I can have both installed at the same time.

BTW - Using W10 Pro on an HP Z840 workstation. Second computer uses W11 Pro.

**Comment by craigraw** [comment]
This appears to be an Acronis issue - if Acronis is intercepting Trezor-related USB communications, there is probably not much that HWI can do (HWI is the application Sparrow uses internally to communicate with Trezor). That said, I suggest adding an issue to https://github.com/bitcoin-core/HWI/issues to learn more - the developers there may be able to provide more insight that can help to resolve the issue.
