### ISSUE TITLE
Can't connect to Bitcoin Core: Server returned HTTP response code: 403 for URL

### ISSUE THREAD

**Issue by Goro2030** [sparrowwallet/sparrow#1022]
Team,

I'm trying to connect Sparrow to my Bitcoin Core 0.25 full node. I tried using the .cookie file, and also the rpcuser and rpcpassword. I have rpcauth enabled too. 

I always get

```
Could not connect:
Server returned HTTP response code: 403 for URL: http://192.168.50.2:18332/wallet/cormorant

```
18332 is the correct port (not using 8332 directly)

In bitcoin.conf, I have the security set like this:

```
rpcuser=user
rpcpassword=password
rpcauth=user:4e98892384899f9a.....
```

What else can I try?

**Comment by craigraw** [comment]
The HTTP response `403` means a client authentication error.

I suspect you just need to delete the `rpcauth` line.

**Comment by Goro2030** [comment]
I fixed it! 

I had the connecting PC excluded from the rpcallowip range. 

Thanks for making me think @craigraw
