### ISSUE TITLE
Currency Rate disappearing in UI

### ISSUE THREAD

**Issue by oPFGKk9gtuw8nuHkzrQn** [sparrowwallet/sparrow#1024]
Concerns Sparrow Wallet 1.7.7

Sometimes, information about price (Balance value in FIAT currency ) disappears from the UI and also from the dropdown menu in preferences:

it normally appears where the blue circle is drawn (Price in EUR / USD etc):
![Balance](https://github.com/sparrowwallet/sparrow/assets/121948323/3de3f130-04fc-4b09-9ff9-f58e641ee22f)

At the same time, within preferences, the Currency Field is greyed out:

![Preferences](https://github.com/sparrowwallet/sparrow/assets/121948323/d57cf9e6-8d54-441f-bee8-324703e911ee)

**Comment by craigraw** [comment]
Check your log file (Help menu) - you may have connection issues to the exchange rate server.

**Comment by craigraw** [comment]
As of 31bd64f8 a warning will be shown in the Preferences if there was an error retrieving currencies from the exchange rate source.

<img width="862" alt="Screenshot 2023-07-17 at 11 11 13" src="https://github.com/sparrowwallet/sparrow/assets/862166/c5712e80-48c2-48cf-a04a-1ec800cd2fb3">
