### ISSUE TITLE
Error Dialogs text truncated

### ISSUE THREAD

**Issue by pjw65** [sparrowwallet/sparrow#1026]
Using Sparrow 1.7.7 on Ubuntu Linux 22.04
When broadcasting a transaction, sometimes there is an error (using "Private Electrum" ubrel on local network).
Most of the time, I can not read the message. 
The dialog text is only one line and truncated, the box is of fixed size.

![image](https://github.com/sparrowwallet/sparrow/assets/869541/a43a45e9-2bc0-44b1-9983-3b2f813ec859)

**Comment by alpeb-btc** [comment]
I was having the same issue on a fresh Arch box; fixed it by installing [ttf-ms-fonts](https://aur.archlinux.org/packages/ttf-ms-fonts).
