### ISSUE TITLE
loading history on multiple wallets at the same time fails

### ISSUE THREAD

**Issue by pjw65** [sparrowwallet/sparrow#1027]
Sparrow 1.7.7 on Ubuntu Linux 22.04
Using "Private Electrum" on Umbrel Node.

Every of the 6 open Wallets will fail the same when opening Sparrow:

> Wallet loading history for Wallet1 - Deposit
> [Jul 17 10:40:46] Finding transactions for [../0/0-../0/89]
> [Jul 17 10:41:29] Finding transactions for [../0/0-../0/89]
> [Jul 17 10:41:29] Failed to subscribe to paths: [../0/0-../0/89]
> Wallet loading history for Wallet2
> [Jul 17 10:40:49] Finding transactions for [../0/0-../0/21]
> [Jul 17 10:41:28] Failed to subscribe to paths: [../0/0-../0/21]
> Wallet loading history for Wallet3
> [Jul 17 10:40:49] Finding transactions for [../0/0-../0/62]
> [Jul 17 10:41:31] Failed to subscribe to paths: [../0/0-../0/62]
> Wallet loading history for Wallet4
> [Jul 17 10:40:49] Finding transactions for [../0/0-../0/20]
> [Jul 17 10:41:30] Failed to subscribe to paths: [../0/0-../0/20]
> Wallet loading history for Wallet5
> [Jul 17 10:40:49] Finding transactions for [../0/0-../0/20]
> [Jul 17 10:41:30] Failed to subscribe to paths: [../0/0-../0/20]
> Wallet loading history for Wallet6
> [Jul 17 10:40:49] Finding transactions for [../0/0-../0/20]
> [Jul 17 10:41:30] Failed to subscribe to paths: [../0/0-../0/20]
> 

"Refresh Wallet" works for every single wallet.

Seems to be a problem when asking the Electrum parallel for multiple wallets. 
How about doing one at the time AND/OR after failing retry after a random time of sleep?

**Comment by craigraw** [comment]
This is a problem with your Electrum server on Umbrel (probably Electrs), not Sparrow. Electrum servers are designed to handle requests from different wallets, and Sparrow ensures all requests are issued sequentially.

Try restarting your Umbrel.
