### ISSUE TITLE
[Feature] allow to display units BTC/sats in mix fashion

### ISSUE THREAD

**Issue by JrCs** [sparrowwallet/sparrow#1028]
It will be great to have a new display for the units that mix BTC and sat like this:

0,01832245 BTC can be display has 
![image](https://github.com/sparrowwallet/sparrow/assets/83008/6bb79477-72bb-4cf3-a8b4-3929adb424db)
so we can see the value in BTC & sats at the same time

**Comment by craigraw** [comment]
This adds too much complexity to the UI IMO.

For example, 1 BTC is now displayed as 1,00000000 BTC, and with different colours.
