### ISSUE TITLE
Gradle unable to download any jars from group io.matthewnelson.kotlin-components

### ISSUE THREAD

**Issue by killsnag** [sparrowwallet/sparrow#1031]
I am using the repo version '1.7.9' and Gradle is unable to download any jars from group io.matthewnelson.kotlin-components. Please advise.

**Comment by craigraw** [comment]
These jars are hosted on the (very highly available) Maven Central: https://mvnrepository.com/artifact/io.matthewnelson.kotlin-components

It's either a temporary network issue, or you have local issues connecting to that service. See if you can access https://repo.maven.apache.org/maven2/.
