### ISSUE TITLE
Add search for bitcoin public key address

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#1033]
Would be great to have the ability to look for a specific public key on the address tab.
Use case: confirm an address belongs to a wallet, even in offline mode.

Will it break if the address is outside the gap limit? Or could prompt the user to increase it if not found.

Thanks!

**Comment by RequestPrivacy** [comment]
Duplicate of #1001

**Comment by craigraw** [comment]
I'm a little confused - is this about searching for a public key or an address?

**Comment by craigraw** [comment]
No response, closing.
