### ISSUE TITLE
Bug: Descriptor incorrect for m-of-n where m is greater than 9

### ISSUE THREAD

**Issue by bitcoinhelp** [sparrowwallet/sparrow#1035]
Issue:

When 'm' in multisig quorum is two digits, the descriptor in Sparrow only shows the first digit. 

For example, a 10of15 multisig appears as a 1of15 multisig - and thus exporting to hardware devices or other platforms the wallet is identified as a 1of15

Additionally, the descriptor for a 20of20 multisig appears as a 2of20 multisig etc

<img width="1303" alt="Screenshot 2023-07-21 at 12 14 18 PM" src="https://github.com/sparrowwallet/sparrow/assets/104367423/d272fe7d-6189-4571-b0fd-e355b3c6d14e">

Version 1.7.8

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in https://github.com/sparrowwallet/drongo/commit/8313d16e97e708e7674646d43d66cf08b052b863.

**Comment by bitcoinhelp** [comment]
Appreciate the quick fix!
