### ISSUE TITLE
Blocked from your Telegram Support channel after developer-related questions and suggestions

### ISSUE THREAD

**Issue by meglio** [sparrowwallet/sparrow#1037]
Hey team, just wondering what caused you to block me from your Telegram @SparrowWallet group (my username is @meglio in Telegram). I guess it was some false-detection by mistake? The only thing I was doing is asking developer-related questions and giving suggestions. You even suggested that I created a detailed feature reqeust here in github for one of the things we have discussed.

**Comment by meglio** [comment]
Unbanned. Thanks.

**Comment by rapidlab309** [comment]
Hey, @meglio
I'm sorry for this inconvenience, false positive I guess.. Glad you've raised this issue and talked to me in DMs.
