### ISSUE TITLE
Support a mempoolfullrbf=1 configuration

### ISSUE THREAD

**Issue by bota87** [sparrowwallet/sparrow#1039]

**Comment by rapidlab309** [comment]
Can't.

**Comment by bota87** [comment]
I suspected that, can it be implemented?

**Comment by rapidlab309** [comment]
Nope, AFAIK.

**Comment by craigraw** [comment]
@rapidlab309 is correct.

**Comment by bota87** [comment]
With the last releases of bitcoin core there is support for full rbf so why it can't be implemented?

**Comment by craigraw** [comment]
It's a fair point. It may be worth adding a configuration variable for this, to match the one in Bitcoin Core (default disabled).

**Comment by bota87** [comment]
Looks good for me, issue reopened?

**Comment by craigraw** [comment]
In c57a4450 I've added config variable `mempoolFullRbf` to Sparrow's config file. It is set to `false` by default, but if set to `true` will enable RBF functionality on mempool transactions without checking the sequence flags on the transaction's inputs.
