### ISSUE TITLE
Feature Request : Allow custom user HWI

### ISSUE THREAD

**Issue by InfiniteQE** [sparrowwallet/sparrow#104]
Would you consider adding a settings option for a custom user HWI binary ?
This could be useful if there are major HWI fixes or feature updates, and allow users to compile HWI on their local machine, rather than to wait for an updated Sparrow version.

This could either be through a config file edit, or via the GUI

**Comment by craigraw** [comment]
Implemented in a8430c7.

I've left this as a file config edit, at least for now. Shut down Sparrow and edit the config file as follows:

```
...
  "hwi": "/path/to/custom/hwi",
...
```

Sparrow will not try to replace this file if it's not in the OS temporary folder area. If the configured file is not present however, Sparrow will revert to it's own copy of hwi.
