### ISSUE TITLE
Could not connect:  SOCKS server general failure. Check if the proxy server is running.

### ISSUE THREAD

**Issue by maxmanbtc** [sparrowwallet/sparrow#1041]
Hello,

I can't get Sparrow to connect to my private Electrum (I run a Citadel node) via Tor, I get Could not connect:
SOCKS server general failure. Check if the proxy server is running.
I know Sparrow has it's own built in Tor proxy and i can see Sparrow say it's Tor is running but when I test the connection in server preferences I get that message.
I have also installed Tor as a service on my Mac Book Air (MacOS Ventura 13.2.1) with Apple Silicon M1 but that wont help either.
I also get the same message when I try to connect via my local ip of the private Electrum. Both my Mac Book Air and the private Electrum are on the same local network.
I have talked to the developer of Citadel and his only idea was to install Tor as a service but as said, it's not work.

**Comment by craigraw** [comment]
Generally this means you should look the server, not the client. Check Tor on the server is configured and working correctly and that the Electrum server is running and accepting requests. If you can test it by connecting to it over a local IP, that can help troubleshoot.
