### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by proofofjogi** [sparrowwallet/sparrow#1042]
On plain vanilla nixos (not nix-bitcoin), I tried installing sparrow as per the instructions.

Unpacking worked but the file does not execute. I think it is lacking dependencies, which nixos does not come with by default. Thus my question here:

What are the dependencies for sparrow wallet so that I can run it on nixos?

Thank you

**Comment by craigraw** [comment]
The dependencies are very minimal and should be present already, AFAIK. See https://github.com/sparrowwallet/sparrow/issues/372#issuecomment-1239169799: `libc6, xdg-utils, zlib1g`

Did you use the correct download for your system architecture (arm vs amd)?

**Comment by proofofjogi** [comment]
Thanks Craig, I think I got the right download but I will double check now. I did think it was a depenencies thing because blockstream green quits as well in the same fashion with the same error message. I grab the exact message next time in nix, I've not got my github connection set up there

**Comment by craigraw** [comment]
Can we close this?

**Comment by proofofjogi** [comment]
Sure
