### ISSUE TITLE
Can never connect to any of the public servers

### ISSUE THREAD

**Issue by Eldaw** [sparrowwallet/sparrow#1044]
Using v1.7.7 and now v1.7.8 on Windows 10, I'm never able to connect to any of the public servers. With the original version I installed, v1.7.6, I could connect only sporadically -- I'd have to keep quitting/restarting/rebooting and trying again and eventually a connection could be established.

When doing 'Test Connection' it's pretty hit-or-miss. Sometimes I see a successful connection with some servers, other times not. Even in cases where I do manage to successfully do a test connection, I can't establish a real connection.

Unfortunately this makes Sparrow useless to me. Other wallets, like Electrum, instantly connect to their configured public servers. And they do so reliably every single time. No hassle, no nonsense.

Maybe Sparrow is only tested to operate successfully with a local node. But then it shouldn't pretend to have public server functionality.

**Comment by craigraw** [comment]
As a mainstream Bitcoin wallet, Sparrow is used by **many** people with the listed public servers. There appears to be some kind of network misconfiguration or other issue affecting your connection.

Bear in mind that the servers do have resource limiting in place, and will disconnect clients that place excessive strain on them (very large wallets etc). 

Why not configure Sparrow to connect to the same server you are successfully connected to with Electrum? Simply specify the details in the Private Electrum Server tab.
