### ISSUE TITLE
[Feature request] When importing wallet with seed search m/44'/... as well

### ISSUE THREAD

**Issue by Jacksper13** [sparrowwallet/sparrow#1050]
Bisq uses BIP44 for its accounts, and when importing the wallet via the 12 word seed, the "discover wallet" does not detect it, presumably because it doesn't search in m/44'/... BIP44 is also not one of the four options of derivations paths to select manually.

Could this derivation path be added to the ones where Sparrow looks for funds? Even if it only is in the automated wallet discovery part?

Thanks!

**Comment by Jacksper13** [comment]
In fact, since Bisq defaults to Native segwit, the addresses to search in the wallet detection should include account#1, or search directly in account #1 instead of #0
![image](https://github.com/sparrowwallet/sparrow/assets/63911988/61fd7594-6262-4513-b79b-889ff6429a60)

**Comment by craigraw** [comment]
Indeed, Bisq is non-standard on this, using `m/44'/0'/1'` on a Native Segwit wallet, contrary to BIP84. This is poor, and contrary to BIP44 which specifies the third index should be used for an account number, not a script type.

That said, Sparrow already looks for funds on all standard derivation paths (including `m/44'/0'/0'`) for all supported script types (including Native Segwit). I'll consider adding `m/44'/0'/1'` as well.

**Comment by craigraw** [comment]
Added `m/44'/0'/1'` to the list of derivations Sparrow searches against for mnemonic wallets in 870a4685.
