### ISSUE TITLE
Cannot connect to private node running on remote computer within LAN

### ISSUE THREAD

**Issue by FeatureSpitter** [sparrowwallet/sparrow#1052]
It was working for a couple of months but suddenly stopped working, between two idle machines.

This is the machine running sparrow:

![image](https://github.com/sparrowwallet/sparrow/assets/39516190/de31d314-aca1-4635-bb6e-f8c2295c3b8b)

Although if I `telnet 192.168.50.184 8332` it doesn't work and it was working before.

And this is the machine running the node (at that LAN IP address):

![image](https://github.com/sparrowwallet/sparrow/assets/39516190/91130a2f-85b5-4083-ab89-60df58ddc8a8)

It seems other peers can connect, but not me.

What am I missing?

**Comment by craigraw** [comment]
You should be aware that P2P peers connect on port `8333`. When you connect to the RPC interface (as Sparrow does) you connect on port `8332`. They are completely different.

It sounds like you are just missing `server=1` in the config file to enable the RPC interface.

**Comment by FeatureSpitter** [comment]
> You should be aware that P2P peers connect on port `8333`. When you connect to the RPC interface (as Sparrow does) you connect on port `8332`. They are completely different.
> 
> It sounds like you are just missing `server=1` in the config file to enable the RPC interface.

Hello, thanks for helping.

Unfortunately it didn't work, and it would be strange if it did, because I was always missing `server=1` and it was working before.

![image](https://github.com/sparrowwallet/sparrow/assets/39516190/3e3d5f60-fb1d-40df-bb00-1f8b1d05a376)

But it seems to be an issue on bitcoin core's side, because even with telnet I get a connection timeout if I try to connect from the machine which is running Sparrow:

![image](https://github.com/sparrowwallet/sparrow/assets/39516190/67cb677a-3593-4272-a856-c5b257ea576e)


I even tried to disable the firewall on the bitcoin core machine. No idea what's blocking it, but clearly not an issue with Sparrow.
