### ISSUE TITLE
Guarda import \ Safepal import ? ( Pull request)

### ISSUE THREAD

**Issue by pixel-wipe** [sparrowwallet/sparrow#1054]
Hello guys. Today I has installed and start to use sparrow wallet.

I has imported my btc seed frases From my guarda wallet and safepal wallet and sparrow wallet didnt showed me up balances From imported wallets.

What kind/type of derivation I May use while import guarda and safepal to be correctly?

**Comment by pixel-wipe** [comment]
Possible to Pull request import Guarda\Safeapal wallets?

**Comment by craigraw** [comment]
> What kind/type of derivation I May use while import guarda and safepal to be correctly?

I don't know, and a cursory search did not turn up anything relevant. It seems this is a question for that vendor, rather than Sparrow.

> Possible to Pull request import Guarda\Safeapal wallets?

I'm not sure what you mean by this - anyone is welcome to submit a pull request, although if those wallets follow standards it should be unnecessary.
