### ISSUE TITLE
Add copy/paste functionabillity to Sign/Verify Message UI

### ISSUE THREAD

**Issue by rapidlab309** [sparrowwallet/sparrow#1056]
Just a shortcut for faster interaction with Sparrow, specially for the signed message to be copied instead of `Ctrl/CMD + A` -> `Ctrl/CMD + C`.

**Comment by craigraw** [comment]
What did you have in mind? I'm not sure how the user would know about some other custom shortcut that did both functions?

**Comment by rapidlab309** [comment]
Something like that:
![image](https://github.com/sparrowwallet/sparrow/assets/96245140/5acc11d3-28f2-4003-be3f-659f7b0e14b3)

**Comment by craigraw** [comment]
I didn't find an elegant way to add a copy button to the text area, but clicking on the field will now automatically select all the text in it. ea3e0ca3.
