### ISSUE TITLE
Transferred into a Sparrow Whirlpool wallet by mistake.

### ISSUE THREAD

**Issue by cescobars54** [sparrowwallet/sparrow#1057]
I transferred by mistake into one of those self-generated Sparrow Whirlpool wallets. Now, I cannot see the funds I transfer. What can I do? please

**Comment by craigraw** [comment]
They are just a normal wallets. If you do not have the Premix, Postmix, Bad Bank tabs on the right, you can readd them using the Add Account button in the Settings (see Whirlpool Accounts). Then click on the tab for the wallet where you send the funds and transfer them out as you would send a normal transaction.

Please note that this channel is not for support - please use the Telegram group.
