### ISSUE TITLE
Getting an "No card present" error

### ISSUE THREAD

**Issue by p-bateman** [sparrowwallet/sparrow#1058]
Hey guys!

I'm using sparrow with a start 9 node. I can ping my local RPC address without any issues (it resolves to an IPv6 and IPv4) but when I try to connect in Sparrow I'm getting this error:

_ERROR [Thread-69] c.s.s.i.c.CardTransport [null:-1] No card present_
 
(it simply creates an ongoing Thread-## here – always has a different thread number)

Any ideas what I'm doing wrong?
Sparrow version: 1.7.8

Thanks

**Comment by craigraw** [comment]
The `No card present` is related to your smart card reader, and is entirely unrelated.

Pinging the address does not mean that the service you are connecting to is up and running. If you are connecting to Bitcoin Core, make sure you have enabled the RPC interface (`server=1` in the config file, see docs for details). If you are connecting to an Electrum server, make sure it is running, and has finished indexing. You may want to ask Start9 for additional guidance.
