### ISSUE TITLE
No Transactions 

### ISSUE THREAD

**Issue by potyu** [sparrowwallet/sparrow#106]
Completed Umbrel node setup (pi+SSD) - fully synced 2 days ago. 
Installed sparrow wallet (windows), imported wallet into sparrow (coldcard air gapped).
Connected to private electrum server using the URL provided in Umbrel Dashboard.
Generated new address and sent BTC from exchange to my address.
Initially I could see this transaction in the wallet (status unconfirmed).
after hitting refresh wallet - It cant see any transactions in my wallet.
Same thing when connecting with Public Server (bitaroo).
Tor Browser installed.
Freaking out a little.
Any advice is greatly appreciated.
[sparrow.txt](https://github.com/sparrowwallet/sparrow/files/6334880/sparrow.txt)

Log attached

**Comment by craigraw** [comment]
Do you have the txid? If so, what was the fee rate?

Something that may have happened with the recent sudden rise in fees is that the exchange didn't pay enough fees and the mempool transaction was excluded from the default 300Mb pool. This doesn't mean the transaction is lost (other nodes will have higher defaults) but it might mean that your Umbrel or the Bitaroo server doesn't have it anymore. This is unlikely but possible. The current purge rate is 8.5 sats/vB.

I'd try a few other public servers - connect to them, and refresh the wallet. If you saw it in Sparrow previously, it was on the Bitcoin network, so it exists.

**Comment by potyu** [comment]
Hi - thanks for the reply. I don't have the txid (i did when I could see the transaction in the wallet).
I just searched Bitcoin Explorer using my address and have found the unconfirmed transaction. 
Fee rate showing as 21.13 sat/vb
I used economy fee option at withdrawal from exchange. Rookie error?
Trying connections to other public servers - Is it generally a long wait for Finding transactions? - seems very slow.

**Comment by craigraw** [comment]
Ok great, your funds are in the mempool. Unfortunately, that transaction is going to take awhile to clear - hashrate has dropped significantly recently due to events in China and blocks are coming in more slowly which is pushing up the fees. One thing you can do is CPFP your stuck transaction. But it will likely clear if you are prepared to wait.

**Comment by potyu** [comment]
Thanks for your help ... good news is the transaction is now showing again (unconfirmed).
