### ISSUE TITLE
[Bug] Massive gap limit increase while mixing with Sparrow Server

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1061]
### System
- Sparrow Server 1.7.7 on Pi 4Gb
- Fulcrum 1.9.1

### Description
I have a couple of days old wallet from which I initiated a mix and furthermore mixed into from another wallet. 
Looking at the advanced settings in the Sparrow Server, I can see that Sparrow already increased the gap limit to a massive number of >2700. It seems to run stable though (i.e. it keeps mixing and fulcrum apparently serving data well).

But this can't be right so I'm open to tips for investigating...

**Comment by craigraw** [comment]
Not a bug, but rather a consequence of protocol decisions in Zerolink, and poor network reliability. Output addresses for the coinjoin cannot be repeated when registering for a mix, and if there is a communication error to the Whirlpool server the registration must be repeated with a new address. This causes the number of unused addresses and thus the gap limit to increase - all of the 'unused' addresses have already been seen by the coordinator.

The solution is to improve network reliability to the Whirlpool server. If the gap limit becomes too large, it makes sense to mix out to the postmix account in another wallet.

**Comment by RequestPrivacy** [comment]
So I guess it comes down to the tor network reliability since I'm in a country which has an overall internet connection that is pretty stable?! 

The question would be if Sparrow could handle this issue somehow? I mean, a minor increase in the gap limit seems not an issue but say Sparrow looses or can't get 10x the connection to the whirlpool server - couldn't it try to switch the tor connection and / or stop trying to make a connection to prevent the gap limit running out of hand?

**Comment by craigraw** [comment]
As of 995d2c5e, Sparrow will temporarily disconnect from Whirlpool if a rapid gap limit increase is detected. Specifically, if the gap limit must be increased more than 20 times in a 10 minute period, Sparrow will disconnect for 5 minutes.

**Comment by RequestPrivacy** [comment]
Thank you, will have a look if it helps!
