### ISSUE TITLE
[Feature]  List of addresses or priv. keys wallet. 

### ISSUE THREAD

**Issue by nostitos** [sparrowwallet/sparrow#1062]
I'm using this feature a lot in electrum,  It's useful to generate custom wallets to monitor a list of specific addresses.

I agree that the use-case might not be very popular but it's been very convenient for sharing a wallet up to a point in time.

It should be possible to create a wallet with a single address or private key.

... Also older wallet.dat were basically just list of keys.

**Comment by craigraw** [comment]
This is not supported because single address wallets encourage address reuse. For example, any change must be sent back to the same address.

**Comment by nostitos** [comment]
It's a good read-only accounting feature.
