### ISSUE TITLE
SparrowWallet

### ISSUE THREAD

**Issue by Gerosmcdonald1062** [sparrowwallet/sparrow#1068]
Hello, I lost my trezor and now I'm trying to link my new trezor to my multisig wallet on sparrow. Please help!

**Comment by craigraw** [comment]
You need to initialize the new Trezor with the same seed words as were on the old (lost) Trezor. So long as this is done, you will be able to use the new device as you did the old one.

**Comment by Gerosmcdonald1062** [comment]
Hi, thank you for your response. Can I change it back to singlesig? or do I have to keep the multisig? I need to import the new trezor correct? I'm having lots of issues. Or is there a way to reset the whole thing?

**Comment by craigraw** [comment]
You can't "change" any wallet - you need to move the funds from the old wallet by spending them. It sounds like you are moving too fast and need to slow down and understand what you are doing.
