### ISSUE TITLE
Issues with Multisig

### ISSUE THREAD

**Issue by Gerosmcdonald1062** [sparrowwallet/sparrow#1070]
I tested sparrow wallet with a single Sig, and everything worked fine. Now I tried to go to multi sig, and I can't move any of my funds. I would like to go back to Single Sig, but I don't know how or if it is possible. I'm scared of losing my funds! Please help! I don't want to be a bother to anyone. Thank you for your attention.

**Comment by craigraw** [comment]
Closing, see #1071
