### ISSUE TITLE
Signing with trezor issues

### ISSUE THREAD

**Issue by Gerosmcdonald1062** [sparrowwallet/sparrow#1071]
Sorry to keep bothering you. But my Trezor keeps signing where the cold card is supposed to sign then my Cold card can't sign. Any thoughts on what is going on. Thankyou!

**Comment by craigraw** [comment]
@Gerosmcdonald1062 opening three related issues on Github (which is exclusively for bugs and feature requests) is not how to go about seeking support. Please use the Telegram group https://t.me/SparrowWallet. 

With respect to your question it is difficult to tell what you have done. In a multisig setup any of the signers can sign the PSBT. Always, with a new wallet setup, test that you can spend with small amounts first. 

I recommend watching https://www.youtube.com/watch?v=qJ_SpQX_YKw to improve your knowledge on multisig setups in Sparrow.
