### ISSUE TITLE
Connecting to EPS to pruned node

### ISSUE THREAD

**Issue by tuxArg** [sparrowwallet/sparrow#1072]
Hi,

I'd like to ask if connecting to an electrum personal server is fully supported. I can see that it just works but in electrum there is a skipmerklecheck when eps is backed by a pruned node. Do I need a special config in sparrow?

Thanks

**Comment by craigraw** [comment]
Yes, it is fully supported (see the EPS export option under File > Export Wallet to get the EPS config file for a wallet).

You do not need any special config in Sparrow.

**Comment by AndySchroder** [comment]
What is the advantage of using an EPS pruned node over connecting Sparrow Wallet directly to Private Bitcoin Core pruned node?

**Comment by craigraw** [comment]
There is no advantage, but rather a disadvantage. Sparrow contains Cormorant, which is a library that does exactly what EPS does, but using newer Core descriptor wallets which handle gap limits within Core itself.
