### ISSUE TITLE
Long name for a wallet becomes unreadable

### ISSUE THREAD

**Issue by Urban-Hacker** [sparrowwallet/sparrow#1076]
When you choose a long name for your wallet it becomes unreadable unless you rename it again.
![image](https://github.com/sparrowwallet/sparrow/assets/92275709/f3440f55-716d-41ed-86f1-f1dbb306b5d0)

A few ideas how to solve this:
* We could display the name in both the vertical tab and in the wallet main screen itself, on top of everything else like in the screenshot, allowing longer description like the screenshot suggest.
* Restrict the amount of character even more and add a new section in the settings to add a longer description of the wallet.
* When the user place the mouse over the tab, display a tooltip with the full name.

**Comment by craigraw** [comment]
Added a tooltip to truncated account tab labels in 97f21394.
