### ISSUE TITLE
Registration issue for Ledger in multisig

### ISSUE THREAD

**Issue by dan6gig** [sparrowwallet/sparrow#1077]
Hi there. 

I’m trying to move funds from my multisig wallet in Sparrow (1.7.8). It’s a 2-3 with two Ledger Nano S devices and a software wallet. 
 
I understand for enhanced security, I now need to register the multisig details on my Ledger device before I can sign a transaction. 
 
I see the screen prompting me to register the device. I scroll through all the xpub details and click accept. But it reverts back to the screen asking me to register the wallet. 

It's an infinite loop. 
 
The strange thing is I have another (newer) mutisig on Sparrow and I was able to register my Ledger and sign a transaction on that.

Any suggestions are much appreciated. 

Thanking you.

**Comment by craigraw** [comment]
I believe this is a Ledger issue and not a Sparrow one. My guess is that the Ledger Nano S (which has limited storage memory) has run out of space to store new multisig configurations. That said, I'm not sure whether the failing multisig config is most recent one you tried to register.

@bigspider any thoughts?

**Comment by bigspider** [comment]
> I believe this is a Ledger issue and not a Sparrow one. My guess is that the Ledger Nano S (which has limited storage memory) has run out of space to store new multisig configurations. That said, I'm not sure whether the failing multisig config is most recent one you tried to register.
> 
> @bigspider any thoughts?

Ledger devices don't store the registered wallets. Instead, they return an hmac as proof-of-registration, which needs to be passed on future requests.

(HWI does not have a way of returning this hmac to the wallet (nor passing it when you sign a PSBT), therefore it does the entire registration flow whenever you make any request related to the multisig flow − that's not ideal but I doubt there is any bug related to that specifically)

Hard to pinpoint if registration might be failing without seeing what exactly is the policy.

**Comment by dan6gig** [comment]
The newer multisig wallet that I did register my Ledger with has a different set up. It's a 2-3 but with 3 hardware wallets (Coldcard, Ledger and Trezor.) 

Whereas the other multisig wallet I can't register my Ledger with has 2 hardware wallets (both Ledger) and a software wallet. 

Could the reason I can't register any of the Ledgers be that there's a software wallet as part of the quorum?

**Comment by craigraw** [comment]
> Could the reason I can't register any of the Ledgers be that there's a software wallet as part of the quorum?

I doubt it - the key information in the PSBT will be in the same format regardless of whether it is a hardware or a software wallet. 

Are all of the derivation paths in this multisig wallet the same?

**Comment by dan6gig** [comment]
Yes, all of the derivation paths are the same: m/48'/0'/0'/2'

**Comment by craigraw** [comment]
Ok. Make sure all of the master fingerprints are correct too.

Beyond this, unfortunately I can't say why it's failing, since it appears this is an error in the hardware wallet itself. You may want to discuss directly with their support team. One solution may be to use a more recent version of the Ledger (such as the Nano S+).
