### ISSUE TITLE
Allow import multisig configuration from Jade

### ISSUE THREAD

**Issue by bitcoinhelp** [sparrowwallet/sparrow#1083]
In the next Jade firmware release, we'll allow exporting a registered multisig configuration via QRs (in same format it is passed to Jade from Sparrow)

At the moment, the File -> Import Wallet path in Sparrow only expects the user's xpub QR when selecting Jade. Would be great to have this also check for a multisig file.

(FYI: We've tested the multisig import from Jade by selecting "BlueWallet" from the Import Wallet flow on Sparrow, and all works well there 👍 - just need something similar)

Thanks for looking into this!

**Comment by craigraw** [comment]
Will do - do you already know the UI path for this export in the Jade so I can amend the help instructions under the Details link?

**Comment by craigraw** [comment]
Added in 90bfa470. Let me know if the description needs to change:

<img width="469" alt="Screenshot 2023-08-31 at 09 36 45" src="https://github.com/sparrowwallet/sparrow/assets/862166/82d4ebdc-b831-40a7-bf21-1842a773744c">

**Comment by bitcoinhelp** [comment]
> Added in [90bfa47](https://github.com/sparrowwallet/sparrow/commit/90bfa470460bc5f595693cc55df71a5d1b9cd9b9). Let me know if the description needs to change:
> 
> <img alt="Screenshot 2023-08-31 at 09 36 45" width="469" src="https://user-images.githubusercontent.com/862166/264570915-82d4ebdc-b831-40a7-bf21-1842a773744c.png">

Perfect, appreciate the speed here Craig! That will indeed be the UI path, the user will just select their multisig record from Registered Wallets and they will see an "Export" button
