### ISSUE TITLE
Deleted Electrum Server connections continue to persist upon restart in version 1.7.8 EXE

### ISSUE THREAD

**Issue by mikeyb233** [sparrowwallet/sparrow#1084]
Go to File -> Preferences -> Server -> Private Electrum

Click dropdown on URL and click manage aliases and delete electrum servers connections. Restarting the program and going back to that table will show that the connections have not been removed. You are also unable to add a new connection that persists upon reopening.

This occurred while having two successfully connecting electrum servers and I attempted to replace one that is no longer used.

Sparrow Version 1.7.8 exe
Windows 10 Home

**Comment by craigraw** [comment]
I couldn't reproduce this at first, but I think I understand what may have happened. Sparrow stores any new servers to the alias list upon successful connection. Therefore, if the server you deleted in the Manage Aliases dialog was still the configured server (i.e. the dialog was closed without selecting another server), and there was then a successful connection to this configured server, it would simply have been re-added.

I can see how this might be confusing, so I've made a change in e23c1b38 which disables the Close button if the currently configured server is deleted, forcing selection of a new configured server.
