### ISSUE TITLE
Coldcard cannot sign PSBT produced by Sparrow

### ISSUE THREAD

**Issue by gus4rs** [sparrowwallet/sparrow#1087]
Exported a tx using "Save Transaction" button, it produced a file with 376 bytes. 
Exported using Electrum wallet using "For Hardware Device; include xpubs" and it produced a file with 888 bytes. 

Coldcard cannot sign the sparrow wallet tx, but can sign the electrum tx

Sparrow Version: 1.7.8

**Comment by craigraw** [comment]
Please be more specific. What error do you get? Singlesig or multisig wallet? Script type? Coldcard hardware version? Coldcard firmware version? Number of inputs/outputs in the transaction?

**Comment by gus4rs** [comment]
Coldcard 3 (4.1.3) prints in the screen "FAILURE My XFP not involved". Single sig tx, 1 segwit input, 1 segwit output

**Comment by gus4rs** [comment]
reimporting fixed it

**Comment by marcmoreau** [comment]
I had an the same issue and realized I was trying to sign a transaction with the wrong cold card. Rookie mistake
