### ISSUE TITLE
Can addresses be watched during IBD sync?

### ISSUE THREAD

**Issue by proofofjogi** [sparrowwallet/sparrow#1088]
Hello

syncing up a pruned node scans the wallet after IBD has completed and prune is applied at that moment. 

It would be better UX, to scan as the data comes in, maybe periodically.

Reason for my suggestion today: I just did a pruned sync on a laptop which is limited to 256 gig on the drive and has only about 100 gigs free. I set prune to 4 gigs and missed the wallet creation date with the prune setting, so the wallet got pruned of and now I have to re-sync holding more data, which I am trying now to use 95% of free storage on the device to make sure to catch the wallet. Will prune it down later.

If sparrow syncronized  repeatedly as data comes into bitcoind, that behaviour would be improved .

**Comment by craigraw** [comment]
This is unfortunately how Bitcoin Core works - it's not possible to change Sparrow to make this happen. When connected to Bitcoin Core, Sparrow relies on it to track the transactions in a wallet, so is dependent on how that tracking is performed.
