### ISSUE TITLE
[ QUESTION ] Mixed address type wallet

### ISSUE THREAD

**Issue by gus4rs** [sparrowwallet/sparrow#1089]
Samourai post mix spends sometimes can generate rest to a legacy address when paying to a legacy address. E.g.:

```
input1: segwit
input2: segwit
input3: segwit
```

```
outpu1: segwit
outpu2: segwit
output3: legacy (payee)
output4: legacy (rest)
```

How can I manage this in Sparrow? Right now I have a "Samourai Postmix" left tab that ignores the non-segwit utxos completely

**Comment by craigraw** [comment]
You'll need to create a separate wallet to see these UTXOs. Import the same seed with the legacy script type and postmix derivation path.

**Comment by gus4rs** [comment]
The Samourai Android app shows the balance from all UTXOs together, and can display UTXOs from different script types. 
I think the UX is great, is there any plan to replicate it in Sparrow?

**Comment by craigraw** [comment]
> I think their UX is great, is there any plan to replicate it in Sparrow?

Adding this would add considerable complexity in the Sparrow UI. For example, when you click on the Addresses tab, there would now need to show 6 lists of addresses instead of 2, to show the addresses for P2PKH, P2SH-P2PKH and P2WPKH (both receive and change). I am not convinced that the cost of this complexity is worth it to support the use case of creating change amounts in legacy address types.

**Comment by gus4rs** [comment]
> For example, when you click on the Addresses tab, there would now need to show 6 lists of addresses instead of 2, to show the addresses for P2PKH, P2SH-P2PKH and P2WPKH (both receive and change)

Don't forget P2TR :)

Bisq internal wallet does it, the addresses are all shown together.  

> I am not convinced that the cost of this complexity is worth it to support the use case of creating change amounts in legacy address types.

The "use case" is to import the Samourai Wallet(s) into Sparrow and have the same balance and see the same UTXOs from one place, but fair enough 👍🏻
