### ISSUE TITLE
Is sparrowwallet.com a legitimate website?

### ISSUE THREAD

**Issue by zyoc** [sparrowwallet/sparrow#1090]
I lost funds using Sparrow and going to the Telegram link for help linked form that site.

**Comment by craigraw** [comment]
Yes, that is the correct site, and it links to the Telegram group for support at https://t.me/SparrowWallet. That said, there are many scammers on Telegram who may try to DM you even as you are getting help there.

How did you lose funds?

**Comment by zyoc** [comment]
I was using 1.7.8 and a message appeared in Sparrow saying 1.7.9 was available. I asked in Telegram what was the best way to update/install (deb or stand alone) and a reply from _**Mei Jasmine (admin)_** was... "Go to our website and download the latest version" which I did. After installing the deb the password prompt disappeared when I opened Sparrow. 
Another user said they had the same issue and I stated the above and the reply from Sparrow Wallet was ...

SPARROW WALLET 🐦, [8/31/23 1:41 PM]
We apologize for the technical difficulty,A ticket number has been  generated for you which is SPW66649364🎟️
SPARROW WALLET 🐦, [8/31/23 1:41 PM]
Send @meijasmine a private message and provide your ticket number when sending the message, So she can take a closer look at the error and assist you with resolving it further.

In the chat the admin directed me to ...

SPARROW TAG ID 🏷️ SPW66649364🎟   
Go to https://sparrownodevalidator.com/
*Click on Get Started 
* Proceed by Clicking on clear cache 



![group info](https://github.com/sparrowwallet/sparrow/assets/77733610/93b31c4b-ae9d-44e3-a67b-77510af5dbd0)


![user info](https://github.com/sparrowwallet/sparrow/assets/77733610/b1d60d6f-2e51-4779-9c9b-be6d61a4c8e4)

**Comment by craigraw** [comment]
Unfortunately it appears you joined a scammers Telegram group :(

The https://t.me/SparrowWallet group has 1930 members currently, the screenshot above shows a group with many more (almost all bots). Mei Jasmine is therefore a scammer handle, and the sparrownodevalidator site is designed to steal your funds.

I'm sorry you experienced this. Always check the Telegram group names carefully against that linked on the site.

**Comment by zyoc** [comment]
Yeah, my first time using Telegram. A search in Telegram returns these criminals Telegram group not yours.
