### ISSUE TITLE
CoinJoin Error - Passphrase with special character

### ISSUE THREAD

**Issue by schafskopf** [sparrowwallet/sparrow#1093]
When I try CoinJoin i get this Error:
Error broadcasting premix Transaction
Failed to find UTXOs in Whirpool wallet

I'm connected to my own fulcrum server.

LOG:
WARN [JavaFX Application Thread] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxxxx:0): not found
WARN [JavaFX Application Thread] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxxxx:0): not found
WARN [JavaFX Application Thread] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxxxxx:0): not found
WARN [Thread-52] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxx:0): not found
WARN [Thread-52] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxxxxxxxxxx:0): not found
WARN [JavaFX Application Thread] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxxxx:0): not found
WARN [JavaFX Application Thread] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxx:0): not found
WARN [JavaFX Application Thread] c.s.w.c.w.d.u.BasicUtxoSupplier [null:-1] findUtxo(xxxxxxx:0): not found

Can it be related to the fact that I use a passphrase with special characters (!)?
Everything except CoinJoin works.

Now I have created a new wallet with another passphrase (without specialcharacters and öäü etc.) And everything works now.

**Comment by craigraw** [comment]
Fixed in https://github.com/sparrowwallet/nightjar/commit/e39809f1c54546698cbc63cbf353b5155c402d7f - the Whirlpool client was not encoding passphrase characters in NFKD encoding as required by BIP39. Dependency update in Sparrow still required, so keeping this open for now.

**Comment by craigraw** [comment]
Tested and committed in 0d7ae74f.
