### ISSUE TITLE
[Feature] Add Fiat value option to the chart and transactions

### ISSUE THREAD

**Issue by Potificate** [sparrowwallet/sparrow#1095]
To start with, I am NOT a trader who watches the value of my stacked sats minute to minute. :-) I just feel that, at this point in time, fiat valuations are still relevant as the give a gauge/guideline as to the buying power of one's portfolio at any given point in time.

What would also be of extreme help is *two* fiat columns in the transactions list. One for fiat valuation at time of the transaction and one for current value. This information would be of particular help when filing taxes.

**Comment by craigraw** [comment]
I am not keen to add fiat values to the transactions table and chart - I believe wallets need to do their part to help people think in Bitcoin and not fiat terms. There is also the consideration of adding more complexity to the UI, which is something I am reluctant to do unless the benefit is very clear.

You may however want to consider adding a comment to #683 - I am sensitive to the tax reporting needs of users, although there are valid problems listed there around sourcing historical exchange rates.
