### ISSUE TITLE
Show end of bitcoin address at last sending step.

### ISSUE THREAD

**Issue by nostitos** [sparrowwallet/sparrow#1096]
![image](https://github.com/sparrowwallet/sparrow/assets/48504624/e95f0c00-c712-4cfe-9982-401deff51fb3)

Having to mouse over to double check that it's the right address is not ideal.

**Comment by craigraw** [comment]
I agree it's not ideal, but in the general case (long labels, multiple payments, small screen) there isn't enough space:

<img width="421" alt="Screenshot 2023-09-10 at 17 09 03" src="https://github.com/sparrowwallet/sparrow/assets/862166/aab79a52-c39c-4568-a416-a824f61f1de1">

Note that at least 6 characters from the end of address are required, or another address can be easily brute forced to look similar. 

That said, I would like to try find a better solution here.

**Comment by nostitos** [comment]
Sorry to mix things up, 

I was also pointing out that trimming labels after 10 characters is a bit intense, the wallet windows need to be smaller 800 pixel wide before it's run out of space to show 10 char. 

![image](https://github.com/sparrowwallet/sparrow/assets/48504624/4c9619ce-4e4e-486f-b235-9d20765f57c5)

![image](https://github.com/sparrowwallet/sparrow/assets/48504624/55c0fd69-1bfe-4b1d-960c-1c4ed861dce8)
Great, I see it's already trimming when too small, so we could just keep the labels to their full length and let it trim.

**Comment by craigraw** [comment]
Solved by adding a caption to the transaction diagram. The caption has the dual role of summarising the transaction, and displaying the full recipient and change addresses. The field has a carousel control on the right that can be scrolled through should there be multiple recipients. External recipients are shown first. 4e3e8b7c.

<img width="1169" alt="Screenshot 2023-10-11 at 13 30 53" src="https://github.com/sparrowwallet/sparrow/assets/862166/b4946daa-49f6-4e13-8b69-708949d82422">
