### ISSUE TITLE
Button that broadcasts should not be so close to button that opens a transaction for preview

### ISSUE THREAD

**Issue by Amperstrand** [sparrowwallet/sparrow#1099]
<img width="1790" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/141745238/946ce18b-8f93-49b8-9d19-316bf0525c6a">

I use Sparrow to verify transactions for the company I work at before they are broadcasted. An issue I had a couple of days ago was that we were troubleshooting a new wallet where the mining fee was getting set way too high. I opened that transaction in Sparrow to parse it to see what was going wrong, and then it was broadcasted by mistake.

As a feature request, I would kindly ask that the OK button which opens and previews a transaction should not be so close to the Broadcast Transaction button.

When previewing transactions I sometimes get nervous. This causes my hand to shake in a way where it sometimes inadvertently clicks on the Broadcast Transaction button (see attached screenshot).

**Comment by craigraw** [comment]
Have you tried moving the Open Transaction window first?

**Comment by nostitos** [comment]
@Amperstrand These two buttons / windows are not related to a single action flow. Seems like a very special case.

**Comment by Amperstrand** [comment]
When you go to file, open transaction, from text (or file) and import an unbroadcasted transaction, the button to broadcast the transaction is hidden under the OK button (depending on screen resolution).

So if you click on the OK button twice, the transaction is broadcasted (because the second click will hit the Broadcast Transaction button).

This is probably usually what you want to do if you are opening a signed transaction. If for whatever reason are not intending to broadcast it, its a mistake that can easily happen.

Moving the Open Transaction window is a very clever workaround that fully resolves the issue.

The other way to resolve the issue is to not open transactions that are fully signed that you don't wish to broadcast or don't use a touchpad which is overly sensitive.

Closing the issue because moving the window is a good workaround and because it is a fairly niche use case. But I would still argue that putting the Open button so close to the Broadcast button is UX issue that can result in mistakes again.
