### ISSUE TITLE
[HWW - CK Tap] Tapsigner/Satscard not found, but `cktap` tool works

### ISSUE THREAD

**Issue by AngusP** [sparrowwallet/sparrow#1103]
Having difficulty getting Sparrow to recognize a Tapsigner/Satscard using the HID Omnikey 5022 USB reader.

![sparrow-not-found](https://github.com/sparrowwallet/sparrow/assets/1328814/1ee85556-6762-4c42-b967-887d78747094)

System is Fedora (Silverblue) `Fedora Linux 38.20230731.0 (Silverblue)`

Coinkite's `cktap` utility works fine, so I'm assuming it's just a case of Sparrow not finding the PCSC library -- particularly here: https://github.com/sparrowwallet/sparrow/blob/93bcf6cef91293f22c166d23ef0d00ef0eb4f85f/src/main/java/com/sparrowwallet/sparrow/io/CardApi.java#L32-L37

None of these exist at those paths on my system -- but there **is** `/usr/lib64/libpcsclite.so.1` and `/usr/lib64/libpcsclite.so.1.0.0`

`cktap` working, and showing `dmesg` picking up the reader:

![cktap-works](https://github.com/sparrowwallet/sparrow/assets/1328814/a3b6c771-d1a3-4f7f-a713-b28683a1aad3)

(I *have* some issues recently with pcscd.service and pcscd.socket (gpg not being able to see a smartcard until restarting these) but I think that's probably a separate problem, as `cktap` still worked.)

**Comment by craigraw** [comment]
Have tried creating symlinks from the libraries in /usr/lib64 to /usr/lib? Usually these are already present, but sometimes they need to be created manually.

**Comment by AngusP** [comment]
Thanks for the response :pray: 

> Have tried creating symlinks from the libraries in /usr/lib64 to /usr/lib?

Fedora Silverblue is *iamveryclever* and has an "immutable base filesystem", so `/usr/lib` is read-only, but I can fix by symlinking in `/usr/local/lib`

I suppose just that might be fine, though is it worth adding `/usr/lib64` as a place for Sparrow to look?

**Comment by craigraw** [comment]
Yes, probably worth it. Added in a18c24e1.

Closing this off.
