### ISSUE TITLE
Missing Transactions History and UTXOs

### ISSUE THREAD

**Issue by jwblyth** [sparrowwallet/sparrow#1105]
I downloaded sparrow on one computer and set up a new wallet configuring it on electrum private server. I downloaded sparrow on a second computer and am trying to restore/retrieve my sparrow wallet on my second computer. I have tried to import the wallet to my second computer using the original sparrow wallet password and 12 word passphrase. The sparrow wallet on the second computer shows no transaction history or UTXOs, even though I have had several received UTXOs from prior transactions on wallet on computer 1. I have only recieved transactions and never sent any sats from my sparrow wallet. Why no transaction history or UTXO balances showing in my restored wallet? Thanks.

**Comment by RequestPrivacy** [comment]
75% chance you entered a passphrase differing from the one of the original wallet (compare the fingerprints of each wallet to see if they're the same) or a 20% chance there's an error retrieving the wallet from your server (connection issues)

**Comment by craigraw** [comment]
Good advice. 

Closing this off, please use https://t.me/SparrowWallet for support (and not Github).
