### ISSUE TITLE
[Feature request] External interface creation for signing PSBTs and message strings

### ISSUE THREAD

**Issue by fess-v** [sparrowwallet/sparrow#1106]
Hello! We're at [Asigna](https://asigna.io/) really looking for a way to integrate Sparrow. For that, we need to be able to sign a taproot PSBT as well as sign a message to be able to authorize our users.
Since we're a web-based multisig, it would be great to have some kind of an interface to be able to interact with a desktop application via deeplinks or through QR codes. Would be glad to get any comments or suggestions on that, we're ready to help with the implementation.

**Comment by craigraw** [comment]
You're able to sign a Taproot PSBT using Sparrow and QR codes already. For QR based message signing, please see #615, which I'm considering for implementation. I'm less keen on implementing deep links, which would require registering additional URI handlers - there would need to be a strong use case for this, and probably a specification as well.

**Comment by fess-v** [comment]
Hey @craigraw thanks a lot for your reply, I think we will integrate it without message signing for now, but we'll wait for this feature to be implemented and then modify our authorization flow
Agree on deeplinks, I think QRs are more than enough for our use case, thank you again
Closing this issue due to #615 already created

**Comment by fess-v** [comment]
Hey @craigraw 
I think there's an issue with Taproot multisig scripts 
What we're doing:
File -> Open transaction -> From text
Pasting this transaction:
cHNidP8BAH0CAAAAAbxDxlOPj3EPJfDQFNlDe8cvh4Rvaus6o1SV4tGHBpLcAAAAAAD/////AqCGAQAAAAAAFgAUBMMvcumSneytZzmL5E4LxYy6rDgAuw0AAAAAACJRIJARrwjKZrbxkZVk8nCYID9GyJmH4hSpERz5bMh6H+yKAAAAAAABAStAQg8AAAAAACJRIJARrwjKZrbxkZVk8nCYID9GyJmH4hSpERz5bMh6H+yKIhXBc/CPUvAZuSgJ5mTF+aNt335PTm09iRPO/1IGlbLXx/wjIDw7h/L9sQtd8mX/TMynCq4v4aoWzS9vunfHYOVUXLwhrMAAAAA=

Which is basically a Taproot multisig script with only 1 owner
The owner is this wallet:
![image](https://github.com/sparrowwallet/sparrow/assets/26626714/895d7a89-a1b6-40fe-a00f-05853970dc15)
So we definitely have this wallet available (and we connected this wallet to our application successfully).
What we're getting next is that no wallet can sign this transaction.
![image](https://github.com/sparrowwallet/sparrow/assets/26626714/01f27c01-7dc4-4409-b93a-7e8e9a5f737d)
Could the taproot tweaking mechanism cause this? 
Please, let me know if we're doing something wrong or if we need to send you the seed phrase for this wallet to test it out, thank you!

**Comment by craigraw** [comment]
> Which is basically a Taproot multisig script with only 1 owner

Creating a Taproot multisig wallet in Sparrow is currently not supported, as standards for Taproot multisig are still emerging. It appears you have created a Native Segwit testnet wallet ('tb1q...`). Did you mean to create a Taproot singlesig wallet?

**Comment by fess-v** [comment]
No, we're from Asigna trying to integrate the Sparrow Wallet now, so this transaction was created separately from Sparrow, but we tried to sign it with it
Do you think Taproot PSBT signing could be supported by Sparrow in the near future?

> > Which is basically a Taproot multisig script with only 1 owner
> 
> Creating a Taproot multisig wallet in Sparrow is currently not supported, as standards for Taproot multisig are still emerging. It appears you have created a Native Segwit testnet wallet ('tb1q...`). Did you mean to create a Taproot singlesig wallet?

**Comment by craigraw** [comment]
> Do you think Taproot PSBT signing could be supported by Sparrow in the near future?

We're going in circles here. Singlesig Taproot PSBT signing is supported. Multisig is not (there any number of ways to create a Taproot multisig wallet, and no well defined standard).

**Comment by craigraw** [comment]
Nothing to do here at this time, so closing this off.
