### ISSUE TITLE
3 different ledger types not connecting with Sparrow-1.7.9 v

### ISSUE THREAD

**Issue by DYOR-Labs-Titan** [sparrowwallet/sparrow#1107]
Hi it is JGX from TG- 
None of my 3 Ledgers HW  (NanoS, NanoX and Nano S+) can be detected by Sparrow wallet. 
BTC app is open before requesting to import HW, also I have tried after the screen dialog ask for it
All HWs are up to date on firmware and drivers. 
I am using : 
- Norton 360
- Windows 11 Pro 64 bit
- 12 gen Intel core i7, 32 RAM

I have restarted the PC several times , Also, I have used another W11 mini-PC, without any success. 
I have used different USB ports , nothing.
The Sparrow log does not shows any USB word, also I re-installed Java

I have used the *.exe and the standalone install, nothing .

Ledger Support shared some basic instructions, but It di not work, they gave up as they advise me to use Electum wallet, which I do not want to use.

Thanks 

Titan

**Comment by craigraw** [comment]
@bigspider any ideas?

I see a similar issue at https://github.com/bitcoin-core/HWI/issues/667, and another user has reported this with a M2 Mac.

**Comment by DYOR-Labs-Titan** [comment]
Problem was fixed, Norton antivirus issue. I added the solution in TG under JGX. Thanks

**Comment by craigraw** [comment]
For other who might find this thread:

> My Norton Antivirus was blocking all ledger or Sparrow actions. I fixed it by going to :
> Norton Settings/ Antivirus/ Data Protector/ Process Exclusions/ Configure/ then Add file

![photo_2023-09-29_07-54-36](https://github.com/sparrowwallet/sparrow/assets/862166/d93f6a24-d1dc-4f51-8c3e-77a7168e55d1)
