### ISSUE TITLE
Sparrow unable to connect and won't run as usual.

### ISSUE THREAD

**Issue by jacksongreyrat** [sparrowwallet/sparrow#1109]
I've been struggling with this problem since yesterday. For some reason all the wallets on my Mac won't work. Blockstream Jade, Specter and Sparrow. Seem like it's not connecting to the internet or server. These are all the method that I've tried so for.

1. Reboot machine and application
2. Reinstall
3. Turnoff VPN
4. Turnoff Firewall
5. Change ISP

Yet. Nothing works. 

<img width="1182" alt="Screenshot 2566-09-26 at 09 17 16" src="https://github.com/sparrowwallet/sparrow/assets/97287125/74c6d9a6-54ed-4d8e-97eb-ea92361dca3a">

**Comment by craigraw** [comment]
Take a look at your macOS Network configuration - possibly something has changed there, especially if you use a VPN.

**Comment by jacksongreyrat** [comment]
> Take a look at your macOS Network configuration - possibly something has changed there, especially if you use a VPN.

I did looked and found out the problem come from the proxy. Because I use Netshare and it config custom proxy which led to Electrum server connecting issue. However, when I config the proxy in Sparrow just like I did in my Mac. It still not connecting. For now I use another ISP without proxy instead and it works.
