### ISSUE TITLE
UI, get an address is to far down + could give an address by default

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#111]
![image](https://user-images.githubusercontent.com/388716/116471722-0419b180-a843-11eb-8d8d-d831fe682db2.png)

**Comment by craigraw** [comment]
A timely issue - as of 1.4.0 the address field will always show a fresh address. The 'Get Next Address' button should not need to be used much - only really in the case of an offline situation where there is outside knowledge that an address has been used.

I think this has been addressed, so I'm closing it off.
