### ISSUE TITLE
Add postmix account to watch only wallets

### ISSUE THREAD

**Issue by checkuon** [sparrowwallet/sparrow#1110]
Right now only accounts 0-9 can be added when using a watch only wallet. Would be useful to be able to add the postmix account as well. Would work well with the Passport HWW that has implemented the postmix account.

**Comment by craigraw** [comment]
Added in 0724c385. A postmix account with the correct derivation path and script type can now be added to any legacy, nested segwit or native segwit wallet. 

<img width="393" alt="Screenshot 2023-09-29 at 14 40 01" src="https://github.com/sparrowwallet/sparrow/assets/862166/7592388e-531d-47fc-b436-53dd1caf58bf">
