### ISSUE TITLE
BIP157 / neutrino mode

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1111]
Wondering if it's worth implementing BIP157 / neutrino mode in sparrow wallet as another backend option? Seems like it would be ideal to eliminate the electrum server requirement. Bitcoin Core 0.21.0 has support for BIP157 and a large percentage of publicly accessible nodes on the network (https://bitnodes.io/nodes/) are running a version of bitcoin core greater than 0.21.0.

BIP157 isn't perfect, but it seems better than trusting a single electrum server. If you run your own bitcoin core node without an electrum server, you need to rely on bitcoin core to watch the wallets from sparrow. It seems like it would be a better design to have sparrow wallet keep track of things instead of require the two to always be in sync with each other. This way you connect to any bitcoin core node and things just work.

**Comment by craigraw** [comment]
The problem with BIP157/158 is that it doesn't scale well. In fact, any protocol that requires the download of an entire block just to retrieve a transaction or two fundamentally does not scale well. This is the issue which affects scaling in Electrs, which I [have discussed here](https://sparrowwallet.com/docs/server-performance.html#discussion). Implementing BIP157 will add another option and increase the complexity of connecting to a server, with these tradeoffs that are perhaps not obvious at first but become more negative over time as the wallet depth increases. For these reasons, I am reluctant to add this.

**Comment by AndySchroder** [comment]
I am now agreeing more with you on this. With https://github.com/sparrowwallet/sparrow/issues/1383 and https://github.com/sparrowwallet/sparrow/issues/1361 we have a better experience with bitcoin core. With https://github.com/bitcoin/bitcoin/issues/29183 we will get the ability to run a pruned node and do relatively quick rescans. I think running a pruned node is going to be a lot better than running neutrino node and we will actually be validating consensus rules rather than just checking how much work is in the block headers.
