### ISSUE TITLE
Can't sign Taproot tx when using privacy mode

### ISSUE THREAD

**Issue by nobody77777** [sparrowwallet/sparrow#1112]
Hello,

I am using two Sparrow instances version 1.7.6. One is offline for signing and the other as watch-only on an online device. Both devices run Debian 11. The wallet is BIP39 Taproot with passphrase and the default 86' derivation.  After creating a transaction with the watch-only wallet using privacy mode and then loading the PSBT file into the offline Sparrow and clicking Finalize Transaction for Signing then clicking Sign, I noticed the blue progress bar fills up but then nothing happens. Specifically, the buttons do not change to the expected "View Final Transaction" and "Save Final Transaction". This issue only happens when using privacy mode when creating the transaction and it does not happen when using efficiency mode. The log file does not show any new lines/entries. Please let me know if there is any additional information that I can provide to help troubleshoot this issue.

Thank you for your time

**Comment by craigraw** [comment]
Try increasing the gap limit on your signing wallet so that it contains all the addresses reflected in the watch-only wallet. Settings > Advanced > change > Close > Apply.

**Comment by nobody77777** [comment]
That worked! Thank you very much.
