### ISSUE TITLE
Testnet Public Server is Down

### ISSUE THREAD

**Issue by glethuillier** [sparrowwallet/sparrow#1113]
The public server `testnet.aranguren.org` is no longer accessible. Since it is the only available testnet endpoint, using the wallet on the testnet with the default configuration is currently impossible.

<img width="862" alt="wallet_bug" src="https://github.com/sparrowwallet/sparrow/assets/66550865/319ccec9-cc1a-4522-801d-36fbb6a905a2">

**Comment by craigraw** [comment]
Noted. Probably just down for upgrades (Fulcrum was just updated), but `ssl://testnet.qtornado.com:51002` is an alternative in the interim. I will look at adding to the list of public testnet servers.

**Comment by craigraw** [comment]
The `testnet.aranguren.org` server is back up, closing.

**Comment by craigraw** [comment]
Added an additional testnet public server in afed5c65.
