### ISSUE TITLE
Mix to - Minimum mixes - not sending coins

### ISSUE THREAD

**Issue by Smiggel** [sparrowwallet/sparrow#1114]
I noticed that on the latest version of Sparrow, the Bitcoin is not send to the wallet set in the mix to settings, when the coins are mixed. I reached the minimum 2 times now, and they still are not send. I have update the minimum amount of mixes twice and restarted the mixing. But the coins still stay in the postmix wallet.

**Comment by craigraw** [comment]
See the docs - there is a 75% chance of mixing out on a new mix after the threshold has been reached.
