### ISSUE TITLE
Whirlpool mixes have stopped working seemingly due to frozen confirmations on 2 UTXOs

### ISSUE THREAD

**Issue by kernowg** [sparrowwallet/sparrow#1115]
I've have two UTXOs for mixes showing partial confirmations in the Transactions wallet since 9/17, one at 1 confirmation and the other at 3. There's been no more confirmations since so they seem stuck, however the rest of the UTXOs in postmix won't mix now (they keep trying but I just just get the little red "!" icon next to each UTXO). Any ideas how to fix this please? Thank you.

**Comment by rapidlab309** [comment]
Sparrow uses the Samourai's Whirlpool coordinator. If you have any troubles with it, you will be able to find answers in their support:
Telegram: @SAMOURAI_SUPPORT_BOT
Email: help@samourai.support
Chat: samourai.support

Hovering the red mark will indicate and give you more info about the reason a particular UTXO fails to whirlpool.

**Comment by kernowg** [comment]
Thanks, I'll try that

**Comment by craigraw** [comment]
It appears you have issues connecting to whatever Electrum server you are using, or the server itself is playing up. There is no other reason for confirmations not to increase with every new block.
