### ISSUE TITLE
Fee range defaults to mainnet rate when on testnet

### ISSUE THREAD

**Issue by tcharding** [sparrowwallet/sparrow#1116]
When running `sparrow` on testnet and creating send transaction the fee range bar defaults to a value that appears to be coming from mainnet.

I noticed this because I had 1000 sats in a test wallet and when attempting to send the `max` button was greyed out. Any value I entered was also not accepted. Took me a little while to realise that the fee was set high so that 1000 sats wouldn't cover the fee. Obviously if I had looked down the screen straight away I would have seen this but I just blocked trying to solve the amount field problem.

Perhaps sparrow should default to 1 sat/byte when running the wallet on testnet?

Thanks!

**Comment by craigraw** [comment]
It's actually not defaulting to the mainnet rate, but rather we are in one of the occasional testnet blockstorms which is causing Bitcoin Core to mis-estimate fee rates. Specifically, on my testnet node, I see:
```
bitcoin-cli estimatesmartfee 1
{
  "feerate": 0.00067350,
  "blocks": 2
}
```

This means Bitcoin Core is estimating 67 sats/vb to get into the next testnet block, which is obviously incorrect. See this for why testnet occasionally experiences these blockstorms: https://bitcoin.stackexchange.com/a/77902/96073. 

You can configure Sparrow to just use 1 sat/vb always in the General Preferences - probably a good idea in testnet.

**Comment by tcharding** [comment]
Ah cool, thanks for the lesson.
