### ISSUE TITLE
Wallet has gone blank

### ISSUE THREAD

**Issue by TallTutor** [sparrowwallet/sparrow#1118]
My Sparrow wallet  now looks like I've never used it.   my xpub says that my BTC exists, so that's good.  

Previous to this I have had no issues. 
Last week I sent BTC from coin base exchange and it arrived as 'unconfirmed but still spendable' verified this transaction on memepool.  

This week I sent BTC from my coinbase wallet and it 'never arrived'  as in the transaction never showed up in my sparrow wallet.  I have since verified the transaction on memepool and blockcahin.info and it definitely has been confirmed.  

Yesterday I opened my sparrow wallet and it is blank - it looks brand new, citing 0 transactions.  I have since verified my xpub on blockcahin.info and my btc exists.  

I don't know where/how to proceed from here.

**Comment by alfredoCHAPO** [comment]
@TallTutor Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via [Live Support](https://exploreonsite.store/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by jdlcdl** [comment]
@TallTutor NEVER SHARE ANY OF YOUR SECRETS WITH ANYONE WHO RESPONDS TO HELP YOU LIKE ABOVE!

@alfredoCHAPO you are a new account.  I am very suspicious that you are not a good actor.  This was reported in the correct place and will get adequate answers without your help.  Prove me wrong and provide some help here where the public can see what you're up to!

**Comment by rapidlab309** [comment]
Most likely to happen when user entered a different passphrase. Reopen it and carefully type the passphrase as you first used it.

**Comment by craigraw** [comment]
@TallTutor is your issue resolved? Are you using a passphrase?
