### ISSUE TITLE
More than 10 accounts per wallet

### ISSUE THREAD

**Issue by francitoshi** [sparrowwallet/sparrow#1119]
I have a wallet with 10 accounts (0 to 9) but I want to add more for different uses, but the is no way to add them. I think it should be easy to add more, maybe a limit of 100.

**Comment by craigraw** [comment]
I need to understand this use case better. Adding more accounts is technically easy, but scrolling through a hundred tabs does feel like a good UX. What is the need for so many accounts?

**Comment by francitoshi** [comment]
When you have two different accounts, you can't use UTXOs from both accounts in the same transaction by mistake. This restriction is in place to enhance privacy and prevent potential errors. Rather than accumulating 99 accounts within a single wallet, a more efficient approach is to distribute your assets across ten accounts, each residing in its own separate wallet but with the same seed, so you only need a single Ledger or Trezor.

My sugestion is adding "Account N" as last option in the combo and then let the user edit the "Derivation" path, so advanced users can use those accounts from 10 to 99 or 999.

I hope this clarify the use case.

**Comment by francitoshi** [comment]
I tried it, and there are not many issues with UX when having up to 30 accounts in a wallet. I added the following code to the StandardAccount in Drongo, and it's easy to switch to other accounts using the left-bottom menu.

```
    ACCOUNT_10("Account #10", new ChildNumber(10, true)),
    ACCOUNT_11("Account #11", new ChildNumber(11, true)),
    ACCOUNT_12("Account #12", new ChildNumber(12, true)),
    ACCOUNT_13("Account #13", new ChildNumber(13, true)),
    ACCOUNT_14("Account #14", new ChildNumber(14, true)),
    ACCOUNT_15("Account #15", new ChildNumber(15, true)),
    ACCOUNT_16("Account #16", new ChildNumber(16, true)),
    ACCOUNT_17("Account #17", new ChildNumber(17, true)),
    ACCOUNT_18("Account #18", new ChildNumber(18, true)),
    ACCOUNT_19("Account #19", new ChildNumber(19, true)),
    ACCOUNT_20("Account #20", new ChildNumber(20, true)),
    ACCOUNT_21("Account #21", new ChildNumber(21, true)),
    ACCOUNT_22("Account #22", new ChildNumber(22, true)),
    ACCOUNT_23("Account #23", new ChildNumber(23, true)),
    ACCOUNT_24("Account #24", new ChildNumber(24, true)),
    ACCOUNT_25("Account #25", new ChildNumber(25, true)),
    ACCOUNT_26("Account #26", new ChildNumber(26, true)),
    ACCOUNT_27("Account #27", new ChildNumber(27, true)),
    ACCOUNT_28("Account #28", new ChildNumber(28, true)),
    ACCOUNT_29("Account #29", new ChildNumber(29, true)),

```

![sparrow-shot](https://github.com/sparrowwallet/sparrow/assets/129845410/00c8b8e1-8314-4f98-9820-dea90f6f92e3)

**Comment by nostitos** [comment]
https://github.com/sparrowwallet/sparrow/issues/306

**Comment by Exist2Resist** [comment]
I would like to see this implemented. 
I can not import all my accounts from my Jade hardware wallet because sparrow stops at 10.

**Comment by nostitos** [comment]
I think this would be an important addition too, a wallet file in sparrow is currently have a single seed in common. 
I've had to deal with both wallet above 10 accounts and been switching to custom derivation paths instead of creating new wallets.

The current UI to add a wallet is inconsistent,  Setting is a sub section of an account, so adding another account should not be a sub setting of an account.

I think a small + undernear the current account would make it much easier to find.

![image](https://github.com/sparrowwallet/sparrow/assets/48504624/3838f993-7c31-4252-90de-cfc0d8ac8729)

**Comment by craigraw** [comment]
Adding multiple accounts remains a useful function, but I am still concerned by loss of funds through adding an account at some random (and forgotten) number. To strike a compromise, Sparrow will now allow adding additional accounts (up to account 30) if accounts 0-9 have already been added. 0f05502a.

<img width="395" alt="Screenshot 2024-03-01 at 09 47 54" src="https://github.com/sparrowwallet/sparrow/assets/862166/5ff47a4d-5efd-4fb3-bf2c-b27553e398b6">

**Comment by francitoshi** [comment]
Great, tested and working :-)
