### ISSUE TITLE
If an XPUB contains the output of a whirlpool mix, allow to remix it even if not from postmix account

### ISSUE THREAD

**Issue by Urban-Hacker** [sparrowwallet/sparrow#1122]
If you have an UTXO from a whirlpool mix, It should be possible to remix it as long as it remains inside whirlpool.

This would enable to easily transfer from xpub to xpub without ever needing to go out of the pools.

IF this feature already exist my bad, because I could not find the button remix on the account in question

**Comment by craigraw** [comment]
While not an unreasonable request on the surface, determining whether a UTXO is actually a postmix output without relying on a derivation path is actually more difficult that it sounds - to be sure it would require deep traversal of the ancestors of that transaction, which would be very computationally intensive. If this was not done, it would be possible to reduce the anonset of a given postmix output by remixing with UTXOs that have not performed (or paid for) the necessary premix step, for example by simply relying on their value to determine if they are in a given pool. The postmix derivation path is a reasonable shortcut for determining inclusion in a pool, along with UTXO value.

**Comment by Urban-Hacker** [comment]
Oh I see, but help me understand, whirlpool would not allow anyway registering an output that is not part of the previous mix. So in theory if we shortly look at the ancestor and determine they are output of whirlpool rounds we could register them correct?

Reducing the anon-set would be anyway prevented by the coordinator, else what would prevent a malicious entity to register bogus UTXO?

**Comment by craigraw** [comment]
Yes, but as a client we'd want to avoid sending bad inputs to the coordinator, which at the least should cause errors. 

Although in theory the coordinator won't know the derivation path of the account the UTXO is coming from, in practice it's too much work for the client to check the UTXO history given the originating premix wallet may not be open. This is the same reason we can't show the actual anonset a UTXO has achieved, and use the mix count as a proxy for it.
