### ISSUE TITLE
[feature] Ability to blacklist a receive address

### ISSUE THREAD

**Issue by BarefootJohn** [sparrowwallet/sparrow#1127]
I would like to blacklist a receive address so I cannot accidentally send anything to it.

What do I expect when blacklisting an address:
- it's never selected by the app and shown in the "Receive" tab
- it's greyed out/disabled (or somehow visually different from others) in the "Addresses" list. Also doesn't have the "Copy..." options in the context menu (right click)
- it's never selected when you send funds from one Sparrow wallet to the other (the "Pay to" dropdown in "Send" tab)
- the address isn't selected if you're "Mixing to..." a Sparrow wallet

### Context
I was doing a P2P trade where the seller was suspicious so I canceled the trade, but he has my receive address. Because of this reason I would like to blacklist this address so I won't use it in the future.
I added a "DO NOT USE - BLACKLISTED" label for myself, but I don't know if Sparrow will ignore this address if I mix or send funds between wallets altho I did fund the next address.

**Comment by craigraw** [comment]
> Sparrow will not select the m address if m+1 has already been used.

Correct - any skipped addresses will never by chosen by the wallet to receive funds.

I am hesitant to implement a 'blacklist' function, since of course there is no way to prevent someone sending to that address outside the wallet, which may be contrary to a naive users expectations.

**Comment by BarefootJohn** [comment]
Ok so if it's skipped when the next address receives funds then blacklist isn't really necessary, especially since you can't actually block it and sending is still possible (like you pointed out @craigraw). I'll use the label like I did now, if needed in the future.
