### ISSUE TITLE
[feature request] indicate duplicated output addresses

### ISSUE THREAD

**Issue by fiatjaf** [sparrowwallet/sparrow#1129]
I was crafting a big transaction with multiple outputs, copying addresses manually from another place and pasting them on Sparrow, but ended up pasting the same address twice and sending some of the funds to the wrong place.

Would be nice if Sparrow could display repeated output addresses in some different color or with a warning sign of some kind, I don't know.

Just a suggestion, feel free to close this if you don't like the idea. Thank you very much for this amazing wallet.

**Comment by craigraw** [comment]
It's a reasonable idea. I can't think of a good use case for sending different outputs to the same address, so a warning seems appropriate.

**Comment by craigraw** [comment]
Added in https://github.com/sparrowwallet/sparrow/commit/9280504f709a7c2867ea8fc281b02e4fc0164027.

<img width="1274" alt="Screenshot 2023-10-12 at 12 36 19" src="https://github.com/sparrowwallet/sparrow/assets/862166/974940e9-65bb-4099-8ed5-44f88f3aa118">
