### ISSUE TITLE
PGP Key expired

### ISSUE THREAD

**Issue by mariusb** [sparrowwallet/sparrow#1130]
Craig it seems your PGP key "D4D0 D320 2FC0 6849 A257  B38D E946 1833 4C67 4B40" has expired on 3 October 2023 @ 15:04
<img width="430" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/678525/91ea26f8-573f-45aa-8ab7-19a8850d11a2">

**Comment by craigraw** [comment]
Yes, key expiry is normal and the key has been updated some weeks ago.

The key id remains the same: D4D0D3202FC06849A257B38DE94618334C674B40. 

Running curl https://keybase.io/craigraw/pgp_keys.asc | gpg --import will import the updated key, as per the normal verification instructions.

**Comment by nbourbon** [comment]
thanks! updated now.
