### ISSUE TITLE
[Feature Request] Allow to send to Scripts

### ISSUE THREAD

**Issue by jaonoctus** [sparrowwallet/sparrow#1132]
Electrum wallet allow us to send to any script; eg:

`OP_RETURN 68656c6c6f20776f726c64`

![image](https://github.com/sparrowwallet/sparrow/assets/7918067/35ac9f76-2764-485f-99e3-2c3940602c56)

**Comment by craigraw** [comment]
I really dislike the Electrum UI here - hopefully that doesn't explanation.

Regarding OP_RETURN, see #97. I am still not seeing a good reason to change the UI (read: make it more complex) to implement this. 

Closing as duplicate.
