### ISSUE TITLE
Question about wallet password

### ISSUE THREAD

**Issue by nailiujac** [sparrowwallet/sparrow#1133]
My question is about the password that can be added when creating a new wallet. The question is whether this password is used to encrypt the wallet's information (transactions, UTXOs, labels), or if it is only used to access the wallet.

In case it is the latter option, do you plan to add functionality to allow encrypting the wallet information stored by Sparrow? I do this using a bash script that runs before start and after close Sparrow (to decrypt and encrypt respectively) starting, but it would be great if it were a native option.

Thank you

**Comment by craigraw** [comment]
It is the former - the wallet file is encrypted by the password.
