### ISSUE TITLE
Bug while exporting keys as xprv/zprv?

### ISSUE THREAD

**Issue by FeatureSpitter** [sparrowwallet/sparrow#1136]
So, I created a new wallet:
![image](https://github.com/sparrowwallet/sparrow/assets/39516190/1c817f1c-a3d9-422a-87a7-d11195e092a0)

The wallet is happy and this is its xpub key and fingerprint:
![image](https://github.com/sparrowwallet/sparrow/assets/39516190/6f0bc8eb-55fe-484d-82ff-c1cedcf8f8a7)

One day I decided to export the private key, so I did as Electrum:

```
{
  "keystore": {
    "xpub": "zpub6rgGh4Q21dLzrac8fqhtCubP5JpfDSf6BJLyJKjfn3D2ojp56PFn7nD7pwVRMtJk9EkkFDW4UrGeDWyFnBfptgvC8uvjWY6PoutNMLwzTyu",
    "xprv": "zprvAY3WiCK4YLmi4neGTqnauNMd8cFLhobtcP3ANMi4CtbLeCeVRzRWCw9qivm3stUnXQ3hwDfCSBzY5qUWcLeatCjadMLmaebwR2fS2suNaHL",
    "type": "bip32",
    "pw_hash_version": 1
  },
  "wallet_type": "standard",
  "use_encryption": false,
  "seed_type": "bip39"
}
```

I now have this nice little key:
```
zprvAY3WiCK4YLmi4neGTqnauNMd8cFLhobtcP3ANMi4CtbLeCeVRzRWCw9qivm3stUnXQ3hwDfCSBzY5qUWcLeatCjadML
```

I then try to import this key on other tools and learn that its Master Fingerprint doesn't match the one shown by Sparrow.

To avoid going insane, I create a drafty nodeJs script that parses the key, and shows its parameters [as per my understanding of the specification](https://en.bitcoin.it/wiki/BIP_0032#Serialization_format):

```
const bs58check = require('bs58check')


function arrayToHex(array) {
  return Array.from(array, byte => uint8ToHex(byte));
}

function uint8ToHex(byte) {
  return ('0' + (byte & 0xFF).toString(16).toUpperCase()).slice(-2);
}

function uint32ToHex(byte) {
  return new Array(uint8ToHex(byte >> 24) ,
          uint8ToHex(byte >> 16) ,
          uint8ToHex(byte >> 8) ,
          uint8ToHex(byte >> 0));
}

const decodeExtendedKey = (key) => {
  const decoded = bs58check.decode(key)

  return {
    receivedSequence: arrayToHex(decoded),
    version: decoded.slice(0, 4),
    depth: uint8ToHex(Buffer.from(decoded.slice(4, 5)).readUInt8(0)),
    parentFingerprint: arrayToHex(decoded.slice(5, 9)),
    childNumber: uint32ToHex(Buffer.from(decoded.slice(9, 13)).readUInt32BE(0)),
    chainCode: arrayToHex(decoded.slice(13, 45)),
    key: arrayToHex(decoded.slice(45))
  }
}

const parseVersion = (version) => {
  switch(arrayToHex(version).join('')) {
    case '02AA7A99':
      return 'Zprv';
    case '02AA7ED3':
      return 'Zpub';
    case '04B2430C':
      return 'zprv';
    case '04B24746':
      return 'zpub';
    default:
      return 'Unknown';
  }
}

const key = 'zprvAY3WiCK4YLmi4neGTqnauNMd8cFLhobtcP3ANMi4CtbLeCeVRzRWCw9qivm3stUnXQ3hwDfCSBzY5qUWcLeatCjadMLmaebwR2fS2suNaHL'
const decodedKey = decodeExtendedKey(key)
const version = parseVersion(decodedKey.version)

console.log(`Version: ${version}`)
console.log(`Depth: ${decodedKey.depth}`)
console.log(`Parent Fingerprint: ${decodedKey.parentFingerprint}`)
console.log(`Child Number: ${decodedKey.childNumber}`)
console.log(`Chain Code: ${decodedKey.chainCode}`)
console.log(`Key: ${decodedKey.key}`)
console.log(`Received Sequence: ${decodedKey.receivedSequence}`)
```

This is the output, and indeed the fingerprint lost its finger:
```
Version: zprv
Depth: 00
Parent Fingerprint: B9,40,6D,D9
Child Number: 80,00,00,00
Chain Code: 83,DB,ED,BE,2D,BF,D2,68,FA,50,88,9D,DD,45,F8,EA,98,A4,05,D8,5C,7E,94,6B,6D,93,F2,8E,AD,54,39,5C
Key: 00,78,1A,74,D0,AA,4F,64,94,14,9A,52,E8,70,40,1C,51,29,C8,30,33,51,3C,78,30,88,D6,E2,81,EB,14,0A,AB
Received Sequence: 04,B2,43,0C,00,B9,40,6D,D9,80,00,00,00,83,DB,ED,BE,2D,BF,D2,68,FA,50,88,9D,DD,45,F8,EA,98,A4,05,D8,5C,7E,94,6B,6D,93,F2,8E,AD,54,39,5C,00,78,1A,74,D0,AA,4F,64,94,14,9A,52,E8,70,40,1C,51,29,C8,30,33,51,3C,78,30,88,D6,E2,81,EB,14,0A,AB
```

This is me now:
![image](https://media.tenor.com/JvAXZIFyE7MAAAAC/fetal-position-sad.gif)

**Comment by FeatureSpitter** [comment]
@craigraw can you have a look plz?

**Comment by craigraw** [comment]
How are you exporting the xprv/zprv from Sparrow?

**Comment by FeatureSpitter** [comment]
@craigraw this way:

Settings > Export (button) and then I select this:

![image](https://github.com/sparrowwallet/sparrow/assets/39516190/d2a8e716-2eff-4b92-af8d-92ddae3321ef)

**Comment by FeatureSpitter** [comment]
@craigraw You can download this test wallet from here:
https://www.dropbox.com/scl/fi/pn0gvpjkd6v0avdn4xwrg/ubitcoin.mv.db?rlkey=8f4mwkxkj4s8zsus6z2qymfzc&dl=1

Passphrase: `xxxxxx`

But if you create your own P2WPKH single or multisig wallet, you'll probably face this strange behavior as well.

**Comment by craigraw** [comment]
I believe you are regarding the `zprv` in the Electrum export file as the master `zprv` of the wallet, where it is in fact the derived `zprv` at the derivation path in the Sparrow wallet file. The fingerprint in this `zprv` is the fingerprint of it's parent key, which in this case is not the master extended private key.

You might ask why Electrum expects this derived `zprv` and not simply the BIP39 seed, but that is due to their lack of desire to support the BIP39 standard in favour of their own Electrum Seed Version System.

**Comment by FeatureSpitter** [comment]
@craigraw hmm, if that's the case, how can I extract from Sparrow the master XPRV?

**Comment by craigraw** [comment]
> hmm, if that's the case, how can I extract from Sparrow the master XPRV?

There is no feature in Sparrow for this currently, unless the software was created with an `xprv`. Deriving the `xprv` from seed is possible with a number of online tools though, like https://bitcoiner.guide/seed/.
