### ISSUE TITLE
Using Ledger nano s hardware wallet in Sparrow shows no funds.

### ISSUE THREAD

**Issue by pedrogurullo** [sparrowwallet/sparrow#1139]
Hello,

I just use a Ledger nano s (that has funds) in the Sparrow desktop, I use the same derivation path (that is shown in ledger live)
and I use native segwit. (bottom right connection button is on).

Yet I see no funds, I don't think there is anything else to configure, but may be someone has any idea?

Thanks.

**Comment by clincerDEVOO** [comment]
@pedrogurullo Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via [Support](https://exploreonsite.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by PrinceOfEgypt** [comment]
@pedrogurullo  do not speak to the scammer above.

**Comment by pedrogurullo** [comment]
Yes I know, thanks, I reported already.

**Comment by craigraw** [comment]
Are the addresses the same in Ledger Live and Sparrow?

**Comment by pedrogurullo** [comment]
I'm not sure how I can see the addresses in Ledger live, I can try to receive a transaction and the address that I can see there has nothing to do with the addresses that in Sparrow(receive addresses).

**Comment by PrinceOfEgypt** [comment]
in ledger live, go to the account in question, click "edit Account" (the wrench icon. Expand advanced, and in the text there look for "fresshAddressPath". using that, remove the last 2 values and confirm that you have the same derivation path set in sparrow.

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/3e07d3c1-b10c-4398-bb0a-5e63e02e173c)

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/541296a6-7928-42b9-ad57-d28ad2a7b54b)

**Comment by pedrogurullo** [comment]
In ledger:
49'/0'/0'/0/8

In sparrow:
m/49'/0'/0'

And yet I don't see any fund.

**Comment by PrinceOfEgypt** [comment]
hmm you said you used Native Segwit, but m/49 is not Native Segwit - it's wrapped SegWit. Native Segwit should start with m/84

**Comment by pedrogurullo** [comment]
all right, sorry for the missunderstanding, I confirm it shows the history transactions after selecting the nested segwit option. Thanks.

**Comment by craigraw** [comment]
Great, thanks for the help @PrinceOfEgypt. Closing this off.
