### ISSUE TITLE
[Feature] Highlight BOLD, input and outputs that belong to us.

### ISSUE THREAD

**Issue by nostitos** [sparrowwallet/sparrow#1140]
![image](https://github.com/sparrowwallet/sparrow/assets/48504624/bb7a20dd-6f15-4952-a9b8-b64b66544ed6)

Example: 

<img width="897" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/48504624/948300a6-9365-44d2-880f-389a2e00c67e">

**Comment by craigraw** [comment]
It's not a bad idea, but the system font used in the UI does not necessarily have a bold option. There might be another way to do this though.

**Comment by Enfernuz** [comment]
I believe it has been actually implemented, via icons:

![sparrow](https://github.com/sparrowwallet/sparrow/assets/935535/711358cb-7f50-442d-884d-96d3cc75f363)

**Comment by craigraw** [comment]
Indeed, thanks for point this out @Enfernuz. Closing this off.
