### ISSUE TITLE
[Feature] Adding support for importing Samourai.txt archive to Sparrow wallet

### ISSUE THREAD

**Issue by 4rkad** [sparrowwallet/sparrow#1142]
Many Samourai users mix in Whirpool, and after some time, they wish to use the feature "Mix to". To do this, they have to import the seed into Sparrow. Could be possible to add the feature to import the samourai.txt into Sparrow wallet, in order to avoid writing the words in the computer?

**Comment by 4rkad** [comment]
Samourai.txt is encrypted with the passphrase.
You would import the archive in Sparrow and you would decrypt with the password.
At least you are not exposing your 12 words directly.
Sparrow has support to import several kind of wallets, why not samourai.txt?

**Comment by craigraw** [comment]
Indeed, can't see any reason not to support this as an import format. @4rkad Is there any documentation on it, specifically the encryption used and format of the unencrypted data?

**Comment by 4rkad** [comment]
Did Tdev contact to you for this issue?

**Comment by craigraw** [comment]
We haven't spoke about this, no - just need a link to the source for the decryption algorithm though.

**Comment by 4rkad** [comment]
Reminder sent to Tdev.

**Comment by craigraw** [comment]
Implemented in d68ab40c. Sparrow now imports Samourai wallet backups via the File > Import Wallet menu.
