### ISSUE TITLE
Tor Proxy - external connections

### ISSUE THREAD

**Issue by TinF0ilHat1** [sparrowwallet/sparrow#1144]
To reach .onion private electrum server Sparrow can either use it's own tor proxy or an external one - if `Use Proxy` is toggled.

 If i am connected to my fulcrum server over SSL clearnet and i use Whirpool, Sparrow does not start its own `Tor Proxy` - meaning it is reaching Whirpool server in clearnet?
However user can still toggle `Use Proxy` to relay on it's own tor daemon; the onion symbol appears on the bottom right.

1. Does this suffice to reach Whirpool through TOR? How (if) can i check it? 
As for this #557: 
Is this http://udkmfc5j6zvv3ysavbrwzhwji4hpyfe3apqa6yst7c7l32mygf65g4ad.onion/rest/pools/ the [only] address Sparrow use to reach Whirpool?
1.1 When using `SSL clearnet + Use proxy: true`  specically on **Sparrow server** i can only see `connected at 1234`. Can something like `External proxy enabled`  be added; if the onion symbol is hard to get into terminal?

3. Could Whirpool be hardcoded to be reachable only over TOR? 
2.1 If the idea  that a trustworthy VPN can be enough while allowing better performances when mixing, can a toggle be   implemented such that you define if external connections can occur without TOR?  `Tor only for external connections: true; false
` 

4. How exactly Sparrow handles connections?  I though It queries the server (Fulcrum) in LocalHost to switch to TOR to reach external services. 
As for this #557: Is this http://udkmfc5j6zvv3ysavbrwzhwji4hpyfe3apqa6yst7c7l32mygf65g4ad.onion/rest/pools/ the [only] address Sparrow use to reach Whirpool?

**Comment by craigraw** [comment]
1. Yes. I will look at adding some kind of proxy indicator to Sparrow Terminal.
2. No - it is my intention that Sparrow does not become dependant on Tor. Alternatives for privacy do exist, and Tor is not 100% reliable.
3. Correct, all external services will only be connected to via Tor if it is configured. See https://sparrowwallet.com/docs/faq.html#how-does-the-proxy-support-work. The address Sparrow uses to connect to Whirlpool depends if Tor is in use or not.

**Comment by craigraw** [comment]
Implemented in d881e47e.

<img width="992" alt="Screenshot 2023-10-31 at 10 36 34" src="https://github.com/sparrowwallet/sparrow/assets/862166/6de405f3-4339-4af2-a350-67285524a033">
