### ISSUE TITLE
Sparrow Server: Freeze UTXO

### ISSUE THREAD

**Issue by TinF0ilHat1** [sparrowwallet/sparrow#1145]
As for now, if i am not wrong, UTXO's can not be freezed like they can on GUI. 
Is this something that can be implemented? 

As a workaround: Where the indications of `address + freeze:true;false` are stored? i was thinking if it's stored in the wallet.db.mv users can easily `scp` the wallet file to the server.

**Comment by craigraw** [comment]
Duplicate of #901 - but recently implemented :)
