### ISSUE TITLE
Error loading transactions: Failed to subscribe to paths:[m/1/0-m/1/19]

### ISSUE THREAD

**Issue by beezneez23** [sparrowwallet/sparrow#1146]
Imported wallet from Trezor - it has generated a different xpub to the original wallet. Also does not download any transactions. I looked at the log and see this message: Error loading transactions: Failed to subscribe to paths:[m/1/0-m/1/19]

I chose derivation path m/84'/0'/0' which I think is the same as the Trezor. Since I noticed on FAQ that Trezor may use nested segwit, I created a new wallet with a different name but using m/49'/0'/0'/0/0 - that didn't work either so I deleted this wallet. 

Any suggestions to fix this? Thanks from a befuddled non-techie.

**Comment by beezneez23** [comment]
Note: imported into Sparrow

**Comment by craigraw** [comment]
Try File > Import Wallet > Scan for connected devices > Discover (when the Trezor appears in the list of import options). This will look across script types and derivation paths.

Closing as this is a support request - rather use the Telegram group.

**Comment by beezneez23** [comment]
Thank you - will join the Telegram group - please let me know what to search for to join the right group.

**Comment by craigraw** [comment]
Here's the link: https://t.me/SparrowWallet

Make sure you solve the loading issues too - these are a separate concern.

**Comment by beezneez23** [comment]
thank you - will work on it.

------- Original Message -------

**Comment by beezneez23** [comment]
Yeah, it worked. So I have a new wallet for the Trezor on Sparrow - it imported one hidden wallet on the trezor but not another one. Do I need to set up a new import wallet for this? Or is there a way to import the transactions on the one just imported as it is the same Trezor device?
So grateful for your help.

------- Original Message -------

**Comment by craigraw** [comment]
You'll either need a new wallet, or a new account on the existing wallet. Try Add Account > Account 1. If that doesn't work, you'll need to experiment with other script types. Ask on the group if you need further assistance.

**Comment by beezneez23** [comment]
Thanks again for your help. It turns out that I needed to set up a new wallet on Sparrow to import the second wallet from Trezor.

**Comment by beezneez23** [comment]
Hello
I was able to see posts on the Telegram site using this link - just tried to access it again to ask a question, but now I get the message that it's a private group. Do I need an invitation to join? Thanks.
------- Original Message -------

**Comment by craigraw** [comment]
What is your Telegram handle?

**Comment by beezneez23** [comment]
Thanks - telegram group handle is, I think:

Lotus ***@***.***_dishes

------- Original Message -------

**Comment by craigraw** [comment]
I see a Lotus Flower, or Lotus Flowers - is it either of these?

**Comment by beezneez23** [comment]
Lotus Flower

I think 🤔

**Comment by craigraw** [comment]
Ok you can try again. Make sure you are not in any of the other scam SparrowWallet groups.

**Comment by beezneez23** [comment]
Thank you- yes, I did see those other groups and was wondering if they were legit. Glad to know you’re the real deal.
