### ISSUE TITLE
add option to set port for personal mempool instance

### ISSUE THREAD

**Issue by zerotrust-community** [sparrowwallet/sparrow#1148]
`hi, maybe it's already implemented, but when i tested, personal mempool not worked with sparrowwallet if i had in URL port`
![image](https://github.com/sparrowwallet/sparrow/assets/148634618/b00fb9f2-bb4c-4ce3-a9c9-a904467e165f)
`i have own mempool configured, and default port is not 443, can you add option to configure with custom port?`

**Comment by craigraw** [comment]
It is already implemented. Just retested it, and it's working fine.
