### ISSUE TITLE
For UTXO Management add a Fiat valuation of the UTXO

### ISSUE THREAD

**Issue by Richie-BTC-Rich** [sparrowwallet/sparrow#1151]
Would it be possible to have some sort of Toggle or Option on the UTXOs tab that would allow you to see the Sats Value in fiat ?  This would help in UTXO consolidation, especially with those that might of  been DCAing small sat amounts into their wallets or people who just want to organize their UTXO set into various fiat denominations. 

Waiting for the day when my grocery store has Sats shelf tags so I know what Sats number is in terms of a price of a apple, etc. But until then its a Fiat world unfortunately.

**Comment by craigraw** [comment]
Please see https://github.com/sparrowwallet/sparrow/issues/1095#issuecomment-1712950736

**Comment by Richie-BTC-Rich** [comment]
I respect that, Thanks for your comment
