### ISSUE TITLE
silent mixing UI failure when using "wrong" derivation account order

### ISSUE THREAD

**Issue by Hoernchen** [sparrowwallet/sparrow#1152]
Trying to mix does not ask for a password or switch to the "send" window, nothing happens if you accidently do this, the mixing popup just disappears after clicking on "preview premix":

- create a new wallet
- accidentally use derivation #\1 for your "first" account
- notice the error, add #0 account
- use #0 to receive funds, try to mix

solution (since deleting #\1 is not possible to reorder the accounts): recreate the wallet using the mnemonic words -> mixing works as expected.

I would have expected some sort of error message, the problem is the silent failure.

**Comment by craigraw** [comment]
Thanks for the bug report. Fixed in 218e7513.

<img width="472" alt="Screenshot 2023-11-08 at 12 25 37" src="https://github.com/sparrowwallet/sparrow/assets/862166/12d43eef-5bd0-4efc-86fb-6066f8a34f63">
