### ISSUE TITLE
Sparrow 1.8.0 does not connect to the Bitcoin node via electrs

### ISSUE THREAD

**Issue by yusoy** [sparrowwallet/sparrow#1156]
With RaspiBlitz v1.9.0, Sparrow 1.8. It does not connect through electrs:
"Error getting fee estimates for target blocks"
I mean, it doesn't connect to Rasp on a local network, nor through Tor remotely...
With Sparrow v1.7.9-1 yes, in both cases.

**Comment by craigraw** [comment]
There have been no changes from v1.7.9 to v1.8.0 I can think of that would affect this - and I would expect it to have been widely reported already if there was a problem. Can you test again? What version of Electrs are you connecting to?

**Comment by yusoy** [comment]
Sorry for the delay, you know the time...and the work.
In raspiblitz electrs v0.9.11
In VM Proxmox electrs v0.9.13

**Comment by craigraw** [comment]
See #899 - I suspect this is a server hardware related issue, where Bitcoin Core can't handle certain requests as the mempool fills up. Can you try making  the following requests directly to your node?

```
bitcoin-cli estimatesmartfee 1
bitcoin-cli estimatesmartfee 10
bitcoin-cli estimatesmartfee 50
```

They should return almost instantly.

Also, please take a look in sparrow.log (Help menu) and report any related errors you see there - and anything from the electrs log file.

**Comment by yusoy** [comment]
I just reinstalled v1.8.0 and it works!!!!
I really don't know what happened...I'll look at the logs.
Thank you.
I close the issue
