### ISSUE TITLE
Sparrow Terminal is sending clearnet DNS Querys to mempool and Coingecko (with local TOR proxy enabled)

### ISSUE THREAD

**Issue by lamanetwork** [sparrowwallet/sparrow#1158]
You can rebuild this behavoir like i did see Testconfiguration below

**Behavior: The Proxy is working fine, except follow DNS Querys (see below). These are still going out to the GW Address/Clearnet. Seems like a Bug to me**

Setup:

192.168.0.1 GW (Router)
192.168.0.2 sparrow Terminal + local Tor listening on 9050
192.168.0.3 Fulcrum (ElectrumServer)
Settings Sparrow
Private Electrum
URL: 192.168.0.3:50002
Use SSL Yes
Use Proxy Yes
Proxy: 127.0.0.1:9050

sudo tcpdump -i eth0 -n -vv port not 22 and host 192.168.0.1 and port 53
14:53:18.229042 IP (tos 0x0, ttl 64, id 5673, offset 0, flags [DF], proto UDP (17), length 108)
    192.168.0.2.50629 > 192.168.0.1.53: [bad udp cksum 0x1591 -> 0xa708!] 59266+ A? mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion. (80) <- ipv4 DNS request for the onion Adress from my eth0 to my router
14:53:18.229083 IP (tos 0x0, ttl 64, id 5674, offset 0, flags [DF], proto UDP (17), length 108)
    192.168.0.2.50629 > 192.168.0.1.53: [bad udp cksum 0x1591 -> 0xf3e7!] 39560+ AAAA? mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion. (80) <- ipv6 DNS request for the onion Adress from my eth0 to my router
14:53:18.242671 IP (tos 0x0, ttl 64, id 33033, offset 0, flags [none], proto UDP (17), length 136)
    192.168.0.1.53 > 192.168.0.2.50629: [udp sum ok] 39560- q: AAAA? mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion. 1/0/0 mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion. AAAA 2620:101:9000:53::55 (108) <- ipv6 DNS respone for the onion Adress
14:53:18.243912 IP (tos 0x0, ttl 64, id 33034, offset 0, flags [none], proto UDP (17), length 124)
    192.168.0.1.53 > 192.168.0.2.50629: [udp sum ok] 59266- q: A? mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion. 1/0/0 mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion. A 208.91.112.55 (96) <- ipv4 DNS respone for the onion Adress

15:10:41.425030 IP (tos 0x0, ttl 64, id 63074, offset 0, flags [DF], proto UDP (17), length 63)
    192.168.0.2.38278 > 192.168.0.1.53: [bad udp cksum 0x1564 -> 0xc48b!] 61062+ A? api.coingecko.com. (35)
15:10:41.425065 IP (tos 0x0, ttl 64, id 63075, offset 0, flags [DF], proto UDP (17), length 63)
    192.168.0.2.38278 > 192.168.0.1.53: [bad udp cksum 0x1564 -> 0xef98!] 43129+ AAAA? api.coingecko.com. (35)
15:10:41.439060 IP (tos 0x0, ttl 64, id 33069, offset 0, flags [none], proto UDP (17), length 316)
    192.168.0.1.53 > 192.168.0.2.38278: [udp sum ok] 43129 q: AAAA? api.coingecko.com. 2/2/7 api.coingecko.com. AAAA 2606:4700::6812:1d78, api.coingecko.com. AAAA 2606:4700::6812:1c78 ns: api.coingecko.com. NS jack.ns.cloudflare.com., api.coingecko.com. NS lucy.ns.cloudflare.com. ar: jack.ns.cloudflare.com. A 108.162.193.121, jack.ns.cloudflare.com. A 173.245.59.121, jack.ns.cloudflare.com. A 172.64.33.121, lucy.ns.cloudflare.com. A 173.245.58.133, lucy.ns.cloudflare.com. A 108.162.192.133, lucy.ns.cloudflare.com. A 172.64.32.133, . OPT UDPsize=4096 (288)
15:10:41.439144 IP (tos 0x0, ttl 64, id 33070, offset 0, flags [none], proto UDP (17), length 292)
192.168.0.1.53 > 192.168.0.2.38278: [udp sum ok] 61062 q: A? api.coingecko.com. 2/2/7 api.coingecko.com. A 104.18.29.120, api.coingecko.com. A 104.18.28.120 ns: api.coingecko.com. NS jack.ns.cloudflare.com., api.coingecko.com. NS lucy.ns.cloudflare.com. ar: jack.ns.cloudflare.com. A 173.245.59.121, jack.ns.cloudflare.com. A 108.162.193.121, jack.ns.cloudflare.com. A 172.64.33.121, lucy.ns.cloudflare.com. A 172.64.32.133, lucy.ns.cloudflare.com. A 108.162.192.133, lucy.ns.cloudflare.com. A 173.245.58.133, . OPT UDPsize=4096 (264)

**Comment by craigraw** [comment]
Thanks for the detailed report. It turns out that Java's internal http client is performing an inadvertent DNS lookup of the provided domain name regardless of whether a proxy is configured or not. I'm switching clients to avoid this issue.

**Comment by lamanetwork** [comment]
> Thanks for the detailed report. It turns out that Java's internal http client is performing an inadvertent DNS lookup of the provided domain name regardless of whether a proxy is configured or not. I'm switching clients to avoid this issue.

Thank you craigraw for your fantastic work so far!

**Comment by craigraw** [comment]
Switched from `HttpUrlConnection` to Jetty `HttpClient` for all external HTTP queries in c81c42a8. Using Wireshark, I now can't see any DNS queries when a Tor proxy is configured.

**Comment by learnwayback** [comment]
When only socks5 is available to sparrow (no other network path) then all name resolution of public and private electrum servers fail:

"Failed to resolve address"

doesn't look like whatever sparrow is using can be trusted not to leak dns?
