### ISSUE TITLE
Creating CPFP transaction not possible

### ISSUE THREAD

**Issue by lasermind** [sparrowwallet/sparrow#1159]
Could it be that I completely don't know what I'm doing, or is there a problem in Sparrow ...? 😳

I have an unconfirmed transaction in my wallet and I wanted to create a CPFP transaction, like so:

![transactions-unconfirmed](https://github.com/sparrowwallet/sparrow/assets/126513496/bc162920-8da0-4b6c-b5e5-542207798deb)

The screen then switches to the send tab, pre-fills the next address, gives label "(CPFP)" and: tells me that there are insufficient funds due to "insufficient confirmed transaction value".

<table>
<tr>
<td>

![send-insufficient-tooltip](https://github.com/sparrowwallet/sparrow/assets/126513496/d34bab57-c1b6-403b-a2b4-06c1f5dab261)

</td>

<td>

[send-insufficient.webm](https://github.com/sparrowwallet/sparrow/assets/126513496/e7a3e92c-ffca-42be-9c4c-03411c4899ee)

</td>
</tr>
</table>

Now that confuses me. In my opinion, the whole point of a CPFP transaction is, to use the output of a *still unconfirmed* transaction to construct a new one – and thus be able to bump fees. Why is Sparrow complaining that it *is* unconfirmed then?

Did I get this wrong somehow?
Are there certain boundaries only within a CPFP transaction can be constructed?

The unconfirmed transaction looks like this:

![tx-graph-annoted](https://github.com/sparrowwallet/sparrow/assets/126513496/000d08fe-31ba-4aa1-9c02-1e42c80c4f82)

I'm trying to spend `my output` and I can assure you, that there *are* sufficient amounts on it; more than I used as my demo values above.

Is there something wrong in Sparrow? I use the freshly released v1.8.0, but also tested with an older 1.7.1: same behaviour.

**Comment by craigraw** [comment]
The current fee rates may mean more fee is necessary than what you are expecting.

My suggestion is to select the UTXO, and another one or two in the UTXOs tab and Send Selected, which does the same thing. Or, use the CPFP function and adjust the fee rate slider downwards until the transaction is possible.

**Comment by lasermind** [comment]
Thanks! But I doubt that the amount is too low to cover even current fees. Even if, I should be able to construct this transaction, shouldn't I?

Have you watched the little video, where I used the CPFP tool and pulled the slider? The slider does not change the numbers at all. As if the UI is broken. 

Also in the UTXO tab, the unconfirmed transaction is marked as "not yet spendable". Is it supposed to be? How do you determine whether that label should be there?

![utxo-nys](https://github.com/sparrowwallet/sparrow/assets/126513496/2d20f691-6b6e-4d19-a788-fa9e11f6e26c)

**Comment by craigraw** [comment]
Have you disabled the toggle for Allow Unconfirmed in the Preferences? Either that, or perhaps frozen this UTXO?

**Comment by lasermind** [comment]
Lo and behold, now this was the culprit!

After enabling this toggle, it suddenly works. 😉 I had no idea that this toggle exists, unbelievable. 😶


![image](https://github.com/sparrowwallet/sparrow/assets/126513496/ba05b5bc-4bff-4cf7-b03a-64b2fd943bd6)

Thanks! 👍


Maybe we should treat this as a quick heads-up, that the CPFP tool should react in a slightly different way. Even a little hint in the tooltip, which appeared, would have pointed me in the right direction to figure this out.

My suggestion would be, to have the CPFP icon also greyed out, maybe with a little note. Or have a message in the spend tab, that the toggle in the preferences will prevent a user from constructing a transaction here. But as of now, a semi-broken UI is probably not a good middle ground.

Anyway: thanks for your help and thanks for your awesome work on Sparrow Wallet!

**Comment by craigraw** [comment]
Error dialog added in a5312374.

<img width="472" alt="Screenshot 2023-11-13 at 14 36 44" src="https://github.com/sparrowwallet/sparrow/assets/862166/afd1e3d6-20ff-4faa-9076-a6cb9b2775ad">
