### ISSUE TITLE
UI bug: receive address table goes blank

### ISSUE THREAD

**Issue by tychsen** [sparrowwallet/sparrow#116]
Reproduce case:

1. Go to "Addresses" tab to ascertain the list of receive adresses are shown. Remember the last one in the list. Scroll to the top of the list before step 2.
2. Go now to the "Receive" tab and press "Get New Address" enough times to be sure you exceed the addresses already shown in previous list. Go past last address you remembered.
3. Go to "Addresses" tab again. List is empty (until scroll).

![empty](https://user-images.githubusercontent.com/42609900/116779812-d0c06800-aa78-11eb-8d54-09048f2c81e9.png)

**Comment by craigraw** [comment]
Fixed in c067300.

**Comment by tychsen** [comment]
Thanks... you are on fire man !
