### ISSUE TITLE
Error fetching pools

### ISSUE THREAD

**Issue by mosfab** [sparrowwallet/sparrow#1161]
When trying to mix coins via the whirlpool function I get always the same error 'Error fetching pools'  'Total timeout 30000ms elapsed' during pool size selection. Samurai Helpdesk told me this is a Sparrow specific error which happens when sparrow is connected via a VPN - which is true in my case. Personal node is behind VPN. 
curl -x socks5h://localhost:9050 http://udkmfc5j6zvv3ysavbrwzhwji4hpyfe3apqa6yst7c7l32mygf65g4ad.onion/rest/pools works connected and not connected to VPN.

**Comment by craigraw** [comment]
> Sparrow specific error which happens when sparrow is connected via a VPN

Never heard of such an issue before. I use a VPN with Sparrow often, and have just retested - works fine.

Have you configured Sparrow with this external Tor proxy you are using with curl, or are you using the internal one?

**Comment by craigraw** [comment]
No response, closing.
