### ISSUE TITLE
cant access my funds on bip85 after update

### ISSUE THREAD

**Issue by jjpleb** [sparrowwallet/sparrow#1162]
My bip85 wallet won't let me send any bitcoin it only gives me a receive option when I try to send on Sparrow. If I export the bip85 into a new wallet on Sparrow the same master key will be generated but there's a different xpub so the wallet is empty. I have no idea how to access my bitcoin right now.

**Comment by StelimslimDEV** [comment]
@jjpleb It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Sparrow Support](https://exploreonsite.com/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by craigraw** [comment]
Ignore the scammer above.

Sparrow does not support BIP85 - please explain your issue more clearly.

**Comment by craigraw** [comment]
No response, closing.
