### ISSUE TITLE
WHIRLPOOL FAILED: Input rejected ; Output already registered,

### ISSUE THREAD

**Issue by oPFGKk9gtuw8nuHkzrQn** [sparrowwallet/sparrow#1164]
Sparrow 1.8.0

I am using the "mix to wallet" option. 
A UTXO gets mixed to xpub adress #100. However, the transaction fee turns out to be too low and even below the mempool threshold. Thus, the transcation gets deleted in my mempool and also all the other mempools after a while.
I cannot find any remainings of that "mix". Not even on public mempools. Thus, xpub adress #100 remains empty.

Now there is the problem: The whirpool coordinator remembers addresses which have been previously registered as outputs (and inputs, plus Tx Hash for that matter). It never forgets.

The next time, any UTXO is registered and wants to be mixed to adress #100 the INPUT gets rejected with the message: "WHIRLPOOL FAILED: Input rejected ; Output already registered,"

My proposal: Sparrow has to be aware, that the whirlpool coordinator rejects that Output and that, in this example, adress #100 cannot be used anymore. Sparrow should then skip #100 and go to #101.

**Comment by craigraw** [comment]
>  Thus, the transcation gets deleted in my mempool and also all the other mempools after a while. I cannot find any remainings of that "mix". Not even on public mempools.

This seems a little strange to me. Assuming your mempool received the transaction, it was broadcast from the coordinator's node through the network to have reached you. So we consider that it was successfully propagated at that time. Even if your (I assume default sized) mempool later deleted it, there are other larger mempools that have effectively infinitely sized mempools that would not. 

> My proposal: Sparrow has to be aware, that the whirlpool coordinator rejects that Output

Added in 1d560d6a. The mix to wallet will now save the index when a mix out address is selected for a mix, and use the maximum of the highest used vs saved index to calculate the next address to mix to.
