### ISSUE TITLE
Error getting fee estimates when using own node

### ISSUE THREAD

**Issue by biatwc** [sparrowwallet/sparrow#1165]
Hi there

I have a pruned (prune=150000) bitcoind running which is at tip, and sparrow 1.8.0.
I set up the connection to the node and click test connection, which results in the following:
```
Could not connect:

Error getting fee estimates: {1=ErrorMessage{code=-32603, message=Internal error, data=null}, 2=ErrorMessage{code=-32603, message=Internal error, data=null}, 50=ErrorMessage{code=-32603, message=Internal error, data=null}, 3=ErrorMessage{code=-32603, message=Internal error, data=null}, 4=ErrorMessage{code=-32603, message=Internal error, data=null}, 5=ErrorMessage{code=-32603, message=Internal error, data=null}, 25=ErrorMessage{code=-32603, message=Internal error, data=null}, 10=ErrorMessage{code=-32603, message=Internal error, data=null}}
```
I see no errors in the bitcoind logs and can get info back from other rpc calls like getblockchaininfo, which don't indicate anything is wrong with the node.

Are there particular bitcoind settings which need to be enable to work with Sparrow?

**Comment by craigraw** [comment]
It's clear that Bitcoin Core is running into problems estimating fee rate - probably you would get errors if you tried

```
bitcoin-cli estimatesmartfee 1
bitcoin-cli estimatesmartfee 10
bitcoin-cli estimatesmartfee 50
```

Unfortunately Core doesn't log anything if it has errors on the RPC interface.

I've seen a few of these problems though, so I have made a change where Sparrow will fallback to a default fee rate if this error is encountered. 74c33702.
