### ISSUE TITLE
Cannot find transactions with Output Descriptor "bitcoincore" Export

### ISSUE THREAD

**Issue by swiss-chris** [sparrowwallet/sparrow#1166]
Recently I created a 2-of-2 Segwit Native Multisig (standard derivation path) and created multiple exports / backups. When I import the BSMS backup, Sparrow finds my previous transactions, but when I import the Output Descriptor "bitcoincore" backup, Sparrow says there are not transactions. What's going on ? 

PS: I'm creating these multiple backups for inheritance purposes, so I would like to know that they will work if needed. If they don't see any transactions, they will likely give up and assume there are not unspent transactions in that wallet.

**Comment by craigraw** [comment]
> but when I import the Output Descriptor "bitcoincore" backup, Sparrow says there are not transactions.

I can't recreate this. I have just:
1. Exported a 2-of-2 Native Segwit multisig wallet using the File > Export Wallet > Output Descriptor function
2. Imported the exported file into a new wallet, using File > Import Wallet > Output Descriptor. The wallet was created with the same details, and all transactions loaded successfully.

**Comment by swiss-chris** [comment]
Hi @craigraw 
Thanks for getting back to me on this and sorry for my late reply.
I tried it again and this time it worked. My assumption is that my own node / tor was misbehaving the previous few times I tried (but only with that format for some reason). Next time I'll try with a local Bitcoin Core as Server instead before raising an issue.
Sorry for the false alarm.
