### ISSUE TITLE
Allow to shrink to smaller window size.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#117]
I thought the window was needlessly too big but found it it's caused by opening it on a 4k screen,

Still it should allow to be shrunk to a set minimum that's only resolution based.

![image](https://user-images.githubusercontent.com/388716/116787763-162e6680-aa74-11eb-8df9-83f514738aea.png)

**Comment by craigraw** [comment]
The current minimum resolution height is about 730px (for a 1366 x 768px screen).

I haven't been able to test on a 4k screen with Windows. Is there a problem?

**Comment by Transisto** [comment]
Left side image is on a 1680x1050 screen, right side is on the 4k
Windows is 1270 high on the 4k.

I found a pattern, that's related to the scaling ratio of my 2nd screen.

Both 4k
Primary is scaled 150% the other 100%

The sparrow windows on the 150% show 15 rows of transactions.
on the 100% it shows 30.

So I tried opening it with 350% scaling, 
Cannot make sparrow fits on either screen, both stop at UTXO section on the left.

Opened at 300%, the windows almost fits but the bottom status bar is missing

![image](https://user-images.githubusercontent.com/388716/117040312-be903500-acd7-11eb-8c0a-4eadf0cc3e94.png)

If the windows doest fit bringing back on the 300% scaling does this
![image](https://user-images.githubusercontent.com/388716/117040446-e7182f00-acd7-11eb-90a5-a4e4e7f61862.png)

**Comment by 6102bitcoin** [comment]
Outstanding Action: Propose closing issue (wallet is usable) or assign task to someone who can test on 4K windows & fix.
Proposed Priority: NA

**Comment by craigraw** [comment]
@Transisto does the advice listed here help at all? https://danantonielli.com/app-scaling-on-high-dpi-displays-fix-2019/

**Comment by Transisto** [comment]
> @Transisto does the advice listed here help at all? https://danantonielli.com/app-scaling-on-high-dpi-displays-fix-2019/

Yes that fixed it.

Basically, the app will take a minimum of 2/3 of the screen size.
on a 43 inch 4k monitor it's really big.
