### ISSUE TITLE
Error when starting the application, the wallet is visible

### ISSUE THREAD

**Issue by bitclub21** [sparrowwallet/sparrow#1170]
![sparrow](https://github.com/sparrowwallet/sparrow/assets/151674208/3cbbf23d-ae25-4da0-9400-233386dc0a99)

I have created a new software wallet, in addition to the main one in the tesnet version, and when you go to open the application, without having to enter a password or passphrase, the funds are seen

**Comment by craigraw** [comment]
You are clearly loading two wallets here - one called 'BTCpayserver' and the other 'maxspa'. I assume the former has no password. You can add a password in the Settings tab - see Advanced.
