### ISSUE TITLE
Trezor Safe 3 not compatible

### ISSUE THREAD

**Issue by michalfeher** [sparrowwallet/sparrow#1172]
The newest Trezor model is not compatible with the latest Sparrow version (1.8.1):
[{“type”: “trezor”, “path”: “webusb:001:1", “error”: “Could not open client or get fingerprint information: Unsupported Trezor model”, “code”: -13}]

**Comment by craigraw** [comment]
Support will be required from HWI, the library Sparrow uses to communicate with USB hwws. I have opened an issue there: https://github.com/bitcoin-core/HWI/issues/713

**Comment by craigraw** [comment]
Thanks @abradshaw good to hear. It's also possible to just change the value of the "hwi" entry in Sparrow's config file to point to the new HWI executable. 

I should have a test device soon.

**Comment by abradshaw** [comment]
> Thanks @abradshaw good to hear. It's also possible to just change the value of the "hwi" entry in Sparrow's config file to point to the new HWI executable.
> 
> I should have a test device soon.

That would have been much simpler :smile: 

Which config file is it?

```
rpm -ql ./sparrow-1.8.2-1.x86_64.rpm |grep cfg
/opt/sparrow/lib/app/Sparrow.cfg
/opt/sparrow/lib/runtime/lib/jvm.cfg
```

**Comment by craigraw** [comment]
The one in Sparrow home: https://sparrowwallet.com/docs/faq.html#where-does-sparrow-store-data

In your case, `~/.sparrow` :)

**Comment by abradshaw** [comment]
> The one in Sparrow home: https://sparrowwallet.com/docs/faq.html#where-does-sparrow-store-data
> 
> In your case, `~/.sparrow` :)

Cool and what would the syntax be for setting an alternative HWI ? I searched the doc and I can't see it

**Comment by craigraw** [comment]
Just edit `~/.sparrow/config` (close Sparrow first) and change the path for the `"hwi"` entry in the JSON map.

**Comment by abradshaw** [comment]
> Just edit `~/.sparrow/config` (close Sparrow first) and change the path for the `"hwi"` entry in the JSON map.

I only see 

```
$ grep hwi ~/.sparrow/config
  "hwi": "/tmp/hwi-2.3.19950810487264932437.tmp"
```

Which seems to be copied from somewhere to this location when you start the app?

**Comment by craigraw** [comment]
Yes that's it. Just edit the path to point to your hwi executable elsewhere on your system.

**Comment by craigraw** [comment]
> the only thing I've noticed is that it is detected as "Trezor One"

Detection of the Trezor Safe 3 has been implemented on the Sparrow side in 1ba501f5. Just waiting on the final release of HWI 2.4.0 now.

**Comment by JWelsh97** [comment]
Seems like it's all coming at once, HWI 2.4.0 has now been released

**Comment by craigraw** [comment]
HWI in Sparrow has been updated to 2.4.0, with Trezor Safe 3 support coming in the next release. 31042039.

**Comment by PeteClubSeven** [comment]
Just wanted to confirm that doing the HWI trick with 2.4.0 always works for my Safe 3 on macOS ❤️

**Comment by jlopp** [comment]
Wen next release? I have some testing of Safe 3 to do and can't get Sparrow to work with the latest HWI - making the config file change doesn't seem to have any effect.

**Comment by craigraw** [comment]
@jlopp Soon, but happy to make a beta build for you in the meantime - just let me know OS and arch.

**Comment by jlopp** [comment]
Thanks; looking for x86 64 bit linux. Tried building but got an error; I'll open an issue for that.

**Comment by craigraw** [comment]
@jlopp Here you go: https://github.com/craigraw/beta/releases/tag/1.8.3-safe3-support

**Comment by abradshaw** [comment]
just to follow up - I just installed the latest release (1.8.3) and its now working out of the box :pray:
