### ISSUE TITLE
Not supported by Cobo Vault ？

### ISSUE THREAD

**Issue by wertaaaaex** [sparrowwallet/sparrow#1174]
HI，Suddenly I found that there is no new version or Cobo Vault. What should I do?

**Comment by craigraw** [comment]
Cobo Vault has been deprecated, and support will be removed in a future release. Consider moving funds to a hardware wallet that is still maintained.

For now, you can close Sparrow, edit the `config` file in Sparrow home (see FAQ to find it on your OS) and change the following variable to true:

```
"showDeprecatedImportExport": true,
```

**Comment by wertaaaaex** [comment]
Thanks
