### ISSUE TITLE
Interrupted startup: "Windows protected your PC. Microsoft Defender SmartScreen prevented unrecognized app from starting..."

### ISSUE THREAD

**Issue by GregTonoski** [sparrowwallet/sparrow#1175]
Steps: Double click an icon to start Sparrow.

Actual Result:
![image](https://github.com/sparrowwallet/sparrow/assets/111286121/a06460f2-afd4-427a-973a-c0607adcae47)
More info must be clicked for the "Run anyway" button to appear.

Expected result:
Sparrow's start/main screen instead of the warning on the blue background.

Environment:
Sparrow 1.8.1 standalone @ Windows 11.

**Comment by remcoros** [comment]
This is completely out of the developers' control. It is Microsoft Windows heuristic-based security to warn about "unknown" programs.

This is based on Microsoft heuristics and from my experience will go away when a lot of people have ignored this warning and installed the software on their PC.

It just takes time for Microsoft to see this as a recognized app.

**Comment by GregTonoski** [comment]
I have reported the incorrect classification as an uncrecognized app to Microsoft at "https://www.microsoft.com/en-us/wdsi/filesubmission".

**Comment by craigraw** [comment]
Thanks. The Windows .exe is signed, so not much more I can do here.
