### ISSUE TITLE
Import of Armory wallets

### ISSUE THREAD

**Issue by Balgden** [sparrowwallet/sparrow#1176]
Would it be possible to add the ability to import Armory wallets?

There are a number of different ways they can be exported but for starters importing from single-sheet unencrypted paper backups in version 1.35c would probably be the most valuable.
Those consist of a root key printed as two lines with 9 groups of 4 letters each. I've found the creation routine here: https://github.com/goatpig/BitcoinArmory/blob/d1521b476cc14a4174bdc739cc0995eeb7e7e656/extras/PromoKit.py#L107-L113

**Comment by craigraw** [comment]
Armoury is now so outdated that I believe very few will still rely on it to store any funds, so I'm not confident this is a good use of time. If the key can be converted into a WIF, Sparrow can sweep it. Otherwise, closing this off unless there is significant interest.

**Comment by cornfeedhobo** [comment]
At the very least, support for importing the paper wallets would be great. I know those were given out a lot at conferences for a few years.

**Comment by nroktib** [comment]
https://github.com/nroktib/arm2wif
Put this together to create a WIF from the wallet root key or paper wallet ("easy16"), example wallet/examples in src/main.c.
I'm not sure if it will really help as I don't know if Sparrow will follow derivation path on the sweep... 
It looks like armory will give you the WIF key, base58 as shown in the "View address keys" dialog for any address with a balance, though could be a tedious task...
