### ISSUE TITLE
Changing the PIN on a SATSCHIP from Coinkite

### ISSUE THREAD

**Issue by stachrom** [sparrowwallet/sparrow#1179]
I tried to change the pin on a Satschip https://satschip.com/  (embeddable Chip)  

<img width="963" alt="Bildschirmfoto 2023-11-25 um 18 32 05" src="https://github.com/sparrowwallet/sparrow/assets/80065/3bf7cece-b951-4bc8-9274-5aa22a3c8f9a">

That did not work. 

<img width="364" alt="Bildschirmfoto 2023-11-25 um 18 34 04" src="https://github.com/sparrowwallet/sparrow/assets/80065/8bdbbcb4-217b-474a-af04-8f3a5193a3ee">

Message Signing is working as expected. 

System: MacOS (Apple M1) | Sparrow-1.8.1-aarch64.dmg
Reader:  HID Model: Omnikey 5427 G2

On a Tapsigner everything worked as expected.

**Comment by craigraw** [comment]
Satscard does not support changing the PIN - it does not support that command: https://github.com/coinkite/coinkite-tap-proto/blob/master/docs/protocol.md#change

**Comment by stachrom** [comment]
Oh - i see.
According to the FAQ this should be possible: https://satschip.com/faq 

> In most respects, it operates exactly like a [TAPSIGNER®](https://tapsigner.com/) except:
> - the PIN always comes as 123456 fom the factory (but can be changed)
> - the private key backup feature is disabled

**Comment by craigraw** [comment]
Yeah looks like that's outdated.

**Comment by EhDee22** [comment]
> Oh - i see.
> 
> According to the FAQ this should be possible: https://satschip.com/faq 
> 
> 
> 
> > In most respects, it operates exactly like a [TAPSIGNER®](https://tapsigner.com/) except:
> 
> > - the PIN always comes as 123456 fom the factory (but can be changed)
> 
> > - the private key backup feature is disabled

I think Craig mistook Satschip for Satscard. I don't believe Sparrow supports Satschip at this time. If you want to change the pin you'll need to use cmd cktap upload via CLI.

**Comment by craigraw** [comment]
Apologies, I did. 

That said, Sparrow supports Satochip, but not Satschip (or least I have never tested one).

**Comment by craigraw** [comment]
Yes, it would probably be relatively easy to support - just needs to be detected and Sparrow needs to avoid calling the backup function.

I would prefer to have one to test against though.

**Comment by stachrom** [comment]
@EhDee22 could you provide the satschip from Coinkite https://satschip.com/ for @craigraw? 

<img width="255" alt="Bildschirmfoto 2024-01-21 um 17 00 01" src="https://github.com/sparrowwallet/sparrow/assets/80065/2804975f-1bdc-44bb-bcd5-02e46a0fbe87">

**Comment by EhDee22** [comment]
Absolutely. We have the stand-alone chip and the card. They operate in the same fashion. How many should I send? Just the chip or are some cards needed as well?

**Comment by EhDee22** [comment]
> craigraw

No problem, an email was sent to craigraw@gmail.com

**Comment by craigraw** [comment]
Forgot to update this issue - SATSCHIP support was added in https://github.com/sparrowwallet/sparrow/commit/74a551ed01f0ff6549e16734b191ead16d99cc3a.

**Comment by stachrom** [comment]
scheduled for 1.8.3?

**Comment by craigraw** [comment]
Yes
