### ISSUE TITLE
Error: get_passphrase got an unexpected keyword argument with Trezor One

### ISSUE THREAD

**Issue by mariodian** [sparrowwallet/sparrow#118]
Hi, when I try to create a new wallet with Trezor One, I get this error message right after I enter the (correct) PIN:

`get_passphrase got an unexpected keyword argument 'available_on_device' `

![Screen Shot 2021-05-03 at 8 53 15 PM](https://user-images.githubusercontent.com/3636406/116878831-7975ef80-ac52-11eb-84be-9fef67cd9d4c.png)

and Trezor's screen shows `Please enter your passphrase using the computer's keyboard`.

I use Sparrow 1.4.0 and Trezor FW 1.9.4.

I have no issues using the device with Trezor Suite, Specter or Electrum.

**Comment by craigraw** [comment]
This error is coming from the underlying library HWI. It's possible it's malfunctioning in some way.

To get Sparrow to replace the copy it's using, close Sparrow, edit your config file (`~/.sparrow/config`) and look for the line `"hwi"`. You can either delete this line, or delete the hwi executable it lists. Restart Sparrow and hopefully HWI will be fixed.
