### ISSUE TITLE
[Bug Sparrow Server] Fiat balance displayed despite exchange rate source set to "none"

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1181]
Sparrow Terminal v1.8.1
Linux Ubuntu flavor

Not exactly sure about the timeline of steps to reproduce this but it goes something like this:
- Open new sparrow terminal installation
- Under `Preferences` -> `General` set `Exchange rate source` to `none` 
- Transfer an existing wallet to newly created `.sparrow` folder
- Open the wallet in Sparrow Terminal
- Go to tabs like `Deposit` -> `Transactions` or `UTXO`
- See that there is a $ amount (or other fiat denomination) behind the `Balance` information

Expected behavior:
After setting the exchange rate source to none, no fiat amount should be displayed (as no exchange rate should be fetched and old values should not get re-used since they are likely outdated).

Note:
After switching between accounts and/or tabs the fiat values disappear somehow. Not sure what exactly triggers the disappearance though.

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in e1fb6741.
