### ISSUE TITLE
[Feature Request] Add Master Fingerprint Sparrow Server

### ISSUE THREAD

**Issue by TinF0ilHat1** [sparrowwallet/sparrow#1184]
Is technically feasible to add the master fingerprint? Lifehash is not necessary

![masterfingerprint](https://github.com/sparrowwallet/sparrow/assets/127325867/0594b2c7-53c5-484e-863e-bf425f021f2e)

**Comment by craigraw** [comment]
Yes, it is. Good suggestion, added in 6072f6d3.
