### ISSUE TITLE
Derivation path Issue

### ISSUE THREAD

**Issue by PUNKWISE** [sparrowwallet/sparrow#1186]
Hi, 

I have tried to import my account on ordinalswallet.com to Sparrow wallet and following the exact steps, I have used both Mnemonics words 12 and select the correct path and also with XPriv . ( For taproot )

Derivation path: m/86'/0'/0'/0 for Ordinalswallet.com 

But after importing it shows this m/86'/0'/0'/0/0/0 .

I have done multiples test and never get my transaction history inside sparrow wallet, And this issue is only with this wallet.

Please check and fix.

**Comment by craigraw** [comment]
> Derivation path: m/86'/0'/0'/0 for Ordinalswallet.com

This is not a standard BIP32 derivation path. Sparrow is a standards based wallet, and in particular follows BIP32 which means adding separate receive and change chains, followed by the address index.

So a derivation path in the keystore of `m/86'/0'/0'` will result in the first address derived at `m/86'/0'/0'/0/0`. If Ordinalswallet.com does not follow this approach it will be incompatible with any other BIP32 wallet.
