### ISSUE TITLE
Virus total : PUA.OSX.Adware on v1.8.1 

### ISSUE THREAD

**Issue by mdrlucky** [sparrowwallet/sparrow#1188]
Hi,
On Virustotal, the lastest version 1.8.1 for macOS (Apple M1/M2) is reporting the PUA.OSX.Adware.

What do you think ? 
Is this a false positive ? 
Thanks

**Comment by craigraw** [comment]
Yes - it's not uncommon unfortunately for Virustotal to report these false positives.
