### ISSUE TITLE
Mixing Wallet Failing to Connect to Node

### ISSUE THREAD

**Issue by abundantone** [sparrowwallet/sparrow#1190]
I have been communicating with Craig Raw on Telegram regarding this issue and he asked me to create this support ticket.

Here are the facts:

I've been running Sparrow 1.7.3 successfully on MacOS (Big Sur 11.7.10) for the past 10 months.  

I connect to my own Bitcoin Core full node.   

All of my sparrow wallets were connecting to my node however the mixing wallet suddenly stopped connecting.

I get an error message:  'Connection Failed: Server Error'.   

There is no issue with my bitcoin node; it is up and running and connecting to my other sparrow wallets.   

I have updated to Sparrow 1.8.1 but the issue with the mixing wallet failing to connect to the server persists.   

I also checked the config file as Craig Raw suggested and it is set to:

“Uselegacycorewallet”: false

I have attached the log.

Looking forward to getting this issue resolved.

Thanks!

 
[sparrow log.log](https://github.com/sparrowwallet/sparrow/files/13536889/sparrow.log.log)
[sparrow log.log](https://github.com/sparrowwallet/sparrow/files/13536891/sparrow.log.log)

**Comment by craigraw** [comment]
See https://bitcoin.stackexchange.com/questions/81447/rpc-giving-error-13 - it appears Bitcoin Core is trying to load a wallet, finding that a passphrase is required, and failing. Unfortunately it doesn't give the name of the wallet.

Sparrow uses one of two wallets in Bitcoin Core depending on whether you are legacy Core wallets, or the newer descriptor wallets. Neither use passphrase encryption. So either something else has added a passphrase to these wallets, or there is some other wallet that requires a passphrase before wallet functionality is enabled. 

You can try closing Sparrow and Bitcoin Core and deleting the Core wallets from the Bitcoin Core data directory until things work again. Sparrow's wallets are called `cormorant` and `sparrow`. Sparrow will recreate these wallets if necessary, but rescanning will be required.

Alternatively, you can enable DEBUG logging by opening Terminal and running:
```
open /Applications/Sparrow.app --args -l DEBUG
```

This will do a lot more logging, but will provide more clues to the problem.

**Comment by abundantone** [comment]
Some further information.

I do remember the passphrase for the encrypted bitcoin core wallet but I
don't remember the name that I gave it.

Looking at Bitcoin Core, this is what I see:


[image: Screen Shot 2023-12-03 at 10.32.00 AM.png]

There is only one wallet showing which is named 'Sparrow' and it is not
clickable.

This is 'Sparrow' wallet is the wallet I created originally to connect my
Bitcoin Core node to my Sparrow wallet(s).

So, I have no clue as to how to delete the Bitcoin Core wallet that I
created a few months ago that seems to be the cause of the current issue.

**Comment by abundantone** [comment]
[image: Screen Shot 2023-12-03 at 11.07.17 AM.png]




[image: Screen Shot 2023-12-03 at 11.07.17 AM.png]

[image: Screen Shot 2023-12-03 at 11.07.51 AM.png]

**Comment by abundantone** [comment]
Okay, I will do that now.  How long will it take to rescan the wallets?  

On another note, I am going to download Bitcoin Core and Sparrow onto another MacOS device.  I am assuming that I can recover my Sparrow wallet(s) on that new device with the 12-word Sparrow seed that was originally created on the device that is encountering the issue?

**Comment by abundantone** [comment]
Once I have the new MacOS device up and running, will I be able to connect to my Sparrow wallet(s) from both of these MacOS devices?

**Comment by abundantone** [comment]
Which one do you like the best; Fulcrum or Electrs?   
Do you have a guide that you can send me that will guide me through the setup?

**Comment by craigraw** [comment]
> Which one do you like the best; Fulcrum or Electrs?

Fulcrum. But unfortunately in neither case is it easy to run on macOS - both do not come with precompiled binaries for that platform. This is why many people use a dedicated Linux miniserver, for example those offered by Ronin Dojo or Start9. If you're up to it though, Ministry of Nodes has some great guides as part of the the Node Box series, for example https://www.youtube.com/watch?v=SpQRrbJt7cg&t=4s.

Let me know if your issue is resolved?

**Comment by abundantone** [comment]
Hi Craig,Yes, the issue was resolved by deleting the Sparrow wallet folder.  Upon rebooting, the Sparrow wallet recreated itself and scanned all the wallets including the mixing wallet.Thanks so much for your help!JoffreyOn Dec 5, 2023, at 3:29 AM, craigraw ***@***.***> wrote:﻿

Which one do you like the best; Fulcrum or Electrs?

Fulcrum. But unfortunately in neither case is it easy to run on macOS - both do not come with precompiled binaries for that platform. This is why many people use a dedicated Linux miniserver, for example those offered by Ronin Dojo or Start9. If you're up to it though, Ministry of Nodes has some great guides as part of the the Node Box series, for example https://www.youtube.com/watch?v=SpQRrbJt7cg&t=4s.
Let me know if your issue is resolved?

**Comment by craigraw** [comment]
Great, closing this off.
