### ISSUE TITLE
pop up hidden

### ISSUE THREAD

**Issue by ArmanTheParman** [sparrowwallet/sparrow#1194]
When creating a new wallet, and clicking "connected hardware wallet" button, the pop up to scan the HWW stays behind the main screen. The user is not made aware there is a popup behind and is left confused and thinking it's not working.

Environment: Linux mint, 64bit, cinnamon. Sparrow version 1.78

**Comment by craigraw** [comment]
Try the latest version?

**Comment by ArmanTheParman** [comment]
Imported into Parmanode today, I'll let you know if it happens again.

**Comment by craigraw** [comment]
I see Parmanode is at Sparrow v1.8.1 :)

Can we close this off?

**Comment by ArmanTheParman** [comment]
Go ahead. I haven't formally tested if I can reproduce the erorr... It happened on a student's computer. If it happens again I'll let you know.
