### ISSUE TITLE
Error Fetching Pools

### ISSUE THREAD

**Issue by BeeJoe** [sparrowwallet/sparrow#1196]
For several days, Sparrow can no longer find pools to mix UTXOs. It times out with "Error fetching pools, Total timeout 30000 ms elapsed" despite the wallets otherwise functioning as expected. This occurs with public server, bitcoin core, and private electrum server. It appears previously initiatied mixing in pools is still working although I don't think I've had a new transaction since this error first appeared.

**Comment by craigraw** [comment]
I can see no issues on my side, or have been reported elsewhere. It may be a local connectivity issue, or if you are connecting via Tor you may be experiencing Tor network issues. If the issue persists try a different connection.
