### ISSUE TITLE
[Bug] Inconsistent state of Mempool entries

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1198]
During whirlpooling a utxo stuck in the mempool leads to a inconsistent state between the transactions and utxos tab, see `0 sats` vs. the correct amount in the mempool `X sats`:

Sparrow GUI v1.8.1

![diff](https://github.com/sparrowwallet/sparrow/assets/72392544/9b565e0a-f034-4bcf-bfc5-b6af3fb11ded)

**Comment by RequestPrivacy** [comment]
Okay maybe this isn't a bug, just the thing again that there's no transfer of value in or out of the wallet during a remix. 

There's still a transaction in the mempool though I guess?! I at least was a bit lost on why they differ...

**Comment by craigraw** [comment]
The amount on the Transactions tab shows the value difference created by transactions in the wallet (value in - value out). The UTXOs tab simply shows the sum of the UTXO values.
