### ISSUE TITLE
Using Trezor Coinjoin account

### ISSUE THREAD

**Issue by v0l** [sparrowwallet/sparrow#1201]
Hello, i would like to use trezor coinjoin account with Sparrow wallet but i cannot import the keypath, i get the following error:

![image](https://github.com/sparrowwallet/sparrow/assets/1172179/24bdec89-84f4-4145-abe9-d4887009f14a)

I try to import the keypath `m/10025'/0'/0'/1'` as defined in https://github.com/satoshilabs/slips/blob/master/slip-0025.md

![image](https://github.com/sparrowwallet/sparrow/assets/1172179/e03722a1-7e88-4044-94cb-6f2586173096)

**Comment by craigraw** [comment]
This error is actually coming from the Trezor. See https://github.com/sparrowwallet/sparrow/issues/1081#issuecomment-1697122417 for instructions on using `trezorctl` to reduce the strictness of these checks.

**Comment by v0l** [comment]
Still having the same issues:

```bash
trezorctl get-session
trezorctl -s <id> set safety-checks prompt
```

Create wallet PT2R with keypath `m/10025'/0'/0'/1'`

**Comment by v0l** [comment]
I was able to use `trezorctl -s <id> get-address -d -t taproot -n "m/10025'/0'/0'/1'/0/0"` and i prompted to show address from "coinjoin account"

**Comment by v0l** [comment]
Ok i just export the node manually with `trezorctl get-public-node -t taproot -n "m/10025'/0'/0'/1'"`

**Comment by craigraw** [comment]
Thanks for documenting this.
