### ISSUE TITLE
Improve the Windows "Verifying the release" documentation

### ISSUE THREAD

**Issue by Medgeina** [sparrowwallet/sparrow#1202]
The https://sparrowwallet.com/download/ documentation Windows section states:

```
Windows

CertUtil -hashfile Sparrow-1.8.1.exe SHA256 | findstr /v "hash"
Compare result to the appropriate value in sparrow-1.8.1-manifest.txt!

With all these steps complete you can be certain of the integrity of your download and can proceed to install!

If you are still struggling, watch [this tutorial](https://youtu.be/U0I-ImS_r8o?t=1889) which covers the same process on macOS. There are also written tutorials for [Windows](https://www.athena-alpha.com/install-sparrow-wallet-on-windows/) and [Ubuntu](https://www.athena-alpha.com/install-sparrow-wallet-on-ubuntu/).
```

Windows users are usually not technical and not used to writing in the terminal. I think it should be better specified that before running the `CertUtil` command is important to change directory to the Downloads directory.

**Comment by craigraw** [comment]
It does actually, at the top:

<img width="965" alt="Screenshot 2023-12-16 at 08 48 36" src="https://github.com/sparrowwallet/sparrow/assets/862166/a2a14b77-cd5d-4097-9722-8ed09782b15d">

I do wish it was easier - but it is safer to have independent providers of different parts of a secure setup, so difficult for me to improve this directly.
