### ISSUE TITLE
my Transaction has stucked for many days,the gas fee is higher than the Medium Priority,but it cannot be confirmation,Especially，the Txid CANNOT be found on the mempool

### ISSUE THREAD

**Issue by 66yiyang** [sparrowwallet/sparrow#1205]
this  Transaction:2108ad982ce7504924d410e732ff12f8845f51051d39b088e5c75ff3dda97e98, is send on Sparrow,the gas fee is higher than these last few days,but it still stuck.
and,the Txid cannot found on mempool and Sparrow,but can be found on OKLINK.
https://www.oklink.com/cn/btc/tx/2108ad982ce7504924d410e732ff12f8845f51051d39b088e5c75ff3dda97e98
I donnot know the reason.please help me.my wallet cannot be use for many days.

**Comment by levinster82** [comment]
Looks like you double spent from that address.  Transaction from Dec. 19 is marked invalid.  [https://www.blockchain.com/explorer/transactions/btc/2108ad982ce7504924d410e732ff12f8845f51051d39b088e5c75ff3dda97e98](url) 

Looks like this Transaction from Dec. 20 with higher fee is the reason your first transaction is invalid.
[https://www.blockchain.com/explorer/transactions/btc/71aa36fb2c12de889610b985331741b4d462821240f3320dc6e6a3769eecf465](url)

**Comment by 66yiyang** [comment]
I donot remember I double spent .&nbsp; but now,how can i make my wallet return to normal？my wallet cannot mint for many days.
&nbsp;


燚阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月25日(星期一) 晚上10:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sparrowwallet/sparrow] my Transaction has stucked for many days,the gas fee is higher than the Medium Priority,but it cannot be confirmation,Especially，the Txid CANNOT be found on the mempool (Issue #1205)





 
Looks like you double spent from that address.  Transaction from Dec. 19 is marked invalid.  https://www.blockchain.com/explorer/transactions/btc/2108ad982ce7504924d410e732ff12f8845f51051d39b088e5c75ff3dda97e98
 
Looks like this Transaction from Dec. 20 with higher fee is the reason your first transaction is invalid.
 https://www.blockchain.com/explorer/transactions/btc/71aa36fb2c12de889610b985331741b4d462821240f3320dc6e6a3769eecf465

**Comment by 66yiyang** [comment]
please help me ,how can i make my wallet return to normal ？my wallet cannot mint for many days.

**Comment by craigraw** [comment]
The answer above appears correct. Please note Github issues are not the right place to seek support.
