### ISSUE TITLE
Import wallet from bip39 12 word seed displays unintelligible message

### ISSUE THREAD

**Issue by gStart9** [sparrowwallet/sparrow#1207]
I select Import Wallet and choose Mnemoic Words (BIP39) - Use 12 Words
I enter the words and click "Discover Wallet".  Then I get this:
![image](https://github.com/sparrowwallet/sparrow/assets/106188942/906825be-bbcd-465b-8544-80b9398e7f74)

The prompt tells me the wallet doesn't exist, and the prompt also doesn't have any questions in it, yet I have the option to answer Yes or No.  I selected Yes for shits and giggles and it then seemed to create the wallet without issue and ask me the date from which to scan for it using the Bitcoin RPC.

What is this dialog supposed to ask?  What is "wallet discovery" which is supposedly not supported by Bitcoin Core?

**Comment by craigraw** [comment]
What OS and desktop is this? I tried to recreate it without success on Ubuntu. Some Linux window managers can do odd things at times.

The dialog should be resizable, so you can expand it to view the full message. In any case, that says "You can however import this wallet and scan the blockchain by supplying a start date. Do you want to import this wallet?".

**Comment by gStart9** [comment]
Ah, ok. That explains it.  I was unable to change the size of the window.  It's Debian 12 with MATE (lightdm)
