### ISSUE TITLE
Feature request: Increase the size of "Send to multiple" tabs

### ISSUE THREAD

**Issue by ryenski** [sparrowwallet/sparrow#1209]
When using the Send to Multiple feature, on several occasions I've accidentally clicked the "x" icon on the tab bar, which removes the tab altogether. 

It would be helpful if the tabs were a bit taller so that the clickable area would be larger. 

<img width="269" alt="Screenshot 2023-12-30 at 10 00 59 AM" src="https://github.com/sparrowwallet/sparrow/assets/234/1df48ff9-0fcc-44a1-8017-9156527baef7">

**Comment by craigraw** [comment]
Tab header width increased in 20df1dbd. It's not a big change, but space is limited. This reduces the number of visible tabs from five to four.

<img width="129" alt="Screenshot 2024-01-09 at 11 53 14" src="https://github.com/sparrowwallet/sparrow/assets/862166/6a511e3e-e001-4e50-9652-c19f9798b8a0">

**Comment by RequestPrivacy** [comment]
Maybe one could get rid of the close icon and instead use a middle/right mouse click for removing the tab? Question is how to convey this possibility to the user?!

**Comment by ryenski** [comment]
IMO even a few extra pixels is a big improvement. Thanks!
