### ISSUE TITLE
Error getting fee estimates - failed connection to local electrum server

### ISSUE THREAD

**Issue by lanewrightme** [sparrowwallet/sparrow#1211]
Hi I'm new to all this, so please forgive me if I make an error in presenting this. 
I'm recently running a full bitcoin node and built an electrum server on a raspberry pi, following the instructions from raspibolt.com.

I downloaded and verified Sparrow wallet, but when I went to connect the wallet to my server on my home network I received an error message: 

Could not connect:

Error getting fee estimates: {1=ErrorMessage{code=2, message=Fee estimation disabled, data=null}, 2=ErrorMessage{code=2, message=Fee estimation disabled, data=null}, 50=ErrorMessage{code=2, message=Fee estimation disabled, data=null}, 3=ErrorMessage{code=2, message=Fee estimation disabled, data=null}, 4=ErrorMessage{code=2, message=Fee estimation disabled, data=null}, 5=ErrorMessage{code=2, message=Fee estimation disabled, data=null}, 25=ErrorMessage{code=2, message=Fee estimation disabled, data=null}, 10=ErrorMessage{code=2, message=Fee estimation disabled, data=null}}

In another post here on github, I saw that someone had a similar issue, but they were trying to connect via Tor. This is not my issue, but I tried to follow @craigraw suggestion to "try asking your node to provide fee estimates directly" using 
```
bitcoin-cli estimatesmartfee 1
bitcoin-cli estimatesmartfee 10
bitcoin-cli estimatesmartfee 50
```
Which resulted in error messages like the following:
```
error code: -32603
error message:
Fee estimation disabled
```
I've confirmed that I'm using the right url. I'm not sure what else to try.

Thanks.

**Comment by PrinceOfEgypt** [comment]
Is your bitcoin node fully synched? If so, make sure you turned off the "blocks only" mode after it synched. 

https://raspibolt.org/guide/bitcoin/bitcoin-client.html#reduce-dbcache-after-full-sync

**Comment by lanewrightme** [comment]
So I uninstalled and reinstalled and it worked.
