### ISSUE TITLE
[Feature request] xpub shield: conceal wallet xpub in the settings tab

### ISSUE THREAD

**Issue by jumbledup** [sparrowwallet/sparrow#1212]
# xpub shield: conceal wallet xpub in the settings tab

When you click the "Settings" tab, the open wallet's xpub is displayed on screen. And in order to do things like change the gap limit for address scanning, add a passphrase to the wallet or export the wallet, the "Settings" tab must be open, which means that the xpub must be displayed on screen. Given that the xpub is private information, it would be a nice privacy feature if the xpub could be concealed (shielded, greyed-out) by default until you click a button to reveal the xpub.

Would be a very easy fix, I imagine.

Thanks Craig. You are doing great work.

**Comment by craigraw** [comment]
Thanks :)

I'm curious though - it seems to me that private information is displayed on the Transactions tab, Addresses tab, UTXOs tab etc. The xpub is just one field - an important one certainly, but also quite difficult to memorise. I would assume given your reasoning that all other private information should be shielded too, which leads us to the Lock Wallet functionality that performs this.

**Comment by craigraw** [comment]
Closing this off as wontfix.
