### ISSUE TITLE
Using Ledger nano s hardware wallet in Sparrow shows no funds.

### ISSUE THREAD

**Issue by Auburnbo** [sparrowwallet/sparrow#1214]
I'm trying to use Sparrow Wallet with the Ledger Nano S that I have used with Ledger Live for the past three years. I'm unable to show my transaction history or funds in Sparrow. I've already reset the birthdate one month before my earliest transaction but it's not discovering any. 
Based on a previous posting here with the same issue I see that Ledger Live shows a Derivation of 44' /0' /0' /0/8 while Sparrow Wallet (using Native Segwit) shows a derivation of m/84' /0' /0'. Is this my problem?
If so, any suggestions on how to fix it? 
Thanks in advance for any help you can provide.

**Comment by craigraw** [comment]
You probably have the wrong script type. Follow these steps:
1. Create a new wallet with File > New Wallet
2. Set the Script Type field to Legacy
3. Import the Ledger as a Connected Hardware Wallet
4. Apply to save
5. Check the addresses match

**Comment by Auburnbo** [comment]
Yes, Craig, that did it. Thanks so much for your help. I had hit a brick wall.

**Comment by Auburnbo** [comment]
> You probably have the wrong script type. Follow these steps:
> 
>     1. Create a new wallet with File > New Wallet
> 
>     2. Set the Script Type field to Legacy
> 
>     3. Import the Ledger as a Connected Hardware Wallet
> 
>     4. Apply to save
> 
>     5. Check the addresses match

Craig, I'm attempting the same thing on a different Ledger Nano S but this time the addresses don't match. Can you help me out on this?
thanks, Bo

**Comment by craigraw** [comment]
I suggest asking on https://t.me/SparrowWallet - Github is not the right place for support.

**Comment by Auburnbo** [comment]
Thanks, Craig.

    On Tuesday, January 23, 2024 at 11:32:23 PM PST, craigraw ***@***.***> wrote:  
 
 


I suggest asking on https://t.me/SparrowWallet - Github is not the right place for support.
