### ISSUE TITLE
Balance wrong, unconfirmed transaction is added to balance

### ISSUE THREAD

**Issue by TheRockaXXX** [sparrowwallet/sparrow#1216]
Hi,
I use sparrow 1.8.1 on Mac OS 14.2.1.
My balance shows my real balance plus a balance, I sent to myself as a consolidation.

Example:
I got 1 BTC in 20 UTXOs. I sent 15 UTXOs worth 0.5 BTC to myself to consolidate. The transaction is not still confirmed. Now sparrow shows my balance 1.5 BTC (0.5 unconfirmed).

Is this the wanted behavior or is this a bug?

Thanks!

**Comment by craigraw** [comment]
It sounds like the server you are connected to is having issues.

Try refreshing the wallet (View menu).
