### ISSUE TITLE
Connect remote bitcoin node - umbrel breaks Brave Browser shields

### ISSUE THREAD

**Issue by jbrauck-unchained** [sparrowwallet/sparrow#1217]
Hi so I couldn't get my umbrel to connect to sparrow via bitcoin core. Umbrel recommends running an electrum server to connect to sparrow, but I wanted to first try it without having to do that.
I followed the instructions I found here https://sparrowwallet.com/docs/connect-node.html#remote-setup
I went into my bitcoin node bitcoin.conf file and made the edits to add
```# RPC Bind ports 
rpcbind=127.0.0.1
rpcbind=*ip my server runs on*
rpcallowip=127.0.0.1
rpcallowip=*ip my server runs on*/16
```

And upon resetting my node, it worked! Sparrow could connect to my node via bitcoin core. But after I realized my brave browser wasn't working, and after a little more digging, it was only when the browser shields were up. I am wondering if the addition of `127.0.0.1` in the conf file could have broken this feature of brave browser. Any possible workaround?

**Comment by craigraw** [comment]
I can't imagine how changing this setting has affected Brave - it seems totally unrelated. Sorry I can't be of more assistance.
