### ISSUE TITLE
Enhance plausible deniability for wallets

### ISSUE THREAD

**Issue by KenKundert** [sparrowwallet/sparrow#122]
Currently the wallets are contained in ~/.sparrow/wallets, and the name of the wallet is the name of the file.  These directories are globally readable.  It makes it impossible to deny the existence of a wallet once somebody looks into this directory and sees the wallets.

From a plausible deniability perspective it would be better if the filename was not the same as the wallet name.  Better would be that the filename a seeming random sequence of characters.

Even better would be for all the wallets to be contained in a single file that contains the actual wallets plus extra decoy wallets so that an intruder could not identify how many wallets were present.

**Comment by craigraw** [comment]
> These directories are globally readable.

The wallets directory (and the wallet files) are now owner readable/writable only (a0d3f3b).

> From a plausible deniability perspective it would be better if the filename was not the same as the wallet name. Better would be that the filename a seeming random sequence of characters.

This seems weak protection at the cost of the usability of the wallet files. The recommended approach for plausible deniability is to use Sparrow Wallet with the default home folder (`~/.sparrow`) for the decoy wallets and supply the `-d` command line flag to specify a different location for the real wallets (which can be on removable media).

**Comment by KenKundert** [comment]
Thanks for the suggestion. However, one of my concerns is passing my bitcoin on to my heirs if something were to happen to me unexpectedly.  It seems like counting on removable storage adds another potential failure mechanism that could interfere with my heirs ability to claim my bitcoin.

**Comment by craigraw** [comment]
Indeed, such concerns are true for most of the obfuscation techniques we use (including your suggestion). There aren't any simple solutions to this. Another alternative is to use the `-d` flag with a more obscure location on your hard drive.

**Comment by francitoshi** [comment]
Maybe the best option is to mount an encrypted directory with something like encfs or gocryptfs, you mount it do your stuff and unmount it. maybe it is something available for Windows and Mac users.
