### ISSUE TITLE
Avoid generating dust change after the Tx0.

### ISSUE THREAD

**Issue by 4rkad** [sparrowwallet/sparrow#1220]
In certain scenarios when initiating a Tx0, the toxic change (unmixed change) can have a very low value. The issue is that transferring that UTXO later can be inefficient/costly. Sparrow wallet can detect if the toxic change generated in the Tx0 is dust (≤5,000 sats, the amount can be adjusted based on the state of mempool fees) and suggest to the user to spend that amount on the mining fee for the Tx0. Sparrow already does this with simple/efficient transactions.

The benefits would be a reduced probability of dust in the Bad bank, avoidance of consolidations of low-value toxic changes, and the Tx0 would eliminate an inefficient output.

**Comment by craigraw** [comment]
While I tend to agree, this is actually a proposal for the Whirlpool coordinator/client so best suggested to the Samourai team.
