### ISSUE TITLE
Transaction view displays wrong order of outputs in "curvy lines" diagram

### ISSUE THREAD

**Issue by donnlee** [sparrowwallet/sparrow#1221]
Update: I just realized i'm on 1.7.2.  I will upgrade to 1.8.1 and report back here.
Update2: I see the bug in 1.8.1 also. New screenshots below.

Ordering of outputs is important when sending ordinals. I encountered an issue with the transaction diagram with the curvy lines:
![sparrow big dot wrong Screenshot 2024-01-07](https://github.com/sparrowwallet/sparrow/assets/1100053/5f371e28-dc24-4ab3-a217-983cea58c33e)
https://mempool.space/tx/ceda3ac258c51952f7847d04c3189b627e15cbed97f645df9744158d49dca596

The diagram shows the 2nd output (Output1) is `bc1p3u89..pndq` and 330 sats, which is incorrect.
The red arrow indicates the mouse pointer position used to trigger the hovering text.
Also, notice how the black dot next to Output1 is larger than the other black dots. Large dot = more sats, if my experience is correct.
`bc1pedrx..` is the larger change address. The diagram says it's the last output and a small dot, but the blockchain says it is the 2nd output.
So the size of the black dots agree with the blockchain, but the addresses printed for each output is incorrect.

If I click `Output #1` on the left pane, it is correct:
![sparrow output1 on left is correct Screenshot 2024-01-07](https://github.com/sparrowwallet/sparrow/assets/1100053/69ca639d-69e2-4458-8f0e-6743866e679f)

Unfortunately, I trusted the diagram and broadcasted.  When I checked mempool.space, I was surprised to see `bc1pedrx..` in Output1.
After the transaction was mined, the Sparrow diagram remained wrong (the screenshots pasted here).

I did another txn today and observed the same bug with the diagram.  I am trusting the left-side pane for now.

**Comment by donnlee** [comment]
sparrow 1.8.1
Txn before broadcasting it.
This time it is Output2.
![sparrow 1 8 1 bug Screenshot 2024-01-07](https://github.com/sparrowwallet/sparrow/assets/1100053/188a572b-7476-40f4-8d1d-2829575f3974)

![sparrow 1 8 1 bug left Screenshot 2024-01-07](https://github.com/sparrowwallet/sparrow/assets/1100053/12e515be-77ef-4eb7-9c74-59433e4d27c3)

**Comment by craigraw** [comment]
Thanks for the bug report. Fixed in 31623718.

This edge case occurred in the situation where there were multiple payments to the same address of the same amount.

**Comment by donnlee** [comment]
Oh sweet, thank you for the quick bugfix!
These ordinal use-cases are breaking all kinds of previous assumptions about bitcoin 😅
