### ISSUE TITLE
Problem importing a non-standard output descriptor

### ISSUE THREAD

**Issue by Lagrang3** [sparrowwallet/sparrow#1226]
I would like to add watch-only wallet on sparrow to double check on-chain funds allocated in a core-lightning wallet.
The problem is that sparrow does not understand the descriptor that I am providing, and it falls back to some default derivation path so the final addresses are wrong.

Let me put an example, for reproducibility lets consider the following bip39 sentence:
```
abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about
```
The command `lightning-hsmtool generatehsm hsm_secret` reads from `stdin` the mnemonic and produces a `hsm_secret` file
which is used by the lightning node to generate the BIP32 seed for the HD wallet.
In this case we have
```
$ xxd hsm_secret
00000000: 5eb0 0bbd dcf0 6908 4889 a8ab 9155 5681  ^.....i.H....UV.
00000010: 65f5 c453 ccb8 5e70 811a aed6 f6da 5fc1  e..S..^p......_.
```
Now, the descriptors for the on-chain wallet are recovered with the `dumponchaindescriptors` command and we get
```
$ lightning-hsmtool dumponchaindescriptors hsm_secret testnet
wpkh(tpubD6NzVbkrYhZ4XwwbFEkiiLEoYizHJPNgawd5HGj7zP78nZN3gQ1kNnWa9zHiUyhndK2YiRp1z6bsR1J63VSKEeZSQuKe1f5aoykT44tdGtY/0/0/*)#0w50lwl2
sh(wpkh(tpubD6NzVbkrYhZ4XwwbFEkiiLEoYizHJPNgawd5HGj7zP78nZN3gQ1kNnWa9zHiUyhndK2YiRp1z6bsR1J63VSKEeZSQuKe1f5aoykT44tdGtY/0/0/*))#yg9tgc4e
tr(tpubD6NzVbkrYhZ4XwwbFEkiiLEoYizHJPNgawd5HGj7zP78nZN3gQ1kNnWa9zHiUyhndK2YiRp1z6bsR1J63VSKEeZSQuKe1f5aoykT44tdGtY/0/0/*)#zj9mfka
```

For a moment we can for simplicity forget about the `sh(wpkh)` and `tr()` descriptors, and use only `wpkh()` which is the default
wallet used to generate addresses when we call `lightning-cli newaddr`.
I have computed that the first 10 addresses are
```
m/0/0/0 tb1qytl4pupga6g3phzdtkykmjk83sa3kcu2ygaljy
m/0/0/1 tb1qsg5zasnfjc0tpxm7jgrxd22fmujygx90dssg6a
m/0/0/2 tb1qunhejlc53sxxwspw4uzx5gwll97vrd8xsgwchz
m/0/0/3 tb1q3ulj75tw59rnum45vq3vy7u7d9rawun7kzfkdm
m/0/0/4 tb1ql94l53zg03mklsa077qzktp5h6phczqehwp2qh
m/0/0/5 tb1qtq4kj85ff9z7rjqemkaw4gstvgfpmftd862rk8
m/0/0/6 tb1qwd8dz7atpyu5szpnywgfmdq7f9jg64yp02r8lj
m/0/0/7 tb1qhuwzrlm5uj37fc2r99hysk0wal6k200v94k56a
m/0/0/8 tb1qem0nnlcath5tz3nd48q76a5wmt3kw7ldedjwmc
m/0/0/9 tb1qlykcapsujtdp7quxj0n4w0aktqvyptfprl6hyq
```
And as a matter of fact I get those when I call `lightning-cli newaddr` repeatedly.
I have tried the descriptor into bitcoin-core and I get there the same
addresses.

Now when it comes to importing that descriptor to sparrow I get into troubles.
It seems that sparrow only support a predefined format for descriptors.
If I plug 
```
wpkh(tpubD6NzVbkrYhZ4XwwbFEkiiLEoYizHJPNgawd5HGj7zP78nZN3gQ1kNnWa9zHiUyhndK2YiRp1z6bsR1J63VSKEeZSQuKe1f5aoykT44tdGtY/0/0/*)#0w50lwl2
```
into a new wallet in the dialog `Edit wallet output descriptor` it looks like
the software doesn't like it and next thing I see the descriptor is changed to
```
wpkh(tpubD6NzVbkrYhZ4XwwbFEkiiLEoYizHJPNgawd5HGj7zP78nZN3gQ1kNnWa9zHiUyhndK2YiRp1z6bsR1J63VSKEeZSQuKe1f5aoykT44tdGtY/<0;1>/*)
```
There is no way to change that. At this point the addresses are wrong because they should be `m/0/0/*` and instead I am getting `m/0/*` and `m/1/*` addresses, no matter what I do. The only workaround I have been able to do is to derive the child `m/0` with my own scripts and then insert that into sparrow.

So in essence I am not able to watch that wallet on sparrow.

**Comment by craigraw** [comment]
Indeed, Sparrow follows BIP32 (with normal receive `/0/*` and change `/1/*` output chains) and does not support arbitrary output descriptors. While there are certainly use cases for arbitrary output descriptors, I've made this call for complexity and maintainability reasons.
