### ISSUE TITLE
Unable to add a custom derivation path for a SegWit wallet

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#123]
Was testing sparrow with the new segwit addresses generated on bisq but it seems that it's not allowed.
I was able to do it on Electrum.

It lets me import seed words with custom derivation path/account, but not create a wallet with SegWit selected and a m/44'/ derivation path.

Was doing this for fun/testing, so maybe its very bad practice. Still, it would be nice to know why its not allowed or to be able to create with whatever derivation path the user chooses.

![image](https://user-images.githubusercontent.com/807505/117189027-b6092e80-adab-11eb-8a64-0314caa8ca64.png)

**Comment by craigraw** [comment]
It's not good practice, but if you want you can allow it in the Preferences. See the 'Validate derivations' toggle under the General section.
