### ISSUE TITLE
Can't install sparrow wallet on parrot os

### ISSUE THREAD

**Issue by nbayoungnode** [sparrowwallet/sparrow#1230]
Has anyone had any luck installing sparrow on parrot? I can install it on tails but nothing on parrot.

**Comment by craigraw** [comment]
There is record of another user running Sparrow on Parrot - perhaps provide more detail on where the install is failing.

**Comment by nbayoungnode** [comment]
Maybe I'm not installing it right. I have downloaded the sparrow pgp manifest.txt file
And sparrow 1.8.1 amd64.deb I tried installing it through the terminal no luck.

**Comment by nbayoungnode** [comment]
> > Maybe I'm not installing it right. I have downloaded the sparrow pgp manifest.txt file And sparrow 1.8.1 amd64.deb I tried installing it through the terminal no luck.
> 
> 
> 
> Once you verified the .deb installer ( see instructions on the download page) open terminal - `cd` where sparrow is  `sudo dpkg -i (your file) `

about to try this and I will get back to you. Thanks.

**Comment by nbayoungnode** [comment]
> > Maybe I'm not installing it right. I have downloaded the sparrow pgp manifest.txt file And sparrow 1.8.1 amd64.deb I tried installing it through the terminal no luck.
> 
> 
> 
> Once you verified the .deb installer ( see instructions on the download page) open terminal - `cd` where sparrow is  `sudo dpkg -i (your file) `

Can you expanded on what you mean by (your file)? I'm kinda new to coding so I'm barely learning how to send codes from to the terminal. I'm stuck at this part ![image](https://github.com/sparrowwallet/sparrow/assets/156553106/53dcc01a-6237-4d1e-8a71-c39bcd593a90)

**Comment by nbayoungnode** [comment]
> > Maybe I'm not installing it right. I have downloaded the sparrow pgp manifest.txt file And sparrow 1.8.1 amd64.deb I tried installing it through the terminal no luck.
> 
> 
> 
> Once you verified the .deb installer ( see instructions on the download page) open terminal - `cd` where sparrow is  `sudo dpkg -i (your file) `

Ok I got it!! Now I get this error. I'm going to restart it [image](https://github.com/sparrowwallet/sparrow/assets/156553106/608cc85c-690d-48ab-8314-b5661058d6f9)

**Comment by nbayoungnode** [comment]
All good now! I got it installed thanks for the help guys. @craigraw you can close this topic now.
