### ISSUE TITLE
Error Executing HWI on Windows 11 with BitBox02

### ISSUE THREAD

**Issue by KushGene** [sparrowwallet/sparrow#1231]
Hey, I did a fresh install of Sparrow 1.8.1 with admin rights.
I wanted to scan my HW but got the following error: Error Executing HWI
I couldnt find a solution online yet.
I get this error even if BitBox app is open and if I open the Sparrow Wallet with admin rights.

Below is the log file, seems that HWI is missing.

[sparrow.txt](https://github.com/sparrowwallet/sparrow/files/13931228/sparrow.txt)

**Comment by craigraw** [comment]
The error is actually `Die angeforderte Adresse ist in diesem Kontext ung ltig`. Unfortunately, HWI [checks for simulators](https://github.com/bitcoin-core/HWI/issues/653) running on ports 2222, 21324, 11044, or 9999. In this case, it appears that [port 21324 is responsible](https://github.com/bitcoin-core/HWI/blob/7fd2cead481197f88cad180757b5cf982eb0a0b1/hwilib/devices/trezorlib/transport/udp.py#L34). Check if anything is running on that port.

**Comment by KushGene** [comment]
> The error is actually `Die angeforderte Adresse ist in diesem Kontext ung ltig`. Unfortunately, HWI [checks for simulators](https://github.com/bitcoin-core/HWI/issues/653) running on ports 2222, 21324, 11044, or 9999. In this case, it appears that [port 21324 is responsible](https://github.com/bitcoin-core/HWI/blob/7fd2cead481197f88cad180757b5cf982eb0a0b1/hwilib/devices/trezorlib/transport/udp.py#L34). Check if anything is running on that port.

Nothing runs on this port.

**Comment by craigraw** [comment]
The error is occurring on trying to make a UDP connection to `127.0.0.1:21324`. The error message, which I have translated as "The requested address is invalid in this context" seems to suggest that there is something here unsupported in your network stack. This could also be related to AV or firewall (although the error message doesn't suggest it).

You might want to try investigating this further with something like netcat: https://stackoverflow.com/questions/6336941/windows-bat-or-cmd-send-some-data-to-a-localhost-udp-port

**Comment by KushGene** [comment]
I have found the problem... Even if I added the Sparrow wallet to split tunneling with MullvadVPN, this seems to have been the problem. As soon as I deactivate MullvadVPN, the search for the hardware wallet works.

So: switch off the VPN.
