### ISSUE TITLE
[Sparrow GUI - UI] Separate dialog boxes better from underlying UI

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1234]
Minor issue but still...

On:
- Sparrow 1.8.2
- Linux Ubuntu flavor 22.04 LTS
- Dark mode

Request:
- Give dialog boxes (e.g. transaction details, About page) a border color to separate them from the background UI

-> No separation gives strange "embedded" look
![g3465](https://github.com/sparrowwallet/sparrow/assets/72392544/14ac7cb2-55b6-4dd2-b392-162189fb454b)
-> Better separation by clearly visible border
![g3465_2](https://github.com/sparrowwallet/sparrow/assets/72392544/827e5a67-8f31-4507-84bb-1e2dce9449ba)

**Comment by craigraw** [comment]
What window manager are you using? Here's what I get on Ubuntu 22.04 running GNOME:

<img width="1056" alt="Screenshot 2024-01-22 at 09 34 29" src="https://github.com/sparrowwallet/sparrow/assets/862166/5802c7d2-d075-4dee-9143-0260b91b5d5e">

**Comment by RequestPrivacy** [comment]
I' have still the older X11:
```bash
requestprivacy@vm:~$ xdpyinfo | grep version
version number:    11.0
X.Org version: 1.21.1.4
```

**Comment by craigraw** [comment]
Ok, I've added a light border. Frustrating that some window managers handle this situation so poorly. 1d32b693.
