### ISSUE TITLE
UX proposal: Rename Cancel-button

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#1236]
Under signing, when pressing "Show QR", it seems more natural to call the exit button on this screen "Back" or "Close" since you actually not cancelling any operation:

![image](https://github.com/sparrowwallet/sparrow/assets/93251679/4c3f3772-2a24-4907-822e-b76e0017c1a0)

**Comment by craigraw** [comment]
Good suggestion, implemented for both display and scan QR dialogs in fbc49fd6.

**Comment by seedhammer** [comment]
Thank you!
