### ISSUE TITLE
Unfreeze spend UTXO for RBF

### ISSUE THREAD

**Issue by dchrist22** [sparrowwallet/sparrow#1238]
Hi, 

I have an unconfirmed transaction, which I want to RBF but, in the transaction screen no input UTXO can be selected and "Insufficiant funds" is showing.

I recreated this in testnet and found out that the problem problably is that I froze that UTXO, saved the TX as .psbt, loaded and send it. Now I can't unfreeze the UTXO because it is not showing in the UTXO tab.

Send screen after right click -> RBF:
![Sparrow - Testnet Wallet_002](https://github.com/sparrowwallet/sparrow/assets/16014040/94729308-eb94-43f8-9bee-1dd37e102cbe)

UTXO Tab without the frozen UTXO and no UTXOs selected:
![Sparrow - Testnet Wallet_003](https://github.com/sparrowwallet/sparrow/assets/16014040/c8ffcb8e-62f9-4f8b-811c-fdc7f72e9b08)

Transaction:
![Sparrow - Electrum psbt_001](https://github.com/sparrowwallet/sparrow/assets/16014040/8ef7cfa9-dcb2-4172-9979-8db15119be65)

I am not sure why in the send screen 2 UTXOs are selected but in the UTXO none is selected. The transaction also had just one input.

Is there a way to show spend UTXO in the UTXO tab or a other way to unfreeze that spend UTXO?

RBF of the UTXO is activated and allow unconfirmed is also checked.

I'm not sure if this is unintended behaviour or I am just not finding the option to show the spend and frozen UTXO.

Thanks in advance

**Comment by craigraw** [comment]
Thanks for the bug report - frozen UTXOs should be unfrozen if they have been spent. Fixed in https://github.com/sparrowwallet/drongo/commit/a436de319a763c36e3a8944af77ebf6e267a4084.
