### ISSUE TITLE
Feature Request: `Add many` to the send page

### ISSUE THREAD

**Issue by keblek** [sparrowwallet/sparrow#124]
In the send page you can add new addresses one by one.

This works fine if you only want to add one or two more outputs.

If you are batching a large tx with many outputs (like batching several LN channel opens or a coinjoin) then this can be tedious and potentially error prone.

Please add a `Add Many` where I can add a list of tx's and their amount. 

Either by opening a file with a list, or paste them into a text box.

For example, I can compile a list of addresses and their amount in a text editor and have the wallet open it and construct a tx from it.

An example would be something like the following;
<Address> <sats>
bc1...gg 1,000,000
bc1...nm 1,000,000

**Comment by craigraw** [comment]
Added in f23a891. The addresses and amount can either be added in the spreadsheet grid in the wallet, or by loading a CSV file with the equivalent tabular data in it.

<img width="962" alt="Screenshot 2021-05-19 at 08 39 54" src="https://user-images.githubusercontent.com/862166/118767446-0ab5aa80-b87e-11eb-8910-3c01a5f4850b.png">

**Comment by keblek** [comment]
Nice! Lightning batchers will appreciate this.
