### ISSUE TITLE
Crop the fee range in the fee chart

### ISSUE THREAD

**Issue by Giszmo** [sparrowwallet/sparrow#1242]
With the fee market developing, some fee ranges will be unused for months on end. This chart:

![image](https://github.com/sparrowwallet/sparrow/assets/96378/69fac061-1676-4e3e-a238-e5f505f3bc62)

currently "wastes" half its height on fee levels not getting confirmed since 3 months, resulting in a horizontal line that could be more pronounced to better see which fee to pick if trying to save on fees.

Granted, with the chart as it is, one might be more inclined to just pay the next-block fee, after all it's all the same while a more pronounced chart would lead to users opting for lower fees but I would argue the latter is favorable for Sparrow users and Bitcoin at large, especially as Sparrow allows RBF. The fee line is flat as this precisely because others are picky.

Please show the y axis instead of 0 to $nextBlockFee, show:

* **ideally**: $thirdyDayLowFee to $nextBlockFee
  As of now, this would be 25 to 40
* **alternative**: 0.9*$fiftyBlockEstimate to $nextBlockFee
  As of now this would be 34 to 40

Over the course of editing this issue I saw above chart turn into:

![image](https://github.com/sparrowwallet/sparrow/assets/96378/4343a392-c444-4a3e-88f5-c91b61c8ec08)
while the 2h trend of the mempool looked rather declining, not increasing. And now, less than 2min later I'm looking at this:

![image](https://github.com/sparrowwallet/sparrow/assets/96378/88008825-a665-452a-8a6b-9671dda13164)

Sorry if that's another issue but that estimator appears to fluctuate wildly.

**Comment by craigraw** [comment]
Good idea, implemented in 7ebb92d9.

<img width="343" alt="Screenshot 2024-01-24 at 09 16 24" src="https://github.com/sparrowwallet/sparrow/assets/862166/90d2b818-4d2d-431e-8fc0-6f4175aa8d77">


> Sorry if that's another issue but that estimator appears to fluctuate wildly.

The estimator is not part of Sparrow, but whatever fee rate source you are connected to. If it's set to Server, it's probably ultimately Bitcoin Core, which has known issues with fee estimation.
