### ISSUE TITLE
[Feature] Add ability for specifying exact fee rates

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1243]
Not sure if there is a way to do this already but I would sometimes prefer to set an exact fee rate (not exact _absolute fee_) for sending.

The slider is great but as it uses a logarithmic axis (every tick is double the fee rate), setting an exact amount at a high fee environments can be tricky.

One could exchange the current informational fee rate text string (`Rate: xx.xx sats/vbyte`) to an input field that uses the values of the slider as the default value but can be clicked for entering specific fee rates?

**Comment by craigraw** [comment]
I appreciate the idea, but there's only so many ways the Send tab can accommodate setting the fee without it becoming a usability problem.

> One could exchange the current informational fee rate text string (Rate: xx.xx sats/vbyte) to an input field that uses the values of the slider as the default value but can be clicked for entering specific fee rates?

I think this would be too complex visually - and that area is also used to display the effective fee rate with CPFP.

**Comment by RequestPrivacy** [comment]
Maybe you find some of the following ideas non intrusive/complex from a users perspective and yet they can bring value imho: 
- Hovering over the slider and scrolling the mouse wheel changes the fee rate in 0.1 steps (steps could be set in the settings) 
- (Right-) Clicking on the fee rate text string opens the contextual dialog where you add an item like `Specyfiy exact fee rate` which opens a text box where one can input the exact sats/vB
- Moving the slider with a left mouse press moves the fee rate like it currently does. If right mouse pressing on the slider for the same translation it increases/decreases the fee rate way slower
- Clicking on one of the displayed fee rate ticks of the slider (currently `1,2,4,8,16,32,64,...,512,1024` sats/vB) resets the sliders minimum or maximum (depending on where the sliders button is) to the clicked value. Clicking on the changed bound tick brings you back to the original range. 
- Add two markers into the current fee rate slider. By default they sit on the min and max ends. Sliding them re-scales the slider after a short delay so that it respects the bounds set by the marker (functionality wise the same as in the point above)
- A another slider to set upper and lower bound of the fee rate (like used for price filtering in online shops - so should be intuitive for most users). The current slider would respect these bounds and could act to fine tune the fee rate in the previously specified bounds.

I find point no 1 interesting as it's fairly easy to set the range per mouse press to the coarse fee rate and then with some mouse wheel spinning get to (somewhat) the exact fee rate and it's an easy feature to understand.

**Comment by marcocattaneogotam** [comment]
+1

**Comment by craigraw** [comment]
> Hovering over the slider and scrolling the mouse wheel changes the fee rate in 0.1 steps

Thanks for this suggestion - implemented in c407a414, with 0.01 sat/vb steps for fine adjustment control. Note that on the Efficiency setting, Sparrow will continue to optimize on coin selection for no change transactions, and if this is successful it will take priority over these fine fee rate adjustments.
