### ISSUE TITLE
Supporting building from source with Java 21

### ISSUE THREAD

**Issue by msgilligan** [sparrowwallet/sparrow#1246]
It would be nice to be able to build Sparrow with Java 21. The README says Java 18 or later is required, but 18, 19, and 20 are no longer supported (and are not easily available with tools like SDKMAN) so it would be nice to be able to build with the current "LTS" version: 21.

I have created three PRs that when combined should allow building with JDK 21:

* #1244   
* https://github.com/sparrowwallet/drongo/pull/19
* https://github.com/sparrowwallet/drongo/pull/21

I have verified that `gradle build`, `gradle run`, and `gradle jpackage` work on macOS/aarch64 using Gradle 8.5 and Java Temurin 21.0.1.

After these PRs (or equivalent) are merged it should be possible to update the Gradle Wrapper to use Gradle 8.5, but that can be done later/separately.

**Comment by craigraw** [comment]
Thanks for the prompt on this. I've upgraded the Gradle wrapper to 8.5 in 37af6635. Sparrow now builds with Java 21.
