### ISSUE TITLE
Unusual change path warning on Blockstream Jade

### ISSUE THREAD

**Issue by Zeke8990** [sparrowwallet/sparrow#1247]
My Blockstream Jade hardware wallet (updated to firmware v1.0.27, tried both radio and no-radio) has been throwing me an "Unusual change path" warning when I attempt to consolidate UTXOs by sending them to the same Jade wallet using Sparrow (v1.8.2).

- I do not have any issues completing the same task with Specter Desktop on OS X.
- I do not have any issues sending UTXOs to different wallets (hot or cold).
- I even attempted installing each driver at https://help.blockstream.com/hc/en-us/articles/900005443223-Fix-issues-connecting-Jade-via-USB#h_01H4PFV1R8CC9TCSBBMBTP5E6J, to no avail.

Blockstream has gone back and forth trying to assist me the past week or two and I will send them the link to this issue, in case their engineers can work with yours.

Thanks,
Tim

**Comment by craigraw** [comment]
I have recreated this - the Jade simply does not seem to like sending funds back to a known receive address in the wallet. Why it warns against this is unclear. The Jade can verify that the receive address is legitimate (and in fact clearly does so in displaying the index of the address in the warning), so there is no valid reason I can think of for warning the user.

If you want to avoid this "warning", just copy a fresh change address from the Addresses tab and send to that instead.

**Comment by Zeke8990** [comment]
I noticed that I don't receive a warning when testing a change address.

I understand that literal leftover "change" is regularly returned to change addresses when transacting with UTXOs. However, what are the repercussions of sending to a change address instead of a receive address?

I am also concerned about running into complications with a multisig signature setup down the line.

**Comment by craigraw** [comment]
> However, what are the repercussions of sending to a change address instead of a receive address?

There are no repercussions. You are simply sending to another address controlled by the wallet.

**Comment by Zeke8990** [comment]
Great, thanks. The Internet was making me nervous ([Five Ways to Lose Money with Bitcoin Change Addresses](https://bitzuma.com/posts/five-ways-to-lose-money-with-bitcoin-change-addresses/)). 😅

I still don't know how you explain Specter having no issues sending funds back to a known receive address on the same Jade. However, I will probably leave such UTXO consolidation to other hardware wallets, in any case.

I was already curious about creating a fresh wallet to be managed by my Jade, though it sounds like I am likely to run into the same issues ...
