### ISSUE TITLE
Trying to verify the hash for latest Sparrow for Window Download

### ISSUE THREAD

**Issue by drBTC21** [sparrowwallet/sparrow#1248]
Just downloaded the Sparrow wallet for windows yesterday. I'm trying to verify the Sha256 sum. 

I notice that the downloaded application is named Sparrow.exe.

When I run the command > CertUtil -hashfile Sparrow.exe SHA256 | findstr /v "hash"

It gives me a hash that is not the same as the hash listed in the Sparrow-1.8.2-manifest.txt file.

Am I doing something wrong or is the Window's version of Sparrow-1.8.2.zip compromised?

Thanks

**Comment by craigraw** [comment]
You need to run CertUtil on the .zip file itself. It appears you have expanded it and then run CertUtil on Sparrow.exe.
