### ISSUE TITLE
Timeout Searching for Brodcasted transaction

### ISSUE THREAD

**Issue by wealthcollector** [sparrowwallet/sparrow#1249]
Been having an issue the past few days when trying to sent to send a multi sig transaction. "Timeout searching for brodcasted transaction" "The transaction was brodcasted but the server did not register it in the mempool. it is safe to try brodcasting again"

I am connected to my node using umbrel and sparrow shows that i'm connected. When I test connection, it says i'm connected as well. Yesterday, this same issue was occurring and I restarted my node and tried to send a transaction after and it didn't work. Then I shut the node down, unplugged it, plugged it back in, and I was able to send a transaction after doing this. This morning neither of those things are working. This has happened to me on occasion in the past, but nothing like the past few days.

Any idea what's going on and how I can fix it. Could it have anything to do with the new update? Thank you.

**Comment by craigraw** [comment]
Are you connecting to your node via Electrs on the Umbrel? Are you broadcasting via Tor or without? It appears that either Bitcoin Core or Electrs is not keeping up, or you are using too low a fee rate and the transaction (if broadcasted using a remote service over Tor) is not propagating to your server as a result.

You can also try putting the txid into a block explorer to get an independent view of whether the transaction has been broadcasted.
