### ISSUE TITLE
Funds sent to Sparrow generated address confirmed, but never arrived in the wallet

### ISSUE THREAD

**Issue by cferr716** [sparrowwallet/sparrow#125]
I sent a DM about a day ago on twitter and was requested to raise an issue here. On 10-May I sent a tx from Cash App to an address generated by Sparrow. The tx confirmed on the block chain and never arrived in my Sparrow Wallet. When I go back into the wallet and search for the address nothing shows up. When I trace the address from the tx it says it is not associated to any wallet. No passphrase was used that I am aware of. I've sent many tx from Cash App to Sparrow in the same way. 

Expected: Generate address. Scan address from Cash app. Send tx. tx confirms and arrives in sparrow wallet

Actual: Generated address. Scanned address from Cash app. Sent tx. tx confirmed, but never arrived in the wallet. The address cannot be found anywhere with no association. 

This wasn't a significant amount of funds >$100, but if there is a bigger issue I needed to let the devs know for future users.

**Comment by craigraw** [comment]
Thanks for the issue. Can you provide details on the type of wallet (BIP39 Software wallet, or hardware wallet)? Was the address sent to the first address in the wallet, or had the wallet received funds before?

**Comment by cferr716** [comment]
yep. I can confirm. It’s a BIB39 software. I used the address that came up first when I opened the receive tab. I can confirm I don’t reuse addresses and I’ve received tx into this wallet previously in the same manner.

**Comment by craigraw** [comment]
Thanks. Does this wallet require a password to open? If so, can you try creating a BIP39 wallet that uses the password as a BIP39 passphrase to see if the missing address comes up?

**Comment by cferr716** [comment]
Just finished creating a wallet with the BIP39 passphrase and the missing address did not come up.

**Comment by craigraw** [comment]
Thanks! Can you check on the Addresses tab whether the addresses are sequential? You can do this by hovering over the address - you should see `../0/0`, then `../0/1`, then `../0/2` etc. If there is a break in the sequence it may be the missing address.

**Comment by craigraw** [comment]
Found and fixed a bug in d67c5c5 where the addresses table dropped an address from the list when it received funds. This was on the view level only - the address was still in the wallet file and would reappear on restarting the app.

**Comment by 6102bitcoin** [comment]
@cferr716 can you confirm that restarting your app or updating to [1.4.1](https://github.com/sparrowwallet/sparrow/releases/tag/1.4.1) resolves this issue?

**Comment by 6102bitcoin** [comment]
Outstanding Action: Identify whether issue is solved either with a restart or with the new release. If so, close issue.
Proposed Priority: Low

**Comment by cferr716** [comment]
I updated to 1.4.1. Re started the application and let the wallet load nothing new. I closed all the wallets and imported from seed and passphrase again. I don't see a break in the numbers in the address tab ../0/0, ...0/1. but there should be a transaction from 10-May that is not in the date range. I also checked all the used addresses in the the wallet and nothing is matching incase it pulled up an previously generated address. It's the most bizarre thing. I know for a fact that sparrow presented me an address, I scanned from the Cash App when I sent the tx. It just doesn't show up anywhere except on the blockchain.

**Comment by 6102bitcoin** [comment]
Could you have loaded a different wallet file accidentally?

**Comment by cferr716** [comment]
Definitely the same wallet.

**Comment by 6102bitcoin** [comment]
Re-reading your comments here you initially said that "No passphrase was used that I am aware of". Most recently you said "I closed all the wallets and imported from seed and passphrase again."

Can you try recocering the wallet without the passphrase and see whether you see your transaction.

Note: The pasphrase is not the same as the wallet password.

---

If that does not work...
Can you import the seed in a different wallet? (E.g. electrum downloaded from source. Be sure to check the gpg signatures etc.)

If it shows your missing transaction then it would suggests that there is an issue in looking up balances.

If it doesnt it would suggest that the issue is the displaying of an unassociated address (or that you used a different passphrase/wallet when generating this address)

**Comment by cferr716** [comment]
@6102bitcoin I've been doing some more reading and trying to educate myself better. I'm thinking I was getting confused between the wallet password and the passphrase. This is why I contradicted myself in the issue above. I've tried a handful of combinations of phrases and I was not able to recover. I'm going to attribute this to user error and a learning experience for myself. Time to roll up my sleeves and continue to learn.

**Comment by craigraw** [comment]
No problem and thanks for this feedback.

**Comment by full-metal-bull** [comment]
I'm having this exact same issue with a recent transaction from CashApp to Sparrow, but even stranger. Sparrow is displaying my most recent transaction, but not the old transaction. If I import wallet to Blue Wallet with seed and passphrase only the old UTXO is present. If I import to Blue Wallet with seed and without passphrase neither UTXO is present.

Easy solution is to just send all funds to a new wallet, but I'd like to figure out how/ why this ishappening.

**Comment by craigraw** [comment]
> Sparrow is displaying my most recent transaction, but not the old transaction.

Have you tried testing against a public server to verify it's not your configured server?

**Comment by full-metal-bull** [comment]
Late reply here, but I believe I mistyped my passphrase. I've been working through a guess of where I may have miskeyed, but I have not got it quite yet. If I don't get it while connected to my server I will try the list on a public server, and if both fail well... I believe I have lost my first sats.

**Comment by craigraw** [comment]
Sorry to hear - take your time and work through the options systematically.

**Comment by sparemenomatterwhat** [comment]
Hi, I am experiencing a somewhat similar issue. However, I can see the balance via blockchain explorers but not in my wallet. I have an empty wallet and empty transaction history. The below is a link to my wallet balance and the funds were sent from Binance

https://www.blockonomics.co/#/search?q=bc1qye4rm4ladg6vzk4hw80wtdl4hs8ye8ltsk7jcv

**Comment by sparemenomatterwhat** [comment]
another link to the transaction for which I cannot view within my sparrow wallet. https://mempool.space/address/bc1qye4rm4ladg6vzk4hw80wtdl4hs8ye8ltsk7jcv
<img width="837" alt="Screenshot 2023-02-09 at 3 33 19 PM" src="https://user-images.githubusercontent.com/124855039/217746897-417beeac-5f47-43f6-88da-a76d1eb458b0.png">
<img width="882" alt="Screenshot 2023-02-09 at 3 33 32 PM" src="https://user-images.githubusercontent.com/124855039/217746908-0224cbcc-4bc4-4c48-abcf-5bd360245acb.png">

**Comment by craigraw** [comment]
@sparemenomatterwhat Please use the support channel at t.me/SparrowWallet for support, and Github for bugs and feature requests.

That said it's clear from the `Wallet loading history` panel above that no wallet loading has taken place, so it is unsurprising that no transactions are displayed. Ensure you are connected to a server (the toggle on the bottom right is on). Test your connection in the Preferences > Server dialog.

**Comment by xbikashtee** [comment]
Fund send from blue wallet to sparrow wallet using blockstream.info server. made two transition, however sparrow wallet isn't showing any fund nor transition, please help, did all the step above but still not showing the fun

**Comment by craigraw** [comment]
@xbikashtee you are not connected to any server. Please use the support channel as described above.
