### ISSUE TITLE
HELP: after 3 confirmations SSL handshake not finalized

### ISSUE THREAD

**Issue by DutchPete** [sparrowwallet/sparrow#1251]
I transferred bitcoin from a website to my Sparrow wallet. After 3 confirmations Sparrow gave a popup message saying the SSL handshake could not be finalized, and the question was if I wished to continue.

Since the popup said it could be due to a man-in-the-middle attack, I clicked on NO.

I can see the funds in my Sparrow Transactions tab (the wallet on the website is empty), they are not red or greyed out, but presumably I cannot use them. Is there a way to check if those funds are usable?

Could it be due to my VPN? Do I need to finalize the transaction? If so, how?

I am a bit desperate. Please help or point me in the right direction.
Many thanks in advance.

**Comment by DutchPete** [comment]
12 hours on and the bitcoin is still shown in Sparrow, just like the bitcoin I put there a long time ago.

Apart from in the Transaction tab mentioned above, it is also shown in the UTXO tab. May I therefore assume all is well, that I have full control of the funds and can use them normally?

**Comment by craigraw** [comment]
See https://sparrowwallet.com/docs/faq.html#pkix-path-validation-failed. Probably, just an expired certificate.
