### ISSUE TITLE
Set an default public server in setttings 

### ISSUE THREAD

**Issue by skyerjoe** [sparrowwallet/sparrow#1257]
is this possible ? 

best regards

**Comment by rapidlab309** [comment]
There are like 6 public servers saved to Sparrow's settings. There's no "default", but they are all could be used as.
If one fails, others will be used as fall back, a backup.

As long as you stay online, and no unattended disconnections, the one you're using will be kept used.

**Comment by craigraw** [comment]
Yes just configure a public server details in the Private Electrum tab.
