### ISSUE TITLE
[FEATURE REQUEST] Display QR Code of Final Transaction

### ISSUE THREAD

**Issue by MeisterEdersCarpentry** [sparrowwallet/sparrow#1258]
To increase convenience for sparrow as an offline signer it would be quite helpful to show the final transaction as a QR Code instead of just a text file.
Since sparrow already has a great QR interactivity, this should be a great addition.

Usecase:

Run sparrow on TailsOS offline. Use Samourai Sentinel as watch only. 
It already works like this: 

1. Scan Sentinel PSBT with Sparrow
2. Sign TX with Sparrow
3. Copy signed TX on microSD
4. Import it into Sentinel
5. Broadcast

I tested it also with an external QR generator app. Worked. 
Doing it in Sparrow directly would increase convenience.
THX

**Comment by craigraw** [comment]
Already implemented. See the File menu after clicking Show Final Transaction:

<img width="234" alt="Screenshot 2024-02-05 at 07 51 45" src="https://github.com/sparrowwallet/sparrow/assets/862166/23255418-531a-4130-b40d-e1746ad720b2">
