### ISSUE TITLE
Some labels missing (for zero balance addresses) when exporting receive addresses CSV

### ISSUE THREAD

**Issue by statusquont** [sparrowwallet/sparrow#1259]
When exporting receive addresses, it seems as if any address with a zero balance doesn't have it's label included in the resulting CSV file, even though those addresses do actually have labels in the GUI. I realized this after seeing gaps in the CSV of addresses with no labels and wondered why. Once I turned off Hide Empty Used Addresses in the GUI I figured out what was going on. 

This could cause people to accidentally re-use an address if they normally practice good UTXO management by labeling everything, and then pull a "fresh" address from the CSV that doesn't have the label included in the exported file.

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 78406fd0.
