### ISSUE TITLE
Multisig for taproot

### ISSUE THREAD

**Issue by weesparrow** [sparrowwallet/sparrow#1262]
This is more of a question than an issue/request.

I see that the Taproot (P2TR) option is only available for single signature wallets. It is my understanding that one of the main benefits of Taproot is increased privacy for multisig. Is this correct? And if so, is there a plan to add Taproot support for Multi Signature?

Cheers

**Comment by craigraw** [comment]
Taproot multisig does indeed offer the potential for increased privacy, but at the cost of additional complexity. For example, schemes like FROST provide m-of-n multisig with an onchain footprint that appears like singlesig, and with the ability to replace signers without moving funds. However, nonces must be precomputed, shared and saved amongst all the signers, and can never be reused without risking loss of funds. These are significant technical and UX hurdles, and as a result progress has been slower than some have expected in making FROST practically available. Standards and hardware devices are still emerging.
