### ISSUE TITLE
Add Option do Decrease Animated QR Code Frame-rate

### ISSUE THREAD

**Issue by odudex** [sparrowwallet/sparrow#1265]
High resolution at a high frame-rate result in high bandwidth and a good UX, unless the signer hardware can't keep up with it.
Krux devices can scan even the high resolution QRs, however, due to the high frame-rate, it will skip some frames. The time it takes for Krux to process each frame is higher than the period each frame is exposed on Sparrow. This is not a big deal, since UR has features that deal very well with skipped frames, but other issues can happen:
Depending on device, display, ambient lights, etc camera can adjust its exposure time or even "merge frames". Like when we take a picture in dark environments, it's easier to get a blurred picture.
I noticed some times I get 2 QR code frames merged by the camera on tests, and I believe an option to reduce the frame-rate to, for example, 1Hz, would be very beneficial to some low cost devices.

**Comment by craigraw** [comment]
As of 8baa8e2e, you can change the frame rate on animated QRs by using mouse scroll while the mouse pointer is over the QR image, between a maximum of 2 seconds and a minimum of 100 milliseconds period delay between frames.

**Comment by odudex** [comment]
This is awesome! Thanks!
