### ISSUE TITLE
Increase timeout of (whirpool) JavaHttpClientService

### ISSUE THREAD

**Issue by remcoros** [sparrowwallet/sparrow#1266]
I was investigating connection issues when mixing using Tor. I've seen past reported issues about these same issues, mainly because Tor can be unstable or slow at times, which causes a lot of exceptions and timeouts.

I noticed in the logs, that the timeout the http client is using is 30 seconds. I think that is defined here: https://github.com/sparrowwallet/nightjar/blob/master/src/main/java/com/sparrowwallet/nightjar/http/JavaHttpClientService.java

The following commit, made this a configurable option on JavaHttpClientService: https://github.com/sparrowwallet/nightjar/commit/aadfb99a53c7164c1ebeaec27847cb6ade6a0f55

but this option is not used consistently and the default of 30 seconds is used (like for Whirpool). In other places, the second constructor is used with values of 60 seconds or even 120 seconds, like here: https://github.com/sparrowwallet/sparrow/blob/master/src/main/java/com/sparrowwallet/sparrow/soroban/Soroban.java#L34 and https://github.com/sparrowwallet/sparrow/blob/master/src/main/java/com/sparrowwallet/sparrow/net/HttpClientService.java#L18

I understand increasing 30 seconds to for example 60 seconds is not a "solution" for slow Tor connections, but from my personal testing, 30 seconds is often not enough.

Can this timeout be increased, or maybe made configurable?

Thanks!

**Comment by craigraw** [comment]
Thanks for pointing this out. I've increased the timeout to 60s in 3f72a84a.
