### ISSUE TITLE
Replacing one of my devices in a Multisig wallet without having the addresses change

### ISSUE THREAD

**Issue by Gerosmcdonald1062** [sparrowwallet/sparrow#1267]
I have attempted to link my new Trezor using the same seed words as the previous device. However, I can't seem to duplicate the same master fingerprint and therefore I can't sign any transactions. Any help would be appreciated! Since August 2023

**Comment by craigraw** [comment]
If your Trezor is not giving you the same master fingerprint, there are only two possibilities: either the seed words were different, or you were using a (different) passphrase. You can enable/disable the use of a passphrase using the USB button in the bottom right of the app.

Closing as a user support request.
