### ISSUE TITLE
Build issues in IntelliJ

### ISSUE THREAD

**Issue by MisterSeven144** [sparrowwallet/sparrow#1268]
Newbie here, so apologies if this isn't the right place to post.

Getting build errors in IntelliJ.

<img width="1286" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/159790687/835d45b2-1747-42fc-9e1e-5691d91a43ee">

Gradle JVM setting is `openjdk-21`.  Anything else I should check?

**Comment by craigraw** [comment]
You are welcome to ask development related issues here, although I will close this off as it's not a feature or a bug.

It's difficult to advise, other than to say the obvious - the submodule drongo is not on the main project's classpath. Check your module settings, mine looks like

<img width="319" alt="Screenshot 2024-02-16 at 07 47 25" src="https://github.com/sparrowwallet/sparrow/assets/862166/b201dc53-d344-4da1-b8cf-2a9685328164">

**Comment by MisterSeven144** [comment]
I don't have the `drongo` source in this project.  Do I need to somehow point to code outside of this project?

<img width="327" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/159790687/cd97a776-7a0c-47a3-8d8e-4421307e7a00">


The `drongo` folder is on my machine as a sibling to the `sparrow` folder (after git cloning both), so do I need to import it as a submodule into this project?

**Comment by craigraw** [comment]
drongo is a git submodule for sparrow. Did you clone recursively as directed in the README?

**Comment by MisterSeven144** [comment]
Thanks, that was it.  Missed that part. :-(

**Comment by MisterSeven144** [comment]
Building from IntelliJ is working now, but cannot run the app.  Tried with both `openjdk-21` and `temurin-21`.  Please advise, thanks.

<img width="1385" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/159790687/e9d022e6-d434-4818-a8dc-2a2e64539170">

**Comment by craigraw** [comment]
Run Sparrow using `./gradlew run`, or the Intellij equivalent.

**Comment by MisterSeven144** [comment]
`./gradlew run` works from a terminal window, and I can also run it from IntelliJ, but I'm hoping to be able to debug from IntelliJ.  Would you know which run configuration settings are needed to launch from IntelliJ?

**Comment by PrinceOfEgypt** [comment]
I can debug with these settings:

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/e4d36cef-8c5d-4a28-b032-54c1aee87f05)

**Comment by MisterSeven144** [comment]
@PrinceOfEgypt that worked -- thank you!
