### ISSUE TITLE
Certificate Renewal or Man in the MIddle Attack Concern

### ISSUE THREAD

**Issue by cryptomoon2140** [sparrowwallet/sparrow#1269]
Hello Sparrow dev team,

I received the following popup in my Sparrow titled SLL Handshake Failed with the text "The certificate provided by the server at **electrum.diynodes.com** appears to have changed. **This may be simply due to a certificate renewal, or it may indicate a man-in-the-middle attack.** Do you still want to proceed". I did not click Yes or No and just force quit sparrow and now looking to run my own bitcoin core node, however I still need to understand if my device is compromised.

After checking when the certificate was issued by running the following code in my terminal, it indicated Jan 26 2024 with an expiration of Apr 25 2024. 

`openssl x509 -in /full/path/to/electrumDiynodesCertificate.pem -text -noout`

This is weird because I had not gotten the popup between Jan 26 2024 and Feb 10 2024 when I would check Sparrow, then the popup started to occur after Feb 10 2024. Additionally, the Serial Number returned in my terminal after running that code above is different than the serial number noted in SSLChecker.com when I search for electrum.diynodes.com. And finally, SSLChecker is flagging this server as missing the root certificate which is also a red flag.

**That being said, is this popup due a certificate renewal or not? Can you confirm there’s no man-in-the-middle attack?**

**If possible, could you also provide me with the Manifest and Manifest Signature file for the 1.8.1 release? I didn't realize I needed to verify the Sparrow release before installing it and now that Sparrow is on 1.8.2, I can't find the 1.8.1 files. Please let me know if this is also a cause for concern regarding the possible man-in-the-middle attack.**

I've always kept a fully air gapped solution with my keys never touching the internet and always verified send addresses between my cold storage device and what Sparrow showed.

Thank you very much.

**Comment by craigraw** [comment]
I've seen a few people get this who connect to electrum.diynodes.com, so I have no reason to believe it is anything other than a certificate renewal. Can always ask @diynodes on Twitter too. 

> This is weird because I had not gotten the popup between Jan 26 2024 and Feb 10 2024

It may be that the certificate was only replaced some time after it was issued.

> If possible, could you also provide me with the Manifest and Manifest Signature file for the 1.8.1 release?

All releases are here on Github. https://github.com/sparrowwallet/sparrow/releases

I would not worry too much about this warning. However, that it is pushing you to consider running your own node is a good thing!

**Comment by cryptomoon2140** [comment]
Hello Craig, thank you so much for your prompt reply and for sharing the releases. Also thank you for your creation of Sparrow and helping people all around the world manage their cold storage. I wish you and your family all the best.
