### ISSUE TITLE
Connection Switch Bugs

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#127]
Tor to Non-Tor connection switch or VPN to Non-VPN switch causes issues (see comment in https://github.com/sparrowwallet/sparrow/issues/29).

Outstanding Action:  Switching connection could restart sparrow?
Proposed Priority: Low

**Comment by craigraw** [comment]
I'm not sure there is still an issue here. Many fixes have occurred since the original issue was posted. If there is still a problem, please list steps to recreate, otherwise I suggest closing both of these off.

**Comment by 6102bitcoin** [comment]
I just broke your comment out into this seperate issue. 

Sounds like it's been fixed since the comment was made and this can be closed.

The other issue has a suggested outstanding action.
