### ISSUE TITLE
Bug: Error while importing testnet multisig from Nunchuk

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#1272]
Following error is shown when trying to import this wallet on testnet:

https://github.com/sparrowwallet/sparrow/assets/93251679/d2e3a539-43a8-43ac-bce6-b714906c0ddb

The error:
<img width="353" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/93251679/d89e26b8-8b07-40c9-8283-dd78091699d0">

Reproduce steps:
- Create a new wallet in Sparrow
- Click the camera-icon under Settings -> Script Policy -> Descriptor
- Scan the QR from Nunchuk

**Comment by seedhammer** [comment]
This might be a Nunchuk bug: https://github.com/nunchuk-io/nunchuk-android/issues/46

**Comment by craigraw** [comment]
This export is non-standard - rather than export an output descriptor, it is actually exporting a block of text starting with
```
# Exported from Nunchuk
Name: test
...
```

It appears to be somewhat similar to the Coldcard multisig wallet export.

**Comment by seedhammer** [comment]
View wallet config -> ... -> Export wallet configuation -> QR code

**Comment by bakaoh** [comment]
hi, i have checked with client team, currently we are using BC-UR2 crypto-bytes (supported by Keystone and Passport old firmware) when exporting QR code, we will add option for BC-UR2 crypto-output (BCR-2020-010) soon

**Comment by seedhammer** [comment]
Nunchuk will resolve.
