### ISSUE TITLE
Certificate Expired Error

### ISSUE THREAD

**Issue by wijg1** [sparrowwallet/sparrow#1274]
When I attempt to connect Sparrow to my raspiblitz, I get the following error:

Could not connect:

Certificate expired at Sun Dec 24 17:00:12 CST 2023

NotAfter: Sun Dec 24 17:00:12 CST 2023

I updated Electrum on my raspiblitz and everything is the latest version as of 2/20/2024 (Raspiblitz 1.10.0, Bitcoin 25.0, CND .16.4-Beta).  Why would I have this error?

**Comment by craigraw** [comment]
I think this question would be better directed to raspiblitz. It appears that the SSL certificate on your raspiblitz (the one that is used by Electrs) needs to be updated.
