### ISSUE TITLE
Password needs to be entered multiple times when signing messages on a Taproot password protected wallet

### ISSUE THREAD

**Issue by jmbinette** [sparrowwallet/sparrow#1277]
Sparrow 1.8.2

When signing multiples messages in the same wallet, the password needs to be entered 2, 3 and subsequent times for each additionnal wallet address you sign.

**Comment by craigraw** [comment]
Yes - this is because Sparrow does not keep the seed unencrypted in memory. There is no way to change this without decreasing the security of the wallet.

**Comment by jmbinette** [comment]
I think I did not explain it well.

**Taproot Signature #1**
Enter message to sign
Enter correct password

**Taproot Signature #2**
Enter message to sign
Enter correct password 1st time
Enter correct password 2nd time

**Comment by craigraw** [comment]
I can't reproduce this. Please provide clear steps to reproduce.
