### ISSUE TITLE
Feature Request: Include Seconds on CSV export

### ISSUE THREAD

**Issue by MaximusMcCann** [sparrowwallet/sparrow#1278]
It is possible for multiple blocks to complete within the same minute.  Exporting a CSV of transactions (as of Sparrow 1.8.2) does not include seconds :(.  Please include the seconds.

**Comment by craigraw** [comment]
What is the use case for this? The CSV export simply mirrors the transactions table.

**Comment by MaximusMcCann** [comment]
1. Accuracy.  Two blocks can complete in the same minute; want to ensure we see them in the correct order in the software.
2. Accounting.  Using additional software for taxes and such, the order can become a problem if the accuracy is only to the minute.
3. Standardization.  ISO8601 is a standard for time, why not use it like?

**Comment by craigraw** [comment]
Good reasons :)

Seconds added to the Transactions and UTXOs CSV export in 6d7f0222.
