### ISSUE TITLE
Balance is wrong when many coins are 'chained'

### ISSUE THREAD

**Issue by pythcoiner** [sparrowwallet/sparrow#1282]
![image](https://github.com/sparrowwallet/sparrow/assets/124568858/3cc7d0d0-8a62-48af-84c4-6eb09dd6617c)

all these tx are chained the balance should be < 1.118 BTC (signet there), but some changes are deteced as incoming coins...

**Comment by craigraw** [comment]
What server are you connected to? It sounds like the problem lies there.

**Comment by pythcoiner** [comment]
it was bitcoin core v25

**Comment by craigraw** [comment]
Can you provide steps to reproduce? When connected directly to Bitcoin Core, Sparrow is calling the `listsinceblock` RPC call.

**Comment by pythcoiner** [comment]
> Can you provide steps to reproduce? When connected directly to Bitcoin Core, Sparrow is calling the `listsinceblock` RPC call.

like this : 

utxo0 ---> payment_0
           ----> change_0


change_0 ---> payment_1
                 ----> change_1


change_1 ---> payment_2
                 ----> change_2


change_2 ---> payment_3
                 ----> change_3

the issue appear only on tx that are still in the mempool

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in ae291086.

**Comment by pythcoiner** [comment]
thank you to alway respond fast, even for minor issues!
