### ISSUE TITLE
Verified update

### ISSUE THREAD

**Issue by casey** [sparrowwallet/sparrow#1285]
I had an idea for an upgrade mechanism which has some nice properties. It works like this:

1. User installs sparrow wallet for the first time, ideally verifying that the binary is signed, etc.
2. For future updates, the user downloads the binary release as usual, but then from within their existing sparrow wallet, has the ability to verify that the release was signed. To do this, sparrow would embed a copy of the public key used to sign releases.

This has the nice property that as long as a user is able to get a good copy of sparrow once, they can verify future releases without needing to know anything about PGP.

**Comment by craigraw** [comment]
Great minds think alike - keep an eye on the next release ;)
