### ISSUE TITLE
Erroneous parse of taproot control block

### ISSUE THREAD

**Issue by irriden** [sparrowwallet/sparrow#1286]
As of e50cc7126d47271f3ef6fdd63bccc37c01ce41ea, sparrow parses the taproot control block `c1d7e21cf0676b1e0ace984819e0327d23e69fa208509c5bd4924b2f09fc4f5cc2` as shown below in the `WitnessScript` box:

![image](https://github.com/sparrowwallet/sparrow/assets/135253179/a6326190-708e-4328-91ae-f92817f57800)

What it actually consists of is:
1. `0xc1`: tapleaf version `0xc0`, odd parity for internal key
2. `d7e21cf0676b1e0ace984819e0327d23e69fa208509c5bd4924b2f09fc4f5cc2`: internal key

Full signet txid of the transaction:
https://mempool.space/signet/tx/ecea2f7a9c709ea32b71128b4b2d703e2421eb3a357be5cab6275a2b76b2f095

**Comment by craigraw** [comment]
Thanks for the bug report. This display has been improved in 0ed8c6af:

<img width="858" alt="Screenshot 2024-02-28 at 10 30 32" src="https://github.com/sparrowwallet/sparrow/assets/862166/8af0981b-ddad-484e-88cb-70e456c83f3a">
