### ISSUE TITLE
MultiSig wallet creation dialog accepts wrong derivation path

### ISSUE THREAD

**Issue by 1ma** [sparrowwallet/sparrow#1287]
I noticed that while creating a cold multisig wallet (Airgapped Hardware Wallet > SeedSigner > Scan) Sparrow 1.8.2 accepts xpubs with the wrong derivation path.

In my case I was testing things out on Testnet and forgot to set the network to Testnet on my SeedSigner, so Sparrow accepted the `m/48'/0'/0'/2'` xpubs instead of the correct `m/48'/1'/0'/2'`.

While the resulting multisig wallet still works I uncovered a downstream bug of that, and is that when you add a New Account to this non-standard wallet Sparrow then expects the wrong derivation path `m/48'/0'/0'/3'` instead of `m/48'/1'/1'/2'`.

I think it would be better for UX to show an error message and reject the xpub if the [coin type](https://bips.xyz/48#coin-type) component of the derivation path doesn't match the expected one.

Also tested the reverse, Sparrow mainnet accepts Testnet multisig xpubs (`m/48'/1'/0'/2'`) and I don't think it should either.

**Comment by craigraw** [comment]
I agree, Sparrow should disallow paths that match other networks if derivation path validation is turned on. Implemented in 803e43cb.
