### ISSUE TITLE
Max send amount hidden until send-to address & label is entered

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#129]
Unclear that a `destination address` and a `label` have to be added before the utxo input amount updates. ([e.g.](https://twitter.com/statusquont/status/1395448989592391682?s=20))

Outstanding Action: Update max send amount on switching to the send tab
Proposed Priority: Low

**Comment by craigraw** [comment]
Added in dd14621.

We don't know the script type of the address yet, so the amount field is simply set to the total UTXO value. It will reduce by the transaction fee once the address and label have been entered to create the transaction.

**Comment by 6102bitcoin** [comment]
Awesome
