### ISSUE TITLE
Sparrow 1.8.2 Krux airgapped-hardware-wallet doesn't show the option to input a file

### ISSUE THREAD

**Issue by tadeubas** [sparrowwallet/sparrow#1291]
When importing an airgapped hardware wallet using Krux option, it doesn't show the button `Import file...` as it should. I've attached a XPUB and a ZPUB file to this issue exported by Krux to a SD card (the extension is `.pub`, I concatenated `.txt` in order to be able to attach it here)

![image](https://github.com/sparrowwallet/sparrow/assets/5518496/f0099a47-b00f-4857-88f4-0541c51f810f)
[XPUB.pub.txt](https://github.com/sparrowwallet/sparrow/files/14453933/XPUB.pub.txt)
[ZPUB.pub.txt](https://github.com/sparrowwallet/sparrow/files/14453934/ZPUB.pub.txt)

**Comment by craigraw** [comment]
I was unaware Krux supported export of wallet details to a file. Added in 6a496894.

<img width="762" alt="Screenshot 2024-03-01 at 07 48 49" src="https://github.com/sparrowwallet/sparrow/assets/862166/b91d9f7e-31cf-4b0f-afb8-66c9feb721e2">
