### ISSUE TITLE
Developers should sign every single release file instead of the manifest-file

### ISSUE THREAD

**Issue by Steampowered-hippo** [sparrowwallet/sparrow#1292]
When I try to teach non-technical users Bitcoin, I want to work with them using the Sparrow Wallet. The "Verify Release" is an important step, that should not be skipped. Verification with gpg is complicated itself, but becomes more complicated, when they have to do additional steps (e. g. calculating a hash for a file and compare it manually). This is difficult to teach and difficult for the students to understand. This problem occurs especially with Windows users.

It would be much easier, if all the single release-files for all the different OS would be signed by the developers. This would result in less steps and easier verification process.

So Sparrow Wallet would be more accessible for non-technical users (which I try to orangpill)

**Comment by craigraw** [comment]
No, this means creating a signature for each release file, which would almost double the number of listed files on the downloads page. It is also much more computationally expensive to sign and verify large files.

That said, you'll be happy to know verification will get much easier from the next release onwards :)

**Comment by Steampowered-hippo** [comment]
To double the number of files is no problem with a good UI-layout. You could follow the concept of Electrum Wallet on its download site.

But glad to here that you already found a solution.Looking forward to it...
