### ISSUE TITLE
[Feature Request] Enhancements for Trezor Safe 3 support

### ISSUE THREAD

**Issue by LoicPandul** [sparrowwallet/sparrow#1297]
After testing the Trezor Safe 3 with Sparrow Wallet, I've encountered two issues that could impact user experience and security :
- First, it's currently not possible to enter the passphrase via the computer's keyboard, a feature available in Trezor Suite which adds a layer of convenience ;
- Second, when signing transactions from Sparrow, the Trezor Safe 3 does not display the recipient's address or the amount being sent on the hardware wallet's screen, only showing the fees. This limitation necessitates blind signing, which could pose security risks.

Apart from these two little things, the support of the Safe 3 looks perfect, thank you! 
Thank in advance for your help with this.

**Comment by craigraw** [comment]
Thanks, appreciated :)

> First, it's currently not possible to enter the passphrase via the computer's keyboard

Correct, this is not allowed for security reasons: https://github.com/bitcoin-core/HWI/pull/287

> Second, when signing transactions from Sparrow, the Trezor Safe 3 does not display the recipient's address

What the Trezor displays entirely depends on the firmware on the device itself, not Sparrow. Are you perhaps sending back to yourself (consolidation)? Try signing for an external spend.

**Comment by voltagebushels82** [comment]
> Correct, this is not allowed for security reasons: [bitcoin-core/HWI#287](https://github.com/bitcoin-core/HWI/pull/287)
> 
> >
Unlike Trezor One, Trezor Safe 3 does not have a touch screen. Entering the passphrase with only two buttons is a nightmare. The lack of a way to enter the passphrase using the computer's keyboard makes Sparrow unusable for me, that's sad.
