### ISSUE TITLE
[Feature request] Direct Link to Sparrow GitHub Releases in Wallet (UX)

### ISSUE THREAD

**Issue by ugzv** [sparrowwallet/sparrow#1301]
### Issue:
The Sparrow Wallet interface lacks a direct link to its GitHub releases page. Users would benefit significantly from easy access to these software updates. 

### Expected:
The addition of a direct link to the GitHub releases page in the Sparrow Wallet. This will facilitate seamless software updates for users.

### Suggestion:
I propose incorporating a hyperlink labeled "GitHub Releases" under the 'Help' section. This will direct users to Sparrow's GitHub releases page: https://github.com/sparrowwallet/sparrow/releases. This change is expected to enhance user convenience and application usability.

**Comment by craigraw** [comment]
Sparrow already provides such a link (to https://sparrowwallet.com/download/) in the status bar when there is a newer version.

I'm not sure there is much to be gained from implementing your suggestion in addition to this, but perhaps I'm missing something.

**Comment by craigraw** [comment]
No response, closing this off.
