### ISSUE TITLE
Anti virus SPHOS complaining when opening Sparraw 1.8.4

### ISSUE THREAD

**Issue by Pann148** [sparrowwallet/sparrow#1303]
Hi,
SOPHOS shows this activity every time I open Sparrow 1.8.4
![2024-03-08_11-33-15](https://github.com/sparrowwallet/sparrow/assets/162664925/650d734c-e681-4162-8196-5a2b75b734b9)

Not sure if this is an issue or not but it looks scary to me.
Thanks,
Pan

**Comment by craigraw** [comment]
It’s a false positive. The message refers to HWI 2.4.0, which is expanded from the Sparrow app when required to communicate with a USB hww.

There's nothing Sparrow can do about this. What you can do however is to 
1. Unblock this file: https://support.home.sophos.com/hc/en-us/articles/360022024211-Excluding-a-file-or-application-from-Machine-Learning-detection
2. Report this false positive to Sophos
