### ISSUE TITLE
setting "Block explorer" to "none" still shows "Open in Block Explorer" when right clicking a transaction

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1306]
Setting "Block explorer" to "none" still shows "Open in Block Explorer" when right clicking a transaction. I would expect that option to go away. When I try and click it, it does not do anything though. However, if that option is there, I think there must be some block explorer configured and I'm concerned it could be accidentally clicked. This then wastes time going into preferences to find out it is really set to none.

**Comment by craigraw** [comment]
Thanks, I've removed it from the context menu in this situation in d1ac5b07. Restart Sparrow or refresh the wallet to reconfigure the context menus.
