### ISSUE TITLE
"Recieve to" doesnt work

### ISSUE THREAD

**Issue by exitfiat** [sparrowwallet/sparrow#131]
Behavior:
When doing a right click on a utxo in the UTXOs tab and pressing on "Recieve to" at any UTXO nothing happens.

Expected Behavior:
Switch to recieve tab with a recieve adress which will direct funds to the selected utxo in the utxo tab.

Version 1.4.1
Ubuntu 21.04
![119367135-f1639280-bcb1-11eb-9344-008ebfffceba](https://user-images.githubusercontent.com/51097237/119367544-5919dd80-bcb2-11eb-9600-7b8e31d5bacb.png)

**Comment by craigraw** [comment]
Thanks for the report. Fixed in 911153e.

Note you won't be directing funds to that UTXO, but rather to the same address as that UTXO. This is not generally good practice (but certainly is valid).
