### ISSUE TITLE
1.8.4 flagged as malware

### ISSUE THREAD

**Issue by user7901** [sparrowwallet/sparrow#1310]
Sparrow 1.8.4. on Windows 11
When a wallet is opened is created an ".tmp" file at "...\AppData\Roaming\Sparrow\hwi\..."
With 1.8.3 and 1.8.4 versions Bitdefender flags that file as "Gen:Variant.Lazy.456623" (a trojan.lazy/infostealer).
Uploading the file to virustotal.com it gives 28 detections of that variant, so it is not only a Bitdefender false positive. I send a pdf of that detections.
[sparrow.pdf](https://github.com/sparrowwallet/sparrow/files/14550415/sparrow.pdf)

**Comment by craigraw** [comment]
It is (as you say) a false positive. Antivirus programs use heuristics (non exact matching) to try identify files, which means false positives happen. The file the AV is flagging is HWI, a well known program written by @achow101 (a Bitcoin Core maintainer) which has recently has a new release, v2.4.0.

Note the HWI file the AV is flagging can be deterministically built from source, so we can be sure of what it does - the binary file matches exactly.

You can do two things - configure your antivirus to stop monitoring the `...\AppData\Roaming\Sparrow\hwi` folder (which doesn’t change) and report this false positive to your AV vendor. With enough reports, hopefully the we can get the AV algorithms to change.

*Technical note:*

If you wish to confirm that this is not a virus, here are the steps to do so:
1. Download the windows specific .zip from https://github.com/bitcoin-core/HWI/releases/tag/2.4.0.
2. Extract `hwi.exe` from the zip file and compare it against the .tmp file in `...\AppData\Roaming\Sparrow\hwi`. You can use a tool like `diff` to ensure that it is an exact match, byte for byte.
3. If you wish to go further, you can build `hwi.exe` yourself deterministically, so you can verify that the release binary is actually compiled from the source. [There are instructions to do so here](https://hwi.readthedocs.io/en/latest/development/release-process.html#deterministic-builds-with-docker).

**Comment by MarMan420** [comment]
Sparrow 1.8.4. on Windows 11
Same issue with McAfee but there is no way to exclude the folder as the AppData\Roaming\ folder is hidden so you can't exclude it. Also noted it only creates file when connecting to sparrow with a Trezor, not Ledger or Passport wallet.

**Comment by craigraw** [comment]
For McAfee users, you can also do the following:
1. Copy the file McAfee is flagging (`hwi2.4.0...tmp`) to some other location.
2. Exclude that file from McAfee scan
3. Close Sparrow
4. Open the file `AppData\Roaming\Sparrow\config` in Notepad
5. Change the value of the `"hwi"` entry to point to the file McAfee is now excluding
6. Save the `config` file and exit Notepad
7. Restart Sparrow

**Comment by MarMan420** [comment]
This is a great solution until I dump McAfee… Thank you Craig!
