### ISSUE TITLE
Sparrow Wallet Version 1.8.4 and Bitcoin Core Node: Connection Issues

### ISSUE THREAD

**Issue by ozziekanga** [sparrowwallet/sparrow#1311]
I was previously running Sparrow Wallet Version 1.8.2 with my Bitcoin Coin node on my MacBook Pro M1 notebook. Sparrow was connecting to the Node without any issues and within around 30 seconds. Yesterday I dowloaded and verified the latest version of Sparrow 1.8.4 and installed it after taking all verification steps. However, the Sparrow Wallet keeps timing out after a few minutes and will not connect to my Node. I've tried this multiple times and get the same result.

Is there an issue with Sparrow Wallet Version 1.8.4, or could there be some other issue at play? Thanks for your help. Phil

**Comment by ozziekanga** [comment]
Further to my original post, I re-installed Sparrow Wallet 1.8.2.  When I then launched Sparrow Wallet, it will still not connect to the Bitcoin Core Node that is running Version 25.0.0.  I first get the "Connect Error (Operation timed out)" message in the bottom left corner.  When I check system preferences and re-point to the Bitcoin_Node folder (/Volumes/(name of my external SSD running Bitcoin Core)/BTC_Node), I still get the timed out message when I test the connection.  A short while later, I then get the error "Socket Error (Socket is closed" message in the bottom left corner.

I've logged out from Sparrow, the Bitcoin Node and my computer and restarted the process.  However, Sparrow will still not connect to my Bitcoin Node.  Will appreciate feedback so I can get this resolved.

**Comment by craigraw** [comment]
There is no known issue (or recent changes in 1.8.4) that I can think of, so it's almost certainly something local to your setup. Are you able to use `bitcoin-cli` to talk to your node? For example:
```
bitcoin-cli getnetworkinfo
```

**Comment by ozziekanga** [comment]
Thanks for your help.  I believe the issue was local.  I just updated my MacOS to Sonoma 14.4 and now Sparrow connects to my Bitcoin Core node in default mode in around 10 seconds.  I had multiple issues with the pervious version of Sonoma, including connecting Sparrow to my Bitcoin Node. 

I have two questions as I'm very new to running my Bitcoin Node and Sparrow and I do not have any developer background:
1. Pervious with Sparrow 1.8.3 I would see the number of BTC and the current value and now I'm only seeing the number of Bitcoin.  Is this a change with Sparrow 1.8.4 or is there some other change I need to make in Sparrow?
2. Where would I input the bitcoin-cli command above to talk to my node? (I presume this would not be in a Terminal window on a Mac)?

Appreciate your further assistance.

**Comment by craigraw** [comment]
Great, closing this off.

> Pervious with Sparrow 1.8.3 I would see the number of BTC and the current value and now I'm only seeing the number of Bitcoin. Is this a change with Sparrow 1.8.4 or is there some other change I need to make in Sparrow?

Your exchange rate source is set in the General Preferences. Possibly there was an error connecting to it on this occasion.

> Where would I input the bitcoin-cli command above to talk to my node? (I presume this would not be in a Terminal window on a Mac)?

Yes, Terminal.
