### ISSUE TITLE
Very slow connection to Sparrow on Trezor One

### ISSUE THREAD

**Issue by bedwards110** [sparrowwallet/sparrow#1315]
I have very slow connection issues when trying to connect my trezor one to my desktop PC Sparrow. It only occurs on this PC. My Windows laptop and Mac have instant connection to my device. The device instantly connects to Trezor Suite on my PC, but takes several minutes on Sparrow. My desktop will be stuck on "scanning" for hardware wallet for a good 5 to 10 minutes. After it finds it, it also takes other 3-5 minutes to sign in. I have turned off firewall, antivirus, updated everything, restarted, uninstall and reinstalled and still have this issue. Any ideas on what it could be? I have a very powerful computer, so specs should not be a problem at all. 
![sparrow](https://github.com/sparrowwallet/sparrow/assets/163154476/53a450ff-db60-4e4b-97c3-6630e38a3754)

**Comment by craigraw** [comment]
It might be something related to how the program Sparrow is using internally, HWI, is scanning certain ports for emulators. See https://github.com/bitcoin-core/HWI/issues/652#issuecomment-1340149342. If you can see if anything is running on those ports, you might be able to diagnose it. You can run HWI directly (on the command line) from `..\AppData\Roaming\Sparrow\hwi\hwi....tmp` if it helps.

**Comment by craigraw** [comment]
See also https://github.com/bitcoin-core/HWI/issues/628

**Comment by craigraw** [comment]
A `LIBUSB_ERROR_ACCESS` is a USB kernel level error - usually temporary from my experience.

You need to supply a command, for example
```
C:\Users\Brandon\AppData\Roaming\Sparrow\hwi\hwi-2.4.04336763555989704409.tmp enumerate
```
to get HWI to actually do anything.

**Comment by bedwards110** [comment]
I tried doing that and it drops down a line and the cursor blinks. It still was stuck on the "scanning" screen for the hardware wallet for 10 minutes. I tried Sparrow on a third laptop and it worked fine (within 10-15 seconds). Not sure why my PC takes excruciatingly long to connect and sign transactions.

**Comment by craigraw** [comment]
Try this:
```
C:\Users\Brandon\AppData\Roaming\Sparrow\hwi\hwi-2.4.04336763555989704409.tmp --debug enumerate
```

**Comment by bedwards110** [comment]
The trezor took about 5 minutes to show up on Sparrow. This is the line that showed up on cmd running the code you sent: 
INFO:hwilib.devices.trezorlib.client:creating client instance for device: webusb:001:10
DEBUG:hwilib.devices.trezorlib.client:sending message: GetFeatures
DEBUG:hwilib.devices.trezorlib.client:received message: Features
DEBUG:hwilib.devices.trezorlib.client:sending message: Initialize
DEBUG:hwilib.devices.trezorlib.client:received message: Features
INFO:hwilib.devices.jadepy.jade_tcp:Connecting to tcp:127.0.0.1:30121
DEBUG:root:Failed to connect to Jade simulator at tcp:127.0.0.1:30121
DEBUG:root:timed out
[{"type": "trezor", "path": "webusb:001:10", "label": "Brandon Trezor", "model": "trezor_1", "needs_pin_sent": true, "needs_passphrase_sent": false, "error": "Could not open client or get fingerprint information: Trezor is locked. Unlock by using 'promptpin' and then 'sendpin'.", "code": -12}]

**Comment by craigraw** [comment]
This is really more of an HWI issue than a Sparrow one. I would suggest opening an issue there with your output: https://github.com/bitcoin-core/HWI/issues - the Trezor devs do look at those issues.

**Comment by bedwards110** [comment]
Okay, thank you for the help.

**Comment by craigraw** [comment]
Closing off as an HWI issue.
