### ISSUE TITLE
Signing by QR does not open camera dialog

### ISSUE THREAD

**Issue by dirkmo** [sparrowwallet/sparrow#1317]
In versions 1.8.3 and 1.8.4 "Sign/Verify Message" does not work on MacOS (aarch64):
In the Sign/Verify Message Dialog window, when I click "Sign by QR", the QR-code window opens up. Then a click on "Scan QR" just closes the dialog window, no camera dialog opens up.

I downgraded to 1.8.2, here the message signing via QR-codes does work.

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 2e847199.
