### ISSUE TITLE
Webcam not reading QR.

### ISSUE THREAD

**Issue by Sparks17** [sparrowwallet/sparrow#1319]
Tried to search known issues regarding this, unable to deduce what my issue is.

My webcam isn’t reading QR from Seedsigner.

Tried different lighting, distances, etc.

Not sure where to start.

Have a simple cheap usb webcam.

Thanks in advance for any tips.

**Comment by craigraw** [comment]
- Have you configured the Seedsigner for use with Sparrow? 
- Does your webcam support HD resolution? 
- Have you tried changing the brightness of the SeedSigner screen (up/down)?

Sparrow normally has no problems scanning the Seedsigner.

Closing this off as a support request.

**Comment by Sparks17** [comment]
Just wanted to follow up.

Got a slightly better webcam.

Sparrow now reading PSBT from Seedsigner with no issue.

Assuming my issue was camera quality.

Thank you!
