### ISSUE TITLE
Minor UI glitch: Sparrow displays uncompressed pubkeys as signatures.

### ISSUE THREAD

**Issue by 1ma** [sparrowwallet/sparrow#1320]
Most public keys stored in Bitcoin transaction inputs are stored in "compressed form". However some UTXOs may have hashed a public key in uncompressed form, where these pubkeys start with `04` instead of `02` or `03` and are twice as long.

Possibly because these public keys are longer than the usual 33 bytes, Sparrow mistakes them for signatures.

Here's a recent example seen in the wild (neither of the following TXs are mine).

https://mempool.space/tx/b2a34a14f1f2887e5606a690df527dc44308b1910e9475cfc65c209c3089a7fb

![pub](https://github.com/sparrowwallet/sparrow/assets/1456708/9cea3969-7970-4f8f-b666-6dbdbaace60d)

For comparison, this other P2PKH transaction spends from a compressed public key (2nd element of the ScriptSig is the usual 33 bytes instead of 65). That one is correctly displayed as `<pubkey1>` in Sparrow: https://mempool.space/tx/632f1a62553a66a4a7c4c29cbbb06288d0f7331cc6b9b256a0c6a02e6f3124b5

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in f3c44e6f.
