### ISSUE TITLE
[FEATURE REQUEST] RBF deactivated by default

### ISSUE THREAD

**Issue by 91anon93** [sparrowwallet/sparrow#1321]
Due to many wallets having this feature disabled by default, it is recommended to keep it that way to avoid any heuristic analysis and altering of the default fingerprint.

![image](https://github.com/sparrowwallet/sparrow/assets/155928550/b4d025a8-2730-4a8c-ad64-d672a7bbae8e)

**Comment by craigraw** [comment]
The number of transactions in the mempool with RBF enabled is currently 69.9%, according to https://bitcoin.clarkmoody.com/dashboard/. So, I think the evidence suggests the reverse is true.

<img width="376" alt="Screenshot 2024-03-16 at 07 44 51" src="https://github.com/sparrowwallet/sparrow/assets/862166/b481e009-7f22-4c20-9a97-ba14b190ec33">
