### ISSUE TITLE
Camera Access issue

### ISSUE THREAD

**Issue by Portal-Doctor** [sparrowwallet/sparrow#1323]
I'm now getting an EXC_BAD_ACCESS (SIGABRT), indicates a crash caused by a memory access violation in Sparrow when trying to read the camera for a Seed Signer import. This type of error often occurs when an application tries to read or write to memory that hasn't been allocated, or that has been deallocated. The specific address causing the problem is at 0x00000000000000b4, which suggests an attempt to access memory near the beginning of the address space, often indicative of a null pointer dereference or a similar issue.

The crash occurs in a thread named Java: atomic-processor-1.

**Comment by Portal-Doctor** [comment]
Notes:  This is now occurring in Sparrow-1.8.2-x86_64 and Sparrow-1.8.4-x86_64 when trying to read from the camera during XPUB key import.

**Comment by craigraw** [comment]
Thanks for the bug report. It looks similar to #1215. Are you able to find the same problematic stack in https://github.com/sparrowwallet/sparrow/issues/1215#issuecomment-1882480531 in the Java `hs_err_pid<pid>.log` crash dump? I've put some guidance to find it in that issue.

Unfortunately I haven't been able to reproduce this somewhat rare issue myself, but I'm starting to get enough information to report the bug on the OpenIMAJ driver. Any help narrowing this down would be much appreciated.

**Comment by craigraw** [comment]
I also have an idea this bug might be avoidable by changing the value of `SCAN_LOOP_WAIT_MILLIS` in [WebcamScanDevice](https://github.com/sparrowwallet/sparrow/blob/master/src/main/java/com/sparrowwallet/sparrow/control/WebcamScanDevice.java). If you run from source (instructions in the project README) changing this value to a higher number might reduce the scan interval sufficiently that a thread race problem does not occur.

**Comment by Portal-Doctor** [comment]
Great idea! I'll rebuild from source and let you know.

Thank you so much! I love my SparrowWallet!

**Comment by Portal-Doctor** [comment]
I built and ran Sparrow using temurin-18 jdk and jre.
Wallets load great.
Import wallet using camera breaks.
hs_err_pid10958.log attached here.

**Comment by Portal-Doctor** [comment]
I tried bumping up SCAN_LOOP_WAIT_MILLIS to 500 and then 2500, but same
result.
I can tell you that I've been using Sparrow Wallet for a long time now on
this machine, so I am suspecting that my camera is dying or the driver has
changed.

But thank you for trying to help!
(I love open source software!)

public static final int SCAN_LOOP_WAIT_MILLIS = 2500;

**Comment by Portal-Doctor** [comment]
I turned on the Use HD Camera Resolutuon setting under the View menu and it's working now!

**Comment by craigraw** [comment]
Great - that's the other thing to try :)
