### ISSUE TITLE
Incorrect sort order for 'sortedmulti' Output Descriptor

### ISSUE THREAD

**Issue by zzzz4** [sparrowwallet/sparrow#1324]
I'm not an expert, so maybe there are details that I'm not aware of.
But at first glance, I don't see how the Actual Value can be correct.
 
# Actual Value
`
wsh(sortedmulti(2,[bf18b8b5/48h/1h/2h/2h]tpubDEMYys3rFh9h7j29f2KQqFTZgF65xjhSU61iABMqvxt51vGJZ7KPYizuYfiF6CoyhTWY7jgcreuJNY8ywbkxiwRu6vpsAamvViv2QDFCctg/<0;1>/*,[bf18b8b5/48h/1h/3h/2h]tpubDF2wmxwnVur42WisBBjVc5c9VcySuhx7MsmrUt9WGjT5YxTjPLS3eijgDXM8Pupa7PnESFtoKecnMAQaaJshsoaZc1ZXQMrSaPtqPejTjp1/<0;1>/*,[bf18b8b5/48h/1h/1h/2h]tpubDEWyPKufntwv2DgRRMTSavF2vHuX8nvPzPN7CHsbZxbiPBtYgcc1SqHWZSzzGeNw6rUYezcfZQ49tH2uVnehMFoiVzH2VG5zFqGGXoe7GtR/<0;1>/*))#q95z9sk2
`

# Expected Value
## if sorting on "Extended public key with key origin" (e.g., `[bf18b8b5...1h/2h]tpubDEW...`)
`
wsh(sortedmulti(2,
[bf18b8b5/48h/1h/1h/2h]tpubDEWyPKufntwv2DgRRMTSavF2vHuX8nvPzPN7CHsbZxbiPBtYgcc1SqHWZSzzGeNw6rUYezcfZQ49tH2uVnehMFoiVzH2VG5zFqGGXoe7GtR/<0;1>/*,
[bf18b8b5/48h/1h/2h/2h]tpubDEMYys3rFh9h7j29f2KQqFTZgF65xjhSU61iABMqvxt51vGJZ7KPYizuYfiF6CoyhTWY7jgcreuJNY8ywbkxiwRu6vpsAamvViv2QDFCctg/<0;1>/*,[bf18b8b5/48h/1h/3h/2h]tpubDF2wmxwnVur42WisBBjVc5c9VcySuhx7MsmrUt9WGjT5YxTjPLS3eijgDXM8Pupa7PnESFtoKecnMAQaaJshsoaZc1ZXQMrSaPtqPejTjp1/<0;1>/*,))#checksum
`

## if sorting on "Extended public key" (e.g., `tpubDEM...`)
`
wsh(sortedmulti(2,
[bf18b8b5/48h/1h/2h/2h]tpubDEMYys3rFh9h7j29f2KQqFTZgF65xjhSU61iABMqvxt51vGJZ7KPYizuYfiF6CoyhTWY7jgcreuJNY8ywbkxiwRu6vpsAamvViv2QDFCctg/<0;1>/*,[bf18b8b5/48h/1h/1h/2h]tpubDEWyPKufntwv2DgRRMTSavF2vHuX8nvPzPN7CHsbZxbiPBtYgcc1SqHWZSzzGeNw6rUYezcfZQ49tH2uVnehMFoiVzH2VG5zFqGGXoe7GtR/<0;1>/*,
[bf18b8b5/48h/1h/3h/2h]tpubDF2wmxwnVur42WisBBjVc5c9VcySuhx7MsmrUt9WGjT5YxTjPLS3eijgDXM8Pupa7PnESFtoKecnMAQaaJshsoaZc1ZXQMrSaPtqPejTjp1/<0;1>/*,))#checksum
`

**Comment by craigraw** [comment]
The usage of `sortedmulti` refers to the sorting of keys in individual scripts as per BIP67: https://github.com/bitcoin/bips/blob/master/bip-0067.mediawiki. The order of xpubs is not relevant here (although Sparrow does order them for consistency).
