### ISSUE TITLE
unrecoverable wallet

### ISSUE THREAD

**Issue by kwikslvr** [sparrowwallet/sparrow#1326]
Approx 1-1/2 years ago I created a new single sig hot wallet from scratch in Sparrow using an auto-generated 12 word seed plus a passphrase. I recorded the seed words and passphrase in 2 locations and proceeded to use the wallet regularly until Dec 2023 when my computer crashed, and I don't have a backup of the Sparrow wallet .mv.db file. Trying to recover the wallet using the 12 word seed plus passphrase fails - I get an error message in Sparrow saying "No existing wallet found".  Also, when I click "Yes" to attempt to import the wallet anyway, the program just kind of hangs and nothing happens.

What could possibly have gone wrong?  Before anyone suggests I didn't write down either the seed or passphrase correctly, that seems impossible since I am forced during the wallet creation process in Sparrow to re-enter the seed, which I obviously did successfully or I couldn't have created the wallet in the first place. (And no, it's not like I temporarily memorized the seed and entered it in to finish the wallet creation process and then wrote down the seed at a later date and messed up).  As for the passphrase, again, I was forced by Sparrow to re-enter the passphrase to open the wallet every time I wanted to use it, which I did many times, so I know I recorded it correctly and am re-entering it correctly now.

Is there some kind of setting or option during the original wallet creation that I may have mistakenly selected which is now preventing the wallet recovery, or at least preventing Sparrow from finding it now?

![Sparrow_import_fail](https://github.com/sparrowwallet/sparrow/assets/106134192/7f6e18fc-4c02-4035-95e7-e167934db2ac)

**Comment by craigraw** [comment]
> What could possibly have gone wrong?

Hard to say exactly, but what I can say is that Sparrow has not changed in any way with the derivation of addresses from seed words and a passphrase. 

There are 4 factors to consider:
- The seed words
- The passphrase
- The script type
- The derivation path

If any of them differ from the original wallet, you will get different addresses.

I suggest trying to create a wallet using the normal process (File > New Wallet) and trying different combinations from there.

> the program just kind of hangs and nothing happens

Please look in the Sparrow log file (Help menu) and report anything that seems related (or is printed when you do this).

**Comment by m3knight** [comment]
I ran into something similar, and what worked for me was Instead of file>import wallet , try file>new wallet.  Go through the steps, and in the Keystore section choose "New or Imorted Software Wallet", input your 12 word seed, then click "Create Keystore".

Hope that helps.  If a dev see's this and has a few minutes to explain the difference between these 2 methods I'd love to know.

**Comment by craigraw** [comment]
> If a dev see's this and has a few minutes to explain the difference between these 2 methods I'd love to know.

There are no differences (given no existing wallet is found by using Import Wallet, and the same script type is chosen). I've just tested this to verify it - Sparrow creates both wallets with the same addresses.

**Comment by kwikslvr** [comment]
> I ran into something similar, and what worked for me was Instead of file>import wallet , try file>new wallet. Go through the steps, and in the Keystore section choose "New or Imorted Software Wallet", input your 12 word seed, then click "Create Keystore".
> 
> Hope that helps. If a dev see's this and has a few minutes to explain the difference between these 2 methods I'd love to know.

@m3knight 
That worked!  A huge thanks for that tip!!

> > If a dev see's this and has a few minutes to explain the difference between these 2 methods I'd love to know.
> 
> There are no differences (given no existing wallet is found by using Import Wallet, and the same script type is chosen). I've just tested this to verify it - Sparrow creates both wallets with the same addresses.

@craigraw 

I went back and tried one more time to recover using the original Import method, and once again it did *not* find the wallet.  But this time (and I have egg on my face), I took a closer look at what would happen when I clicked Yes on the pop up box asking if I wanted to Import the wallet anyway?  The program didn't actually hang - instead (as I'm sure you know) it was waiting for me to select the Script Type and click a second button.

![Screenshot from 2024-03-29 22-48-15](https://github.com/sparrowwallet/sparrow/assets/106134192/84e5cd0d-f52b-4d11-b635-f12fac343afc)

Once I did that, the wallet and funds were recovered.  Still don't understand why it couldn't find it in the first place, but I'll close this ticket.
