### ISSUE TITLE
wallet birthdate earlier than bitcoin core prune date 

### ISSUE THREAD

**Issue by PEPEyo33** [sparrowwallet/sparrow#1327]
I have connected bitcoin core to sparrow but it gives me an error message :

wallet birthdate earlier than bitcoin core prune date 

I cannot see any of the history of the wallet 

how can I fix this ? 

Thanks

**Comment by PEPEyo33** [comment]
using sparrow wallet with bitcoin core

**Comment by craigraw** [comment]
The only way to fix this is to resync the blockchain from scratch, unfortunately. There is no way currently for Bitcoin Core to retrieve blocks and transactions it has pruned.

**Comment by PEPEyo33** [comment]
Thanks

From: craigraw ***@***.***>
Date: Monday, March 18, 2024 at 2:18 AM
To: sparrowwallet/sparrow ***@***.***>
Cc: PEPEyo33 ***@***.***>, Author ***@***.***>
Subject: Re: [sparrowwallet/sparrow] wallet birthdate earlier than bitcoin core prune date (Issue #1327)

The only way to fix this is to resync the blockchain from scratch, unfortunately. There is no way currently for Bitcoin Core to retrieve blocks and transactions it has pruned.

**Comment by PEPEyo33** [comment]
I there a way for me to stop the pruning of any date ?  I am re installing now.

Thanks again

From: craigraw ***@***.***>
Date: Monday, March 18, 2024 at 2:18 AM
To: sparrowwallet/sparrow ***@***.***>
Cc: PEPEyo33 ***@***.***>, Author ***@***.***>
Subject: Re: [sparrowwallet/sparrow] wallet birthdate earlier than bitcoin core prune date (Issue #1327)

The only way to fix this is to resync the blockchain from scratch, unfortunately. There is no way currently for Bitcoin Core to retrieve blocks and transactions it has pruned.

**Comment by craigraw** [comment]
Yes, you can remove the `prune` setting from bitcoin's config.

**Comment by PEPEyo33** [comment]
Thank you , it would be great if you can make a quick video showing how to ?

Regards

Eddie

From: craigraw ***@***.***>
Date: Monday, March 25, 2024 at 4:25 AM
To: sparrowwallet/sparrow ***@***.***>
Cc: PEPEyo33 ***@***.***>, Author ***@***.***>
Subject: Re: [sparrowwallet/sparrow] wallet birthdate earlier than bitcoin core prune date (Issue #1327)

Yes, you can remove the prune setting from bitcoin's config.
