### ISSUE TITLE
[Windows] Are we Regtest friendly?

### ISSUE THREAD

**Issue by sfhacker** [sparrowwallet/sparrow#1330]
Hi.

First of all, thanks a lot for this project.
We are new to using this wallet so .... bear with us.

![image](https://github.com/sparrowwallet/sparrow/assets/25817529/b6846726-bb0e-47bf-a225-18006bd3ea83)

![image](https://github.com/sparrowwallet/sparrow/assets/25817529/d02bfbe0-48fc-4c11-98ee-c5f86b211c9a)

The issue is that it never connects.

Using Postman and/or command line, no issues at all.

![image](https://github.com/sparrowwallet/sparrow/assets/25817529/1b6c881f-1124-435b-bd7f-5adb290224fa)

Thanks in advance.

**Comment by craigraw** [comment]
The answer to your question is yes - Sparrow works in regtest, so long as it is started using `-n regtest`. See https://sparrowwallet.com/docs/faq.html#how-can-i-run-testnet

Closing this off, let me know if you have any further issues connecting.
