### ISSUE TITLE
Windows Defender Alert

### ISSUE THREAD

**Issue by gfontaniere** [sparrowwallet/sparrow#1331]
Hello,
When i install Sparrow, Windows Defender shows an alert about presence of a virus : Trojan:Win32/Wacatac.B!ml
![Capture d'écran 2024-03-19 073654](https://github.com/sparrowwallet/sparrow/assets/12762548/359f3afc-00b1-4dfd-8b16-ad6a4d7d0ff2)
Have a nive day.

**Comment by anon-dev-gh** [comment]
+1

**Comment by gfontaniere** [comment]
Same issue with standalone client or installable client.

**Comment by amavis442** [comment]
+1

**Comment by amavis442** [comment]
Looks like duplicate of #1310

**Comment by gfontaniere** [comment]
So this is a false positive. Thank you.

**Comment by craigraw** [comment]
It is a false positive yes. Marking as a duplicate of #1310.
