### ISSUE TITLE
[MULTISIG][REGTEST] Extended keys

### ISSUE THREAD

**Issue by sfhacker** [sparrowwallet/sparrow#1332]
Hi there.

I am new to the crypto world (and to this wallet), so ..... be patient!

When creating a BTC REGTEST multi sig wallet, P2WSH script type, I kinda expected the extended key to be something like [1]:

`Vpub5mkstnP5g6Q3kXFiqfucnKLV8gaGfFUCvMfYUAxW5pJNhCfcaRafPth32Tcc757uKrUtCH12UprvQiuxPMiiHcNR8H3jwemo2HBkQkyrktE`
	
However, I got this:

![image](https://github.com/sparrowwallet/sparrow/assets/25817529/8d23c2da-655c-45a9-ba15-c037ccbde080)

Most probably, I clicked on the wrong button.

![image](https://github.com/sparrowwallet/sparrow/assets/25817529/fcd5f791-6354-4c54-ad64-c015d78140f6)

[1] https://electrum.readthedocs.io/en/latest/xpub_version_bytes.html

**Comment by craigraw** [comment]
The "xpub version bytes" refer to an outdated specification called SLIP-0132. While still widely used in older wallets, it has been largely replaced with a new system, output descriptors, which is more future proof. There is for example no SLIP-0132 equivalent for Taproot. 

You can however still get the SLIP-0132 xpub by clicking on the double arrow button to the right of the xpub field in Sparrow.
