### ISSUE TITLE
[UI] Change unfocused tab color

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1334]
I've added 3 tab bars below. On the top is the Tor Browser, in the middle Bisq and on the bottom Sparrow in dark mode.

The first two use a tab color for unfocused tabs that blends with the background of the tab bar. Sparrow uses a really dark grey which looks so heavy that I have to wonder which one is focused every time I come back to it: the "normal" UI grey or the heavy dark one which catches the eye?! The stroke width of the light blue border is too subtile for a quick glance I would say.  

As this is purely subjective it would be interesting to hear from others whether they also have this impression.

![image](https://github.com/sparrowwallet/sparrow/assets/72392544/9a9949f7-9904-41ef-b27a-0652ab001a22)

For comparison I've added the UI with a unfocused tab color that also blends in with the background, which makes it clearer where the focus lies imho:

![image](https://github.com/sparrowwallet/sparrow/assets/72392544/e4f3e0a0-5888-4107-9147-fdea2135df8c)

**Comment by craigraw** [comment]
I agree - have been meaning to look at this. The background color of the unselected tabs is now lighter than the selected tabs. 210d52c0.

<img width="290" alt="Screenshot 2024-03-25 at 13 02 01" src="https://github.com/sparrowwallet/sparrow/assets/862166/4a963d3d-d134-48a9-adba-d1842c5db105">
