### ISSUE TITLE
Clearer splash screen

### ISSUE THREAD

**Issue by maxtannahill** [sparrowwallet/sparrow#1335]
![image](https://github.com/sparrowwallet/sparrow/assets/13302849/f701b4e2-7793-4c4b-a030-8232f69f6601)

Some users seem to find the initial splash screen a bit confusing. I suspect this is more common with non native English speakers. Instead of text inside the box instructing users how to handle wallet files they are likely less familiar with, possibly some large buttons represented as icons with a text explanation could be displayed instead?

Maybe icons for a the following actions:

new wallet, open wallet and import wallet could be set with a box underneath for dragging mv.db files into?

**Comment by craigraw** [comment]
Good idea. I've found a way to do this, and opted for hyperlinks rather than buttons as I want to keep the UI lightweight here. 6ea6f4b5.

<img width="587" alt="Screenshot 2024-03-25 at 14 19 38" src="https://github.com/sparrowwallet/sparrow/assets/862166/8d88bc1c-577c-490f-bf77-676a31024747">
