### ISSUE TITLE
[UI] Blue stroke of focused tab disappers 

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1336]
Writing about issue #1334 I noticed that the blurred blue stroke of the focused tab disappears after interacting with the lower portion of the screen. As it's a valid highlighting of the wallet which is currently active I see no reason why it should disappear.

Steps to reproduce:

1. Open 2 wallets (i.e. 2 different tabs)
2. Select the non-active tab
3. See how the blue stroke switches to the clicked tab
4. Click on any part of the lower portion of the UI, e.g. `Send`
5. Notice how the blue stroke is gone

**Comment by craigraw** [comment]
This relates to the UI framework, and whether the tab header is actually focused or not. It will be difficult to change, and I'm not sure it actually makes sense, since when interacting with other controls the focus has moved.

Marking this as won't fix.
