### ISSUE TITLE
Can't view my balance in Sparrow wallet.

### ISSUE THREAD

**Issue by aveeno099** [sparrowwallet/sparrow#1339]
Just recovered my seedphrase from my old Trezor into a new Coldcard with Sparrow wallet. My first time using Coldcard and Sparrow.

After importing my Coldcard JSON file into Sparrow the balance shown in Sparrow under transactions says zero. Wallet summary also says zero, but it should not be zero. Does Sparrow wallet allow you to see all your funds or does it only show funds that were transacted using Sparrow?  

I have verified funds are present with Trezor suite and Bluewallet but for some reason does not show any funds in Sparrow.

I have verified seedphrase entered is correct under Coldcard view seedphrase feature.

**Comment by PrinceOfEgypt** [comment]
> I have verified funds are present with Trezor suite and Bluewallet but for some reason does not show any funds in Sparrow.

Sounds like you don't have the same derivation path in sparrow as you do in Trezor / BlueWallet. Did you choose the correct account type (legacy/segwit/native segwit) when you created the wallet in sparrow? Do the addresses shown in sparrow match the addresses in Trezor Suite?

**Comment by aveeno099** [comment]
it says native segwit under script type in sparrow wallet

**Comment by PrinceOfEgypt** [comment]
> it says native segwit under script type in sparrow wallet
> 

What does it say in the other wallets? Again, an easy way to check would be to look at the list of addresses that are showing up.. do they start with a "1", "3", "bc1q", "bc1p"?

Native Segwit would be "bc1q", but if the addresses in Trezor Suite don't match then your wallet was using a different derivation path.

**Comment by aveeno099** [comment]
all of my receive addresses in trezor start with bc1q. never used any
address that did not start with those letters.

in Coldcard when is says press 0 for non-zero account I have no clue what
that means nor did the coldcard documentation ever explain what you are
supposed to do when you get that question. it is crazy how non-user
friendly this thing is. I am almost regretting that I bought this stupid
thing.

**Comment by aveeno099** [comment]
when i click on "receive" in sparrow wallet there is a long list of
addresses that all start with bc1q.

**Comment by PrinceOfEgypt** [comment]
Are the two list of addresses the same? If not, did you press "0" and enter an account number on the coldcard?

**Comment by aveeno099** [comment]
"Are the two list of addresses the same?"

What two lists of addresses are you referring to?

I tried it creating the wallet both ways. First time I didn't press zero or
anything just hit OK to generate the generic JSON file.

The second time I pressed zero then entered 1 for account number and then
generated JSON using that.

Either way it gives me the same result in Sparrow wallet. Balance appears
as zero either way.

Another point of confusion is when the official Sparrow website tells you
to select Generic JSON instead of Sparrow JSON, and yes I tried it both
ways.

**Comment by aveeno099** [comment]
are you referring to the "receive addresses" and" change addresses" lists
in sparrow?

btw I have no idea what those list of addresses are for. I can only assume
the "receive addresses" are fresh addresses for receiving bitcoin but have
no idea the meaning of "change addresses."

**Comment by aveeno099** [comment]
if those are the two lists you referring to the addresses between them do
not match at all they are completely different.

the only thing they have in common is that they all start with bc1q in both
lists.

**Comment by PrinceOfEgypt** [comment]
> "Are the two list of addresses the same?"
> 
> 
> 
> What two lists of addresses are you referring to?
> 
The list in sparrow and the list in Trezor Suite.

**Comment by PrinceOfEgypt** [comment]
You clearly don't have the same wallet on the Coldcard as you did on the Trezor. The Coldcard is a more advanced device with more options, and you shouldn't select options without knowing what they mean (the account number for example)

You may want to watch some of the BTC Sessions videos, he covers Coldcard basics and even has a video specifically about switching from a different hardware wallet to a Coldcard. 

There is no issue here with Sparrow. Do yourself a favor - watch these two videos start to finish without messing with your Coldcard, then reset the device and start clean following along with the second video. 

https://youtu.be/FAYmE5-40PQ?si=SKgYn3R93IiFychI

https://youtu.be/rgiwIo3IeSE?si=wCfr8EMICly-PvwF

**Comment by aveeno099** [comment]
Just downloaded Wasabi desktop and Nunchuck mobile.
Had no problem importing from Coldcard with these wallets and my balances
on them can be seen, even balances from my hidden wallets.
The addresses match my Trezor. Which proves that I set up my Coldcard
correctly the first time.

Much easier to work with than Sparrow, which is still not showing anything.

**Comment by PrinceOfEgypt** [comment]
Did you check that Sparrow is actually connected to a server? The toggle button on the far bottom right is on and either yellow, green, or blue?

https://sparrowwallet.com/docs/quick-start.html

![image](https://github.com/sparrowwallet/sparrow/assets/2649235/34bdf756-81c0-42d5-9996-18a021917a46)

**Comment by aveeno099** [comment]
Thanks for your help but I give up on Sparrow for now. Don't have any more
time to mess around with it. Maybe I will try again in the future.

**Comment by PrinceOfEgypt** [comment]
Ok please close this issue then

**Comment by PrinceOfEgypt** [comment]
@craigraw can you close this? Looks like he's not coming back

**Comment by Jikoun** [comment]
Could you help me with similar problem? 

I imported coldcard to sparrow, then I imported xpub to bluewallet and there I generated receive address and send it there, but then I realized I should have imported zpub. And now I cannot sign the transaction so I can send it to zpub. I tried to import legacy format from coldcard, but did not work...

**Comment by PrinceOfEgypt** [comment]
Right click on the xPub in Sparrow and it will give you the option to copy the zPub.

**Comment by Jikoun** [comment]
I am not sure if I wrote it correctly. I imported xpub to bluewallet and generated receiving address there. I sent there some sats and it won't appear in Sparrow, because in sparrow I have bc1 address. I sent sats to 1 address.

**Comment by PrinceOfEgypt** [comment]
You created a legacy wallet in BlueWallet, not a native Segwit one. You need to send the funds back to sparrow and export the wallet correctly to BlueWallet using either the export wallet option or by copying the zPub

**Comment by Jikoun** [comment]
How can I send it from watch-only wallet (xpub from my coldcard) when I cannot sign it with my coldcard?

**Comment by PrinceOfEgypt** [comment]
You'll have to create the transaction in BlueWallet, export it to a pbst and sign it with the coldcard. You can then import the signed transaction back into BlueWallet and broadcast it there.

**Comment by Jikoun** [comment]
And exactly that doesn't work. Coldcard show me error because of derivation path and so on.

**Comment by PrinceOfEgypt** [comment]
Sorry, not sure where you went wrong but as far as I'm aware the coldcard should be able to sign a transaction for any valid derivation path of its seed. Regardless this is not a sparrow issue - you may want to look for help on the BlueWallet GitHub page.

**Comment by Jikoun** [comment]
Okay, I will try. Thanks for your effort anyway.

**Comment by craigraw** [comment]
Closing this issue off. Thanks for your help @PrinceOfEgypt.
