### ISSUE TITLE
can sparrow be used as an offline signing device?

### ISSUE THREAD

**Issue by ghscuuo** [sparrowwallet/sparrow#1340]
Sorry if that's a dumb question.  

I don't see why an offline sparrow would be any different from a traditional hardware wallet (actually offline sparrow would be much better in a few ways, as I see it).  I see some evidence and comments that it can, and I've tried hard to make it work, but maybe it's not possible, or I'm doing something wrong. 

I'd like my offline, never, ever, online, signing device to be sparrow on, say, tails, on an old laptop.  And then export my xpubs via qr or file from the offline sparrow to an online sparrow on another old laptop, build my transactions in the online sparrow, and then pass those transaction via qr or file to the offline sparrow for signing, and then similarly pass the signed transaction back to the online sparrow for broadcasting. 

What repeatedly happens, with no ui indication of anything wrong, and nothing obvious to simpleton me in the logs, is:

1. in online sparrow 1.8.4-1, watch-only, single sig, Native Segwit (P2WPKH), build tx, Finalize Transaction for Signing, Save Transaction, sd card, .psbt file, eject sd card.
2. in offline sparrow 1.8.4-1, File, Open Transaction, .psbt file from sd card.  Transaction Overview and Details look correct (though seeing the Locktime Block was surprising to this beginner), Signing Wallet looks correct. Click blue Finalize Transaction for Signing, click blue Sign, see Signatures blue bar progress to apparent completion on the right with BIP39 label.  Blue Sign button still blue.  No indication of a problem. Save Transaction, to sd card, .psbt.psbt file, eject sd card.
3. in online sparrow, Load Transaction, .psbt.psbt file from sd card. Signatures blue bar progresses to far right, with BIP39 label.  I think a Broadcast Transaction button should appear. 

What am I missing?  How can I help troubleshoot and test and document? 

Thanks in advance, and thanks for an awesome product!

**Comment by ghscuuo** [comment]
On the offline sparrow, the log ends with 

a series of Transaction output value: ..
Found input witness utxo amount...
Found input sighash_type All...
Found input bip32_derivation with master fingerprint...
Found output bip32_derivation with master fingerprint...
Calculated fee at ...

**Comment by ghscuuo** [comment]
My testing so far has had two different complexities:  

1. One was, my motivation was to RBF a low fee transaction that I broadcasted via other more complicated means (and so I was trying to use this offline-online-sparrow config to simplify that).
2. Another complexity was my "simpler" test was trying to send to my taproot wallet (because I'm cheap, as you know, and I hear taproot has lower fees).

For the sake of science, I just now made an even simpler test, just sending some sats back to a new address in my same Native Segwit (P2WPKH) wallet, and this time, on the offline sparrow, when I clicked Sign, it changed to Save Final Transaction...  I saved that to a ".txn" file (note not .psbt.psbt file this time), and then loading that .txn file into online sparrow, the Signatures bar went full, with BIP39 label, and a big beautiful blue Broadcast Transaction button appeared.

My cheapness has cost me many hours...let's work together to make those hours not a complete waste...

**Comment by craigraw** [comment]
What you are doing is a well tried and tested approach :)

There is no problem with loading a signed .psbt into Sparrow to broadcast. There's also no problem with this transaction sending to a Taproot address, or being an RBF transaction. What I think is likely here is just that the "online" Sparrow was actually offline, as in the toggle in the lower right was off. 

Fwiw I just tested your original scenario and everything worked fine. Happy to reopen this if you find some issue.

**Comment by ghscuuo** [comment]
I bet tor is the problem.

To be clear, online sparrow had great connectivity to the default public node, quickly and completely finding all of my utxos from all of my different wallets and accounts, had great fast responsive current fee estimations, and like a lazy lifeguard watched my too-low-fee transaction slowly sinking into the deep end of the mempool. :) 

Did you test on mainnet, with tor?

Do you think the problem (on tor) was at the transaction-building step, during .psbt creation?  I think it must be, because of the missing "Save Final Transaction" on the offline Sparrow. The .psbt must be missing something subtle.  I think that may be the first bug. 

Then the signing sparrow thinks it has enough info to sign the transaction, and so it seems to sign it and move the progress bar to the far right (looks complete and successful), not knowing that something is wrong.  Part of the code thinks it signed the tx, but the next part of the code either disagrees or is not aware, silently.  That could be the second bug (or two).

How can I help?

**Comment by craigraw** [comment]
> Do you think the problem (on tor) was at the transaction-building step, during .psbt creation? I think it must be, because of the missing "Save Final Transaction" on the offline Sparrow. 

I don't think so, but could you check the log file for the offline Sparrow? Help menu. It may show something that will indicate the cause.

**Comment by ghscuuo** [comment]
[sparrow_redacted.log.gpg.zip](https://github.com/sparrowwallet/sparrow/files/14812657/sparrow_redacted.log.gpg.zip)

I don't see anything obvious.  Sorry if I over-redacted.

**Comment by craigraw** [comment]
Unfortunately nothing useful I could see in the log file either. If you can find a set of steps to reproduce (perhaps on testnet) that would be useful.

**Comment by ghscuuo** [comment]
Here's a consolidation.psbt file and testnet trace log with the same behavior.  Remove trailing ".zip" from .gpg filename. 
[testnet-fail.zip.gpg.zip](https://github.com/sparrowwallet/sparrow/files/14898686/testnet-fail.zip.gpg.zip)

Let me know how _I_ can be useful. :)

**Comment by craigraw** [comment]
Thanks. Unfortunately I can't see any problems with the PSBT, and the log file contains no errors. Of course without the seed I can't sign the PSBT to actually see what you're seeing. At what stage in your described process did you save this PSBT - was it on the online Sparrow, or after signing with the offline one?

With my own seed, I tested the scenario again on my side without any issues.

**Comment by ghscuuo** [comment]
Sorry for this distraction. I hope we discover something helpful.
[Testnet_Test_20240409_01-05-37AMUTC.zip.gpg.zip](https://github.com/sparrowwallet/sparrow/files/14912665/Testnet_Test_20240409_01-05-37AMUTC.zip.gpg.zip)

**Comment by craigraw** [comment]
Thanks for the data. Unfortunately it has brought us no closer to a solution on this though. Here's what I did:

1. Created an offline only version of the wallet with the seed. This wallet has no history.
2. Successfully signed testcons.psbt with this wallet. The Save Final Transaction button appears.
3. Created a watch only version of the wallet with the output descriptor. This wallet was connected and has history.
4. Created testcons2.psbt with this wallet following the steps you described.
5. Successfully signed testcons2.psbt with the offline wallet.

If you do the same on your online computer (using the toggle in the lower right to connect/disconnect) are you able to reproduce the problem? I can't think of a reason the clock would cause any issues, but who knows at this point.

**Comment by ghscuuo** [comment]
Inspired by something about your wording, on my offline sparrow, I closed my testnet wallet, and created a new wallet with the same seed, and it signed the .psbt perfectly, creating a .txn file, which broadcast and confirmed perfectly from my online sparrow. 

Do we have a silently corrupt offline wallet?  Both wallets attached. 
[testnet_wallets.zip.gpg.zip](https://github.com/sparrowwallet/sparrow/files/14940712/testnet_wallets.zip.gpg.zip)

Let me know how I can help.

**Comment by craigraw** [comment]
Thanks - finally found it. It turns out to be a simple gap limit problem (napkin_0 required a gap limit of 35, not 34 to sign all the inputs). 

However, Sparrow should automatically increase the gap limit, but it didn't in this case because it could partially sign the transaction (some of the inputs). This edge case has been fixed in 93893111.

Thanks for your help in finding this! Increasing the gap limit on your original offline wallet should solve the problem.

**Comment by ghscuuo** [comment]
Great to hear! Thanks for your patience and hard work!

Any logging or UI changes practical to help prevent or troubleshoot the next issue?

**Comment by craigraw** [comment]
Nothing new - log file is best.
