### ISSUE TITLE
Can't Resize Sparrow App

### ISSUE THREAD

**Issue by Bitcoinian** [sparrowwallet/sparrow#1341]
When I open the Sparrow App it is larger than my screen  (both on my laptop and my 75" TV/Monitor. I can't even grab an edge to pull it in smaller,
Esc button doesn't work I have to hit ctrl/alt/delete   and resighn in just to access my browswer and regular screen.
It worked last week.
Suggestions?
![Sparrow wallet too large for screen  20240323_144238](https://github.com/sparrowwallet/sparrow/assets/135888257/6e3463cf-cdbb-4bf6-a106-bb0859c58adf)

**Comment by PrinceOfEgypt** [comment]
Is this windows? Hit WindowKey + Up Arrow with Sparrow focused (the foreground app)

**Comment by Bitcoinian** [comment]
Thank You Prince!
That solved the problem!
Cheers,
Ian

Sent with [Proton Mail](https://pr.tn/ref/Y9WX0DB76RC0) secure email.

**Comment by Bitcoinian** [comment]
Yes It is Windows  ,Prince and your suggestion solved my problem.  Thanks again! Cheers!
