### ISSUE TITLE
Sparrow on Raspberry Pi OS

### ISSUE THREAD

**Issue by MarkJelic** [sparrowwallet/sparrow#1342]
It actually works pretty well... Except the Menus don't stay "dropped" when you select them (they immediately disappear as soon as you let the mouse go) and you can't "click and drag" the mouse to a menu selection, either. In fact, any menu (including drop down lists) appear like one menu item down rather than directly under the menu. But with drop down lists, at least those stay open and you can select them, they just look odd, not being connected to the selector.

**Comment by MarkJelic** [comment]
OK, good news... I can make the Menus stay dropped if I use the keyboard to drop them... That is, if I hit ALT and then Down Arrow, then I can use the mouse to move around to whatever menu and use the left click as normal to select a menu option. (I can also use the arrow keys to move around the menu options and hit Enter to select.)

**Comment by craigraw** [comment]
Thanks, this is a known issue with a fix in sight. See #170.
