### ISSUE TITLE
Comparing the hash of the sparrow-1.8.4 file with the sparrow-1.8.4-manifest.txt file does not match the results

### ISSUE THREAD

**Issue by Luferarpa** [sparrowwallet/sparrow#1346]
I was checking the hash file of the download I made of the sparrow version 1.8.4 wallet, and it does not match the information contained in the sparrow-1.8.4-manifest.txt file.

**Comment by craigraw** [comment]
The hashes do match if you have the correct file. Have you tried downloading again? How are you performing the hashing?

**Comment by craigraw** [comment]
Closing this off.
