### ISSUE TITLE
Feature Request: show addresses on device 

### ISSUE THREAD

**Issue by tychsen** [sparrowwallet/sparrow#135]
It would be nice to be able to ask Sparrow to show addresses on device in order to verify them.

**Comment by craigraw** [comment]
Check the 'Display Address' button at the bottom of the Receive tab. Note you need to have a USB connected hardware wallet configured.

**Comment by eliasnaur** [comment]
Nice, I hadn't seen that option. Is it possible to get that feature on the "addresses" tab as well? You may have several receive addresses in flight or want a batch of verified addresses.

**Comment by eliasnaur** [comment]
On second thought, using the down arrow icon for selecting an address for receiving and then pressing "display address" is fast enough compared to verification. I think this issue can be closed.

**Comment by tychsen** [comment]
Is it possible to see it on a Cold Card or any other air gapped device?

**Comment by craigraw** [comment]
> Is it possible to see it on a Cold Card or any other air gapped device?

Yes, but you'll need to use the 'Address Explorer' feature on that device. 

Can we close this off?

**Comment by tychsen** [comment]
Im closing off in gratefulness...
