### ISSUE TITLE
non-standard derivation path changed when recovering a software wallet with a descriptor already defined

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1352]
1. Create a new wallet
2. generate seed phrase
3. choose a non-standard derivation path (m/844'/0'/0')
4. import the keystore
5. copy the descriptor
6. Create a new wallet to recover the descriptor into
7. Paste the descriptor that uses a non-standard derivation path of m/844'/0'/0'
8. Click `Import` in the keystore
9. Click `Software Wallet`
10. Enter seed phrase
11. m/84'/0'/0' is suggested instead of m/844'/0'/0'
12. import the keystore without realizing the derivation path used is wrong
13. wrong wallet is recovered

**Comment by craigraw** [comment]
Sparrow will now use the current derivation of the keystore (if present) as the default derivation when importing a BIP39 seed or master private key. 8ac642b0.

**Comment by AndySchroder** [comment]
Tested in version 1.8.5, this is working good as expected!
