### ISSUE TITLE
changing descriptor of a recovered software wallet forgets the seed and changes to watching only wallet

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1353]
1. Create a new wallet
2. generate seed phrase
3. choose a non-standard derivation path (m/844'/0'/0')
4. import the keystore
5. copy the descriptor
6. Create a new wallet to recover the descriptor into
7. New or imported software wallet
8. enter seed phrase
9. import the keystore using the default derivation path
10. Paste the correct descriptor that uses a non-standard derivation path of m/844'/0'/0'
11. wallet changes to a watching only wallet and forgets the seed

I would expect sparrow wallet to look at the derivation path and use the xpriv it has and see if it computes the same xpub. If it computes the same xpub, then it should stay a software wallet and not switch to a watching only wallet.

This issue coupled with https://github.com/sparrowwallet/sparrow/issues/1352 make it hard to recover a wallet with a custom derivation path because both approaches don't work the way I would expect.

**Comment by craigraw** [comment]
> This issue coupled with https://github.com/sparrowwallet/sparrow/issues/1352 make it hard to recover a wallet

I would argue that both #1352 and this issue violate the principle of doing what the user has asked, and instead try to be 'clever', which has both pros and cons. Does it really make it 'hard to recover a wallet'? There is no good reason for normal users to be using non-standard derivation paths in the first place.

**Comment by AndySchroder** [comment]
If the derivation path in the descriptor is not used when importing a software wallet, but instead a different derivation path is substituted in place of it, what do we have the descriptor for at all? It seems to me that if a descriptor completely defines a wallet, the user should just need to copy paste (or scan) the descriptor and then type (or scan) the seed (or type (or scan) the seed and then copy paste (or scan) the descriptor) and then get the wallet. The way it is now, the user has to keep overriding the default derivation path to match their custom descriptor. If someone doesn't know anything about derivation paths, they aren't going to know they have to watch out for sparrow wallet ignoring the derivation path in the descriptor.

**Comment by AndySchroder** [comment]
Also, if someone doesn't have a custom derivation path, they likely won't have a descriptor saved at all and they will try to use the defaults for everything and then they won't encounter this issue or https://github.com/sparrowwallet/sparrow/issues/1352.

**Comment by craigraw** [comment]
Implemented in 10a79609. Sparrow will now keep any existing seeds with matching fingerprints when changing a wallet's output descriptor, rederiving the xpub if necessary.

**Comment by AndySchroder** [comment]
Tested in version 1.8.5, this is working good as expected!
