### ISSUE TITLE
Can't connect to a public server over Tor

### ISSUE THREAD

**Issue by BTC1M** [sparrowwallet/sparrow#1356]
Hi, i am trying to connect to a public server though Tor but it doesn't work.
I can connect to any public server, but not with proxy enabled.
I have tried with all the public servers available, on proxy 127.0.0.1 port 9050.
I also tried with "localhost" instead of 127.0.0.1, and on port 9150.

The error message i am getting is : 
`Could not connect:
Connection refused: connect. Check if the proxy server is running.`

And at the bottom near "Server Preferences", it is written : 
`Connection failed: Socket Error (Connection refused: connect)`

I am on Windows, my sparrow version is up to date (1.8.4), and so is my Tor Browser (13.0.13).
I already tried to reboot.

**Comment by craigraw** [comment]
It seems that some part of the network is refusing your connection. Unfortunately there's nothing Sparrow can do about this - if privacy is important, it may be time to consider running your own node. You can also use a VPN instead of Tor.
