### ISSUE TITLE
Feature Request: import and sign raw transactions

### ISSUE THREAD

**Issue by ordinariusprof** [sparrowwallet/sparrow#1357]
Would it be possible for sparrow to sign an unsigned raw transaction hex that's created with bitcoin-core or bitcoinjs ?

Load transaction works great:
After loading, it could check that all inputs are controlled by a specific wallet and offer to sign it.

Thanks for considering,

**Comment by craigraw** [comment]
Trying to understand this use case better. Both Bitcoin Core and bitcoinjs provide functionality to create PSBTs, which is the more appropriate data structure for an unsigned bitcoin transaction. Why would you not use them?

**Comment by ordinariusprof** [comment]
I didn't have a chance to try this yet but I'll do that next time, I assume loading an unsigned psbt that has an input controlled by a loaded wallet in sparrow will allow me to sign it with sparrow.

**Comment by craigraw** [comment]
Yes, so long as the PSBT has been reasonably well constructed.
