### ISSUE TITLE
auto close QR code after receiving or update it to match the current receiving address

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1359]
When on the receive screen you can click to increase the size of the QR code in a new window. After receiving, the receive screen advances to the next address, but the old QR code is still showing.

Please make sparrow either close the larger QR code window or make it show the next address to match the main receive screen.

**Comment by craigraw** [comment]
Sparrow will now close the dialog when the address updates. 33d9f260. Added some UI to make the dialog easier to find at the same time.
