### ISSUE TITLE
Sparrow can't find Trezor T 

### ISSUE THREAD

**Issue by tychsen** [sparrowwallet/sparrow#136]
For some reason Sparrow doesn't connect to Trezor T.

I first thought it was because Trezor hidden wallet feature was enabled (password) - so I turned that off via their own Trezor Suite.

But still I get this error when trying to sign:

"Error scanning, check devices are ready"

When trying to create a new wallet, and selecting Trezor I get:

"There was error connecting to the wallet - Error scanning, check devices are ready"

The Trezor T works fine from both Trexor.io/start and through the Trezor Suite app.

UPDATE: Restarted sparrow wallet. Didn't help. Restarted the whole machine, helped. Now it worked.

I am very unsure if this is a wallet-related issue. But on the other hand, the Trezor worked fine with both Suite and online. hmm...

**Comment by craigraw** [comment]
Thanks for reporting - this is a known issue where the operating system is deleting some files behind the scenes. Will be fixed for the next release.

**Comment by tychsen** [comment]
Will be fixed in next update.
