### ISSUE TITLE
Consider updating CSV transaction export to use UTC default as timezone

### ISSUE THREAD

**Issue by notsureofagoodname** [sparrowwallet/sparrow#1360]
By default Sparrow shows Tx in local timezone as part of CSV export. Most of the tax software expects time to be in UTC. This is throwing off buy/sell trade history with software without editing every transaction and doing a bulk import/export. Takes the file from something software generated to human edited also.

Ask here is to update CSV export of transactions to use UTC - or set a toggle/flag somewhere to allow CSV export to use UTC.

**Comment by craigraw** [comment]
Thanks for the suggestion. I think it probably makes sense to do this as part of a larger feature that allows customisation of the time zone across the app.

**Comment by notsureofagoodname** [comment]
TY for reviewing/comment. Agree a setting to allow a user to select an export-TZ of their choice is ideal. If that's not possible kindly suggest defaulting to UTC.

**Comment by badonyx** [comment]
+1 please include time zone in the timestamp and/or default to UTC. block height would be very useful too.

**Comment by craigraw** [comment]
I can include the timezone, but what format is best? For example, ISO 8601/RFC 822 can be used:
```
2020-11-03 12:41:20 +0200
```

I am also cautious of breaking imports to software that does not understand time zones. Block height can also be added.

**Comment by notsureofagoodname** [comment]
ISO 8601 sounds good to me. Export default imho should be in UTC - it's universal for a reason :).

From Koinly "All the transactions should be imported into Koinly using UTC timezone"
From Cointracker "Time entries are optional. If you choose to include a time, it is assumed to be in UTC"
From CryptoTaxCalculator "Timestamp (UTC)"
From CoinPanda "Timestamp (UTC): All dates should be UTC timezone"

That's the major crypto tax software platforms I can find (and use), they all assume UTC..

**Comment by craigraw** [comment]
Ok, that seems a convincing argument. I've changed the CSV exports to use UTC for both the transactions and UTXOs export, and noted this in the column header. 0fed7c45.

**Comment by notsureofagoodname** [comment]
TY.
