### ISSUE TITLE
mention that `txindex=1` is recommended with bitcoin core

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1361]
When connecting directly to bitcoin core, sparrow wallet documentation does not mention that the `txindex=1` is required. Without this setting sparrow wallet _mostly_ works, but reviewing transactions is very limited. We can't see values (amounts and addresses) of any transaction inputs (they all come up as "Unknown") and we can't browse to see the input transactions (the Outpoint is not a link). Fees are also not computed (they come up as "Unknown Fee") because sparrow wallet does not know the amounts of the inputs.

I'd recommend making the reason for this more clear within sparrow wallet and also update https://sparrowwallet.com/docs/connect-node.html to indicate that `txindex=1` is recommended (but not required) to get full functionality.

**Comment by craigraw** [comment]
> sparrow wallet documentation does not mention that the txindex=1 is required

To be clear (for others who might read this) it is not required.

> also update https://sparrowwallet.com/docs/connect-node.html to indicate that txindex=1 is recommended (but not required)

Done - I wouldn't go so far as to say recommended, but it's certainly something I would enable if pruning was disabled.

> I'd recommend making the reason for this more clear within sparrow wallet

It's actually more difficult that it might appear. Without `txindex`, some transaction lookups will work, and some won't. Some may fail due to network issues. There is AFAIK no reliable way to tell whether txindex is enabled or not. Happy to reopen this if I have missed something here.

**Comment by AndySchroder** [comment]
> It's actually more difficult that it might appear. Without `txindex`, some transaction lookups will work, and some won't. Some may fail due to network issues. There is AFAIK no reliable way to tell whether txindex is enabled or not. Happy to reopen this if I have missed something here.

What kind of network issues are you talking about that cause it to fail? bitcoind doesn't normally go to peers to get any tx data does it? Are you saying some will even fail with txindex enabled?

Just curious, what kind of transaction lookups even work with txindex disabled?

**Comment by craigraw** [comment]
> What kind of network issues are you talking about that cause it to fail?

It's possible - for example if connecting to Bitcoin Core remotely.

> Just curious, what kind of transaction lookups even work with txindex disabled?

Transactions related to the user’s wallet

**Comment by AndySchroder** [comment]
> > Just curious, what kind of transaction lookups even work with txindex disabled?
> 
> Transactions related to the user’s wallet

It seems as though it only knows about outputs received or sent by the wallet. It doesn't know about other outputs in a transaction that are not sent to a wallet, so you can't get a full view on the transactions that the wallet participated in. For example, you can't know the fee paid on the transaction sent to you if the sender had a change address or paid people other than you in the same transaction, or you can't know the fee if you are participating in a collaborative transaction.

Does this match your experience?

**Comment by craigraw** [comment]
Yes, agreed.
