### ISSUE TITLE
Sign Message with QR flow seems broken

### ISSUE THREAD

**Issue by 1ma** [sparrowwallet/sparrow#1363]
Sparrow version: 1.8.4
OS: Xubuntu 22.04
Reproducing steps:

1. Open a cold single signature wallet.
2. Go to the Addresses tab.
3. Right click any address and click Sign/Verify message.
4. Write some text in the Message field, click Sign by QR.
5. In the QR screen, click Scan QR. Instead of launching the webcam Sparrow goes back to the "Sign/Verify Message" screen.

Reproducible in P2PKH, P2WPKH and P2TR wallets, regardless of signing format. Sparrow itself doesn't seem to throw any exception in the logs, looked up to DEBUG level.

**Comment by craigraw** [comment]
Yes, this was recently fixed. See #1317.
