### ISSUE TITLE
Error broadcasting TX

### ISSUE THREAD

**Issue by santochibtc** [sparrowwallet/sparrow#1364]
I can't broadcast a transaction signed by Samourai wallet. I want to send a UTXO from postmix without change.
I am having this exception
```
ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)
```

**Comment by craigraw** [comment]
That error is coming from your node (or whatever Bitcoin Core node you used to broadcast). It's not a Sparrow generated error - essentially the node is saying the public key in the script wasn't correct.
