### ISSUE TITLE
Inadvertently used Taproot script and created/funded a wallet using a Tapsigner

### ISSUE THREAD

**Issue by aspenrecon** [sparrowwallet/sparrow#1366]
Since Tapsigner cannot sign taproot transactions, the funds are stuck. I imported the tapsigner XPRV to a coldcard and tried creating a new hot wallet with the same script but received the following error. Any suggestions on how to proceed?
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/14894108/sparrow.log)

**Comment by craigraw** [comment]
What export function are you using on the Coldcard? The error you are getting indicates you are exporting for a multisig wallet. Try the file created by using the Advanced > MicroSD > Export Wallet > Generic JSON > 0 function.

**Comment by aspenrecon** [comment]
That was it. Much appreciated craigraw

**Comment by craigraw** [comment]
Improved the error message in 2441b4d7. Thanks for reporting.
