### ISSUE TITLE
Error toggle passphrase- KeepKey

### ISSUE THREAD

**Issue by Smiggel** [sparrowwallet/sparrow#1367]
I am trying to sign a transaction with my my KeepKey, that I have attached to my MacBook Pro. I run Sparrow 1.8.4.

I have attached my KeepKey to my computer. And when I try to toggle the password screen in Sparrow I get the error:

"Error toggle passphrase"
__init()__ missing 1 required positional argument:
'internal_name'

The passkey keyboard never shows up and so I can not sign any transaction.

**Comment by craigraw** [comment]
Closing this off as an HWI issue.
