### ISSUE TITLE
Inability to RBF unconfirmed TX

### ISSUE THREAD

**Issue by marnusminie** [sparrowwallet/sparrow#137]
As requested by Craig on Telegram:

Input #0 value: 0.04344318
Output #0 value: 0.0036472
Output #1 value: 0.039793
Original fee: 0.00000298

Type: Segwit

**Comment by craigraw** [comment]
Can't seem to recreate the issue. I'm not sure which of the two outputs was the change output (I assume the larger one) but certainly there is sufficient value there to cover increasing the fee, and no need to include additional UTXOs. I have constructed the same transaction on testnet and am able to create an RBF replacement transaction with a > 20 sats/vB fee. 

A bit of a mystery as to why the Create Transaction button wasn't working.

**Comment by 6102bitcoin** [comment]
3 months since this was raised -  Were you able to replicate @marnusminie ?

**Comment by marnusminie** [comment]
Hi guys

Have not experienced the same issue since this original problem appeared,
so no ongoing hassles I guess :)
[image: Untitled design (1).gif]
*Marnus Minie*
BitVice
| e: ***@***.***
| w: www.bitvice.io

**Comment by craigraw** [comment]
Ok thanks - I'm going to close this off, please comment if it happens again.
