### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MaxBuyBit** [sparrowwallet/sparrow#1371]
The search all wallets feature using a TXID is a massive help. I would love to be able to label within the search window if possible? 

Currently I copy TXID and paste it into search all wallets, I then click on the first transaction and label before re searching and clicking on the second to label. If we could label in the search window it would be half the work.

I know this is a minor inconvenience but it adds friction when labelling allot of old transactions and wallets. 

Thanks. 

MBBB.

**Comment by craigraw** [comment]
Added in 41146310. You can now edit labels directly in the Search Wallet dialog.
