### ISSUE TITLE
Issue with verify download tool - inconsistent subkey date

### ISSUE THREAD

**Issue by aChrisYouKnow** [sparrowwallet/sparrow#1375]
I know this is a bit out of scope of the main use of Sparrow wallet, so, mark this as a very low priority, but I still figured it was worth mentioning. 

I have really been enjoying the convenience of using Sparrow to verify software. Fantastic tool.

I recently went to varsity the latest Raspiblitz build, and got the following error: 
"Subkey is not bound: 1 rejected signatures: SUBKEY_Binding Fri Oct 20 18:33:25 EDT 2023: Signature was created at Fri Oct 29 18:33:25 EDT 2023 and therefore not valid yet at Thu Sept 21 21:32:25 EDT 2023"

However, if I use GPG to verify the signature, aside from verifying fine, I see the following dates which pre-date the signature date:
pub   rsa4096 2019-09-03 [C]
      92A746AE33A3C186D014BF5C1C73060C7C176461
uid           [ unknown] Christian Rotzoll <christian@rotzoll.de>
sub   rsa4096 2019-09-03 [S] [expires: 2024-10-19]
      C0EE614531A416B4CDB7A2D7AA9DD1B5CC5647DA
sub   rsa4096 2019-09-03 [E] [expires: 2024-10-19]
      A7D4DA6295EC365E4CCF05FCD40D94E6C7C9B4D9
sub   rsa4096 2019-09-03 [A] [expires: 2024-10-19]
      AA80506CFCAB340584C49F0E1C29DC2F8D764F9A.

I'm wondering where Sparrow is getting the Fri Oct 20 18:33:25 EDT 2023 date from, which is causing the verification to fail. 

Source of key: 
https://keybase.io/rootzoll/pgp_keys.asc

Full verification instructions from Raspiblitz:
https://github.com/raspiblitz/raspiblitz/blob/v1.10/FAQ.md#how-to-verify-the-sd-card-image-after-download

Where the Raspiblitz image and signature file come from:
https://github.com/raspiblitz/raspiblitz?tab=readme-ov-file#downloading-the-software

Thanks!

**Comment by craigraw** [comment]
> I'm wondering where Sparrow is getting the Fri Oct 20 18:33:25 EDT 2023 date from, which is causing the verification to fail.

This is the creation date of the signature file. 

What Sparrow is saying here is that the signing subkey (the key that created the signature file) has a binding signature with a creation date after the signature file's creation date.

**Comment by aChrisYouKnow** [comment]
Is the binding signature creation date different than these dates I see via gpg? 

pub   rsa4096 2019-09-03 [C]
      92A746AE33A3C186D014BF5C1C73060C7C176461
uid           [ unknown] Christian Rotzoll <christian@rotzoll.de>
sub   rsa4096 2019-09-03 [S] [expires: 2024-10-19]
      C0EE614531A416B4CDB7A2D7AA9DD1B5CC5647DA
sub   rsa4096 2019-09-03 [E] [expires: 2024-10-19]
      A7D4DA6295EC365E4CCF05FCD40D94E6C7C9B4D9
sub   rsa4096 2019-09-03 [A] [expires: 2024-10-19]
      AA80506CFCAB340584C49F0E1C29DC2F8D764F9A

I'm just trying to duplicate outside of Sparrow where the Fri Oct 20 18:33:25 EDT 2023 is coming from. Could very well still be a misunderstanding on my end, but it looks like all dates associated with the signing key (and subkeys) pre-date the signature file and release file (2023-09-21). 

Thanks again.

**Comment by craigraw** [comment]
You are only see expiry dates with that export - you need creation dates.

Try `gpg --list-packets pgp_keys.asc`

**Comment by aChrisYouKnow** [comment]
Thanks a lot, great learning opportunity. I had never gone deeper than checking gpg for "_Good signature from..._" and making sure I got the signature file from a different source than where I was getting the release. The warning Sparrow throws makes a lot of sense with the binding signature being created later than the signature file. I had never looked that deep before to check the dates of the binding signatures. Really appreciate your time, Sparrow wallet, and this great bonus tool for verifying other software releases. Have a good one!
