### ISSUE TITLE
adding accounts with watching only wallets keeps adding accounts named `Account #1`

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1377]
1. Create a new wallet
2. add a descriptor to watch
3. add a new account. This one is called `Account #1`
4. add a descriptor to that new account
5. add a new account. This one is called `Account #1`
6. add a descriptor to that new account
7. add a new account. this one is called `Account #1`

**Comment by AndySchroder** [comment]
If I then delete the second `Account #1` then it will add `Account #2`, but then all added accounts after that are called `Account #2`.

**Comment by craigraw** [comment]
I can't reproduce this. Specifically in step 4, what are you doing in the UI?

**Comment by AndySchroder** [comment]
Will have to get back with you in a few days. There seem to be some nuances to how this scenario is created and I've noticed the behavior is different between sparrow 1.8.4 and 1.8.5 and I need some more time to more clearly debug.

**Comment by AndySchroder** [comment]
Okay, it seems as though the account number is taken by incrementing the derivation path by 1. So, I think the scenario I presented above was created by using descriptors with different xpubs but all the same derivation path of `m/84'/0'/0'`.

I would expect the account number to be taken by adding up the total existing accounts and then incrementing by 1. I think the situation here is that with watching only wallets, since BIP-0044 account discovery isn't really possible, and since there is no seed, you can't pre-populate the descriptor with an xpub computed for derivation path that is incremented by 1. Therefor the accounts in sparrow wallet must be flexible enough that they allow any descriptor to be input and they aren't necessarily all from the same wallet, so that's why you can't look at the derivation path and increment by 1.

This scenario here leads to similar discussion as in https://github.com/sparrowwallet/sparrow/issues/1379#issuecomment-2055656848 where the flexibility of sparrow allows it to be used in unusual ways. Possibly it might make sense to only allow secondary watching onlly accounts for single-sig descriptors that share the same master fingerprint? However, I'm not sure if that's a good idea because there is no way (without having the seed) to link the xpub to the master fingerprint and check that they are connected, is there? For multi-sig wallets where I don't know that the master fingerprint actually means anything, does it make any sense at all to allow to have secondary accounts?

**Comment by craigraw** [comment]
> So, I think the scenario I presented above was created by using descriptors with different xpubs but all the same derivation path of m/84'/0'/0'.

Although I see no strong reason to prevent it, this is not really a normal use case - different wallets should be used rather than different accounts in a single wallet. 

> I would expect the account number to be taken by adding up the total existing accounts and then incrementing by 1.

It's more likely that the user might be using the same seed, but a discontinuous range of accounts, in which case this approach fails. 

Rather, in your case, the user can simply rename their account tab appropriately. Right click on the account tab to do this. 

> For multi-sig wallets where I don't know that the master fingerprint actually means anything, does it make any sense at all to allow to have secondary accounts?

Certainly, just because there is no single master fingerprint doesn't mean multiple accounts aren't useful.

**Comment by AndySchroder** [comment]
Okay, so you want to mark this one as won't fix?

**Comment by craigraw** [comment]
After fixing an unrelated issue yesterday I've realised having accounts with the same name may cause other issues. As of 21d91d3d Sparrow will additionally check against existing account names when suggesting new accounts to add. This should solve both this issue, and the discontinuous range of accounts problem.
