### ISSUE TITLE
Coldcard multisig: Correct derivation not found for script type: P2WSH

### ISSUE THREAD

**Issue by akarve** [sparrowwallet/sparrow#1378]
Even Sparrow 1.85 shows the above error when reading a file from Coldcard, be it Generic JSON or in the "Sparrow" format (Coldcard claims the latter should work with single sig or multi sig).

Release notes show that an issue was fixed with Single-sig (I corroborate) but Multi-sig remains problematic.

Directly connecting the wallet via USB is a workaround.

**Comment by craigraw** [comment]
> Even Sparrow 1.85 shows the above error when reading a file from Coldcard, be it Generic JSON or in the "Sparrow" format (Coldcard claims the latter should work with single sig or multi sig).

It does look like Coinkite have recently added a P2WSH derivation to this export, but (as Sparrow notes in the Details link) the normal way of doing this is via by importing the file created by using the Settings > Multisig Wallets > Export XPUB > 0 feature on your Coldcard.

That said, I have made a change so the Sparrow will fall back to the singlesig import if importing the multisig format fails. c9b40b19.
