### ISSUE TITLE
automatically convert all watching only accounts in a wallet to software wallets if they share the same master fingerprint when a seed is added to one of them.

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1379]
If the first account in a wallet is a watching only wallet, any accounts added allow an arbitrary descriptor to be defined. So, we can actually add any watching only account derived from any seed into the same wallet file in sparrow. We can tell if the different accounts are actually from the same seed by comparing the master fingerprint. If we have multiple accounts added from descriptors that reference the same master fingerprint, when replacing the keystore in an account with a software wallet and a seed phrase, all accounts in the wallet that share the master fingerprint should be changed from a watching only wallet to a software wallet. As it is now, the rest of them just stay watching only wallets and you need to add the seed phrase to each one.

**Comment by craigraw** [comment]
What would be the use case here? Seems very niche.

**Comment by AndySchroder** [comment]
Possibly it is not worth pursuing, but this issue as well as https://github.com/sparrowwallet/sparrow/issues/1376 seem to allow the user to start using the wallet in unusual ways. I guess I'm trying to expose thees issues but don't necessarily know if they should be fixed. Wondering if it is worth trying to prevent these use cases rather than fix them?

It just seems weird to me that you can start to use the accounts feature as a way to have multiple totally different wallets instead of different accounts within the same wallet. Things could get confusing if people have too much flexibility.

It might be better to not allow replacing a watching only keystore with a software wallet keystore if the wallet has multiple accounts defined with user defined descriptors.
