### ISSUE TITLE
show warning before displaying seed words

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1380]
In https://github.com/sparrowwallet/sparrow/issues/1350 a QR code was added for the seed. A warning dialog box comes up before showing the QR code.

I'd argue that even showing the seed in text form deserves a warning. The text form of the words can also be a leak. Can we get a warning dialog box before clicking "View Seed..." too?

Showing the QR code is a bit more sensitive since cameras are intelligent enough to know that data should be in them, so I still think an extra (second) warning should be kept there before showing the QR code form of the seed phrase.

**Comment by craigraw** [comment]
I seed phrases are well enough understood to be sensitive that this is not necessary. In addition, for wallets with a password, the password is required first.

Marking as wontfix.

**Comment by AndySchroder** [comment]
I'm mostly concerned about accidental clicks here. For example, say you have a touch screen and you point at something and then accidentally touch and bring up the seed phrase.

**Comment by AndySchroder** [comment]
True, but if you don't have a password set for the wallet then there is no prompt. I agree if you set a password it will seem like an extra step, but maybe if no password is set then it is more appropriate to have another prompt?

**Comment by craigraw** [comment]
If you have no password set on a hot wallet, protecting the seed is clearly not a high priority - for example in a testnet wallet.
