### ISSUE TITLE
cycle through open wallets/tabs with Control+PageUp and Control+PageDown

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1381]
Please allow cycling through open wallets/tabs with Control+PageUp and Control+PageDown . This is a common feature for tabbed applications.

**Comment by craigraw** [comment]
This is already the case. The tabs need focus of course, but the key bindings work as they should for the different operating systems. If you find this is not the case, please comment.

**Comment by craigraw** [comment]
All of these suggestions require either overriding the focus handling, or common key bindings already in use on various operating systems. I am very reluctant to do - people come to expect certain behaviour, and trying to impose on that in general creates a worse UX for most people. It's possible to come up with less used key bindings, but of then they are difficult to ever learn about.
