### ISSUE TITLE
mention that `blockfilterindex=1` is recommended with bitcoin core

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1383]
With https://github.com/bitcoin/bitcoin/pull/25957 (see https://github.com/bitcoin/bitcoin/blob/e3c17112ddfe740e5ab4c652d80ed1a19c13da5a/doc/release-notes/release-notes-25.0.md?plain=1#L162) I think you should now recommend (but not require) `blockfilterindex=1` with bitcoin core in order to do faster rescans on https://sparrowwallet.com/docs/connect-node.html .

**Comment by craigraw** [comment]
Good idea, added.

**Comment by AndySchroder** [comment]
Wondering if this should be moved down next to the txindex part? Also mention that the blockfilterindex requires extra disk space too. Also, it will take some time to build the txindex and blockfilterindex for the first time.

**Comment by craigraw** [comment]
The blockfilterindex is small enough in comparison to the block storage and txindex that I think it can be added without too many additional considerations. Too much information/choices on this page would be overwhelming IMO. Everything will work well enough until the indexes are built.
