### ISSUE TITLE
Trezor T signing errors

### ISSUE THREAD

**Issue by Bonzbonanza** [sparrowwallet/sparrow#1384]
Of course, right after moving my largest piece of bitcoin into a Sparrow wallet using my Trezor T it doesnt want to sign a transaction to send out funds. I invariably get a HWI error and if I rescan enough I get no matching devices. I have gotten to the point where the Replace button is finally an option so I have changed to a Software wallet as a temporary measure and have gotten as far as the last screen where I am warned that "Existing transactions will be replaced as the wallet addresses will change. Do you want to Proceed?" The pressing question is, do I? This sounds like it will delete the balance which is a bad option. What is the expectation?

Then, there should be an investigation into why the Trezor isn't detected. I have verified the seed with the Trezor Suite and know the passphrase as well.

**Comment by Bonzbonanza** [comment]
--Error executing HWI--

That is the first error when trying to sign the transaction.

**Comment by Bonzbonanza** [comment]
It seems to have been a passphrase issue. 

For the sake of the person who finds this thread on a search in the future, if you do change a wallet to a software wallet from a hardware wallet, what happens with your balance? If it disappears, what is the use case of ever wanting to switch wallet type?

**Comment by craigraw** [comment]
> For the sake of the person who finds this thread on a search in the future, if you do change a wallet to a software wallet from a hardware wallet, what happens with your balance?

If it's the same seed, the balance will remain the same.

Closing this off.

**Comment by Bonzbonanza** [comment]
Before you close it, let me suggest that you warn the noob, like myself, about that last phrase.

The word "replace" is not necessarily intuitive. I thought that I could replace my lost device with a random software wallet as a salvage operation which is incorrect. Maybe "substitute" is a battery choice, or a short reminder that a new seed is a new wallet. When it all happens under the tab of an existing wallet it seemed like you had magically solved my problem! :)

Karl Leibensperger, DO

Sent from Proton Mail Android

-------- Original Message --------
