### ISSUE TITLE
Cannot import a wallet on regtest

### ISSUE THREAD

**Issue by cryptoquick** [sparrowwallet/sparrow#1387]
I'm trying to load this regtest / testnet wallet, but every time I set it in the Settings editor, it loses the derivation path.
`tr([86h/1h/0h]xpub6DKQnNbWQ4hBURTiNzn9nntzjHVwPboz7gNTcp2N1a7QVVrnKjNHJi5RtCxPLSxGuUDhcaAnqeLwCCFYFz8gZXvnHkKRQw6uAZGfYU6A6ye/<0;1>/*)`

**Comment by craigraw** [comment]
According to [BIP380](https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki#key-expressions), this is not a legal output descriptor as the key origin information does not include the master fingerprint.

However, I've made Sparrow more lenient in https://github.com/sparrowwallet/drongo/commit/3a2344f1297e25a9c691ddad66264e00c391af44 to allow for descriptors with incomplete key origins.

**Comment by cryptoquick** [comment]
Wow, that was quick! Thank you!

**Comment by cryptoquick** [comment]
So, I tried this out, and there's just one problem. If I attempt to edit the descriptor like so:

`tr([5a32a844/86h/1h/0h]xpub6DKQnNbWQ4hBURTiNzn9nntzjHVwPboz7gNTcp2N1a7QVVrnKjNHJi5RtCxPLSxGuUDhcaAnqeLwCCFYFz8gZXvnHkKRQw6uAZGfYU6A6ye/<0;1>/*)`

I click OK, but it won't let me click Apply. Further, if I close the wallet and reopen it, the modified derivation path doesn't persist.

**Comment by craigraw** [comment]
If you are on mainnet (I assume you are because you are using a mainnet xpub), you'll need to disable derivation path validation in the General Preferences. This is because you are using the default derivation path for testnet, likely leading to unintentional reuse of keys.

**Comment by cryptoquick** [comment]
Oh! Good point! I just reloaded by wallet and found the proper xpub for testnet.

`tr([5a32a844/86'/1'/0']tpubDDD2SBj6Y2HnR7GShSdwM2HuFcpx8Cm4sdPGdaTpra1nx5HtPvwNFivx2UDR11FURvXahDL3hrTDZArqE3om2dW27dgeCSYYtREudnGdDgm/0/*)`

When I try to edit now, I get the message, "Invalid output descriptor", "Provided tpub extended key invalid on configured mainnet network. Use a testnet configuration to use this extended key."

The only problem is, I'm not sure how to use a testnet configuration. I've checked all the menus I can think of checking... If there is a way, it's non-obvious.

**Comment by craigraw** [comment]
> The only problem is, I'm not sure how to use a testnet configuration.

If you are running from source, you'll need to use `./sparrow -n testnet`

> Disabling validate derivations doesn't seem to help.

Working fine on this side. Suggest creating a new wallet and reimporting.
