### ISSUE TITLE
Issue scanning signed transaction QR from Specter-DIY

### ISSUE THREAD

**Issue by alexbowe** [sparrowwallet/sparrow#139]
When co-signing in a multi-sig with a Specter-DIY I can't read the signed PSBT.

The Specter-DIY signs the PSBT fine whether it is transmitted via QR or SD card.

When I try to scan the QR code into Sparrow, the blue bar fills up, but the camera window doesn't disappear.

When I try to load the PSBT from the SD card, I get this error:

![image](https://user-images.githubusercontent.com/208211/122543126-490aca80-cfe0-11eb-94d0-8cd266533a58.png)

I have tested QR signing with this device on Specter and Blue Wallet and it works in both cases.

Specter-DIY has a [simulator](https://github.com/cryptoadvance/specter-diy), which might help with this issue.

CC @stepansnigirev

**Comment by craigraw** [comment]
Support for Specter DIY's trimmed PSBTs has already been added in https://github.com/sparrowwallet/sparrow/commit/600a77da3ae33bd283980c490cbf7b771707cb8e (not yet in a binary release).
