### ISSUE TITLE
can't edit the descriptor of the second account with a text box but can with a camera and QR code

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#1390]
1. Create new wallet
2. Settings Tab
3. Click "Edit" next to the descriptor
4. Paste a descriptor
5. Click OK
6. Apply
7. Add account
8. OK
9. "Edit" button is not available. You can only scan a QR code or show an incomplete descriptor that has no master fingerprint or xpub.

I don't understand why the second account can't add a descriptor by pasting into the text box, but it can by scanning a QR code. It seems like both options should always be available.

**Comment by craigraw** [comment]
I've allowed editing of the output descriptor of a new account on a watch only wallet in 1887e1c7. Changing the policy or script type won't be allowed though.

**Comment by AndySchroder** [comment]
So, if you paste or scan a descriptor that uses a different script or policy type, will it error out or it just sneaks the script or policy type change through that way?

**Comment by craigraw** [comment]
It will show an error, and no change to the wallet will be made.

**Comment by AndySchroder** [comment]
Nice, sparrow wallet gets better every day!
