### ISSUE TITLE
Allow me to add UTXO (pending or not) to "Cancel RBF"

### ISSUE THREAD

**Issue by donnlee** [sparrowwallet/sparrow#1393]
I did an issue search and https://github.com/sparrowwallet/sparrow/issues/108 says:
```
> Creating fully custom RBF mean I ignore the transaction, use the same UTXO,
> combine with other UTXO, and send the BTC elsewhere.

True - with Sparrow you can remove UTXOs from a replacement tx but not add others.
```
Is this still the case?
Sometimes I need to totally "re-make" a SET of broadcasted txns.
Here is a use-case I run into:
1. I have 3 txns (example) in the mempool. For simplicity, each txn has 2in/2out.
2. After some minutes, I need to cancel all 3 txns and create a new txn with some of those inputs.

What I want to do:
I would like to `Cancel RBF` one of those txns. Then in the `Send` screen I will create the new txn and Sparrow will give me complete freedom to select any UTXOs **INCLUDING UTXOs of unconfirmed txns** to ADD as inputs.
So I will add inputs from the 2nd and 3rd txns such that the new txn has inputs from all 3 unconfirmed txns (eg. 1 input from each unconfirmed txn).
Thus, with just one new txn, I can "RBF-Cancel" all 3 txns and create a 4th txn that has a completely different objective.
Instead of 3 txns in this example, I have had as many as ~10 txns.

**Another use-case:**
I broadcast a txn with 1in/1out.
After some minutes, feerates have risen and I want to increase my feerate to be included in the next block.
I click `Increase fee (RBF)`, but I don't see my original input (1in) in the `Send` screen. Instead i see Sparrow has added ~70 inputs!
So i go back and click `Cancel RBF` and now I can make a new txn with the original input.
But now I can't find a way to add more UTXOs (sats) to the inputs!
I would like to add more inputs in the `Send` screen so my 1in/1out can be RBF'd with a 3in/1out, for example.

Pls let me know if these two use-cases can be done.
Thank you

**Comment by craigraw** [comment]
> Is this still the case?

In general, yes. 

> Sparrow will give me complete freedom to select any UTXOs INCLUDING UTXOs of unconfirmed txns to ADD as inputs.

Technically this is possible, practically the UX is quite difficult. I'd like to support it, but finding a way to do it that doesn't make the default "straightforward" method more complicated is necessary.

> But now I can't find a way to add more UTXOs (sats) to the inputs!

Did you actually have a requirement to do so? Sparrow will automatically enough UTXOs to allow the fee rate slider to be set to the maximum "high priority" fee rate.

Note that `Increase fee (RBF)` and `Cancel RBF` run the same code - the difference lies only in the output (and in use, the random additional UTXO selection).

**Comment by donnlee** [comment]
> Did you actually have a requirement to do so?
Yes, because the original txn was a 1in/1out.  I needed to add more inputs to increase the fee and I couldn't figure out a way to add them.
Next time I will try moving the fee slider right away.  I notice when the slider moves, lots of things recalculate/animate.
Maybe that will help.

**Comment by craigraw** [comment]
>  I needed to add more inputs to increase the fee

Sparrow had already added enough input value to pay the current high priority fee rate.

**Comment by donnlee** [comment]
Seems sparrow added 70 utxo's when only 1 or 2 were needed.
Is this expected?
I had to click 68 times to reduce the input set to 2 inputs.

**Comment by craigraw** [comment]
The selection is random - if you start with few small UTXOs, lots more need to be added as each increases the transaction size. 

It's a little cumbersome, but if you freeze all but the UTXOs you want to spend, Sparrow will respect that.

**Comment by donnlee** [comment]
Freezing 90% of my utxo's worked.
Thank you
Big learning for me is that Increase Fee and Cancel RBF run the same code
