### ISSUE TITLE
Transaction Not Appearing in Sparrow Wallet

### ISSUE THREAD

**Issue by twhite3600** [sparrowwallet/sparrow#1394]
I am a new user of the Sparrow app and have recently created a new Airgapped wallet.  Once I had the wallet set up I transferred bitcoin from my Muun wallet to my Sparrow Airgapped Wallet and now this transaction does not appear in the Sparrow wallet.  The transaction has been confirmed and completed on my Muun wallet but the transaction information to date has not shown up on my Sparrow wallet.  I checked and confirmed that the addresses match in both wallets as well as on my Cold Card wallet. 
Could you please assist me in resolving the issue of the transaction not appearing in the Sparrow wallet.

Teresa (Nicole) White
email address:  nickrnmi1971@gmail.com
Phone:  1-518-384-1271

**Comment by craigraw** [comment]
If the addresses match, you have a wallet loading issue. Make sure that Sparrow is online - see the toggle in the bottom right corner. Make sure it is on. Once it is, try to refresh the wallet (View menu).

Note user support queries are best handled on http://t.me/SparrowWallet.
