### ISSUE TITLE
Derivation path (bug)

### ISSUE THREAD

**Issue by 91anon93** [sparrowwallet/sparrow#1397]
Sparrow does not accept derivation path when copy-pasted, 
![image](https://github.com/sparrowwallet/sparrow/assets/155928550/9fe9dad6-4cc8-488f-a42e-6651573a9f3f)

so I have to enter it manually.
![image](https://github.com/sparrowwallet/sparrow/assets/155928550/d92f4ad4-b791-4f51-8319-a7787b225060)

**Comment by craigraw** [comment]
It's unclear, but you may have been trying to enter the default testnet derivation path for Native Segwit into a mainnet wallet. If you want to allow this, disable derivation path validation in the General Preferences.
