### ISSUE TITLE
The program does not run

### ISSUE THREAD

**Issue by ETHSev** [sparrowwallet/sparrow#1399]
When I run the program it gives me an error in a window.
“Failed to launch JVM”
When I close it it gives me another window.
“Child Process exited with code 1”
I use windows server 2022.
The problem is that it worked fine before.
![Sparrow error](https://github.com/sparrowwallet/sparrow/assets/95754429/7c465e1f-45ff-4520-bb28-811785931351)

**Comment by craigraw** [comment]
Please provide your sparrow.log, as requested.

**Comment by ETHSev** [comment]
where i can find it ?

**Comment by craigraw** [comment]
Good to hear, closing this off.
