### ISSUE TITLE
Fee too low

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#14]
Can the fee range be prevented from going below 1 sat/byte?
I believe this causes the transaction signing to fail and the message is not clear.

<img width="807" alt="Screen Shot 2020-09-21 at 3 00 13 PM" src="https://user-images.githubusercontent.com/807505/93809794-b9381b80-fc1b-11ea-936b-b068f194678d.png">

**Comment by craigraw** [comment]
I'll look into this - the Electrum server protocol does have a (now deprecated) call blockchain.relayfee which returns the minimum fee for the bitcoind node it is connected to.

**Comment by craigraw** [comment]
Implemented in https://github.com/sparrowwallet/sparrow/commit/e48e40da0dc637f21ec2e8f0f73aa151bba1e6a1

The minimum fee rate is now retrieved, the block target rates are adjusted if necessary and validation is performed on the fee field to ensure that the fee rate is sufficient.
