### ISSUE TITLE
resizing window on fedora

### ISSUE THREAD

**Issue by gilles-homez** [sparrowwallet/sparrow#1406]
Dear Sparrow Wallet Team,

I am experiencing an issue with Sparrow Wallet on my Fedora system running GNOME with Wayland. The main window of Sparrow Wallet is too large for the screen and cannot be resized effectively to fit. Adjusting the application's window to a usable size has proven to be challenging without affecting the scaling of other applications on the system.

System Details:

OS: Fedora Linux 38 (Workstation Edition)
Environment: GNOME 44.10 on Wayland
Display Resolution: 1920x1080
Attempts to Resolve the Issue:

Adjusting GDK_SCALE and QT_SCALE_FACTOR environmental variables, but these did not influence the Sparrow Wallet window as expected.
Trying to force the application to use XWayland with GDK_BACKEND=x11 did not resolve the issue and resulted in a non-responsive, black window.
Temporarily changing the system's screen resolution or scaling affects all applications and is not a viable long-term solution.
The only workaround that has had some effect is changing the global scaling setting via GNOME's display settings, but this solution is far from ideal as it impacts all applications.

It appears there might be an issue with how Sparrow Wallet handles window scaling or interacts with GNOME's Wayland session. Could you please look into this issue? Any guidance on possible settings within Sparrow Wallet that I might have missed or any upcoming fixes would be greatly appreciated.

Thank you for your assistance.

Best regards,
Gilles Homez

**Comment by craigraw** [comment]
See https://sparrowwallet.com/docs/faq.html#sparrow-is-too-big-for-my-screen - this setting will only impact Sparrow.
