### ISSUE TITLE
New incompatible BBQr format causing confusion

### ISSUE THREAD

**Issue by cryptoquick** [sparrowwallet/sparrow#1407]
Confusion is being caused for users of existing devices, like the Foundation Passport and SeedSigner, by the incompatible BBQR code standard. Since its improvements are marginal at best, since only 1 bit is saved in the encoding, I'd recommend removing it entirely. That said, if that's not desirable, in the very least change the default to how it used to work before.

**Comment by craigraw** [comment]
This comment doesn't make much sense to me. Sparrow continues to use BC-UR encoding as default, unless the configured device in the keystore is a Coldcard. 

> That said, if that's not desirable, in the very least change the default to how it used to work before.

This is already the case.
