### ISSUE TITLE
Cannot Sign PSBT 

### ISSUE THREAD

**Issue by macdank415** [sparrowwallet/sparrow#1408]
I set up a multi-sig wallet requiring 1 of 2 keys but the second key was not finalized.  Cannot sign the PSBT.   

<img width="644" alt="Screenshot 2024-04-29 230350" src="https://github.com/sparrowwallet/sparrow/assets/168513567/a1781463-ad7f-4465-ae26-d7de12797027">

**Comment by macdank415** [comment]
Is this a bug?  Even when I change the multi-sig wallet to 1of1 I cannot sign the PBST.

**Comment by craigraw** [comment]
It's unclear what you are doing. Your screenshot shows an incomplete multisig wallet. Then, you mention a PSBT, presumably created from somewhere else. You will need the same wallet configuration in Sparrow as that "somewhere else" that created the PSBT.

**Comment by macdank415** [comment]
Hello,So I didn’t realize that using two same signers (cold card and ledger) would recreate the same wallet I already have.  I decided to remove the ledger in the 1 of 2 multisig wallet setup, and sent the btc to the wallet.  Today, I tried to send the btc out of the wallet but the cold card wouldn’t sign the PSBT. When I change the multisig setup to 1 of 1 (cold card only) the btc is visible but still would sign the PSBT. If I use a different signer there is an error stating the transaction will be wiped.On Apr 30, 2024, at 12:36 AM, craigraw ***@***.***> wrote:﻿
It's unclear what you are doing. Your screenshot shows an incomplete multisig wallet. Then, you mention a PSBT, presumably created from somewhere else. You will need the same wallet configuration in Sparrow as that "somewhere else" that created the PSBT.

**Comment by craigraw** [comment]
> I decided to remove the ledger in the 1 of 2 multisig wallet setup

This creates an entirely different wallet, with different addresses.

> When I change the multisig setup to 1 of 1

Again, this creates an entirely different wallet. 

You need to use (or recreate) the original wallet into which you received the funds, in order to spend it.

**Comment by macdank415** [comment]
If the multisig wallet is incomplete, does that mean the btc is inaccessible even though I have the cold card  signer? On Apr 30, 2024, at 1:00 AM, Daniel Kwon ***@***.***> wrote:﻿Hello,So I didn’t realize that using two same signers (cold card and ledger) would recreate the same wallet I already have.  I decided to remove the ledger in the 1 of 2 multisig wallet setup, and sent the btc to the wallet.  Today, I tried to send the btc out of the wallet but the cold card wouldn’t sign the PSBT. When I change the multisig setup to 1 of 1 (cold card only) the btc is visible but still would sign the PSBT. If I use a different signer there is an error stating the transaction will be wiped.<image0.jpeg><image1.jpeg>On Apr 30, 2024, at 12:36 AM, craigraw ***@***.***> wrote:﻿
It's unclear what you are doing. Your screenshot shows an incomplete multisig wallet. Then, you mention a PSBT, presumably created from somewhere else. You will need the same wallet configuration in Sparrow as that "somewhere else" that created the PSBT.

**Comment by macdank415** [comment]
That is this wallet.  1 of 2 wallet with only one signer established.  I guess the there is no hope to access the funds. noThanks,DanielOn Apr 30, 2024, at 1:04 AM, craigraw ***@***.***> wrote:﻿

I decided to remove the ledger in the 1 of 2 multisig wallet setup

This creates an entirely different wallet, with different addresses.

When I change the multisig setup to 1 of 1

Again, this creates an entirely different wallet.
You need to use (or recreate) the original wallet into which you received the funds, in order to spend it.

**Comment by macdank415** [comment]
The wallet address I sent btc to with 1 of 2 signors established was  bc1qnskfxeahrseh0fcqw5lwwgfsyuea877x2z852q654lzfuapsnrmsrfavvr.   I still have this wallet and when I realized that it wasn't a new wallet, I removed the ledger and sent the funds to  bc1q9wrq2rj8dr6gmlfl7f87tdp7t0s3tzexlxadjz9znf8wtgyfad5sxpq5tq . BTC is now stuck there and cannot sign the PSBT.



    On Tuesday, April 30, 2024 at 01:36:08 AM PDT, craigraw ***@***.***> wrote:  
 
 



That is this wallet. 1 of 2 wallet with only one signer established.


If you never completed the wallet setup, you never received an address from Sparrow to deposit funds. It is technically impossible to do so.

**Comment by craigraw** [comment]
The funds are not stuck - you just need to recreate the wallets that you sent funds to. You have all of the information necessary to do this.

I suggest using File > New Wallet to create new wallets to do so.

Closing this off as user support.
