### ISSUE TITLE
Invalide file when import `Bitcoin Core.dat` file (encrypted and unencrypted)

### ISSUE THREAD

**Issue by CruiseMan** [sparrowwallet/sparrow#141]
Created wallet in `Bitcoin Core` and trying to import it, bet getting error: `Input is not base64 or hex`
<img width="364" alt="Screen Shot 2021-06-23 at 1 14 38 PM" src="https://user-images.githubusercontent.com/15807643/123162028-f89ecd00-d424-11eb-9c86-92d225838e40.png">

App: 1.4.2
Bitcoin Core 0.21.1

**Comment by CruiseMan** [comment]
Restarted the app and imported again unencrypted .dat file wich doesnt' require a password, just hit `Unlock` and got error:
<img width="363" alt="Screen Shot 2021-06-23 at 1 19 21 PM" src="https://user-images.githubusercontent.com/15807643/123162584-a14d2c80-d425-11eb-8f02-af73fe20f363.png">

**Comment by craigraw** [comment]
Sparrow doesn't support importing Bitcoin Core wallet database files directly. Adding support for this would require adding a dependency on BerkeleyDB/SQLite, and parsing the database. 

With recently created wallets, you can export the output descriptor from Bitcoin Core and enter it into Sparrow (Edit the Descriptor field in the Settings). With older Bitcoin Core wallets, you'll need to sweep the funds out into a new Sparrow wallet.

**Comment by J1ngle** [comment]
With recently created wallets, you can export the output descriptor from Bitcoin Core and enter it into Sparrow (Edit the Descriptor field in the Settings). With older Bitcoin Core wallets, you'll need to sweep the funds out into a new Sparrow wallet.

May I ask how to do this ? I got my descrpitors from Bitcoin Core

**Comment by craigraw** [comment]
> With older Bitcoin Core wallets, you'll need to sweep the funds out into a new Sparrow wallet.

Sending the UTXOs out one by one is the most private approach.

**Comment by J1ngle** [comment]
> 

Thanks Carigraw for the reply. My bitcoin core descrpitors are inscribed with ordinals inscription, and would like to import the whole wallet into sparrow. Sending the UTXOs is quite expensive through the high gas network .

I found some solution that say I can use output descriptor from bitcoin core and enter into sparrow. Any more information I can follow? Thank you .

**Comment by craigraw** [comment]
> I found some solution that say I can use output descriptor from bitcoin core and enter into sparrow. Any more information I can follow?

You can create a new Sparrow Wallet, edit the Descriptor field, and paste in the output descriptor from Core.
