### ISSUE TITLE
Incorrect Multisig Threshold Import Issue

### ISSUE THREAD

**Issue by giahuy98** [sparrowwallet/sparrow#1410]
When importing a wallet with a threshold greater than or equal to 10 using BSMS or Output Descriptor for wallet import, Sparrow appears to import the wrong multisig threshold, setting it as 1 instead of the correct value.

```
Sparrow --version
Sparrow Wallet 1.9.0
```
[10-of-10-bitcoincore.txt](https://github.com/sparrowwallet/sparrow/files/15195411/10-of-10-bitcoincore.txt)
[10-of-10-bsms.txt](https://github.com/sparrowwallet/sparrow/files/15195413/10-of-10-bsms.txt)
![image](https://github.com/sparrowwallet/sparrow/assets/100193713/348650dd-09b1-4fa9-889b-9ee57126c915)

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in https://github.com/sparrowwallet/drongo/commit/9d250437ad7e59eba7bf7c7d3f73b936a91d262e.
