### ISSUE TITLE
 BBQR Import from Nunchuk Fails

### ISSUE THREAD

**Issue by giahuy98** [sparrowwallet/sparrow#1411]
Sparrow fails to import BBQR from Nunchuk in Z format due to premature decompression. According to BBQR specifications, decompression should start only after receiving all parts (https://bbqr.org/BBQr.html#advanced-encodings). However, Sparrow decompresses upon receiving the first part (https://github.com/sparrowwallet/sparrow/blob/master/src/main/java/com/sparrowwallet/sparrow/io/bbqr/BBQRDecoder.java#L35), leading to import errors `Error inflating with zlib`.

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 7b0dfd66 and tested working against Nunchuk.
