### ISSUE TITLE
Improve Electrum Wallet Export

### ISSUE THREAD

**Issue by jlopp** [sparrowwallet/sparrow#1415]
Interesting edge case I came across recently:

I set up a multisig wallet in Sparrow with Keystones, Ledgers, and Trezors. I then wanted to test the wallet in Electrum so I exported the wallet as electrum compatible JSON.

However, opening in Electrum crashed due to an unknown hardware type (keystone):

```
  File "/tmp/.mount_electrl9ABhr/usr/lib/python3.10/site-packages/electrum/keystore.py", line 1082, in hardware_keystore
    raise WalletFileException(f'unknown hardware type: {hw_type}. '
electrum.util.WalletFileException: unknown hardware type: keystone. hw_keystores: ['bitbox02', 'coldcard', 'digitalbitbox', 'jade', 'keepkey', 'ledger', 'safe_t', 'trezor']
```

I'm thinking that perhaps a good workaround would be to export unsupported hardware keys as "watch only" keys for Electrum.

**Comment by craigraw** [comment]
Thanks for reporting - it would probably be good for Electrum to handle this better, but I've implemented b59a65dc to only export usb capable hardware wallets as `hardware` keystore types.
