### ISSUE TITLE
[Feature request] Keep " Connected to ... "

### ISSUE THREAD

**Issue by TinF0ilHat1** [sparrowwallet/sparrow#1416]
Do you see any drawback keeping it? Block height can disappear.

![Screenshot from 2024-05-10 21-46-32 cleaned](https://github.com/sparrowwallet/sparrow/assets/127325867/3ddec736-00fe-4d11-818f-48d1ec422359)

It comes in handy when [ ` "loadRecentWallets": false,]
` dealing with multiple wallets and different nodes.

**Comment by craigraw** [comment]
I assume you mean whether status messages disappear after awhile? Yes, the drawback is a more cluttered interface. You can see this message (including the block height) at any time by the tooltip over the online/offline toggle in the lower right.
