### ISSUE TITLE
More conservative Java version requirements? (Keeping it compatible with at least current Debian versions)

### ISSUE THREAD

**Issue by stuser81** [sparrowwallet/sparrow#1417]
For security reasons, some of us cannot install packages on Debian other than official Debian repos. This means:

* Debian 11 Bullseye: Java 11
* Debian 12 Bookworm (current latest): Java 17
* Debian 13 Trixie (future version est. 2025): still set at Java 17 (although I hope eventually they update it to at least 18).

Any chance, moving forward, to be more conservative with Java versions and keeping it align with Debian? It makes sense as Sparrow is supposed to be a security-focused wallet. A part of that means, making possible to run it for security-focused Debian users.

Because of this I can't currently use Sparrow wallet. If you e.g. keep the version requirement at 18, and Debian 13 Trixie (hopefully) update to >= 18, I can start using Sparrow in 2025.

**Comment by stuser81** [comment]
Actually, any chance you could downgrade the Java requirement to 17? This way I could already use Sparrow now (on Debian 12). Java 17 is also LTS: https://en.wikipedia.org/wiki/Java_version_history

Are there any crucial features in Java 18 that you need?

**Comment by craigraw** [comment]
What stops you from simply using the Sparrow binaries?

**Comment by stuser81** [comment]
> What stops you from simply using the Sparrow binaries?

Thanks, I didn't realize Java wasn't require to run the binary and the build is reproducible.
