### ISSUE TITLE
Bitcoin Core - what's the real issue?

### ISSUE THREAD

**Issue by stuser81** [sparrowwallet/sparrow#1418]
I came to Sparrow from Electrum wallet, with hope to cut out the electrumx middle man - would be great to have only Bitcoin Core to worry about.

But now this warning scares me: "This [connecting to Bitcoin Core] means you are not sharing your transaction data, but be aware Bitcoin Core stores your balance, transactions and public keys unencrypted on that node, which is not ideal for true cold storage."

1. By connecting Sparrow to Bitcoin Core, what files precisely in my Bitcoin Core blockchain directory will be modified?
2. Is there no way to somehow delete/revert these modifications after I quit Sparrow wallet?

**Comment by craigraw** [comment]
Github is not the right place to ask user support questions. But to answer it, Sparrow creates and uses a Bitcoin Core wallet called `cormorant` to store information about wallets you load. Bitcoin Core in turn uses this information to retrieve transactions affecting the wallets. You can delete the `cormorant` wallet after you close Sparrow, but if you do so you'll need to rescan the blockchain again should you want to reload those wallets.
