### ISSUE TITLE
BBQR minor issues

### ISSUE THREAD

**Issue by odudex** [sparrowwallet/sparrow#1419]
I've been exploring BBQR integration within Krux and encountered minor issues involving Sparrow. They might stem from Krux itself; please disregard them if they're not reproducible on your end. I am currently using Sparrow 1.9.1 on Windows. Here are the specific problems I've noted:

- BBQR Button Accessibility: When operating in the transaction window, the BBQR button is not visible, despite I was pretending to use a Coldcard as signer. To access BBQR option, I have to navigate through File -> Show PSBT as QR.
- QR Code Window Behavior: After scanning and signing the BBQR with my Krux device, selecting "Scan QR" in Sparrow results in the QR code window unexpectedly closing.
- Transaction Window Compatibility: The transaction window displays an UR QR code by default, not having the option to use BBQR. Attempting to scan a BBQR in this window (exported as an uncompressed PSBT with encoding set to "2") results in a parsing error. Notably, Nunchuck successfully parses the BBQRs generated by Krux.

I still can't export compressed, "Z" encoded PSBTs in Krux, I will try again when possible.
Please let me know if further information is needed or if there are specific logs that would help in addressing these issues.

**Comment by craigraw** [comment]
> When operating in the transaction window, the BBQR button is not visible, despite I was pretending to use a Coldcard as signer. 

I can't reproduce this. Sparrow follows the logic described in [this comment](https://github.com/sparrowwallet/sparrow/issues/1414#issuecomment-2102393397) when deciding whether to show and select the BBQR button on the QR display dialog. Let me know if you would like the BBQR button to be shown (and selected?) for Krux devices.

> After scanning and signing the BBQR with my Krux device, selecting "Scan QR" in Sparrow results in the QR code window unexpectedly closing.

It's not clear to me what you mean by "unexpectedly closing" - on pressing "Scan QR", Sparrow should close the QR display dialog and open the QR scan dialog. If that's not happening, please check for an error in sparrow.log.

> The transaction window displays an UR QR code by default, not having the option to use BBQR. 

See above.

> Attempting to scan a BBQR in this window (exported as an uncompressed PSBT with encoding set to "2") results in a parsing error.

I don't have the means to reproduce this unfortunately. I will note though that "Z" encoding is the same as the "2" encoding, just with compression at the beginning or decompression at the end. Sparrow scans "Z" encoding BBQR from Nunchuk successfully.

**Comment by odudex** [comment]
Sorry, me again. I probably made a confusion during tests. Sparrow still fails to parse PSBTs signed by Krux. Upon examining a PSBT signed by Coldcard Q1, which Sparrow accepts, I noticed it uses hex encoding and produces a compact signed PSBT, excluding the header b"psbt..." among other data. Thus, I wonder: Does Sparrow's BBQR require the PSBT to be compact or hex encoded?

**Comment by craigraw** [comment]
Sparrow reads both binary and hex encoded PSBTs. If there's a PSBT parsing issue, it should be in the log file. Not sure what compact is?

One thought: For base32 encoded sends, Sparrow will decode each fragment individually, so they must be modulo 8 in length.

**Comment by craigraw** [comment]
Ok, that's useful - then issue has nothing to do with BBQR, but rather that Sparrow was unable to successfully verify the partial signatures provided on one or all of the inputs. This might be because the `PSBT_IN_NON_WITNESS_UTXO` or `PSBT_IN_WITNESS_UTXO` field was missing, or simply that the signature was incorrect for some reason.

**Comment by odudex** [comment]
I must be corrupting data somewhere, because same signatures are accepted when saved in a SD card, or encoded in UR.
In Nunchuk the signatures are accepted as BBQr too.
I caught a decoding issue and generated a new [Android APK](https://github.com/odudex/krux_binaries/raw/main/Android/Krux_24.04_BETA_31_Android_0.14_BBQrT_2.apk), but I am still failing to export something Sparrow will accept.

**Comment by craigraw** [comment]
If you can send a test PSBT, I'm happy to load it on this side to determine the exact cause of the failure.

**Comment by craigraw** [comment]
Thanks, I've been able to confirm the cause.

The issue here is as I suggested previously - Krux is not including the `PSBT_IN_WITNESS_UTXO` field on the inputs in the signed PSBT (even though they are provided in the PSBT created by Sparrow for signing). Without this field, the signature cannot be verified independently, as the hash being verified cannot be recreated.

This is true for both the BBQR encoded version, and the `sparrow_bbqr_test-signed-SD.psbt` provided in the .zip, both of which (on my side) produce the error related to the signatures being unverifiable.

**Comment by odudex** [comment]
Confirmed. By including `PSBT_IN_WITNESS_UTXO`, Sparrow will accept it. Additionally, this inclusion allows Sparrow to verify signatures even without the original, unsigned PSBT loaded.
Is it correct to conclude that BBQr will always require `PSBT_IN_WITNESS_UTXO`, regardless of whether the unsigned transaction is loaded or not, while SD card and UR formats may not require it if the unsigned transaction is loaded?
Regardless, it is advisable to always include `PSBT_IN_WITNESS_UTXO` for consistency?

**Comment by craigraw** [comment]
> Regardless, it is advisable to always include `PSBT_IN_WITNESS_UTXO` for consistency?

Yes, it's actually a required field in this case per BIP174. It could be better specified, but the description for the `PSBT_IN_NON_WITNESS_UTXO` field in BIP174 says:

>  This should be present for inputs that spend non-segwit outputs and can be present for inputs that spend segwit outputs.

Then, for the `PSBT_IN_WITNESS_UTXO` field:

> This should only be present for inputs which spend segwit outputs, including P2SH embedded ones

In any case, I think the value of having a PSBT containing enough information for anyone to verify the signatures is very useful - I certainly value Sparrow's ability to do this.

**Comment by craigraw** [comment]
Great to hear.

I've added BBQr as a (non-default) option for Krux wallets in 6e4d308c. 

Can we close this off?

**Comment by odudex** [comment]
Great! Thank you for all!
