### ISSUE TITLE
Passphrase has no effect (Testnet)

### ISSUE THREAD

**Issue by Steampowered-hippo** [sparrowwallet/sparrow#1420]
Hi,
I created a Wallet in Sparrow (just for testing purposes) in Testnet some months ago with a Password and an additional Passphrase. Now I opened this Wallet (Testnet3) but accidentally typed the wrong Passphrase. But anyway the Wallet showed the transactions.

Expected behaviour:
The wallet opens but does not show any transactions, as the seedphrase plus the wrong passphrase should create a different wallet

Sparrow Wallet V 1.9.1
on MacOS Sonoma 14.5

**Comment by craigraw** [comment]
If the wallet is offline, it will continue to show the old transactions. See https://sparrowwallet.com/docs/faq.html#all-my-addresses-have-changed

**Comment by Steampowered-hippo** [comment]
Ah ok, thanks, that's it!
