### ISSUE TITLE
[Feature Request] Randomize version/Locktime on each transaction

### ISSUE THREAD

**Issue by 4rkad** [sparrowwallet/sparrow#1424]
It would be interesting to randomize both the version and the locktime of each transaction to complicate the analysis and avoid detecting which is the change address. This is because analysts often look for consistencies and patterns in transactions to infer change addresses. 

By introducing variations in these fields, the complexity of heuristic analysis is increased since transactions with non-uniform characteristics are created, making it harder to identify clear patterns. This, in turn, enhances the user's privacy by making it more difficult for analysts to differentiate between outputs that are actual spends and those that are change addresses.

<img width="906" alt="Screenshot 2024-05-20 at 13 44 21" src="https://github.com/sparrowwallet/sparrow/assets/55397917/56b277d6-fcb5-4bcb-af52-c8b12fe18cc2">

**Comment by craigraw** [comment]
For randomizing the version number, see #1178.

Re locktime, for non-Taproot wallets I think the greater anonymity set is found by simply implementing anti-fee-sniping, as Sparrow does now. Of course this is debatable, but anti-fee-sniping is widely implemented across many wallets.

For Taproot wallets, Sparrrow has implemented BIP326, which is specifically designed to randomize nLocktime and nSequence for greater anonymity, especially with the likely large number of PTLCs in future.
