### ISSUE TITLE
Fee Setting is ignored on "Sweep Private Key" feature

### ISSUE THREAD

**Issue by petzsch** [sparrowwallet/sparrow#1425]
No matter what I set as fee in the first screen, the resulting transaction always results in a 111 sats fee (1,02 sats/vB)

I'm sweeping from a native-segwit address to a native-segwit address (external, not part of the open wallet).

Hope you can repro. Let me know if you need any more details.

EDIT: On 1.9.1 on Windows 11.

**Comment by petzsch** [comment]
It might have been an edge case: The private key had a balance of 1,000 sats and I tried to sweep with 7,1 sats/vB. The resulting fee would have exceeded the total available balance.

Still would be nice to handle such cases with a warning message or something.

**Comment by craigraw** [comment]
Yes, this is expected behaviour for this edge case, but I agree it appears unexpected. I've added a warning in afb60374.

<img width="472" alt="Screenshot 2024-05-27 at 09 43 35" src="https://github.com/sparrowwallet/sparrow/assets/862166/2b404f23-a1f4-4492-b741-30f5f569e30b">
