### ISSUE TITLE
Documentation incorrect on Remote Setup: 

### ISSUE THREAD

**Issue by DerekVonk** [sparrowwallet/sparrow#1427]
The documentation page on remote setup: sparrowwallet.com/docs/connect-node.html does not mention anything on the prerequisite of having to enable the 'RPC Server' in the preferences -> Options - Main tab. This feature is disabled by default.

I've wasted an hour trying to figure out why I could not connect to the wallet on another local machine and this relatively small addition seems like an easy fix.

I've also tried looking for a way to submit a pull-request to suggest somthing instead of creating an issue, but that is not possible according to the README in the docs directory.

**Comment by craigraw** [comment]
> does not mention anything on the prerequisite of having to enable the 'RPC Server' in the preferences -> Options - Main tab

This is the same as setting `server=1` in bitcoin.conf, which is the first instruction in the documentation you linked to. I don't believe the UI option you mention is available on older Bitcoin Core installations.
