### ISSUE TITLE
sparrow wallet not recognizing camera

### ISSUE THREAD

**Issue by kingmehodl** [sparrowwallet/sparrow#1429]
aiming to import my coldcard Q1 wallet and when i hit scan on the airgapped wallet, the camera popup window comes up but the camera doesnt get turned on. 
i've tested to see if my usb connected logitec works by going to [an](url) online webcam testing site and yes my logitec is able to show my camera feed. 
![Screenshot from 2024-05-30 11-48-57](https://github.com/sparrowwallet/sparrow/assets/155427844/3386edbf-ac30-4a32-941e-10626866659a)

however, with sparrow it just keeps on trying to find the feed and nothing happens. attaching screenshot...

**Comment by craigraw** [comment]
This might be resolved by changing/updating the camera driver. Unfortunately, I don't think there's much I can do here.

Have you tried a different resolution (HD Capture)?

**Comment by ghscuuo** [comment]
I had similar. A quick web search fixed it.  IIRC, I had to install cheese, and had to reboot, or something like that

**Comment by craigraw** [comment]
No response, closing this off.
