### ISSUE TITLE
Signing a message with a taproot address using Trezor does not work (wrong address derivation path)

### ISSUE THREAD

**Issue by psychoet** [sparrowwallet/sparrow#1430]
- Sparrow wallet ver.: v1.9.1
- Trezor one firmware version: v1.21.1

I am trying to sign a message with a taproot address created from Trezor One H/W wallet.
Since Trezor suite does not support signing a message with a Taproot address yet, I am trying to do it with Sparrow wallet.
Only available signing option was BIP322.

When I tried to sign the message, following warning message showed up on the device:
"Wrong address path for selected coin."

And the address shown after this message was not the same one (bc1p~), but a legacy address (starting with 1).

It would be appreciated if someone let me know this is a bug or I am doing in a wrong way.

**Comment by craigraw** [comment]
It's just not supported by the Trezor at this time, unfortunately.
