### ISSUE TITLE
Two wallets missing

### ISSUE THREAD

**Issue by DeathandBitcoin** [sparrowwallet/sparrow#1432]
Opened my Sparrow this morning (synced to my Bitcoin Core) and two of my wallets are gone.
I have three separate hardware wallets on my Sparrow desktop, and normally all three are there when I launch Sparrow, but it is only showing one.
I have the latest version of Sparrow downloaded, and my node shows the value of all three of my wallets.
Why did this happen?
Do I need to import these wallets again?

**Comment by DeathandBitcoin** [comment]
I followed the Telegram group link but it says the group is private. Can I get an invite somehow?

**Comment by craigraw** [comment]
Did you try File > Open Wallet from the application menu?

Closing as a user support request.
