### ISSUE TITLE
.desktop should set Single Window

### ISSUE THREAD

**Issue by BenWestgate** [sparrowwallet/sparrow#1436]
Hello Sparrow

I noticed the .desktop file included in the linux packages displays "New Window" in the context menu of right clicking on the Icon in Gnome but Sparrow is a single window application so this is wrong and does nothing useful if clicked.

Current Incorrect Behavior:
![image](https://github.com/sparrowwallet/sparrow/assets/73506583/03546733-2936-4c6f-acac-2c6dbb81408c)

![image](https://github.com/sparrowwallet/sparrow/assets/73506583/f7dec778-a72c-44bb-8005-d19e02ce155b)

This can be prevented by adding this to key to the .desktop file:
```
SingleMainWindow=true
```

Desired Behavior after adding the above:
![image](https://github.com/sparrowwallet/sparrow/assets/73506583/31f4813e-34da-463b-816f-5df8eb687da5)

![image](https://github.com/sparrowwallet/sparrow/assets/73506583/6660ff0b-fcea-4dea-b63c-edaf49d3d626)

**Comment by craigraw** [comment]
Thanks for suggesting this.

There is actually one case where this function does do something - when running Sparrow with another network configuration, it will open a window in mainnet. I assume this is true for any configuration that differs from the default. That said, I discovered this purely by accident, and I doubt it is obvious or particularly useful, so I am still leaning towards implementing your suggestion.

**Comment by BenWestgate** [comment]
> Thanks for suggesting this.
> 
> There is actually one case where this function does do something - when running Sparrow with another network configuration, it will open a window in mainnet. I assume this is true for any configuration that differs from the default. That said, I discovered this purely by accident, and I doubt it is obvious or particularly useful, so I am still leaning towards implementing your suggestion.

I believe you can then make that a drop down menu. So left click is mainnet and right click presents all network options, not already open. (Max single window per network)

But I have to imagine 90%+ of people testing non-mainnet are not launching with the app menu. Especially since it has not had those options. So this fancy solution may be a waste of time. What do you think is best?

**Comment by craigraw** [comment]
I think it's probably best to just remove it altogether as you originally proposed :)
