### ISSUE TITLE
Hidden RPC Limits?

### ISSUE THREAD

**Issue by jlopp** [sparrowwallet/sparrow#1440]
I'm testing setting up a watch-only wallet for a wallet that has hundreds of deposits to the same address.

When I point Sparrow to an electrum server, it correctly pulls in the entire transaction history.

However, when I point to a Bitcoin Core RPC endpoint, it's only showing the first 250 deposits.

The node in question is fully synced to chain tip. Is there a limit somewhere I'm not aware of?

**Comment by jlopp** [comment]
I think I figured it out: the problem appeared to be caused by the node being restarted in the middle of the initial wallet load and scan. Somehow this seemed to cause it to lose the pointer of the block height at which it was still scanning when the scan was interrupted, and future scans only look at the most recent few blocks.

**Comment by craigraw** [comment]
> Somehow this seemed to cause it to lose the pointer of the block height at which it was still scanning when the scan was interrupted, and future scans only look at the most recent few blocks.

I'm not certain, but I think this is expected behaviour for Bitcoin Core?

To get Sparrow to trigger a rescan, you can set the wallet birthday (Settings tab > Advanced) to any date prior to the current wallet birthday.

**Comment by craigraw** [comment]
Closing as Bitcoin Core wallet related.
