### ISSUE TITLE
UI shows 2 UTXOs selected, but only 1 is used

### ISSUE THREAD

**Issue by ottosch** [sparrowwallet/sparrow#1442]
Edit: I was told on Telegram this behaviour is expected because 1 coin was enough to pay.
If so, the UI is a little confusing to me.

Sparrow 1.9.0.
On signet, I selected 2 coins for a transaction:

![image](https://github.com/sparrowwallet/sparrow/assets/17476/86ed5265-6be2-4c1a-88f8-4d0e2079e39a)

Although UI showed 2 coins selected, only 1 was actually used in the transaction:

![image](https://github.com/sparrowwallet/sparrow/assets/17476/53ec6e10-7f32-48b3-8d5e-487f8fbaf52a)

I [sent the transaction](https://mempool.space/signet/tx/df0b03cc2dcae2f8b48fe09ccfb969b267cbc9d3b10335d3cdab76e2e40d4fd3) and only the 17,280 coin was actually used.

Unrelated (?): the fee estimate was always very high:

![image](https://github.com/sparrowwallet/sparrow/assets/17476/3e48b9c5-f5e0-40b8-8016-825dee8f0bb5)

**Comment by ottosch** [comment]
Today I only had 2 UTXOs. Selected both, tried to reproduce it, could not.
I split one UXTO in 2. I selected 2 of the 3 UTXOs and the issue happens again.

The 2nd input is added or removed depending on the Amount field. Coins selected: 13_033 sats and 159_000 sats.

Payment if it fits 1 coin:

![image](https://github.com/sparrowwallet/sparrow/assets/17476/fee86765-facb-42c8-89ce-e4e9d53eaf56)

Payment if it requires both:

![image](https://github.com/sparrowwallet/sparrow/assets/17476/64672632-49ed-46d9-a239-aaf6526068dd)

**Comment by craigraw** [comment]
Have you disabled "Allow Unconfirmed" in the Preferences?

<img width="265" alt="Screenshot 2024-06-14 at 07 37 10" src="https://github.com/sparrowwallet/sparrow/assets/862166/57372906-a546-42e9-87b6-c65f157ca9ee">

**Comment by ottosch** [comment]
No, it's enabled. And IIRC/IIUC one input was still unconfirmed in that last screenshot (says CPFP there).

**Comment by craigraw** [comment]
It may be related to the extremely high estimated fee rate. Switch the Fee Rates Source to Minimum (1 sat/vb) in the Preferences and try to reproduce again.

**Comment by ottosch** [comment]
Tested and it happens regardless of the fee rate. In this last test, I noticed it only happens if there's an unconfirmed UTXO.
I recorded the video below. I try to show:

- the pending coin is being removed if not needed;
- the 2 confirmed coins are always selected.

https://github.com/sparrowwallet/sparrow/assets/17476/24873941-bbc0-44e4-baae-2e6c7fa4758c

**Comment by craigraw** [comment]
Thanks for the video - I wasn't aware you were changing the output amount, and that (of several confirmed transactions) one of the UTXOs was unconfirmed.

Sparrow will attempt to avoid spending unconfirmed UTXOs if possible, since they have a chance of being replaced and invalidating the transaction. In general, transaction success outweighs other considerations. It's still possible to create the transaction you desire by adding a second output, entering a change address, and selecting the Max button.

**Comment by ottosch** [comment]
Thanks for clarifying!
