### ISSUE TITLE
Close button does not work on "Backup Multisig wallet" modal

### ISSUE THREAD

**Issue by torkelrogstad** [sparrowwallet/sparrow#1448]
This modal is not possible to close. I'm on Sparrow 1.9.1, macOS

<img width="810" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/16610775/4cb8bf38-ff8f-4c35-b70d-9abe5ff81cb9">

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in fb679c01.
