### ISSUE TITLE
I can't connect the sparrow wallet with raspiblitz

### ISSUE THREAD

**Issue by up1son** [sparrowwallet/sparrow#1449]
I can't connect the sparrow wallet with raspiblitz at bitcoin.conf I modified it this way following at sparrow the msg wallet suport must be enabled  in bitcoin core,However, I'm already running Bitcoin Core v27, and this message appears, what can I do?

**Comment by up1son** [comment]
![20240627_182450](https://github.com/sparrowwallet/sparrow/assets/171509381/9b8506fd-26be-4234-ab86-a34c69aeed67)
![20240627_182502](https://github.com/sparrowwallet/sparrow/assets/171509381/9824529d-b8ad-48ab-8b1f-1a04419420be)

**Comment by remcoros** [comment]
change `disablewallet=1` to `disablewallet=0` in bitcoind.conf

**Comment by craigraw** [comment]
This is the correct advice. Closing this off.
