### ISSUE TITLE
Can't close `Sing/Verify Message` window

### ISSUE THREAD

**Issue by kolya182** [sparrowwallet/sparrow#145]
Wanted to change address, opened one of the addresses, change my mind, want to close, but it done's work. Only one way to close it is click `Done`, but done servers more as completion of editing.

https://user-images.githubusercontent.com/3277207/123363820-2a4c8c80-d528-11eb-8d76-03e9f10207bf.mov

**Comment by craigraw** [comment]
Implemented in ea2f858. Will also now close when the Escape key is pressed.
