### ISSUE TITLE
Issues with jade on sparrow wallet

### ISSUE THREAD

**Issue by HenryHerbert** [sparrowwallet/sparrow#1450]
I am having issues signing transactions on sparrow wallet with my block stream Jade. When I click to sign the transaction on the Jade, it comes up with a error code on sparrow saying cannot read input transaction. Any ideas what I can do?

**Comment by craigraw** [comment]
Probably a duplicate of #1060 - upgrading the Jade driver solves this.

**Comment by craigraw** [comment]
Closing as duplicate.
