### ISSUE TITLE
Prevent potential address re-use in receive screen by warning users that he already copied an address

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#1455]
I had a need to generate multiple receive addresses in sparrow and paste them in other applications. So I pulled up the receive tab, copied an address and switched to the other application to paste the address.

Then I was distracted and when I came back I took the next address in the receive tab and pasted it into another application.

The problem was that it wasn't the NEXT address, it was still the old one resulting in a consolidation and therefore linking two separate outputs together. I simply haven't clicked on the "Get next address" button but took it for granted that this was a new address.

The problem was entirely my (the users) fault as I was in a hurry and distracted and didn't check the addresses. I was just wondering if it would be possible for sparrow to somehow warn the user that he already used the address (but hasn't yet received a tx to it).

E.g. in my case if I already clicked on the `Copy` symbol of the address and do it again open a pop-up that states that I already copied the same address previously.

**Comment by craigraw** [comment]
> I was just wondering if it would be possible for sparrow to somehow warn the user that he already used the address (but hasn't yet received a tx to it).

I don't think this is generally possible (moving on to the next address after copying it would likely be confusing) - but see #1453 for recent feature request that is worth consideration.

**Comment by RequestPrivacy** [comment]
You might be right, generally if could be tricky. A warning in the case you copy an address 2 times should be feasible though? Or do you prefer to have a "complete" solution, not just one that works with a subset of features?

> E.g. in my case if I already clicked on the Copy symbol of the address and do it again open a pop-up that states that I already copied the same address previously.

**Comment by craigraw** [comment]
> A warning in the case you copy an address 2 times should be feasible though?

I don't love this tbh - I can think of plenty of reasonable cases where copying an address twice would be normal behaviour, for example to enter into some other software (eg for accounting).

I think #1453 is a better alternative, so I'm closing this off in favour of that one.
