### ISSUE TITLE
[Feature Request] Open .onion links in Tor Browser rather than default Browser

### ISSUE THREAD

**Issue by DaniDipp** [sparrowwallet/sparrow#1459]
When I specify a custom block explorer on a .onion domain in the settings, it would be great if Sparrow could open the link in the transaction viewer with the Tor Browser rather than my default browser.

**Comment by craigraw** [comment]
I agree with the idea, but this needs to be supported by Tor Browser through use of a custom URI handler. See https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41017. If that gets implemented, I'd be happy to make sure it works in Sparrow. Closing for now as unimplementable.
