### ISSUE TITLE
`Mempool Size` chart shows `0 MvB`

### ISSUE THREAD

**Issue by kolya182** [sparrowwallet/sparrow#146]
<img width="483" alt="Screen Shot 2021-06-24 at 8 31 05 PM" src="https://user-images.githubusercontent.com/3277207/123365482-338b2880-d52b-11eb-8aea-70ea7f36acc6.png">
Current setting
<img width="388" alt="Screen Shot 2021-06-24 at 9 09 06 PM" src="https://user-images.githubusercontent.com/3277207/123368312-6b489f00-d530-11eb-8f13-ff5f495f119c.png">

Mempool.space chart as an example
<img width="531" alt="Screen Shot 2021-06-24 at 8 34 42 PM" src="https://user-images.githubusercontent.com/3277207/123365694-9ed4fa80-d52b-11eb-9444-587efb364f8b.png">

**Comment by craigraw** [comment]
Fixed in b6a3538. The mempool size chart will now switch to kvB units when the maximum Y value of the chart is less than 1 MvB.

<img width="358" alt="Screenshot 2021-06-28 at 14 08 18" src="https://user-images.githubusercontent.com/862166/123634895-49466980-d81b-11eb-9668-4bbce9df3d52.png">
