### ISSUE TITLE
Ledger Stax and Flex support

### ISSUE THREAD

**Issue by null-ish** [sparrowwallet/sparrow#1460]
The Ledger Stax has arrived and I think there is some things that need to be added to drongo / sparrow / HWI libs:

Device IDs: `(0x2c97, 0x0006)`
Ledger Model ID: `0x60: "Ledger Stax"`

Found [here](https://github.com/spesmilo/electrum/blob/master/electrum/plugins/ledger/ledger.py).

**Comment by craigraw** [comment]
Noted - there's still not a lot of test devices available, but I will try to get hold of one.

**Comment by regina-hash** [comment]
You can join their telegram group for support https://t.me/sparrowwalletcommunity They helped me when i was experiencing an error with my wallet

**Comment by hydradave** [comment]
Please take care this is not the telegram community linked from the official sparrow website [https://sparrowwallet.com/](url)

**Comment by vinxp97** [comment]
I have a Stax and it's great! Wish it was detectable by Sparrow though, doesn't seem to work on Mac, hence the issue. LMK if there's anything I can do to help on my end i.e. test an update.

**Comment by craigraw** [comment]
Availability for both the Stax and Flex is still very limited, but I'm hoping to get a test device in September. There is an [open PR on HWI here](https://github.com/bitcoin-core/HWI/pull/746) to add support, which would in turn allow Sparrow to support for both devices.

**Comment by man55** [comment]
> Availability for both the Stax and Flex is still very limited, but I'm hoping to get a test device in September. There is an [open PR on HWI here](https://github.com/bitcoin-core/HWI/pull/746) to add support, which would in turn allow Sparrow to support for both devices.

We are looking forward to it!

**Comment by craigraw** [comment]
@null-ish @vinxp97 @man55 Please let me know if you can test, and if so what Sparrow download (platform) you use.

**Comment by craigraw** [comment]
I have uploaded pre-release binaries to https://github.com/craigraw/beta/releases/tag/1.9.2-hwi-3.1.0. 

Please test if you can.

**Comment by joaocosta-anchor** [comment]
I just  tested it. I was able to add the flex as part of a multisig wallet and I was also able to sign a transaction with it. Works great!
<img width="1072" alt="Screenshot 2024-09-18 at 13 40 14" src="https://github.com/user-attachments/assets/696b2df2-bcdf-4c27-83d0-9865baa0a39e">

Thank you @craigraw

**Comment by Joaofcm** [comment]
I successfully tested Flex as a wallet, both for single and multisig configurations. I was able to add Flex as a wallet and successfully sign a transaction

<img width="1072" alt="Screenshot 2024-09-18 at 13 40 14" src="https://github.com/user-attachments/assets/88ed428b-9891-40ee-9bda-44f38702443b">

Thank you @craigraw !

**Comment by vinxp97** [comment]
> I have uploaded pre-release binaries to https://github.com/craigraw/beta/releases/tag/1.9.2-hwi-3.1.0.
> 
> Please test if you can.

I used Stax on M2 Mac/AARCH64. It worked without issue when attempting to import a passphrase + non-passphrase wallet -- haven't tested a transaction yet.

**Comment by craigraw** [comment]
Great, thanks @vinxp97. 

That's a successful test of both Flex and Stax, so I'm closing this off.
