### ISSUE TITLE
Invalid Key Derivation Path when importing on my 

### ISSUE THREAD

**Issue by memcmp** [sparrowwallet/sparrow#1462]
I'm trying to import a multisig wallet from my old computer to my new computer ( Intel Mac 12.7.5 to m1 Mac 14.5), these are the methods I tried, all fail for the same reason:

- BSMS via file
- BSMS via QR Code
- Sparrow
- Output Descriptor ( File & QR code)
- Copied the .db files directly from ~/.sparrow/home/wallets/ to my target computer ( When I try to open I get an error message "Wallet file is not valid" )

The problem I'm having is that when I try to import it the "Derivation" path field of all Keystores is red and I cannot save the wallet. The derivation path of all Keystores `m/84'/0'/0'`. Sparrow seems to have an issue with the lat `'`. When I delete it, I could import the wallet, but the path is obviously wrong and I cannot properly sign transactions.

The `'` in the middle of the key path are fine. I verified that it is the same character.

Some colleagues of mine already imported that wallet successfully ( also to OSX 14.5, also m1 ).

The same wallet works on my old Mac, with all versions of Sparrow ( tried from 1.8.1. to 1.9.1). I also tried importing and exporting from different versions and different builds:

- Export from 1.8.1 - 1.9.1
- Import to 1.8.1. - 1.9.1 ( intel build with rosetta and arm build ). I always encounter the same problem.

Any ideas?

https://github.com/user-attachments/assets/25195602-f981-451e-8ece-4acf4d1ac648

**Comment by craigraw** [comment]
You are trying to use the derivation path for a singlesig Native Segwit wallet on a multisig wallet. If you really want to do this, you can disable derivation path validation in the General Preferences. But be aware this practice may lead to key reuse and funds being linked onchain where they would not otherwise be so.

**Comment by memcmp** [comment]
Thank you so much for this quick reply! That totally solved my issue. ( The Wallet was originally created with nunchuck )
