### ISSUE TITLE
Signing Error Ledger Nano S [old firmware]

### ISSUE THREAD

**Issue by SlyStarsky** [sparrowwallet/sparrow#1464]
I'm working with a Ledger Nano S with firmware version 1.3.1 and a BTC wallet version 1.1.5.

I'm trying to access and send my BTC. (I'm not sure where my 24 words are. A lot has happened in my life over the past few years, and I was HODLing, which, combined with everything else, means I'm not sure where or if I still have the phrase.)

I can finally see my btc funds!!

- After having tried many versions of Electrum
- Having worked through numerous errors and contacted Ledger's helpdesk, and worked through some more errors
- I can now finally see my funds via an older version of Sparrow wallet 1.2.0 (**Thank you, Sparrow**!). I was SO relieved.

I was ready to send my BTC, but then, at the very last step, a new error appeared: "bad argument."

It happens when I need to sign the transaction and have logged into my BTC wallet on my Ledger. Sometimes it gives me the option to accept the first transaction on my Ledger, but as soon as I "accept" and right-click the checkmark, it gives the error again.

I can't figure out how to fix this error (without updating my Ledger).

What could I still try? (I've tried: 2 computers, different ports, different cables, different Sparrow versions 1.2.0 & 1.4.0)

![Scherm­afbeelding 2024-07-04 om 13 13 04](https://github.com/user-attachments/assets/b19dc54b-9976-49d6-b1cb-3349a9b6cad7)

**Comment by jpph** [comment]
did you tried old version of electrum ?

**Comment by SlyStarsky** [comment]
Hey! Yes many! With electrum I can't even see my btc. 

6months ago I could still do everything with ledger live app on chrome.

**Comment by jpph** [comment]
If I were you I would use a fresh install of windows and try several electrum version dated around same date as your ledger version. If good amount I would seek help from professional (like cryptoguide he is doing good vid on yt)

**Comment by SlyStarsky** [comment]
I have an OS. Do you mean a reset Windows computer? (I could go to my dads who has one!)

**Comment by jpph** [comment]
Yes, I figured that USB driver were better managed by hardware wallet on windows.

**Comment by SlyStarsky** [comment]
Thank you, I'll give that a try

**Comment by craigraw** [comment]
Unfortunately other than trying different versions of Sparrow I don't have much to suggest - Ledger's API has been a mixed bag of incompatibilities until around a year ago. 

Closing as a user support request.
