### ISSUE TITLE
Is the Sparrow for Android app a fake?  Looks sus.  sparrowiki.com

### ISSUE THREAD

**Issue by dlitz** [sparrowwallet/sparrow#1466]
This looks suspicious:  https://sparrowiki.com/

It's the second result when searching for "Sparrow Android wallet", themed the same as the official site, but links directly to an APK rather than the Play Store, and points to the official GitHub where there is no actual Android source code (as far as I can tell). I notice that there are no links back to this site from the official site.🤔

Is there an official Sparrow app for Android, or are they all fakes at this point?

![Screenshot_20240721_161958](https://github.com/user-attachments/assets/4b16d007-cb02-4ec7-8661-ded620829982)

**Comment by craigraw** [comment]
It's a fake and a scam. There is no Sparrow Wallet Android app.

I have reported this site to the domain registrar.
