### ISSUE TITLE
Broadcast transaction from unknown wallet gives timeout error

### ISSUE THREAD

**Issue by tadeubas** [sparrowwallet/sparrow#1468]
I did 3 tests to be sure:
- The first was a wach-only wallet loaded on Sparrow that broadcast a transaction signed by an HW (Krux v24.07) without errors.
- The second and third were a complete signed PSBT from a wallet unknown to Sparrow (not loaded) that were broadcasted with the error shown in the image below. I tried to broadcast again with the same error, I looked for the transaction on my node and it was already found as transmitted!

Side note: For the second and third tests I was unable to finalize the unsigned transaction for sign because the wallet was not loaded on Sparrow, but HW (Krux v24.07) was able to sign the transaction without any issues.

![image](https://github.com/user-attachments/assets/206ac77b-6d6c-46e3-aeb1-c14782c0125f)

**Comment by craigraw** [comment]
This appears to be a problem with the server you are connected to, which is not notifying Sparrow that the transaction has been received in the node you are connected to.

Which wallet is loaded in Sparrow is unrelated.

**Comment by tadeubas** [comment]
Wow I see, thx a lot ❤️ :
File > Show PSBT as QR...
