### ISSUE TITLE
FAILURE PSBT does not contain any key path information

### ISSUE THREAD

**Issue by LeoGroff8** [sparrowwallet/sparrow#1470]
<img width="487" alt="image" src="https://github.com/user-attachments/assets/b5292344-7275-4129-abff-364deebb3d28">

I created this wallet using my MK4 and yesterday when I tried to do some UTXO consolidation it return me this error when doing sighash all::
FAILURE PSBT does not contain any key path information

When I select sighash default I get the following error: Can only do Sighash ALL.

I tried creating different transactions but I get the same errors with any transaction I create. I also tried recovering my keys using bluewallet and it did not find any transaction. I do have multiple UTXOs in it.

I have already checked the master finger print from the coldcard mk4 and sparrow and they match.

How can I trouble shoot this to be able to move/recover my funds?

Thanks!

**Comment by craigraw** [comment]
You need to run the Edge firmware on the Coldcard to sign Taproot transactions.

**Comment by LeoGroff8** [comment]
Hi Craig, 
I am still waiting on my SD/USB-C adaptor but that is probably it. I have an older firmware on my mk4 and this is the only wallet with Taproot allow. I appreciate all the work you've done and the quick response here. 
Cheers

**Comment by algotechio** [comment]
I have the same problem with MK3.  I am running the latest version of firmware 4.1.9.

I created the taproot wallet in Sparrow (also latest version 1.9.1). 

I tried to sign the transaction first with USB and then Saving the Transaction to MicroSD.  In both cases got the same error as listed above.

**Comment by craigraw** [comment]
@algotechio The Edge firmware is 6.x. 4.1.9 does not support Taproot.
