### ISSUE TITLE
Server returned HTTP response code: 403 for URL: http://192.168.1.174:8332/wallet/cormorant while connecting to bitcoind full node with compiled-in wallet support

### ISSUE THREAD

**Issue by kosuodhmwa** [sparrowwallet/sparrow#1471]
Could not connect:

Server returned HTTP response code: 403 for URL: http://192.168.1.174:8332/wallet/cormorant

Why?

**Comment by kosuodhmwa** [comment]
i also added disablewallet=0, does not solve problem

 
maybe problem is that it runs via tor? but miro bitcoin manager web gui also runs without tor... (???)

bitcoin stack i use is Satoshi:27.99.0

**Comment by craigraw** [comment]
Status code 403 indicates an authentication problem.

Please do not ask support questions here. Github is for bug reports and feature requests.

**Comment by kosuodhmwa** [comment]
ok https://github.com/bitcoin/bitcoin/issues/30557

**Comment by kosuodhmwa** [comment]
ok thx
