### ISSUE TITLE
Transaction lost (can't find address anymore in sparrow)

### ISSUE THREAD

**Issue by redOz92** [sparrowwallet/sparrow#1473]
Hello,

I've got a strange issue.
I transferred 1.5M sats from Zeus Wallet to Sparrow Wallet with the QR code on Sparrow but I can't find the address anymore in Sparrow and also I didn't receive anything.

https://mempool.space/tx/747063b45480f62f7a626cf19568077504d7df65f39a4d9530eaca34f46fe1f2?mode=details
https://mempool.space/address/bc1q0rx2d4rd4u3u4nwjdvjpduummu9qk2y4z3ta5c

This is my transaction but can't find it anymore.
I'm pretty sure I saw the transaction pop up on sparrow when it was send..

**Comment by craigraw** [comment]
If you are using a passphase, see https://sparrowwallet.com/docs/faq.html#all-my-addresses-have-changed

**Comment by redOz92** [comment]
Already tried those things, opened the sparrow software wallet in Linux & Windows. Tried to make mistakes with my passphrase but no results at all :-(

**Comment by craigraw** [comment]
Sparrow doesn't store the passphrase by design, so there's not much that can be done from this side. Try writing the passphrase out quickly many times in a text editor, and try all the variations.

**Comment by redOz92** [comment]
Could I change some settings to get other addresses or change the derivation path?

**Comment by craigraw** [comment]
Yes, you can. But unless you did that previously, it's not going to help. I would suggest creating a new wallet rather than editing the existing one if you want to do this.

**Comment by redOz92** [comment]
I scanned the QR in Sparrow Wallet (linux) via my Zeus Wallet (mobile) and I saw the transaction in a popup (or I dreamed) in Sparrow as always but afterwards I could not find that address and the transaction anymore.. I can't understand where the transaction went. The 3885 sats have arrived but the 1495691 sats cannot be found.
![photo_2024-08-08_09-14-39](https://github.com/user-attachments/assets/427383e8-4b7a-428f-8236-0f578cb97125)

**Comment by craigraw** [comment]
I don't believe it's possible for Zeus to create a transaction that sends to more than one payment address at a time - so it appears by deduction that the larger amount is to a change address owned by your Zeus wallet.

**Comment by redOz92** [comment]
![photo_2024-08-08_14-06-03](https://github.com/user-attachments/assets/99eff554-fece-4bde-a8e3-41b55a45c9ed)

This is the transaction. The bigger amount is on Destination Addresses #2 but it's not in any of my wallets..

**Comment by craigraw** [comment]
My advice then is to keep trying different passphrases.
