### ISSUE TITLE
Connected to remote server, but on start screen it wants to get local filepaths

### ISSUE THREAD

**Issue by kosuodhmwa** [sparrowwallet/sparrow#1474]
why? 
![image](https://github.com/user-attachments/assets/ff1049de-33eb-4af6-a4ee-759899264d66)

**Comment by kosuodhmwa** [comment]
it seems it has completely phucked up my wallet 
![image](https://github.com/user-attachments/assets/9d2b6251-9e41-4160-bc12-a6710bf42e65)

**Comment by kosuodhmwa** [comment]
how to create a new wallet on remote bitcoind server now? i can only see local options with local files

**Comment by kosuodhmwa** [comment]
and how to restore old wallet? there was a few bucks on

**Comment by kosuodhmwa** [comment]
<how to create a new wallet on remote bitcoind server now? i can only see local options with local files>

<and how to restore old wallet? there was a few bucks on>

Something has created a wallet called "cormorant" (nobody knows why) and then i had 2 wallets which had a problem with "miro bitcoin manager". now i've deleted "cormorant" then i saw my old one wallet again

**Comment by craigraw** [comment]
As already requested in https://github.com/sparrowwallet/sparrow/issues/1471#issuecomment-2260215852, please do not ask user support questions here. These questions can be asked on the Telegram group at https://t.me/SparrowWallet.

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
https://t.me/SparrowWallet 

Ufffff there are tons of scammers
