### ISSUE TITLE
Sparrow frozen when trying to sign 3 of 5

### ISSUE THREAD

**Issue by kami104** [sparrowwallet/sparrow#1476]
I'm using Debian bookworm and Sparrow 1.9.1.

I'm trying to sign a transaction of a multisig wallet 3 of 5 in native sewgit, one key is hot, other keys are cold. Cold keys are signed using a seedsigner 0.7.0.

Before finishing the scan of the first cold signature the software freezes and the operative system freezes too. Sometimes I get this message but everything gets frozen later.
![Untitled1](https://github.com/user-attachments/assets/1fe8e2d4-6874-49a5-b015-eea45fa6d53f)

This problem only comes out when signing with seedsigner but not with the hot seed. My seedsigner works fine with Sparrow if I'm signing a singlesig wallet.

**Comment by craigraw** [comment]
This sounds like a camera driver issue. Take a look at #1429, and try changing the camera resolution as well.

**Comment by kami104** [comment]
Yes, I remembered some months ago I was able to use the camera without any problem.

I was working on a virtual machine (and I still doing) so I reinstalled the OS and the problem has gone.

Thanks for your support.
