### ISSUE TITLE
Transaction labels

### ISSUE THREAD

**Issue by ssmithx** [sparrowwallet/sparrow#1479]
This may be stupid (but so am I)  It took me 30 minutes and 2 asks to friends to find how to label transactions.
I don't know what this means, but one friend mentioned:
"Ghost text field description would be nice. Some smarty pant GitHub user should suggest 😉"

**Comment by ssmithx** [comment]
when a field wants you to enter data there is "default" text in there...not text that you have to erase per se but in the "background" of the field input box until you actually start typing and it's kinda greyed out/faint.

i.e. Label Description here...

**Comment by craigraw** [comment]
Thanks for the suggestion. There is a big downside though - even if it's greyed out, there's a huge amount of additional visual complexity. Imagine if Excel had greyed out text in every cell saying "Enter number, text or formula here"?

I would certainly reconsider if this was a frequent issue, but to my memory it hasn't come up before.
