### ISSUE TITLE
Jade won't sign PSBTs imported from text

### ISSUE THREAD

**Issue by hazrulnizam** [sparrowwallet/sparrow#1480]
### Background

I was exploring PSBTs, and was trying to craft my own custom PSBTs and sign them using Sparrow. The main idea is to combine UTXOs from different wallets into one transaction, like a coinjoin (sort of).

I managed to learn how to craft the PSBTs using Bitcoin Core, then transfer the PSBT to Sparrow using text import. I am able to sign the PSBT for the UTXOs belonging to Sparrow software wallets with no problems, but for UTXOs belonging to a Jade I was having trouble signing them.

In order troubleshoot the issue, I tried simplifying the PSBT by removing inputs one by one until the only remaining input is the UTXO  from the Jade wallet. Even this most simple transaction with one input and one output, when crafted outside of Sparrow and imported via the Open Transaction > From Text method, was unable to be signed by Jade and failed with `Failed to extract input_tx from parameters` error.

### Your environment

* Sparrow 1.9.1 Windows Installer Edition
* Bitcoin Core 26.0.0 for crafting PSBT
* Blockstream Jade

### Steps to reproduce

1. Create PSBT with one input and one output using Bitcoin Core `createpsbt`
2. Update PSBT using Bitcoin Core `utxoupdatepsbt`
3. Copy and Paste Base64 PSBT string to Sparrow Wallet using Open Transaction > From Text function.
4. Examine imported transaction and note that Sparrow correctly identifies input is from Jade wallet.
5. Click Sign button with the USB icon in the transaction tab. 
6. Click Sign button next to the Jade in the hardware list in the popup window.
7. Verify the transaction on the Jade and confirm it with the hardware button on the Jade.
8. Sparrow returns Signing Error - Failed to extract input_tx from parameters.

### Expected behaviour

Signing should be successful.

### Actual behaviour

Sparrow returns Signing Error - Failed to extract input_tx from parameters.

### Additional Info

Re-creating the transaction from within Sparrow itself posed no problems. Say using the following method:

1. Select the input UTXO in Sparrow and click Send Selected.
2. Key in Pay To: address and Label, set the fee and click Create Transaction >>
3. Click Finalize Transaction for Signing.
4. Click Sign button with the USB icon in the transaction tab. 
5. Click Sign button next to the Jade in the hardware list in the popup window.
6. Verify the transaction on the Jade and confirm it with the hardware button on the Jade.

The transaction is exactly the same using the two methods (the Transaction Hex at the bottom of the screen are exactly the same using the two methods), but the first method won't sign.

Oh, and also, using the import PSBT method works fine when signing inputs using native Sparrow soft wallets. Only when trying to sign using Jade does this issue happen.

**Comment by craigraw** [comment]
I appreciate all the effort in this thorough report :) But it's actually not in the right place. 

As you can see from [the Jade firmware source](https://github.com/Blockstream/Jade/blob/0d6ce77bf23ef2b5dc43cdae3967b4207e8cad52/main/process/sign_tx.c#L586), the error is not coming from Sparrow but from the Jade itself. It appears that you haven't included the `NON_WITNESS_UTXO` field on your PSBT inputs, but I may be wrong. Whatever the cause, Sparrow is just the conduit here, and your issue lies with the PSBT parsing on the Jade itself.

**Comment by hazrulnizam** [comment]
Thank you for taking the time to answer. I am still learning and I don't understand fully how to craft a proper PSBT.

Your answer pointed me to the fact that the PSBT I fed into Sparrow is not complete and is missing the `NON_WITNESS_UTXO` field. It turns out that Bitcoin Core's `utxoupdatepsbt` function only adds `WITNESS_UTXO` fields, and to add `NON_WITNESS_UTXO` fields, I needed to run `walletprocesspsbt` as well.

However, this only works for UTXOs belongs to the wallet installed/mounted on the Bitcoin Core instance.

You mentioned that Sparrow is just a conduit for the PSBT. Is there a way to make Sparrow perform the PSBT Updater role, and add all the necessary info to the PSBT?

Or is there another way to do it with Bitcoin Core?

Thanks again!

**Comment by craigraw** [comment]
If you are constructing a segwit transaction, you actually shouldn't need `NON_WITNESS_UTXO`. But some hardware wallets require it to prevent a low likelihood attack: https://blog.trezor.io/details-of-firmware-updates-for-trezor-one-version-1-9-1-and-trezor-model-t-version-2-3-1-1eba8f60f2dd. Unfortunately, this approach makes PSBTs larger (and in the case of multisig, potentially much larger) which can cause hardware wallets that use QR codes to be effectively unusable. Sparrow does add the `NON_WITNESS_UTXO` or the`WITNESS_UTXO` when loading a PSBT if they are not present and available in a loaded wallet - but to avoid very large PSBTs it does not add both.

You might want to explore creating a non-segwit transaction to test if this is happening to you with the Jade.
