### ISSUE TITLE
Build failed: Could not resolve com.nativelibs4java:bridj:0.7-20140918-3.

### ISSUE THREAD

**Issue by Cheapshot003** [sparrowwallet/sparrow#1481]
Hi! When I try to build the sparrow binary with gradlew I get the following error:
`tarting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
Project : => 'com.sparrowwallet.sparrow' Java module

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.nativelibs4java:bridj:0.7-20140918-3.
     Required by:
         project :
      > Could not resolve com.nativelibs4java:bridj:0.7-20140918-3.
         > Could not get resource 'https://maven.ecs.soton.ac.uk/content/groups/maven.openimaj.org/com/nativelibs4java/bridj/0.7-20140918-3/bridj-0.7-20140918-3.pom'.
            > Could not GET 'https://maven.ecs.soton.ac.uk/content/groups/maven.openimaj.org/com/nativelibs4java/bridj/0.7-20140918-3/bridj-0.7-20140918-3.pom'. Received status code 503 from server: Service Unavailable

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 28s
9 actionable tasks: 9 executed
`

Does anybody else experience this issue? Have this on 2 different machines. Both Java-18 (Temurin).
I mean, a 503 should affect everyone, right?

**Comment by craigraw** [comment]
Should be resolved now. Let me know if you still have issues.

**Comment by Cheapshot003** [comment]
Unfortunately still the same error
![picture](https://github.com/user-attachments/assets/f6df0166-a50e-45f2-b254-d2fd14345a77)

When I visit the url I also get the 503
![picture2](https://github.com/user-attachments/assets/1a48e4ce-ff8e-4396-97b0-70b6d1dc8ebe)

**Comment by craigraw** [comment]
I have just done a successful build on a fresh system, so I think there is something cached on your side that is causing this. 

Try
```
./gradlew --refresh-dependencies jpackage
```

If that doesn't work, try deleting your Gradle cache entirely with
```
rm -rf $HOME/.gradle/caches/
```

I've uploaded the problematic jar to another repo, so it should not matter that the soton.ac.uk one is down.
