### ISSUE TITLE
Python path problem

### ISSUE THREAD

**Issue by Hueristic** [sparrowwallet/sparrow#1482]
Winx64
from log

> 2023-03-14 14:48:34,144 ERROR [Thread-6] c.s.s.i.Hwi [null:-1] Error executing hwi-2.2.1
java.io.IOException: Error loading Python DLL 'e:\Temp\_MEI71962\python39.dll'

Cannot find where to change this path, the environment is correct.

**Comment by craigraw** [comment]
Try upgrading. The latest version of Sparrow ships with HWI 3.0.0, it may resolve your issue.

**Comment by Hueristic** [comment]
heavily modified win7x64

    On Tuesday, August 20, 2024 at 10:52:48 AM EDT, craigraw ***@***.***> wrote:  
 
 


What OS are you using?

**Comment by craigraw** [comment]
Win7 is not a supported platform.

But here's something you can do. HWI is an external program that Sparrow calls to talk to USB hwws. You can change the path to it in Sparrow's config file. So if you can get an HWI copy to run on your system (see https://github.com/bitcoin-core/HWI/releases) you can close Sparrow and change the value of the `hwi` entry in `%APPDATA%\Sparrow\config` to point to it. You can even run from source by pointing to `hwi.py`. Restart Sparrow and it will use your HWI instead.
