### ISSUE TITLE
Monospaced fonts for Addresses (UTXO Tab)

### ISSUE THREAD

**Issue by pvig0q1s** [sparrowwallet/sparrow#1483]
'UTXOs' tab: Addresses should be presented in monospaced font (like in other places of Sparrow Wallet). With the currently used font family some addresses appear to have a different lenght (characters) than others.

**Comment by craigraw** [comment]
Implemented in cbee3415. I have previously been blocked by the need to use hyperlinks in this column (which need to appear in the system font) but found a way to solve this.
