### ISSUE TITLE
Change in key path notation (Coldcard) introduces confusion

### ISSUE THREAD

**Issue by pvig0q1s** [sparrowwallet/sparrow#1485]
Coldcard introduced a change in key path notation somewhere before Firmware 5.3.1. In changelog 5.3.1. they write:

_"Important Bugfix: Already imported multisig wallets would show errors when signing. This was caused by our internal change in key path notation from 84' (prime) to 84h (hardened)."_ (https://github.com/Coldcard/firmware/blob/master/releases/History-Mk4.md#531---2024-05-09)

In their changelogs I wasn't able to find clarification for the switch in general. I'm technicaly not educated enough so this is more of a wild guess for their reasoning: Technically, in my head, there is no difference between using h or ' (both h and ' mean hardened / "nothing" means unhardened). Since it is difficult for the eyes to distinguish between ' and *nothing*, change by Coldcard improves readability (of the code and for users using the device). I recognize, in CC Firmware there is a function (cleanup_deriv_path in utils.py) which shows how they do the conversion; e.g. used when importing multisig configuration. Besides, h notation is used by bitcoin (descriptors).

Now, in Sparrow this introduces an issue:

Files imported to Sparrow propagate to the Keystore Tab (in this case, using "h" with newer CC Firmware). Once you have a standard multisig wallet in Sparrow; e.g. 1x Coldcard (m/48h/0h/0h/2h) and 1x other keystores (m/48'/0'/0'/2') the Receive tab shows 'multi/0/0' for Derivation. This is confusing as it would mean the same as using prime notation (') for both keystores but diverging paths; e.g. 1x Keystore (m/48'/0'/0'/2') and 1x Keystore m/48'/0'/666'/2').

Even though I (guess) to understand why Coldcard made the change (and welcome it) it is hard to imagine that competitors will do the same thing. I think Sparrow Wallet should address this from an UI perspective. I imagine there is more to it than just changing all ' to h (compatibility with all the different manufacturers) but to stay consistent from UI perspective, it would be nice if on Receive Tab (...other places?) a unified way of showing information is used.

**Comment by craigraw** [comment]
> Technically, in my head, there is no difference between using h or ' (both h and ' mean hardened / "nothing" means unhardened).

This is correct.

> Since it is difficult for the eyes to distinguish between ' and nothing, change by Coldcard improves readability (of the code and for users using the device).

I disagree. IMO, m/48'/0'/0'/2' is much easier to read than m/48h/0h/0h/2h. But I don't think there will ever be universal agreement, so Sparrow tries not to be too opinionated here. IIRC the major reason for Bitcoin Core to switch to "h" was avoiding using an apostrophe in arguments on the command line.

> Once you have a standard multisig wallet in Sparrow; e.g. 1x Coldcard (m/48h/0h/0h/2h) and 1x other keystores (m/48'/0'/0'/2') the Receive tab shows 'multi/0/0' for Derivation. This is confusing as it would mean the same as using prime notation (') for both keystores but diverging paths; e.g. 1x Keystore (m/48'/0'/0'/2') and 1x Keystore m/48'/0'/666'/2').

Fixed in 95b1aa8e. Sparrow will also now rewrite derivation paths for file and card imports so they look the same.
