### ISSUE TITLE
Sparrow wallet on Linux w. DWM not showing numeric text

### ISSUE THREAD

**Issue by bvotteler** [sparrowwallet/sparrow#1486]
I cannot get Sparrow wallet to show numeric text. 
Alphabetic text shows, but has weird spacing.

I tried a few Java opts to address the usual culprits, but no luck so far.
```
$ Sparrow --version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djdk.gtk.version=3
Sparrow Wallet 1.9.1
```
No errors in `.sparrow/sparrow.log` look relevant (only a few connection errors).

I also tried using `wmname LG3D` as I'm running DWM.

Any tips for what I should do to fix this?

**Comment by bvotteler** [comment]
Screenshot for reference: 
![sparrow_scrot](https://github.com/user-attachments/assets/7aa92290-b531-43f8-b590-40e6ed574688)

**Comment by craigraw** [comment]
I suggest trying to update/change your system font, which is getting picked up and used by Sparrow.

**Comment by bvotteler** [comment]
> I suggest trying to update/change your system font, which is getting picked up and used by Sparrow.

Thanks for the hint! Got it sorted.

In case it helps someone else in future:
My `~/.config/fontconfig/fonts.conf` looked a bit bloated with some font names I didn't recognize.

Replaced it with a more sparse one which I copied from [this reddit comment](https://www.reddit.com/r/archlinux/comments/9rhq1g/comment/e8hhcey/). (Already had `font-noto-*` installed.)

Restarted Sparrow and all was well.
