### ISSUE TITLE
[Feature] Spending UTXOs from multiple wallets in a single transaction

### ISSUE THREAD

**Issue by pycanis** [sparrowwallet/sparrow#1487]
Is it reasonable to implement such feature? How difficult would it be?

**Comment by craigraw** [comment]
The point of having multiple wallets/accounts is segregation - to avoid combining UTXOs in a single transaction that links them onchain. Adding this feature could cause more harm than good. 

From an implementation perspective, it's quite difficult - there would need to be some kind of a "master wallet" which acted like all the open wallets simultaneously.

**Comment by pycanis** [comment]
Although I'd still benefit from this feature, I understand there's only a niche use case. Thanks for the reply.
