### ISSUE TITLE
How to disable change address in Sparrow

### ISSUE THREAD

**Issue by TangMonk** [sparrowwallet/sparrow#1488]
I could use `use_change: false` in Electrum Wallet, But how in Sparrow?

**Comment by craigraw** [comment]
It's not possible. I'm not adding this "feature" either, since it makes transactions less private for both sender and receiver, and Bitcoin overall less private as well.

**Comment by TangMonk** [comment]
> It's not possible. I'm not adding this "feature" either, since it makes transactions less private for both sender and receiver, and Bitcoin overall less private as well.

However, I’d like to do something similar to an exchange or company that doesn’t prioritize privacy. 

Sparrow is a very nice wallet, but it should offer some options for this, just like the `coin control` feature in the Bitcoin Core GUI or `use_change: false` Electrum.

**Comment by TangMonk** [comment]
> > However, I’d like to do something similar to an exchange or company that doesn’t prioritize privacy.
> 
> New Bitcoin addresses are effectively free. What is the cost of additional privacy?

It’s costly to manage. Why do Binance, Coinbase, or other companies keep using fixed addresses?

**Comment by craigraw** [comment]
> Isn't costly?

Not really. I test Sparrow on active wallets with millions of addresses, that have 10s of new transactions in every block. It handles this well. Modern Electrum servers like Fulcrum scale very well, particularly if they are running on decent hardware. You can even configure Sparrow to only watch the last x addresses in the Advanced Settings. 

Giving up privacy is a very serious tradeoff, which IMO should only be made if there are no other alternatives. I'm not convinced that is the case.

**Comment by TangMonk** [comment]
> Not really. I test Sparrow on active wallets with millions of addresses, that have 10s of new transactions in every block.

How do you set the `gap limit`?
