### ISSUE TITLE
UTXO Consolidation - Sparrow not able to sign with Ledger Nano S

### ISSUE THREAD

**Issue by JW-CH** [sparrowwallet/sparrow#1489]
Device: Ledger Nano S
Bitcoin App Version: 2.2.3
Sparrow Wallet Version: 1.9.1
PC-OS: Windows 11

I am trying to consolidate my UTXOs. When trying to sign the Transaction, the device-window appears, and I am able to see my Ledger Nano S, it says that my device is unlocked. When clicking the sign button, nothing happens on the ledger and sparrow just says 'Signing...'. Am I doing anything wrong?

Edit: After a few minutes, I get following message: `'utf-8' codec can't decode byte 0x78 in position 0: invalid start byte`

**Comment by craigraw** [comment]
It's probable that your Nano S (which is a very limited device) is running out of memory. Try signing a transaction with fewer input UTXOs. 

Closing as a Ledger device issue.
