### ISSUE TITLE
Can't spend `1 sat`

### ISSUE THREAD

**Issue by kolya182** [sparrowwallet/sparrow#149]
Related https://github.com/sparrowwallet/sparrow/issues/148 ?
I should be able to spend `1 sat` right ?

https://user-images.githubusercontent.com/3277207/123530558-b25d9e00-d6b0-11eb-9436-877ee79607b2.mov

**Comment by craigraw** [comment]
No - the Bitcoin network will reject a 1 sat amount in order to prevent spam transactions. The minimum number of sats you can send is 546 sats, although this number varies according to script type. This is known as the dust threshold.

**Comment by kolya182** [comment]
> No - the Bitcoin network will reject a 1 sat amount in order to prevent spam transactions. The minimum number of sats you can send is 546 sats, although this number varies according to script type. This is known as the dust threshold.

Would you consider adding `?` info button explaining this to the user ?. In case user want to send small amount `<546` sats. 
Bitcoin Core only shows this, which is not very helpful.
<img width="423" alt="Screen Shot 2021-06-28 at 11 41 47 PM" src="https://user-images.githubusercontent.com/3277207/123749573-6eae9400-d86a-11eb-9cc2-2d909920dd56.png">

**Comment by craigraw** [comment]
Good idea. Added in 8033e5f.

<img width="481" alt="Screenshot 2021-06-29 at 12 25 35" src="https://user-images.githubusercontent.com/862166/123785036-583f2180-d8d8-11eb-88da-94649737e488.png">
