### ISSUE TITLE
Fake Payjoin?

### ISSUE THREAD

**Issue by sha-265** [sparrowwallet/sparrow#1490]
Is there any reason not to create fake "payjoin" transactions for better privacy?

It's similar to the fake "coinjoin" feature, but with less outputs so it's better if you want to consolidate your UTXOs (and pay a little bit less fees), and not splinting them, but still get better privacy.

**Comment by craigraw** [comment]
No reason not to. Generally the more entropy in a transaction the better. Transactions with multiple inputs and outputs have more possible interpretations - so long as the basic guidelines of avoiding rounded amounts and multiple script types are followed.

**Comment by sha-265** [comment]
So what about adding it as a feature?

**Comment by craigraw** [comment]
You can already create transactions with multiple inputs and outputs.

**Comment by sha-265** [comment]
How can I force the wallet to add an input, even if it's not "needed"?

**Comment by craigraw** [comment]
Just multiple select from the UTXOs tab.
