### ISSUE TITLE
[Feature request] Sign again or compare signature

### ISSUE THREAD

**Issue by mario7421** [sparrowwallet/sparrow#1492]
I would like to sign again a transaction that is already confirmed on the blockchain, in order to verify whether a deterministic nonce was used during the original signing process. To achieve this, I intend to remove the existing signature and generate a new one using a different device than the one that originally signed the transaction.
When I open a confirmed transaction there are no buttons to sign again, so I think this is currently not possible.

**Comment by craigraw** [comment]
Correct. If you wish to do this, I suggest creating and signing two identical transactions without broadcasting. Comparing the signatures will achieve the same verification that devices are using RFC6979 when signing.
