### ISSUE TITLE
connection issues on sparrow

### ISSUE THREAD

**Issue by Jiggamoto** [sparrowwallet/sparrow#1493]
Goodafternoon, was wondering, while running on a public server, why my sparrow keeps losing connection and having to continuosly connect and disconnect during usage. is this a pc issue or a sparrow issue?

**Comment by craigraw** [comment]
There are two reasons why this may happen:
1. Connectivity issues on the client PC
2. Too many open wallets (or wallets with too many addresses). The public servers have limits to protect abuse, and reaching these limits will trigger a disconnection and temporary ban. The solution in this case is to run your own Bitcoin node.
