### ISSUE TITLE
Send screen after transaction broadcast

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#15]
Should the "Send Screen" clear all the fields after a transaction is successfully signed and broadcasted? It's confusing when you go back a tab and all of the fields are filled with the address and amounts from the transaction we just published.

**Comment by craigraw** [comment]
Agree - will implement.

**Comment by craigraw** [comment]
Implemented in https://github.com/sparrowwallet/sparrow/commit/ead8fa2207c513c8f38d7cd7eedd324067911585
