### ISSUE TITLE
Trying to install arm64 package. Error that it's a amd64 package.

### ISSUE THREAD

**Issue by lewi3069** [sparrowwallet/sparrow#1503]
dpkg: error processing archive sparrow-server_2.0.0-1_arm64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 sparrow-server_2.0.0-1_arm64.deb

**Comment by craigraw** [comment]
Try the tar.gz

**Comment by lewi3069** [comment]
I'm not seeing that [here](https://github.com/sparrowwallet/sparrow/releases) for the arm64 sparrow server (headless)

**Comment by craigraw** [comment]
It's here: [sparrow-server-2.0.0-aarch64.tar.gz](https://github.com/sparrowwallet/sparrow/releases/download/2.0.0/sparrow-server-2.0.0-aarch64.tar.gz) (You have to click 'Show All Assets' - looks like a minor display change on Github). aarch64 and arm64 are equivalent.

**Comment by craigraw** [comment]
Fixed in 73b672a7.
