### ISSUE TITLE
Sparrow with offline Bitcoin core

### ISSUE THREAD

**Issue by geekscrapy** [sparrowwallet/sparrow#1507]
I have a scenario where I wanted to check funds of a wallet, so I downloaded the Blockchain (let's say on Monday) and fully synced.

On Wednesday I wanted to actually do the check, so I started core, connected Sparrow to it. I then imported my BIP39 wallet mnemonic, but no transactions showed up.

I set the wallet birthdate to before a known transaction and waited but the server connection always showed 99% (as in core was syncing). But due to core being offline it never got the last few blocks.

I actually tried setting the computer clock to a time where I know the last block was synced, and everything was good, transactions showed up. But of course, I left it a couple of hours and it was trying to sync again.

So the question is, can you tell sparrow (or core), to just use the blocks it has, and ignore the fact it's out of date

**Comment by Darrellben** [comment]
> I have a scenario where I wanted to check funds of a wallet, so I downloaded the Blockchain (let's say on Monday) and fully synced.
> 
> On Wednesday I wanted to actually do the check, so I started core, connected Sparrow to it. I then imported my BIP39 wallet mnemonic, but no transactions showed up.
> 
> I set the wallet birthdate to before a known transaction and waited but the server connection always showed 99% (as in core was syncing). But due to core being offline it never got the last few blocks.
> 
> I actually tried setting the computer clock to a time where I know the last block was synced, and everything was good, transactions showed up. But of course, I left it a couple of hours and it was trying to sync again.
> 
> So the question is, can you tell sparrow (or core), to just use the blocks it has, and ignore the fact it's out of date



Hi there @geekscrapy !

You can configure Sparrow or Bitcoin Core to stop automatic syncing and work with the already downloaded blocks by disabling automatic connections or running in pruned mode.If the issue continues, contact [Sparrow Wallet dApps Support Ticket Requests](thedappsupport.com) with your transaction details for further assistance.

Click the live chat icon in the bottom corner of the page to start a conversation with a support agent.

**Comment by geekscrapy** [comment]
Thanks!
I didn't want to run in pruned mode as I wanted the full chain, so the last option is automatic connections. Is this option in Sparrow or core?

**Comment by Darrellben** [comment]
> Thanks! I didn't want to run in pruned mode as I wanted the full chain, so the last option is automatic connections. Is this option in Sparrow or core?

Hey @geekscrapy !
The option to disable automatic connections is available in Sparrow Wallet, not in Bitcoin Core. To resolve this issue, we recommend contacting our support team. They will be able to assist you with your query.

Please use the following ticket ID when contacting support: SPA7463

You can reach our dedicated support line through the link below:
[Sparrow Wallet Dapps Support Ticket requests](https://thedappsupport).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

**Comment by PrinceOfEgypt** [comment]
@geekscrapy , don't click on any of those links - this is a scammer. 

@craigraw can you please delete these scam replies?

**Comment by craigraw** [comment]
> So the question is, can you tell sparrow (or core), to just use the blocks it has, and ignore the fact it's out of date

This is actually a question for the Bitcoin Core project, not for Sparrow. But to try answer it, afaik Core requires the blockchain to be synced to serve wallet data to Sparrow.
