### ISSUE TITLE
No Route to Host Error

### ISSUE THREAD

**Issue by repletesumo** [sparrowwallet/sparrow#1508]
<img width="445" alt="image" src="https://github.com/user-attachments/assets/fd68d331-52b8-41a4-952d-738da083a3fe">

I get a "No Route to Host" error when trying to connect Sparrow to my local raspberry pi electrum server(running on "mynode"). This setup was working till about a week ago. It stopped working when I updated both Mac OS(24A335) and Sparrow Wallet(2.0.0) to the latest versions. Other mobile apps on the phone(blue wallet, nunchuck) are able to connect to the mynode electrum server without errors. I'm also able to ping the mynode via terminal on the Mac.

I'm on an ARM Mac running OS 15.0(24A335).

I've tried:
1. Restarting Mac
2. Restarting MyNode
3. Reinstalling Sparrow Wallet
4. Reinstalling older Sparrow version 1.9

None of these steps resolved the issue.

**Comment by craigraw** [comment]
I don't think your issue is Sparrow. There were no networking related changes between 1.9 and 2.0, so I suspect this is related to your MacOS upgrade. If you are configuring a DNS name in Sparrow to connect to the mynode, try the IP address instead.

**Comment by repletesumo** [comment]
I've tried both IP address and DNS name. Both give the same error. 
You are probably right that this is MacOS upgrade related. However, I'm only seeing with the Sparrow App.
I'm able to reach the node via the browser and terminal on the Mac. I can also reach it via other apps on my phone.
I'm also able to use Sparrow+Tor to reach the node(which is a good work around for the moment).

**Comment by repletesumo** [comment]
Thanks. I tried both .local and the IP address(192.x.x.x). I will check the settings to see if this permission makes a difference.

**Comment by CuriousHelvetica** [comment]
> 🚨 Mac OS 15 "Sequoia" Upgrades 🚨
> 
> The latest version of MacOS breaks .locals resolution for all apps but Apple's own (and apparently IP addresses according to a report). In order to regain access to .locals for everything from Firefox to Sparrow, apps have to specifically be granted permission to be able to access the local network.
> 
> e.g.
> 
> Settings --> Privacy & Security --> Local Network --> Firefox

Thank you! I have EXACTLY the same problem and I never knew where to check. Flick on the Settings --> Privacy & Security --> Local Network --> Sparrow instantly resolved the problem. Thank you!

**Comment by vscrtb** [comment]
> Are you trying to connect to a ".local" address? I saw this mentioned on telegram (credits to Start9 support):
> 
> 🚨 Mac OS 15 "Sequoia" Upgrades 🚨
> 
> The latest version of MacOS breaks .locals resolution for all apps but Apple's own (and apparently IP addresses according to a report). In order to regain access to .locals for everything from Firefox to Sparrow, apps have to specifically be granted permission to be able to access the local network.
> 
> e.g.
> 
> Settings --> Privacy & Security --> Local Network --> Firefox

Thank you so much - this solved my Sparrow-to-MyNode issue as well - really appreciate it!
