### ISSUE TITLE
Add copy seed phrase as a string including all words

### ISSUE THREAD

**Issue by kolya182** [sparrowwallet/sparrow#151]
![Screen Shot 2021-06-30 at 12 15 00 AM](https://user-images.githubusercontent.com/3277207/123918089-60c74480-d938-11eb-8cd0-7a258404eaa5.jpg)
Like so
<img width="45" alt="Screen Shot 2021-06-30 at 12 16 36 AM" src="https://user-images.githubusercontent.com/3277207/123918151-70468d80-d938-11eb-9442-7f52d7dc5e4a.png">

**Comment by craigraw** [comment]
This would be helpful particularly in testing scenarios, added in b9e64d4.

However, I haven't added the copy icon to all the fields as I don't want to confuse users with additional UI elements at this point.
