### ISSUE TITLE
Custom Policy Type

### ISSUE THREAD

**Issue by anurag-l1nt** [sparrowwallet/sparrow#1515]
I’ve noticed that in the `settings.fxml` file, the "CUSTOM" option for Policy Type has been commented out since 2020, although looking at other parts of the code, it seems that there is some support implemented for it. 

https://github.com/sparrowwallet/sparrow/blob/233addc1b7a8c20efaede39919bf91397a1c0223/src/main/resources/com/sparrowwallet/sparrow/wallet/settings.fxml#L35-L41

Why was it deactivated?

I ask because I would like to "play" with this and implement some custom policy type, perhaps a time-locked multisig, and I’d like to know if the option was disabled because there’s some capability that’s not supported or if it was just for security reasons, to prevent users from putting their funds at risk by using policy types they’re unfamiliar with.

I think it could be interesting to have a few other predefined Policy Types that could be useful for users, implementing more complex contracts like spending with multisig at any time or with a single signature after a set time, for example.

Thank you very much.

**Comment by craigraw** [comment]
It was never implemented. Custom policy types are not currently supported, and there are no immediate plans to implement them.
