### ISSUE TITLE
2.0 wont connect to core 28

### ISSUE THREAD

**Issue by pragford** [sparrowwallet/sparrow#1517]
2.0 will connect to core 27 but not 28. Both core configs are identical. Any ideas?

**Comment by PrinceOfEgypt** [comment]
Check the release notes for 28.0, specifically the "P2P and Network Changes" section. There have been changes to the default behavior that may be impacting you depending on your configuration 

https://bitcoincore.org/en/releases/28.0/

**Comment by craigraw** [comment]
I can't reproduce this. Check the log file for any errors (see Help menu).

**Comment by pragford** [comment]
Copy that, I'll get back to you

**Comment by pragford** [comment]
2024-10-14 18:01:55,049 ERROR [JavaFX Application Thread] c.s.s.n.ElectrumServer [null:-1] Failed to start BWT
dev.bwt.libbwt.BwtException: JSON error: invalid type: sequence, expected a string
at com.sparrowwallet.merged.module@2.0.0/dev.bwt.libbwt.daemon.NativeBwtDaemon.start(Native Method)
at com.sparrowwallet.sparrow@2.0.0/com.sparrowwallet.sparrow.net.Bwt.start(Unknown Source)
at

**Comment by craigraw** [comment]
Ok, you are using the old pre-descriptor Bitcoin Core wallet. Sparrow still supports this approach for legacy Core installs, but if you are upgrading (and not running a pruned node) it's time to move on. 

The way to do this is to shut down both Core and Sparrow. Then delete the 'sparrow' folder in the Bitcoin Core wallets directory. Restart Core and Sparrow. Sparrow will ask Bitcoin to recreate your wallet as a descriptor-based wallet (called 'cormorant'). Rescanning will then commence, after which you will be back up and running again.

**Comment by pragford** [comment]
I did that, still will not connect . I get an error when starting core that says skipping wallet path that doesn't exist ...... Failed to load data base path ....../sparrow. Path dies not exist. It then loads core as cormorant bit sparrow still won't connect. Same error in logs

**Comment by craigraw** [comment]
Ok. Close Sparrow, open the config file in sparrow home in a text editor (see the first FAQ to find it) and change the value of useLegacyCoreWallet to false.

**Comment by pragford** [comment]
Copy that, ty. Willtry when home

**Comment by pragford** [comment]
OK that worked, now in the wallet I get this error:  errormessage
Code=4 message=list descriptors is not available for non descriptor wallets , data=null

**Comment by pragford** [comment]
Solved. Ty for the help.
