### ISSUE TITLE
Gdk-WARNING **: time stamp: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.

### ISSUE THREAD

**Issue by e-Gyi-qO** [sparrowwallet/sparrow#1519]
I get
`Gdk-WARNING **: time stamp: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.`
Can those warning eliminated?

**Comment by craigraw** [comment]
Unfortunately not - it's occurring on a lower level to the application. That said, it's harmless - you can read more about it here #1059.
