### ISSUE TITLE
Sparrow Wallet doesn't support the Specter DIY Multi Sig Deskriptor

### ISSUE THREAD

**Issue by Schnuartz** [sparrowwallet/sparrow#1527]
if you create a Multi Sig Wallet, and then import all the Multi Sig Data from the Cosigners into the Specter DIY. Than you have a second Wallet on your Specter DIY, where you can check all the adresses from the Multi Sig Wallet. Than you can go into the Wallet settings from the Specter DIY and export the wallet Descriptor of the whole Multi Sig Wallet. But the Sparrow Wallet is not able to interpret this specific Multi Sig Descriptor. 😥

Blue Wallet is able.
![82cea170-d6c5-42e6-b9ae-93225a5a4c8d](https://github.com/user-attachments/assets/405c5890-ed09-4e3f-b9e9-711590686282)
![0c24ceab-3c24-487d-a392-a2c1a4787327](https://github.com/user-attachments/assets/10a250c1-c670-4b8b-accf-bc0bb6581845)

**Comment by craigraw** [comment]
Can you provide a (redacted) example of this output descriptor?

**Comment by Schnuartz** [comment]
> Can you provide a (redacted) example of this output descriptor?

So this is the deskriptor (blank wallet)



{"descriptor": "wsh(sortedmulti(2,[74d682c3/48h/0h/0h/2h]xpub6EtQChMwaSperjj8crD4zfyWU7Jc1baj4bh9NGFUg7RDrzBeFvVgtYPFmYWDSgy3ie3NkzYkJCoyRKqLgS6XovSr44kpaphkyauovUSVoRv/0/*,[2bacd1ba/48h/0h/0h/2h]xpub6EbjWkRGwgr1R6VA1YkjysQKEsefPzZZyTTueFo7bLyQknHJM6aXf9Rd7jT3FKh4TcnKKeiFjuscQDvEgdzQf1RxeQYcG7h3BwmMtFUFJos/0/*,[8a8edf5c/48h/0h/0h/2h]xpub6E1QrYbCfT4MVLP8d1M7wRnLsjKZstVSZTaKL1GSu8WyvzzKscaNGmxfpV6J9aDCXcnfcVZR8ATAfH8uhEcTBiSArgxty8uFNKVHLgmio42/0/*))#esdnumzc", "label": "Specter DIY Testwallet Support"}


This said the Crypto Guide to the issue in the Specter DIY HWW telegram group:
"
Ah rito, basically the easiest way right now is to just create a new wallet in Sparrow, click on edit next to the "Script Policy" heading

click to scan the QR code and then you can just remove the description at the start and the label at the end. (Basically everything before wsh( and everything after the figerprint

Should be a simple PR to add the button to Sparrow import screen"



I think the problem could be solved like it works with the jade:

![c7d0684f-76cc-4774-b9d0-21f8ddf630b1](https://github.com/user-attachments/assets/8e3b6d20-1286-4502-9ed9-b176373c58e7)

You probably don't need it but I created a better description of the error as well:
![f2450ebc-3332-4944-9b96-2f14c8846784](https://github.com/user-attachments/assets/caf2f846-ef2d-4981-b80b-582cb88fa33a)

**Comment by craigraw** [comment]
Thanks for the thorough report. The reason this is not working is because you are using the function to import the device's xpub into Sparrow, not a complete multisig wallet output descriptor. I have added a 'Specter DIY Multisig' option to the File > Import Wallet list, which functions in the same way as the 'Specter Desktop' option (which can be used currently with this example, as it seems to use the same file format).

> if you create a Multi Sig Wallet, and then import all the Multi Sig Data from the Cosigners into the Specter DIY.

How are you currently importing this data? Can you check whether an export function is also necessary to import a multisig wallet from Sparrow to Specter DIY? You can again use the Specter Desktop option in the File > Export Wallet menu on a multisig wallet in Sparrow to check.

**Comment by Schnuartz** [comment]
oh, you are completely right. Sorry that I didn't tested it myself for some reason. But it works if you export the Multi Sig Wallet from the Specter DIY as Specter Desktop in Sparrow Wallet. 
![Screenshot 2024-11-04 143007](https://github.com/user-attachments/assets/09b5175f-dc6d-4323-89ff-5c7f58da6807)

And the export from Sparrow to Specter DIY is no problem as well. You can just export this data like normal in an Multi Signatur Wallet.

![Screenshot 2024-11-04 143347](https://github.com/user-attachments/assets/547c0d78-ec16-437e-9458-2a1ab5ae1fed)

So thank you!!! Specter DIY works great with Sparrow!
But maybe it would be cool to add some information to the import Funktion in Sparrow Wallet that you have to import the Multi Sig Wallet from the Specter DIY as Specter Desktop, because that's not intuitive.

**Comment by craigraw** [comment]
Added a Specter DIY Multisig option to the Wallet Import menu in 12034a07.

<img width="612" alt="Screenshot 2024-11-05 at 08 47 39" src="https://github.com/user-attachments/assets/f99dc48e-044e-4929-8e6c-030ab3606278">
