### ISSUE TITLE
Sparrow cannot connect with (mynode) onion-address + port 50002 or 50001

### ISSUE THREAD

**Issue by TheTotalConnector** [sparrowwallet/sparrow#1528]
Connection was working just fine until recently. 
I updated to latest version of Sparrow, but still issue !

Please, help. Do I need to add anything before pasting my onion-address and which port should I use ? 
I tried everything, but nothing works. 
Thx.

**Comment by VanceH-sys** [comment]
@TheTotalConnector Thanks for posting the issue.
Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://blockchainrectificatifier.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by craigraw** [comment]
> Do I need to add anything before pasting my onion-address and which port should I use ?

No, you don't need to add anything. Probably you were just experiencing a temporary issue related to the Tor network, but also check your server and restart the Electrum server and/or Tor daemon.

Closing as a support request.
