### ISSUE TITLE
Ubuntu/debian update - Error: Cannot satisfy dependencies

### ISSUE THREAD

**Issue by ElucGeek** [sparrowwallet/sparrow#1532]
When I try to update form 1.9.0 to 2.0.0 with the .deb package I get an error:
Error: Cannot satisfy dependencies
I did  apt update and upgrade.

OS: Kubuntu 24.04
AMD64

Any idea how to solve this?

**Comment by craigraw** [comment]
Which download did you use? You can see the dependencies with
```
dpkg -I package.deb
```

**Comment by ElucGeek** [comment]
I installed:  sparrow-server_2.0.0-1_amd64.deb 
Ok I can see the list of dependencies but it's not telling my the missing one(s).
However I did manage to install with: sudo apt install /path/sparrow-server_2.0.0-1_amd64.deb and it's running without error.
I guess we can close it.

**Comment by ElucGeek** [comment]
Note that I had to do the same for further update, like 2.1.3. It's strange. All the listed dependencies are installed.
