### ISSUE TITLE
Immense appreciation and respect - plus a few technicalities

### ISSUE THREAD

**Issue by Creator222** [sparrowwallet/sparrow#1538]
Hello _dearest_ Craig Raw, you MAGNIFICENT Soul,

I am called to reach out to you to express my deepest, utmost, sincerest appreciation, honor and respect for the SERVICE TO HUMANITY that you have provided and continue to provide so selflessly, with or without support (we should ALL be supporting you / your team), for many years, in the development and continual support you provide in Sparrow Wallet.

You are undoubtedly, a unique and magnificent Soul on this planet and I so greatly admire this part of your Divine Purpose in contributing this incredible, consistently effective, beautiful, trustworthy software. I see men like you in nearly the same regard as Satoshi Nakamoto himself - which is extremely highly regarded. 

I would love to share with you a donation today made on BTCPay on your website for about 55,000 sats, around $50 USD. I had to make it on the chain, despite trying three times to send it over lightning using my phoenix wallet. Each LN attempt failed. The error in phoenix says: "An error occurred on a node in the payment route. The payment may succeed if you try again." I should have tried with a different LN wallet but didn't think to, so I'm not sure what is causing the issue. I'll try again next time I donate :)

I have been using your software for many years as a tool for managing this incredibly important resource we all have access to on Earth now, called Bitcoin. I am so humbled by your dedication. Your work ethic. Your Love. To support this budding ecosystem that has immense potential to bring humanity into a completely new state of existence, one of freedom, abundance, and much of what we all deserve is Divine HUmans.

Another issue is just being able to contact you/your team. I was unable to join the Telegram group. Telegram gives me an error: "Sorry, this group is not accessible." Just thought I'd let you know. I also couldn't send you a message on Twitter because your account requires messengers to be "Verified", which I am not.

I hope you are having a brilliant, peaceful November, wherever you are in the world, and enjoying these face-melting actions in the bitcoin marketplace as well.

With greatest appreciation and respect,

Yuri

**Comment by Creator222** [comment]
![photo_2024-11-15_18-06-11](https://github.com/user-attachments/assets/825b5f4a-edcd-4a35-bb8b-dce8702406a8)

**Comment by craigraw** [comment]
Thank you for the kind words Yuri.

Managing inbound liquidity is an ongoing task :) It should be better now - I appreciate your donation!

> Telegram gives me an error: "Sorry, this group is not accessible."

Let me know your Telegram username (either here or on Telegram DM) and I'll take a look.
