### ISSUE TITLE
update path to tor on nixos

### ISSUE THREAD

**Issue by AronGahagan** [sparrowwallet/sparrow#1541]
I'm afraid I don't know enough about all this to submit a pull request, but on NixOS, in the file

`~/.sparrow/tor/work/.kmptor/tor`

the command (in NixOS) is (something like):

`exec /nix/store/7i5qcshkq7brb8n0bxdkmb1vfm1pwbbc-tor-0.4.8.13/bin/tor "$@"`

but if tor gets updated in the nix store, that path changes (to include a hash and a version, etc.), so the command (for NixOS)  should be

`exec /run/current-system/sw/bin/tor "$@"`

the above path is what you get from running `which tor` - tested and works in sparrow 1.9.1 (latest release available in the nixpgs).

**Comment by craigraw** [comment]
See https://sparrowwallet.com/docs/faq.html#does-sparrow-require-tor. Sparrow starts it's own, bundled Tor if Tor is required and an external Tor proxy is not configured. This is what is in `~/.sparrow/tor/work/.kmptor/tor`.

If you are running NixOS with Tor installed, I suggest configuring Sparrow to use that instead in the Server Preferences (probably `127.0.0.1` and port `9050`).

**Comment by AronGahagan** [comment]
Thanks, @craigraw - either way, the hard-coded path generated by sparrow returns 'file not found' when I tried to connect. Updating it to the above fixed it, is version agnostic, and is update-proof. Fantastic app, btw. Thanks again.
