### ISSUE TITLE
New Wallet Option - Has Existing Transactions checkbox

### ISSUE THREAD

**Issue by sgulley2** [sparrowwallet/sparrow#1543]
In the latest version of Sparrow 2.0.0, when selecting the New Wallet Option, the Has Existing Transactions checkbox is missing in the Mac M1/M2 version - It is present in the Intel version however

**Comment by craigraw** [comment]
The existing transactions checkbox is only present when connected to Bitcoin Core (green toggle) since it is only required in that case. Can you verify?

**Comment by sgulley2** [comment]
Yes that would be correct - out of curiosity why is this so ?



Sent from my Galaxy



-------- Original message --------
From: craigraw ***@***.***>
Date: 11/25/24 12:54 AM (GMT-05:00)
To: sparrowwallet/sparrow ***@***.***>
Cc: Stuart Gulley ***@***.***>, Author ***@***.***>
Subject: Re: [sparrowwallet/sparrow] New Wallet Option - Has Existing Transactions checkbox (Issue #1543)


The existing transactions checkbox is only present when connected to Bitcoin Core (green toggle) since it is only required in that case. Can you verify?

**Comment by craigraw** [comment]
Bitcoin Core needs to scan the blockchain for transactions belonging to a particular wallet to build an index of them. This process takes time, so you generally don't want to start at genesis, as it will take much longer. So, the existing transactions checkbox allows you to specify a wallet birthdate to speed things up. With Electrum servers, you already have a complete index of all transactions, so a wallet birthdate is unnecessary.

**Comment by sgulley2** [comment]
Thx - makes sense



Sent from my Galaxy



-------- Original message --------
From: craigraw ***@***.***>
Date: 11/25/24 1:03 AM (GMT-05:00)
To: sparrowwallet/sparrow ***@***.***>
Cc: Stuart Gulley ***@***.***>, Author ***@***.***>
Subject: Re: [sparrowwallet/sparrow] New Wallet Option - Has Existing Transactions checkbox (Issue #1543)


Bitcoin Core needs to scan the blockchain for transactions belonging to a particular wallet to build an index of them. This process takes time, so you generally don't want to start at genesis, as it will take much longer. So, the existing transactions checkbox allows you to specify a wallet birthdate to speed things up. With Electrum servers, you already have a complete index of all transactions, so a wallet birthdate is unnecessary.
