### ISSUE TITLE
[Feature Request] Implement P2TR Multi-Signature Wallet Support

### ISSUE THREAD

**Issue by witthawin0** [sparrowwallet/sparrow#1545]
**Taproot Multi-Signature Wallet Support**

Summary: Add comprehensive support for Taproot multi-signature wallets in Sparrow Wallet, enabling users to leverage Bitcoin's latest advancements for enhanced privacy, scalability, and flexibility in multi-party transactions.

Description: Sparrow Wallet currently supports P2SH and SegWit multi-signature wallets. Introducing Taproot-based multi-signature support would offer users several benefits, including:

Improved Privacy: Taproot makes all outputs and transactions look the same on-chain, reducing the ability for observers to distinguish between simple transactions and multi-signature setups.

Enhanced Scalability: With Schnorr signatures, aggregating multiple signatures into a single signature reduces transaction size, saving block space and lowering fees.

Flexibility: Taproot supports more complex spending conditions with script trees (Tapscript), enabling advanced use cases without revealing unnecessary details.

**Comment by craigraw** [comment]
While understandable, this issue has been raised several times already.

The most interesting scheme for threshold based multisig with Taproot is FROST. Once FROST has a good implementation (most likely, in libsecp256k1) then it can be integrated into Sparrow.

Closing as a duplicate.

**Comment by davterra** [comment]
Any estimated ETA for  this?

**Comment by craigraw** [comment]
You'll need to ask the people working on libsecp256k1.

**Comment by pjw65** [comment]
> You'll need to ask the people working on libsecp256k1.

How about https://github.com/bancaditalia/secp256k1-frost ?

**Comment by craigraw** [comment]
> How about https://github.com/bancaditalia/secp256k1-frost ?

Interesting! But marked as not ready for production
