### ISSUE TITLE
Wallet detects bip47 transactions from different script types

### ISSUE THREAD

**Issue by ottosch** [sparrowwallet/sparrow#1548]
After importing a **TESTNET4** wallet from Ashigaru, Sparrow created the wallet as a Nested Segwit one.
The 2 P2SH UTXOs were loaded correctly, but 1 P2WPKH UTXO that came from BIP47 is also displayed, along with other BIP47 transactions to P2WPKH addresses.

I'm not sure if scanning the other script types is a feature or a bug, but it looks confusing to me:

UTXOs:
![image](https://github.com/user-attachments/assets/c4320fe7-11e4-487d-b71b-1f9c83b734bf)

Transactions:
![image](https://github.com/user-attachments/assets/8fe27dd0-223f-4346-b140-f60e3cf6e56f)

**Comment by craigraw** [comment]
It is a requirement for supporting BIP47 that a wallet can receive UTXOs of P2PKH, P2SH-P2WPKH and P2WPKH script types. While for usability reasons Sparrow does not in general support multiple script types in a single wallet, it does in the case of BIP47.

If you go to the Addresses tab, and click on the PayNym icon in the top right, you will be able to see the various subwallets created for each BIP47 notification received.
