### ISSUE TITLE
Request to make animated QR display size, density, & frame rate configurable

### ISSUE THREAD

**Issue by SeedSigner** [sparrowwallet/sparrow#155]
Given the increasing variety of hardware devices using QR codes for PSBT exchange, it would be helpful for Sparrow users to have the ability to adjust settings related to animated QR display size, density and frame rate to accommodate for devices with differing levels of ability to ingest and process frames.

**Comment by craigraw** [comment]
Given there is no way to tell in advance how to adjust these settings, ideally I would like to keep this burden off the user. It seems that we should as a developer community try to find a group of settings that we can all work towards (or perhaps two of them?). I will post to the Airgapped Wallet Standards signal group to see if we can reach any kind of consensus.

**Comment by craigraw** [comment]
As per the Signal discussion, Sparrow now uses 200ms and 250 bytes max fragment length (up from 400ms/100 bytes).

I did implement the ability to increase the max fragment length by resizing the dialog as you suggested, but given that the decoder will need to be reset when this happens I don't think it's a safe change to add, so I've reverted it.

**Comment by SeedSigner** [comment]
I think the change to 200ms and 250 bytes will go a long way to improve user experience, really appreciate your work on this.
