### ISSUE TITLE
camera on my mac does not capture my CC BBQR code when airgapping?

### ISSUE THREAD

**Issue by ntmnuts** [sparrowwallet/sparrow#1550]
Hi 
I want to create a new wallet w CC Q and in airgapped mode. All goes fine until I need to scan the QR on my CC Q which the camera on my Mac for whatever reason will not capture (tried several times). The Sparrow sw mentions its facetime camera and Im sure that I previously note that I had an option to instead connect w the camera on my iphone, but now in Sparrow it does not give me the option to use my phones camera anymore? 

Can you help?

**Comment by craigraw** [comment]
Make sure you are capturing in HD. You can also use your phone to magnify the image for your laptop camera.

Closing as a support request.

**Comment by ntmnuts** [comment]
How do I use my phone to magnify the image for lap top camera? the option to do so does not appear?

**Comment by ntmnuts** [comment]
sorry , pls ignore my previous question, I will figure it out and you have better things to do than that:) 

However, I dont understand what happened in Sparrow w the functionality/option to choose to link my phone to the mac and then just use the phone to scan directly  instead of the Mac. That worked fine when I created first airgapped wallet in Sparrow w CCQ, but now the option to do so in Sparrow does not show anymore when I want to issue another new wallet airgapped? did I do something to mistakenly turn this function off/on? or what? would you know?

**Comment by craigraw** [comment]
I meant the simplest is actually to hold your phone between the laptop and the Coldcard, so the laptop is looking at it's screen, which is showing a magnified image of the Coldcard screen. It's inelegant, but it works. Fwiw I don't need to do this on a Macbook Pro, but I know some older Macbooks have worse cameras.

>  I do something to mistakenly turn this function off/on?

Nothing I'm aware of unfortunately.

**Comment by ntmnuts** [comment]
ok got it and thanks :)
