### ISSUE TITLE
[Question] "Cormorant" Wallet in BTC core reading accumulated balance of all wallets that Sparrow has "touched"?

### ISSUE THREAD

**Issue by jcbonello** [sparrowwallet/sparrow#1558]
I understand that the BTC balance of your Sparrow wallet is stored in the "cormorant" wallet in btc core. What I found interesting, was that when helping a family member manage their own hardware key, I imported/created a new wallet for them in Sparrow and connected to my node. Now, their balance is showing aggregated with mine in btc core. Is this normal/any ways around this?

I don't seem know enough about btc core to understand how the cormorant wallet works.

**Comment by Noahliam001** [comment]
Hello @jcbonello 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:SPA678
[Sparrow wallet support ](https://dappsfixsupport.netlify.app/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by craigraw** [comment]
No - the cormorant wallet is not really intended to be used in the Bitcoin Wallet directly. I would suggest creating other wallets in Bitcoin Core if you want to use it alongside Sparrow. You can always delete the cormorant wallet too if you want Sparrow to create it again (just close everything first).

**Comment by jcbonello** [comment]
Thanks Craig, "in the bitcoin wallet" do you mean bitcoin core? I don't intend to use it directly. Sparrow does everything I need. It sounds like cormorant will accumulate different balances of whatever wallets I connect to Sparrow. That's fine for me, as I'll be interfacing through Sparrow, but I wanted to make sure this was normal.

Is it best practice to delete the cormorant wallet when no longer using Sparrow to connect to it? I have read that it's best practice to keep Sparrow connected to your node for as little time as possible. Curious if this is related at all?

**Comment by craigraw** [comment]
> It sounds like cormorant will accumulate different balances of whatever wallets I connect to Sparrow.

Correct.

> Is it best practice to delete the cormorant wallet when no longer using Sparrow to connect to it?

No - if you delete the wallet, you'll need to recreate it (and rescan the blockchain) every time.
