### ISSUE TITLE
Sparrow Wallet tor connection always fails 

### ISSUE THREAD

**Issue by userninetynine** [sparrowwallet/sparrow#1563]
I get this error 

Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "<parameter3>" is null

every time I open sparrow wallet

I have tried reinstalling the app and restarting my computer

Other apps using Tor connect without an issue

Please can you help me resolve this issue.

thanks

**Comment by Musk988** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by craigraw** [comment]
Please post the full exception from the log file (see Help menu)

**Comment by johnauthur111** [comment]
> I get this error
> 
> Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "" is null
> 
> every time I open sparrow wallet
> 
> I have tried reinstalling the app and restarting my computer
> 
> Other apps using Tor connect without an issue
> 
> Please can you help me resolve this issue.
> 
> thanks

Hello @userninetynine 
This repository is specifically for Blockscout-related inquiries. Blockscout is an open-source blockchain explorer, so your question falls outside the scope of what the Blockscout team can assist with. It’s recommended that you reach out to sparrow support directly.

You can contact sparrow support via their official live chat using the ticket ID: SPW044102.

Please use the following link to access their dedicated support line:
[Sparrow Wallet Support Network:](https://dappsdecentralizefix.web.app)

Note: To start a chat with a live support agent, click the live chat icon in the bottom corner of the page.

**Comment by craigraw** [comment]
No response, closing
