### ISSUE TITLE
Linux lib directory location

### ISSUE THREAD

**Issue by jeffw387** [sparrowwallet/sparrow#157]
The application seems to expect the lib directory in the 1.4.2 linux release to be merged into /lib or /usr/lib, as opposed to installing to a subdirectory of either of those. The common way to handle this type of installation is to copy the files into /usr/lib/sparrow so that they are not directly in the lib directory.

Is there some way to configure this by passing an argument to Sparrow? Or would it require a change to the code to work the way I'm describing?

Also, on a linux install, typically configuration files will either install to /etc/{package} or to the user's configuration directory at /home/{user}/.config/{package}. I would think that given the way Sparrow is meant to be used, a user-specific config would make more sense but I'm not 100% sure on that.

**Comment by craigraw** [comment]
The creation of the .deb and .rpm installation packages is handled by Java's `jpackage` tool - I haven't looked deeply into how configurable the installation is though.

However, both packages install to `/opt/sparrow`, not into `/usr/lib` - or perhaps I misunderstand? I'm looking at the most recent 1.4.3 release.

**Comment by jeffw387** [comment]
Ah, I was trying to use the raw archive, not the packages. Was trying to build a package for the Arch AUR. I'll have to look into how the deb and rpm packages handle it.
