### ISSUE TITLE
Sparrow wallet on Start9 OS - Cant detect hardware wallet.

### ISSUE THREAD

**Issue by techrivertree** [sparrowwallet/sparrow#1572]
I have a mini PC setup with Start9 OS. Bitcoin Core, Electrs, and Sparrow wallet are installed. Bitcoin core is fully synced and Electrs says I can connect to a wallet.

Sparrow wallet will open. In preferences, I am able to ping my private electrs server.

When I try to connect to a hardware wallet (Ledger Nano X and Cold Card Mk 4) Sparrow wallet cannot detect either of those hardware wallets. I tried both on my PC and on my mini PC with a known good cable.

Any ideas?

![Screenshot from 2024-12-27 20-54-20](https://github.com/user-attachments/assets/7dedfea4-b1b0-4209-a8fc-2d6a633dc4b8)
![Screenshot from 2024-12-27 20-55-25](https://github.com/user-attachments/assets/da2e362b-7152-4c46-b9f8-06657af93fa0)

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by remcoros** [comment]
Hello @techrivertree 

ignore the last comment, that is a scammer.

Sparrow on StartOS does not support Cameras and other hardware devices, see: https://github.com/remcoros/sparrow-webtop-startos/issues/11

Sparrow on StartOS through the browser can be considered a 'hot' wallet.

If you need a secure and private setup, I recommend to install Sparrow on your desktop PC and let it connect to your bitcoin core/electrs node.

**Comment by craigraw** [comment]
Thanks for answering @remcoros

**Comment by Evelyn82** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Sparrow Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
