### ISSUE TITLE
Transaction amount field missing- Windows

### ISSUE THREAD

**Issue by AtomicAkorn** [sparrowwallet/sparrow#158]
Using latest Windows version of Sparrow. I noticed when trying to send a transaction out from the wallet the transaction amount field was missing. The only way to send out a transaction was to select and send the entire UTXO.

**Comment by craigraw** [comment]
I can't recreate this. Can you send a screenshot?

**Comment by AtomicAkorn** [comment]
I'm sorry I cannot provide a screenshot. I decided to switch to Linux. The
wallet works perfectly so far on Linux.

**Comment by craigraw** [comment]
Ok - I'm going to close this issue for now then.
