### ISSUE TITLE
[Feature Request] Add Samourai Whirlpool CJ implementation

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#160]
Let's be honest, bitcoin isn't fungible and Lightning doesn't fix this. We will not receive privacy on the base layer and the de facto L2 seems already custodial (e.g. people using exchanges & other KCY services). The risk for bitcoin is to become increasingly centralized around these services and a potential implication thereof is the rehypocation/fractional reserve banking of the coins held on those services. The original cyberpunk promise of bitcoin will be lost.

To counteract this trend and make the ecosystem more resilient against tracking, censorship and financial exclusion, bitcoin needs a widespread use of privacy tools for those still transacting self-sovereign. Today, CJ implementations are a great tool to gain financial privacy and fungibility.

Samourai Wallets implementation 'Whirlpool' has gained a lot of trust the last couple of months (currently 3,640 unspent BTC remixing) and is relatively straight forward to use (compared to e.g. Joinmarket). It is only available on Android though.

For me it would be great to see if Sparrow wallet would implement this solution. I see a couple benefits:

1. First mover advantage for desktop implementation (not counting Wasabi here, as I deem it broken).
2. Increase of privacy for Sparrow wallet users, even if no postmix tools are available at the start. Better a cj without postmix tools as a spend without cj.
3.  Sparrow wallet would earn an income trough the fee sharing and therefore wallet development will become more sustainable.
2. Increase of privacy for Samourai users, as one of the main cons of the implementation is the leaking of xpubs if you use whirlpool without your own dojo node. The sparrow liquidity would almost act like new dojo users and therefore increase the incentives to use whirlpool even further, increasing adoption and with it privacy for both wallet users.
4. General bring cj adoption to a broader user base and help bitcoin stay relevant and free for all going forward.

Coinjoin and financial privacy is not a crime and bitcoiners shouldn't bend the knee to forces suggesting otherwise. 

I'm sure the feature will gain a lot of users once implemented and help to fight against the slowly degrading ethos of bitcoin.

**Comment by craigraw** [comment]
Thanks for the detailed and thoughtful considerations. I concur with you. 

While I don't like to promise features until I'm sure I can implement them, I am currently working with the Samourai team to evaluate the possibility of Whirlpool client support in Sparrow.

**Comment by RequestPrivacy** [comment]
This is great news. I appreciate the effort and hope an implementation will be feasible. I also think that there is a good chance for a little fundraising by the community - specifically for the feature if needed. So please keep us updated.

**Comment by RequestPrivacy** [comment]
Really happy to see whirlpool 2caee79df4d6448a3d30ae6ad6b7f68566bb9fe6 coming to sparrow. Wicked fast! Thanks for your ongoing effort to improve bitcoin!

**Comment by RequestPrivacy** [comment]
Congratulations to the success. I hope users will flock to sparrow and donate or contribute with their mix fees to the sustainability of the project and the work you put in it.

**Comment by craigraw** [comment]
> Let's be honest, bitcoin isn't fungible and Lightning doesn't fix this. We will not receive privacy on the base layer and the de facto L2 seems already custodial (e.g. people using exchanges & other KCY services). The risk for bitcoin is to become increasingly centralized around these services and a potential implication thereof is the rehypocation/fractional reserve banking of the coins held on those services. The original cyberpunk promise of bitcoin will be lost.

Thanks! BTW your OP was well worth rereading.
