### ISSUE TITLE
Add anti-fee-sniping code using nSequence to help improve privacy of off-chain protocols

### ISSUE THREAD

**Issue by chris-belcher** [sparrowwallet/sparrow#161]
I saw on twitter that Sparrow has already implemented taproot single-sig wallets.

Please consider adding privacy-improving code which I suggested on the mailing list: https://gist.github.com/chris-belcher/903feab321bf41055c91eaec46581e89

It will help provide some cover traffic for off-chain protocols like Lightning. If we pull this off we could end up in a great situation where LN channel openings and closings look exactly the same as on-chain taproot transactions. That would be great for the privacy and fungibility of bitcoin.

The BIP proposal contains some pseudocode which hopefully you can just copypaste and translate into your language: https://gist.github.com/chris-belcher/903feab321bf41055c91eaec46581e89#pseudocode

**Comment by craigraw** [comment]
Thanks for suggesting the proposal here - I’ve had it in my inbox for some time but haven’t got to it yet. Will look at this for the next release.

**Comment by craigraw** [comment]
Added in https://github.com/sparrowwallet/drongo/commit/c9e57fad018750a150a563cd17c8872d7cda48f0.

I'll note that currently the pseudocode will not only disable absolute locktime, but disable or enable RBF depending on whether the absolute locktime is set. I believe it would be better to use

```
input.nsequence = 2**32 - 3
```

which would leave locktime and RBF enabled in all cases. The absolute locktime can be set to zero when relative locktime is used.

**Comment by chris-belcher** [comment]
Great work, thanks!

Good suggestion regarding the nsequence value, I've updated the document to have that: https://gist.github.com/chris-belcher/903feab321bf41055c91eaec46581e89/revisions#diff-089b3248b5f1e9b7bccc09e372a83a19f87818a11263087e7961bc999cca2bf2

**Comment by craigraw** [comment]
Great, this is going out with the Sparrow release today.
