### ISSUE TITLE
[Feature Request] Save PSBT as HEX 

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#162]
Samourai Wallet has experimental PSBT support but requires transactions to be imported as hex. 

It would be nice to be able to copy the psbt (in hex) to clipboard also, saving the step of opening the file to copy the text.

**Comment by mflaxman** [comment]
While I think it's lame that Samourai (apparently) doesn't accept PSBT in the standard base64 format, +1 for functionality to copy the psbt to clipboard. Specter-Desktop has this and it's really nice.

For Sparrow testing I've found it annoying to save the PSBT to a file, open the file, copy the contents, and then paste them into a Signer ([`multiwallet.py`](https://twitter.com/mflaxman/status/1321503036724989952) software CLI wallet in my case).

**Comment by craigraw** [comment]
Added in 74b4f51.

<img width="437" alt="Screenshot 2021-08-16 at 08 45 17" src="https://user-images.githubusercontent.com/862166/129522533-1586b8e3-5a54-4e12-869d-6e6df268fbed.png">
