### ISSUE TITLE
Enable `MAX` button before entering wallet address

### ISSUE THREAD

**Issue by CruiseMan** [sparrowwallet/sparrow#165]
I'm trying to swap max available amount using exchange service and i need to know what amount in need to send, i can't enter max and then choose fee amount to see what final amount will be send and use tat number on exchange. Thank you.

<img width="643" alt="Screen Shot 2021-07-28 at 4 44 46 PM" src="https://user-images.githubusercontent.com/15807643/127400281-c59e4777-22b9-43e8-8a8c-416135fc81bc.png">

<img width="828" alt="Screen Shot 2021-07-28 at 4 45 00 PM" src="https://user-images.githubusercontent.com/15807643/127400302-6b8f3565-8b47-4dc4-9b78-efad9d76ab45.png">

**Comment by craigraw** [comment]
Unfortunately this is not technically possible. The address determines the output script, and the length of the output script is required to determine the fee, and the fee determines the max spendable amount.

**Comment by CruiseMan** [comment]
Ok, I see, make sense.
