### ISSUE TITLE
Inconsistancy displaying unit on send and sign transaction page

### ISSUE THREAD

**Issue by CruiseMan** [sparrowwallet/sparrow#166]
I choose `BTC` unit on send page:
<img width="444" alt="Screen Shot 2021-07-28 at 4 52 46 PM" src="https://user-images.githubusercontent.com/15807643/127401575-4b65d328-bc19-4f3e-a453-5258d349e3b6.png">

But on create transaction page amount displayed in `sats`. For a sake of double check i expected to see `BTC` amount or even both as an improvement.
<img width="306" alt="Screen Shot 2021-07-28 at 4 51 00 PM" src="https://user-images.githubusercontent.com/15807643/127401444-cfebfc71-3449-4c92-a933-9b42afa83487.png">

**Comment by craigraw** [comment]
If you'd like to see all amounts in BTC, choose the `View > Bitcoin Unit > BTC` option in the menu. The dropdowns next to the amount fields are just for convenience so you don't have to do a conversion externally when the amount is supplied to you in a different unit to the one you have configured Sparrow for.
