### ISSUE TITLE
Feature request: quick-link to Server settings

### ISSUE THREAD

**Issue by statusquont** [sparrowwallet/sparrow#167]
Feedback from an edge-case user FWIW:

I am nomadic. I run myNode via VirtualBox, and connect Sparrow to it (Private Electrum Server). As such my node's IP is always changing with every new location I am in. Vbox uses Bridge Adapter so the host machine can get an IP from the router for the Virtual Machine (i.e. the node).

I was thinking it might be nice if in Sparrow, the connection toggle switch in the lower-right corner also provided a quick-link to the server settings panel. It would only need to be visible when Sparrow can't connect to the server. That way if Sparrow couldn't connect to the server, a clickable link/button would show up there that would open the Preferences window and Server tab so I could update the IP with one click. It would also be useful for "normal" users if there was ever a connection issue to quickly jump to the area most likely to provide the solution to fix the connection.

**Comment by 6102bitcoin** [comment]
Proposal: Quick link to server settings upon connection error.

Benefit: Saves 3 mouse clicks (File > Preferences > Server > Edit) becomes (View Server Settings > Edit)

Drawbacks: More code, users may jump to editing server settings rather than trying to connect again?

**Comment by craigraw** [comment]
Added in 4e4fd75. On connection failure, the status bar will now contain a link that will pop up the server preferences:

<img width="460" alt="Screenshot 2022-02-07 at 14 06 41" src="https://user-images.githubusercontent.com/862166/152785417-539905e4-6ca8-435d-9d30-192794e10ae9.png">
