### ISSUE TITLE
Feature request: Exporting the UTXO table to CSV

### ISSUE THREAD

**Issue by xavierfiechter** [sparrowwallet/sparrow#169]
![Screenshot 2021-08-09 at 11 22 57](https://user-images.githubusercontent.com/31884704/128685154-b0802d83-4bd0-46d8-9d02-2065a5e2f915.png)

**Comment by craigraw** [comment]
Thanks - already implemented in https://github.com/sparrowwallet/sparrow/commit/fc9cdaabb4b7b602dfd93b26d1fc53a2e92144b2 :)
