### ISSUE TITLE
Ability to remove inputs from the send screen

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#17]
Would be nice to have the ability to remove inputs when creating a transaction. This would make it faster if the user doesn't want to select UTXOs in the separate screen.

It would also help users to be more privacy focused and induce more discipline in the labeling.

![Group 26192](https://user-images.githubusercontent.com/807505/93930848-fd92ec80-fceb-11ea-90ce-5444c44effb7.png)

**Comment by pedromvpg** [comment]
It would also be really helpful to have some labeling for inputs and outputs, and also call out how many sats on each available input.

![Group 26192](https://user-images.githubusercontent.com/807505/93931952-75ade200-fced-11ea-9252-c406d3c85bab.png)

**Comment by craigraw** [comment]
Thanks for the ideas. With the first one, is the intent that removing an input would allow other UTXOs from the wallet to be included (as per the coin selection algorithm), or that a "locked" coin selection of only the remaining UTXOs currently selected is set?

Regarding labelling inputs (and outputs), you can do this in a number of places (Transactions, Addresses and UTXOs tabs). The UTXOs tab is probably the most sensible place to do it for inputs to a transaction - just click on a Label cell in the table to edit. 

The sats amount is available on the tooltip for the input - I'm nervous of trying to put too much onto the diagram, as the amount labels can get quite long. As a thought, possibly clicking on input label could switch between showing the labels and showing the amounts?

**Comment by pedromvpg** [comment]
Got it!

Removing outputs would be helpful in case the algorithm ends up selecting UTXOs the user doesn't want to spend. So it would just select the next best one. Or maybe it could show a modal asking if the user wants to **Remove Input** or **Remove and Auto Replace Input**. If blacklisting of UTXOs is added then maybe this is overkill.

More labeling in the Send screen was mostly for labeling the diagram (i.e. inputs/outputs titles) just to educate the user. Hoping to have other people use this wallet to learn and better understand bitcoin under the hood. It's not directed and labeling the UTXOs themselves.

Didn't see the tooltip, but see it now that I left my curser static for longer. Maybe it could be made to show more immediately.

**Comment by craigraw** [comment]
Added the ability to remove UTXOs directly from the transaction diagram in https://github.com/sparrowwallet/sparrow/commit/eb0907660492f068fdd4288821e9ac21a953bba5. This works as you would expect - removing UTXOs causes other UTXOs to be selected to meet a given spend target, unless the user is looking to spend all UTXOs or a selected set of UTXOs, in which case the spend amount reduces as the UTXO is removed from the set.

Tooltip delay has been greatly reduced on the diagram too (https://github.com/sparrowwallet/sparrow/commit/2cb667a67106621466e9379721676409d208c0c6).
