### ISSUE TITLE
Display spend address on `Send` page 

### ISSUE THREAD

**Issue by CruiseMan** [sparrowwallet/sparrow#171]
I would like to see spend address, the reason for this was I have one UTXO with lets say 0.01 BTC and was trying to send 0.0005 and it used 2 more UTXO and this big one in order to collect necessary amount. But currently I take back and forth to figure out with one need be be remove in order to spend from `big` UTXO only. This improvement can make my life much easier.

Visual example when desire address added in front of `self (change)` and maybe add address balance  ?
<img width="631" alt="Screen Shot 2021-08-12 at 7 19 15 PM" src="https://user-images.githubusercontent.com/15807643/129281990-61ca02f5-d2c7-4282-a603-ac6ddb632d0c.png">

app 1.4.3

**Comment by craigraw** [comment]
The address is shown in the tooltip for that UTXO. Unfortunately, space constraints make it difficult to add the address to the label itself (note that there are additional elements that may appear to the left of the diagram).

**Comment by craigraw** [comment]
Closing this off.

**Comment by CruiseMan** [comment]
Ok ok, my firth emotion was to delete Sparrow after this, but unfortunately no better alternatives. I still need to find a way to precisely spend UTXO's

**Comment by craigraw** [comment]
Glad you stuck around :)

Why not use the labelling functionality on UTXOs, or the tooltips as mentioned above?

Note the problem with using addresses to identify UTXOs is that you can have more than one UTXO sent to an address, so it's not definitive.
