### ISSUE TITLE
SQL label column format change in 1.4.3 does not allow wallet to open

### ISSUE THREAD

**Issue by ChesterMcRacken** [sparrowwallet/sparrow#173]
Have wallet which functioned perfectly in versions prior to 1.4.3.  When upgraded to 1.4.3 wallet will not open with error:

org.h2.jdbc.jdbcSQLDataException: Value too long for column "label CHARACTER VARYING(255)"

Maybe the column in table containing the labels was changed and not compatible with wallets created in prior versions which had long labels input by user. 

By rolling back to 1.4.1 the wallet opens again no problem.

**Comment by craigraw** [comment]
Thanks for the feedback - this is likely caused by a very long label in the wallet. It is a bug however, and Sparrow should check and trim long labels before persisting them.

**Comment by craigraw** [comment]
Label truncation added in 8f7f0d4.
