### ISSUE TITLE
Unable to import Unchained Capital JSON

### ISSUE THREAD

**Issue by AtomicAkorn** [sparrowwallet/sparrow#174]
I am unable to import my 2/3 unchained capital multisig vault json wallet config file. When I attempt to import in sparrow it gives an error and the error detail is in regards to the string 'unknown'. Looking at the config file I noticed that the unchained xpub doesn't have a derivation path indicated only 'unknown'.

**Comment by craigraw** [comment]
This issue has now been fixed, but not released yet. For now, you can edit the export file to make the derivation path the same as the others - it won’t affect the wallet functionality since you won’t be signing with that keystore.
