### ISSUE TITLE
Add font size in Settings

### ISSUE THREAD

**Issue by icreator** [sparrowwallet/sparrow#175]
Please add font size in Settings!

**Comment by craigraw** [comment]
Can you describe the need for this in more detail?

**Comment by icreator** [comment]
Add selection of Font Size for all application in settings.

the font of the text is very small now  ((

**Comment by craigraw** [comment]
Could this be useful? https://www.sparrowwallet.com/docs/faq.html#sparrow-icons-and-text-are-tiny

**Comment by icreator** [comment]
> Could this be useful? https://www.sparrowwallet.com/docs/faq.html#sparrow-icons-and-text-are-tiny

set up font size for all aplications? - bad idea

**Comment by 6102bitcoin** [comment]
The suggestion by craig would make the program usable. That said, I appreciate that you may not wish to change the global settings. Typically there is a way to adjust scaling of individual programs, though this is OS/distro dependent. 

Can you include details about the display resolution, platform (Ubuntu, Windows 10 etc) and ideally a screenshot showing the scaling. 

If you are on windows try [this](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display) suggestion from stackoverflow:
1. Find sparrow.exe you installed.
2. Right click -> Properties
3. Go to Compatibility tab
4. Check Override high DPI scaling behavior.
5. Choose System for Scaling performed by:

**Comment by willcl-ark** [comment]
Hey all, I see a similar issue on Sparrow Wallet 1.5.2, on a fresh Ubuntu 21.04 install with a 4k (well, technically UHD) monitor scaled to 200%:

![sparrow_display_settings_ubuntu](https://user-images.githubusercontent.com/6606587/141006427-2421d71f-af2c-4785-853e-e7c219a7713a.png)

![sparrow_font_scaling_issue](https://user-images.githubusercontent.com/6606587/141006447-260a553b-a247-46e8-9424-b1a7b50e65d2.png)

Fonts are much smaller than system fonts, shown in title and menu bars for context.

Let me know if you are going to look into this further and need any more info :) FWIW it is still usable at this size, for me.

**Comment by willcl-ark** [comment]
So, if I run the installed binary as root like:

```
sudo su
GDK_SCALE="2.0" /opt/sparrow/bin/./Sparrow
```

Sparrow respects the Java scaling env var:

![sparrow_correct_scaling](https://user-images.githubusercontent.com/6606587/141011398-9b9df444-4e21-4629-bc14-e2609fcd7b50.png)


However as regular user (installed binary via `sudo dpkg -i sparrow_1.5.2-1_amd64.deb`) it does not respect the env var, no matter how exported.

So support seems innately ready in the GUI library, but perhaps a quick fix is to check the shell for that var using `System.getenv`?

**Comment by craigraw** [comment]
Thanks for the reporting. Will try to see if I can introduce a command line parameter to change the scaling percentage.

**Comment by craigraw** [comment]
This turns out to be more difficult than anticipated, but there is a workaround. The correct setting for scaling a JavaFX application on Linux is `glass.gtk.uiScale`. The GUI library (JavaFX) reads this variable from the JVM options or environment variables before any Sparrow code runs, so I can't introduce it as a command line option. Also, although a named parameter with dots is standard for Java, it is not easy to add in a Unix shell. There is a bug open for this [here](https://bugs.openjdk.java.net/browse/JDK-8153911).

However, there is a way to do it:
```shell
env "glass.gtk.uiScale=200%" bash
/opt/sparrow/bin/Sparrow
```

I found that this worked on my Ubuntu system. If anyone can think of an improvement, please share.

**Comment by craigraw** [comment]
A further note - the correct setting for Windows is `glass.win.uiScale`.

Setting this environment variable in Windows is straightforward via the System settings. Note that like the Linux one it can be set to a percentage (`200%`), a decimal (`2.0`) or a DPI (`192dpi`).

**Comment by willcl-ark** [comment]
> This turns out to be more difficult than anticipated, but there is a workaround. The correct setting for scaling a JavaFX application on Linux is `glass.gtk.uiScale`. The GUI library (JavaFX) reads this variable from the JVM options or environment variables before any Sparrow code runs, so I can't introduce it as a command line option. Also, although a named parameter with dots is standard for Java, it is not easy to add in a Unix shell. There is a bug open for this [here](https://bugs.openjdk.java.net/browse/JDK-8153911).
> 
> 
> 
> However, there is a way to do it:
> 
> ```shell
> 
> env "glass.gtk.uiScale=200%" bash
> 
> /opt/sparrow/bin/Sparrow
> 
> ```
> 
> 
> 
> I found that this worked on my Ubuntu system. If anyone can think of an improvement, please share.

Thanks Craig. I'll test this out when I'm next back and just set an alias if it works :)

**Comment by craigraw** [comment]
Added this information to the relevant FAQ: https://sparrowwallet.com/docs/faq.html#im-running-on-a-high-resolution-screen-and-sparrow-icons-and-text-are-tiny

**Comment by craigraw** [comment]
A slightly easier way to do it in Linux (updated in the FAQ):

```shell
 _JAVA_OPTIONS=-Dglass.gtk.uiScale=200% /opt/sparrow/bin/Sparrow
```

Closing this off as solved.

**Comment by BitcoinMechanic** [comment]
Launching the app with CLI args is a bit hacky. I'm not used to desktop applications not having the ability to resize within the app themselves. Seems like an obvious oversight?

Honestly needing a magnifying glass to use Sparrow has been a big reason I have not wanted to make it my daily driver.
