### ISSUE TITLE
Unable to import SeedSigner xpub from QR code

### ISSUE THREAD

**Issue by AtomicAkorn** [sparrowwallet/sparrow#178]
Unable to import xpub QR code from SeedSigner. Error message appears saying the QR code is not a PSBT.

**Comment by craigraw** [comment]
Could you provide detail on the series of steps to reproduce? (on the SeedSigner and Sparrow)

**Comment by AtomicAkorn** [comment]
Seedsigner

- Seed Tools > Generate a seed with image > save 24 word seed phrase to slot#1
- Seed Tools > Generate xpub > use seed slot#1 > load xpub QR code

Sparrow
-New wallet > 2/3 multisig native segwit
-Keystore1 > airgapped hardware wallet > Under seedsigner option scan button to scan seedsigner xpub qr code
message generated "Parsed QR parts were not a PSBT or transaction"

![IMG_20210822_113054](https://user-images.githubusercontent.com/87580695/130366995-a14564e1-9405-4c63-9d63-f80d9bf06334.jpg)

Linux operating system used

**Comment by craigraw** [comment]
Figured out the problem here - you need to change the wallet to Sparrow Wallet in the Settings of SeedSigner.

That said, I've now made Sparrow support the Specter Desktop default as well.
