### ISSUE TITLE
Open/Import Wallet is Very Confusing

### ISSUE THREAD

**Issue by mflaxman** [sparrowwallet/sparrow#18]
`Open Wallet...` throws an unhelpful error if trying to import a wallet:
![Screen Shot 2020-09-24 at 4 35 25 PM](https://user-images.githubusercontent.com/448644/94203006-57c6b580-fe84-11ea-9a08-e34988810818.png)

It does work if you go to `Import wallet` instead.

As a UX feedback, it was really confusing that I was even supposed to be in the File menu. I was trying to paste in a script descriptor here (that field seems read only):
![Screen Shot 2020-09-24 at 4 35 07 PM](https://user-images.githubusercontent.com/448644/94203231-a83e1300-fe84-11ea-82f3-0bc7c6fb9f8c.png)

I spent a while on this and nearly abandoned altogether!

Also, it'd be great if I could just paste in the descriptor (from Specter) instead of saving it to a file and then passing that file to sparrow.

**Comment by craigraw** [comment]
I agree the UX could be better here. What I propose is adding an Edit button on the right of the Descriptor field which allows you to view and edit the full output descriptor:

<img width="801" alt="Screenshot 2020-09-25 at 12 19 31" src="https://user-images.githubusercontent.com/862166/94256067-7f238e00-ff29-11ea-9e74-11c7948b01d8.png">

I'll have a look at improving the error message on Open Wallet as well.

**Comment by craigraw** [comment]
Implemented in https://github.com/sparrowwallet/sparrow/commit/ead8fa2207c513c8f38d7cd7eedd324067911585

**Comment by craigraw** [comment]
Sparrow will now on File > Open attempt to import the provided file if it does not recognise it as a Sparrow wallet. The attempt includes all current wallet import types: Coldcard singlesig (JSON), Coldcard multisig (TXT), Electrum (JSON and encrypted), and Specter (JSON). Implemented in f949bcc

Thanks for the UX feedback - it would be great to get more in this area.

**Comment by craigraw** [comment]
Open wallet error dialog messaging improved in 3a885b3.

**Comment by craigraw** [comment]
Closing this off, all changes released in 0.9.5.
