### ISSUE TITLE
Don't create a blank Bitcoin Core wallet without prompt

### ISSUE THREAD

**Issue by Sjors** [sparrowwallet/sparrow#181]
As of v0.22.0 (maybe earlier) Bitcoin Core no longer creates a default wallet. You can try it using the new pre-release: https://bitcoincore.org/bin/bitcoin-core-22.0/

When using Sparrow with that node it spontaneously creates a "sparrow" wallet when you connect. That's probably not a good idea, also because having 2 wallets is a more confusing experience.

**Comment by craigraw** [comment]
Indeed, I think not creating the default wallet already began in 0.21. I discussed this with BWT's developer, @shesek (BWT provides Sparrow with an Electrum interface to a Bitcoin Core wallet). Our conclusion at the time was that given BWT adds a bunch of watch-only addresses, it made more sense to keep them in a separate wallet by default so there was no confusion or risk of conflict. The default wallet can be used by untoggling the "Multi-Wallet" setting in the Bitcoin Core panel for the Server Preferences.

That said, by the title of this issue do you mean Sparrow is also creating a blank default wallet, in addition to the "sparrow" wallet?

**Comment by Sjors** [comment]
> The default wallet can be used by untoggling the "Multi-Wallet" setting in the Bitcoin Core panel for the Server Preferences.

Untoggling that only makes sense for people who install a fresh node, not if you already have some core wallets. I think?

> That said, by the title of this issue do you mean Sparrow is also creating a blank default wallet, in addition to the "sparrow" wallet?

No, it only created a "sparrow" wallet. This is a watch-only legacy (i.e. non-descriptor) wallet. Since it doesn't have private keys, at least there's no risk for the user to accidentally send money to it, but it still seems confusing.

**Comment by craigraw** [comment]
It should not - I've made a change in 8f63d89 that should avoid creating a Core wallet when no Sparrow wallets are open.

**Comment by craigraw** [comment]
Turns out this change is actually causing testing the connection to fail when the configured wallet doesn't exist. I'm going to undo this change.

**Comment by craigraw** [comment]
Change reverted in 395e90e. 

> When you first start Sparrow and connect to your node, is there any reason at all to automatically create a wallet?

I've come to realize that my original answer to this was incorrect. Sparrow needs to create the Bitcoin Core wallet it is intending to use, otherwise it cannot know if the connection is truly successful.

I'm going to close this off, I don't think there is any further work to be done here.

**Comment by Sjors** [comment]
> it cannot know if the connection is truly successful.

How so? There are plenty of other RPC methods to check the connection with.

**Comment by craigraw** [comment]
Indeed, but my interface is via BWT which really just one method, albeit somewhat configurable. The idea is to test that BWT can function correctly, which means ensuring the wallet BWT is configured to use either exists or can be created.
