### ISSUE TITLE
 PKIX path validation failed when connecting to Electrum

### ISSUE THREAD

**Issue by mandelbit** [sparrowwallet/sparrow#185]
All of a sudden I'm getting the following error when connecting to electrs running on a local node. Is this a TLS cert issue? As far as I know none of the certificates on the node side have changed. Please can someone push me in the right direction for debugging.

```
Could not connect:

PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed

PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
```

**Comment by craigraw** [comment]
Yes, this is a TLS issue. 

Check the relevant certificate file in the `certs` folder in your Sparrow home folder (likely `~/.sparrow/certs`). You can delete this file and Sparrow will recreate it when it next connects to electrs.

**Comment by mandelbit** [comment]
Worked a charm, thanks Craig
