### ISSUE TITLE
Ledger HW imported UTXO - error sending coins

### ISSUE THREAD

**Issue by captJiri** [sparrowwallet/sparrow#186]
Connected my Umbrel Node to Sparrow. Imported my Ledger HW UTXO into Sparrow wallet and could see the balance in Sparrow. Got error about "fetching utxo" while trying to send coins from sparrow to another wallet. I had to first move/send these coins from Ledger Live desktop app. Thenafter i could send utxo also from sparrow wallet. Is that ok? How to, in case, proceed with HW + Sparrow Seed Recovery ? Many thanks for reply.

**Comment by craigraw** [comment]
Having never owned a Ledger (they don't provide sample devices to developers) I'm less familiar with it. That said many people use Sparrow with Ledger without issues. I assume the Ledger was imported into Sparrow as a Connected Hardware Wallet?

Was the error in Sparrow or Ledger, and can you describe what action you were taking when it occurred? If that's in the past now, then I think all is ok if you can send coins out (ie the Ledger can sign transactions). Would need to understand more to help further.

**Comment by captJiri** [comment]
Thanks for reaction. Yes there are no problems now, Sparrow works excellent with HW Ledger wallet. The 1st synchronization between Ledger HW and Sparrow (via USB) was also w/o any problem ane went excellent. 

The mentioned Error occured when i tried to make 1st transaction and send synced HW UTXO directly from Sparrow to any other wallet ... it was not possible. So i did following - I used the original app Ledger Live Desktop + HW and sent some test UTXO to my node. Then I sent this test UTXO back but this time directly to Sparrow wallet. Since that, I could sent UTXO directly from Sparrow using HW Ledger w/o problems, worked and works good now. So seems like Sparrow could not send the HW UTXO originated via different Desktop app (ledger live) or smthg so ...

But this all brings me to this main question: If I had to use f.ex. recovery seed i would use it for Ledger Live app - as Sparrow does not support recovery seed - but would it work when there is UTXO in Sparrow not in Ledger Live anymore .. ? This i could test like sending out UTXO from Ledger Live app now, when it was sent directly to Sparrow... Do I understand correctly that Sparrow works as a bridge wallet between node and other wallet (incl. HW wallet) ? Or can i proceed with seed in Sparrow - as i have not seen any function for that in the menu ... ? 
Hopefully i managed to explain more to you, many thanks.

**Comment by craigraw** [comment]
Actually, Sparrow does support using your recovery seed. From [this reading](https://www.ledger.com/academy/crypto/what-is-a-recovery-phrase) I see that Ledger supports a standard called BIP39. You can create a BIP39 based wallet in Sparrow, Ledger or any other hardware wallet. In Sparrow, this is called a Software Wallet. If you create a new wallet, choose Software Wallet (the 3rd button in the row on the Settings tab) and then select the number of words from the BIP39 option in the dialog that pops up, you should be able to recreate your wallet in Sparrow.

> Do I understand correctly that Sparrow works as a bridge wallet between node and other wallet (incl. HW wallet) ?

Yes correct. We generally use the term coordinator to describe this function.

**Comment by craigraw** [comment]
Closing this off as solved.
