### ISSUE TITLE
Error creating wallet using illegal characters

### ISSUE THREAD

**Issue by B-396** [sparrowwallet/sparrow#187]
Creating a new wallet with an illegal character (e.g. "testWallet*") on Windows, leads to the following error:
![2021-09-04 17_30_42-Wallet Name](https://user-images.githubusercontent.com/17456997/132138965-38dcb692-11ae-4950-97d1-62a784418c03.png)
![image](https://user-images.githubusercontent.com/17456997/132138996-d9483570-2c4d-4c9f-847a-8ad10a183e4a.png)

**Comment by craigraw** [comment]
Thanks for the bug report. Fixed in ed2914f. The wallet name dialog will now replace illegal characters with underscores.
