### ISSUE TITLE
[minor] `Test Connection` fails when `User/Pass` selected

### ISSUE THREAD

**Issue by CruiseMan** [sparrowwallet/sparrow#189]
Must be an easy fix, just handy to stay on `User/Pass` view testing different users credentials, small thing but annoying, sorry for picking on it. pass and login empty credentials by default

<img width="538" alt="Screen Shot 2021-09-06 at 11 26 39 PM" src="https://user-images.githubusercontent.com/15807643/132295046-b3b9fab0-c385-4ab4-a226-fb587b5544a2.png">
<img width="554" alt="Screen Shot 2021-09-06 at 11 27 03 PM" src="https://user-images.githubusercontent.com/15807643/132295052-09fa69e1-3db5-488f-b897-8b235970f7fb.png">

**Comment by craigraw** [comment]
I'm probably misunderstanding what you mean, but in the second screenshot the Test Connection is failing because the User / Pass details aren't filled in?

**Comment by CruiseMan** [comment]
> I'm probably misunderstanding what you mean, but in the second screenshot the Test Connection is failing because the User / Pass details aren't filled in?
Test Connection is failing while User/ Pass tab selected, when select Default it connects.

**Comment by craigraw** [comment]
What I mean is - when you select the User/Pass tab, you need to fill in the two textfields immediately below it with those details from `bitcoin.conf`.

**Comment by CruiseMan** [comment]
> What I mean is - when you select the User/Pass tab, you need to fill in the two textfields immediately below it with those details from `bitcoin.conf`.

That the thing, there are no credentials for RPC in `bitcoin.conf`

**Comment by 6102bitcoin** [comment]
I have just tested and can confirm the above; if rpcuser & rpcpassword are not set in bitcoin.conf sparrow will not connect. 

FYI Specter wallet does connect when these parameters are not set, I am not clear how but it is likely in [this](https://github.com/cryptoadvance/specter-desktop/blob/cb8968b5fb6cde5e92c8c2bbcf7643a5454b59ba/src/cryptoadvance/specter/rpc.py) python script.

**Comment by craigraw** [comment]
Implemented in 3e47a49. Sparrow will now default to cookie auth when user/pass are not filled in.
