### ISSUE TITLE
Poor rendering of the font on Mac Os

### ISSUE THREAD

**Issue by D4nte** [sparrowwallet/sparrow#19]
Is it possible to improve the font rendering on mac os? I downloaded the binary from the website.

![image](https://user-images.githubusercontent.com/300805/94261690-a142fd80-ff75-11ea-98c1-4d75c88b4ca0.png)

**Comment by craigraw** [comment]
This is unfortunately an upstream JavaFX bug when running on OSX Catalina. Text renders poorly on non-retina displays. There is an open bug report on this: https://bugs.openjdk.java.net/browse/JDK-8236689

Does it look ok on your Retina display?

**Comment by D4nte** [comment]
> This is unfortunately an upstream JavaFX bug when running on OSX Catalina. Text renders poorly on non-retina displays. There is an open bug report on this: [bugs.openjdk.java.net/browse/JDK-8236689](https://bugs.openjdk.java.net/browse/JDK-8236689)
> 
> Does it look ok on your Retina display?

Yes indeed, it looks good on the retina display!

**Comment by 6102bitcoin** [comment]
Outstanding Action: Monitor openjdk issue and update when fixed
Proposed Priority: Low

**Comment by 6102bitcoin** [comment]
Still marked as unresolved. 
https://bugs.openjdk.java.net/browse/JDK-8236689

Last updated 2021-07-13 (2+ months ago).

**Comment by craigraw** [comment]
I'm going to reopen this, as it's still an issue that comes up occasionally, and I hope is addressed.

**Comment by craigraw** [comment]
Fixed in 63259a2. The characters on an external non-retina screen in OSX are still a little close together, but there is a substantial improvement in rendering. Reference: https://github.com/openjdk/jfx/pull/642

![Screenshot 2021-10-14 at 09 54 42](https://user-images.githubusercontent.com/862166/137275317-b838a514-0d9e-46fe-9ad8-e5a83cdfecee.png)
