### ISSUE TITLE
Change addres failure

### ISSUE THREAD

**Issue by Szczerbo** [sparrowwallet/sparrow#190]
When I send some BTC, I can't choose "change address" to be the same as the one which I used to spending. Ofcourse I understand security issues but user have to have possiblity to choose this as an option.

Maybe this is somewhere in .config file but can't find this option. Any ideas or hints?

Greetings:)

**Comment by craigraw** [comment]
Greetings :)

Sparrow specifically doesn't allow choosing an already used address (reuse of addresses is bad for privacy) but you can select the next unused address (and so on) by clicking on the down arrow which appears when you hover over the change output in the transaction diagram on the Send tab.

**Comment by Szczerbo** [comment]
Unfortunately, this is a requirement of the law regulator - have to be transparent (I am providing one address that is monitored by the law regulator). Unfortunately, if there is no such option and you won't add it in the near future, I will have to abandon Sparrow;(

**Comment by craigraw** [comment]
That is an unfortunate requirement! Sorry to hear.

You can achieve what you are looking for by adding a second payment to the transaction (see the Add button) and specifying the change address there, with the appropriate amount. In this case Sparrow won't create an actual change address output - you will just have the two payments.

**Comment by Szczerbo** [comment]
Seems that this workaround may work for me - but still would be great to do one transaction and pay once for transfer:) 
Please take this into consideration creating publine for Sparrow (I can wait a bit:) ). Love Sparrow and its functionality with simplified view (not like many other unnecessary complicated solutions).

**Comment by craigraw** [comment]
With this approach you won't pay any more - it's just a bit more laborious to create the transaction.

I think it's unlikely Sparrow will ever promote easy address reuse - too many issues! For this reason I'm going to close this one off. Thanks for sharing your use case though.
