### ISSUE TITLE
Provide instructions of complete repo cloning via https

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#199]
### Description
During the current "reproducible build" debate in issue #188 and #192 I kept wondering if it is possible to enable a cloning of the repository via the https method. The instructions in the `readme.md` and `reproducible.md` just use ssh which may be a barrier for people who want to try building sparrow and haven't yet looked into ssh, don't have a Github account or want to test different build environments e.g in VMs without the hassle to transfer or add ssh-keys for those environments.

### Actions taken
I tried `git clone --recursive https://github.com/sparrowwallet/sparrow.git` which works for all but the drongo submodule. The folder remains empty as a ssh connection fails to establish. In a short research I haven't found how to tackle the problem to include the submodule for https.

### Solution
Add instructions in `readme.md` and `reproducible.md` for a complete https clone incl. the drongo submodule.

**Comment by craigraw** [comment]
Fixed in 4f9b87b. Sparrow can now be recursively cloned with 
```
git clone --recursive https://github.com/sparrowwallet/sparrow.git
```
as well as
```
git clone --recursive git@github.com:sparrowwallet/sparrow.git
```

README updated to reflect this in ca1f934.

**Comment by RequestPrivacy** [comment]
It seems it still tries to clone via ssh into the drongo module. Not sure why it can't pull it with https?

![g58](https://user-images.githubusercontent.com/72392544/134382812-a392fe49-5760-4cca-a796-2b0236297c49.png)
note: I denied a further cloning although I have ssh keys. That's why the agent at the end isn't happy.

**Comment by craigraw** [comment]
This is because you're checking out on a tag (1.5.0-beta1) which precedes the fix above. The next release will have the fix as a previous commit.

**Comment by RequestPrivacy** [comment]
Aaaaah embarrassing, sorry for that. I should have given a thought or two before raising the question.
