### ISSUE TITLE
Error connecting Ledger to Multisig

### ISSUE THREAD

**Issue by MsFloofie** [sparrowwallet/sparrow#2]
Trying to add my Ledger Nano S to my 2-3 MultiSig. Whenever I scan for hardware wallets (The ledger is unlocked and on the bitcoin app) I receive this error message: 
![2020-09-02_21-08](https://user-images.githubusercontent.com/61802657/92060337-75ab6980-ed61-11ea-8c96-14557b6578b9.png)
I do not know what is causing the problem, nor any solution on how to fix it.

**Comment by resipsadude** [comment]
Same error here.

**Comment by craigraw** [comment]
Fix coming soon.

**Comment by craigraw** [comment]
Should be fixed in 0.9.3: https://github.com/sparrowwallet/sparrow/releases/tag/0.9.3

I don't have a Ledger to test against though, so feedback would be appreciated.

**Comment by MsFloofie** [comment]
It is fixed! Thank you so much

![2020-09-03_18-55_Sparrow](https://user-images.githubusercontent.com/61802657/92180846-fcba1980-ee15-11ea-928c-0c1802e38ae1.png)
![2020-09-03_17-36](https://user-images.githubusercontent.com/61802657/92180847-fd52b000-ee15-11ea-9e3e-8f27b126caa4.png)
