### ISSUE TITLE
[Feature request] Add milibitcoins as an option for "Display unit"

### ISSUE THREAD

**Issue by dsmid** [sparrowwallet/sparrow#201]
Can you please add milibitcoins support?
Sats are too small and BTC too huge. mBTC would be a great compromise.
![image](https://user-images.githubusercontent.com/3982431/133449856-4a33c082-45e9-414b-8fee-ec55e1e48951.png)

**Comment by craigraw** [comment]
This is one time where I'd like Sparrow to be somewhat opinionated - I think promoting satoshis as a standard denomination reduces confusion in the long run. Granted the numbers are quite large right now, but that's likely to change :)
