### ISSUE TITLE
Switching from `Multi Signature` to `Single Signature` loses keystore for both

### ISSUE THREAD

**Issue by CruiseMan** [sparrowwallet/sparrow#202]
I had originally created restore and later on decided to create a multi sig signature, but after it was created I wanted to switch to single signature and I don't see `keystone` anymore. After app restarted multi sig keystrokes restored. Refresh wallet `Cmd+R` doesn't restore keystores.

https://user-images.githubusercontent.com/15807643/133574721-5662f91c-45b4-4dc6-916e-c7ea037d0d89.mov

**Comment by craigraw** [comment]
This is the intended behaviour. Changing the wallet policy is a major change, and so clears the keystore details to allow new keystores to be added.

If you want to go back, the Revert button at the bottom returns everything to the original state (as opposed to the Refresh Wallet command which refreshes the transactions for the wallet).

**Comment by CruiseMan** [comment]
Thank you Craig as always, sorry for annoying questions, unfortunately can’t help with code but maybe I can order you some pizza or coffee ?

**Comment by craigraw** [comment]
No problem, and thanks for the message - these Github issues can be a bit dry :)
