### ISSUE TITLE
scan using built-in iSight camera crashes

### ISSUE THREAD

**Issue by citizenanalog** [sparrowwallet/sparrow#204]
Running mac os Sierra 10.12.6, Sparrow 1.4.3

When trying to scan an image for new wallet creation of air-gapped wallet, if 'built-in iSight is selected' the program crashes.

Using a USB webcam works, anytime built-in iSight is selected the program crashes.

**Comment by craigraw** [comment]
Can you share the crash log, or an excerpt from it?

**Comment by citizenanalog** [comment]
Fixed by disabling 'Use HD Capture' in the Ribbon Toolbar (View -> Use HD Camera Resolution).
