### ISSUE TITLE
Unable to import testnet wallet using vpriv

### ISSUE THREAD

**Issue by indcyfa** [sparrowwallet/sparrow#206]
I'm trying to recover a testnet wallet from an xpriv with a known balance. Derivation path of xpriv is m/84'/1'/0'. 

I convert xpriv to vpriv using https://3rditeration.github.io/btc-extended-key-converter/. I start Sparrow in testnet mode and import it  via `Software wallet | Master private key | Enter private key`. However the resulting wallet has the incorrect vpub and no balance. When importing the exact same vpriv into Electrum I see the correct vpub and balance.

**Comment by craigraw** [comment]
I think the problem here is that you are working with a derived `xprv`, but Sparrow is expecting a master `xprv`. Do you have the master `xprv`?

If not, here's one way to a least get a watch only wallet - get the `bx` tool from https://github.com/libbitcoin/libbitcoin-explorer (no binaries provided unfortunately).

Then
```
bx hd-to-public xprv......
```

This will provide an `xpub`. Take the result to https://3rditeration.github.io/btc-extended-key-converter/ and convert to `tpub`. Then create a watch-only wallet in Sparrow and use the `tpub`, master fingerprint `00000000`.

Unfortunately supporting derived `xprv` values in Sparrow is unlikely - it's a niche case and would require a lot of additional work.

**Comment by indcyfa** [comment]
Hi @craigraw 

I'm trying to recover a SLIP-0039 backup in Sparrow with coins at derivation `m/84'/1'/0'`. Using Ian Colemans tool https://iancoleman.io/slip39/ I enter the required shares and get the 'Master secret' - 32 hex chars. I plug this value into https://iancoleman.io/bip39/ as the 'BIP39 seed'. If I then take the 'BIP32 Root Key' xpriv, convert to vpriv (P2WPKH on testnet) and import into Sparrow running in testnet mode I see 0 balance (same result with electrum). 

However if I use a custom derivation path with https://iancoleman.io/bip39/ by selecting BIP32 tab and `m/84'/1'/0'` and then take the resulting 'BIP32 Extended Private Key' xpriv and convert it to vpriv and import it into Electrum I see the expected balance. But not so with Sparrow.

**Comment by craigraw** [comment]
>  import it into Electrum I see the expected balance. But not so with Sparrow.

I assume the vpubs are different? See if there is any difference if you use Wallet > Information in Electrum versus the value in the Sparrow Settings tab (you can switch between tpub/vpub with the double arrow button on the right).

I've tried doing everything you've described and have ended up with the same xpub/tpub/vpub values. 

For example:
BIP32 Root Key (tprv/vprv)
```
xprv9s21ZrQH143K2RfaQCVLW9ofoonRoYzEKHeAz2mHah3sZ6V77dikFqoXHYUSxJskpiuopx5EtH7nd3dkosp7DMak8DUhUoYpuUY6vJGRyLR
vprv9DMUxX4ShgxMKqHLjUv65ycfTsVXvK1EV4bjREyWpgJ7StrecKPd1iVFF8ZGxVZv1SgCKzt7xxQgrUQdNUz5ctDYPY5rJyurN2Qp98CXQc9
```

converts to the following xpub/tpub/vpub at `m/84'/1'/0'`:
```
xpub6Bzp39czf8w4qdkc64h2RGbi4Xy7pjQ6RaVJm5Ed5wSwDBhi6vag65bBfaKHtQC7GRXUQ653Qxi8rdQSRo9E2KV5aEPVJKKCEP9QWcvy7yq
tpubDCNSZPSgNQtX7RwTYFg7dBw5Pf4mp7u9yD5c7dHmRrCpxUNRB9RmEXG1ucQ5Qu9M4L4P1faux4YBYou3pezTukwNdq8nyqyRpLjpGeJrdY6
vpub5YLHRpHAMmr793NNRM7n16QhibgDwVR6bMSsCHSrKvhB6z5FbcFYqxGudAQ7tatGT9Hru8svVe1364BJzQKCRr7sqYze8VgDgw27jUoo1Jg
```

regardless of whether I am using Sparrow or https://iancoleman.io/bip39/ to do the derivation.

**Comment by indcyfa** [comment]
Thanks for your effort to help @craigraw 

My test data:

Seed: `f3dd6b74b719d66541d2e6ab49e40c40`
BIP32 Root Key (xprv/tprv/vprv)
`xprv9s21ZrQH143K3wAxxajYoi7tSMRVZT3RnzdMrPXMbyxHGaDiUhKRSx3J7kkmCbecnv2WAvUoahuzGKH7itQ55AjyGhSXEUHRe3t6Xzcgrpr`
`tprv8ZgxMBicQKsPekQVd9b3yMjskUqhny5S8YYUiowp5xSm4AxoU4fAxhQk2vvRCy2wAMZHB26Zk4VnjAprr6k1tE1ZoLeptq1UZ9dWyeHQMaj`
`vprv9DMUxX4ShgxMMLnjHsAJPXvt6R8bgD4RxmavHbjaqyCXANbFyNzJCpj25LqbCnLmydntfyHgfPCtVk3zHVa3UhNmY23g4eeT6bkoktTmxNt`

converts to the following xprv/tprv/vprv at m/84'/1'/0' (according to Ian Coleman tool):

`xprv9ytj4PaWjBTmJJ7uPfScreypLE2UFdfcCMVDxRvrHiXqa5GZSVJCrNrB9MdNJpCBYZweSgQFoM68gs9NXgrLvmCTyZbTAUHeT4T8wzRhbQ8`
`tprv8gZfqitr8THqu7MS4EJ82JboeMSgV9hcXuQLprMJmh2KMg1eRrdxN8Dd4Xo2KBaVv1URSn21xhfw9ih7euCHjpU4WCokpq1hNACZPiqvq1c`
`vprv9LECT4EgRpNobhjfiwsNSUnozHjaNPgcN8SnPe95Xhn5Tse6wAy5cFXu6wiCJztLjHi2wjD8t2P2vHvF6J2KLHqGEtCbzeefucKrApvihb9`

converts to the following xpub/tpub/vpub at m/84'/1'/0' (according to Ian Coleman tool):

`xpub6Ct5Tu7QZZ24WnCNVgydDnvYtFrxf6PTZaQpkpLTr44pSsbhz2cTQBAezfWbamC45uGQa9vSNveHYPDxra73TnZkFZmX4rY1p2PJ9GYx7Cp`
`tpubDDFhz8w6GpyWnaPDwsxiRiFvDNxceUtX7D187NPcBxpiCAGR4FTYYcqVEhbP7G9HsooKBjSJv2ULEZiaFRxHME23KAWpkPCFPyyhuCztmBm`
`vpub5ZDYrZmaGBw6pBp8pyQNocjYYKa4mrQTjMNPC2Yh63K4LfyFUiHLA3rNxFbRawtDGd2o5CjKTbwBmozqRBH1sKCYWtNfu2u3GaG1N3EJ53p`

If I attempt to import the vprv above (ending `vihb9`) into Electrum I get vpub as shown above (Wallet | Information) and see balance of `0.00182` BTC. 

If I import the same vpriv into Sparrow I get the vpub below and obviously no balance.

`vpub5Y5eNU6SnMAp6rvNvVR8npxu6risuuNCVJKFrXF89zu5Y1jDefqc6EWmJGv7aC6HKB3S1ZBmkeNhogCkGPzcVfu5wzr6TqdAg7RpXqVJpEx`.
`tpubDC7oW3FxnzDE5FVU3PyUQvVGmv7RnXrFs9wzms63FvQjPW2PED1pUoVsaiv56WMMvMox85tmD4urGRvV6efsyaiakGzFKBvNoX9X4ysYxLV`

**Comment by craigraw** [comment]
Strange - I just did exactly this:

1. Run Sparrow in testnet
2. From the menu, File > New Wallet.  
3. Chose **Software Wallet** from the four options. Dialog opens.
3. For the Master Private Key (BIP32) option, click **Enter Private Key**
4. Paste in `vprv9DMUxX4ShgxMMLnjHsAJPXvt6R8bgD4RxmavHbjaqyCXANbFyNzJCpj25LqbCnLmydntfyHgfPCtVk3zHVa3UhNmY23g4eeT6bkoktTmxNt`
5. Click **Import**
6. The dialog closes and the tpub is `tpubDDFhz8w6GpyWnaPDwsxiRiFvDNxceUtX7D187NPcBxpiCAGR4FTYYcqVEhbP7G9HsooKBjSJv2ULEZiaFRxHME23KAWpkPCFPyyhuCztmBm`, which is correct as per your notes above.

Is your experience different?

**Comment by indcyfa** [comment]
No, that works. As you said:

> I think the problem here is that you are working with a derived `xprv`, but Sparrow is expecting a master `xprv`. Do you have the master `xprv`?

I was using the derived vprv and didn't quite parse what you said until now. Ok so I just need to remember that we can't point sparrow at the derived xprv, just the root xprv/tprv/vprv which is encoded with the derivation path anyway. 

Got it! Thank you @craigraw !

**Comment by craigraw** [comment]
Cool, closing this off.
