### ISSUE TITLE
Cant broadcast transaction to premix and send funds

### ISSUE THREAD

**Issue by DanielPX1** [sparrowwallet/sparrow#209]
Hi I have just run into an issue during whirlpool testing. When I select UTXOs and click mix, then I get into send interface, where I can't change any labels and fees etc. (Guess that is right). However the broadcast transaction button does not work at all. It is blue as it should be, but no matter how many times I click, nothing happens.

I thought it might be passphrase bug? Since I by mistake typed wrong passphrase into wallet ,,log in" and it let me open wallet anyway. So I thought I mind have a wrong signature or something. However by importing the right one, bug still remains. Cant send funds away and can't mix as well

**Comment by craigraw** [comment]
Does anything appear in the log file? Help menu > Show Log File.

**Comment by DanielPX1** [comment]
> Does anything appear in the log file? Help menu > Show Log File.

not sure, will check tomorrow. However exporting wallet and sending away through electrum worked well. So not sure what did not work

**Comment by craigraw** [comment]
Is this an Electrum seeded wallet?

**Comment by DanielPX1** [comment]
> Is this an Electrum seeded wallet?

**Comment by DanielPX1** [comment]
Damn I closed something, kinda new to GitHub so sorry for mistakes. 

It is generated via sparrow, however uses passphrase, might be an issue?

**Comment by craigraw** [comment]
Reopened. Unlikely to be a passphrase issue, that functionality is working on my side. 

Some of the notes above seem strange to me - you should only be able to open the wallet with the password, not the passphrase (unless they are the same).

The sparrow.log is probably the best way to diagnose the problem generally.

**Comment by DanielPX1** [comment]
I don't have logs now, fixed issue by reinstalling whole app. Sorry, guess I am not very helpful... However it was pretty weird. 

It went like this:
1)
Open wallet -> Password -> Asked Passphrase for keystore -> Import correct one –> unlocked
I had access to my 100k+ sats, however 40k sats which I received when imported incorrect passphrase could not be seen.

2)
Open wallet -> Password -> Asked Passphrase for keystore -> Import incorrect one –> unlocked
Additional 40k sats were visible, I could send away all funds including first one away... 

Was very weird, however app let me input many incorrect passphrases and nothing happened. However importing wrong password didn't let me in. Not sure why app asked for passphrase

**Comment by craigraw** [comment]
> I had access to my 100k+ sats, however 40k sats which I received when imported incorrect passphrase could not be seen.

Actually, this makes sense to me now. By inputting the wrong passphrase you changed all the addresses in the wallet (all passphrases are technically valid) - but the wallet still stores and shows your old transactions from the original passphrase. If you had tried View > Refresh Wallet, they would have disappeared.

Sparrow asks for a passphrase if you enter one when you first create a BIP39 wallet. It's the textfield below the words textfields. Sparrow doesn't save this value - you need to re-enter it whenever you load the wallet, as you have experienced.

I'll close this off. Glad it's fixed!
