### ISSUE TITLE
[Feature]  Derive valid checksum last word when restoring seed.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#214]
For people generating their own entropy by pulling words out of a hat.

![image](https://user-images.githubusercontent.com/388716/134759655-885f25d0-0fe9-4fb7-83c9-e2c58b19b856.png)

That button would only highlight when all but the last word has been entered.

**Comment by craigraw** [comment]
There is a selection of words that could serve as the last word, since the checksum is only the last few bytes of the final word.

I have considered adding this feature before though, so it's good to have it listed here.

**Comment by 6102bitcoin** [comment]
Duplicate https://github.com/sparrowwallet/sparrow/issues/156
