### ISSUE TITLE
Coinjoin - Possible to denominate the pool in sats?

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#215]
It would be helpful to see the pool amount in sats too. 
Maybe something like 
Pool min: 0.001 BTC (100,000 sats)

![image](https://user-images.githubusercontent.com/807505/134766866-5011f53f-1055-4786-9ba2-0a95096f727e.png)

**Comment by craigraw** [comment]
Good suggestion, implemented in 761e9c9.

<img width="402" alt="Screenshot 2021-09-27 at 09 31 33" src="https://user-images.githubusercontent.com/862166/134864148-7b7baedf-70ba-4624-9b29-7c89b6079118.png">
