### ISSUE TITLE
Minimize to tray options

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#218]
useful for leaving the wallet open for a long time mixing in the background.

Could also have a headless mode with mixing enabled or a start minimized argument.

**Comment by craigraw** [comment]
Already implemented - see the View menu.

**Comment by k1mbalam** [comment]
this is already implemented in linux? I don't see it in the "view" menu :(

**Comment by craigraw** [comment]
Unfortunately Linux has no general concept of system tray (it has things that look like it on some desktops) so it can't be implemented there in a generic way.

**Comment by AndySchroder** [comment]
> Unfortunately Linux has no general concept of system tray (it has things that look like it on some desktops) so it can't be implemented there in a generic way.

Yes, https://sparrowwallet.com/docs/ suggests there is a system tray option but it doesn't clarify it is not available on linux.

However, I'm still confused why this is not possible. The following programs are examples that have good system tray support on linux:

- https://bitcoincore.org/
- https://delta.chat/en/
- https://www.pidgin.im/
- http://gmusicbrowser.org/
- https://www.remmina.org/
- https://transmissionbt.com/
- https://www.videolan.org/vlc/

**Comment by craigraw** [comment]
>  it doesn't clarify it is not available on linux

Added.

> However, I'm still confused why this is not possible.

Sparrow relies on `java.awt.TrayIcon` as support in JavaFX [is not yet available](https://bugs.openjdk.org/browse/JDK-8092115). There is some context on Linux support here: https://stackoverflow.com/questions/50440268/the-system-tray-is-not-supported-on-the-current-platform. I believe a native solution [is probably possible](https://github.com/JoshuaD84/HypnosMusicPlayer/tree/master/src/linux-tray-icon-gtk), but I'd prefer to avoid that.
