### ISSUE TITLE
Feature Request - Fee in fiat

### ISSUE THREAD

**Issue by shaggy35** [sparrowwallet/sparrow#22]
Like to see what my fee is in fiat when sending. Wonder if this could be incorporated, sats/vbyte etc don't really mean too much to me tbh.

**Comment by craigraw** [comment]
Not sure what you mean - the fee is shown in fiat on the right of the fee field:

<img width="425" alt="Screenshot 2020-10-11 at 14 45 28" src="https://user-images.githubusercontent.com/862166/95679022-8789f300-0bd0-11eb-9d26-efef7913bf26.png">

**Comment by shaggy35** [comment]
ahhh, hadn't put a receiving address in so didn't see it :)
