### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by chimp1984** [sparrowwallet/sparrow#220]
First of all: Congrats to the wonderful wallet!

I observed quite high CPU usage (about 20%) after leaving the Sparrow wallet running for a few days and using mixes. I stopped mixes but CPU was still high. After restart it was low.  
IMac, OSX 10.12

**Comment by 6102bitcoin** [comment]
We could have a test to monitor useage over time with a [script](https://stackoverflow.com/questions/1221555/retrieve-cpu-usage-and-memory-usage-of-a-single-process-on-linux) if this is an issue. Given the recent addition of whirlpool I expect users will increasingly run in the background.

**Comment by craigraw** [comment]
Fixed by https://github.com/sparrowwallet/sparrow/commit/a22f69e2c125ae035c67a9757bff31859028de30
