### ISSUE TITLE
Stop mixing doesn't stop the animation.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#227]
![image](https://user-images.githubusercontent.com/388716/135176108-dd0e5a0b-de22-40b1-a7aa-b558b50a570c.png)

**Comment by craigraw** [comment]
Yes - this is because the mix transaction has already been broadcast by the coordinator, and stopping mixing can't stop the Bitcoin network (luckily :). The progress bar will disappear along with the spent UTXO once your server picks it up.
