### ISSUE TITLE
[Feature] Main transaction view could show amounts.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#228]
![image](https://user-images.githubusercontent.com/388716/135209745-411a9e2c-e2c8-48dc-b34b-90cade8e5c35.png)

If the space is a concern I think it'd be great to show the btc amount when hoovering on the pie chart segment.

The delay to show the mouse over tooltip should be reduced to instant. Currently long enough to skip over that feature.

Alternatively clicking on one of the input pie segment or output could jump us to the specific input number page.

**Comment by 6102bitcoin** [comment]
The transactions section is currently useful when you know what you are looking for in advance (e.g. what locktime was used, What is the script pub key of output #5). 

It is not very convenient for exploring / browsing through the details of the transaction (i.e. trying to understand broadly what the inputs / outputs are, their sizes, the likely flows of funds).

There are two popular and very differnet approaches;

1. Show just the amounts, addresses and key tx info (locktime etc). Examples of this are mempool.space & blockstream.info.

2. Also show flows of funds, e.g. KYCP.org. This uses boltzman which requires a reasonable amount of computation per tx/ It would be a very nice feature to run this analysis locally in the background for all transactions in the wallet.

Both approaches use a two column approach with inputs on left hand side & outputs on right hand side. For both the inputs and the outputs the addresses and amounts are shown together.

**Comment by craigraw** [comment]
> If the space is a concern I think it'd be great to show the btc amount when hoovering on the pie chart segment.

Implemented in 22b7b65.

> It is not very convenient for exploring / browsing through the details of the transaction (i.e. trying to understand broadly what the inputs / outputs are, their sizes, the likely flows of funds).

For sure - there is a natural tension between a transaction editor allowing editing of all fields (which Sparrow leans towards) and a transaction viewer. Including the transaction diagram in the Send tab would be step forward, but I don't yet see a natural location for it in the transaction UI. Possibly tabs on the Overview screen.

> Also show flows of funds, e.g. KYCP.org.

That's good goal, although I don't know how practical it is even given the power of a desktop. But certainly a Boltzmann analysis would be a powerful feature.

**Comment by craigraw** [comment]
I'm going to close this off as implemented. 

The transaction diagram feature is covered in #164. The Boltzmann feature should be a new issue.
