### ISSUE TITLE
Open new wallets on different windows

### ISSUE THREAD

**Issue by pedromvpg** [sparrowwallet/sparrow#23]
Is it possible to open wallets on different windows so all the tabs relate to 1 single wallet?
When sending transactions from multiple wallets it make it hard to know which tabs relate to which wallet.

**Comment by craigraw** [comment]
This is a good idea and something I've been thinking about. 

With this turned on, it is better to automatically create a new window for each new wallet loaded, or allow the user to add new windows and add wallets to them (depending on which one is active)?

**Comment by pedromvpg** [comment]
I would think just create a new window every time, by default. 
Maybe in the advanced settings an option can be added that allows the tabs to move from window to window and such.

**Comment by craigraw** [comment]
Implemented in 6a1c3fa.

This can be configured in the view menu:

<img width="235" alt="Screenshot 2020-12-08 at 12 34 18" src="https://user-images.githubusercontent.com/862166/101472791-b6fb7880-3951-11eb-8360-d4369babfa87.png">
