### ISSUE TITLE
Can't send from Postmix, Create TX grayed out. [v1.5.0]

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#232]
![image](https://user-images.githubusercontent.com/388716/135563694-dceacf00-144d-4b15-af1d-6a922ecf36b6.png)

I was able to empty the Badbank just before

**Comment by Transisto** [comment]
The balance reported was off by a 0.001 extra on Sparrow vs electrum

I spend the coins on electrum and sparrow would not update the balance.

I reconnected to different servers and the balance updated correctly.

`2021-10-01 01:08:17,100 WARN [JavaFX Application Thread] c.s.s.w.TransactionEntry [null:-1] TransactionEntry 000000000000000000000000 for wallet mix test-Postmix missing child for input null on output 0000000000000000000:3
2021-10-01 01:08:17,101 WARN [JavaFX Application Thread] c.s.s.w.WalletTransactionsEntry [null:-1] Removing and not notifying incomplete entry 0000000000000000000 value -1400000`

**Comment by craigraw** [comment]
> I reconnected to different servers and the balance updated correctly.

Ah - confirms my suspicion in #231. Which server were you connected to? I'd like to inform them of the error.

**Comment by Transisto** [comment]
electrum.blocksteam.info

**Comment by craigraw** [comment]
Ok thanks. Closing this off as not a Sparrow issue.
