### ISSUE TITLE
Feature request: add Electrum compatible BIP39 restore option

### ISSUE THREAD

**Issue by igorglv** [sparrowwallet/sparrow#238]
Right now if one wants to restore a wallet from an Electrum mnemonic words, Sparrow shows "Invalid checksum" error. If one imports Electrum wallet directly, Sparrow correctly shows seeds as "Electrum Seed Version System".

Request 1: to add a "Electrum 12 words" menu item in "Mnemonic Words (BIP39)" and may be remove "enter ...", so the menu will looks like "Electrum 12 words" "BIP39 12 words" "BIP39 15 words" "BIP39 18 words" ...

Request 2: add a conversion option from Electrum seeds to BIP39 words in "View Seed..."

**Comment by craigraw** [comment]
For the reasons discussed in #59, I don't want to add Request 1 in Sparrow. Having two seed standards introduces more confusion, and it would do the community a disservice to support creating ESVS seeds. The current support is intended as a restore option for Electrum wallets, but ultimately I believe it is wise to migrate such wallets to a more widely compatible standard.

I don't believe Request 2 is possible, unfortunately.

**Comment by igorglv** [comment]
I understand the reasoning but it creates absolutely terrible user experience. I knew that the words are correct, so I entered it multiple times, restarted Sparrow and tried again, though that this functionality is currently broken, googled and got nothing, nothing is the help files...
How about to add a warning message for the "12 words" option that Sparrow does not support Electrum seeds (and maybe other well known non standard wallets) and one must import the wallet directly?

**Comment by craigraw** [comment]
Agreed, this is exactly why two seed standards almost identical in appearance make for bad UX.

I've implemented your suggestion in b9d6cb1.

<img width="562" alt="Screenshot 2021-10-06 at 08 19 57" src="https://user-images.githubusercontent.com/862166/136151146-27e59c7f-4d2a-48c5-85ac-9d8b1444a19b.png">

**Comment by dazza9x** [comment]
Sparrow is not able to import the electrum file? Any ideas?

**Comment by dazza9x** [comment]
![image](https://user-images.githubusercontent.com/118892353/223615029-52379b73-40e0-4987-b685-2f45d1c985de.png)

**Comment by craigraw** [comment]
The message in the screenshot contains all the information you need already. Create a new wallet with your BIP39 seed words.

**Comment by gus4rs** [comment]
What about the labels? Is there a way to import them from a electrum BIP39 wallet? Electrum allow to export labels in the following format:
```json
{
    "txid1": "label1",
    "txid2": "label2",
}
```

**Comment by craigraw** [comment]
Labels from Electrum wallets will be imported with the File > Import Wallet > Electrum feature.

**Comment by gus4rs** [comment]
Can't see this option in 1.7.3, but I can see "wallet labels".

**Comment by craigraw** [comment]
It's 6th on the list.

**Comment by gus4rs** [comment]
The 6h on the list is "Coldcard multisig" the 7th is "Electrum" but this is to import the full wallet and doesn't work with wallets that are not electrum seed native

**Comment by gus4rs** [comment]
FTR, I pick the Electrum JSON and convert into the BIP format and was able to import the labels from electrum

**Comment by gus4rs** [comment]
Yep, I convert it and it worked, thanks
