### ISSUE TITLE
Doesn't load the proper transaction history.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#24]
Same wallet same electrum server

Sparrow
![image](https://user-images.githubusercontent.com/388716/96300129-0f05a680-0fc3-11eb-915a-70d6df42de4d.png)

electrum
![image](https://user-images.githubusercontent.com/388716/96300227-3197bf80-0fc3-11eb-8b56-64169801df1f.png)

**Comment by Transisto** [comment]
Nevermind, The reason is wallet is using a non-standard derivation path, so no change address is being detected or something

**Comment by craigraw** [comment]
It would be interesting to know more. Having a non-standard change path is very unusual.

That said this might be related to #26 - improvements coming in the next release.
