### ISSUE TITLE
[Bug] Some invisible UI element are pushing up the view.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#242]
![image](https://user-images.githubusercontent.com/388716/136254157-9ecf17f5-ca6b-4bca-a2de-3164fdba9a7e.png)

![image](https://user-images.githubusercontent.com/388716/136254203-f4a2200f-0059-4005-a700-022b1ba3b839.png)

and

![image](https://user-images.githubusercontent.com/388716/136254315-ddd3885d-0409-42e5-b3a2-076fc203ee88.png)

![image](https://user-images.githubusercontent.com/388716/136254426-0fbc46d5-34e4-4cce-9fbf-5ff92ae6631a.png)

![image](https://user-images.githubusercontent.com/388716/136254495-18b8aa4f-d843-4b52-acf8-5eccd5f54f22.png)

Note, I'm using the suggest windows system override scaling option, so that the wallet doesn't always take at least 2/3 of my very large screen.

**Comment by craigraw** [comment]
Fixed in a68eeb4.
