### ISSUE TITLE
Issue connecting to Tor with Umbrel node

### ISSUE THREAD

**Issue by AtomicAkorn** [sparrowwallet/sparrow#251]
I am having an issue connecting to tor using private server via umbrel. It was connecting fine up until today 10/8. I keep getting the error message:

Connection failed: IO error (cannot connect to hidden service)

**Comment by craigraw** [comment]
This is more likely an issue with your Umbrel node. Have you updated it recently? The new Electrs needs to reindex, so it will be down for awhile. Check your Electrs logs to see if that's the case.
