### ISSUE TITLE
Change font of addressess

### ISSUE THREAD

**Issue by jakvb** [sparrowwallet/sparrow#253]
It is hard to recognize similar characters. For example `1` and `l`.

**Comment by 6102bitcoin** [comment]
![1l](https://user-images.githubusercontent.com/42300012/142278815-a8a09490-5661-4235-8b64-88d4c1a6a4d1.png)

They are reasonably similar, however it is uncommon (and not recommended) to read out an address. If you are doing so I recommend converting into the NATO phonetic alphabet using [this tool I wrote](https://github.com/6102bitcoin/nato-to-string/).

**Comment by craigraw** [comment]
Good suggestion.

I'm going to close this off as I think any changes here are unlikely given the lack of proposed alternatives.
