### ISSUE TITLE
Wallet stop communicating with any servers until restarted.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#255]
ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed

No amount of clicking and switching server would help.
![image](https://user-images.githubusercontent.com/388716/136671512-e75276ff-e824-43b6-b578-63e312ff27a5.png)

![image](https://user-images.githubusercontent.com/388716/136671546-b90a9b59-6194-4f35-bc58-3773bdd3c2d1.png)

Not getting any connection error or timeout, it's just not actually trying to connect.

**Comment by craigraw** [comment]
Do you have access to a Linux desktop to test on? I have been wondering if these issues are somehow related to the Windows networking stack.

**Comment by haromz** [comment]
I'm also getting this issue on a Mac. It is not related to Windows networking stack. Ping to the server works however.

**Comment by walker377** [comment]
Same issue for me on Mac as well. Restarting Sparrow appears to have fixed.

**Comment by 6102bitcoin** [comment]
Should this issue be closed?

**Comment by Transisto** [comment]
Stayed online for two day, from here, I'll reopen if it happens again.
