### ISSUE TITLE
Sparrow does not see existing Electrum wallets when attempting to import

### ISSUE THREAD

**Issue by davterra** [sparrowwallet/sparrow#27]
Running 0.9.5 on Ubuntu 20.04
I have 4 existing Electrum wallets. When I start Sparrow and attempt to import any of them, I end up with a file window at my
~/user/.electrum/wallets folder, but it appears as if the folder is empty, even when the selector is set to "All files".

NEW INFO:
I find that if I create a backup of the Electrum wallet using Electrum's "backup" function, Sparrow does see and import that backup file.

If this is by design & the only way to import an Electrum wallet into Sparrow, then I think that should be mentioned in the "Show Details" part of the Electrum wallet import procedure.

**Comment by craigraw** [comment]
Thanks for the bug report. It turns out Linux handles file filtering slightly more strictly, requiring the . in the file name to match a '*.*' file pattern. File pattern has been changed to '*' for All Files in https://github.com/sparrowwallet/sparrow/commit/f48fb610e86e804c3c2d7d53728d29d87d22a1c2

**Comment by davterra** [comment]
Thanks for the quick fix & info
