### ISSUE TITLE
Feature Request: PSBTs with QR code support

### ISSUE THREAD

**Issue by darwayne** [sparrowwallet/sparrow#270]
Hello, thanks for providing such amazing software to the community!

I noticed I’m not able to use sparrow as a co-signer when using PSBTs. I’m forced to either use sparrow as the sender or export the signed transaction to a file. I was expecting to see an option to use a QR code to sign a transaction similar to how blue wallet does.

Am I missing something from my end or is this just a feature that isn’t there yet?

**Comment by craigraw** [comment]
Closing this off - no response and I believe this functionality is already present as described.

**Comment by darwayne** [comment]
Thanks, missed your first response.
