### ISSUE TITLE
[Feature] Show sat/byte paid and distance from tip for unconfirmed transactions.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#271]
Currently:
![image](https://user-images.githubusercontent.com/388716/137599569-5dbcfabf-32b5-448d-a7c4-2cbb4f7c5d63.png)

Idea:
![image](https://user-images.githubusercontent.com/388716/137599606-da209aaa-10be-4709-aa7e-6b216ae5e955.png)

**Comment by 6102bitcoin** [comment]
Seems like a good idea to me.

**Comment by craigraw** [comment]
This was added in v1.5.6.
