### ISSUE TITLE
[BUG] Transaction amount off by a satoshi

### ISSUE THREAD

**Issue by suvayu** [sparrowwallet/sparrow#282]
Not sure exactly what was going on, I was paying an invoice of an amount like this `0.XXXX1000`.  When I entered the amount in the UI, the transaction that was created was for `0.XXXX0999`.  I noticed it before broadcasting, so recreated it, this time I entered `0.XXXX1`, but I realised the same thing happened again when I received a notification from the payments portal (shown below):

> We have received only 0.XXXX0999 of the 0.XXXX1000 BTC ... leaving a remaining balance of 0.00000001 BTC. This can happen if you forgot to account for the coin TX fee when sending to us or if you are using a coin that only allows 6 digits after the decimal and didn't round up to the 6th digit.

I had to make an additional 600 sats transaction (because of dust limit) to pay my invoice completely.

I can see the transaction fee was added separately, so I'm wondering what went wrong?  I don't do a lot of transactions, so I'm not sure if I did everything correctly.

*PS:* If needed, I can share the Tx privately.

**Comment by suvayu** [comment]
Hi @craigraw, sorry about the delay, busy couple of weeks.

I tried to compile from master, but ran into some java version issues I think (I used the latest from the Fedora repos, openjdk 17).  But then I noticed there was a new release, so I tried the 1.5.2 release, and the issue is fixed!  Thanks for the prompt resolution :)

**Comment by craigraw** [comment]
Great, thanks for reporting back!
