### ISSUE TITLE
Connection toggle slow pulsing consume 5% GPU and is not noticeable at normal speed.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#284]
https://youtu.be/dwJ8NsbQenE?t=242
5x speed. I Switch on-off connection around 4min in.

I had no idea the toggle was pulsing until I played the video at 5x speed.

Connection to servers has always been a hit and miss on Windows, improving the feedback when it's connected or not connect would help a lot.

I've clicked and looked at that toggle so many times I can't believe I didn't notice the pulsing.

**Comment by craigraw** [comment]
Further improved in e418971.
