### ISSUE TITLE
Maximized Sparrow Too Large for Viewport

### ISSUE THREAD

**Issue by bettyvschmartz** [sparrowwallet/sparrow#298]
Using Sparrow Wallet maximized on a low resolution Linux device results in the main window being too large for the viewport. This particular resolution is 1366 x 768. I also find that any dialogues that open cause the main window to unmaximize itself. 

Tested using XFCE, and currently as a workaround have to hide the bottom panel. 

-- bvs

**Comment by craigraw** [comment]
The minimum height of Sparrow depends on the height of the title bar used by the window manager, but it's generally about 730px. So that can be problem when the OS has a dock/app menu higher than 38px. 

What is the current maximum height using XFCE, with the bottom panel showing?

**Comment by bettyvschmartz** [comment]
That sounds like the problem. In XFCE the top and bottom panels are 30px each so in my case there is only a usable screen space of 708px.

-- bvs

**Comment by craigraw** [comment]
Minimum application height reduced to 708px in 5e7d1d1. Hopefully that's small enough!
