### ISSUE TITLE
Can't add keystore to watch only wallet?

### ISSUE THREAD

**Issue by mflaxman** [sparrowwallet/sparrow#3]
The `Apply` button is greyed out and the `Import...` button takes me to a page that doesn't allow for text input:
![Screen Shot 2020-09-03 at 4 33 37 PM](https://user-images.githubusercontent.com/448644/92176022-464d3900-ee03-11ea-800a-fd3bc724a07e.png)
(Doens't matter whether I use `xpub` or `Zpub`)

Seed phrase is `zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo buddy`:
http://seedpicker.net/calculator/last-word.html
![Screen Shot 2020-09-03 at 4 33 14 PM](https://user-images.githubusercontent.com/448644/92176023-46e5cf80-ee03-11ea-853c-effd7d914491.png)

My use-case is that I'd like to be able to import a bunch of xpubs from a multisig wallet on an eternally quarantined machine and use that to assist in verifying receive addresses. It'd be great to include in my guide here for example:
https://btcguide.github.io/verify-receive-address/advanced

**Comment by mflaxman** [comment]
On a related note, it'd be awesome if you could just take a Specter-Desktop wallet (xpub) output file and just import the whole thing. It uses script descriptors, so you get all the pubkeys and m/n.

**Comment by MsFloofie** [comment]
It is in Multi-Signature policy in your picture. Did you try inputting it with Single Signature policy?

**Comment by mflaxman** [comment]
I'm trying to do it as part of a multisig, but I get the same issue on single sig p2wpkh:
![Screen Shot 2020-09-03 at 4 49 01 PM](https://user-images.githubusercontent.com/448644/92177091-6ed63280-ee05-11ea-80e9-8d98b5cc1609.png)

**Comment by craigraw** [comment]
Thanks for pointing this out - I was aware of it but didn't get around to fixing it before the first release. Currently, you have the option of adding a watch only keystore when you first create the keystore, but not afterwards. I will probably add a 'Watch only Keystore' button on the left at the bottom of the import dialog. This will close the dialog and give you the normal watch only keystore view which allows the user free text entry in the fields.

For now a workaround is to change the M/N sliders which will create fresh keystores. The watch only option is then on the right in the initial selection buttons. 

I will take a better look at Specter-Desktop - my intention with Sparrow is to be able to import and export from multiple formats so very in line with that. Your suggestion of using an airgapped computer as a multisig coordinator/address checker is one of the key use cases for Sparrow as well.

**Comment by craigraw** [comment]
Fixed in https://github.com/sparrowwallet/sparrow/commit/7d7c5e5064a10792894c0bc0c814cfc94564057e through a button added to the bottom left of the keystore import dialog.

**Comment by craigraw** [comment]
Specter Desktop wallet file import and export added in https://github.com/sparrowwallet/sparrow/commit/0adf94bf6278992d72abb2cad33f6be2b397f92d.
