### ISSUE TITLE
Can't install on fresh instance of Debian 10 in Qubes

### ISSUE THREAD

**Issue by davterra** [sparrowwallet/sparrow#30]
Using debian10 vm inside Qubes, when I try to install the latest .deb I get this: (I've had no problems installing it
on a Ubuntu Virtualbox VM - works fine there)

user@debian-10:~/Downloads$ sudo dpkg -i sparrow_0.9.6-1_amd64.deb 
(Reading database ... 151728 files and directories currently installed.)
Preparing to unpack sparrow_0.9.6-1_amd64.deb ...
xdg-desktop-menu: No writable system menu directory found.
dpkg: warning: old sparrow package pre-removal script subprocess returned error exit status 3
dpkg: trying script from the new package instead ...
dpkg: ... it looks like that went OK
Unpacking sparrow (0.9.6-1) over (0.9.6-1) ...
Setting up sparrow (0.9.6-1) ...
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package sparrow (--install):
 installed sparrow package post-installation script subprocess returned error exit status 3
Errors were encountered while processing:
 sparrow
user@debian-10:~/Downloads$

I tried running apt install -f to check for dependencies and got this output:

user@debian-10:~/Downloads$ sudo dpkg -i sparrow_0.9.6-1_amd64.deb 
(Reading database ... 151728 files and directories currently installed.)
Preparing to unpack sparrow_0.9.6-1_amd64.deb ...
xdg-desktop-menu: No writable system menu directory found.
dpkg: warning: old sparrow package pre-removal script subprocess returned error exit status 3
dpkg: trying script from the new package instead ...
dpkg: ... it looks like that went OK
Unpacking sparrow (0.9.6-1) over (0.9.6-1) ...
Setting up sparrow (0.9.6-1) ...
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package sparrow (--install):
 installed sparrow package post-installation script subprocess returned error exit status 3
Errors were encountered while processing:
 sparrow
user@debian-10:~/Downloads$

**Comment by davterra** [comment]
Ok, I did some googling and apparently there is a bug in xdg. 
This link provides a very simple fix, which worked for me. 
https://askubuntu.com/questions/405800/installation-problem-xdg-desktop-menu-no-writable-system-menu-directory-found
Problem solved.

**Comment by craigraw** [comment]
Glad to hear, and thanks for documenting this.
