### ISSUE TITLE
Feature request: Amount of transaction on signing screen

### ISSUE THREAD

**Issue by raymondclowe** [sparrowwallet/sparrow#300]
Please consider adding the amount of the transaction somewhere on the screen where signing is done.

Something like this:

![Screenshot Sparrow need-tx-amount 2021-11-08 edit](https://user-images.githubusercontent.com/68897994/140681131-75975357-8dac-4660-aa8e-9a93923354f8.png)

The amount being sent is an important field that is otherwise not visible just before I take the last step, signing.

**Comment by craigraw** [comment]
Unfortunately space for additional fields is always tricky, particularly as the vertical height is limited on some laptops. There are also potentially multiple amounts being sent, some as change, which makes representation more difficult.

The amounts being sent are present in the tooltips in the transaction diagram and the outputs screens accessible from the tree on the right. I'm not sure how to condense this information into a single value in a generally useful way.

**Comment by raymondclowe** [comment]
Thanks, I did not notice the tooltips.  I'll take a look.  

Perhaps (probably) I'm being a dinosaur here but I don't think about tool tips much.

**Comment by craigraw** [comment]
Closing this off.
