### ISSUE TITLE
Could not parse signed PSBT

### ISSUE THREAD

**Issue by jooray** [sparrowwallet/sparrow#303]
I am trying to do a 2-of-3 multisig setup with one software wallet and two Trezor T devices (with passphrase, enterred on the device).

I created the wallet remotely as:

Computer 1:
- Keystore 1: Trezor T
- Keystore 2: xpub from another computer
- Keystore 3: software wallet

Computer 2:
- Keystore 1: xpub from another computer
- Keystore 2: Trezor T
- Keystore 3: xpub from the software wallet

They both correctly generate the same addresses. They have received BTC, both computers see it. 

When I try to sign a simple transaction to spend maximum amount to a different address, I create a PSBT, Finalize it for signing and then Click Sign. It does not matter on which of the computers, the result is the same: The transaction is correctly displayed on Trezor, I confirm address, amount, fee and locktime. 

Then I get "Could not parsed signed PSBT" in Sparrow.

In logfile I also get 

"2021-11-09 11:06:54,281 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: Could not parsed signed PSBT"

and nothing else.

The PSBT is pretty standard:

0200000001bca838bb94268ef79abdaadddf991c59166c7df24f7261a0352f0f5786284b150000000000fdffffff016420000000000000160014a9be958f06ad10b7154c9dd92dfa7958620274211fd10a00

It seems that Trezor T recognizes the transaction to sign correctly too.

Trezor T firmware: 2.4.2
Sparrow Wallet: 1.5.2
OS: macOS 12.0.1

Let me know if I can help debug this somehow.

**Comment by craigraw** [comment]
Are you able to run Sparrow from source? Instructions in the project README.

I've just committed fb85277 which prints the full stacktrace to the log (and corrects the typo you founds, thanks) - this should give more information on where the PSBT parsing is failing.

**Comment by craigraw** [comment]
The issue here is that either HWI or Trezor is returning an invalid PSBT (according to BIP174). My guess is that that this might have something to do with one of the other keystores in the wallet (probably the 'xpub from another computer') - perhaps it has a master fingerprint of `00000000` and `m/0` derivation path? This might be triggering a bug where these values are not written out properly and as a result the `valuedata` for a `PSBT_GLOBAL_XPUB` field is being written out as `0` or something similar. These fields should always be written as a series of `<32-bit uint>`s - in this case we don't even have one `<32-bit uint>`.

If so, try setting a different value for the master fingerprint and/or a longer derivation path. The Trezor doesn't store this data so it will sign regardless.

**Comment by jooray** [comment]
Thank you. I used the original master fingerprint from the other Sparrow wallet, so it was not all zeroes, but I had a shorter derivation part. I used a longer one and it worked, thank you.

Two suggestions: Maybe Sparrow could issue a warning when the derivation path is short.

And a question - why is there a master fingerprint and derivation path, when I give xpub that is master key at the given derivation? It is not used for signing as far as I understand. What is the purpose of this in watch only wallets, is it just a documentation? I understand why we need derivation path for hardware wallets - so the hw wallet knows which private key to use, the derivation path can be long. But for watch only I don't understand, is there a reason?

**Comment by jooray** [comment]
BTW: I suggest keeping the exception in the log as it is currently commited, so when other people have problem, they get the whole error message.

**Comment by craigraw** [comment]
> Two suggestions: Maybe Sparrow could issue a warning when the derivation path is short.

Glad to hear it worked. I think actually that Sparrow was too strict here - I've made a change in https://github.com/sparrowwallet/drongo/commit/f46d6277551cdb69286fbc3a6e536e0542cb7170 to allow zero length derivation paths.

> And a question - why is there a master fingerprint and derivation path, when I give xpub that is master key at the given derivation?

In general the xpub is not the master public key - this is only true without any derivation path. You're correct that in the case of a strictly watch only wallet this is for documentation purposes. Consider however that certain hardware wallets (like Coldcard) store the master fingerprint, derivation and xpub for all of the cosigners in a multisig wallet. If these do not appear correctly in the PSBT, the hardware wallet may refuse to sign.

I'll close this off now - thanks for the filing the issue. The exception will remain logged.
