### ISSUE TITLE
Status Bar Update Link Shows Multiple Times

### ISSUE THREAD

**Issue by bettyvschmartz** [sparrowwallet/sparrow#304]
It seems when Tor is restarted, that the update link in the status bar is duplicated. 

Steps to reproduce:

1. Connect to a Tor node
2. See the toggle, onion icon, and update link in the status bar
3. Disable or restart the local Tor service
4. Toggle connection off/on
5. See there is the toggle, upgrade link, onion icon, and upgrade link again

-- bvs

**Comment by craigraw** [comment]
Thanks for the report - fixed in c3778b6.
