### ISSUE TITLE
Can't seems to figure out how to import a custom derivation from a ledger nano S

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#306]
![image](https://user-images.githubusercontent.com/388716/141385178-37c6a270-79c3-4774-aa5f-375d54eda8b9.png)
![image](https://user-images.githubusercontent.com/388716/141385834-974b338d-293c-4382-ae93-be49610cc04a.png)

The discover doesn't seems to work or it's not going far enough, For example I'd like to be able to import the ledger's m/84'/0'/2147483646' and m/99'/0'/1'

The discover function tool could show something to the effect of what paths and what depth were checked when nothing is found.

**Comment by craigraw** [comment]
> The discover doesn't seems to work or it's not going far enough, For example I'd like to be able to import the ledger's m/84'/0'/2147483646' and m/99'/0'/1'

Indeed - that would take far too long! Only accounts 0 to 9 are supported at this time as tabs on the right. Other accounts will need a new wallet.

> The discover function tool could show something to the effect of what paths and what depth were checked when nothing is found.

Good idea - I've already added (in source) an informational dialog when this happens - I'll make sure it notes which accounts were scanned for. Added in a7aafa2.
