### ISSUE TITLE
All labels have disappeared from Postmix UTXOs

### ISSUE THREAD

**Issue by calligrl** [sparrowwallet/sparrow#307]
I can't remember if the labels I had set in Deposit had automatically propagated to the UTXOs in Postmix or if I had to set them manually, but a few days ago all the labels in Postmix UTXOs disappeared, though one label has since reappeared. Prior to this, single labels had disappeared but I'd been able to figure out what the label should have been and put it back. But now I've no was of knowing which is which.

I'm assuming that all labels are stored locally, so is there any way I can get them back? I've tried refreshing the wallet but nothing changed.

Is there any information I can supply that would help?

Running Sparrow 1.5.2 on openSUSE Leap 15.2

**Comment by craigraw** [comment]
Are you doing wallet refreshes (prior to losing labels)? 

Also, check the ~/.sparrow/wallets/backup folder for dated backups of your wallet, which may contain the labels.

**Comment by calligrl** [comment]
> Are you doing wallet refreshes (prior to losing labels)?
> 
> Also, check the ~/.sparrow/wallets/backup folder for dated backups of your wallet, which may contain the labels.

**Comment by calligrl** [comment]
Sorry, I didn't mean to close the issue.

Yes, I think I may have used the Refresh Wallet function prior to losing the labels.

There is nothing in the backup folder, although it has a Modified time stamp for today. I noticed a few days ago that it was empty.

**Comment by craigraw** [comment]
Apologies for the slow response. Unfortunately without a backup there's no way to restore the labels. Sparrow saves your current wallet as a backup before refreshing all the transaction data (and reapplying labels), but deletes it on a successful wallet load. My hypothesis here is that the wallet load completed "successfully", but the server did not return all the transactions for the wallet (perhaps the passphrase was different?)

I've made a change in 9b9b295 which will keep the saved backup wallet if the wallet transactions are fewer when the wallet is refreshed. Hopefully this will provide protection against this situation reoccurring.
