### ISSUE TITLE
Feature Suggestion: Scan derivation path option on seed import

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#309]
Problem:
If a user only has their mnemonic seed they currently have to manually try different common derivation paths / script types in order to find their coins. 

Proposal:
Add functionality to automate this process. [Electrum](https://github.com/spesmilo/electrum/blob/6650e6bbae12a79e12667857ee039f1b1f30c7e3/electrum/bip39_recovery.py#L19) has this feature. They use a [json](https://github.com/spesmilo/electrum/blob/master/electrum/bip39_wallet_formats.json) file to make is easy to add additional paths. It could made sense to use this format if possible - addition of new paths could then be ported back to electrum.

I volunteer to add the paths from [walletsrecovery.org](walletsrecovery.org) that are missing from this json

**Comment by Transisto** [comment]
That would go a long way to making Sparrow more beginner friendly.
There's already a "Discover" option when adding account.
I don't like that custom derivation like Whirpools accounts cannot be added when discovering from a hardware wallet.

**Comment by craigraw** [comment]
Added in 91d491f. The first item in the Wallet Import dialog allows entry of mnemonic words, and if the user is online Sparrow will search for existing transactions (if not, the script type will need to chosen explicitly). It looks at all default derivations, and `m/0'`, across all singlesig script types. This covers all the possibilities listed in the Electrum json file (but using the correct derivation according to the network). I believe it also covers walletsrecovery.org paths for singlesig wallets. If existing transactions are found at the account 0 derivation path, Sparrow looks for other accounts (1-9) plus Whirlpool accounts. This is therefore simple way to fully restore any normal BIP39 wallet in Sparrow.

<img width="612" alt="Screenshot 2022-02-15 at 13 38 12" src="https://user-images.githubusercontent.com/862166/154055607-46e35986-1b7a-4813-9949-67a1c92588ee.png">
