### ISSUE TITLE
Unable to import Unchained Capital/Caravan wallet

### ISSUE THREAD

**Issue by Marcsmyname** [sparrowwallet/sparrow#318]
When I import Caravan wallets into Sparrow, I am unable to click the "apply" button.  The wallets, xpubs, master fingerprint, and derivation path's are there. The script type is Legacy(P2SH) but I'm pretty sure caravan uses Nested Segwitt.

Is this a bug or am I doing something wrong? 

I am using Ubuntu.

![sparrowunchained](https://user-images.githubusercontent.com/55064159/142660392-98656fab-0466-42b6-8f41-eed941d7e3bb.png)

**Comment by craigraw** [comment]
There is a problem on "GreenTape" keystore (can't see what it is). Are you using the Caravan file import?

**Comment by Marcsmyname** [comment]
No. I experimented with Unchained Capital. I downloaded the file from unchained capital, but I was able to recreate it in Caravan.

**Comment by craigraw** [comment]
Ok. Can you identify the problem with the "GreenTape" keystore?

**Comment by Marcsmyname** [comment]
I'm not sure. Here are The other two keystores.

![greenTape](https://user-images.githubusercontent.com/55064159/142911649-88613b91-76b0-4d36-9847-75a3e97cd82e.png)


![blueTape](https://user-images.githubusercontent.com/55064159/142911655-e903a3fb-901c-41bd-9fc9-58d10eae1266.png)
.

**Comment by craigraw** [comment]
These are strange and non-standard derivation paths. If you are certain they are correct, try disabling the derivation path validation in the General Preferences. However, given your previous comments I think it's likely this setup does not represent the same Caravan wallet.

**Comment by lvnilesh** [comment]
See response from https://twitter.com/MsHodl on this https://twitter.com/nakamotwani/status/1479977316793020416

Something seems amiss with Unchained derivation path. 

Are derivation paths required to access all the funds associated with a given multi-sig?

**Comment by craigraw** [comment]
They're not strictly necessary, although certain non-essential fields in the PSBT will be technically incomplete/incorrect. So long as you have the correct xpub for all the signers you can generate the spending scripts for the multisig wallet.
