### ISSUE TITLE
Implement Replace-by-Fee (RBF)

### ISSUE THREAD

**Issue by louneskmt** [sparrowwallet/sparrow#32]
Actually, if one's transaction has a too lower fee-rate, it get stuck unconfirmed for a while. Increasing their transaction fees using Replace-by-Fee can be useful to speed it up, especially in these times, with a (really) full mempool.

**Comment by craigraw** [comment]
Unsure what you mean - it is implemented, and in fact turned on by default for all new transactions created by Sparrow. Try clicking on one of the inputs in the transaction view once you have created a transaction. You can edit it before you finalize the transaction for signing.

**Comment by louneskmt** [comment]
Yes, I found how to enable it on a transaction, but how can I use RBF to increase my transaction fees once it's signed and broadcasted, with Sparrow?

**Comment by craigraw** [comment]
That's easy - just create a new transaction that spends the same inputs you previously marked as RBF. You can add additional inputs or change other elements in the replacement transaction too - the RBF flag just means that those inputs with it enabled can be 'double-spent' and the replacement transaction won't be rejected once submitted to the mempool.

**Comment by louneskmt** [comment]
Mmmh okay, thank you. I was looking for an "Increase fees" option like on Electrum, which creates directly the same transaction I/o and just asks the new fee rate.

**Comment by craigraw** [comment]
That's a fair suggestion that I'll look into. Obviously, something will need to change otherwise the fee won't change. I expect that the preference is for the change output to reduce, but where that's not present additional inputs will be required.

**Comment by louneskmt** [comment]
Yes, on Electrum, the change is reduced according to the new fees. Thanks!

**Comment by bettyvschmartz** [comment]
How do you create a new transaction that spends the same inputs in the UI?

I agree that having a _boost_ or _speed up_ option would be useful. 

-- BVS

**Comment by craigraw** [comment]
You can do this from the Transactions tab. If the transaction is 
1. In the mempool
2. All inputs are RBF enabled
3. All inputs are from the wallet

then Sparrow will add a hover icon next to the transaction which looks like a hand with a cross above it. You can also right click to 'Increase Fee', which takes you to the Send tab with the transaction loaded, from where you can increase the fee (Sparrow may add another UTXO if there is insufficient change).

**Comment by bettyvschmartz** [comment]
The spent UTXO (one input) shows RBF enabled and ticked, and checked in a block explorer. All checks out. 

When I hover over it I just see the magnifying glass. The outputs (including change) have the send icon when I hover so they can be spent on. 

What am I missing? It's unconfirmed, one input with RBF, and all from the wallet. Is it because it's a consolidation tx, i.e. both outputs back to same wallet? 

-- BVS

**Comment by craigraw** [comment]
Appears there might be a bug here - will investigate.

**Comment by bettyvschmartz** [comment]
I removed my last comment by accident but basically, I wrote that all of the above requirements seem to have been met. There was only a magnifying glass icon by the transaction. There was one input (UTXO), RBF enabled, and from the same wallet. It was a consolidation tx, i.e. it spent back to same wallet with both outputs including change so not sure if that is the issue. It was also the only UTXO in the wallet as it's a test wallet. RBF should spend the same input so don't think that was the issue. 

I managed to subsequently CPFP using the change output from this tx and now the transactions are confirmed. Whilst the CPFP was confirming I could then see the symbol you refer to.

-- BVS

**Comment by craigraw** [comment]
Ok, I've fixed a bug to handle RBF fee increases for consolidation outputs in 525d57e. Previously, the consolidation output was not recognised as a payment for the replacement transaction (although the functionality to increase fee was present).

This doesn't explain the issue you had though, which I'm still unable to reproduce. Will have another go at trying to reproduce it using your notes.

**Comment by craigraw** [comment]
Found and removed a condition that required locktime = 0 for an transaction to be considered replaceable. https://github.com/sparrowwallet/drongo/commit/4d61585e4ce9fb346a44a875de47e9d5ff1cebe2
