### ISSUE TITLE
[Feature] Show proportional size of the inputs and outputs in graphical transaction views

### ISSUE THREAD

**Issue by alaznem** [sparrowwallet/sparrow#320]
# Problem

- General: The transaction view doesn't display the proportional size of the inputs and outputs, but I consider this information as highly relevant for interpreting a tx.
- Explicit example for forming a send tx: If using the privacy feature in the send tab, the coins being selected as STONEWALL inputs are relevant to the size of the resulting change. Maybe one likes to optimize the chosen inputs to the desired change outputs.

# Proposed solution

## Low hanging fruit
Extend on the left and right the tx strings with the pies which are available in the input & output overviews already:

![pie, tx-string, pie](https://raw.githubusercontent.com/alaznem/sparrow-issue-show-proportional-size-images/main/pie-tx-string-pie.png)

## Better UX
Make the strings as big as the relative size the input and output is contributing:

_This is a random example and more complex than the needed horizontal aligned input -> tx -> output flow view._

![flow arrows relative in size](https://i.pinimg.com/originals/7c/29/b9/7c29b9c8d6eab44c50f8225c30978306.jpg)

**Comment by craigraw** [comment]
Thanks for the suggestion. I tried varying the line thickness previously without good results, but I've now found a better way to indicate relative sizes, best illustrated in the diagram itself:

<img width="615" alt="Screenshot 2021-12-15 at 14 29 05" src="https://user-images.githubusercontent.com/862166/146187085-38871047-cdc4-4ceb-aa2d-61337a86f9e4.png">

All of the inputs and outputs sizes are shown as circles with radii proportional to the sum of the inputs. Where the input values are not known, the circles are not displayed. 

Implemented in aff872e.
