### ISSUE TITLE
[Feature] Show number of UTXOs in "UTXOs" view

### ISSUE THREAD

**Issue by dergigi** [sparrowwallet/sparrow#322]
It would be great to have something like "15 UTXOs total" below the list, or show it in the label above the UTXO list: "15 Unspent Transaction Outputs"

**Comment by elkimek** [comment]
+1

**Comment by craigraw** [comment]
Implemented in 3c94664. The UTXOs tab has been reworked as follows:

<img width="1150" alt="Screenshot 2021-12-07 at 13 29 41" src="https://user-images.githubusercontent.com/862166/145025763-6b57c594-4431-4424-9af2-33a1d062cdc5.png">
