### ISSUE TITLE
[Feature] Store Index of Last Active Tab (Child/Parent)

### ISSUE THREAD

**Issue by bettyvschmartz** [sparrowwallet/sparrow#326]
If there are multiple wallets open (wallet 1, wallet 2, wallet 3) and a transaction tab is opened from say wallet 2, upon close, you will be dropped back into wallet 3 (the last tab in sequence/index rather than the last _active_ tab).

It would be good if the index of the last active tabbedpane was stored so it reclaimed focus. More so, it would be good if these tabs had parent/child relationship so you could remember the last active parent where there are no child tabs remaining, otherwise flip back to each _last active child_. I thought about nested tabs but I know you also have account tabs to contend with so it doesn't want to be tab hell. 

-- bvs

**Comment by craigraw** [comment]
> If there are multiple wallets open (wallet 1, wallet 2, wallet 3) and a transaction tab is opened from say wallet 2, upon close, you will be dropped back into wallet 3 (the last tab in sequence/index rather than the last active tab).

Good idea! Implemented in e59ee47.

> It would be good if the index of the last active tabbedpane was stored so it reclaimed focus.

I confess I didn't really understand what you meant here - what is the 'tabbedpane' in this context?

**Comment by bettyvschmartz** [comment]
Sorry, @craigraw. A bad explanation. By _tabbedpane_ I was referring to each tab in _TabPane_. May have caused confusion. 

Looking at the commit, that fits the bill exactly. Thanks.

-- bvs
