### ISSUE TITLE
Sparrow crashes with GTK error when opening wallet

### ISSUE THREAD

**Issue by viking66** [sparrowwallet/sparrow#333]
I'm trying to run Sparrow on Ubuntu but I'm running into an issue when I try to open a wallet. Sparrow crashes with the following error:

```
(Sparrow:3011905): Gtk-WARNING **: 09:30:06.766: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(Sparrow:3011905): Gtk-WARNING **: 09:30:06.767: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

**Comment by viking66** [comment]
It appears this was a result of my Sparrow instance being in a bad state. I deleted my data folder (`~/.sparrow`) and after starting from scratch it appears to work as expected.

**Comment by viking66** [comment]
I got a step further after starting from scratch but now it's crashing with the same error when I try to open the import file menu (File > Open Transaction > File).

**Comment by craigraw** [comment]
I don't think this is a Sparrow issue specifically, but you can try the fixes mentioned here: https://bbs.archlinux.org/viewtopic.php?id=223801

**Comment by craigraw** [comment]
I'm closing this off as a GTK-related issue for now.
