### ISSUE TITLE
[Feature] Prevent copy&paste of seed words during keystore setup

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#337]
I understand it's easy to copy&paste the seed words during a wallet setup e.g. from a local text file. A storage of the seed on the online device shouldn't be encouraged though (even if the file isn't saved but just used for the temporary transfer - due to potentially wrong transfer on paper/steel later, after the wallet has been created). 

To stop the behaviour, I suggest to disabel copying seed word strings during setup (I think Electrum also enforces this).

But I get it if this isn't a loved feature, as there are valid use cases for copy&pasting seed words from the online device (recording of instruction videos with trough away wallets, creating multiple wallets for just a couple of small transactions etc.)

**Comment by alaznem** [comment]
> To stop the behaviour, I suggest to disabel copying seed word strings during setup (I think Electrum also enforces this).

Electrum does empty the clipboard between displaying and verifying the seed words. So the conveniant workaround for disposable wallets at electrum is to temporarily paste them somewhere and copy them again when electrum asks for verifying the seed words.

**Comment by RequestPrivacy** [comment]
This seems to be a good, balanced approach for both use cases. Although I'm more in favour of a complete disabling of copying the seed words. For the mentioned quick use cases, one should just simply choose a shorter seed to write it down quickly (e.g. just 12 words).

**Comment by craigraw** [comment]
I think the key point is that seed words should not be easily copyable *from* the wallet - this discourages online backups. Electrum is substantially different here as it allows copying of all the seed words at once, while with Sparrow you need to copy them one by one.

Pasting all the seed words at once I think is fine - as suggested above it's helpful to have this convenience feature available for certain use cases.

**Comment by RequestPrivacy** [comment]
> with Sparrow you need to copy them one by one.

This is indeed already a measure to discourage copying, although it could be seen as a bad UX from newcomers. Not being able to copy in the first place makes the point of "don't do this" more clear imho. But then once again - there are legit use cases.

It seems the best trade off is the one implemented. @craigraw from my point of view we can close the issue!?

**Comment by craigraw** [comment]
Agreed, closing this off.
