### ISSUE TITLE
[UX] Reorder the fee slider for Target Block view to lowest fee on the left.

### ISSUE THREAD

**Issue by RealDudePerson** [sparrowwallet/sparrow#338]
When sending a transaction you are presented with a fee selection that is great with one UX complaint. I found this out when I sent what I thought was a 1sat/vB transaction that ended up being a 1 block target transaction.

While if I was more careful I would have noticed this before broadcasting, it would be great to prevent the issue altogether.

When selecting by target block inclusion you are presented with a slider to select your target block. This slider ranges from highest fee on the left (indicated with red) to lowest fee on the right.
![image](https://user-images.githubusercontent.com/4443705/144484522-af916241-714d-4225-9298-f5edff33aa0f.png)

When you change the view to Mempool size, the slider changes to selecting the fee by vB. The slider's highest and lowest fee flips from highest on the left in the previous view to highest on the right in the current view.
![image](https://user-images.githubusercontent.com/4443705/144484872-5a0f8491-1ab3-4c6c-a5bd-6cad4d8e5560.png)

I have no background in UX design, but instinctively I want to say that the lowest fee should be on the left hand side of the slider, and the highest fee on the right hand side of the slider regardless of the number labels at the bottom.

**Comment by 6102bitcoin** [comment]
I understand why the sliders are arranged as they are - both are chronological with the smaller number on the left hand side. I agree that having the low fee end of the slider flip when toggling between the views could be confusing, I imagine this is why Craid added the colour gradient.

If the suggested change were implemented some users familiar with the wallet may accidentally pay an excessive fee. To avoid this a warning box could be added etc, but this would affect all users not just those who are used to the old (current) design.

**Comment by craigraw** [comment]
I understand the UX concern here, and I think the counterpoints are valid too.

One of the other things I don't like about making this change is that the high end of the slider (50+ blocks) is by definition vague - clearly it is rough estimate since we are trying to predict future mempool contention. I'm uncomfortable with a slider starting at a vague value and moving to a more precise one - it feels that the opposite should be the case (as is currently implemented).

Overall I'm leaning against this currently.

**Comment by craigraw** [comment]
On balance I think it's better to leave things as they are. Thanks for the suggestion though!
