### ISSUE TITLE
Unable to sign PSBT with Ledger Devices...

### ISSUE THREAD

**Issue by BTCHODL21** [sparrowwallet/sparrow#339]
Not sure if i'm missing something but I've imported my Unchained Vault into Sparrow, as part of experimenting I sent some Sats to a new address in Sparrow rather than the Unchained Address for the Vault. As a result I have a new UTXO in the Vault that Unchained can't see but Sparrow can.

My 2 of 3 keys are ledger (rightly or wrongly for this vault) so when I create a new PSBT to withdraw the UTXO to the Unchained recognised address I can't for the life of me work out how to sign it with the 2 ledgers.

I couldn't work it out before I updated the Bitcoin app on ledger to 2.0 and the firmware and also after the update.

Are there instructions for signing PSBT's generated by Sparrow with ledgers?

**Comment by craigraw** [comment]
I'm unclear from your post on what the setup of your Sparrow wallet is (and how it differs from the Unchained one). But in answer to your question:

It should be as simple as clicking the "Sign" button on the Transaction screen. The [guide for Coldcard](https://sparrowwallet.com/docs/coldcard-wallet.html#sending-bitcoin) does show the process, but the Sign button is greyed out there as the signing is done airgapped. For your wallet, it should be enabled. You should then see a dialog with the Ledger (whichever is connected) and you can sign from there.

**Comment by BTCHODL21** [comment]
I create the transaction, plug in the first of my ledgers and this is all I see:

![Screen Shot 2021-12-03 at 9 06 43 pm](https://user-images.githubusercontent.com/95472932/144584713-66f26b7e-ff68-4fce-ba97-e41577d53695.png)

**Comment by craigraw** [comment]
If you go to the wallet Settings, what Type are the keystores? They should be Connected Hardware Wallet.

**Comment by BTCHODL21** [comment]
"Watch only wallet" I didn't change anything after importing the wallet configs. Do I need to re-import each of the keys and can I assume that doesn't do anything detrimental to the multisig vault?

**Comment by craigraw** [comment]
You need to create a new wallet, replicating the current Sparrow wallet but importing the Ledger(s) as Connected Hardware Wallets (I'm still not clear if your Sparrow wallet is single or multisig). There's no risk to funds in doing this.

**Comment by BTCHODL21** [comment]
I did an File > Import Wallet > Caravan Multisig 

and then imported the json file. It's then set up the keystores as watch only wallets.

**Comment by craigraw** [comment]
That's strange. Can you compare your caravan json file with the sample one at https://github.com/sparrowwallet/sparrow/blob/master/src/test/resources/com/sparrowwallet/sparrow/io/caravan-multisig-export-1.json?

Sparrow looks at the field `"method"` in `extendedPublicKeys` to determine the keystore type. e.g.
```
"method": "ledger"
```

Does yours differ?

**Comment by BTCHODL21** [comment]
There's no method field in the json

**Comment by craigraw** [comment]
Ok that explains it, although I'm unclear why they weren't included. It may be easiest to add the fields to the json file and import the file again.

**Comment by BTCHODL21** [comment]
Yep will try that in the morning, thank you so much! Will let you know. Have let unchained know too.

**Comment by BTCHODL21** [comment]
That worked a treat once I remembered to add an additional , after the prior label. All working perfectly now, thanks for the assistance. I've suggested that unchained add the label to the output when they generate the JSON too, can't believe i'm the first to bump up against this but least we worked it out.
