### ISSUE TITLE
Mempool type fee selection (mb to tip)

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#34]
![image](https://user-images.githubusercontent.com/388716/97796173-15139e00-1be5-11eb-8903-5bc66cfc5bb2.png)

I always use X mb from tip when selecting a fee,  Could be said if I choose 10mb from tip that it's "in 10 blocks" (assuming no added transactions)

But right not this seems to be an estimate over an unspecified time period.

Current mempool, 
![image](https://user-images.githubusercontent.com/388716/97796433-feb71380-1bdf-11eb-8d19-a09f898c40f3.png)
(https://mempool.space/mempool-block/1)

**Comment by craigraw** [comment]
This is an interesting idea, and might be possible with Electrum server protocol. Will consider implementing.

**Comment by craigraw** [comment]
Released in 0.9.8

**Comment by Transisto** [comment]
Is this what's supposed to be shown?
![image](https://user-images.githubusercontent.com/388716/102269746-12e27600-3eeb-11eb-9aeb-cb6a17f2c14a.png)

Usually I'd expect, Fee to pace a transaction at 0.5, 0,75, 1, 2mb 10mb from tip.

**Comment by craigraw** [comment]
It should look like this: 
<img width="793" alt="Screenshot 2020-12-16 at 10 54 47" src="https://user-images.githubusercontent.com/862166/102328229-74f4b700-3f8f-11eb-8503-caf1593f22be.png">

Hovering over the chart then gives the information you're looking for:

<img width="331" alt="Screenshot 2020-11-20 at 15 40 35" src="https://user-images.githubusercontent.com/862166/102328609-f51b1c80-3f8f-11eb-88c5-dd173c027301.png">


It would appear the Electrum server you are connecting to doesn't support the `mempool.get_fee_histogram` call - can you share details of which server implementation you're using?
