### ISSUE TITLE
Feature Request: Support for importing wallet.dat files?

### ISSUE THREAD

**Issue by jsgalt** [sparrowwallet/sparrow#340]
I know it's a PIA, but it also such a PIA to access ancient wallet.dat files already that a fully-featured wallet like sparrow supporting it would be a god send.

Not saying you should let people make wallet.dat files, just import and extract keys from then. 

I do recovery for people sometimes and no one except bitcoin core seems to support this ancient file format. I know there's more advanced tools to extract keys from them, but having a clean interface that supports it would be lovely.

Cheers guys. Great wallet.

**Comment by craigraw** [comment]
Unfortunately this is probably not going to happen - it would mean supporting outdated versions of BerkeleyDB across all platforms, not to mention handling the outdated ways that Bitcoin Core used to store keys (not HD wallets). I know it's a PITA, sorry!

**Comment by craigraw** [comment]
Unfortunately any reading of the file would require BerkeleyDB - it is a binary format native to that library.
