### ISSUE TITLE
Grammatical Error on Help Page

### ISSUE THREAD

**Issue by NyamiDev** [sparrowwallet/sparrow#341]
Hi,

Thank you for a great product. Just a small typo found at:

https://sparrowwallet.com/docs/mixing-whirlpool.html
Chapter: Other mixing clients

in this sentence: 

The Samourai CLI comes as part of the Ronin Dojo node package, and can also be run **_as_** on its own or connected to the Samourai GUI desktop tool.

I think the highlighted word 'as' should be taken out. 

Cheers,

NyamiDev

**Comment by craigraw** [comment]
Thanks, fixed!
