### ISSUE TITLE
Signatures missing from txhex after signing a tx that spends input present in previous unbroadcasted tx

### ISSUE THREAD

**Issue by mandelbit** [sparrowwallet/sparrow#343]
I constructed and signed a transaction, all successful and ready to broadcast (included sigs). Shortly after (before broadcasting) I needed to change the output amounts, so I refrained from broadcasting the old signed txhex in order to create a new transaction using the same inputs with my revised outputs (to same output addresses). 

Now when I sign with the HWW, all of the UX flow looks smooth while signing the tx, however the resulting txhex is actually unsigned (nothing to indicate this in Sparrow UI except a shorter txhex which, having checked, misses the necessary input signatures). 

Having checked the blockchain, I can see for certain that the previous 'superceded' transaction was not broadcast, however there seems to be something stopping Sparrow from signing the nex transaction that uses the same utxos as input, and whatever the error, it doesn't seem to be handled by Sparrow or communicated in the wallet.

So far tried the following simple attempts at resolution:
- restarted Sparrow
- updated to the latest 1.5.2 release of Sparrow
- restarted HWW

Still the same issue with missing sigs, and seemingly unable to sign the transaction using Sparrow.

**Comment by craigraw** [comment]
What HWW is this? It seems likely that the issue lies there - it may be refusing to resign the same inputs. There's nothing in Sparrow itself that I can think of which would prevent this.

**Comment by xsats** [comment]
This was using a BitBox02. I ended up using another input which did work. You're probably right - likely not caused by Sparrow so closing the issue

**Comment by mandelbit** [comment]
This was a Bitbox02. Ended up using different inputs which worked for now. Closing as you're probably right that the issue lies with the HWW.
