### ISSUE TITLE
doubled balance bug when mix occurs

### ISSUE THREAD

**Issue by elkimek** [sparrowwallet/sparrow#344]
I'm having some kind of weird balance bug where when a Whirlpool notification appears the balance gets doubled. When I refresh the wallet, the bug disappears and the total balance get correct sum.

**Comment by craigraw** [comment]
Do you mean the balance on the Transactions tab? Is this with v1.5.2?

**Comment by elkimek** [comment]
Yes. In v1.5.3-beta1

**Comment by craigraw** [comment]
Could be a server-related problem - I've had no other reports or experienced this myself.

If you experience it again, please check the transactions table to see if there are any transactions that don't make sense.

**Comment by elkimek** [comment]
I already did, it seems to me it's just a display bug. No odd UTXOs when compared before bug, with bug and after bug (refresh).

Thought I'm not sure if it's not electrs related as I and few others are having very similar issues on RoninDojo [feat_electrs_update test branch](https://code.samourai.io/ronindojo/) where is also electrs 0.9.3 Balances getting doubled and Dojo sees spent transactions as unspent. Though there is no easy option to refresh the wallet like in Sparrow and every new import ends with wrong result.

**Comment by craigraw** [comment]
Thanks for the information - likely server-side then. Hopefully they will fix this soon.

**Comment by elkimek** [comment]
cc @romanz then :)

**Comment by romanz** [comment]
Is it possible to reproduce it on regtest/signet?

**Comment by elkimek** [comment]
It would be hard if not impossible since the issues are related to postmix accounts only. Note that on Dojo the import process is three times "heavy" since there is like-type change output from postmix txs. Not sure if that's case for Sparrow right now.

**Comment by craigraw** [comment]
Closing this off as not a Sparrow issue.
