### ISSUE TITLE
[UX/UI] Enhance design of tx-graph in send tab

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#345]
The current tx graph in the send tab is reduced to the minimum (meant in a positive sense) and therefore easily understandable. I guess we could add a little more information for fast sanity checks - either by stating the absolute and/or relative amounts of each inputs and putputs. 

For even faster understanding of the transaction one could add visual hints like "loading bars" or "arrow thickness" according to the relative "weight" (in terms of send amount) of each utxo. Example 5) is inspired by the transaction representation of [oxt.me](https://oxt.me/), see random example used [here](https://oxt.me/graph/transaction/tiid/3817444656).

Please excuse my limited design skills as it was just intended as a fast sketch. 

![sparrow_UI_proposal](https://user-images.githubusercontent.com/72392544/145009884-3bc3da9f-0e54-4d72-b2ff-73535c9a4b2e.png)

**Comment by craigraw** [comment]
Thanks for the suggestions. Please see https://github.com/sparrowwallet/sparrow/issues/320#issuecomment-994751040 for how this has been implemented.
