### ISSUE TITLE
Computer Camera Error - "Your system is missing a dependency..."

### ISSUE THREAD

**Issue by anon5022** [sparrowwallet/sparrow#351]
I'm trying to utilize my built-in webcam for scanning QR codes for wallet access but keep getting the error stating, "Your system is missing a dependency required for the webcam."

I've tried the suggestions listed under the FAQ section on the Sparrow website but am still having the issue occur. Any help would be greatly appreciated.

**Comment by craigraw** [comment]
A good place to start is to read #102 which is similar. The key to solving this is to find what dependency is missing from your system when the native camera libraries are loaded. The native camera libraries are expanding in a folder that looks similar to `C:\Users\XXXXX\AppData\Local\Temp\BridJExtractedLibraries16774346556145691140\`. This location should be reflected in an error in the sparrow log file when the camera is opened (See the Sparrow Help menu to find the log).

To find the native libraries, you need to run Sparrow, try open the camera, check in the log for the folder path (it may have changed), then look in that folder (without closing Sparrow) for the native libraries. Then, you need to open these .dll files (particularly `OpenIMAJGrabber.dll`) in a dependency checker to find out why they can't load.

The dependency check I use is https://github.com/lucasg/Dependencies - if you open the .dll in that application it should show if there are any dependencies missing.

Please let me know what the results are, and if you get stuck doing any of the above.

**Comment by anon5022** [comment]
Thanks for the steps to get me started. Here's what I got from the sparrow log file after attempting to use the webcam: 

Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\xxxxx\AppData\Local\Temp\BridJExtractedLibraries10884500527848021030\OpenIMAJGrabber.dll'
	at com.nativelibs4java.bridj@0.7-20140918-3/org.bridj.BridJ.getNativeLibrary(Unknown Source)
	
How do I go about looking into the folder for the native libraries? After that, I'm not quite sure how to use the dependency checker that you linked to above in order to discover the reason for the error.

I honestly may be in way over my head here so if you don't have the time to lead me through, I completely understand.

**Comment by craigraw** [comment]
You should able to get to the AppData folder by searching for `%APPDATA%` in the Windows desktop search. Browse to the folder in Explorer from there. Note Sparrow needs be running after trying the camera as mentioned above for the files to be present.

You need to install the dependency checker from that page on your system - there is a download link to a .zip file at the top.

**Comment by kwikslvr** [comment]
I'm running into the same camera issue on my Surface Pro running Windows 10 (64bit) with the latest version of Sparrow (1.6.6), and can't solve it despite going through all the debugging steps above.  I checked the log which identified the OpenIMAJGrabber.dll not being loaded.  So I ran the dependency check and it said msvcp100.dll was missing.  I found that file in a different application subfolder so copied it to my C:Windows\System32 folder, as well as my C:Windows\SysWOW64 folder, restarted Sparrow and tried the camera again but still get the same error.  Rebooted and tried again -> same error.  Tried downloading/repairing the .dll by getting it directly from Microsoft Visual C++ Redistributable latest supported downloads, but still no luck.  What else can I try?  Dependencies is still showing this for some reason:
![missing_dll](https://user-images.githubusercontent.com/106134192/190075470-49db1852-fc74-486d-ac6a-2d2aa1084454.png)
Any other suggestions?  Where is OpenIMAJGrabber trying to look for the msvcp100.dll but can't find it?

**Comment by craigraw** [comment]
Have you tried loading MSVCP100.dll in the dependency checker? Maybe try rebooting?

**Comment by kwikslvr** [comment]
@craigraw Thanks for the quick reply! I tried rebooting and it didn't help.  Just checked the dependencies of msvcp100.dll and it showed 2 missing .dll files. One was msvcr100.dll, but that is *not* missing - I had found it and put it in the same folders at the same time the msvcp100.dll file (again, goes to my question of where it's looking for these files that it can't find them).  The other missing one is this, which I have no idea where to find it, or how to resolve the issue:
![2022-09-14 12_18_41-Dependencies (x64)](https://user-images.githubusercontent.com/106134192/190243833-0d252e17-57a0-4ca9-9e37-fe3c7f6dc11a.png)

Incidentally, I also checked the dependencies of msvcr100.dll and it was all good.

**Comment by kwikslvr** [comment]
Okay, so I managed to get my camera working within Sparrow!  Found a better source for updated .dll files than Microsoft's website as suggested in the Sparrow FAQ.  I downloaded 64 bit versions of both msvcr100.dll and msvcp100.dll from here instead: https://www.dll-files.com/
Dropped the files into my Windows\System32 folder, started Sparrow, and everything worked!

**Comment by craigraw** [comment]
Great, thanks for the feedback. I've added this to the FAQ at https://sparrowwallet.com/docs/faq.html#your-system-is-missing-a-dependency-for-the-webcam.

**Comment by editor-Ajian** [comment]
**You may place .dll file in wrong path (like me), use `dependencies` software to check your `msvcr100.dll` in `system32` folder and `syswow64` folder.**

I meet the same problem, and can not fix it with the suggestion in FAQ. Then I find this issue and download the `dependencies` software.
After trying many source to download `msvcr100.dll` file and fixes issued by Microsoft but still being stuck, I decide to use `dependencies` to check my `msvcr100.dll` s in different folders. And that is the answer - I happened to put the files in wrong path.

So my advice is that, after download .dll files in https://www.dll-files.com/, please use `dependencies` to see where it should be. A file which should be `system32` folder, will show its dependencies in `system32` folder. 

My OS is 64-bit Windows 11.

**Comment by craigraw** [comment]
Closing this off as solved (at least as much as is possible).
