### ISSUE TITLE
Debian File Differs From Built Source

### ISSUE THREAD

**Issue by RobertMiranda** [sparrowwallet/sparrow#353]
Followed doc here: https://github.com/sparrowwallet/sparrow/blob/master/docs/reproducible.md

Downloaded Debian file here: https://github.com/sparrowwallet/sparrow/releases/download/1.5.3/sparrow_1.5.3-1_amd64.deb

command: 
diff -r /home/user/sparrow/build/jpackage/sparrow_1.5.3-1_amd64.deb /home/user/Downloads/sparrow_1.5.3-1_amd64.deb

result: 
differ

Not sure if I am doing this correctly but the command:
diff -r build/jpackage/Sparrow  /home/user/Downloads/Sparrow
returned no output

**Comment by craigraw** [comment]
The `.deb` installers are not yet reproducible (mostly due to file timestamps).

> Not sure if I am doing this correctly but the command:
> diff -r build/jpackage/Sparrow /home/user/Downloads/Sparrow

If `diff` returns no output, then the two folders are identical. It sounds like you reproduced the release binary successfully!

**Comment by RequestPrivacy** [comment]
Interesting that a Debian built produces no `diff` like in #197? What makes the difference?

**Comment by craigraw** [comment]
If you're referring to the bug fixed for JDK18, I'm not sure what triggers it. I've never encountered it myself. Perhaps it is building on a non-Debian system where it occurs.

**Comment by RobertMiranda** [comment]
> The `.deb` installers are not yet reproducible (mostly due to file timestamps).
> 
> > Not sure if I am doing this correctly but the command:
> > diff -r build/jpackage/Sparrow /home/user/Downloads/Sparrow
> 
> If `diff` returns no output, then the two folders are identical. It sounds like you reproduced the release binary successfully!

Thanks. I did the build on Ubuntu 20.04.1.

**Comment by craigraw** [comment]
Great, closing this off.
