### ISSUE TITLE
Difficulty connecting to cloud RaspiBolt testnet node

### ISSUE THREAD

**Issue by thunderbiscuit** [sparrowwallet/sparrow#354]
Hello, and thanks for the awesome wallet! It's a superb piece of software for advanced users.

I've been working my way through the RaspiBolt guide on a cloud machine, trying to get a full testnet setup working. Things are going well, except that I'm at the point where I'm trying to get Sparrow to connect to my Electrum server on the node and for some reason I just can't seem to get it working.

See [this comment](https://github.com/raspibolt/raspibolt/issues/808#issuecomment-989910246) for my current configurations. I can easily connect Sparrow to an Umbrel setup so I know that side of things is working, but I'm wondering if you'd have any ideas as to what I'm doing wrong, maybe on the RaspiBolt side, maybe in combination with some Sparrow config. Because of the number of variables at play I suspect it's just a combination of things (firewall, Tor, NGINX, SSL) I'm not quite aligning properly.

The error I'm getting on the Sparrow side is mostly this one:
```shell
Could not connect:

Error getting fee estimates
```

This is with with the port `60002` configured in Sparrow and the SSL toggle at `on`, _as well as_ with my other Tor address (see Stadicus example for the Tor without SSL config) directed at port `60001` with the SSL toggle `off`.

Any ideas where I might be going wrong?

**Comment by thunderbiscuit** [comment]
Issue was fixed as per a tip by @Stadicus to turn the bitcoind config `blocksonly` toggle off. Cheers!

**Comment by Stadicus** [comment]
Nice! I'm linking the Sparrow wallet issue for completeness https://github.com/sparrowwallet/sparrow/issues/354
