### ISSUE TITLE
Mempool chart labels

### ISSUE THREAD

**Issue by cutiful** [sparrowwallet/sparrow#355]
If you hover over the mempool chart, it shows labels like "1+ vB: 0.24 MvB". This doesn't make much sense to me, as `mempool.get_fee_histogram` call returns fee to size relations. Shouldn't the label at https://github.com/sparrowwallet/sparrow/blob/ced4d4d337a1752fddaa35fb05ea889200d22e42/src/main/java/com/sparrowwallet/sparrow/control/MempoolSizeFeeRatesChart.java#L84 be "+ sat" instead of "+ vB"?

**Comment by craigraw** [comment]
Thanks - it should be "+ sats/vB". Fixed in 4cbb402.
