### ISSUE TITLE
Unable to import multisig coldcard

### ISSUE THREAD

**Issue by heredia21** [sparrowwallet/sparrow#357]
Getting the error:

Failed to import. name must be ascii, 1..20 long multisig.py:683

Tried again changing the wallet name.. Got "my key not included" multisig.py:691

**Comment by craigraw** [comment]
These are two different errors, probably.

You should be able to edit the wallet name to a shorter one by editing the Coldcard export .txt file directly.

The "my key not included" suggests that the Coldcard was not involved in creating the multisig wallet. Did you export from it when setting up the wallet in Sparrow?

**Comment by heredia21** [comment]
Ah, you're right. Error on my part. Didn't realize I had to input the passphrase I set before importing. All good.
