### ISSUE TITLE
Not able to sign a transaction with Ledger

### ISSUE THREAD

**Issue by finned-palmer** [sparrowwallet/sparrow#361]
I'm trying to combine several segwit UTXOs and spend them to a separate wallet, but each time I go to sign the TX via my Ledger I get this error "Non-witness UTXO does not match outpoint hash".

This is on Sparrow version 1.5.4 on Linux.

I have previously only sent single UTXOs using Sparrow, this is the first time I've tried combining them.

**Comment by craigraw** [comment]
Thanks for bug report, duplicate of #356. Expect a new release shortly with this fixed.

**Comment by finned-palmer** [comment]
Great, thanks for the quick response.

**Comment by craigraw** [comment]
ICYMI - Sparrow v1.5.5 fixes this problem.
