### ISSUE TITLE
Error broadcasting transaction

### ISSUE THREAD

**Issue by wordkeepa** [sparrowwallet/sparrow#362]
Getting this error second day. Before that everything was fine.

![image](https://user-images.githubusercontent.com/55933816/146297900-d65c26cb-001c-475c-9de7-ff5a291d1a66.png)

Please help.

**Comment by craigraw** [comment]
Thanks - this is (very likely) a duplicate of #356. There will be release out today to fix it.

**Comment by craigraw** [comment]
ICYMI - Sparrow v1.5.5 fixes this problem.

**Comment by wordkeepa** [comment]
Thank you!

Best,
WK

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
