### ISSUE TITLE
[Feature] Allow to regenerate BIP39 when create software wallet in fast way

### ISSUE THREAD

**Issue by CruiseMan** [sparrowwallet/sparrow#364]
**Issue** No quick/convenient way to regenerate mnemonic words
**Motivation** I need to have  this option to regenerate words if they long, harder to write-down, spell, memorize or even enter then on hardware devise (the best to used on hardware if they short and words begins with latter from beginning of alphabet), that will allow faster entry on hardware advise, easy to memorize (yes i do that sometimes) 
**Possible solution:** Add `Generate` button next to `Valid checksum`
<img width="644" alt="Screen Shot 2021-12-16 at 3 09 05 PM" src="https://user-images.githubusercontent.com/15807643/146462410-c6c59850-0507-4051-8a51-4179a98246ba.png">

**Comment by craigraw** [comment]
You can always click the `Enter 12 Words` button and then `Generate New` again. One extra click perhaps, but not too bad?

**Comment by CruiseMan** [comment]
> You can always click the `Enter 12 Words` button and then `Generate New` again. One extra click perhaps, but not too bad?

Yes, extra click that the whole point. I simply want to click on one button. That would be very convenient, Thank you Craig.

**Comment by 6102bitcoin** [comment]
IMO an extra button to save one click for a niche use case is unlikely to merit the effort. 

> (the best to used on hardware if they short and words begins with latter from beginning of alphabet), that will allow faster entry on hardware advise, easy to memorize (yes i do that sometimes)

A friendly warning that by doing this you are reducing the security of your wallet. There are only 88 bip39 seed words that are 4 or fewer characters which start with a, b or c. Thus you have much lower security than the recommended minimum of 128bits (88^11 is less than 2^22 which is << 2^128)
