### ISSUE TITLE
Inconvenient change of behavior

### ISSUE THREAD

**Issue by GambolingPangolin** [sparrowwallet/sparrow#365]
## Old behavior (1.5.2)

When you create a multisig wallet, the ordering of the key descriptors inside the associated output descriptor agrees with the ordering of the keystores.

## New behavior (1.5.5)

The ordering might no longer agree.  If you copy the output descriptor and paste it into a new wallet e.g. for a read only replica, the keystores are in a different sequence than when the wallet was created.

## Example

* Keystore 1:
  - `7d53a98b`
  - `m/48h/1h/0h`
  - `tpubDCTdp859bEYi2hbEdz1LCJUhUvrvoWwfLwW2bnoH8Be6QZ8C16VzmwriQMu4rV6H4XmfmLmbL42JynjFDq45uTohECJT9TBGqNsr9tG5Y2Z`
* Keystore 2: 
  - `fc8f9aec`
  -  `m/48h/1h/0h`
  - `tpubDCuoHtk3Wv2P3G41a9sHQmZRoibqfX7GZXCogR4dRQRDJMe4dheUmaanDybQ2N8sVzdhZs6r38Dmqep5ZukTGNe58cQhT44perp5GdVyPwB`

Here is the resulting descriptor:

```
wsh(sortedmulti(1,[fc8f9aec/48h/1h/0h]tpubDCuoHtk3Wv2P3G41a9sHQmZRoibqfX7GZXCogR4dRQRDJMe4dheUmaanDybQ2N8sVzdhZs6r38Dmqep5ZukTGNe58cQhT44perp5GdVyPwB/<0;1>/*,[7d53a98b/48h/1h/0h]tpubDCTdp859bEYi2hbEdz1LCJUhUvrvoWwfLwW2bnoH8Be6QZ8C16VzmwriQMu4rV6H4XmfmLmbL42JynjFDq45uTohECJT9TBGqNsr9tG5Y2Z/<0;1>/*))#8lhue9a7
```

## Discussion

In both cases the set of scripts belonging to the wallet is the same, due to the choice to use `sortedmulti` (canonicalizing the key order in scripts).  So I think that Sparrow should respect the user-supplied keystore ordering.  This user would like to order the keys in a specific way to make a certain process simpler :grin:

**Comment by craigraw** [comment]
While I understand that a change in behaviour can be less than ideal, it seemed better to me to have a canonical output descriptor rather than one than is user-defined. In trying to encourage users to backup their output descriptors for multisig wallets, it is simpler to verify your backup when the descriptor is canonical since no knowledge of the output descriptor format is required.

**Comment by GambolingPangolin** [comment]
What backup verification strategy do you have in mind here?  I don't see one which is plausible but would fail if the descriptor were not canonicalized.

**Comment by craigraw** [comment]
If one did not understand a descriptor (probably a common situation) then a different order of adding keystores would make a "reconstructed from seeds" wallet descriptor appear different to the original descriptor backup.

When making this decision I couldn't see a good reason *not* to canonicalise - but perhaps there is one?

**Comment by craigraw** [comment]
> you could pop up a confirmation that they are going to be reordered before letting them save the wallet?

I've tried to avoid popups in Sparrow as much as possible. Also, I think this would be difficult to communicate well, and this would probably cause more consternation than benefit (as would reordering the keystore tabs automatically). I do agree it's not ideal that the keystore tab order does not match the canonical list - it's just that I don't see a good UX to solve this at present. 

Re your use case, do keystore labels (or failing that, master fingerprints) not address this?

**Comment by GambolingPangolin** [comment]
Yes, master fingerprints unambiguously identify the keystore belonging to each signer.  However, in my experience there is less friction if you can communicate to each signer the keystore position that they own.  So I think I'll continue to do this, taking care to use the descriptor to figure out the positions rather than the input order when I'm setting up the first instance of the wallet.

I suppose that you are right that telling the user about the difference between the displayed keystore order and the order in the descriptor is likely to be confusing for the majority of users, if you show them at the wrong time.  Spitballing, how about putting some text in the "Edit Descriptor" window that points this out if the orders differ?  Maybe that strikes the right balance between being TMI for most folks, but being really helpful if the user assumes that the keystore order will be the same in the descriptor.  FWIW it took a while to figure out that this change of behavior was breaking my process because I had to go back and forth with my signers.

**Comment by 6102bitcoin** [comment]
It appears that the conclusion of this issue is a suggested enhancement: Add Text in the "Edit Descriptor" window that notified the user that the entered keystore order is not canonicalized, but the descriptor is.

**Comment by craigraw** [comment]
Added in a76d9db.

<img width="681" alt="Screenshot 2022-01-05 at 13 11 08" src="https://user-images.githubusercontent.com/862166/148208925-11bef2e5-8754-4c8d-8b5b-d8d2b5305ab9.png">
