### ISSUE TITLE
payment to sparrow paynyms possible or not possible?

### ISSUE THREAD

**Issue by Ziya-Sadr** [sparrowwallet/sparrow#366]
I'm playing around with sparrow wallet (testnet obvsly) and tried sending an amount from samourai wallet to the paynym provided in sparrow wallet. It's sent but not received in sparrow. Is sparrow actually supposed to receive such payments? if not, I guess it should be noted somewhere so users won't make such a mistake with real funds!

**Comment by craigraw** [comment]
It's not currently possible no (Sparrow does not support BIP47 at this time). This is noted in the docs - see the second paragraph that covers the "Paying to a PayNym" functionality: https://www.sparrowwallet.com/docs/spending-privately.html#paying-to-a-paynym.

**Comment by eabrosius** [comment]
I just made this misstep as well (assumed I could send from samourai to my sparrow paynym). Are the funds lost or is there a way to retrieve them?

**Comment by craigraw** [comment]
The comment I made above is now out of date - as of v1.6.0 Sparrow supports BIP47 and PayNyms, which are interoperable with the Samourai implementation. If the PayNyms have been linked, Sparrow will pick up the funds. Open the PayNym dialog in Sparrow and follow the Samourai PayNym to find the reverse link if necessary.

**Comment by eabrosius** [comment]
Hmm interesting... can't seem to figure out what's going on. The paynyms were linked on both ends prior to transaction. Attached are some screenshots of sparrow and samourai. Any idea what I can try next?
![Screen Shot 2022-04-29 at 7 30 06 AM](https://user-images.githubusercontent.com/6733936/165948530-3454b139-a624-42fc-800d-f3567e23ca46.png)
![Screen Shot 2022-04-29 at 7 30 31 AM](https://user-images.githubusercontent.com/6733936/165948534-86c10076-3807-406a-b7b3-11ab36d92596.png)
<img width="325" alt="Screen Shot 2022-04-29 at 7 57 46 AM" src="https://user-images.githubusercontent.com/6733936/165948791-08e44b2b-f07b-481c-94d7-4c6b313be5ed.png">
<img width="324" alt="Screen Shot 2022-04-29 at 7 58 04 AM" src="https://user-images.githubusercontent.com/6733936/165948805-92c67552-216e-4fd0-b62f-c479146bc947.png">
<img width="326" alt="Screen Shot 2022-04-29 at 7 58 13 AM" src="https://user-images.githubusercontent.com/6733936/165948814-563981fb-2a7a-4c15-b82b-267cf3c743d2.png">

**Comment by craigraw** [comment]
Ok, it looks like Sparrow has picked the notification transaction and created the PayNym wallet - I can see the address you paid to in txid `e71de5bfe0c59b8f9b55e8d36112f9d5ae51ba6f2a229c8e1f3cc57b04899328` reflected in that wallet above as the first address.

At this stage, it just looks like that wallet hasn't synced yet - is Sparrow connected? Have you tried to refresh (View menu)?

**Comment by eabrosius** [comment]
Yes it is connected and I have refreshed many times. I have successfully received other txs (regular non-paynym txs) since the paynym tx in question. Does it have something to do with the fact that I am connected via bitcoin core and not electrum?

**Comment by craigraw** [comment]
Yes - unfortunately the Bitcoin Core connection does not support PayNyms yet. Try a public server and your txes should appear (or setup a private Electrum server).

**Comment by eabrosius** [comment]
Got it. The tx shows up when I switch to a public server. 

One more question before I stop bugging you... If I want to switch back over to using Core as my connection method, what do I need to do prior to doing so in order to regain access to the funds from that paynym transaction? Guessing I'll need to send them back to samourai (or some other wallet), flip back to Core, and then send the funds back to sparrow...?

**Comment by craigraw** [comment]
Yes - or a better solution IMO is to install a private Electrum server alongside Bitcoin Core.
