### ISSUE TITLE
Feature request: Sweep funds from an OpenDime

### ISSUE THREAD

**Issue by satrinity402** [sparrowwallet/sparrow#369]
https://opendime.com/

I would like the ability to use Sparrow Wallet to sweep funds from an OpenDime. According to the website [FAQ](https://opendime.com/faq), in order to sweep funds, the wallet used to sweep must support **WIF-format private key import**

**Comment by 6102bitcoin** [comment]
Sparrow curretly has no private key sweep functionality. In sparrow wallet configurations are specified in the output descriptor. A single priv key has no output descriptor. I don't know whether sparrow could cleanly import a priv key. 

I imagine a compromise could be a sweep feature accessible from the tools menu where a user can enter a privkey (WIF) and specify the address to be sent to (with an option to select an open wallet) similar to how the mix-to wallet feature works with whirlpool

Thoughts @craigraw ?

**Comment by craigraw** [comment]
> I imagine a compromise could be a sweep feature accessible from the tools menu where a user can enter a privkey (WIF) and specify the address to be sent to (with an option to select an open wallet) similar to how the mix-to wallet feature works with whirlpool

Yes, this is a good description of how it could be reasonably achieved. On the roadmap, seems like a useful feature.

**Comment by craigraw** [comment]
Implemented in 9c3b647.

<img width="792" alt="Screenshot 2022-01-12 at 15 46 06" src="https://user-images.githubusercontent.com/862166/149152032-0e396f56-5690-47e4-98bb-4f949e6be78a.png">
