### ISSUE TITLE
UXTO mixing process bars stay visible.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#373]
![image](https://user-images.githubusercontent.com/388716/147364364-d1697fc3-2a7b-43af-9bd6-6f3c14207899.png)

**Comment by craigraw** [comment]
This is a problem with the server - Sparrow is expecting to receive notification that the mix transaction has been broadcast, but that notification has not been sent by the server. So, if the server is working correctly, Sparrow is correctly reflecting the state of things. What is much more likely is that the server is broken and failing to do its job. Sparrow cannot fix this, so I'm closing this off - it's an issue that needs to be solved in the server software.
