### ISSUE TITLE
"create transaction" function is not selectable

### ISSUE THREAD

**Issue by jonjonez** [sparrowwallet/sparrow#38]
When filling in the address fields, values and specifying the fee in the dynamic bar. Even filling in all these values, the 'create transaction' button is not available,

I've tried everything:

- Electrum server configured
- wallet has sufficient amounts + fee
- I did tests selecting UTXO's
- I made tests sending from Trezor, bluewallet, all with sufficient balances

NOTE: Electrum server is working and the sparrow wallet is synchronizing the balances correctly.

See the images below:

**Comment by jonjonez** [comment]
![sparrow-wallet01](https://user-images.githubusercontent.com/23480437/99732058-91d7c080-2a9d-11eb-90b9-c77b4400e728.png)
![sparrow-wallet02](https://user-images.githubusercontent.com/23480437/99732068-94d2b100-2a9d-11eb-96c0-0f04843ff298.png)

**Comment by craigraw** [comment]
Label is a required field. Sparrow uses this to label the transaction and associated UTXOs.
