### ISSUE TITLE
UX: Minor Changes to Gordian Seed Tool Instructions

### ISSUE THREAD

**Issue by ChristopherA** [sparrowwallet/sparrow#380]
Using Sparrow (macOS 1.5.5) and Gordian Seed Tool (iOS 1.3).

In Sparrow, I do "New Wallet" named "Singlesig Watch Only" test.

I click on Airgapped Hardware Wallet, and "Seed Tool":

This should probably be more properly labeled "Gordian Seed Tool"

Under details for this, it says in Gordian Seed Tool:

"Authenticate/Derive Key/Other Key Derivations/Account Descriptor"

Until you support `crypto-request` this instead probably should be:

"Authenticate/Derive Key/Other Key Derivations/Bitcoin/Mainnet/Master Key/Secondary Derivation/Account Descriptor/Share Button"

![2C7963D5-4887-42FD-AF05-745FFE920537](https://user-images.githubusercontent.com/69103/147988664-49e85047-35d8-43de-aa17-44abe4700f0c.png)

![3B063175-CBCB-4BAE-955D-1B17C127ED3F](https://user-images.githubusercontent.com/69103/147988862-d55975c9-7457-44e4-98fe-2300b35f0e93.png)
![BC0AE89C-272A-4C96-B64E-A5279C5E333C](https://user-images.githubusercontent.com/69103/147988869-dd4b9938-cc2d-49db-81de-0bd73233f869.png)

/cc @wolfmcnally @shannona

**Comment by craigraw** [comment]
Implemented in bbdfec1. Seed Tool is now renamed to Gordian Seed Tool and instructions have been updated.
