### ISSUE TITLE
BUG: no success/no error scanning ur:crypto-hdkey

### ISSUE THREAD

**Issue by ChristopherA** [sparrowwallet/sparrow#381]
Using Sparrow (macOS 1.5.5) and Gordian Seed Tool (iOS 1.3).

In Sparrow, I do "New Wallet" named "Singlesig Watch Only" test.

I click on Airgapped Hardware Wallet, and "Seed Tool".

If I don't use the Account Descriptor (see https://github.com/sparrowwallet/sparrow/issues/380) but instead in Gordian Seed Tool offer "Authenticate/Derive Key/Other Key Derivations/Bitcoin/Mainnet/Segwit/Public HD Key/Share Button":

![0ED6B642-09E4-4E52-9CE8-DFBF9F33D7B1](https://user-images.githubusercontent.com/69103/147989534-bdbf58f9-1790-4392-a32d-745519c7dfa9.png)

resulting in this QR:

![889CEFE3-C3A8-40B8-9B68-BC2BBDFD70C6](https://user-images.githubusercontent.com/69103/147989579-1ad588e0-9e3a-44ba-b071-ae0f81118704.png)

and try to scan it in Sparrow, the scanner scans it and closes, but returns you to Sparrow’s list of Airgap Wallets, rather than giving an error (or what I was hoping it would do is coerce it into an segwit output descriptor).

/cc @wolfmcnally @shannona

**Comment by craigraw** [comment]
`ur:crypto-hdkey` does not reliably contain the master fingerprint so it cannot be supported here. However as of bbdfec1 Sparrow will now accept `ur:crypto-output` for the correct script type (and provide an error if the incorrect script type is selected for the output descriptor). If `ur:crypto-hdkey` is provided an 'Import Error' message will now be shown and the instructions drawer opened.
