### ISSUE TITLE
FEATURE REQUST: In Software Wallets Import, support paste of text UR for crypto-account

### ISSUE THREAD

**Issue by ChristopherA** [sparrowwallet/sparrow#383]
Using Sparrow (macOS 1.5.5) and Gordian Seed Tool (iOS 1.3).

In Sparrow, I do "New Wallet" named "Singlesig Watch Only" test.

When using a non-M1 Mac (with its better camera), crypto-output QR from Gordian Seed Tool is often just a bit too big to cleanly scan. (would be great if both Gordian Seed Tool had button to animate it and Sparrow could automatically do the right thing when it sees any animated QR, but that is beyond the scope of this issues, see https://github.com/BlockchainCommons/GordianSeedTool-iOS/issues/115 ).

Thus I'd like to see a 4th choice under "Software Wallets" be for support for pasting arbitrary UR text.

For instance, for our reference DPAL seed, the UR for `crypto-account` is:

```
ur:crypto-account/oeadcyhngrmuwzaolttaadeetaadmutaaddloxaxhdclaordwdlfiesawyctiekidmvwgrrknlckbzcttluycyensfssatpenbverhprferodiaahdcxdnmdkthnrlytglntdmcnwnuorkrsihsackbkstbthhbabdgoheflgajkidwkwnkpamtaaddyoeadlncsdwykaeykaeykaocyhngrmuwzaycyeeoxcsditaadeetaadmhtaadmwtaaddloxaxhdclaobguydidmglwsclhdadpylowlemlemsspfdpadibdglpkhkwmamcacmletnfxaontaahdcxhfztnsuepdgsmdenlnyndnbtlpcejouykifzeocfbycyhlkstosemolpaoverfpyamtaaddyoeadlncsehykaeykaeykaocyhngrmuwzaycymetdvlfgtaadeetaadmwtaaddloxaxhdclaxvlcprfttldjobkredtlnhsidwybaeyjtswyandlgjnehtkdsidbkqzsrkphyfhsaaahdcxhnfgnepefxgdytryckticelyotsstoknfntavevaskiddmolsarntykbrybtjpksamtaaddyoeadlncsghykaeykaeykaocyhngrmuwzaycyzssajpsntaadeetaadmhtaadnytaaddloxaxhdclaxwzbtwpfnkgotrsgugdgmwlnegyrfbdktcfsndwskpkjyretkgodpmhspwdzelrgmaahdcxeosphyvdntcxhypesprfpyrfzmntvyoxtymehhwzsadlvohklgvthtpytlhtvwenamtaaddyoeadlfcsdpykaocyhngrmuwzaycyhngrmuwztaadeetaadmhtaadmetaadnytaaddloxaxhdclaoioflfpgojsvlbyskytfwhlbeaskewytiiafpptkkaafpplbsjphpiohpfgktahleaahdcxcpoyoltoltgolrswjpynfzdpdmimdtweqdnefemyihlrvejsfhbgrftyaepycwdmamtaaddyoeadlocsdyykaeykaeykadykaocyhngrmuwzaycynewncnlbtaadeetaadmetaadnytaaddloxaxhdclaohldlmdrtlacxhnfpptplfyltwelafsnezslyndhllnvdimmwlpylkbwzjltbdmenaahdcxlejtimcnrlbtdemdoereyaqzprkpndbdgwfzflqdbzkohgzobycxcnvabaosbglfamtaaddyoeadlocsdyykaeykaeykaoykaocyhngrmuwzaycynewncnlbtaadeetaadnltaaddloxaxhdclaxmtrfaaolkogtiakibahnbwsesbcaytihamdnwksfvdgmoxoevsvavowffdvtgtvyaahdcxkomtutcxkbswgsrodnpsaxpmskiotetylujkeelnidnlcxotoxpewehkaaftkgbaamtaaddyoeadlncshfykaeykaeykaocyhngrmuwzaycydpsesseyfyhkbnsg
```

I'd like to be able to paste into a UR choice on this Sparrow screen:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/69103/147993203-7f215599-088f-458a-8030-622a26cf6432.png">

It would also be great if it could support some of the UR text formats here, such as crypto-seed, crypto-sskr, hd-key, etc. and just do the right thing, for instance, if it is a crypto-hdkey it will ask which derivation, an hdkey of a pubkey 84', it will just cooerce it into a new segwit keystore, or if it is a hdkey 48' it will add it to a multisig account.

For instance, this is the DPAL crypto-seed. It should just jump to your seed UX.

```
ur:crypto-seed/oxadgdhkwzdtfthptokigtvwnnjsqzcxknsktdaosezofptpbtlnlyjzkefmaxkseceheyetdpidinjycxguihihiecxgdkpidjziniacxghihjkjycxhfihiajyjljpcxdehkinjtjnjtcxfwjzkpihdtcxendyeeideseoiyeyaakkadwdghisinjkcxinjkcxjyisihcxeheyetdpidinjycxdeeyeecxktjljpiedtcxjkihihiecxkpjkihiecxhsjkcxhscxjokpidjziniacxjpihiojpihjkjkinjljtcxjyihjkjycxkoihiajyjljpcxiyjljpcxgogmjkdwcxfljljpieinhsjtcxguihihiecxghjljljzdwcxhsjtiecxjkihihiejyjljljzdpiajzindmbkbkghisinjkcxjkihihiecxhsjtiecxhsjzjzcxjeihkkjkcxioihjtihjphsjyihiecxiyjpjljncxinjycxjkisjlkpjziecxidihcxiajljtjkinieihjpihiecxkpjtjkihiakpjpihcxhsjkcxjyisinjkcxjeihkkcxjnhsjyihjpinhsjzcxinjkcxidihinjtiocxjkishsjpihiecxjokpidjziniajzkkcxhsjkcxhscxjyihjkjycxkoihiajyjljpdmbkbkfpjzjkjlcxjejtjlktjtcxhsjkcxfygdfpgscxdpcxvolansfyhsjpjecxgdkpjpjojzihcxfpjskphscxgsjlkoihvolantcxhsjkcxhsjtcxjljziecxkoihjpjkinjljtcxjliycxgsiniyihfdhsjkiscxishsiecxjyishsjycxiajljzjljpdmbkbkfwinjyiajlinjtcxgthsjkjyihjpcxgrihkkcxfginjtioihjpjojpinjtjyftcxendyeeideseoiyeybkfejyisihjpihkpjncxfpiaiajlkpjtjycxcndycxfpieiejpihjkjkcxhpjndleeeedidlendyvolanldldyvolanldldydldyhlftcxdyksececemeceyeciedyeeeoeneceniheseoetecfyetfefgfpfpesfxieeehseohsihfpiefedyehehenetbkosimihpm
```

This is the DPAL bitcoin master private crypto-hdkey.

```
ur:crypto-hdkey/onadykaoykaxhdclaeeheyceykguhkgdbzpssfkplpftwdhkaetdetpfcnztjzctlrcygoiobtteplqdwnaahdcxvdbggasekkuytykkfefdlahtflkecpbzyackrpfmghvyqdssfsfhmtzcttsehdcsasksfzfdfygrihkkcxiyjpjljncxeheyetdpidinjycxguihihiecxgdkpidjziniacxghihjkjycxhfihiajyjljpcxdehkinjtjnjtcxfwjzkpihdtcxendyeeideseoiyeyrtemaaeo
```

Here is a DPAL private segwit crypto-hdkey:

```
ur:crypto-hdkey/olaoykaxhdclaejnsodtmtfwdkknwpbeqdlacskoadsgdlehbwrpahdmmepkbywsmuvynlmwbbdktsaahdcxhnfgnepefxgdytryckticelyotsstoknfntavevaskiddmolsarntykbrybtjpksamtaaddyotadlncsghykaeykaeykaocyhngrmuwzaxaxaycyzssajpsnasksfzfdfygrihkkcxiyjpjljncxeheyetdpidinjycxguihihiecxgdkpidjziniacxghihjkjycxhfihiajyjljpcxdehkinjtjnjtcxfwjzkpihdtcxendyeeideseoiyeybgzcadso
```

And the DPAL watch-only segwit crypto-hdkey:

```
ur:crypto-hdkey/olaoykaxhdclaejnsodtmtfwdkknwpbeqdlacskoadsgdlehbwrpahdmmepkbywsmuvynlmwbbdktsaahdcxhnfgnepefxgdytryckticelyotsstoknfntavevaskiddmolsarntykbrybtjpksamtaaddyotadlncsghykaeykaeykaocyhngrmuwzaxaxaycyzssajpsnasksfzfdfygrihkkcxiyjpjljncxeheyetdpidinjycxguihihiecxgdkpidjziniacxghihjkjycxhfihiajyjljpcxdehkinjtjnjtcxfwjzkpihdtcxendyeeideseoiyeybgzcadso
```

/cc @wolfmcnally @shannona

**Comment by craigraw** [comment]
I don't like this much - it encourages the sharing of UR text fragments which are opaque and difficult to identify. I don't see a good UX with this approach. 

I believe the right approach is to reduce the QR complexity so that lower resolution cameras can scan successfully.

**Comment by wolfmcnally** [comment]
The purpose of the UR technology, by design, supports multiple modes of transport including plain text. A single UR text string can be of any length, avoiding limitations in QR payload size and the need to use streaming QR codes to deal with resolution limits of screens and cameras. Seed Tool allows copying of text URs wherever it displays QR codes, and accepts them as well. Text URs themselves include a CRC-32 checksum, making them resistant to undetected corruption via human handling. /cc @ChristopherA
