### ISSUE TITLE
Would be convenient to be able to disconnect from the Server menu

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#385]
Currently we always need to close that page to be allowed to click underneath on the bottom toggle.

![image](https://user-images.githubusercontent.com/388716/148142822-d06571cf-c0dd-4015-9f60-c77a4c2ce137.png)

**Comment by craigraw** [comment]
Clicking 'Edit Existing Connection' will immediately disconnect from the connected server.

**Comment by Transisto** [comment]
Ok, Thank you
