### ISSUE TITLE
Signing error - Could not sign PSBT

### ISSUE THREAD

**Issue by deepy420** [sparrowwallet/sparrow#387]
I have a multisig wallet in which one of the signatures is a hardware wallet. The wallet has many inputs. I try to sign a transaction and I get an error saying Signing Error and "Could not sign PSBT".

<img width="497" alt="Screen Shot 2022-01-08 at 9 11 37 PM" src="https://user-images.githubusercontent.com/92241753/148665309-ad421cda-c3e0-4a40-b91f-7cd1d23ab75b.png">

I am able to successfully sign the transaction with Electrum using the same hardware wallet and passphrase.

I am able to sign transactions using that hardware wallet and Sparrow for a different wallet that doesn't have many inputs. Maybe the large number of inputs is the issue? There are 32 inputs. I can provide the psbt file if that would be safe enough to do.

**Comment by craigraw** [comment]
Don't send the PSBT file here, it contains privacy sensitive information.

When saying "the wallet has many inputs" - do you mean "the transaction has many inputs"? Can you check the Sparrow log (Help menu) for more information?

**Comment by deepy420** [comment]
I've attached the full log file here. You can specifically search the log file for "could not sign" to see the related error messages.

[log.txt](https://github.com/sparrowwallet/sparrow/files/7836247/log.txt)

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 7f2d72e.

**Comment by deepy420** [comment]
Thanks for fixing this. When do you think the next release will be out? I'm trying to determine if I should wait to send the payment I need to send or if I should just export the wallet to Electrum and use that in the meantime.

I'm facing another issue when doing one of the multisig signatures with the Fully Noded iphone app after exporting the PSBT from Sparrow. I'm not sure if the issue is in Fully Noded or Sparrow, but I thought I'd link to the issue here so that you can take a look when you have time:
https://github.com/Fonta1n3/FullyNoded/issues/206

I'm not sure if it's related to this issue that you resolved here because it's occurring in the same wallet. It doesn't occur in other wallets. Thanks!

**Comment by craigraw** [comment]
> When do you think the next release will be out?

Probably in a couple of weeks - running from source is not super difficult, but Electrum is a good fallback.

> I'm not sure if it's related to this issue that you resolved here because it's occurring in the same wallet.

It's not related. I'm happy to take a look at the PSBT if you email it to me at craig at sparrowwallet.com. Otherwise, you can save in a number of different formats - try the File > Save PSBT > As Base64 option.

**Comment by craigraw** [comment]
Thanks, received. The PSBTs look fine, and load in Sparrow - it's probably their size that is troubling FullyNoded. Try the File > Save PSBT > Without Xpubs menu item to reduce the file size.

**Comment by deepy420** [comment]
Thanks. Yea I think FullyNoded isn't able to handle a psbt with such a large file size. The transaction has 39 inputs and 2 outputs. I tried it without the xpubs based on your suggestion. It's still 6.7MB in base64 and 5.1MB in binary. The original with the xpubs is 5.1MB, so it doesn't make any difference.

**Comment by craigraw** [comment]
I see there is already one signature present - try without signing first?
