### ISSUE TITLE
Sparrow crashed on OSX

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#394]
First time I see Sparrow just disappear.

error from OSX,

https://pastebin.com/5PvPjdq8

**Comment by craigraw** [comment]
Appears to be a kernel bug in OSX related to a memory allocation error. I don't believe this is a Sparrow bug per se - it might be related to the other M1 Pro issue you reported. I'm going to close this off as I don't believe it's directly actionable.
