### ISSUE TITLE
[Feature] Label Search

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#397]
The abiliy to search within labels to find a particular utxo would be useful.

- Ideally across all accounts within a wallet e.g. Deposit, Premix, Postmix & Bad Bank
- Ideally partial searches

(Could be combined with the address search bar)

**Comment by Transisto** [comment]
+1
Electrum search index Label TXID and Addresses.

**Comment by craigraw** [comment]
Added - see https://github.com/sparrowwallet/sparrow/issues/396#issuecomment-1026015840
