### ISSUE TITLE
[UX] Expand Transaction Summary 

### ISSUE THREAD

**Issue by 6102bitcoin** [sparrowwallet/sparrow#399]
The transaction summary diagram is convenient when evaluating whether outputs are moving within your wallet (e.g. to Premix) or out of wallet (e.g. Paying Coordinator Fees). This information is not all visible due to the diagram being collapsed for large numbers of outputs. It would be useful for this diagram to be shown expanded, with scrolling if required.

Labels or colors could indicate whether a spend is internal or external in the pie chart overview.

**Comment by craigraw** [comment]
Implemented in ca928fc. Clicking on any transaction diagram will open it up in an expanded format in a popup. The expanded format allows the display of additional inputs and outputs (no scrolling implemented yet) along with the amounts for each.

<img width="1026" alt="Screenshot 2022-02-02 at 17 45 28" src="https://user-images.githubusercontent.com/862166/152187727-0f86e8c6-3b41-4449-a81c-7a4073c1a21a.png">

There are still several improvements possible that can be looked at in further iterations.
