### ISSUE TITLE
Displayed miniscript out of sync

### ISSUE THREAD

**Issue by sgeisler** [sparrowwallet/sparrow#4]
When playing around with different spend policies I noticed that the displayed miniscript/descriptor doesn't change accordingly.

E.g. `P2SH-W2WPKH` should be displayed as `sh(wpkh(key))`, but stays `pkh(key)`. Closing and reopening the window doesn't seem to fix the issue.

![2020-09-03-235228_5120x1440_scrot](https://user-images.githubusercontent.com/1876998/92177533-fa20e980-ee40-11ea-98dd-100cbf27fd12.png)

**Comment by craigraw** [comment]
I'm unsure if that's valid miniscript. Certainly `sh(wpkh(key))` is used in output descriptors, and (for example) Sparrow will display that in the Receive panel. But I can't seem to find any reference to it in http://bitcoin.sipa.be/miniscript/ or any other document on miniscript that I've seen. It would be good to have clarity on this point!

**Comment by sgeisler** [comment]
Yeah, I confused the terminology too again. What you display seems to actually be miniscript (maybe missing an underscore), but in the case of `p2sh-p2wpkh` there just isn't any miniscript involved. What you want to display is probably a miniscript-based descriptor, because while `sh(pk_h(key))`, `sh(wphk(key))` and `sh(wsh(pk_h(key)))` all encode the same spend policy, they produce different scripts/addresses. And the addresses you display are `sh(wphk(key))` ones, so the displayed miniscript is kinda misleading. I think the descriptor concept is easy to see in [rust-miniscript](https://github.com/rust-bitcoin/rust-miniscript/blob/master/src/descriptor/mod.rs#L52-L69).

**Comment by craigraw** [comment]
That seems reasonable. I agree it would be a clearer description of the wallet with less ambiguity. So:

Singlesig:
P2PKH: `pkh(keystore)`
P2SH-P2PKH: `sh(wpkh(keystore))`
P2WPKH: `wpkh(keystore)`

Multisig:
P2SH: `sh(sortedmulti(m,keystore1,keystore2,...))`
P2SH-P2WSH: `sh(wsh(sortedmulti(m,keystore1,keystore2,...)))`
P2WSH: `wsh(sortedmulti(m,keystore1,keystore2,...))`

I agree the underscore seems missing looking at sipa's doc, but it doesn't feel natural to include in the above.

**Comment by craigraw** [comment]
Implemented in https://github.com/sparrowwallet/drongo/commit/3115669c4644017cee69ebe6d402cc72fdc29d91

**Comment by sgeisler** [comment]
Nice! I think it should also be named differently in the ui (something along the lines of `Miniscript descriptor`) once sparrow actually uses the new version of drogo. Looking forward to the next release!

**Comment by craigraw** [comment]
Agreed - due to label space I think I'm going to go with 'Descriptor', since it is closest to output descriptor language, but with each keystore abbreviated to it's label to make it easier to read. Each keystore will have a a tooltip with the output descriptor representation of the keystore e.g. `[d34db33f/44'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL` (no child key derivation). The context menu will allow for copying the full unabbreviated output descriptor.

I'm also moving from multi to sortedmulti as a more accurate representation of multisig wallets in Sparrow.

**Comment by craigraw** [comment]
Implemented in https://github.com/sparrowwallet/sparrow/commit/b8c3bf1bea3dece95be99bd4ca44820826ef9f72.
