### ISSUE TITLE
"Mix to" need to be switched back and forth to another wallet for Apply button to work

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#401]
![image](https://user-images.githubusercontent.com/388716/149678145-b3919b36-488a-46ed-90f3-da98bbdc0474.png)

The destination wallet is open and properly selected but we need to choose another wallet and back for apply button to be active, as if no wallet was selected.

**Comment by craigraw** [comment]
Perhaps I misunderstand, but if you wish to make no change to these settings, why would the Apply button be active? It should only be active if there is a change to configuration that needs to be applied.

**Comment by Transisto** [comment]
I think it's because there's two option, one "Mix to X" and one that is just "Start Mix"

So it seems like "Start mix" will just mix indeast of "Mix to X"

Possibly that the Start mix could change to "Start mixing to X" if there's one set.

**Comment by craigraw** [comment]
Ok - so as I understand it, you were starting the mix by editing the mix configuration rather than just clicking the Start Mixing button, because you felt that just using the "Start Mixing" button would not respect the mix configuration?

First I've heard of this, although I can see the potential for confusion. I'm not sure that changing to "Start mixing to X" will be better though - it seems to suggest that mixing to that X wallet will happen immediately, or on the next mix.

**Comment by Transisto** [comment]
Well the confusion is what makes me go to mixto more often than I need to make sure the wallet has Applied the command properly. If the fields are valid I expect to be able to click "Apply" even if they're the same settings as before.


"Mix!" is a verb that could also mean "Start Mixing" 

I thought of a better way to resolve confusion;
When incomplete "Mix to" is good but when filled it could be simply "to walletXYZ" 

So it'll end up reading as  
[Start Mixing]   [to walletXYZ]

Or could be

[Start mixing]   [Mixing to walletXYZ] 
(when set)

**Comment by craigraw** [comment]
> If the fields are valid I expect to be able to click "Apply" even if they're the same settings as before.

This is not standard UX practice - something must need to be "applied" for the Apply button to be active.

> [Start mixing] [Mixing to walletXYZ]

Agree with this second suggestion, had come to this same conclusion. Implemented in 306f241.
