### ISSUE TITLE
transaction labels restored to previous state when connecting to different server

### ISSUE THREAD

**Issue by alexdibella** [sparrowwallet/sparrow#402]
Hi, thanks for amazing work!

When changing the server I connect to (e.g. from a public one to a private electrum and vice versa), my labels are restored to a previous state. Steps performed:

- open wallet connected to public server
- assign label to unlabelled transactions and/or modify existing labels
- change server to private electrum
- wallet loads with labels prior to my latest updates

The above is true also if the labels are updated while connected to private electrum and switching to public server. I've tried to exit the wallet before changing the server I connect to and the behaviour is preserved.

Running v1.5.5 (sparrow_1.5.5-1_amd64.deb) on Ubuntu 18.04

Let me know if you need more details!

Cheers,
-A

**Comment by SVZima** [comment]
I have a similar issue using private Electrum over Tor. I lost the vast majority of all my labels to all of my wallets yesterday after creating a new multis wallet (I'm nor sure if this is a coincidence or not). I have only a few very early labels being displayed when I initially started using Sparrow, some of my wallets do not show any labels. 

Wallet refresh and switching server connections did not resolve the issue.

**Comment by alexdibella** [comment]
don't know if it helps, but I tried to connect to all servers in the list available on sparrow and the labels get restored to the same specific state with all of them

**Comment by SVZima** [comment]
Thanks, I ended up opening up the last wallet backup file before the labels were lost and that worked as well.

**Comment by craigraw** [comment]
Thanks for the comprehensive bug report! Fixed in a825a69.

@SVZima I think this is a different problem. If you encounter it again, please open an issue describing what you were doing before it happened. I suspect it has something to do with refreshing the wallet, and then restarting Sparrow before the refresh is completed.

**Comment by alexdibella** [comment]
super! do you foresee any release soonish? or is it worth it a build?

**Comment by craigraw** [comment]
In a couple of weeks.

**Comment by SVZima** [comment]
> Thanks for the comprehensive bug report! Fixed in [a825a69](https://github.com/sparrowwallet/sparrow/commit/a825a693c1b9ee71593451956ccc476f612c5487).
> 
> @SVZima I think this is a different problem. If you encounter it again, please open an issue describing what you were doing before it happened. I suspect it has something to do with refreshing the wallet, and then restarting Sparrow before the refresh is completed.

@craigraw Thank you!
