### ISSUE TITLE
[Freature] Option to sync and start monitoring address after a start gap.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#404]
What if we could instruct the wallet to only monitor addressed from a starting point to speed up syncing?

For example a wallet with 2200 transaction/addresses could start at 2000 and goes all the way to 2200 + gap limit.

I don't know any wallet that support this but seems like it could be a good practice saving resource for larger wallet that never reuse addresses.

**Comment by craigraw** [comment]
Yes, I have been thinking about this, particularly in the case of postmix wallets which should never allow address reuse. It does raise the possibility (and user support burden) of a number of subtle issues - for example any balance issue will now need to be checked against "did you enable the start gap option"? That said, refreshing the wallet could still trigger a full subscribe against all addresses so perhaps not so serious.

I think the right solution still lies in fixing the servers to support deep wallets, but I realise that practically it may take some time for this to happen. Possibly the best route for now is to add this as a config file option - this would allow a trial period for those who are experiencing issues without adding too much in the way of user support.

I am thinking of an `onlySubscribeLast` option, which is integer based and by default set to -1 to disable. It can be set to any positive number to subscribe only that number of used addresses when syncing. For example, if set to 100, for any wallet over 100 used addresses, only the last 100 addresses are subscribed to, plus any new used addresses, plus the gap limit.

**Comment by 6102bitcoin** [comment]
Good idea. Would it be per wallet or per account? If per account a user could set the whirlpool premix/postmix/badbank at 100 but the deposit could stay at -1.

**Comment by Transisto** [comment]
I'll respond a bit later but here are semi-related conversations on electrum repo.
https://github.com/spesmilo/electrum/issues/6697
https://github.com/spesmilo/electrum/pull/6741
https://github.com/spesmilo/electrum/issues/6625
https://github.com/spesmilo/electrum/issues/5626

I think designing and innovating around this partial syncing concept could benefit other wallets.
What's considered a large wallet to sync is currently orders of magnitude bigger with Electrum

**Comment by craigraw** [comment]
> Would it be per wallet or per account?

I am thinking it will be a global setting. The problem is in a sense global to the user - if @Transisto had available a private ElectrumX instance, this would not be required. While I do see the advantage of particular account configurations when it comes to deposit vs postmix, in practice I think it might be more frustrating to need to configure this for each wallet individually, and probably not required if one uses a higher value like 500.

> I'll respond a bit later but here are semi-related conversations on electrum repo.

Thanks - I loaded the provided xpub `vpub5VfkVzoT7qgd5gUKjxgGE2oMJU4zKSktusfLx2NaQCTfSeeSY3S723qXKUZZaJzaF6YaF8nwQgbMTWx54Ugkf4NZvSxdzicENHoLJh96EKg` into Sparrow against Electrs and it completed the full 10000+ address wallet load in a minute or two. The wallet file is 13.5Mb. Testnet is not the same as mainnet though, the blocks are much smaller which eases things considerably for Electrs.

**Comment by Transisto** [comment]
I don't quite understand why we'd need to monitor addresses that are 1000 address away from current address. In the same way that the gab limit default to 20 or 40 I don't see a reason why we could not stop looking down 100 address down.

I'd think there's about 2% of users who'd eventually need to partial sync, more and more as mixing become more common and free remixes happens. 

This solutio should be implementable with near zero risk of miss-uses if applied to 2147483646 derivation path.

I don't remember that I've set such arbitrary gap limits but I'd see the option for limited monitoring into advanced, next to the gap limit.

![image](https://user-images.githubusercontent.com/388716/150044006-9f2a0501-33a1-4425-9f05-604a6f5651ea.png). (postmix)

There could be a syncFrom and subscribeToLast

**Comment by craigraw** [comment]
> I don't quite understand why we'd need to monitor addresses that are 1000 address away from current address.

I think it's largely historical - it's really only in more recent times that address reuse has become so discouraged, but it certainly can't be taken as a given that it won't happen. People use Bitcoin as they want to.

> I'd think there's about 2% of users who'd eventually need to partial sync

Agree - this not a feature required for the regular user, at least not yet.

> This solutio should be implementable with near zero risk of miss-uses if applied to 2147483646 derivation path.

Indeed - but it should probably be rolled out gradually, being opt-in initially.

> I don't remember that I've set such arbitrary gap limits but I'd see the option for limited monitoring into advanced, next to the gap limit.

This does have the advantage of being included within the GUI, so I'll consider this.

> There could be a syncFrom and subscribeToLast

What is the difference between these two? I was envisaging one setting only, as described above.

> BTW I didn't see evidences that show it's the public electrumX resource that are limited since they sync the 6000 deep wallet incredible fast on electrum.

You can read about ElectrumX resource limiting here: https://electrumx.readthedocs.io/en/latest/environment.html#resource-usage-limits. All public servers likely have some form of this configured. For ElectrumX, it appears that batched requests are counted more heavily than single requests. Did you try changing the `batchPageSize` parameter as suggested?

**Comment by craigraw** [comment]
Added in 41d1a18. Loading the previously mentioned 10000+ wallet takes just a few seconds on Electrs with the value set to 100. Note that the setting will only take effect on the next wallet load. By default, wallets will continue to subscribe to all addresses, so this is opt-in functionality at this stage.

<img width="512" alt="Screenshot 2022-01-19 at 13 39 53" src="https://user-images.githubusercontent.com/862166/150124447-830f3808-d04c-4e8e-acb8-7e32e3b1aaea.png">
