### ISSUE TITLE
Password box not selected when selecting window

### ISSUE THREAD

**Issue by tcharding** [sparrowwallet/sparrow#405]
Legendary software mate, top effort.

Minor ergonomic improvement request here please.

When I bring the sparrow window to the foreground (Ctl-Tab to select it) with all wallets locked the password field is not selected so one must manually select it with the mouse. It  would be awesome if it were selected so I could jump straight to my terminal based password manager without moving my hands from the keyboard :)

For example https://crates.io/ does this and it makes me smile every time.

I'm running Ubuntu LTS and KDE.

Thanks for all your work, well appreciated.

**Comment by craigraw** [comment]
Implemented in 9bf53ab, thanks for the suggestion!

**Comment by tcharding** [comment]
Legend!
