### ISSUE TITLE
How to build & run project for Win32?

### ISSUE THREAD

**Issue by vlad441** [sparrowwallet/sparrow#407]
I recently tried to build a project for a 32-bit system, after fixing a lot of small errs, I was able to build the project without errors. But when I tried to run it, it didn't work. After looking at the logs in the console, I made the assumption that the .dll libraries are only for 64 bits.

Is it possible to build and run project for 32 bit system?

**Comment by craigraw** [comment]
Not simply, no. Unfortunately several of the binaries do not have win32 equivalents. I imagine it may be possible to build those, but win32 is not likely to become a targeted platform.
