### ISSUE TITLE
Unable to save more than two watch-only/xpub accounts

### ISSUE THREAD

**Issue by curemici** [sparrowwallet/sparrow#410]
I'm doing a watch-only wallet with five accounts. Every account has its own xpub.
When I add the third account and exit and reopen the wallet, the second account has vanished.

Here are my steps for reproduction:

Create New Wallet
Settings Single Signature / Native Segwit
Script Policy (wpkh(Account1)
Keystore 1 - Xpub Watchonly Wallet
Label - Account1
Master fingerprint 00000000
Derivation m/84/0'/0'
xpub: xpub....firstaccountsxpub

Apply ... All transactions there ... fine

Close wallet -- Reopen -- fine

Settings Add Account
Script Policy (wpkh(Account2)
Keystore Xpub Watchonly Wallet
Label - Account2
Master fingerprint 00000000
Derivation m/84/0'/0'
xpub: xpub....2ndaccountsxpub

Apply ... fine

Close wallet -- Reopen -- fine

Settings Add Account
Choose an account to add -- Account #2
Script Policy (wpkh(Account3)
Keystore Xpub Watchonly Wallet
Label - Account3
Master fingerprint 00000000
Derivation m/84/0'/0'
xpub: xpub....3daccountsxpub

Apply ... fine

Close wallet -- Reopen 
Account #1 = Account2 has vanished

Give it a second try. Labeled from Account#0 - Account#2
After Closing Account#1 has vanished again

Give it a third try. 
When coming to the third account:
Choose an account to add -- Account#1 ==> Leads to Account#1=Account#2

Hope that helps to find the error.

**Comment by craigraw** [comment]
Thanks for the bug report! Fixed in ee992b7.
