### ISSUE TITLE
Greyed out tools > Find Mix Partner and Show PayNym

### ISSUE THREAD

**Issue by lvnilesh** [sparrowwallet/sparrow#412]
Using Sparrow 1.5.5 on an m1 Mac. 

Mixing tools are greyed out and UTXO do not show the mixing selection at all. 

<img width="497" alt="Mixing tools are greyed out" src="https://user-images.githubusercontent.com/93558/151629827-975d5bf6-bafd-4e05-9553-e24099d3c6ea.png">

Wondering what am I missing.

Appreciate your help. Thanks.

**Comment by lvnilesh** [comment]
See below screenshot from official documentation but in my setup, the Mix Selected button does not show at all.

I repeated the same steps on a PC with Sparrow 1.5.5 but no joy. 

<img width="1127" alt="mix-select-utxos-2x" src="https://user-images.githubusercontent.com/93558/151632190-dc13e5b1-1b27-44d0-a9c4-857afcae0ec0.png">

**Comment by craigraw** [comment]
This most likely cause for this is that your wallet is not a Native Segwit, singlesig BIP39 software wallet. Follow the Quick Start guide in the docs to create a wallet compatible with these tools.

It may also simply be that you are not connected to a server (see the bottom right toggle).

**Comment by lvnilesh** [comment]
My main wallet is hardware signer based native-segwit single-sig. It appears that sparrow whirlpool tool expects a software controlled native-segwit single-sig because it worked only when I created a test software single sig native-segwit using Sparrow.

By the way, Just want you to know that Sparrow is awesome, but I suspect you knew that already :) Thanks.

**Comment by craigraw** [comment]
Thanks :)

Yes, a software wallet is currently required due to the timeouts when using Soroban (which match the timeouts in Samourai wallet for compatibility). That said, it's not inconceivable you could perform the hardware wallet signing within the time allowed, so long as it was via USB or QR code (using SD cards would be too slow). Something to think about.

**Comment by arbocoin** [comment]
Sparrow privacy tools (paynym, stowaway, stonewall...) only support softwallets and not wallets from a conected hardware wallet? 
Then what would be the workflow that is supposed to be done to manage the funds of our how with sparrow? Is it essential to transfer all the utxos to a softwallet, losing the security of having them in a hww? I don't understand... I'm sure I'm missing something... 
Can you help me with this doubt?
Many thanks

**Comment by craigraw** [comment]
Stonewall (privacy optimized sends) are possible with a hww. PayNyms, Stowaways and StonewallX2s are not for technical reasons - for example, the private keys are required to generate addresses using PayNyms, and it's not possible to retrieve them from a hardware wallet.

It's ok to have multiple wallets, for example one using a hardware wallet for perhaps the majority of your funds, and a spending wallet where the seed is in Sparrow. This allows you to take advantage of the strengths of both approaches.

**Comment by arbocoin** [comment]
Thanks very much for your reply! 👌

Sent from Proton Mail for iOS

El dg, 31 jul, 2022 a 16:59, craigraw ***@***.***> va escriure:
