### ISSUE TITLE
Can't withdraw funds from multisig

### ISSUE THREAD

**Issue by Ricardodtv** [sparrowwallet/sparrow#413]
Good afternoon, I have a problem and I may lose some funds: I created a multisig wallet through Sparrow and sent it to some funds that arrived correctly! The problem is when I intend to raise the funds and I need to sign the transaction by the seedssigner it says "crashed" what will be the problem? Thanks

**Comment by craigraw** [comment]
The SeedSigner is crashing? Then it's probably a question better asked on the Seedsigner repo. It could be that the PSBT is too large for it, but if this is a new wallet that seems unlikely.

**Comment by craigraw** [comment]
Closing this off - appears to be better asked on the SeedSigner project repo.
