### ISSUE TITLE
Error installing udev rules.

### ISSUE THREAD

**Issue by Toledo11** [sparrowwallet/sparrow#415]
When i insert the command: sudo /tmp/hwi-2.0.214759361391458857839.tmp installudevrules 
I obtain this error:

{"error": "installudevrules failed: [Errno 6] No such device or address", "code": -13}

What should i do to fix that?

**Comment by craigraw** [comment]
You can also install them manually: https://github.com/bitcoin-core/HWI/blob/d6a8cdef3b904a8a7ea5e316a83cb4037046202d/hwilib/udev/README.md

**Comment by AndySchroder** [comment]
Getting the same error on ubuntu 18.04, 20,04, and 22.04 . However, after running the command, it "seems" to work okay despite the error.

Also, a few more comments about the udev rules install process:
- Why isn't this just done automatically by the .deb package? You already have to run sudo to do that anyway. Does it really hurt to do it for everyone even if they aren't using a hardware wallet? Running this command you are having them install rules for a bunch of wallets they may not have, so why not just have everybody do it?
- This entire process of running a binary executable with sudo in your /tmp directory with a randomly generated name seems a bit sketchy. Honestly would rather just be referenced in the GUI to the link above than encourage people to use this (but doing it automatically by the .deb package would really be best).

**Comment by craigraw** [comment]
> Getting the same error on ubuntu 18.04, 20,04, and 22.04 . However, after running the command, it "seems" to work okay despite the error.

Consider opening an issue on https://github.com/bitcoin-core/HWI/issues - it would be good to get this sorted.

> Does it really hurt to do it for everyone even if they aren't using a hardware wallet?

That's an open question - in my experience some will not want this, perhaps perceiving it as a security issue as unlikely as that is. For example, Coldcard users who only use it in airgapped may want this possibility of understanding USB communications disabled. Not a strong argument, but a possible one. 

I'd be happy to consider a PR for a `postinst` script though.

> Honestly would rather just be referenced in the GUI to the link above

That could be added - but some will be daunted by those instructions and running the HWI command is simpler.
