### ISSUE TITLE
Please release native M1 (universal) build for macOS

### ISSUE THREAD

**Issue by fulldecent** [sparrowwallet/sparrow#422]
<img width="379" alt="Screen Shot 2022-02-10 at 11 52 41" src="https://user-images.githubusercontent.com/382183/153456581-1ab0a67b-214b-45ee-84a1-3c1952d85b14.png">

**Comment by craigraw** [comment]
Such a release is planned, but it will require acquiring the necessary hardware for testing purposes first.

**Comment by fulldecent** [comment]
Chicken and egg problem here! Donate page only supports BTC. Can't open wallet on M1. More donation alternatives supported?

**Comment by craigraw** [comment]
> Can't open wallet on M1.

That's strange - can you provide more details? I'm not aware of any functionality issues on M1.

**Comment by fulldecent** [comment]
Sure. I just am avoiding Rosetta that's why

**Comment by craigraw** [comment]
Only BTC supported at this time. Out of interest, is there a particular reason to avoid Rosetta?

**Comment by fulldecent** [comment]
I recently "upgraded" from the 13" to the 14" MacBook Pro. Battery performance is much less.

By not using Rosetta, I can know which apps are Rosetta because it gives me a warning each time. Sometimes this is unexpected places, so the popup is helpful.

As soon as I install Rosetta then all other stuff will install without warning.

---

For example if you install Node JS, that's M1 native. But if you install Node JS with NVM that's Intel.

I would have never known that if I already had Rosetta installed.

**Comment by acantril** [comment]
Rosetta is a pain, as @fulldecent mentioned it allows other non apple silicon stuff to 'sneak on'
If you're having issues developing without hardware, i would suggest asking for donations for it - i would have thrown you over a decent number of sats if i'd known you were waiting on hardware.

Last time i asked you said coming soon, no mention of new hardware being a blocker.

**Comment by craigraw** [comment]
It's not a blocker - as I noted previously, I'm planning on acquiring it.

**Comment by acantril** [comment]
Any update on the m1 version yet ?

**Comment by craigraw** [comment]
Currently working on it - see latest commit

**Comment by craigraw** [comment]
A beta version of Sparrow for the Apple M1 (aarch64) has been released:
https://github.com/sparrowwallet/sparrow/releases/tag/1.6.4-beta1

All native libraries have been recompiled for this architecture. 

Please test and provide feedback.

**Comment by lvnilesh** [comment]
With this beta build, I notice SUPER fast loading of the app on a M1 Mac mini. Will test more. Thanks.

**Comment by acantril** [comment]
oh nice, i'll test right away.

**Comment by acantril** [comment]
Initial comments mirror what @lvnilesh said ... the load is SUPER fast.

**Comment by acantril** [comment]
I'll be using it normally today, @craigraw let me know if you need anything specific testing (in general) with the m1 builds.

**Comment by acantril** [comment]
Initial feedback.
I can see nothing which is broken yet,  I've only tested for about 1 hour but I'll update this with any functionality issues or stability issues I find.
The speed is so much better, Rosetta has this really weird "feel" to it, applications are sluggish is some strange places. This like button clicks have constant fraction of a second delays, with this native version all that is gone.
There appear to be no UI artefacts anymore.. previous to this the app would leave patches of it's Ui behind on the screen as static images... that behaviour is gone now which is awesome.

CPU is 1/10th of what is was (0.9-1% in activity monitor, vs the ~10% I had before). It used to be listed in the 'apps using significant energy' part of the battery dropdown, but isn't anymore.

The memory usage seems a little less... ~1GIG vs 1.5 GIG on the rosetta version.

**Comment by craigraw** [comment]
Thanks for the feedback - clearly Rosetta needs to make a lot of compromises to get things working. 

The native libraries handle things like USB hww communication, the webcam, Taproot signing/verification, Tor, Bitcoin Core connections, and wallet encryption. I've tested all of these, but additional testing on any of them is always welcome.

**Comment by acantril** [comment]
No worries at all, I have a coldcard and passport so I'll test out both of those comms mechanisms.

**Comment by acantril** [comment]
Confirmed working with coldcard via USB
Connected to local (ipv4) electrum 
really snappy ... and vs rosetta build on another mac ... much more responsive.

**Comment by craigraw** [comment]
> Please provide terminal command instructions for a complete erase of any and all traces of previous versions and user data and any associated settings.

For the application, just overwrite the folder you installed to (presumably you installed to Applications). For the user data, delete the `~/.sparrow` folder.
