### ISSUE TITLE
Open recent, (wallet) under File menu, Feature

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#425]
Electrum keeps a memory of last 5 opened wallet files.
![image](https://user-images.githubusercontent.com/388716/153549415-483a71b4-1e93-4773-a42e-78053a3b0bdf.png)

**Comment by craigraw** [comment]
Sparrow already reopens all previously open wallets on launch, so this would only be useful for recently closed wallets. There is a privacy impact to this - I believe once you close a wallet, Sparrow should forget about it.

On this basis I'm -1 on adding this feature.
