### ISSUE TITLE
Blockstream Jade Support

### ISSUE THREAD

**Issue by Georgantas** [sparrowwallet/sparrow#427]
I'm creating this issue to track support for the Blockstream Jade hardware wallet in Sparrow.

Jade multisig is merged into HWI: https://github.com/bitcoin-core/HWI/pull/475 Blockstream's implementation of multisig is good. You register the multisig xPubs onto the device, and it uses them to verify the change addresses, receive addresses, etc. This avoids the pitfalls described here: https://shiftcrypto.ch/blog/the-pitfalls-of-multisig-when-using-hardware-wallets/

Thank you!

**Comment by evliu** [comment]
2.1.0 officially released https://github.com/bitcoin-core/HWI/releases/tag/2.1.0

**Comment by craigraw** [comment]
Jade support added in cd15097. It is probably necessary to use Blockstream Green to initialise and update the device firmware first.

Tested on singlesig and multisig wallets. The registering of the multisig configuration appears to be done by asking the device to display an address from the multisig wallet, which can be done using the Display Address button on the Receive tab in Sparrow. Message signing on singlesig is also supported.

**Comment by evliu** [comment]
Looks good. Was able to set up a 3-5 multisig with three different types of devices including a newer jade that requires 2.1.0 and pyserial 3.5. Thanks!

**Comment by Georgantas** [comment]
I also tested it with a 2-of-3, and just found a small issue on the Jade's side: https://github.com/Blockstream/Jade/issues/40 On Sparrow's side, everything seems to be working great! This is amazing for self custody, thank you @craigraw ! 😃
