### ISSUE TITLE
[Bug]  Cannot connect to IPv6 Electrum servers via DNS

### ISSUE THREAD

**Issue by SRv6d** [sparrowwallet/sparrow#428]
When connecting to an IPv6(only) Electrum server, Sparrow only requests an A record (IPv4 address) and then  returns the following error:

```
Could not connect:

Retries exhausted
```

This is on macOS Monterey (12.2).

**Comment by craigraw** [comment]
Sparrow connects fine to IPv6 addresses:

<img width="544" alt="Screenshot 2022-02-14 at 09 24 05" src="https://user-images.githubusercontent.com/862166/153818749-33a864b0-277b-4053-ae47-3bf08c1e12d6.png">

The error you received indicates that the socket connection was made without errors, however the server itself did not return data from the requests sent to it. This needs to be investigated on the server side, or you can try a different server.

**Comment by SRv6d** [comment]
@craigraw The issue is not connecting to IPv6 servers itself, via an IPv6 address. The issue is that Sparrow will not connect if it resolves a DNS name to an IPv6 address. This becomes an issue especially in mobile and or NAT64 networks.

An example:

blockstream.info does not have an IPv6 address currently, but on nat64 networks, the provider DNS will map the IPv4 address within an IPv6 translation prefix (since only IPv6 is available natively). Apple explains this issue fairly well [in more detail](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html).

If we assume blockstream.info is at `A 35.201.74.156`, on a nat64 network the AAAA record will look like this `AAAA 64:ff9b::23c9:4a9c`, or `64:ff9b::35.201.74.156`(to make it easier). Sparrow receives this answer but fails to connect.
 
<img width="568" alt="Screenshot 2022-02-14 at 12 33 40" src="https://user-images.githubusercontent.com/18124752/153856927-993aed90-a4a7-42a9-ad3d-1a4886939eb4.png">

Connecting to the address which Sparrow receives in it's AAAA request directly works perfectly fine though.
<img width="564" alt="Screenshot 2022-02-14 at 12 37 08" src="https://user-images.githubusercontent.com/18124752/153857528-37597d8f-4688-4603-9df0-78e411644b03.png">

**Comment by craigraw** [comment]
Ok thank you. I'm reopening this, can you change the title to be more accurate of the issue?

I believe this will likely be addressed (at least to some extent) by use of the Java system property `java.net.preferIPv6Addresses`. This can be set to either `true` or `system`: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/net/doc-files/net-properties.html

If possible could you test this on your side? Unfortunately I don't have the confidence to setup the nat64 environment to test this properly. It should be possible by setting the environment variable `JDK_JAVA_OPTIONS` as follows:
```
export JDK_JAVA_OPTIONS=-Djava.net.preferIPv6Addresses=system
open /Applications/Sparrow.app
```

Alternatively if you can share an IPv6 only Electrum server (even privately craig at sparrowwallet dot com) I'd be happy to test it. It's also possible to set system properties when running from source in `build.gradle`.

**Comment by SRv6d** [comment]
Much appreciated. Updated the title. Unfortunately setting the system property didn't do the trick and I haven't been able to run from source.

```
* What went wrong:
Could not determine the dependencies of task ':run'.
> Could not resolve all task dependencies for configuration ':runtimeClasspath'.
   > Could not resolve project :drongo.
     Required by:
         project :
      > No matching configuration of project :drongo was found. The consumer was configured to find a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'javaModule' with value 'true' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

I've tested `InetAddress.getByName` using an IDE on OpenJDK 17 and it correctly returned IPv6, although I wan't able to debug further since I just don't know what I'm doing when it comes to Java.
I set up a quick IPv6 only proxy to blockstream.info so you can test properly and will send it to you via email.

**Comment by craigraw** [comment]
> I haven't been able to run from source

The submodule is missing - try `git clone --recursive git@github.com:sparrowwallet/sparrow.git`
If you then change line 130 in `build.gradle`:
```groovy
run {
    applicationDefaultJvmArgs = ["-Djava.net.preferIPv6Addresses=true", 
...
```

and run with `./sparrow`

Thanks for the proxy. My initial test with it failed (No route to host), but I think that is more to do with my local network than Sparrow. I will keep at it.

**Comment by SRv6d** [comment]
I did clone recursively, unfortunately that doesn't solve the issue. I could try on ubuntu later but I'm not sure I'll be able to replicate the issue there.

**Comment by craigraw** [comment]
I managed to get IPv6 working locally by using a VPN (apparently my ISP does not support it). Once installed, everything worked perfectly on the Sparrow v1.5.6 release:

<img width="537" alt="Screenshot 2022-02-15 at 09 29 14" src="https://user-images.githubusercontent.com/862166/154014066-9c4dc4d8-a3a6-4a79-bbf2-abca4fc68c76.png">

MacOS 11.6.2.

I also tried different values of `-Djava.net.preferIPv6Addresses` - all worked. 

Going back to the original post, I think what may have happened was that the server was not responding at the time of that test - the 'retries exhausted' indicates Sparrow did successfully send bytes over the socket, it just didn't get any application-level response.

**Comment by craigraw** [comment]
Can I close this off?

**Comment by craigraw** [comment]
Can you try starting Sparrow using the following:
```
_JAVA_OPTIONS=-Djava.net.preferIPv6Addresses=system /Applications/Sparrow.app/Contents/MacOS/Sparrow
```

You can also substitute `true` for `system`. Please let me know the results.

**Comment by craigraw** [comment]
Any update here? Would be good to get this sorted.

**Comment by SRv6d** [comment]
Running Sparrow as specified with either `system` or `true` makes the connection work.

**Comment by craigraw** [comment]
Thanks. I've set `-Djava.net.preferIPv6Addresses=system` going forward in e594007.
