### ISSUE TITLE
Can't sign loaded transaction in multisig setup

### ISSUE THREAD

**Issue by Czino** [sparrowwallet/sparrow#429]
Following situation:

Have a 2/4 multisig setup / native segwit.
Each signer is using a Bitbox02 HWW.
The other Keystores are imported by sharing xpubs

Multisig setup is correct, receiving addresses match and some TX have been successfully signed.

# Test cases:

Test 1 ☑️
Keystore 1 creates PSBT and signs.
Sends PSBT to Keystore 2
Keystore 2 signed transaction and broadcasts

Test 2 ☑️
Keystore 2 creates PSBT and signs.
Sends PSBT to Keystore 1
Keystore 1 signed transaction and broadcasts

Test 3 ❌
Keystore 2 creates PSBT and signs.
Sends PSBT to Keystore 3
Keystore 3 cannot sign transaction.
Following error messages occurs: `No key found for input 0`

Test 4 ❌
Keystore 4 creates PSBT and signs.
Sends PSBT to Keystore 2
Keystore 2 cannot sign transaction.
Following error messages occurs: `No key found for input 0`

In test 3 and 4, the same transaction has been loaded into the same multisig setup but on Electrum. There the signing of the transaction works without errors.

# Further comments
Not sure if that's a hint, but I inspected the input of the failing TX and the Witnessscript shows the following

`OP_2 <pubkey1> <pubkey2> <pubkey3> <pubkey4> OP_4 OP_CHECKMULTISIG`

Where all `pubkey` show a different order than the pubkeys for the address in question shown in electrum.

| Sparrow  | Electrum |
| ------------- | ------------- |
| `pubkey1`  | Position 2 |
| `pubkey2`  | Position 4 |
| `pubkey3`  | Position 1 |
| `pubkey4`  | Position 3 |

**Comment by craigraw** [comment]
The problem I suspect is that you have not correctly saved the master fingerprint to all of the keystores in Sparrow. Why not just import the Bitbox02s as normal? 

The error is coming from HWI: https://github.com/bitcoin-core/HWI/blob/0d846a64967697eacd999cf7967fc6a5ba5b6282/hwilib/devices/bitbox02.py#L676

The method that returns the correct pubkey depends on master fingerprint in the PSBT input's provided keys matching the master fingerprint on the device.

Electrum does not use HWI, and probably uses a looser policy.

**Comment by Czino** [comment]
Thanks @craigraw that fixed indeed the issue
