### ISSUE TITLE
Missing an indicator that the wallet is not up to date and loading transactions.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#432]
I know about the "Show loading logs" option but it's not set by default and it's under a specific "History" tab.

I think there's a lot of unused space in the status bar that could be used to show either a static "Loading ..." a spinner or some sort of progress information.

**Comment by craigraw** [comment]
> I know about the "Show loading logs" option but it's not set by default and it's under a specific "History" tab.

It is shown by default on all new installs. The Transactions tab on which it appears is the default tab when opening the wallet.

> I think there's a lot of unused space in the status bar that could be used to show either a static "Loading ..." a spinner or some sort of progress information.

An error in loading the wallet is indicated by a red wallet tab icon. The connected status is indicated by the toggle in the status bar. Continually showing notifications in the status bar with every server interaction is distracting and unnecessary for the normal situation of the server being functional. I don't believe this is a good UX idea.

**Comment by Transisto** [comment]
I think a good solution could be for the server side to fetch faster and
not have people worry about a different balance for longer than 10 seconds
when opening the wallet.

 When transactions get done from another instance of that wallet and
Sparrow hasn't cached up yet. I understand as common as I originally
thought.

**Comment by craigraw** [comment]
> I think a good solution could be for the server side to fetch faster and
not have people worry about a different balance for longer than 10 seconds
when opening the wallet.

Indeed. Running a local instance of Fulcrum would sort this out, particularly for the large wallets you are using. I just don't think the servers you are using are suitable, and it appears Sparrow is having issues when it is actually the server. See my server performance report - some things Sparrow cannot fix itself.
