### ISSUE TITLE
Fail to connect to bitcoin node on LAN

### ISSUE THREAD

**Issue by peevishbadger** [sparrowwallet/sparrow#433]
Hi, 

[Sparrow linux standalone]

I have a bitcoin node running on my LAN at 10.0.0.19, I'm able to query it fine from a desktop terminal with the curl command, but Sparrow is not able to connect.   If I put incorrect credentials in the Sparrow connect window, my node terminal reports "ThreadRPCServer incorrect password attempt from 10.0.0.201", but correct rpc credential does not generate a node side warning, it just does not work.  The TestConnection button comes back with an error almost instantly with correct rpc credentials entered. 

I changed the rpcuser to 'bitcoin' from what it formerly was, and edited bitcoin.conf to say:

rpcuser=bitcoin
rpcpassword=xxxxxxxxx
[main]
rpcbind=127.0.0.1
rpcbind=10.0.0.19
rpcallowip=127.0.0.1
rpcallowip=10.0.0.0/16

None of this changed the already-working ability to query the node from a terminal on my desktop (10.0.0.201).   The node is running on a NAS in a Docker container.   Since the curl command works fine and the node is cheerfully synced with the outside world, I think this must be some handshake issue on the Sparrow side.    

Thanks

PB

**Comment by craigraw** [comment]
Did you check the Sparrow log (Help menu) to see if there was any useful information in there?

**Comment by craigraw** [comment]
My guess is that this `bitcoind` instance is configured without wallet support - in this case the wallet APIs are not available.

**Comment by craigraw** [comment]
Closing this off, please comment if you feel the conclusion was not correct.

**Comment by peevishbadger** [comment]
Yes, thank you I did have disablewallet=1 in the bitcoin.conf.    I thought that meant to refer only to the nodes own local wallet, not generically to wallet services. 

Now I have to see if I can recover the BTC sent to a secondary address, that I sent in error to one of my wallets secondary addresses, but BEFORE I had the node connection working.   I don't think this should matter .    But the transaction is not showing up and I see no way to scan the node chain for a secondary address.    Transaction looks fine on Blockchain Explorer.   I might have to open a new issue.   Thanks for your help!

**Comment by craigraw** [comment]
> I thought that meant to refer only to the nodes own local wallet, not generically to wallet services.

If you connect to Bitcoin Core, you use Bitcoin Core's wallet behind the scenes.

> I sent in error to one of my wallets secondary addresses

Not sure what is meant by a 'secondary address`.

**Comment by peevishbadger** [comment]
Hi, 

I tried to get clever and from my wallet picked the 2nd of the Receive Addresses from the Addresses tab in the wallet rather than just the one presented in the Receive tab, which is the 1st of the addresses in the Addresses tab.  All this BEFORE I got the node connected.   I know.  

Address on Receive tab, which also is the first in the Addresses/Receive:

bc1qrx...jmapcn
m/84'/0'/0/0

Address I sent to, which is the second (derived) address on the Addresses/Receive tab:

bc1qs4.....5rend 
which has derivation m/84'/0'/0/1

I'm able to query my local bitcoin node using the TxID which I see in my sending wallet using 

me@here:~$ curl -u'bitcoin' --data-binary '{"jsonrpc": "1.0", "id": "curltest", "method": "getrawtransaction", "params": ["ef59a507fe6c.....cbe1f9", true]}' -H 'content-type: text/plain;' http://10.0.0.19:8332/

And my transaction is visible in my local node as it should be.     

So I think I just need to figure out out to get the Sparrow wallet to scan for the   m/84'/0'/0/1 address, and not just the first one. 

Or should I send a few sats to the m/84'/0'/0/0 address to kick it into action ?

Thank you for your help with my noob questions. 

PB

**Comment by craigraw** [comment]
This shouldn't be a problem - Sparrow scans the first 20 addresses by default for new transaction. Are you sure the derivation path is not m/84'/0'/0'/0/0 - note the extra /0'?

**Comment by peevishbadger** [comment]
Yes I made a typo, hand typing.  

The starting derivation is m/84'/0'/0'/0/0 , I sent fund to the address with the second derivation, m/84'/0'/0'/0/1.    I left everything to default settings as I was getting started.      I've triple checked the receiving address (Sparrow second derivation) against the log in the funding wallet, the blockchain record at blockstream.info, and Sparrow's Address tab the receiving wallet.

I've thought about temporarily using a public bitcoin node in case there is still some subtle problem with my local one, just as something to try, since I directly checked this particular transaction as I described above.  

Thank you again for your help,  

PB

**Comment by craigraw** [comment]
Testing against a public server is probably a good idea here - as noted above there should be no issues finding the transaction at /0/1.

**Comment by peevishbadger** [comment]
OK I connected to the node at electrum.blockstream.info, and SUCCESS.    I could see Sparrow scanning in turn for all the derivation addresses (which it did not show before) and at the end my transaction from over a week ago was sitting there. 

I hadn't wanted to do this before as one's one node has better privacy.    But perhaps my node still has some weird config problem, or Sparrow was confused because of the backwards order I had done things, and wasn't scanning the derivatioins properly. 

I will test again with some (much smaller!) transactions with the public node, and my own.    

Thanks for your help.   I really want to get this working as I've become soured on BTC without some obfuscation.

**Comment by craigraw** [comment]
It does appear that something strange happened on the Bitcoin Core wallet. Probably, it makes sense to delete the 'sparrow' wallet in the Bitcoin Core wallets folder and sync from scratch, setting the birthdate of the wallet to before the first transaction.

On the other hand, setting up a private Electrum server is well worth the effort to avoid all of this.

**Comment by peevishbadger** [comment]
I did as you suggested, and all good now!

Thanks again for your generous help.   I'll donate some BTC when I have some clean ones!
