### ISSUE TITLE
Connection failed IO Error (cannot connect to hidden server)

### ISSUE THREAD

**Issue by henries1927** [sparrowwallet/sparrow#435]
While doing a mix I lost connection and I'm not able to connect again to EPS (Connection failed IO Error (cannot connect to hidden server)).I tried to change also EPS of another node. I tried also to open Tor Browser and proxy without result (Could not connect: SOCKS server general failure. Check if the proxy server is running.) SO Ubuntu
This under Ubuntu: I tried another Sparrow with Windows no problem connecting to same EPS

**Comment by henries1927** [comment]
i tries also with ps aux and kill the Tor process without success. 
curl --socks5 localhost:9050 --socks5-hostname localhost:9050 -s https://check.torproject.org/api/ip
 {"IsTor":true,"IP":"185.220.101.15"}

**Comment by craigraw** [comment]
Did you come right with this? I don't believe it is a Sparrow issue but something local to your Ubuntu environment.

**Comment by henries1927** [comment]
Yes perfect, It was a TOR problem with Ubuntu.

Thanks a lot

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 25 feb 2022, 08:22, craigraw ha scritto:
