### ISSUE TITLE
Window height doesn't fit a 13" screen

### ISSUE THREAD

**Issue by louneskmt** [sparrowwallet/sparrow#44]
Hi again!

I'm on a 13" MacBook Pro, with the display to default settings (Retina 2560x1600, "looks like 1440x900" setting), and the min window height is too high: almost the whole footer happens to be under the dock, so I cannot click on the connection toggle button (unless I move the window to have the button in the bottom right corner of the screen, see below). I also cannot resize the window height. 

<img width="213" alt="image" src="https://user-images.githubusercontent.com/38882571/100392504-0fb84080-3037-11eb-8df0-28ada257a9c7.png">

**Comment by craigraw** [comment]
Thanks this is helpful. Could you measure the maximum pixel height that would work on your screen? Should be possible while taking a screenshot with Cmd+Shift+4.

**Comment by louneskmt** [comment]
There are approximately 1600px between the top of my Dock and the bottom of my menu bar.

**Comment by craigraw** [comment]
Thanks, fixed in 64c3db3.
