### ISSUE TITLE
Trouble connecting Trezor T for signing

### ISSUE THREAD

**Issue by BigBoy2222** [sparrowwallet/sparrow#440]
When I click sign transaction and scan for my hardware wallet, even though the Trezor is plugged in and active, I get the response "No Matching Devices found". When I go into settings in Keystores and click "Replace" the Trezor shows up there.

**Comment by craigraw** [comment]
The master fingerprint for the keystore in Sparrow must match the master fingerprint in the Trezor - it cannot be `00000000`. Use the Replace function to fix it if that is the case.

**Comment by BigBoy2222** [comment]
In Sparrow the master fingerprint is not 00000000.  If I use the Replace function, wont I loose the transaction history and wallet Balance?

**Comment by Yuxanju** [comment]
Then you will need to synchronize your wallet and then you debug it and then you reboot your device

**Comment by BigBoy2222** [comment]
Are there some instructions on how to synchronize, debug and reboot?  Also, I saw from reading through other issues that people have an issue if the Trezor asks for a passphrase.  I hooked this Trezor up to a different wallet for a different coin. I think I probably should not have done that.  Now when I connect the Trezor to Sparrow the Trezor asks for a passphrase. I don't have one so I just hit the green check mark on the Trezor and it connects.  Could this be part of the problem?

**Comment by craigraw** [comment]
You can toggle the passphrase functionality back and forth using the USB icon in the status bar that pops up after the device is plugged in and unlocked. If you aren't using a passphrase, toggle it off and try again.

**Comment by Yuxanju** [comment]
You will need the  bech13 to synchronize your wallet.. I can send you a
secure encrypted ellipal link to synchronize your wallet and then you debug
it

**Comment by craigraw** [comment]
> You will need the  bech13 to synchronize your wallet.. I can send you a
secure encrypted ellipal link to synchronize your wallet and then you debug
it

I don't know what this means - please ignore this advice.

**Comment by BigBoy2222** [comment]
Thank you craigraw. I will ignore that.  Looks bad to me too.  Thank you for the instruction on toggling off the passphrase. Unfortunately I am still not able to connect the Trezor.  In the Keystores for this wallet, when I click on "Replace" I can preview the Master fingerprint and xpub / zpub that will replace what is there now.  I am wondering what the repercussions of doing this are. Will I be able to spend funds out of this wallet that came in under the previous fingerprint and xpub / zpub before the replacement?

**Comment by Yuxanju** [comment]
Once you do your synchronization. You can spend it

**Comment by craigraw** [comment]
I suggest creating a new wallet with this Trezor - that way you don't risk changing anything with your current wallet, and you can compare to see if there are any differences. There are no downsides to this approach.

**Comment by craigraw** [comment]
Closing this off.
