### ISSUE TITLE
Sparrow Standalone Linux doesn't work in Tails

### ISSUE THREAD

**Issue by jinrinn** [sparrowwallet/sparrow#441]
Tails version : 4.27 (latest as of this writing).
Linux Standalone : https://github.com/sparrowwallet/sparrow/releases/download/1.5.6/sparrow-1.5.6.tar.gz
" Error: missing server' JVM at /home/amnesia/Persistent/Sparrow/lib/runtime/lib/server/libjvm.so' "
... needs to be truly standalone so it can run in any folder.

**Comment by jinrinn** [comment]
Installed the default JRE in Tails and also re-unzipped the Sparrow standalone package, and it's working. There's a chance that for some reason that file was just missing in the previous untar but looks like it's there now.

**Comment by craigraw** [comment]
Strange. Thanks for sharing this. Sparrow ships with a complete JRE inside, so the original error is something of a mystery.
