### ISSUE TITLE
Feature Request: Add a column for Change/Index 

### ISSUE THREAD

**Issue by Francisco-DAnconia** [sparrowwallet/sparrow#442]
I spent some time trying to understand the transaction window and how that relates to the items in the "UTXOs" and "Transactions" panes. Sparrow is unparalleled here. 

I think it would be really useful to allow an optional column that had the "<change>/<index>" for the transactions to aid in finding them. So, for example  "0/4" would identify receiving address 5, and "1/72" would indicate the 73rd change address.

It might even be useful in the "Addresses" pane. especially if "Hide Empty Used Addresses" is on. Saving time from needing to hover and wait for the tooltip.

Btw, is this the correct forum for feature requests? New to this.

**Comment by craigraw** [comment]
I have considered this previously, but feel it it would take up too much space/overwhelm the average user. 

That said, I agree it's very useful information, so I have decreased the show delay for these tooltips from 1 sec to 250 milliseconds. 78a6ce4
