### ISSUE TITLE
Removed password for a wallet, can't open it again.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#445]
![image](https://user-images.githubusercontent.com/388716/156101435-ef46250f-0212-48fd-8761-71925463239b.png)

The error message I get.

**Comment by craigraw** [comment]
Can you post the steps to recreate this error?

**Comment by Transisto** [comment]
I created a new wallet and did the same steps and it didn't reproduce.

**Comment by Transisto** [comment]
The bip39 seed was imported, nothing odd was done to it.

I had an original copy of the wallet and did the same thing many time with same problem.

Changing the password worked but not removing it.

**Comment by craigraw** [comment]
@russelldavies Thanks for the steps - unfortunately, when following them I can't recreate this error.

Can you try again, and watch the log file (Help menu) to see if there are any logs printed, particularly when you change the password?

> I couldn't set a new password so left it as "no password".

Could you also clarify what you mean here in terms of the UI display? How did Sparrow prevent setting a new password?

**Comment by craigraw** [comment]
Thanks for the report. Fixed in 930e36fa.

**Comment by craigraw** [comment]
Further fix for changing the password after adding a new account in 7f254e76.
