### ISSUE TITLE
Unknown publisher warning Windows 10 install

### ISSUE THREAD

**Issue by odroider** [sparrowwallet/sparrow#447]
I would like to install Sparrow Wallet on my Windows 10 machine, however when I run the installer downloaded from the official Sparow site, I am getting the warning:

Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

App: 
Sparrow-1.5.6.exe 
Publisher:  
Unknown publisher 

Obviously this not what I want to see from an applications as security sensitive as a Bitcoin wallet. 

Is this a normal warning that I can ignore or should I regard it as suspicious?

Thanks.

**Comment by craigraw** [comment]
It's entirely normal. To sign the Windows installer requires acquiring code signing certificates from certain CAs that don't add much security so long as you are following the download verification process on the sparrowwallet.com download page.

At some point I will look at removing the warning.

**Comment by RomaRV** [comment]
Нет миксера на версии Виндовс
