### ISSUE TITLE
[Feature] Allow easier export of transaction from the transaction tab.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#449]
One of my transaction is signed but broadcasting isn't working, 

I noticed there are no ways to save it for sending another mean aside from selecting the HEX text at the bottom.

![image](https://user-images.githubusercontent.com/388716/156597778-4b2d383d-1527-4ce9-8171-105135d0e0e3.png)

![image](https://user-images.githubusercontent.com/388716/156597702-37dbffdd-5b36-456f-97fb-22a6fb8a5905.png)

In electrum every pre-signed or confirmed transaction can be exported.
![image](https://user-images.githubusercontent.com/388716/156598592-6c3925c5-87df-4277-b99f-8f0e85a65903.png)

Someone might want to broadcast via another network / device so more export options would help.

Ps: Not a priority for me.

**Comment by craigraw** [comment]
You can use the File menu? File > Save Transaction. Also, if you right click on the hex area, you can Copy All without selecting.
