### ISSUE TITLE
Freeze UTXO option

### ISSUE THREAD

**Issue by atom686** [sparrowwallet/sparrow#45]
There are many dust attacks by chainanalysis these days. An option to freeze UTXOs seems necessary.

**Comment by craigraw** [comment]
Thanks for the suggestion - will look at implementing.

**Comment by craigraw** [comment]
Added in 572e451. 

A UTXO can be frozen by right clicking on it and selecting 'Freeze UTXO'. A frozen UTXO can be unfrozen the same way. Frozen UTXOs cannot be used as inputs to a transaction.
