### ISSUE TITLE
Unable to install 1.6.0 on Windows 10

### ISSUE THREAD

**Issue by cole505** [sparrowwallet/sparrow#453]
Unable to install 1.6.0 on Windows 10 Home - "The cabinet file 'Data.cab' required for this installation is corrupt and cannot be used." 1.5.6 installs and runs without any issues.

**Comment by MarcGoldring** [comment]
On win 11, my 1.6.0 install had no errors. I used the .exe not the .zip/standalone, so i would think that you have a damaged download. out of interest did your SHA hash calc ok?

**Comment by craigraw** [comment]
My default Windows platform is also Windows 10 Home - no errors on installation here.

**Comment by cole505** [comment]
It must have been a local issue - I just installed 1.6.1 with no issues. Thanks very much - Sparrow is awesome.
