### ISSUE TITLE
different paynyms for the same seed on sparrow and sw

### ISSUE THREAD

**Issue by haribosan** [sparrowwallet/sparrow#454]
using the same seed + passphrase I get this paynym on samourai wallet: https://paynym.is/+orangeresonance129, and this one on sparrow: https://paynym.is/+blackpine425. how is it possible, assuming both sw and sparrow use the same bip47 standard?

**Comment by craigraw** [comment]
I can't reproduce this - Sparrow reliably recreates the same payment code originally created by Samourai Wallet using the same seed and passphrase. 

Is it possible to provide a seed + passphrase (obvs with no funds) that demonstrates this?

**Comment by craigraw** [comment]
Also: Is it possible you used a non-zero account? e.g. `m/47'/0'/1'`

**Comment by haribosan** [comment]
I just deleted my wallet on Sparrow and re-imported the seed, this time the paynym matches the one generated by SW. That's odd though, I had always left my previously imported wallet basically untouched, never used non-zero accounts.

**Comment by craigraw** [comment]
Ok thanks for the feedback.
