### ISSUE TITLE
If launched with the desktop launcher, Sparrow won't exit properly when quitting

### ISSUE THREAD

**Issue by YellowWords** [sparrowwallet/sparrow#455]
Hitting the quit button in the main menu in the UI, the Sparrow process doesn't exit, and the wallets remain open. I can for example see various processes open in `htop` belonging to Sparrow even afterwards. If you then reopen Sparrow it'll fail with an error message saying this wallet is already open in another process. The desired behavior would be for quitting to completely close all wallets and cause all the processes to stop.

Interestingly, this behavior doesn't happen if you start it by calling `/opt/sparrow/bin/Sparrow` directly, only with the menu launcher.
I had a look at the launcher and it seems that is calls `/opt/sparrow/bin/Sparrow %U` - I don't know what the `U%` does but I removed it and that made it work as expected.

Sparrow Version: 1.6.1, present since at least 1.5.x
OS: Linux Mint 20.3

**Comment by Transisto** [comment]
Loosely related, but on Windows my Sparrows always end up not bein able to get connections,

`2022-03-04 10:03:20,475 ERROR [ElectrumServerReadThread] c.s.s.n.TcpTransport [null:-1] Error opening socket inputstream
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.0/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.0/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

and whenever that happen the process would not close.

![image](https://user-images.githubusercontent.com/388716/156791462-8828f8da-221b-4d15-8391-adaadf7ed549.png)
Have to kill it manually.

**Comment by althea16** [comment]
YES! I have this same problem. After I exit Sparrow I need to go into the task manager and cancel a Sparrow process before I can open my wallet again. This only started happening after the last couple of updates.
Every time I get the error:
"Error Opening Wallet
The wallet is locked. Is another instance of Sparrow already running?"

**Comment by otyl** [comment]
> YES! I have this same problem. After I exit Sparrow I need to go into the Windows task manager and cancel a Sparrow process before I can open my wallet again. This only started happening after the last couple of updates. Every time I get the error: "Error Opening Wallet The wallet is locked. Is another instance of Sparrow already running?"

I also have this exact issue on Windows 10. I am fairly sure that the bug only exists in the 1.6.0 and 1.6.1 releases.

**Comment by craigraw** [comment]
I can't reproduce this on OSX 11.6.2, Ubuntu 20.04, or Windows 10 Home with the v1.6.1 install.

Given this I will need assistance to investigate further. @YellowWords, once you have quit Sparrow and can see the Sparrow processes with `htop` as you have described, please issue:
```
kill -3 <PID>
```
where `<PID>` is the process id that you can see in `htop`. This will print out a long thread dump of all active threads to ~/.sparrow/sparrow.log. Please copy this output into this issue.

**Comment by YellowWords** [comment]
@craigraw I actually can't reproduce the issue now for some reason - I reverted my workaround on the desktop file I mentioned, but now Sparrow is exiting correctly. I can't rule out it was just something local to my machine so I'll close this issue for now.

**Comment by althea16** [comment]
I do not understand how to do the workaround and still have this issue. It never happened before the last two updates.
What is the solution for a more non-technical person? 
Thanks very much for your attention to this.

**Comment by craigraw** [comment]
@althea16 please open a separate issue.

**Comment by Transisto** [comment]
I think the issue happen once it's been running for about one day.
