### ISSUE TITLE
UI bug: Create transaction button not active

### ISSUE THREAD

**Issue by haromz** [sparrowwallet/sparrow#456]
**Steps to reproduce:**

1. Click "Send"
2. In "Pay to" field open the dropdown and select a "paynym"
3. On the paynym window select a contact and press "Select contact"
5. Fill in the "Label" field.
6. For the amount press "Max"

The transaction diagram is being shown, everything looks fine, but the "Create transaction" button is not active, is greyed out, can't be clicked. You cannot proceed to the next step.

**Workaround**: edit the "Amount" field, the "Create transaction" button becomes active. You can press again "Max" if needed, the button will remain active from now on.

**Sparrow v1.6.1**
**Tested on:** Macbook pro 2019
**OS version:** MacOS Moneterey 12.2.1

**Comment by craigraw** [comment]
Thanks for the bug report, not sure how I missed that! Fixed in 689f4ab.
