### ISSUE TITLE
Feature Request - Enable "do not spend" utxo's

### ISSUE THREAD

**Issue by zonklift** [sparrowwallet/sparrow#458]
Enabling a "do not spend" feature would be convenient as well as an idiot-check for wallet spends out of post-mix/bad-bank. There could simply be a check box next to each utxo (utxo tab), which eliminates that utxo from the selection algorithm when spending with cahoots (or if merging to spend in any way). 

Currently, the user creates a spend, and then can eliminate utxo's from the input side using the input/output diagram. This is good, but it is not ideal. In the spend diagram the user can only visually see a portion of the label (tool tip hover shows address only). It is also theoretically possible to eliminate utxo's and end up using ones that had previously been spent together (even with a stonewall). That's a footgun. 

The best solution is to eliminate potential user error (and automate). This means the user can simply mark the utxo's they do not want to spend, and let the selection algorithm do the work for them. 

Another possible way to tackle this is if users put "do not spend" in their labels, that the selection for spending uses that label as a filter to eliminate them from use. 

One more point is that marking do not spend should be persistent between sessions (stored with labels perhaps), and force the user to uncheck or un-label the do not spend utxo's.

**Comment by craigraw** [comment]
You can freeze a UTXO in the UTXOs tab. Right click in the Output column.

**Comment by zonklift** [comment]
Thanks for the heads up. I had not seen that feature before (or ever right clicked the output).
