### ISSUE TITLE
Wallet import from Electrum misses most of the labels

### ISSUE THREAD

**Issue by atom686** [sparrowwallet/sparrow#46]
I tried with couple of Electrum (Coldcard + Electrum to be precise) json wallets, and all of them loose 90% of labels for addresses, transactions and UTXOs.

**Comment by craigraw** [comment]
Sparrow only supports importing of transaction labels from Electrum wallets at this time. I've tested again and I can't reproduce the issue on these - all transaction labels are imported. 

Is there anything in sparrow.log (in your .sparrow folder) or other clues that might help?

**Comment by atom686** [comment]
Logs are empty.

**Comment by atom686** [comment]
I think the problem might be in that Sparrow imports only tx labels. In electrum it shows label for an address in TX history as well. Prob the best solution might be to import all labels available.

**Comment by craigraw** [comment]
Thanks for the feedback. Importing of address labels from Electrum added in 88dfde3.

**Comment by statusquont** [comment]
Just ran into this issue as well. I have 57 transactions in Electrum. I imported the wallet into Sparrow, and only 31 retained their labels. None of the original labels have any special characters or anything. The success/failure seems randomly distributed over time. For example, 2 of the most recent transactions, received on the same day, with nearly identical labels, one imported fine, the other didn't.

**Comment by craigraw** [comment]
Ok, I've found another reason why this might occur - Electrum sometimes takes transaction labels from address labels.

I've implemented a change in 9600d57 which copies these address labels out to transaction labels when this occurs (and the transaction label isn't present).
