### ISSUE TITLE
on a standard (unmodified) Dell Inspirion7300 Win10 laptop, top & bottom parts of Sparrow frame(s?) are cropped.  Action button legends illegible & so are difficult/ impossible to use

### ISSUE THREAD

**Issue by ww49** [sparrowwallet/sparrow#460]
please see screenshots in attached MS Word doc; laptop details in the 'Dell~' doc.
[Sparrow - cropped top & bottom of frame(s).docx](https://github.com/sparrowwallet/sparrow/files/8220377/Sparrow.-.cropped.top.bottom.of.frame.s.docx)
Sparrow v 1.6.1
[Dell Inspirion7300 -About.docx](https://github.com/sparrowwallet/sparrow/files/8220406/Dell.Inspirion7300.-About.docx)

(I'm a brand new Sparrow user, eager to begin using your highly-regarded wallet.)

Thanks!

**Comment by craigraw** [comment]
This type of issue is generally resolved by explicitly setting the scaling factor for Sparrow. See the [FAQ on this](https://www.sparrowwallet.com/docs/faq.html#im-running-on-a-high-resolution-screen-and-sparrow-icons-and-text-are-tiny) - I would suggest setting the environment variable `glass.win.uiScale` to `80%` before starting Sparrow.
