### ISSUE TITLE
Feature request: saved list of private Electrum servers

### ISSUE THREAD

**Issue by maxtannahill** [sparrowwallet/sparrow#462]
The URL: has a dropdown of server history but it would be great if this could be an editable list i.e. a label to be applied for each server and for historical connections that are no longer relevant to be deleted.

**Comment by Transisto** [comment]
Trusted list of fallback node, would be good even for private servers. (Multiple uncle Jim)

**Comment by craigraw** [comment]
Implemented in 1f676927 - see https://github.com/sparrowwallet/sparrow/issues/681#issuecomment-1243773030.
