### ISSUE TITLE
Transaction to Taproot

### ISSUE THREAD

**Issue by Mitc0in** [sparrowwallet/sparrow#465]
Hi, i am a beginner so dont judge me. I created a Taproot Wallet and used the xpub to create a only watch wallet in Bluewallet. After that I send some sats to the Bluewallet. Somehow its an bc1q receive address. Some days later I want to send these somewhere else but Sparrow didnt show me the sats. The wallet ist empty. Sparrow dont show me bc1q-Addresses in Receive or Change Addresses. Whats wrong? The xpub is the same of both wallets (Sparrow and Bluewallet only watch) but only Bluewallet shows me the Address with thesats.
Thanks for help.

**Comment by craigraw** [comment]
It is very likely that Blue Wallet has assumed your xpub represents a Native Segwit wallet. Your funds aren't lost - you just need to create a Native Segwit wallet in Sparrow (using your seed words if you want to be able to send the sats out).

**Comment by Mitc0in** [comment]
I saw it was a legacy address that bluewallet created. I found out how to switch the script type of my wallet in sparrow and like magic, the funds are visible. Thanks for the fast answer!
