### ISSUE TITLE
[Feature] Add customizable PayNym names

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#469]
As every paynym has a rather generic name it is hard to remember the nyms from people you know in real life or have a closer yet pseudonymous relationship (like with a Twitter handle).

If one could add an additional, customizable name this would help to link the generic name of the nym to the name under which you know the person.

I don't know if this has implications on the potential for doxxing someone though (say you're in a chat group like Telegram, you could sample the PayNyms from different people and create a list linking the nyms to the avatars->person->potential phone numbers in the chat group). But considering that people could do such a linking on a spreadsheet anyway, I don't think there is an elevated risk for such kind of things?

**Comment by craigraw** [comment]
Implemented in c02da60. This was already possible for linked payment codes (without PayNyms) implemented in a765e07, so adding this was fairly simple. Renaming a linked PayNym contact is possible by right-clicking on it in the PayNym dialog.
