### ISSUE TITLE
'SSL Handshake Failed' dialog does not accept 'Yes' button

### ISSUE THREAD

**Issue by Sparrowhawk1337** [sparrowwallet/sparrow#472]
After rebuilding a RaspiBlitz, the SSL certificate has understandably changed.

Connecting with Sparrow Wallet to the new Private Electrum Server shows the "SSL Handshake Failed" dialog.
This includes "Do you still want to proceed?" with "Yes" and "No" options.

![screenshot](https://user-images.githubusercontent.com/101246652/159109766-f823e0d3-7b9e-4cd8-b6cf-378a4bd28def.png)

Clicking "Yes" just brings the same dialog back with no change.
I would expect it to accept the new certificate and overwrite the cached one in "C:\Users\...\AppData\Roaming\Sparrow\certs".

As a workaround, Sparrow Wallet can be closed and the cached SSL certificate deleted manually.

**Comment by craigraw** [comment]
The cached certificate file should indeed be deleted - possibly this is failing for some reason (file permissions)? Sparrow should do better at detecting this though.

Can you take a look in the sparrow log (Help menu) to see if there is a related exception?

Also, was this dialog triggered using the Test Connection button in the Server Preferences, or when Sparrow was connecting normally?

**Comment by Sparrowhawk1337** [comment]
There is an exception related to the certificate (below) but not one about the file delete failing.

`2022-03-19 X ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.TlsServerException: Provided server certificate from 192.168.1.X did not match previously saved certificate at C:\Users\X\AppData\Roaming\Sparrow\certs\192.168.1.X
	at com.sparrowwallet.sparrow@1.6.1/com.sparrowwallet.sparrow.net.TcpTransport.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.1/com.sparrowwallet.sparrow.net.ElectrumServer.connect(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.6.1/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)`

The  "SSL Handshake Failed" dialog was triggered using the "Test Connection" button.

This is on a Windows machine.

**Comment by craigraw** [comment]
Although the reason the file could not be deleted remains unclear, I've added an error dialog to indicate when this happens which provides the path to the file for manual deletion. Probably, there's not much else possible in this case. b0f60bb.
