### ISSUE TITLE
UI suggestion, Left to right panels

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#473]
I've been using Sparrow a lot and can summarize the UX flow looks something like that.

![image](https://user-images.githubusercontent.com/388716/159148097-5b1cb8c7-0261-4e85-b832-9bda7b1b2fe0.png)

I'm familiar with the flow but now my head and eyes hurts from the stain of always being on the wrong account / section of the wallet.

What would be the drawback of having the Accounts being at that alternative location?

![image](https://user-images.githubusercontent.com/388716/159148213-8a1f519b-eb13-4aee-a2bc-e9053c284c18.png)

**Comment by RequestPrivacy** [comment]
I like the idea. 

I also understand the blue "branding" of Sparrow, but what about different colors for the different (whirlpool) accounts? Lets say blue remains for the deposit and all non-whirlpool accounts. Premix gets the color yellow, Postmix green. Bad bank obviously red. 

This would improve a speedy recognition of what account you're in without even having to look at the accounts tab (similar to the color identifier of different VMs in Qubes). The question is how to insert the colors without destroying the "clean" look of Sparrow (the whole column which is currently blue, just the borders, just the account tabs...?). 

If Craig is not entirely against it I will open a separate issue for this.

**Comment by Transisto** [comment]
@RequestPrivacy Not a bad idea, but the icons could instead be more explicit, For example the Badbank is clearly Toxic,  The postmixt, ready to spend, ect,  The icons should be a bit bigger and not be sideway.

My concern is how to visually make it clear to the user that the Section in blue are for each Accounts.

This is a visual of how the user should think,

![image](https://user-images.githubusercontent.com/388716/159168852-4dbf8a3c-e20e-4ee6-93a3-4b4bbbaaf4aa.png)

**Comment by Transisto** [comment]
Here I integrated your different color concept with shades of selections.

![image](https://user-images.githubusercontent.com/388716/159171121-c1076140-69f4-4f95-bad4-6d7b1a9eca05.png)

![image](https://user-images.githubusercontent.com/388716/159171128-a85c194f-2365-44e1-936a-e8a56e0461a9.png)

![image](https://user-images.githubusercontent.com/388716/159171132-873006a7-1cb4-4adc-b06a-33a0d1a68805.png)

![image](https://user-images.githubusercontent.com/388716/159171139-37fc8466-4633-42f7-94a6-4c56f47e6dee.png)

**Comment by RequestPrivacy** [comment]
> Not a bad idea, but the icons could instead be more explicit

@Transisto not completely sure what your "instead" is referring to?

Thanks for your work with the mockup. This is exactly what I had in mind. My only concern is that the colors destroy the clean look of Sparrow. I'm not a designer but I think it will become to cheerful.

Maybe something more discreet like colored borders?

![drawing](https://user-images.githubusercontent.com/72392544/159184666-247e8106-c20d-45af-b1eb-057fdb1ff719.png)

![drawing1](https://user-images.githubusercontent.com/72392544/159184691-6c860a4c-4b0a-4f35-9d2d-2bdaedb54a70.png)

**Comment by Transisto** [comment]
@RequestPrivacy I just meant Bigger icons and not sideways. Seems self explanatory enough without color.

I like the wrap arround you've done. Just enough color to know what type of coin we're working on.

**Comment by RequestPrivacy** [comment]
Although I still think the color coding would be a valuable tool and our little mockups do the job, I'm not entirely sure if I'm happy with the look. 

**That being said, the left hand side account tabs are awesome.** I can -just by looking at the screenshots- already feel how much more natural it is. A thing I never thought I needed but once I've seen it it just feels right lol. I hope there speaks nothing against it.

I included another screenshot from your idea above and a second one with some shading on top, which makes the account tab and column feel afloat and therefore raise even more attention.

Flat look
![drawing3](https://user-images.githubusercontent.com/72392544/159186617-634470dc-4887-40d4-9af2-cbd53c83e175.png)

Floating look
![drawing2](https://user-images.githubusercontent.com/72392544/159186416-4f3a36ec-5edc-43a9-b6a6-7d1cef87769d.png)

**Comment by craigraw** [comment]
I understand the desire the reduce the mouse movement/eye tracking, and I experimented with a left accounts tab placement when building this feature originally. There are some significant downsides though - it introduces a double row of tabs, which I've never liked as UI element, and the look of it isn't great IMO - it looks complicated to my eye.

<img width="289" alt="Screenshot 2022-03-21 at 09 50 30" src="https://user-images.githubusercontent.com/862166/159222283-c4829365-01c3-465c-be08-060d014073fd.png">

Possibly this could be improved by changing the look of the tabs to the blue as suggested - unfortunately this is not as simple as it might appear, as the traditional tabs support scrolling when the number of tabs exceed the space available, which the blue tabs do not.

**Comment by RequestPrivacy** [comment]
I respect your design choice although it seems to come down to personal preference?

Would it be a great hassle to offer to the user the possibility to toggle between left & right in the settings?

**Comment by craigraw** [comment]
Some options:

Option 1:
<img width="328" alt="Screenshot 2022-03-21 at 10 23 56" src="https://user-images.githubusercontent.com/862166/159226765-6ef7a385-2da6-408d-9d18-e3405e464b52.png">

Option 2:
<img width="334" alt="Screenshot 2022-03-21 at 10 26 48" src="https://user-images.githubusercontent.com/862166/159226774-d57578c3-71cc-4834-8e25-5a7ed13b6cc2.png">

Option 3:
<img width="335" alt="Screenshot 2022-03-21 at 10 29 05" src="https://user-images.githubusercontent.com/862166/159226791-52c8859e-bd48-43d5-9fac-deef246232de.png">

Option 4:
<img width="336" alt="Screenshot 2022-03-21 at 11 09 03" src="https://user-images.githubusercontent.com/862166/159232383-3fff5a7d-a43a-48b2-86bf-f511873e8a88.png">

Of these, option 4 appears best to me.

However, there is another downside: the blue bar of tabs shifts when tabbing between wallets with accounts, and those without. The content inside the tab also shifts, which is not ideal. One solution would be to always show the account tab header, although this does include UI complexity for the beginner.

![tabs](https://user-images.githubusercontent.com/862166/159230989-9674d111-b28a-49c8-bf82-f339fe127eee.gif)

**Comment by RequestPrivacy** [comment]
I also like option 4, as the the contrast to the currently selected "Send" tab is gradual. Next best option is no. 3 imho.

The shifting looks indeed weird. Is there a way for the interface to query if wallets with multiple accounts are open (which would suggest a "power user") - it then could display the account tab header for all wallets, even for the ones which currently have just the default account. So the power user sees no shifting if he switches the wallets but also doesn't get confused it standard account tabs appear on the other wallets.

For a more "regular" user / a power user who has no wallets with multiple account structure open, the interface can display no account tabs.

One could also argue that Sparrow is the superb wallet because it teaches users in the usage of Bitcoin. Introducing an account tab for all is just a next step to raise awareness that there even exists something like "accounts".

**Comment by craigraw** [comment]
Implemented in 230a4c5. Once a wallet with multiple accounts has been opened, all open wallets will show subtabs from then on. This permits the "gradual discovery" that I feel is important to make the wallet more approachable, but minimizes the amount of change to the interface during operation.

<img width="1150" alt="Screenshot 2022-03-22 at 09 24 09" src="https://user-images.githubusercontent.com/862166/159429245-3599c2c4-9707-4a8c-9bf1-3bb9b4aca9b4.png">
