### ISSUE TITLE
Linking Paynym does not work

### ISSUE THREAD

**Issue by CommanderUkraine** [sparrowwallet/sparrow#474]
Linked several times PayNym Account ("Link Contact") and each time sent the corresponding TX. 

Even after 12 confs program show the PayNim still as unlinked, could repeat it with numerous PayNyms.

**Comment by craigraw** [comment]
Can you take a look in the sparrow log file (Help menu) to see if there is anything relevant? Particularly around the times that you sent the notification transactions. Please paste any exceptions here if found.

**Comment by craigraw** [comment]
Closing, see #475.
