### ISSUE TITLE
Tab order not remember between app restarts

### ISSUE THREAD

**Issue by statusquont** [sparrowwallet/sparrow#477]
I had 4 wallet tabs opened. I wanted to change the order of the tabs so I closed the wallets that were in the 'wrong' position in the tab bar and then re-opened the wallets in the order I wanted them to appear. A bit of a kludge, but not a deal breaker. I closed down Sparrow. When I reopened it, the tabs were back in the 'wrong' order that had appeared before I 'fixed' it. Would be nice if the order was remembered between sessions. 

See also #476 which is a bit related.

**Comment by craigraw** [comment]
Unencrypted wallets open before encrypted ones - does this cause the 'wrong' order? It would be possible to rearrange the tabs after all passwords entered, but I'm not sure if this would look a bit strange.

**Comment by statusquont** [comment]
In this case, all wallets were undecrypted.

**Comment by craigraw** [comment]
Unencrypted wallet tab order is now retained between app restarts. d9bba16.
