### ISSUE TITLE
Select all button on UTXO tab.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#478]
![image](https://user-images.githubusercontent.com/388716/159382278-7d08ffbf-75b7-429c-9311-6ce57c269488.png)

Most commonly I select all with CTRL+A before mixing, So a button there would help people who don't know the shortcuts.

**Comment by craigraw** [comment]
Not a bad idea, but space is limited and there may be a need for additional (more important) functionality in this area in future. It's difficult to take functionality away after it's been added.

**Comment by RequestPrivacy** [comment]
> So a button there would help people who don't know the shortcuts.

Maybe under Help a `Keybindings` or `Shortcuts` section to familiarize users with the availability?

**Comment by Transisto** [comment]
> 

"Select All" and "Clear" are mutually exclusive so can be renamed depending if any selection is made.

**Comment by RequestPrivacy** [comment]
Not sure about the mutually exclusive argument. What about having already selected a  subset? Now the user could want to `Clear` or `Select All`.

**Comment by Transisto** [comment]
> Not sure about the mutually exclusive argument. What about having already selected a subset? Now the user could want to `Clear` or `Select All`.

You're somewhat right but the "Select All" button is mostly for people who might not know about about CTRL+A shortcut and want to start a MIX.

**Comment by craigraw** [comment]
I've reconsidered this, and decided to add a 'Select All' button to the UTXOs tab. It's probably a common enough use case that the UI space consumed worth it. 6931cf7.
