### ISSUE TITLE
[Displaying Bug] Postmix UTXO bar chart has missing utxos bars after remix 

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#479]
During remixing all utxos are shown in the bar chart, no matter if registered input or waiting to be queued for remixing.

Once a utxo participates successfully in a remix, it is put into an unconfirmed state, waiting in the mempool to get confirmed. It would be reasonable to remove it from the utxo bar chart until this happens.

I noticed something strange though: some bars are indeed missing (the unconfirmed mixed one isn't under those tough), see the attached picture. 

**It looks like the newly selected utxo for further mixing suddenly disappears as well as another one (it seems the previously mixed one, can't confirm this 100%).** All utxos shown are from the same pool size.

The bars don't come back once the unconfirmed utxo is included in a block. If I reopen the wallet after it has been confirmed all bars are back.

I run a Linux machine and the latest Sparrow 1.6.2 including all newly added features since the release.

![sparrow_mixing_missing](https://user-images.githubusercontent.com/72392544/159454378-ce9cb008-1b1e-4c27-bd57-43d5e05d02dd.png)

**Comment by RequestPrivacy** [comment]
After a remix has happened with the wallet in the locked state no bars are visible at all. Other accounts (e.g. Badbank) aren't affected.

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in b1940e9.
