### ISSUE TITLE
Errors when creating new wallet with Ledger Nano X

### ISSUE THREAD

**Issue by chadb78** [sparrowwallet/sparrow#481]
When trying to create a new wallet, I choose scan to look for my device and I get the error: "Error executing HWI". I I cancel and try this again, I can get pass the connect screen, but when I try to import the Keystore I get the error: 

"Could not retrieve xpub"
java.io.IOExeption:Cannot run program
C:\Users...\hwi-2.0.212169735412740647651.tmp
CreateProcess error=5, Access is denied

**Comment by craigraw** [comment]
This is due to a Windows file permission error executing the file `C:\Users...\hwi-2.0.212169735412740647651.tmp`. It's unclear why this is happening, since Sparrow is creating that file. 

For further debugging, can you provide the Windows version you are using?

**Comment by chadb78** [comment]
Windows 11

**Comment by craigraw** [comment]
There's some evidence to suggest this may be related to antivirus software. Can you try temporarily turning any antivirus off to see if it is the cause?

**Comment by craigraw** [comment]
Old issue without response, closing this off.
