### ISSUE TITLE
[Error] Min relay fee not met

### ISSUE THREAD

**Issue by Xaspr** [sparrowwallet/sparrow#486]
On a pretty sizable transaction, I received the error 'min relay fee not met'.

From the logs:

> min relay fee not met, *** < ***
> [...]
> at com.sparrowwallet.sparrow@1.6.2/com.sparrowwallet.sparrow.net.BatchedElectrumServerRpc.broadcastTransaction(Unknown Source)
> ... 12 common frames omitted
> Caused by: com.github.arteam.simplejsonrpc.client.exception.JsonRpcException: ErrorMessage{code=1, message=the transaction was rejected by network rules.

It was a segwit multisig transaction with a fee of 1.00 sats/vB. 

Any idea what went wrong here? Would this be solved if the fee is higher than 1.0 sats/vB?

**Comment by craigraw** [comment]
> Would this be solved if the fee is higher than 1.0 sats/vB?

Yes, make it slightly higher and the transaction will work.

You haven't mentioned what is doing the signing here, but it's possible that it is not creating canonical signatures, which is increasing the size of the transaction slightly larger to that which Sparrow is estimating. See https://github.com/sparrowwallet/sparrow/issues/144#issuecomment-869560080 for details.
