### ISSUE TITLE
Reduce time for mouse-over tooltip

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#489]
Delay is about 3000ms, Fells very long

Did some research, and it suggest between 300 and 500ms

> "I found a couple of libraries where the tooltip seems to be set at a **default of 500ms**, which seems quite reasonable."

https://ux.stackexchange.com/questions/358/how-long-should-the-delay-be-before-a-tooltip-pops-up

**Comment by craigraw** [comment]
Actually, the default is 1 second, but it has been reduced in many places. All of the table cell related tooltips have been reduced to 250ms, and the transaction diagram tooltips to 50ms.

If there is a specific tooltip that you feel is taking too long to show, please describe where it is.

**Comment by Transisto** [comment]
Those were the question marks in setting / advanced.
For example those in https://github.com/sparrowwallet/sparrow/issues/490

**Comment by craigraw** [comment]
Reducing the help tooltip show delay to 500ms in 1f51f63.
