### ISSUE TITLE
Question and suggestion

### ISSUE THREAD

**Issue by bitcoinheiro** [sparrowwallet/sparrow#49]
Hi, been testing sparrow and I find it quite good so far.
I've got one question regarding the price fetch from coinbase/gecko. How is it done? Does the wallet requests price for specific amounts of sat every time or for the price of a whole bitcoin every X time and then calculates the price for the specific amount locally when user requests?

Would be great to make clear to user how price is fetched (if it's privacy oriented) and maybe provide an internal calculator tab where user can fetch price of a whole bitcoin from a source or use his own price to calculate their sats related calculations outside of google and straight into the wallet software. To encourage good practices.

Cheers!

**Comment by craigraw** [comment]
Thanks! And thank you for your video tutorial - didn't understand much but picked up a few minor UI issues to work on. 

Re exchange rates, this the exact call that is made: https://api.coingecko.com/api/v3/exchange_rates https://github.com/sparrowwallet/sparrow/blob/038069f6e63b4508d83c4e79bcd1cd8102c98054/src/main/java/com/sparrowwallet/sparrow/net/ExchangeSource.java#L85

As you can see there are no specifics passed  - it's just the various prices for 1 BTC. Sparrow then calculates using those rates to show you the actual balance of your wallet.
