### ISSUE TITLE
I had downloaded and just set up Sparrow... old version needed update in order to receive BTC from a crypto exchange...

### ISSUE THREAD

**Issue by WaysideRewlz** [sparrowwallet/sparrow#495]
Not a problem - more of a problem and the fix that I found solved the problem...

I downloaded and just set up Sparrow for the first time (using with a hardware wallet).  I did a test transfer of some BTC from a crypto exchange to my Sparrow wallet.  Waited for what seemed like a long time - over an hour, and did not see the BTC coming into Sparrow... There were some error messages in the log file, but I wasn't sure what they meant, tried to google them, but couldn't find the exact error messages... Found something that told me to toggle the switch in the lower right hand corner, that had been turned off... When I turned it ON, it started to connect to a Electrum server, and it didn't connect, but it told me that there was a new version of Sparrow available (I was using 1.5.6 and the new version is 1.6.2).  I downloaded the newer version, and when it fired up, it connected to the Electrum Server right away (didn't have to toggle the switch in the lower right hand corner), and it found the BTC from the crypto exchange, that I hadn't seen before.  So, not sure whatALL was the initial problem with the older version of Sparrow, but for me, downloading the new version seemed to fix the problem.

**Comment by craigraw** [comment]
Thanks for the feedback. What probably happened was that your previous install had selected a public server that wasn't responding at the time. The new version switched to a new public server. The version update in the status bar is actually unrelated to the server comms.

Anyway, glad it's working.
