### ISSUE TITLE
[UX/Suggestion] 'Mix to wallet' drop down list doesn't update after renaming a wallet account

### ISSUE THREAD

**Issue by rstmsn** [sparrowwallet/sparrow#497]
When on the UTXO tab of an open wallet, clicking the 'Mix To' button opens a dialog box. The first option on this dialog is 'Mix to wallet'. It displays a drop down list of open wallets where coins can be sent, after a certain number of successful mixes.

If the open/available wallets have multiple accounts, these accounts are included as individual options in the 'Mix to wallet' drop down list.

If you switch to one of these open wallets, and rename one of it's Accounts, when you swtich back to the mixing wallet, and press 'Mix to', the list of available wallets/accounts does not update to reflect the account that was renamed. 

I think the UX could be improved if this list updated automatically, to reflect the renaming of wallet accounts.

**Comment by craigraw** [comment]
> If you switch to one of these open wallets, and rename one of it's Accounts, when you swtich back to the mixing wallet, and press 'Mix to', the list of available wallets/accounts does not update to reflect the account that was renamed.

I wasn't able to recreate this behaviour (the list does update appropriately) but Mix To button did not. This is fixed in dd5278f.
