### ISSUE TITLE
Locked wallet is unlocked after restart

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#498]
I have two wallets open within Sparrow. If I lock one of them (View - Lock Wallet) then close the application, when I reopen the Sparrow the locked wallet is unlocked.

**Comment by craigraw** [comment]
This is expected behavior. I don’t think most users would want their wallet to be locked just after they have entered their password to open it - if it was, they would need to enter their password twice. It’s easy enough to lock with the keyboard shortcut.
