### ISSUE TITLE
Clear button on UTXOs tab is never inactive

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#499]
If I look at the UTXO tab of a wallet the "Send Selected" button is greyed out unless one or more UTXOs are selected, at which point it becomes active. However, the "Clear" button is always active whether there are UTXOs selected or not.

**Comment by craigraw** [comment]
Fixed in 6aa3bb2.

**Comment by hur4hur5** [comment]
Can confirm working correctly in 1.6.4.
