### ISSUE TITLE
~/.sparrow dir created despite use of --dir

### ISSUE THREAD

**Issue by bitcoinhodler** [sparrowwallet/sparrow#50]
I'm trying to run two instances of Sparrow 0.9.9, one each for mainnet and testnet. To keep them segregated, I run the testnet instance like so (on Ubuntu Desktop 20.04.1):
```
/opt/sparrow/bin/Sparrow --dir /home/user/.sparrow-testnet --network testnet
```

Most files then get created in `/home/user/.sparrow-testnet` -- but it still creates a directory `/home/user/.sparrow` with one file `sparrow.log`.

Shouldn't the log file also go in the specified `--dir`?

**Comment by craigraw** [comment]
Indeed! Fixed in d722c49
