### ISSUE TITLE
Sorting on Output column incorrect on Premix account

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#500]
I coinjoined. Many UTXOs entered my Premix account. All the UTXOs, as expected, had the same transaction id. When I sorted by the "Output" column the rows were sorted in the below manner. This may not be the exact behavior as I didn't screenshot it, but it was something along these lines. I would expect it to sort as 1, 2, 3, ...., 20, 21 instead.

6e48ab49:1
6e48ab49:11
6e48ab49:12
6e48ab49:13
6e48ab49:14
6e48ab49:15
6e48ab49:16
6e48ab49:17
6e48ab49:18
6e48ab49:19
6e48ab49:2
6e48ab49:20
6e48ab49:3
6e48ab49:4
6e48ab49:5

**Comment by craigraw** [comment]
Fixed in 37a8a0a.
