### ISSUE TITLE
Graph on transaction tab suffers from x-axis not adjusting

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#501]
The x-axis on the "Transactions" tab's graph seems to never be finer than days. This can make the graph look broken when all transactions happen within a few hours.

This is a Premix account on a wallet (labeling on axis' cut off for privacy). UTXOs arrived and then were mixed quickly. This resulted in the balance shooting up and then back down to zero within less than an hour. As I result I'm guessing the up and the down are represented by the vertical light grey line on the far left. The graph keeps updating as days go by to show the current date on the far right of the x-axis. Maybe this shouldn't happen but instead have the date/time of the first and the last transactions on the account be the far left and far right of the x-axis respectively?
![Screenshot from 2022-04-02 22-43-33](https://user-images.githubusercontent.com/102880838/161402284-a9c80638-8c97-4ec6-95c6-60a50730326c.png)

Because my Badbank account shot up and stayed up it looks more normal.
![Screenshot from 2022-04-02 22-51-29](https://user-images.githubusercontent.com/102880838/161402468-bd658d1a-5c4a-4bb4-a8e7-a3cdd17b6757.png)

.

**Comment by craigraw** [comment]
I think it's more important to have consistent axis behaviour. Specifically, the graph should always display starting from the birth date of the wallet, and ending at the current date. 

The alternative you've described might result in finer detail on the flow of funds for the particular case you've described (although I'm not sure there's a great deal of value in this specific case) but it would mean the user would need to check the x-axis every time to  determine the period displayed, adding to the cognitive burden. 

For this reason I'm inclined to leave things the way they are. This chart is intended as a quick overview of wallet history, and if all activity happened a long time in the past, this is currently indicated. Possibly future improvements might include some zooming or other period manipulation.

Here's a premix wallet chart which exhibits the "up & down" typical of this account, but with many premixes over time:
<img width="379" alt="Screenshot 2022-04-26 at 16 37 01" src="https://user-images.githubusercontent.com/862166/165325295-e48f9158-031d-4f3e-a54d-1dba7c8a6d50.png">
