### ISSUE TITLE
Try to connect to Electrum at intervals

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#502]
Sparrow is connected to my node (Private Electrum Server over Tor). If I turn my node off Sparrow disconnects as I'd expect and the toggle in the bottom right turns off. When I bring my node back up I have to manually switch the connection toggle back on again. Could Sparrow try at intervals to reconnect and so make this a bit smoother for users?

**Comment by craigraw** [comment]
It does try to reconnect at intervals, starting off at around a minutes delay which increases logarithmically if a failure occurs.
