### ISSUE TITLE
Coldcard instructions incorrect when creating additional accounts.

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#503]
When adding an account to a wallet with an airgapped Coldcard the instructions found by clicking "Details" are incorrect. You are instructed: "Advanced > MicroSD > Export Wallet > Generic JSON > 0" but this is incorrect and will always export the JSON for account 0 on the Coldcard. If I'm creating account 1, 2, etc on Sparrow then these instructions should be dynamic and say "... Generic JSON > 1", etc.

![Screenshot from 2022-03-31 20-14-56](https://user-images.githubusercontent.com/102880838/161403101-5ebe053a-2273-4e37-a30c-5ea2fd9cc51a.png)

**Comment by craigraw** [comment]
Fixed in e565786.
