### ISSUE TITLE
Open transaction tab doesn't update upon block being mined

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#504]
I had the Postmix account open, viewing the UTXOs window and happened to see a UTXO enter a mix as it became labeled "Unconfirmed, not yet mixable" (or something to that effect). So I used the magnifying glass icon in the output column to open the transaction in a new tab for viewing. Under the Blockchain section of the transaction tab it said "Status: Unconfirmed" as expected because the tx was still in the mempool.

When the tx was mined into a block it remained in this same unconfirmed state even though in the transactions window it showed the pie chart slightly filled in to show one of six confs. It remained this way as more blocks were mined on top. Only when closing the transaction tab in question and clicking the magnifying glass again did the "Blockchain" section of the transaction tab show the correct details.

Transaction tab for the tx in question (the one with the paper plane and e.g. [67abba74] in the title)
![Screenshot from 2022-04-01 16-14-35](https://user-images.githubusercontent.com/102880838/161403291-106831db-67b2-4e99-b45e-103e4e14832d.png)

Close up of the value column for the same tx on the "Transactions" tab at the same time
![Screenshot from 2022-04-01 16-14-45](https://user-images.githubusercontent.com/102880838/161403293-a95e82d0-a96b-429f-bbdc-fd3d9e3213fd.png)

**Comment by craigraw** [comment]
Fixed in eceaf40.

**Comment by hur4hur5** [comment]
Can confirm working in 1.6.4.
