### ISSUE TITLE
View -> Lock All Wallets never greyed out

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#506]
When the active wallet is unlocked the View -> Lock Wallet option is clickable. When the active walled is locked the View -> Lock Wallet option is greyed out and not clickable. So the Lock Wallet option is responsive to the state of the active wallet.

When all wallets are locked, the View -> Lock All Wallets option is not greyed out which does not make sense. It should grey out and be unclickable if all wallets are already locked.

Clicking View -> Lock All Wallets does indeed lock all wallets but at this point also does not become greyed out and unclickable.

**Comment by craigraw** [comment]
Fixed in 1ccfc3c.
