### ISSUE TITLE
When reducing addresses monitored Postmix consider some remixes as incoming transactions.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#507]
I understand this is a symptom of reducing monitored addresses. (last 200)
But it should be possible to detect and apply the changes to our old address when it's part of a transaction at a newer index. 

If we know our own Tx0 and monitor the remix received we shouldn't in theory not have to monitor old indexes in Postmix since we're not supposed to hand out these addresses for payments.

<img alt="image" src="https://user-images.githubusercontent.com/388716/161434914-b19ec77b-460f-478f-882a-ef7852e372d9.png">

This transaction show it thinks it only received.
<img alt="image" src="https://user-images.githubusercontent.com/388716/161435452-91c59e01-e54d-4230-93b8-f7eab8a96883.png">

Transaction details show it knows which input belong to Postmix ..0/1367/ and the output ..0/1550/ but the first one is not applied to history.

**Comment by craigraw** [comment]
Adding this functionality would be complex, and I'm not sure the additional maintenance burden is worth it given (I believe) the limited use of reducing monitored address functionality at this time. The simple solution is to use a performant personal server like Fulcrum and monitor all addresses, which in a sense offloads the complexity to where it belongs. 

For this reason I'm going to close this off at this time.
