### ISSUE TITLE
Allow to broadcast an imported transaction.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#508]
<img alt="image" src="https://user-images.githubusercontent.com/388716/162287244-ba9e6f80-4ad4-47d3-b929-2d0f9842f23c.png">

![image](https://user-images.githubusercontent.com/388716/162287461-7262c9c5-3575-4255-b5be-4fc766f9091b.png)

**Comment by craigraw** [comment]
I believe this only happens if Sparrow is offline when you load the transaction? Sparrow needs to perform a blockchain lookup to determine if the transaction has already been broadcast.

**Comment by Transisto** [comment]
You're right, the wallet wasn't connected, regular broken sockets issue. 

<img alt="image" src="https://user-images.githubusercontent.com/388716/162629858-4ea1e774-80a2-4f58-8522-c54ae9230198.png">

While on that view, What's "Keystore 1" when transaction is already signed from another wallet?

**Comment by craigraw** [comment]
> While on that view, What's "Keystore 1" when transaction is already signed from another wallet?

It's just a default name for the keystore that Sparrow creates when loading the transaction into its wallet model.
