### ISSUE TITLE
"Send To Many" require double-clicking a box to be able to Copy/Paste

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#509]
<img alt="image" src="https://user-images.githubusercontent.com/388716/162346553-32014402-0922-403e-a37f-fb013f18ecdb.png">

This one doesn't work.

<img  alt="image" src="https://user-images.githubusercontent.com/388716/162346703-ee1f03fe-443d-4398-8ff2-f6654ebd06c5.png">

The cursor has to show up for this one to appear.

**Comment by craigraw** [comment]
Fixed in 472fccc - you can now paste in a string without editing the cell.
