### ISSUE TITLE
Wallet loading log not updating for all accounts

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#513]
I have multiple accounts on a wallet (m/84'/0'/0', m/84'/0'/1', etc) in Sparrow. Sometimes when I load the wallet on startup the folder icon in the wallet's tab is red indicating some sort of error. When I then look on the Transactions tab I can see the 'Wallet Loading Log' at the bottom of the window and the last entry in this log is "... Failed to subscribe to paths ...". This is the same for the 'Wallet Loading Log' on all my accounts for this wallet.

I then go to the first account and select [View->Refresh Wallet]. Sparrow then adds more rows to the log to indicate transactions were successfully loaded. So far so good.

But if I then look at the wallet loading log for the other two accounts the last log entry is still the failed to subscribe to paths one. If I click refresh wallet again, this time with account /0'/1' selected, the loading log updates for this account as it did for /0'/0'. But the loading log for /0'/2' is still showing failed to subscribe. So it seems that in order to get the wallet loading log to show a more reassuring "Finished loading." message for each account you need to [View->Refresh Wallet] for every account in your wallet. Now I don't know if this means Sparrow is only refreshing the account in question or if it is refreshing all of them. But not having the log update for every account is disconcerting.

I've attached screenshots of the logs for accounts 0' through 2' and you'll be able to see the similar timestamps on each log for when the wallet was opened and then slightly different timestamps on each account's log as I refreshed each one in turn.

Also worth noting is that the red icon next to the wallet name went back to white from red after I refreshed account 0.

Account 0
![Screenshot from 2022-04-09 12-27-22](https://user-images.githubusercontent.com/102880838/162572674-e694ebfc-3cd0-40ee-b888-6f9ddc96e61f.png)

Account 1
![Screenshot from 2022-04-09 12-27-27](https://user-images.githubusercontent.com/102880838/162572676-54ec1768-0e3d-4423-9663-6f7f4d6535c3.png)

Account 2
![Screenshot from 2022-04-09 12-27-02](https://user-images.githubusercontent.com/102880838/162572682-7803fee1-8fe9-42e9-ad62-8eae1a9f7ac4.png)

**Comment by craigraw** [comment]
You do have to "refresh wallet" for every account. This is mainly a consequence of the widespread use of Electrs, which does not scale well and would not handle multiple simultaneous wallet refreshes, particularly when the wallets are deep. The best solution to this problems is to change your Electrum server to Fulcrum, which is a much more performant implementation. See the Electrum server benchmark in the docs for details.

Hopefully when Fulcrum becomes more default, Sparrow can move to refreshing all wallets at once.

**Comment by hur4hur5** [comment]
My Sparrow instance is pointed at an Umbrel at the moment which uses Electrs protocol I assume.

From what you're saying (and from my initial quick read of https://sparrowwallet.com/docs/server-performance.html) I could look into doing an IBD and running Fulcrum on a separate machine and then link Sparrow to this whilst we wait for projects like Umbrel to consider moving to Fulcrum. This would allow me to confirm what you're saying and give feedback on a Sparrow/Fulcrum combo. Is that understanding correct? Really liking Sparrow and keen to contribute in ways I'm able.

Is it worthwhile in the meantime considering renaming "Refresh Wallet" to "Refresh Account"? This would have saved the confusion I found here. Then when in future you have Fulcrum as an option in [File->Preferences->Server] this could change back.

**Comment by hur4hur5** [comment]
If there is only one account (as I guess is the case 95% of the time) then it could stay as "Refresh Wallet". But "Refresh Account" would seem to be a more accurate term for wallets with more than one account.

**Comment by craigraw** [comment]
> Is that understanding correct?

Yes - testing is always welcome, although I have little doubt Fulcrum will solve these issues.

Re renaming the menu command, it’s a good idea worth considering. Perhaps ‘Refresh Wallet Account’ would be clearer. Will consider.

**Comment by hur4hur5** [comment]
Agree 'Refresh Wallet Account' would be clearer.

**Comment by hur4hur5** [comment]
What about leaving the menu option as "Refresh Wallet" when there is only one account for the wallet. This would be the case in the majority of cases. It would be my presumption that when a wallet has multiple accounts the user would be aware of the term "Account" and so renaming the option to "Refresh Account" only for wallets with multiple accounts would seem reasonable?

**Comment by hur4hur5** [comment]
Fulcrum. You are correct that this is a significant improvement. This has solved the confusing "red folder" issue that appeared from time to time. This hasn't occurred since moving to Fulcrum. The errors I used to see in the transaction log window when refreshing the wallet also now never occur. In fact, the failures caused by Electrs(?) on my Umbrel node were the only thing that required me to refresh the wallet/account. I have not had to refresh anything since switching.

For those interested I have bitcoind running locally on the same machine as Sparrow with storage on a dedicated M.2 SSD. Fulcrum is also running locally on my machine pointed at my local bitcoind instance. Its storage is also on the same SSD. Fulcrum took ~28 hours to do the initial indexing.

Wallet loading is sub one second fast as are the updates after transactions.

The Fulcrum solution will surely be favored over others by everyone at some point. Highly recommended and thank you for the recommendation. It was straightforward to set up. If the node packages switched to this then surely that would be an easy win for them and everyone else.

**Comment by craigraw** [comment]
> so renaming the option to "Refresh Account" only for wallets with multiple accounts would seem reasonable?

Good refinement. Implemented in dd1976f.

Thanks for the comments on Fulcrum - it is indeed a step change in performance and overall user experience.

**Comment by hur4hur5** [comment]
This does not appear to be working correctly on 1.6.4. I see the 'View -> Refresh Wallet Account' option at all times, regardless of how many wallets I currently have open. Running Ubuntu Linux.

**Comment by craigraw** [comment]
> I see the 'View -> Refresh Wallet Account' option at all times, regardless of how many wallets I currently have open.

Just to check we are on the same page - you should see 'Refresh Wallet Account' on wallets with more than one account (multiple tabs on the left). On wallets with a single account (one tab on the left, or none visible) it should be 'Refresh Wallet'.

**Comment by hur4hur5** [comment]
You have a very polite way of telling people they're wrong. Which I am. This is working correctly and I was mistaken. I've spent time today testing functionality on a few tickets I've authored and got wallet tabs and account tabs conflated. More attention needed. Thanks @craigraw, loving using Sparrow.
