### ISSUE TITLE
Error running in Umbuntu on Mac M1 Parallels

### ISSUE THREAD

**Issue by lookingcloudy** [sparrowwallet/sparrow#514]
uname -m -> aarch64

Downloaded the correct java jdk:
OpenJDK16U-jdk_aarch64_linux_hotspot_16.0.2_7.tar.gz

the build was successful.
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/5413972/162579131-49e7115d-6cb8-4ba9-aebd-e16f6be5a992.png">

Running ./sparrow failed with this error:

Sounds like a JDK problem.  All libs are updated.  Googling doesn't seem to uncover any solutions.  Any ideas?
<img width="752" alt="image" src="https://user-images.githubusercontent.com/5413972/162579500-924c5180-860f-4ed6-b912-d477949c685a.png">

**Comment by craigraw** [comment]
The reason given as the "Possible cause" in the screenshot sounds correct to me. I'm due to start on the OSX M1 version of Sparrow soon, after which I might be able to offer a solution.

**Comment by craigraw** [comment]
Old issue, support for Linux aarch64 has been present for some time.
