### ISSUE TITLE
Strange problem connecting to a local Bitcoin Core

### ISSUE THREAD

**Issue by chocolatebarantlion** [sparrowwallet/sparrow#515]
Hello,

I installed Sparrow 1.6.3 on a fresh Windows 10 computer, after I installed Bitcoin Core and did a full sync with the ledger.

I configured Sparrow to connect to the Bitcoin Core, and it worked perfectly at first, I was able to do a few transactions.

But then a strange problem occurred : 

- When I launch Sparrow, it connects to Bitcoin Core without problem (the dot in the lower right corner is green, and the message "Connected to http://127.0.01:8332 at height XXXXXX" is displayed)

- But when I open one of my wallets, suddenly I get the message "Connection failed: Server Error (Check if Bitcoin Core is running...)", and it is impossible to toggle the dot in the lower right corner to the "connected" status

- BUT when I go to the server settings in the Preferences, and I click on "Test Connection", it works ! I get a green mark, and the message :

`Connected to bwt v0.2.4 on protocol version 1.4
Server Banner: 
   ██████  ██     ██ ████████ 
   ██   ██ ██     ██    ██    
   ██████  ██  █  ██    ██        █▀▀█   █▀█    █▀█  
   ██   ██ ██ ███ ██    ██    █ █ █  █    ▄▀   █▄▄█▄ 
   ██████   ███ ███     ██    ▀▄▀ █▄▄█ █ █▄▄ █    █  

   ／Ｓａｔｏｓｈｉ：２２．０．０／

   🗄️ ᴀʀᴄʜɪᴠᴀʟ 🗣️ ᴍᴇᴍᴘᴏᴏʟ ʀᴇʟᴀʏ 🙉 ɴᴏʟɪsᴛᴇɴ

     NETWORK: 🌐  ᴍᴀɪɴɴᴇᴛ
   CONNECTED: 💻  10 ᴘᴇᴇʀs
      UPTIME: ⏱️  3 ᴍɪɴs

   BANDWIDTH: 📶  85.4 ᴍʙ 🔼  4.1 ɢʙ 🔽 (24ʜ ᴀᴠɢ)
  CHAIN SIZE: 💾  454.5 ɢʙ

    HASHRATE: ⛏️  207.0 ᴇʜ/s (7ᴅ ᴀᴠɢ)
  DIFFICULTY: 🏋️  28.6 ᴛ (ʀᴇ-🎯  ɪɴ 3 ᴅᴀʏs ⏳)
  REWARD ERA: 🎁  6.25 ʙᴛᴄ (½ ɪɴ 25 ᴍᴏɴᴛʜs ⏳)

  LAST BLOCK: ⛓️  731250 ／ 4 ᴍɪɴs ᴀɢᴏ ／ 4.0 ᴍᴡᴜ ／ 2.8ᴋ ᴛxs
                 Fᴇᴇ ʀᴀᴛᴇ 3-9 ／ ᴀᴠɢ 7 ／ ᴛᴏᴛᴀʟ 0.077 ʙᴛᴄ
     MEMPOOL: 💭  272.3 ᴠᴋʙ ／ 629 ᴛxs ／ ᴍɪɴ Fᴇᴇ ʀᴀᴛᴇ 1
    FEES EST: 🏷️  20 ᴍɪɴs: 4 ／ 4 ʜᴏᴜʀs: 1 ／ 1 ᴅᴀʏ: 1

 SUPPORT DEV: 🚀  bc1qmuagsjvq0lh3admnafk0qnlql0vvxv08au9l2d ／ https://btcpay.shesek.info
`

Do you have any idea how I could solve this problem ? :)

**Comment by craigraw** [comment]
Are you opening a Taproot wallet? Unfortunately there are changes still required in upstream projects to support Taproot when connecting to Bitcoin Core.

**Comment by chocolatebarantlion** [comment]
> Are you opening a Taproot wallet?

Yes I had to, because I was sending money from an old wallet that doesn't support native Segwit addresses.

> Unfortunately there are changes still required in upstream projects to support Taproot when connecting to Bitcoin Core.

So does it mean I cannot spent the money I received on this Taproot address ?

**Comment by craigraw** [comment]
If you use a private or public Electrum server, it will work fine. Taproot support with Bitcoin Core will hopefully land soon.

**Comment by chocolatebarantlion** [comment]
> If you use a private or public Electrum server, it will work fine. Taproot support with Bitcoin Core will hopefully land soon.

Hello, just coming back for an update. Does Taproot support with Bitcoin Core now work ?

**Comment by craigraw** [comment]
> Hello, just coming back for an update. Does Taproot support with Bitcoin Core now work ?

Yes
