### ISSUE TITLE
Selecting many UTXOs for Cahoots - Large Negative Fee Error

### ISSUE THREAD

**Issue by apemithrandir** [sparrowwallet/sparrow#517]
- I have two instances of Sparrow Wallet open each with a different wallet file open.
- In the first instance I select a large number of different post-mix UTXOs (>10) and select to send them to an external address.
- I change the amount from being equal to the sum of all UTXOs to being slightly less than or equal to (Sum of UTXOs - fee)/2.
- Now I select "Add Mix Partner" and choose the PayNym of my second wallet as the mix partner.
- On the select wallet I select Post-Mix as the account to perform the Stonewall x2 from and match up with my first wallet.
- I return to my first wallet to review the transaction and I see that a random subset of my initial UTXOs have been selected for the transaction as well as a random 2 UTXOs from the second wallet.
- The fee amount displayed is a very large **negative** number:
- ![image](https://user-images.githubusercontent.com/99969638/162860545-bd7e9ff3-e81a-488d-b280-c241f931f3e9.png)
- All the numbers "add up" but the UTXOs selected from the first wallet amount to less than spending amount.
- The application then tries to receive fees via a negative fee amount in order to "add up" to the required spending amount.
- In terms of reproducibility, if I change around my initial UTXO selection it doesn't always happen. But if I keep my initial UTXO selection the same it will happen every time. Also if I lower the spending amount with the same UTXO selection the error will also disappear.
- It seems to be related to the random selection of UTXOs chosen from the initial UTXO set.
- Given that getting to the source of the error may require revealing information about my UTXOs, I may not be able to help so much in this public forum but if you (@craigraw) want you can direct message me via some private messenger.

**Comment by craigraw** [comment]
Looks like a tricky error - I was unable to reproduce this.

If possible, can you try recreating it, but [running with DEBUG logging](https://www.sparrowwallet.com/docs/faq.html#how-can-i-run-testnet)? 

There will be a lot of logging, but we are looking for lines starting with the following:
```
BIP84 utxos: 
BIP84 selected utxo:
[8] selected utxos, totalContributedAmount=
```

**Comment by apemithrandir** [comment]
I have since updated a few times and can no longer reproduce this bug.
