### ISSUE TITLE
FEATURE REQUEST - Allow switching to Testnet mode via UI

### ISSUE THREAD

**Issue by BitcoinQnA** [sparrowwallet/sparrow#518]
Sparrow has been my go to recommendation for desktop for a long while now and I often urge people to try it out in testnet mode first to get comfortable. It would be great if users could achieve this from the preferences pane in the UI rather than needing to follow [these](https://sparrowwallet.com/docs/faq.html#how-can-i-run-testnet) instructions, which, although well documented, can be a little daunting for newer Bitcoiners.

**Comment by craigraw** [comment]
Implemented in c981cf3. If Sparrow is running in mainnet, there will be a Tools menu item to 'Restart in Testnet'. This will change to 'Restart in Mainnet' if Sparrow is not running mainnet.

**Comment by hur4hur5** [comment]
Can confirm this is working well in 1.6.4 on Ubuntu Linux. Commenting here as it may be worthwhile updating the docs at https://sparrowwallet.com/docs/faq.html to describe the new way of connecting to testnet.

**Comment by craigraw** [comment]
Thanks for the nudge - updated the FAQ.
