### ISSUE TITLE
Whirlpool Configuration Error / Freezing

### ISSUE THREAD

**Issue by aarondank** [sparrowwallet/sparrow#521]
I am running the latest version of Sparrow 1.6.3 on Windows 10 Home.
I have Sparrow connected to a private electrum server running on a rasp pi umbrel setup.

I created a BIP39 Software wallet and transferred my BTC there, successfully.
Select 'UTXO' icon > Highlight the single UTXO and select 'Mix Selected (xxxx sats)'
Configure Whirlpool > Premix Priority: Normal > Next
Configure Whirlpool > I am presented with 3 options: 
a) 5million sats  b) 1million sats  c) 100thousand sats

However, no matter which pool size I select, I cannot proceed.
Regardless of pool selection, the 'Premix Outputs' reads: "Calculating..." indefinitely, and I cannot click the "Preview Premix" button to proceed.

Any suggestions?

THANK YOU

**Comment by craigraw** [comment]
This is due to a temporary issue contacting the Whirlpool coordinator. It could be that the Tor network was unreliable at this time, or that the coordinator was briefly unreachable for some other reason. Are you using Tor?

**Comment by aarondank** [comment]
Thank you so much Craigraw.
I am connecting through the onion address generated by umbrel for a private electrum server… so yes, I am connecting through Tor (no problems when I test the connection). This has been an issue for 48 hours so I’ve retested a number of times at this point. I even tried connecting to a public server, but the same issue occurs.

**Comment by craigraw** [comment]
Can you ping pool.whirl.mx?

Secondly, are there any relevant errors in the log file? (Help menu)

**Comment by aarondank** [comment]
Forgive my ignorance, I'm assuming you mean ping pool.whirl.mx from the Rasp Pi / Umbrel node (where the private electrum server is hosted) - that is successful! 

I have no coding experience so (and I'm just new) so I'm not really getting much from reading through this log file. However, I am seeing various errors listed. I have attached the log file for your review. I believe my first whirlpool attempt was 2022-04-14 so you can scroll to that point in the log.

Thank you sincerely.
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/8501855/sparrow.log)

**Comment by aarondank** [comment]
Successfully ping'd pool.whirl.mx from the machine running sparrow, as well as the rasp bi using an ssh client.
Tried disabling all baked in firewall / windows security.
Tried running Tor Browser before opening Sparrow.

No luck yet!

**Comment by craigraw** [comment]
I would try creating a new Sparrow wallet with the same seed. There are some strange database related issues in the current wallet file that I haven’t seen before.

**Comment by aarondank** [comment]
I will give it a go tonight, and report back. Thank you!

**Comment by aarondank** [comment]
Brilliant - that worked!
When I created the first wallet, I created a TAPROOT address...
With the second wallet, I went with Native Segwit.

Not sure if that's what made the difference or not, but figured it's worth noting.
Thank you so much!

**Comment by craigraw** [comment]
Great! Yes only Native Segwit for mixing - I will need to check why the mix button was even present for you. Closing this off.
