### ISSUE TITLE
The address generated by Sparrow is now missing, along with funds

### ISSUE THREAD

**Issue by iamelieus** [sparrowwallet/sparrow#522]
I run Sparrow through Bitcoin Core. 

On April 17, I sent funds from my Coinomi wallet to one of my Sparrow software wallets. On that same day, I did another tx from that same Coinomi wallet to my Sparrow-connected Trezor for cold storage.

Today, April 19, I wanted to withdraw funds from the Sparrow software wallet. When I opened it, the balance with the recent deposit was displayed for a second, but then immediately reverted back to the previous balance after syncing was completed. Fearing the worse, I checked my larger Trezor balance, and I was relieved to see the recent tx was still there.

Blockchain explorers and my own Bitcoin Core node confirm the tx. What's strange is that the Sparrow-generated address is no longer found in the Receive Addresses.

I tried importing the wallet on other clients, but to no avail.

This seems to be similar to issue #125

Thanks in advance for your help.

**Comment by craigraw** [comment]
Can you try to determine the index of the address you used, and check it against the sequential address indexes in Sparrow? Indexes start at zero and count upwards, and are shown in a tooltip when hovering over the address.

I would also consider recreating the Sparrow wallet (reimporting the Trezor) and testing against a public server.

**Comment by iamelieus** [comment]
_> Can you try to determine the index of the address you used, and check it against the sequential address indexes in Sparrow? Indexes start at zero and count upwards, and are shown in a tooltip when hovering over the address._
Thanks for your reply, very much appreaciated. The issue is that the address I used is no longer found in the wallet's Addresses list.

_> I would also consider recreating the Sparrow wallet (reimporting the Trezor) and testing against a public server._
No issues with the Trezor wallet, it's with the wallet I created with Sparrow.
I also recreated the Sparrow wallet on another computer, but to no avail.

**Comment by craigraw** [comment]
> Thanks for your reply, very much appreaciated. The issue is that the address I used is no longer found in the wallet's Addresses list.

What we are trying to determine here is if there is a numerical break in sequential address indexes. Assuming you used the next unused address, you should be able to determine this from the address tooltips.

Are you using a passphrase with this Trezor?

**Comment by iamelieus** [comment]
> What we are trying to determine here is if there is a numerical break in sequential address indexes. Assuming you used the next unused address, you should be able to determine this from the address tooltips.

Got it. I checked and there is no break in the sequence.

Now regarding the Trezor setup: I tried to open the wallet and I got an error. Immediately I suspected a deeper issue, and found the log file. This is not my expertise but there seems to be a lot of error messages. Would seeing the log help?

**Comment by craigraw** [comment]
Yes you can go ahead and attach it here. What error did you get?

**Comment by craigraw** [comment]
From the log file it appears that the wallet file is locked, which can happen if Sparrow is already running in a different process. Try to determine if there are multiple Sparrows open, and close them all before retrying. As a last resort, rebooting the computer can help.

**Comment by iamelieus** [comment]
Thanks for your continued input, very much appreaciated.

I shut everything down and rebooted the computer. Now when I try to open the wallet in question, I get the following error (see screenshot).

Thoughts?

![Screenshot at 2022-04-21 11-23-40](https://user-images.githubusercontent.com/104038872/164494920-744c7a4e-42ab-43f3-b721-43b0963d15ab.png)

**Comment by iamelieus** [comment]
I need to clarify: I have a SOFTWARE wallet, as well as a TREZOR-CONNECTED wallet with Sparrow.

It's the software wallet that has the issue, not the Trezor wallet.

If the software wallet is corrupted, can I use the "recovery tool" that's mentioned in the error message?

**Comment by craigraw** [comment]
Ah, that makes it much clearer.

Re recovery, it will be easiest to recover from the seed words you wrote down when you created the software wallet. 

> When I opened it, the balance with the recent deposit was displayed for a second, but then immediately reverted back to the previous balance after syncing was completed.

Did you add a passphrase? This behaviour you have described happens when you use a different passphrase when opening your wallet. Every passphrase creates a different, valid wallet with different addresses.

**Comment by iamelieus** [comment]
Yes I did have been using the same passphrase since the creation of that wallet (Feb 20).

**Comment by craigraw** [comment]
Incorrect passphrases are almost always responsible for these kind of issues, especially given the behaviour you have described. Consider if there are any other variations of your passphrase you may have entered, and try them out.

**Comment by iamelieus** [comment]
Already tried several variations, but to no avail

**Comment by craigraw** [comment]
Take it slow and keep trying - it is very likely a typo. I'm going to close this issue off as passphrase related. Good luck with the search!
