### ISSUE TITLE
first transaction to sparrow is gone along with receiving address

### ISSUE THREAD

**Issue by nevrwinzz** [sparrowwallet/sparrow#524]
Same issue as others are having I assume, just downloaded the wallet today, the last time I checked it had 2 confirmations, when I checked again awhile ago there was no transaction and the address sparrow generated is gone also, along with my bitcoin.

**Comment by craigraw** [comment]
Please provide some details on your wallet. Are you using a passphrase?

**Comment by nevrwinzz** [comment]
I had just finished setting up the wallet per the instructions on the sparrow website, I did not set up a passphrase.  The receiving address was generated from sparrow, the last time I checked the transaction had 18 confirmations. I set the wallet with single sig. and native segwit.

**Comment by craigraw** [comment]
Ok - and did you close Sparrow after receiving the transaction?

**Comment by nevrwinzz** [comment]
Once I knew the transaction was in progress I closed the wallet and came back later, that’s
When I noticed it was gone.

**Comment by nevrwinzz** [comment]
When I pull up the transaction ID on sparrow it shows the status as unknown.

**Comment by craigraw** [comment]
> When I pull up the transaction ID on sparrow it shows the status as unknown.

Try doing this again when connected to a public server - if you are sure the txid is in the blockchain, it appears that the server you are connected to is not returning good information.

I would also try creating a new wallet from the seed. Fwiw these kind of issues are almost invariably caused by incorrect passphrases. Sparrow will always create the same addresses from the same seed/passphrase.

**Comment by nevrwinzz** [comment]
Do I need to delete the old before I create a new one using the same seed?

**Comment by nevrwinzz** [comment]
Do I need to use the same passphrase or create a new one?

**Comment by craigraw** [comment]
> Do I need to delete the old before I create a new one using the same seed?

No, you can keep the old wallet.

**Comment by craigraw** [comment]
> Do I need to use the same passphrase or create a new one?

Definitely the same as you used originally - this is key to recovering your funds.

**Comment by nevrwinzz** [comment]
Should I add a password to the new wallet or will it make any difference on recovering the funds?

**Comment by craigraw** [comment]
Resolved as passphrase issue.
