### ISSUE TITLE
Feature Request: Delete wallet safely

### ISSUE THREAD

**Issue by decentralizedb** [sparrowwallet/sparrow#527]
Having the possibility of safely deleting the wallet from the device would be a good functionality in Sparrow.
To avoid problems any deletions should be confirmed by password or the passphrase.

**Comment by craigraw** [comment]
I'm interested to understand the use case better here. Is deleting the wallet file manually from the `wallets` folder not simple enough when required? It doesn't seem like this would be a widely needed function, but maybe I'm missing something?

**Comment by RequestPrivacy** [comment]
Manually "deleting" it (i.e. throwing it into the trash where it is "purged" after some time or after another user interaction) just removes the link to the file in the storage system, not the data itself. The wallet COULD be re-discover later. Encrypting your whole drive is a first defense but is vulnerable as your password could be compromised. 

So you could do a safe removal manually through something like `$ sudo shred -vfz <path_to_wallet-file>` or another utility which overrides the underlying wallet data itself with 0 or 1's or a random combination of both. Having such an utility in Sparrow would be a plus imho as it would provide every user with such an "safe" removal of the wallet from the disk.

**Comment by decentralizedb** [comment]
Supporting what @RequestPrivacy wrote, many users (mainly beginners) are not very clear about how they could safely delete the wallet, including file backup as well, and leave that info in the computer storage.

A button (or process) in Sparrow that would allow the user to haven't to exit from Sparrow to do so, and delete the files safely, like the @RequestPrivacy example does, would be a good user experience and good functionality for user privacy, I think.

**Comment by craigraw** [comment]
Added in b5fa8f0, which adds a menu item and a tab context menu item to close and delete an open wallet. 

The wallet file (plus any backups) are overwritten with random data before the files are deleted. How effective this is depends on the hardware it is running on - my research indicates that on SSDs this is not particularly effective, and that disk encryption is the best protection in that case. However, this functionality is certainly better than simply having the file moved to 'trash', as noted above.
