### ISSUE TITLE
Sparrow isn't including or finding 2nd account, derivation  m/44'/0'/1'

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#529]
Deposit  :  m/44'/0'/0'
???  :  m/44'/0'/1'
Account #2 : m/44'/0'/2'
Account #3 : m/44'/0'/3'

<img alt="image" src="https://user-images.githubusercontent.com/388716/165241376-90220fb0-8596-4648-a123-fb1f7952f76f.png">

**Comment by craigraw** [comment]
1. What function are you using to discover accounts? Import BIP39 wallet, or the Add Account > Discover button? 
2. Are there funds in the m/44'/0'/1' account?

**Comment by Transisto** [comment]
1. Did discovery after seed entry, it found the first one only, as expected.
2. Yes there is activity there, (Ledger live)

**Comment by Transisto** [comment]
Just retested and noticed something else.

When Discovering wallet, once it's done it open an additional empty window.

This skipping of the m/44'/0'/1' only seems to happen for 44' legacy derivation.



<img width="391" alt="image" src="https://user-images.githubusercontent.com/388716/165338347-d0495292-5e41-4262-8956-766b4f379591.png">

**Comment by craigraw** [comment]
I was not able to recreate any of the described behaviour - funds in an Account#1 wallet were discovered successfully, and no additional empty windows were opened.

Can you try to reproduce on testnet?

**Comment by craigraw** [comment]
Any update on this? Or can it be closed?

**Comment by craigraw** [comment]
Closing this off.
