### ISSUE TITLE
BitBox02 not detected on Linuxmint 20.3 xfce desktop

### ISSUE THREAD

**Issue by annatuta** [sparrowwallet/sparrow#532]
Hello - i have no experience with sparrow, i use it first time, i try to install a new wallet and then connect with my bitbox02. 
The scan shows, if bitbox02 is on or offline. But when online, there always displays an error message in sparrow - see screenshot 2:
![sparrow_bitbox_nicht_verbunden](https://user-images.githubusercontent.com/104705687/166131545-64e53de5-280f-4f8c-a5e2-4113e8dbf4cf.png)
![sparrow_bitbox_parsing](https://user-images.githubusercontent.com/104705687/166131547-a49bb61e-5196-46a2-a71a-9e40f07f3401.png)
I tried with or without tor-connection, with or without passphrase, starting first bitbox02 or sparrow. Allways the same.
I need it as fast as possible. Thanks for Yor help!

**Comment by annatuta** [comment]
Edit: i also tried it with the backup-sd-card inside because of the hint with json-file. Also the same.

**Comment by craigraw** [comment]
On Linux, you need to install udev rules - see the Tools menu for the command (needs to be run as root).

**Comment by annatuta** [comment]
Thank You, i am an  unexperienced Linux- and github-user: could you help me with a link to the correct commands and give me installation instructions, please?
Thank You very much,
Anna

**Comment by craigraw** [comment]
Sure - the Tools menu in Sparrow provides a dialog with the correct command, which needs to be run from the command prompt (outside of Sparrow, since it needs to run with root permissions). Alternatively, you can do the same manually by following the instructions here: https://github.com/bitcoin-core/HWI/blob/master/hwilib/udev/README.md

**Comment by annatuta** [comment]
Okay, i changed to root-user and got this answer in terminal: ~$ sudo /tmp/hwi-2.0.22897880137458288391.tmp installudevrules
[sudo] Passwort für...:               
{"error": "installudevrules failed: [Errno 6] No such device or address", "code": -13}

The Link to https://shiftcrypto.ch/start_linux is dead. Here should be "the rules", i have to copy?

"Apply these rules by copying them to /etc/udev/rules.d/" :
OK, if you may give me that rules i only have to change directory to there and copy them into it?

"and notifying udevadm." - What do i have to do here?

"Your user will need to be added to the plugdev group, which needs to be created if it does not already exist." -  How can I do this?
![sparrow_udevrules](https://user-images.githubusercontent.com/104705687/166148348-032253d1-913f-4384-b5c0-f641d3848d01.png)

**Comment by craigraw** [comment]
Shift Crypto provide more detailed instructions here: https://shiftcrypto.support/help/en-us/9-troubleshooting/15-usb-connection-issues-my-bitbox02-is-not-detected

If you can't find your Bitbox with `lsusb`, you will need to run the entire command they provide in the gray box as root (so put `sudo` first, or switch to root before running it with `sudo su`).

**Comment by annatuta** [comment]
I forgot that line: https://github.com/keepkey/udev-rules/blob/master/51-usb-keepkey.rules
Is that necessary too adtional to the bitbox-line (the dead link)?

**Comment by annatuta** [comment]
Bitbox02 is listed (because of code input i need to use an extension cable, but its listed) - the 2nd last line: 
~$ lsusb
Bus 002 Device 002: ID 8087:8000 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 13d3:3404 IMC Networks 
Bus 001 Device 002: ID 8087:8008 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 005: ID 174c:3074 ASMedia Technology Inc. ASM1074 SuperSpeed hub
Bus 004 Device 004: ID 0bda:0307 Realtek Semiconductor Corp. Card Reader
Bus 004 Device 003: ID 174c:3074 ASMedia Technology Inc. ASM1074 SuperSpeed hub
Bus 004 Device 002: ID 174c:3074 ASMedia Technology Inc. ASM1074 SuperSpeed hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 005: ID 17ef:6025 Lenovo ThinkPad Travel Mouse
Bus 003 Device 004: ID 174c:2074 ASMedia Technology Inc. ASM1074 High-Speed hub
Bus 003 Device 003: ID 174c:2074 ASMedia Technology Inc. ASM1074 High-Speed hub
Bus 003 Device 002: ID 174c:2074 ASMedia Technology Inc. ASM1074 High-Speed hub
Bus 003 Device 006: ID 03eb:2403 Atmel Corp. BitBox02BTC
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

What would you recommend to do?

**Comment by craigraw** [comment]
Just checking - have you shut down the Bitbox app first, before trying with Sparrow?

**Comment by annatuta** [comment]
No. Both apps where activ, because i need the bitbox-app to start the box itself. Should i shut all and only start sparrow app? 
The box then is offline ....

1. Mai 2022, 16:55 von ***@***.***:

**Comment by annatuta** [comment]
As You wrote, i tried to just close the bitbox-app and the connection in sparrow is here!
See screenshot - just have to connect?
Note: i now startet the wallet without the passphrase (25.word-option). May i use sparrow with as well as without passphrase? I use these as 2 different wallets.
I now start restart the bitbox with the passphrase again, because i saw in the tutorial there will be a master fingerprint that may have relation to passphrase, okay?
Thanks! Anna

**Comment by annatuta** [comment]
![bitbox_online_welche_keys_importieren](https://user-images.githubusercontent.com/104705687/166152877-eb0069dd-c2bf-460a-a970-f3b212e0da3a.png)

**Comment by craigraw** [comment]
> Note: i now startet the wallet without the passphrase (25.word-option). May i use sparrow with as well as without passphrase? I use these as 2 different wallets.

Yes, you can do both. Create two different wallets in Sparrow for each.

Glad it's working - closing this off.

**Comment by annatuta** [comment]
Thank You especially for your patience!
So i may start with it as it is 24-words-wallet und differ with 2 names for 2 wallets, is that correct?
Anna

**Comment by craigraw** [comment]
Yes, correct.

**Comment by annatuta** [comment]
PS: may i change the label "Bitbox 02" in the 1. now installed wallet before i make a quit and newstart inclusive passphares / 25.word ?

**Comment by craigraw** [comment]
Yes, you can change the keystore label to anything you like.
