### ISSUE TITLE
Unable to connect ledger nano s+ as hardware wallet

### ISSUE THREAD

**Issue by Leibniz137** [sparrowwallet/sparrow#533]
This is a newer model ledger. I have an older ledger nano s and it works fine connecting to sparrow.

But when I try to scan the ledger nano s+ (with the bitcoin app running), I get this:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/2193797/166133296-1967e8c5-cb92-497f-9189-b69669d13f2b.png">

This issue https://github.com/sparrowwallet/sparrow/issues/386 suggested installing udev rules, but I don't see this in the dropdown (using a mac)

<img width="235" alt="image" src="https://user-images.githubusercontent.com/2193797/166133335-168607b8-7743-4194-970c-ba1e2c99c7ee.png">

Not sure what the issue is, derivation path?

**Comment by craigraw** [comment]
Shutdown the Ledger app if it is running. You don't need udev rules on a Mac.

**Comment by Leibniz137** [comment]
thanks for the reply!

I tried it again after making sure ledger live was closed, but unfortunately I got the same error.


To get some more info, I was trying to increase the log level in hopes of seeing some more info in `~/.sparrow/sparrow.log`

I didn't see any log level config settings in `~/.sparrow/config`, but I did see this file:
```
/Applications/Sparrow.app/Contents/runtime/Contents/Home/conf/logging.properties
```

I tried setting `.level= DEBUG` and `java.util.logging.ConsoleHandler.level = DEBUG` but that didn't seem to change the log level.

**Comment by craigraw** [comment]
Debug logging can be enabled with a command line flag (see the FAQ for details). However:

Sparrow is calling HWI internally, which you can do directly from the command line. For example:
```
~/.sparrow/hwi/hwi-2.0.2/hwi enumerate
```

If HWI can't find the Ledger (displays `[]`), it might be worth taking a look at what devices your Mac can see: https://stackoverflow.com/questions/17058134/is-there-an-equivalent-of-lsusb-for-os-x

**Comment by craigraw** [comment]
Update: It appears that HWI does not support the Ledger Nano S+ yet: https://github.com/bitcoin-core/HWI/issues/595

**Comment by Leibniz137** [comment]
I think I have a fix for the hwi thing: https://github.com/bitcoin-core/HWI/pull/604 

is there a way to test sparrow with a custom version of hwi?

**Comment by craigraw** [comment]
Yes, just close Sparrow and edit the `config` file in Sparrow home (see FAQ) and edit the path in the `"hwi"` entry to point to your custom build.

**Comment by craigraw** [comment]
Sparrow v1.6.5 has been released with Ledger Nano S Plus support.
