### ISSUE TITLE
first transfer from atm to sparrow hot-wallet did not work

### ISSUE THREAD

**Issue by annatuta** [sparrowwallet/sparrow#536]
Hello - you helped me to install my sparrow app on linuxmint 20.3 xfce desktop. 
Thanks again!
Yesterday i tried out my first transfer from bankomat (a kurant maschine, a small one). The amount was adressed to my first generated adress per QR code. Never came in. No transaction is showed. Sparrow seems online ... see screenshot.
How may i proof that sparrow is really online?
Anna
![sparrow_online](https://user-images.githubusercontent.com/104705687/166445186-a21fd157-2262-4090-b203-83122d736ef2.png)

**Comment by craigraw** [comment]
Try searching for the address you entered for the transaction in a block explorer, like [mempool.space](https://mempool.space/) - see search at the top. Try to see if your transaction appears. Then you will know if Sparrow should be showing anything.

PS could we rather use the Telegram group t.me/SparrowWallet for user support queries - this interface is for reporting bugs and feature requests. Thanks

**Comment by annatuta** [comment]
Oh, sorry, yes!
I am a beginner here .... thanks for your friendly help.

Anna


3. Mai 2022, 13:56 von ***@***.***:
