### ISSUE TITLE
Both Windows and Linux binaries available for download don't match those from source (1.6.3)

### ISSUE THREAD

**Issue by hugoender** [sparrowwallet/sparrow#537]
Built the binaries for 1.6.3 on both Windows and Linux and both times the resulting binaries did not match the binaries available for download on the Sparrow website. The binaries were compared using hash/checksum as well as `diff -r`. The latter identified the  `runtime/lib/modules` files as differing and when I checked, they are indeed different. Downloaded one is 84,268KB while the built one is 84,270KB.

@craigraw mentioned that there is a "bug [that] seems to be triggered only rarely" that causes built binaries to not match downloadable binaries. The fact that it happened two out of two times that I tried building this on two different machines (Windows and Linux) makes me wonder if this maybe isn't that rare. 

Regardless, it's concerning that the downloadable binaries differ from those built from source and I definitely think it's something that should be addressed. The Sparrow Github page states "Reproducibility is a goal of the Sparrow Wallet project." and I believe that to be a very noble goal. I'd be more than happy to help root cause this as my setups seem to trigger this "bug" consistently. 

I'm submitting this issue here so it's recorded in case anyone else experiences something similar. All I will say is that the mantra "Don't trust. Verify." exists for a reason and at this point, at least on my setups, there's no way to verify the binaries that are available for download on the Sparrow website.

**Comment by hugoender** [comment]
This issue has been bugging me all day so I decided to delete everything and start from scratch again. I downloaded the .zip file on the Sparrow Downloads page, extracted the contents and moved the Sparrow folder into a folder named "Downloaded". I then built the binaries from source again and moved the Sparrow folder located inside the jpackage folder into a folder named "Built". 

To compare them I fired up my Ubuntu WSL and did a `diff -r Downloaded/Sparrrow Built/Sparrow` and this time they came back the same! Not sure what changed. Maybe this is what @craigraw was referring to when he said it's a "bug that seems to be triggered only rarely". 

I'm very happy to see the two binaries match. I will close this now and hopefully this will serve as reference for others that may run into a similar issue.

**Comment by RequestPrivacy** [comment]
It would be cool if you could document your built-process on [bitcoinbinary](bitcoinbinary.org) as this helps people to gain a basic level of trust (e.g. their own process produces these random non-deterministic builds or they aren't so technical inclined).
