### ISSUE TITLE
invalid password error

### ISSUE THREAD

**Issue by 4NobleTruths** [sparrowwallet/sparrow#538]
v1.6.3 on Debian 10
Was working ok for a couple weeks, but with usual JVM nonsense, where it bleeds RAM until the app hangs or crashes the machine.

This time when sparrow hanged like that, and had to be killed, on restart it doesn't recognize the wallet password anymore. 

Does it have to be restored from seed?

**Comment by 4NobleTruths** [comment]
Restored from seed, which worked, but had to increase JVM ram allotment to 6GB to get mixed UTXOs to appear.

Of course, lost all the labels that were in the original wallet.

**Comment by 4NobleTruths** [comment]
Now I see also that Badbank txs did not recover, and have error:

> [May 08 22:19:50] Failed to subscribe to paths: [../0/0-../0/19]

**Comment by craigraw** [comment]
> Was working ok for a couple weeks, but with usual JVM nonsense, where it bleeds RAM until the app hangs or crashes the machine.

It's not clear what you mean here - that Sparrow has a memory leak? Or the JVM itself? If so please open an issue with evidence of this - I have done long running memory monitoring tests on all 3 platforms to test this, and have found no evidence of it.

> This time when sparrow hanged like that, and had to be killed, on restart it doesn't recognize the wallet password anymore.

What error did you get? Was the wallet file corrupted?

> Restored from seed, which worked, but had to increase JVM ram allotment to 6GB to get mixed UTXOs to appear.

Are you running from source? Or are you introducing RAM limiting another way?

> Now I see also that Badbank txs did not recover, and have error:

This means that the server you are connected to is failing, not Sparrow itself. If you are using Electrs, it may need a restart, or better upgrade to Fulcrum.

**Comment by 4NobleTruths** [comment]
Thanks for response! 
I think it's the JVM, where it consumes more and more resources until the app stops responding. This one is running in a Qubes VM by itself with 4 cores and 6GB available to it maximum. I'll try to get the exact numbers from top next time it happens.

The error was "invalid password", for password I get straight from file manager. I think the wallet file corrupted when it had to be killed, because it wasn't responding.

I'll try to reboot electrs. Fulcrum is not available for my node yet I think.

**Comment by 4NobleTruths** [comment]
To get Badbank again was enough to just disconnect sparrow a few times with the button in lower right.
