### ISSUE TITLE
[Docs] Whirlpool "Preparing the wallet" should specify P2WPKH wallet required

### ISSUE THREAD

**Issue by kobiebotha** [sparrowwallet/sparrow#543]
**Issue:**
Whirlpool with P2TR wallets is not supported. Currently on [this page](https://sparrowwallet.com/docs/mixing-whirlpool.html), it is specified that `The wallet needs to be a standard derivation on the default account #0`. However an additional prerequisite is that the wallet needs to be native Segwit and that taproot wallets are not supported. [Ref](https://t.me/sparrowwallet/21424).

**Suggested change:** 
update this:
`The wallet needs to be a standard derivation on the default account #0 - for example, m/84'/0'/0' for Native Segwit. Electrum generated seeds are not supported.`

to this:

`The wallet needs to be native Segwit (P2WPKH) and have a standard derivation on the default account #0 - i.e. m/84'/0'/0'. Electrum generated seeds are not supported.`

**Comment by craigraw** [comment]
> However an additional prerequisite is that the wallet needs to be native Segwit and that taproot wallets are not supported.

Apologies, I misremembered this. It's correct that Taproot wallets aren't supported, but other script types (Legacy and Nested Segwit) are. I'll chat to the Samourai team about adding Taproot support to the Whirlpool client.

The documentation has been updated with a note on Taproot support.
