### ISSUE TITLE
[UI] Enhance "View transaction" graph for whirlpool (re)mixes

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#545]
# Description

## Steps to Reproduce
- Participate as a freerider in a whirlpool remix 
- Go to the transaction view of said remix (e.g. by right-clicking on an output in the UTXO tab -> View Transaction

## Graph Enhancement 

For 1. and 2. see picture below

1. Equal output symbols for every output besides the fee (from the current left pointing arrows for own output to the paper plane thing). Benefit: it makes it clearer that your output is nothing special or standing out from the others. It is equal.
2.  Colored connecting line for the own input and output. Benefit: quick overview over the "flow" of the transaction even for equal symbols introduced in point no.1.
3. (Not depicted) Change label while hovering over own output from `Consolidate x amount to \<path>` to something like `Remixing x amount to \<path>`. Benefit: clearer picture of what is happening since it isn't really a consolidation imho? One of your inputs goes in and the same amount goes out. Maybe a consolidation in the scope of the whole transaction but for the user not really?!

![Sparrow_1_1](https://user-images.githubusercontent.com/72392544/168113189-449bb1cf-a8d5-40db-904b-f9c930103cfc.png)

Some of the thoughts could also be implemented for first time mixes, not just remixes.

**Comment by craigraw** [comment]
I've given this a lot of thought, but I'm not convinced. There would need to be a significant advantage to ask the user to adopt a new mental model for a 'similar but not quite the same' behaviour in the transaction diagram.

For example, the goals of point 1 & 2 seem to contradict each other. Further, as you have noted I think it is useful to quickly determine your own output amongst the 5, and the icons represent a consistent way to do this across all transaction diagrams. The similarity of the outputs is really just their size, which is indicated by the size of the dot at the end of the line.

The use of the word 'Consolidation' for all intra-wallet outputs is similarly consistent, even if arguably you are not 'consolidating' one input to one output. 

There is another point - keeping the diagram consistent as indicates that this is a normal Bitcoin transaction (just one with high entropy), which is a view worth promoting imo.

**Comment by RequestPrivacy** [comment]
Thanks for considering.

> For example, the goals of point 1 & 2 seem to contradict each other.

Not quite in my opinion. Point 2 characterizes the "flow" of your utxo in the transaction, point 1 addresses more the end state of said utxo. Even if point 1 isn't realized and the output symbol remains with the left arrow, I recall you have to hover over all inputs to see which one is yours. Point 2 would help to identify your input quicker. 

But I understand and appreciate your intention to leave things consistent over the wallet. I was just taken by a bit of a surprise as I studied a whirlpool transaction graph more closely and saw "Consolidation" and only 4 "send" utxo as I expected 5 of them.

**Comment by craigraw** [comment]
> I recall you have to hover over all inputs to see which one is yours

Actually, you can just use the icon to determine - outputs that are received by an open wallet will be indicated by either a down arrow (receive chain) or coins (change chain).

I'll close this off, but I appreciate the thoughts and suggestions!
