### ISSUE TITLE
Whirlpool new wallet configuration dialog incorrect

### ISSUE THREAD

**Issue by Sparrowhawk1337** [sparrowwallet/sparrow#546]
Sparrow Wallet v1.6.3

The whirlpool tabs (Deposit, Premix, Postmix, Badbank) have been moved to the left of the window but the documentation shown on creating a new whirlpool wallet is not yet updated.

It looks like this applies to the text and the arrow on the bottom of the tabs graphic.

![sparrow](https://user-images.githubusercontent.com/101246652/168459443-a14c9cd8-538c-43cb-8066-ae4f3e401500.png)

**Comment by craigraw** [comment]
Thanks, text fixed in 66be5c4. The tab overflow arrow direction is determined by the UI toolkit.
