### ISSUE TITLE
[UI] Menu is drawn below menubar on portrait monitor display

### ISSUE THREAD

**Issue by acarlton** [sparrowwallet/sparrow#547]
I'm running Sparrow on Ubuntu. I have two external monitors - one landscape and one swiveled to a portrait orientation. When I moved the Sparrow application to full-screen on the portrait display, and click on the menu, the menu items are drawn far below the top menubar. I tried to grab a screenshot, but the menu disappeared on keypress.

**Comment by craigraw** [comment]
Probably related to #170 - does it look familiar?

**Comment by acarlton** [comment]
Yes, it does look familiar. Setting `GDK_DISPLAY=1` and running Sparrow from the command line did not fix it for me though. I'm running Ubuntu 21.10 native. Also, I was running Java 8, but also tried upgrading to 11 and now running 16 -- didn't help.

It's reasonably safe to assume the issue is related to the other ticket and should be handled there. Thanks for a great wallet!
