### ISSUE TITLE
Copy-Txid-Button: contents don't adjust

### ISSUE THREAD

**Issue by pvig0q1s** [sparrowwallet/sparrow#548]
Sparrow 1.6.3

After filling the form on Send-Tab and consequently clicking "Create Transaction >>" the Txid is presented on the next page. 

The Txid can be copied by clicking the "Copy-Txid-Button".

![btn](https://user-images.githubusercontent.com/77514744/168894145-7c4cce29-55cf-4c34-a4bd-629d7b23d56e.jpg)

When the User adjust the transaction on the Details-Tab (Version-Number and/or Locktime parameters) the displayed Txid adjusts, but contents of "Copy-Txid-Button" don't. The initial Txid is copied to clipboard.

It does not make a difference if we click "Finalize Transaction for Signing" or not. Also, say we have a finalized (and signed) Tx, load it into Sparrow and then changing parameters (e.g. adjusting Locktime) the same behaviour applies.

The expected behaviour should be that copied contents align with the info displayed in the UI.

##### Great progress on the Wallet, craig! Well done & thanks!

**Comment by craigraw** [comment]
Thanks for the bug report, and the kind words :)

Fixed in 555e5ec.
