### ISSUE TITLE
Create Transaction fail-safe

### ISSUE THREAD

**Issue by pvig0q1s** [sparrowwallet/sparrow#550]
On Send-Tab, the User can either specify a feerate by using the Range-slider or by manually entering a fee into the associated text box.

Using the slider, the range is capped to the smallest point on the spectrum (1 sat/vB); one cannot drag further. 

Using the text box, entering a fee, there is also a protection to not fall below 1 sats/vB feerate (text box gets a red border and "Create Transaction >>" is greyed out):

![protect](https://user-images.githubusercontent.com/77514744/168912244-8a3fe237-8d87-4a61-b4b7-39211cf4f3f6.jpg)

Connecting to the pre-configured aranguren server (fulcrum testnet), it is possible to go below a rate of 1sat/vB and "Create Transaction" -> Finalize/Sign -> Broadcast.

![pub](https://user-images.githubusercontent.com/77514744/168912285-5240a60c-77e4-4431-be2e-9c27eafc3dbf.jpg)

Sparrow 1.6.3
Fee Rates Source: Minimum 1sat/vB "Server"

Of course, this Tx does not propagate but besides switching servers (or using the 'Refresh Wallet' option) at a later stage, the transaction is showing up in Transaction-Tab :grinning:

![sat](https://user-images.githubusercontent.com/77514744/168912982-c7499b96-e4ba-4848-a816-8b7be9987d1c.jpg)

IMO there should be a autonomous protection to not go below the minimum rate. Beginners might also see a recommended feerate on, e.g. mempool.space, enter those values in the text box under the impressionen that it is the absolute fee.

**Comment by craigraw** [comment]
Thanks, it turns out the aranguren server was returning a min relay fee rate of 0 sats/vb. The minimum permissible value has been set to 1 sat/vb as of 4b2b8f6.
