### ISSUE TITLE
Date field no longer sorting

### ISSUE THREAD

**Issue by brendanphall** [sparrowwallet/sparrow#556]
In UTXOs tab, 'Date' column is no longer sorting when the column header is clicked. This was functional with the last version. This is especially helpful to monitor activity of multiple UTXOs as they are mixed.

**Comment by craigraw** [comment]
Thanks for the bug report - it was picked up immediately after the v1.6.4 release and fixed in https://github.com/sparrowwallet/sparrow/commit/f4259642b88bfcfbcb423fc09ab3e339a8ad8074.
