### ISSUE TITLE
Ledger Nano S - Could not sign TX & display sending/receiving address

### ISSUE THREAD

**Issue by captJiri** [sparrowwallet/sparrow#560]
Hi,

Ledger Nano S Firmware 2.1.0
Bitcoin Version on it: 2.0.4
Error message, when trying to display the Receiving address:

('0x6a80', 'Error in <BitcoinInsTzpe.GET_WALLET_ADRESS: 3> COMMAND', ")
Could not find anything in Log file.

Thanks for reply.
Jiri

**Comment by captJiri** [comment]
The same problem with Signing the Sending address:

('0x6a80', 'Error in <BitcoinInsType.SIGN_PSBT: 4> command', ")

**Comment by craigraw** [comment]
Thanks, duplicate of #553.
