### ISSUE TITLE
my wallet mixes a coin with another of the same wallet (testnet)

### ISSUE THREAD

**Issue by antonilol** [sparrowwallet/sparrow#562]
on the testnet there are not many users so the chance of this happening here is higher

my wallet just mixed a coin that has been mixed once with one that hasnt been mixed

https://sparrowwallet.com/docs/mixing-whirlpool.html#why-whirlpool guarantees 'Never mixing with yourself'

my postmix contains 2 outs with the same txid:
![image](https://user-images.githubusercontent.com/49868160/169668005-7be0c56b-ee5d-4441-99d7-8f200b803fe4.png)

premix tx: https://mempool.space/testnet/tx/5aa921585a6745f925f5b581e65aa6f64f257deedc3a17bf8429c9818623d840
first mix tx: https://mempool.space/testnet/tx/43be95c4dba41f05dd94bf20ff51bc86e5a0754b5aecbeb04bba344a986ef0cb
second mix tx (contains input from premix): https://mempool.space/testnet/tx/ea16144aafb7e2271471efcadd0f242c06ac2fb79df17e380f312180cf92fa02

**Comment by craigraw** [comment]
Yes, I’ve seen this behavior too. It occurs because the Whirlpool rules are relaxed on testnet to make it easier to trigger a mix. This should never happen on mainnet.

**Comment by antonilol** [comment]
:+1:
