### ISSUE TITLE
Delete Wallet freezes Sparrow for >60 seconds on Linux

### ISSUE THREAD

**Issue by pjw65** [sparrowwallet/sparrow#565]
Sparrow 1.6.4 
Ubuntu 20.04

I tried to delete a read-only wallet with transactions

1. opened sparrow, waited till everything is synced
2. choose tab with read-only wallet I want to delete
3. File / Delete Wallet   and confirmed the dialog
The tab was closed
Sparrow was frozen
After a while I killed sparrow and restarted.
Nothing was deleted, I could just reopen the read-only wallet with File/Open

**Comment by craigraw** [comment]
I can't reproduce this on Sparrow v1.6.4 and Ubuntu 20.04. 

1. Did you mean a watch-only wallet? 
2. Is there anything unusual about the storage on this machine? 
3. Is this reproducible?
4. Can you check the Sparrow log file (See Help menu) to see if any relevant error was recorded there?

**Comment by pjw65** [comment]
1. yes, watch-only wallet.
2. no
3. I removed the walled by hand, and die a new watch-only wallet with an xpub
4. nothing recorded in log before freezing sparrow

I tried to delete another wallet (multisig), which freezes Sparrow for about 60 seconds. (no mixer running)
Then with a new watch-only wallet just createt it took more than 200 seconds (mixer running on other wallet)

**Comment by craigraw** [comment]
> Why does it take so long anyway?

I suspect this was caused by a slow random number generator that is particular to your system. Before it deletes the file, Sparrow overwrites it with random data.

I've greatly reduced the overwrite data entropy in 0f2cf9c to reduce the possibility of this happening.
