### ISSUE TITLE
Cannot connect to Tor

### ISSUE THREAD

**Issue by BTC1M** [sparrowwallet/sparrow#568]
Hi folks,

I didn't have any problem to connect Sparrow with my electrum server w/ tor, until today.
This afternoon i restarted the tor browser, and an auto-update started. Since then, i haven't been able to connect. The tor browser is working fine though. Here are the following error message i get when testing the connection :

- Without "Use proxy" activated :
`Cannot connect to hidden service`

- With "Use proxy" activated, with 127.0.0.1 and port 9050 :
`Error reply: Unable to set option: Failed to bind one of the listener ports. Is a Tor proxy already running on port 9050? Assuming Tor proxy is running on port 9050 and trying again...`
`SOCKS: Host unreachable. Check if the proxy server is running.`

- With "Use proxy" activated, with 127.0.0.1 and port 9150 :
`An established connection was aborted by software on your host computer`

Sparrow version : 1.6.3
Operating system : Windows 10

**Comment by craigraw** [comment]
Tried a reboot? Often helps on Windows. 

Otherwise, this app might help you find what's running on local port 9050: https://docs.microsoft.com/en-gb/sysinternals/downloads/tcpview

**Comment by BTC1M** [comment]
_> Tried a reboot? Often helps on Windows._
Yes i already tried to reboot my computer and my node

_> Otherwise, this app might help you find what's running on local port 9050: 
    https://docs.microsoft.com/en-gb/sysinternals/downloads/tcpview_
I just tried that, there is nothing running on local port 9050

**Comment by BTC1M** [comment]
_> Firewall issue? Anti-virus?_
Everything was working fine earlier this day, i didn't change anything to my firewall or anti-virus so i don't think so

_> Try using localhost instead of 127.0.0.1_
Same error

While testing connection a bunch of times, strangely it succeeded (without "Use proxy").
But when i activate "Use proxy", i get a new error now :
`SOCKS: TTL expired. Check if the proxy server is running.`

_> If you have a Unix-like shell install (for example Git Bash) try see if you can execute the cURL command in https://github.com/sparrowwallet/sparrow/issues/557._
I'm going to try that, i will edit this post when it's done

**Comment by craigraw** [comment]
Strange. Windows does odd things. I'm going to close this off for now, reopen if it happens again.
