### ISSUE TITLE
View -> Lock All Wallets isn't always greyed out when all wallets locked.

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#570]
A fix for issue #506 where the 'Lock All Wallets' menu option was never greyed out was made and the fix looks like it made it into 1.6.4. I've gone on to test this in 1.6.4 and Sparrow now seems to grey out the menu option only some of the time.

If I go to each wallet individually and select 'View -> Lock Wallet' then on locking the last wallet the option to 'Lock All Wallets' does indeed get greyed out.

However, having one or more wallets unlocked, if I select the 'Lock All Wallets' option then all wallets do indeed get locked. But the 'Lock All Wallets' menu item isn't always set to greyed out. I've had a play with this and one way I've found to consistently reproduce this error is:

- Have two wallets open and both unlocked
- Select the first wallet tab and click 'Lock Wallet'
- Select the second wallet tab and click 'Lock Wallet'
- Keeping the second wallet tab selected and click 'Unlock'
- Select the first wallet tab
- Click 'View -> Lock All Wallets'
- See that all wallets are locked but the 'Lock All Wallets' option is not greyed out

A second way which appears repeatable:

- Have two wallets open and both unlocked
- Select 'View - Lock All Wallets'
- Select the second wallet tab and click 'Unlock'
- Select the first wallet tab
- Click 'View -> Lock All Wallets'
- See that all wallets are locked but the 'Lock All Wallets' option is not greyed out

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 33a61e3.
