### ISSUE TITLE
Shadowy icon on UTXOs tab in dark mode

### ISSUE THREAD

**Issue by hur4hur5** [sparrowwallet/sparrow#573]
On the UXTOs tab of a wallet the output column has a 'view transaction output' icon (magnifying glass) and 'send' icon (paper plane). When using the light theme these icons are not visible at all until the mouse hovers a row in the output column at which point the icons appear.

Light Theme:
![Light Theme](https://user-images.githubusercontent.com/102880838/170359864-0802a716-02e6-4a87-a9d1-1f87cc93e0a9.png)

However when using the dark theme these icons, when not hovered over, have a 'shadow' visible.

Dark Theme:
![Dark Theme](https://user-images.githubusercontent.com/102880838/170359868-5ada0829-3def-424e-910d-663c293e80b8.png)

![Dark Theme Large](https://user-images.githubusercontent.com/102880838/170359873-71e96a51-149c-4bc6-84f3-744a08910624.png)

I am suggesting that this shadow should not appear at all, as with the light theme.

**Comment by craigraw** [comment]
I can't reproduce this - can you confirm the platform it is occurring on? It appears to be Linux - I've tested on Ubuntu 20.04.

**Comment by RequestPrivacy** [comment]
I experience the same issue. Running Sparrow 1.6.3 in a VM and Kubuntu 22.04.

**Comment by craigraw** [comment]
I've made a change in adc9905 that should (I hope) resolve this. Will need feedback to know for sure.

**Comment by RequestPrivacy** [comment]
That fixed it for me, thanks!

**Comment by craigraw** [comment]
Thanks, released this in v1.6.5 for further testing.

**Comment by hur4hur5** [comment]
I will test on 1.6.5 (if I can't manage beforehand). Worth mentioning that I've also noticed this 'shadow' on the magnifying glass icon on the Date column of the Transactions tab and the down arrow icon on the Address/Outpoints column of the Addresses tab. I assume your fix will cover these too but worth checking. Maybe @RequestPrivacy can confirm?

**Comment by RequestPrivacy** [comment]
There are no shadows anymore for me. In every table and column. So should be fixed for you as well.

**Comment by hur4hur5** [comment]
Checked this fix in 1.6.5. No shadows on any of the icons now in dark mode. Light mode also still fine as it was before.
