### ISSUE TITLE
Add Tor support for public nodes for better whirlpool privacy

### ISSUE THREAD

**Issue by Al2922** [sparrowwallet/sparrow#576]
Hey guys,

my request would be to add a tor button as a optional feature to improve privacy when connection to public nodes. 

I think broadcasting a static IP is an attack vector for onchain analysis companies to undo a coinjoin. If i broadcast tx0 with IP 98 and then do the whirlpool coinjoin and then broadcast a postmix tx again with IP 98 the pre and postmix TX can be connected. If a public node just collects the ip adresses of the broadcasts a onchain analysis company can undo coinjoins. 

"Just run your own node" is right now the only solution but if sparrow wallet wants to improve the privacy front while having the best UX adding a tor button would fix this alot. Samourai and Wasabi Wallet have it integrated in combination with coinjoins and i guess its because you dont want to broadcast your transcations with the same ip adresses everytime.

**Comment by craigraw** [comment]
> If i broadcast tx0 with IP 98 and then do the whirlpool coinjoin and then broadcast a postmix tx again with IP 98 the pre and postmix TX can be connected.

All Whirlpool transactions are broadcast from the Whirlpool server, not from Sparrow directly.

> my request would be to add a tor button as a optional feature to improve privacy when connection to public nodes.
> "Just run your own node" is right now the only solution

It's not true that running your own node is the only solution - it is easy enough to run Tor Browser, enable the proxy and set it to `localhost` and `9150`. See as follows - I am here connecting to the `emzy.de` public server over Tor:

<img width="862" alt="Screenshot 2022-05-30 at 12 57 29" src="https://user-images.githubusercontent.com/862166/170978517-1e016e8c-9d21-4185-a9f7-881cdee24760.png">

**Comment by craigraw** [comment]
Closing this off as solved.
