### ISSUE TITLE
Can't sign a taproot transaction

### ISSUE THREAD

**Issue by nbourbon** [sparrowwallet/sparrow#578]
Hi, I tried sending a taproot transaction (I believe since 2 versions ago you have finally updated it but I didn't try till today).

I'm getting the following error at the time of signing.
('0x6a82', 'Error in <BitcoinInsType.Sign_PSBT:4> command', ")

It does show the preview on my ledger without any problem... but after I sign then this is the error that is prompted to me 
Nico

<img width="487" alt="Screen Shot 2022-05-29 at 17 44 11" src="https://user-images.githubusercontent.com/6254963/170890770-38e87c3d-3f0b-4e41-9b5a-dbbeb128a098.png">

**Comment by craigraw** [comment]
Indeed, Ledger does not yet support the SIGHASH_DEFAULT hashtype defined by Taproot BIP341. It is planned for the next firmware release. See https://github.com/LedgerHQ/app-bitcoin-new/issues/47

**Comment by nbourbon** [comment]
oh ok, I didn't know there was a sighash_default. is there any reference material to understand why using that one instead of sighash_all ?

**Comment by craigraw** [comment]
You can read https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#signature-validation-rules

The ability to set SIGHASH_ALL for Taproot inputs has now been added in 62e7c34.

**Comment by craigraw** [comment]
Closing this off - nothing further can be done on the Sparrow side.
