### ISSUE TITLE
1.6.4 downloaded yet doesn't detect Jade wallet

### ISSUE THREAD

**Issue by artflr** [sparrowwallet/sparrow#581]
Looking to set up multi vendor multisig unable to link jade

**Comment by craigraw** [comment]
Have you tried these instructions?

https://help.blockstream.com/hc/en-us/articles/900005443223-Why-is-Blockstream-Jade-not-recognized-by-my-computer-

**Comment by craigraw** [comment]
Unfortunately I can't "get it going for you" - you need to install the drivers (if on Windows) or run the commands (if on Linux). You might want to try if Blockstream Green wallet can see it.

**Comment by craigraw** [comment]
Closing this off as a Jade driver issue.

**Comment by artflr** [comment]
Blockstream green does not see it for the reasons that you explained. I am in the dark ages as far as Tech goes. That’s what happens to your brain when you get over the age of 65, LOL. So as much as I want to be a sovereign I do need the help of others. Again, thanks for your help.
