### ISSUE TITLE
Used Xpub for Blockonomics and no sats in my wallet

### ISSUE THREAD

**Issue by Jboss1977** [sparrowwallet/sparrow#582]
Used my Xpub address for blockonomics and no sats are in my wallet. I do have all wallet addresses used for the transactions on blockonomics side but nothing is reflecting in my sparrow wallet.

Please advise possible solutions.

Jason

**Comment by Jboss1977** [comment]
I can see the wallet balance on mempool as I did a normal deposit and i can see the transaction in sparrow from my deposit today and the balance for the xpub transactions are there but not reflecting in my wallet

**Comment by craigraw** [comment]
It would depend on how the blockonomics wallet is using the xpub - I think this is more a question for them. From the Sparrow side, check the wallet is loading without errors, and consider increasing the gap limit (Settings > Advanced).
