### ISSUE TITLE
Use of external block explorer?

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#584]
Given a small privacy warning notification I think it would be beneficial to let user click to open on their block explorer of choice.

I run my own mempool.space instance and I would sometime like to cross check the information with another party.

**Comment by craigraw** [comment]
I'm not too keen on this for the privacy reasons you mention. The idea behind building a comprehensive transaction viewer is to avoid the need to use a browser - providing links out defeat this purpose to a certain extent, as well as add additional UI elements. Sparrow provides many copy functions for txids and addresses throughout the app which can be easily entered into a block explorer's search if need be.
