### ISSUE TITLE
Drop invalid unconfirmed transactions

### ISSUE THREAD

**Issue by eliasnaur** [sparrowwallet/sparrow#589]
After double-spending a transaction manually, the replaced (and invalidated) transaction is now stuck in the "unconfirmed" state on the Sparrow transaction overview. I see no way to remove the invalid transaction, but either way, this issue is about Sparrow automatically removing unconfirmed invalid transactions.

I'm not sure what information to provide, other than I'm running the latest version (1.6.5).

**Comment by craigraw** [comment]
This is due to a server issue, which did not report the transaction to Sparrow as replaced. Likely, refreshing the wallet will sort it out.

**Comment by eliasnaur** [comment]
This was indeed the issue, and a refresh (View->Refresh Wallet) flushed out the invalid transaction. Thank you!
