### ISSUE TITLE
[Bug] QRCode for PSBT don't animate on a specific scenario - null pointer exception

### ISSUE THREAD

**Issue by tadeubas** [sparrowwallet/sparrow#592]
Using Sparrow to create a PSBT and them showing QRCode for sign, clicked on "Use Legacy Encoding (Cobo Vault)" 2 times, opened another PSBT, maybe checked the QR again, don't remember, then clicked on menu "File > Show PSBT as QR..." then I noticed the QR code was not animated anymore.

sparrow.log:
```
2022-06-10 16:21:17,901 ERROR [JavaFX Application Thread] c.s.s.MainApp [null:-1] Exception in thread "JavaFX Application Thread"
java.lang.NullPointerException: Cannot invoke "com.sparrowwallet.sparrow.control.QRDisplayDialog$AnimateQRService.isRunning()" because "this.animateQRService" is null
```

Sparrow `1.6.5`

**Comment by craigraw** [comment]
I wasn't able to recreate this, but I've added code to check for an NPE in the indicated areas. 94c5920c.
