### ISSUE TITLE
SSL handshake failed seems to happen too often.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#599]
<img alt="image" src="https://user-images.githubusercontent.com/388716/173403042-72eeb028-22d0-45ab-9ad7-67119faa1df7.png">

I've gotten this about 30 times in the last 6 months, seems to always be blockstream, but I'm always using blockstream as my primary server.

How often is blockstream SSL cert changing and could this error be cause by something else?

**Comment by bassim** [comment]
@Transisto are you using a VPN by any chance? That is what causes the popup to show up for me I think

**Comment by Transisto** [comment]
> @Transisto are you using a VPN by any chance? That is what causes the popup to show up for me I think

No I wasn't, on the plus side it seems to not happen anymore, also haven't used Sparrow much though.
