### ISSUE TITLE
Importing existing Electrum wallet doesn't apply any existing labels

### ISSUE THREAD

**Issue by lucasmoten** [sparrowwallet/sparrow#6]
The label field for transactions does not get set from a wallet imported from an existing Electrum wallet.

This would be a nice-to-have type enhancement for anyone planning to transition from Electrum to Sparrow.

**Comment by craigraw** [comment]
This is a good idea, and should be relatively simple I hope. I will look at implementing it.

**Comment by craigraw** [comment]
Implemented in https://github.com/sparrowwallet/sparrow/commit/b9db4421dfb8ae91852a652969d0070ae6a697f7
