### ISSUE TITLE
label values with BIP39

### ISSUE THREAD

**Issue by sparcsun** [sparrowwallet/sparrow#600]
Currently sparrow wallet will load the same tx/address labels for a "wallet" regardless of a different BIP39 phrase, which leads to mislabeling.

db should save labels under  fingerprint or xpub and to distinguish.

**Comment by craigraw** [comment]
Please see https://github.com/sparrowwallet/sparrow/issues/603#issuecomment-1163388023

Sparrow does not store anything derived from the passphrase, so it cannot know if the address labels apply to a different passphrase. 

> db should save labels under fingerprint or xpub and to distinguish.

Doing so would reduce wallet security as discussed in the link above.

**Comment by sparcsun** [comment]
I'm not sure I follow... The wallet is storing labels, so we know there was account activity. It can at minimum hash the xpub and store that with the labels, and hence x-check when loading a BIP39 whether those labels belong to this wallet or not. I dont believe this leaks info more than the fact there are labels associated to a wallet file.

**Comment by tadeubas** [comment]
The point discussed on issue #603 is regarding plausible deniability and security, I think you should read the whole thread there. Saving any extra info is extra info to a possible attacker.

**Comment by sparcsun** [comment]
I re-read the thread, and still not entirely convinced. Here are my assumptions, and please do challenge:

1. Sparrow is desktop software, with different attack vector than a mobile wallet
2. We are already storing labels, hence labels appearing against non-exsisting UTXOs is already info leak.
3. Super paranoid user, would not use labels in general, labels are for ppl that actually need to track stuff, and can potentially be very descriptive. Hence they have made that trade off for themselves. 
4. This can be easily solved by having a custom label field to load from, i.e. user input label ID# (not great UX, but solves "info leak",, or a simpler way is for example to take random consecutive 10 character substring of hash(xpub) and pattern match when loading... 

Of course, framing the problem, I use BIP39 because I want to put alot of effort to secure my 1 seed, and only 1 seed, and use a passphrase for subaccounts for example or plausible deniability... at the moment, using labels with subaccount (via different phrases) doesnt work...

I also understand project priorities/resources, but pushing back a bit on security risk premise...

**Comment by tadeubas** [comment]
@sparcsun could you create multiple wallets (with the same BIP39 words) to do act "subaccount" via different BIP39 phrases? This way the labels of TXs/address would distinguish, right? (you would only have to open the right wallet for the right passphrase)

**Comment by sparcsun** [comment]
@tadeubas that's smart! 
I was going to suggest we decouple labels from the wallet db files into a label db to further increase privacy... your 
suggestion is simple and works, thank you!
