### ISSUE TITLE
Closing connection 2482: ... (connection has passed maxLifetime)

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#601]
Duplicate of https://github.com/sparrowwallet/sparrow/issues/583

`Closing connection conn2482: url=jdbc:h2:/Users/... user=SA: (connection has passed maxLifetime)`

I don't think the issue should have been closed.

The way Sparrow end up being permanently disconnected and not reconnect after a day or so is abnormal.

**Comment by craigraw** [comment]
This message does not refer to the server connection, but is printed by the database connection pool as part of its normal management processes. In this case, it's simply closing old database connections (it opens new ones as necessary too).
