### ISSUE TITLE
Not recognizing my new Coinkite hardware wallet

### ISSUE THREAD

**Issue by Calegard** [sparrowwallet/sparrow#605]
I just received my hardware wallet from Coinkite and I watched their tutorial on the quick start guide.  I’m to the point of connecting with Sparrow wallet but when I’m trying to scan for my hardware wallet (and yes it is connected via USB) I repeatedly get the message “No hardware wallets found”.  Any insight and solutions on this issue?

**Comment by Calegard** [comment]
Okay, apparently the USB cable was bad (even though it powered up my Coinkite wallet).  I switched cables and now it recognizes my wallet.

**Comment by craigraw** [comment]
The USB power line and communication line are separate, so it's possible just the one was damaged.
