### ISSUE TITLE
Generate secure bip39 passphrase

### ISSUE THREAD

**Issue by Jakob-1870** [sparrowwallet/sparrow#609]
For people who want an uncrackable passphrase,
a "Generate Secure Passphrase" button should simplify this process. 

They won't have to find, possibly insecure, supplemental tools.
 
The only concern I see is newbies who see the button and click it because it says secure, thinking that it's required or insecure if they don't use it; not understanding the purpose of it.
It should be clear, as Sparrow currently does, that it's optional.

**Comment by craigraw** [comment]
Generating a long random sequence of characters for a user to remember is probably only appropriate for advanced users (who would likely have their own ways to do this anyway). Newbies using this feature would likely forget such a difficult passphrase and lose access to their funds. So on balance I think not a good idea to add this - better for the user to choose their own passphrase suitable to their experience.
