### ISSUE TITLE
testnet addresses?

### ISSUE THREAD

**Issue by neuro-fishy** [sparrowwallet/sparrow#61]
Hi

I wanted to test out Sparrow wallet (1.1.0) and I didn't find any means to use testnet addresses (tb1*). Whatever I do I get bc1*

I didn't find any docu either about testnet.
Am I missing something, or it's not yet implemented?

Thank you

**Comment by louneskmt** [comment]
Check out the README here : https://github.com/sparrowwallet/sparrow#configuration

**Comment by neuro-fishy** [comment]
Thank you.
In case it's indeed missing from https://sparrowwallet.com/docs, please consider adding the command line options there too.
