### ISSUE TITLE
Do not inform that the wallet is using a passphrase

### ISSUE THREAD

**Issue by Jakob-1870** [sparrowwallet/sparrow#610]
Sparrow is informing potential attackers that the user is using a passphrase wallet through the passphrase popup when loading the wallet. This doesn't occur with non-passphrase wallets.
This incentivizes the attacker to continue attacking since the user may have more wallets. This security relies on an attacker being ignorant of secret wallets but this is a dangerous assumption. It would be better if sparrow did not inform that the user has additional wallets. So that wallets with and without passphrases appeared the same.

I'm not sure what the best UX for this would be.
Maybe by default open the regular seed wallet. Then there can be a new advanced setting somewhere, "Open passphrase wallet"
It would have a warning about what the passphrase is, that it needs to be saved, etc.

I think this would give users better plausible deniability.
The only downside I see is that it's easier for the user to forget he has a passphrase wallet and use his seed wallet instead. Or just forget about it entirely.
But I think the advantage of it overrides this concern, especially as this feature is for advanced careful users.

**Comment by Bzvwf16WSDKoSZd8** [comment]
Indeed, this is an existing user experience issues on Sparrow wallet.
Another two major multisig wallets, Blue wallet and Electrum have also support BIP39 passphrase, buy they do not ask for BIP39 passphrase when re-opening the wallet.

Bluewallet also offers Plausible deniability, but it is turned off by default!
https://bluewallet.io/features/#pdeniability

**Comment by craigraw** [comment]
> Maybe by default open the regular seed wallet. Then there can be a new advanced setting somewhere, "Open passphrase wallet"

I believe this would add considerable complexity (to an area that already has a lot of user queries) without adding much security. There is not much evidence to suggest that plausible deniability is successful security approach, and it conflicts to some extent with using Sparrow offline and storing no derived information about the passphrase. But it is possible to use several passphrases if you want it.

> The only downside I see is that it's easier for the user to forget he has a passphrase wallet and use his seed wallet instead. Or just forget about it entirely. But I think the advantage of it overrides this concern, especially as this feature is for advanced careful users.

I disagree - I think it would be very common to start using the 'regular' wallet by mistake. Passphrases in my experience are used by a wide range of users.

**Comment by craigraw** [comment]
Closing this off as I don't see a good way to achieve it (that wouldn't risk confusion and potential loss of funds).
