### ISSUE TITLE
Getting notifications of transaction showing "0 BTC total"

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#614]
<img  alt="image" src="https://user-images.githubusercontent.com/388716/177023986-8e715f37-2cbe-4e63-b1ae-2ed8bb94bc2d.png">

Useful to know something was detected but why show 0 BTC?

This happens when the wallet is doing it's syncing after having disconnected.

**Comment by craigraw** [comment]
> Useful to know something was detected but why show 0 BTC?

This is because the BTC total of new transactions found is zero.
