### ISSUE TITLE
In some cases Sparrow doesn't create BIP47 notification transaction. This may result in loss of funds.

### ISSUE THREAD

**Issue by limpbrains** [sparrowwallet/sparrow#617]
If Alice sent Bob some funds with BIP47, Bob now can send them back to Alice, but before that he needs to send Notification transaction, despite that wallet already knows about this channel. Sparrow doesn't do that, it allows immediate sending. 

Now if Alice removes her wallet and tries to recover it with seed phrase, wallet will not find Notification transaction and will not recover Bob -> Alice payment. 

I reproduced this bug with v1.6.5 on testnet.

**Comment by craigraw** [comment]
When Alice loads her PayNym (Tools > Show PayNym) the BIP47 wallet linking to Bob will be created, so this is only relevant to using BIP47 without PayNyms.

**Comment by limpbrains** [comment]
Not sure if I activated PayNym, on Alice wallet, probably not.

**Comment by craigraw** [comment]
Fixed in 22303a2e. Sparrow will now only allow sending to PayNyms or payment codes where a notification transaction to the recipient has previously been sent from the wallet.
