### ISSUE TITLE
Feature request: Sweep funds from a BIP38 encrypted paperwallet

### ISSUE THREAD

**Issue by Mannohat** [sparrowwallet/sparrow#620]
I would like the ability to use Sparrow Wallet to sweep funds from a BIP38 encrypted paper-wallet.

**Comment by Mannohat** [comment]
**For others that encounter this challenge, this is how I got it to work.**
Using Sparrow Desktop and the Bluewallet app on iOS:
1. In Bluewallet > add new wallet > select bitcoin > and then at the bottom, select "import wallet".
2. You are now prompted to enter the passphrase and it then shows a new wallet and its balance.
3. In the Sparrow top menu, select Tools > Sweep Paper Wallet. Choose the destination address/wallet in the dropdown and select the camera icon to open for a QR scan.
4. In Bluewallet, select the newly imported wallet and tap the 3 dots in the top-right corner, then select "Export/Backup" to open a **secret** QR code which you then show the Sparrow QR reader.
5. Check everything and you are good to go.

**Comment by craigraw** [comment]
Implemented in ecf9b787. Pasting a BIP38 encrypted private key into the Sweep Private Key dialog will trigger a popup requesting the passphrase for the key, after which it will be decrypted to WIF format for sweeping.
