### ISSUE TITLE
HWI on Linux doesn't always cleans it's temporary directory

### ISSUE THREAD

**Issue by eugenesan** [sparrowwallet/sparrow#629]
I discovered that packaged in Sparrow HWI 2.1.1 binary, doesn't always removes it's temporary directory.

It's not obvious what causes that behavior but I suspect it happens when there is USB communication error.
I was playing around and running both Ledger Live and Sparrow and after a few hours there were a few dozen copies of HWI temporary directories (usually named /tmp/_MEIXXXXXX). Each instance takes ~50MB and since most Linux installations limit /tmp to free space on root partition, it can cause issues pretty quickly.

At least in one instance, HWI obviously crashed and left it's temporary directory:
kernel: [201989.142012] hwi-2.1.1127641[261498]: segfault at 200 ip 00007f9c2a20a28b sp 00007f9c261fdd20 error 4 in libusb-1-150b88da.0.so.0.1.0[7f9c2a200000+17000]

I see no corresponding entries in sparrow.log

I can think of the following workaround:
1. Run HWI binary with the following environment variable: TMPDIR=/tmp/HWI-123
2. When execution is finished, make sure /tmp/HWI-123 is empty

**Comment by craigraw** [comment]
Looks like a known (and old) [issue in pyinstaller](https://togithub.com/pyinstaller/pyinstaller/issues/2379) that has only very recently [been fixed](https://togithub.com/pyinstaller/pyinstaller/pull/6923). Hopefully we will see a new release of pyinstaller soon that can be incorporated into HWI.

In the meantime I'll look into how Sparrow can clean up these 'temporary' directories.

**Comment by craigraw** [comment]
I've added a check in 4e08334a to test if the HWI process exited with a value other than zero, and if so to find and delete the `_MEIxxxxxx` directory that was created if it still exists.

I'm going to close this off as solved, but if the issue reoccurs (it's difficult to test) then please comment below.

**Comment by oliverlj** [comment]
i'm seeing this issue as well on ubuntu 22.04
