### ISSUE TITLE
BitBox02 not detected on macOS

### ISSUE THREAD

**Issue by Stadicus** [sparrowwallet/sparrow#63]
Sparrow uses HWI to connect with hardware wallets. The BitBox02 is fully supprted for single-sig wallets and the integration in Sparrow works nicely on both Linux (Ubuntu 20.04) and Windows 10.

![sparrow-bb02-win](https://user-images.githubusercontent.com/19550140/109382914-86d5cd00-78e3-11eb-9171-c979e7127e3e.jpeg)

![sparrow-bb02-linux](https://user-images.githubusercontent.com/19550140/109382919-8b01ea80-78e3-11eb-952a-dbb61af1d040.jpeg)

On macOS (High Sierra, 10.13.6) the BitBox02 is not detected at all, however. I follow exactly the same steps as on the other operation systems. Are there any specific logs I can provide to dig deeper?

**Comment by craigraw** [comment]
Thanks for the report. Are you able to test if HWI can see the Bitbox directly? You’ll see the location of the hwi binary in the sparrow config file - running hwi enumerate should list it.

I need to ask Shift for a demo device to test with.

**Comment by Stadicus** [comment]
I just ran the HWI binary that came with Sparrow with `./hwi enumerate` on macOS cli, but it does not show any devices. I guess that's the underlying issue.

I'll try to reproduce with the latest HWI release, running it from source directly, and report back.

I'm part of the Shift Crypto team, and happy to send you a device for testing. I'll DM you separately for that.

**Comment by Stadicus** [comment]
Quick update: I tested running HWI from source, version 1.2.1 and master, and both versions detect the BitBox02 without issue.

* version 1.2.1 (commit `d86368f`)
  ```sh
  stadicus@Shift-MacBook: ~/HWI $ ./hwi.py enumerate
  [{"type": "bitbox02", "path": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D,7/EHC1@fd000000/PRT1@fd100000/IOUSBHostDevice@fd100000/AppleUSB20InternalHub@fd100000/AppleUSB20HubPort@fd120000/BitBox02@fd120000/IOUSBHostInterface@0/IOUSBHostHIDDevice@fd120000,0", "model": "bitbox02_multi", "needs_pin_sent": false, "needs_passphrase_sent": false, "fingerprint": "b5496bff"}]
  ```

* version 2.0.0-dev (master)
  ```sh
  stadicus@Shift-MacBook: ~/HWI $ ./hwi.py enumerate
    [{"type": "bitbox02", "path": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D,7/EHC1@fd000000/PRT1@fd100000/IOUSBHostDevice@fd100000/AppleUSB20InternalHub@fd100000/AppleUSB20HubPort@fd120000/BitBox02@fd120000/IOUSBHostInterface@0/IOUSBHostHIDDevice@fd120000,0", "model": "bitbox02_multi", "needs_pin_sent": false, "needs_passphrase_sent": false, "fingerprint": "b5496bff"}]
  ```

The HWI binary installed by Specter somehow does not find any devices:

* version 1.2.1
  ```sh
  stadicus@Shift-MacBook: /private/var/folders/by/fjt772d92fg8_wkzf74wgdxm0000gn/T/hwi-1.2.1-4242736371183522221 $ ./hwi enumerate
  []
  ```

**Comment by craigraw** [comment]
Sparrow uses a slightly modified [fork](https://github.com/sparrowwallet/HWI) of HWI on OSX, which avoids the need to expand the pyinstaller binary to the HWI application + Python runtime every time it runs, triggering a fresh Gatekeeper check on the newly created hwi executable and slowing things down significantly. It does this simply by changing the pyinstaller build to build the expanded application + Python runtime, which Sparrow then puts in a temporary file location the first time it is used, saving the location of the hwi executable in the config file.

Likely due a mistake with rebasing, it appears that this fork is different to the v1.2.1 commit `d86368f` in more ways than it should be: https://github.com/bitcoin-core/HWI/compare/master...sparrowwallet:master

I'll sort this out with the next release. Thanks for the testing and feedback!

**Comment by Stadicus** [comment]
> I'll sort this out with the next release. 

Awesome, thank you very much.

**Comment by craigraw** [comment]
#f0c239d upgrades HWI to 2.0.0rc2 which sorts this problem out.

Thanks for the testing device!

**Comment by marcocattaneogotam** [comment]
I still have the same issue today with sparrow 1.7.7
