### ISSUE TITLE
Add Support for Electrum QR PSBT's

### ISSUE THREAD

**Issue by Jakob-1870** [sparrowwallet/sparrow#632]
Electrum is very useful for many people setting up cold storage as it comes pre-installed on Tails OS.
It would be nice if Sparrow supported it.

A simple button in the QR code menu--like the cobo legacy encoding button would work.

**Comment by craigraw** [comment]
I think it would be better for Electrum to support the widely supported animated QR standard that has emerged with UR 2.0. Cobo Vault used an early draft of this standard (not recommended by the spec creators), and now that this product has been abandoned by its manufacturer I'd like to remove this button someday. Supporting multiple incompatible QR standards makes the UI unnecessarily more complex IMO. 

Better still would be for Tails to include Sparrow by default - all that is necessary to my knowledge is for someone to add and maintain a Sparrow package in the Debian repo.

**Comment by Jakob-1870** [comment]
I made an issue for it on electrum.
https://github.com/spesmilo/electrum/issues/7905
