### ISSUE TITLE
Error Loading PSBT

### ISSUE THREAD

**Issue by S4JJ4D** [sparrowwallet/sparrow#633]
Trying to import the following psbt which was generated through bitcoin-cli `createpsbt` command, Sparrow prompts an error with the message "No UTXO data provided".

**psbt**: 
```
cHNidP8BAGECAAAAAb0dR04sAl0sMmY+BVZXixqarGeBac9aioWTdbXyTTzkAQAAAAD/////AQAAAAAAAAAAJWojQnVybmluZyBhIGZldyBzYXRzIHNob3VsZG4ndCBtYXR0ZXIAAAAAAAAA
```
outpoint (`txid:vout`) for this psbt is just a random UTXO on the chain.

I have validated this psbt through both Electrum and [https://bip174.org/](https://bip174.org/).

Interestingly, Sparrow is able to parse the psbt if it goes through the following path:
 
```
┌───────────────────────┐    ┌────────────────────────────────┐    ┌────────────────────────────┐
│Load PSBT into Electrum├───►│Export parsed PSBT as .psbt file├───►│Load .psbt file into Sparrow│
└───────────────────────┘    └────────────────────────────────┘    └────────────────────────────┘
```

**Comment by craigraw** [comment]
Thanks for the bug report. Reinspecting BIP174, it looks like PSBTs without UTXO information are allowed, so Sparrow now accepts these as of https://github.com/sparrowwallet/drongo/commit/ce90e29284a3faa4479620a612a05b444b2a56b1.

They won't be of much use for signing though, as Sparrow uses the UTXO data to locate a wallet (from the currently loaded wallets) that can perform the signing.
