### ISSUE TITLE
Funds not showing sent from Strike App

### ISSUE THREAD

**Issue by og-blc** [sparrowwallet/sparrow#637]
I recently bought a Coldcard to stack sats in. I followed BTC Sessions video on YT regarding the set up. For my first transaction I sent 0.0004 BTC from Strike via scanning the QR code on the Sparrow "receive" tab. The transaction was sent on Stike's end and has over 9 confirmations on block explorer and yet is still not showing in my Sparrow wallet. I have refreshed the wallet, restarted my computer, and confirmed that the receiving address was in fact generated from Sparrow. I do not have a password or passphrase associated with this wallet or Sparrow in general.  Not sure what to do here. Please help.

Thanks.

**Comment by og-blc** [comment]
I just did a ledger to sparrow tx and it was fine. Something is wrong from Strike to sparrow.

**Comment by craigraw** [comment]
What server are you connecting Sparrow to? Consider changing to a public server temporarily to check.

**Comment by og-blc** [comment]
I'm connected to (and have only used) a public server ssl://electrum.emzy.de:50002

**Comment by craigraw** [comment]
Ok - and the wallet loading log (Transactions tab) shows the wallet completes loading without errors?

You're able to see the address you sent to (assume you have the txid to check on a block explorer) in the Addresses tab in your Sparrow wallet?

**Comment by og-blc** [comment]
Wallet loading log completes with no errors. When I hit refresh it pops up that my last tx (from ledger) was confirmed.

I am NOT able to see the address that I sent to from Strike in the "Addresses" tab. I can only see the address when I look thru the 250 receive addresses on my coldcard (exported to excel).

I hit "Get Next Address" (on Sparrow) before I scanned the QR code on my Strike app to send the funds. Not sure if that has anything to do with this or not.

**Comment by craigraw** [comment]
> I am NOT able to see the address that I sent to from Strike in the "Addresses" tab.

Ok - have you imported the Coldcard with the correct script type and derivation path? (Do the first addresses in the Coldcard address export match those in Sparrow?)

If so you may just need to increase your gap limit (Settings > Advanced). If not, change the script type or derivation path before importing.

**Comment by og-blc** [comment]
Script type and derivation path checks out.
I increased gap limit by increments of 5 (I am now at 75), refreshed wallet, and MY BTC SHOWED UP!

Thank you so much for the help. I cannot thank you enough!

**Comment by craigraw** [comment]
Great! Closing this off.
