### ISSUE TITLE
Show/Switch network in GUI

### ISSUE THREAD

**Issue by keblek** [sparrowwallet/sparrow#64]
right now you have to set an env variable or write a file to specify the network, would be convenient to be able to switch in the GUI when taking a wallet.

**Comment by craigraw** [comment]
True, but doing so would add considerably to the complexity and maintenance requirements of the codebase and UI, and potentially also confuse the user. Testnet/signet support instead follows the original goal - to be a near-identical copy of the mainnet chain, but running apart from it, and so Sparrow does the same with the app.

**Comment by keblek** [comment]
I understand, it's probably why so few wallets offer the feature.

Do I have to build from source to switch networks? 

I can't seem to get it to start up in signet mode with this command on macOS `sudo open /Applications/Sparrow.app -n=signet`.

Any tips?

**Comment by craigraw** [comment]
You don't need to build from source. Try

``open /Applications/Sparrow.app --args -n signet``
