### ISSUE TITLE
[BUG] Wallet PIN shown in plain text during wallet load prompt

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#642]
I just build Sparrow 1.6.6 on a Linux Ubuntu flavor and the text/numbers in the PIN field during a wallet load is suddenly shown in plain text. 

Have I missed something and is this intentionally?

UPDATE: After closing and reopening the wallet the PIN entry is hidden behind bullets once again and I can't reproduce the error. Maybe just something during the very first start?

**Comment by craigraw** [comment]
Odd. Never seen this behaviour. Let me know if you see it again. There have been no changes to the password dialog for some time.

**Comment by craigraw** [comment]
I assume this hasn't happened again - can we close this off for now?

**Comment by RequestPrivacy** [comment]
Unfortunately (or fortunately?) it never happened again, no.

So closing this off for now.
