### ISSUE TITLE
Cancel rescan

### ISSUE THREAD

**Issue by casey** [sparrowwallet/sparrow#646]
Is it possible to cancel a rescan? I changed a wallet birthday, but I think it continued to scan from the prior birthday.

**Comment by craigraw** [comment]
Unfortunately Bitcoin Core provides no way to cancel a rescan (other than shutting it down). The best advice here is to use an Electrum server like Fulcrum to make individual wallet scanning unnecessary.

**Comment by casey** [comment]
Ah, okay. Thank you!
