### ISSUE TITLE
Coldcard UX hint on export is outdated for Mk4 with firmware >= `5.0.2`

### ISSUE THREAD

**Issue by scgbckbone** [sparrowwallet/sparrow#647]
from Coldcard firmware version `5.0.2` (current head is `5.0.6`) menu option `Import from SD` changed name to `Import from file`. This only applies to Mk4, Mk3 still has `Import from SD`. Just a minor thing I noticed playing with Sparrow. Besides this - great wallet - keep it up!

![Screenshot from 2022-08-06 16-21-04](https://user-images.githubusercontent.com/25349625/183252937-752e7254-95a3-4bb8-8a15-5d70fabe3ab8.png)

**Comment by craigraw** [comment]
Thanks!

Text updated in f1a662ba.
