### ISSUE TITLE
Pure Java package of the app

### ISSUE THREAD

**Issue by eugenesan** [sparrowwallet/sparrow#648]
I wonder is there a reason why there are only "binary" packages of the app in each release?

It would really nice to see a pure java package generated by .`/gradlew distTar` for those of us who already have JRE installed.

P.S.
There is one caveat. Native binaries (hwi and libbwt_jni) are packaged only for the platform the package is built on.

**Comment by craigraw** [comment]
Bundling with Sparrow with a JVM included ensures binary reproducibility, reduced complications from different Java versions, and increased security from a minimal JVM provided by JLink. All this for the cost of a few extra megabytes on disk.

If you want to use your own JRE though, my suggestion is to run from source - this is simple to do and described in the project README.
