### ISSUE TITLE
BIP47 Notification TX funds source from specific account

### ISSUE THREAD

**Issue by rapidlab309** [sparrowwallet/sparrow#651]
As for the moment, the notification TX will be payed by the account you were on when opened the PayNym window. I suggest that before making the TX and accepting it, Sparrow should show what UTXO is about to use and from which account.

**Comment by craigraw** [comment]
Unless I'm missing something, this is what the Preview button is for:

<img width="472" alt="Screenshot 2022-08-10 at 12 40 38" src="https://user-images.githubusercontent.com/862166/183882237-af454b23-6c4e-451d-9951-fc98b904840a.png">

**Comment by rapidlab309** [comment]
True. Had something wrong on my side, where I couldn't broadcast the preview TX.
