### ISSUE TITLE
Refresh button for collbrative TX

### ISSUE THREAD

**Issue by rapidlab309** [sparrowwallet/sparrow#652]
At the moment when the counter timed out, the requested aborted after 60 seconds and the user must re-enter the PayNym details from scratch. A refresh button would make it lot easier, specially on the current Tor DDoS attack.

**Comment by craigraw** [comment]
Yes, I can see how this would be useful. Added hyperlink to retry meeting request in e4383899.

<img width="842" alt="Screenshot 2022-08-10 at 14 14 49" src="https://user-images.githubusercontent.com/862166/183898697-91a25253-84b8-44df-b0ee-73932b308013.png">
