### ISSUE TITLE
wallet loading history notification and no reception of transferred btc

### ISSUE THREAD

**Issue by tmunchkin** [sparrowwallet/sparrow#658]
Hi, I created a new wallet in sparrow earlier and transferred btc from my electrum wallet to the receiving address. The transaction went through however it has not been received by the sparrow wallet.  I double checked that I sent it to the correct address and I did. All the sparrow wallet says is that it is loading the history for that wallet. It has said this for the past 12 hours.  Is the btc lost? I don't understand why this would be happening, is there any way to fix this?

**Comment by craigraw** [comment]
It is almost certainly not lost - you simply have a wallet loading issue. What server are you connecting to?

**Comment by tmunchkin** [comment]
I think I'm connected to a public server which I didn't realize when setting it up. electrum.emzy.de.  Reopening the wallet I also can no longer see the receiving address in the history panel.

**Comment by craigraw** [comment]
Let's move this over to the Telegram support channel at https://t.me/SparrowWallet. A number of things come to mind (such as entering an incorrect passphrase) but it's easier to communicate there.
