### ISSUE TITLE
[BUG] "Show log file" doesn't open file

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#659]
Sparrow  version: https://github.com/craigraw/beta/releases/tag/1.6.6-no-debug-stripping
Host: Linux Kubuntu 22.04 LTS
Editor: Kate
File Manager: Dolphin

The log file does exist in the .sparrow folder and I recall opening worked properly some (?) versions ago. In the log itself nothing is mentioned why it failed to show the logs.

https://user-images.githubusercontent.com/72392544/185160017-9294ff90-326e-4ad8-9b57-db2815946d72.mp4

**Comment by craigraw** [comment]
This may be due to the size of the log file. Sparrow asks the OS to open the file, and cannot know if the request completed successfully or not unfortunately.

You should be able to test if the log can be opened by double-clicking on it in the file manager. If there's a problem, try moving it out so Sparrow creates a new file.

**Comment by RequestPrivacy** [comment]
I deleted all text in the log file manually and at the time I recorded the above video the file had nothing in it. So file size isn't the problem I guess.

Opening manually via the file manager worked and works without problems. I just deleted the file and Sparrow created a new one.

Unfortunately the problem still exists though.

**Comment by craigraw** [comment]
In the video, what application was it trying to open the file in? It appears briefly in the taskbar with a round blue icon.

**Comment by RequestPrivacy** [comment]
It's the default editor in the Kubuntu flavour.

![image](https://user-images.githubusercontent.com/72392544/185374856-1ab6e87a-9004-46cb-90a2-288a1234262f.png)

**Comment by craigraw** [comment]
That's odd. So Sparrow is correctly launching the editor, but it terminates or crashes for some reason. Is there anything in syslog which might indicate why? It might be useful to temporarily change the default application for the log file type to see if the same behaviour occurs.

**Comment by RequestPrivacy** [comment]
Changing the default application to Okular allows Sparrow to open the log file. So it seems to be a Kate related issue.

If Kate is already open (plain, without something loaded) it gets the log file once I tell Sparrow to display it. Still researching how to increase the verbosity of `syslog` or `journalctl`, right now it just states that Kate opens but shows no error once it "crashes/closes". A general tip on how to increase the output would be appreciated.

Feel free to close the issue if you think it isn't of any interest and/or to vaguely related to Sparrow.

**Comment by craigraw** [comment]
You show be able to edit `rsyslog.conf` and change from `*.info` to `*.debug` - but I confess I haven't tried this myself.

Closing this off as I don't think there's much Sparrow can do here - this relates to URI handling in another application.
