### ISSUE TITLE
[UI] Mockup of side buttons rotated and columns with more similar size.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#660]
I've had a hard time looking at the sideway icons, especially since 3 of them represent movement/directions.

The second column buttons are a bit too wide, they would only be square if the wallet is used in full screen mode. (1080p)

![image](https://user-images.githubusercontent.com/388716/185195516-f3fe23ca-ff67-42f9-8eff-97473003c63a.png)
![image](https://user-images.githubusercontent.com/388716/185193737-6c8f5170-86e6-4040-9c84-0b876cb555fc.png)

**Comment by craigraw** [comment]
Closing this off in favour of #807.
