### ISSUE TITLE
Display the BIP47 address

### ISSUE THREAD

**Issue by cutiful** [sparrowwallet/sparrow#664]
After connecting to the Electrum server, Sparrow subscribes to the addresses derived from the zpub and a BIP47 address with the following derivation path: `m/47'/0'/0'/0`.

Some Electrum server software (e. g. Electrum Personal Server) needs to know all of the user's addresses in advance. Such software is impossible to configure without knowing the BIP47 address. Given only the zpub, EPS returns a cryptic error (showing its scripthash as per the Electrum protocol spec) and disconnects the client.

Would it be possible to show the address somewhere in the UI (e. g. under xpub/zpub in settings)? Assuming it isn't already shown, but I couldn't find it. It's the only thing that prevents Sparrow from being used with EPS.

**Comment by craigraw** [comment]
I've done one better here - as of d139ca27 Sparrow can now export a file containing the relevant fragments for the EPS config file, including the notification address and any BIP47 wallets. Note that if a BIP47 payment is received, the export will need to be redone. 

<img width="612" alt="Screenshot 2022-08-22 at 14 35 30" src="https://user-images.githubusercontent.com/862166/185922570-68ba8664-f54b-4d8d-a042-312d48cc5046.png">

**Comment by cutiful** [comment]
Thank you so much!

**Comment by cutiful** [comment]
I just tested this feature, it works well with a regular wallet. But premix/postmix/badbank don't use BIP47, so export fails for those.

**Comment by cutiful** [comment]
Also, as far as I understand from https://github.com/sparrowwallet/sparrow/issues/430#issuecomment-1046917099, premix/postmix/badbank are created automatically once the user starts a coinjoin. Would it be possible to export them along with the main wallet? Or at least mention that you need to export them separately in the comments.

**Comment by craigraw** [comment]
Agreed, it makes sense to always export all related wallets. I've made this change in c24f953e.

**Comment by cutiful** [comment]
Perfect, thanks!
