### ISSUE TITLE
Having issue connecting sparrow on linux mint  to my umbrel node hosted on a raspberry pi

### ISSUE THREAD

**Issue by tdf1230** [sparrowwallet/sparrow#665]
using a raspberry pi to run umbrel node , having a issue connecting sparrow wallet on linux mint to my node, also running sparrow on my macbook pro and it is connecting without any issues, tyring to determine if setup is different for linux mint 
any ideas thanks

**Comment by craigraw** [comment]
There should be no difference from Sparrow's perspective, so if both configurations are the same, likely there is something local to the linux mint machine or the network that is causing the issue. Trying pinging the Umbrel etc to see if connectivity exists.

It's better to handle configuration issues on the Telegram group: https://t.me/SparrowWallet, closing this off here.
