### ISSUE TITLE
Feature request: Allow specific custom derivation paths (without standard receive/change step)

### ISSUE THREAD

**Issue by sutterseba** [sparrowwallet/sparrow#666]
I am trying to import a quite specific multisig setup where I need to access keys at `m/0/0/20/n`, with `n` being the **address** index.

* Yes, this path is not the standard.
* Yes, **all** components are unhardened.
* Yes, there is no extra derivation step for receive/change addresses. Account `20` is receive, `21` is change.

Now to my issue: Sparrow interprets any given derivation path as the account path and therefore derives to `m/0/0/20/0/n`,  performing the extra derivation step for receive addresses, which is absolutely correct _under normal circumstances_, but makes it impossible to access the specified path.

Would it be possible to add an opt-in setting that ignores the extra derivation step and derives signing keys **directly** at the custom path such that the custom path `m/0/0/20` leads to addresses at `m/0/0/20/0`, `m/0/0/20/1`, [...]?

That would make Sparrow a lot more powerful (and me very happy)!

**Comment by craigraw** [comment]
Unfortunately there is a lot of work and additional UI complexity to support this use case, which I think is fairly rare. For example, in the Addresses there would now be no "Change" table, or concept of change in the wallet itself. Change is an important design feature in BIP32 for many reasons in a general wallet application. 

Receive and change addresses are a very well supported standard - there is even now special syntax in output descriptors to support this derivation path step. Consider adapting your derivation path so it can support more wallets, even if you don't actually use the change derivation.

**Comment by sutterseba** [comment]
> Consider adapting your derivation path

This is about **recovery** of an existing BitGo multi-sig. They do have a recovery tool (which is very bad) but I was trying to find a different and easy way around it - mainly to help other users. 

I absolutely understand, of course, that this is too much effort for this specific use case! Thanks for the quick reply.
