### ISSUE TITLE
Randomize mnemonic phrase's backup verification

### ISSUE THREAD

**Issue by rapidlab309** [sparrowwallet/sparrow#670]
As opposed on Telegram group, it might be more secure to have the mnemonic phrase words to be typed in random order.

**Comment by craigraw** [comment]
One problem with this is it prevents the cut and paste of the whole series of words (which is immensely helpful in testnet situations). It's also adding another step to potentially confuse new users, and I suspect would create a lot of support issues.

I think I would need to see some examples of keystroke logging causing loss of funds before implementing this.
