### ISSUE TITLE
disable telemetry: stop phoning home on wallet startup

### ISSUE THREAD

**Issue by nyxnor** [sparrowwallet/sparrow#674]
Disable pinging sparrow by configuration, option needed

My tor controller logs show this when starting the wallet:

```
650 STREAM 2731 NEWRESOLVE 0 www.sparrowwallet.com:0
650 STREAM 2732 NEWRESOLVE 0 www.sparrowwallet.com:0
650 STREAM 2731 SENTRESOLVE 4228 www.sparrowwallet.com:0
650 STREAM 2732 SENTRESOLVE 4228 www.sparrowwallet.com:0
650 STREAM 2731 REMAP 4228 135.181.110.78:0
650 STREAM 2732 CLOSED 4228 www.sparrowwallet.com:0
650 STREAM 2731 CLOSED 4228 135.181.110.78:0
650 STREAM 2733 NEW 0 135.181.110.78:443
650 STREAM 2733 SENTCONNECT 3856 135.181.110.78:443
650 STREAM 2733 REMAP 3856 135.181.110.78:443
650 STREAM 2733 SUCCEEDED 3856 135.181.110.78:443
```

Didn't find any option to disable telemetry.

**Comment by craigraw** [comment]
You can disable checking for software updates in the preferences:

<img width="432" alt="Screenshot 2022-08-29 at 09 01 04" src="https://user-images.githubusercontent.com/862166/187142428-0f8f0ada-be05-4224-9792-c5b0e7a14feb.png">

**Comment by nyxnor** [comment]
Thanks, summing
- disabling exchange rate source (set it to none)
- diabling notifications for software updates

I don't see any other domains being pinged except my private electrum server.

**Comment by craigraw** [comment]
Thanks, also see https://github.com/sparrowwallet/sparrow/issues/657#issuecomment-1217728077 regarding increased logging for external connections.
