### ISSUE TITLE
GUI partially blanked after suspend on Ubuntu

### ISSUE THREAD

**Issue by wielandgmeiner** [sparrowwallet/sparrow#676]
When coming back from suspend the gui is sometimes, not always, partially blanked. Sometimes completely, shows only canvas, sometimes fonts are missing.
Version: sparrow_1.6.6_amd64.deb
OS: Ubuntu 20.04.4 LTS
![screenshot](https://user-images.githubusercontent.com/1280973/187424714-d33180f5-a210-4a1c-9923-a46d1a6e1248.png)

**Comment by craigraw** [comment]
This appears to be a Linux graphics driver issue: https://bugs.openjdk.org/browse/JDK-8096170

Unfortunately, I don't think it's within Sparrow's codebase to fix. Possibly updating the graphics driver (the advice is to use the proprietary driver) may help. Fwiw, I have tested Sparrow on the same OS and version for many years now without this issue.
