### ISSUE TITLE
Transaction history show unconfirmed that were confirmed ~2 months ago.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#68]
there's 3 of them.

**Comment by Transisto** [comment]
I restarted a few times trying to connect to multiple different servers.
New outcome is there's missing at least the last 2 full months of transaction.

As if something crash and abandon when trying to sync more than X addresses.

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/110186753-39c29100-7de4-11eb-9494-36d73b8da9ba.png)

Unconfirmed was confirmed on 2021-01-04 19:55

**Comment by Transisto** [comment]
After trying to connect with blockstream server I manage to get to actual current state.

The whole time where was no way to know if anything was happening in terms of server connection.

**Comment by craigraw** [comment]
> The whole time where was no way to know if anything was happening in terms of server connection.

As of #13d701b, the status bar indicates progress when loading transactions for a new wallet.

> After trying to connect with blockstream server I manage to get to actual current state.

Using public servers can be slow, particularly when loading older wallets. Consider connecting to your own node if available.
