### ISSUE TITLE
Attempting to import my seed from voltage.cloud node results in invalid checksum

### ISSUE THREAD

**Issue by robertclarkson** [sparrowwallet/sparrow#685]
![Selection_093](https://user-images.githubusercontent.com/3826238/190854506-61586b57-0a84-4f4a-8483-4d5523f1e766.png)

**Comment by robertclarkson** [comment]
Actually i've just tested with iancoleman's code and this might be a voltage issue.

**Comment by craigraw** [comment]
Ok - I'll close this off for now then.
