### ISSUE TITLE
"Prevent Computer Sleep" does not seem to prevent sleep on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by stripey679** [sparrowwallet/sparrow#686]
I checked the box for "Prevent Computer Sleep" and left my computer unattended. When I came back, the screen was black and when I moved the mouse, I had to type my password to log back in. My two open wallet tabs had red icons instead of the normal gray ones. I assume this means the computer going to sleep caused problems. These eventually went back to gray, although I'm unsure if it was due to the passage of time, or if I closed and re-opened Sparrow.

To prevent sleep, I had to disable computer sleep through the operating system.

I have not attempted to reproduce this issue after the first time it occurred.

OS: Ubuntu 22.04.1 LTS
64-bit

**Comment by RequestPrivacy** [comment]
Are you sure it went into "sleep" like suspending to RAM? Or did it just lock your screen and turned off the display?

I think the intention of "sleep" is that it doesn't suspend but can still be locked. The red icons aren't necessarily a sign for your computer going into suspend...

**Comment by craigraw** [comment]
Sparrow does the best it can to prevent computer sleep, sending regular keyboard presses to the OS indicating activity. In general, this works well across various desktops. However, how the OS deals with this is somewhat implementation specific, and ideally it's better to configure the OS as you have done - it's authoritative place that handles suspension. 

I don't think there's much more than Sparrow can do here, so I'm going to close this off. Note that alternative, OS-specific applications for handling computer sleep are also listed in the Whirlpool docs.

**Comment by stripey679** [comment]
> Are you sure it went into "sleep" like suspending to RAM? Or did it just lock your screen and turned off the display?
It may have just locked.
 
> The red icons aren't necessarily a sign for your computer going into suspend...
I took them to be one. If they weren't, then I have no reason to believe my computer went into full suspend mode. 

> ...ideally it's better to configure the OS as you have done - it's authoritative place that handles suspension.
There probably wasn't a problem, but in any case I solved it by changing my OS settings, as recommended.
