### ISSUE TITLE
Server UI freeze when still syncing?

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#69]
![image](https://user-images.githubusercontent.com/388716/110186009-efd8ab80-7de1-11eb-8cfa-2eee2c8a92f7.png)

**Comment by craigraw** [comment]
It's unclear what the issue being reported is?

**Comment by Transisto** [comment]
Server pane is grayed out for no apparent reasons. Most likely because it's talking to a server.

**Comment by craigraw** [comment]
Yes, only one connection is allowed at a time. Pressing the 'Edit Existing Connection' in the screenshot above terminates the current connection, allowing you to set up a new one.

**Comment by 6102bitcoin** [comment]
Outstanding Action: Clearly indicate that server has successfully connected
Proposed Priority: Low

**Comment by craigraw** [comment]
I'm going to close this off - I'm not sure there is anything to fix here.
