### ISSUE TITLE
[Feature] Display current synchronized block height of Sparrow client in UI

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#690]
### Current State

When Sparrow receives a new block the client informs the user via an notification at the bottom of the UI. This notification disappears after a short amount of time. As far as I've seen the "block height" Sparrow knows about isn't displayed elsewhere,

### Proposed Feature
Add an permanent information of the last block Sparrow received prominently in the UI. Imho preferably in the `Transactions` tab.

### Reasoning

- Important information for fast debugging (current state of the Sparrow client)
- Generally an important and fun information to display

**Comment by craigraw** [comment]
You can get the current block height from the tooltip on the server toggle in the bottom right.

**Comment by RequestPrivacy** [comment]
Ah sorry for wasting your (and my) time. Totally forgot about this feature. Going to close this off.
