### ISSUE TITLE
Sign a message using taproot address

### ISSUE THREAD

**Issue by mario7421** [sparrowwallet/sparrow#691]
Taproot addresses are not recognized as valid in the form to sign text messages. I am referring to the case in which a taproot wallet is opened inside Sparrow.

**Comment by windsok** [comment]
Is there a standard for message signing with taproot addreses?

**Comment by craigraw** [comment]
Yes, BIP-322 exists, but there is no real adoption yet. I don't know of any wallet software that uses it as of this date.

**Comment by Czino** [comment]
While maybe not the prettiest use case, users receiving bitcoin from exchanges under EU/Swiss regulations could be allowed to also receive to other address types than P2PKH or P2WPKH, including taproot.

I'd really like to tell our users that they can use taproot addresses by using BIP322 style signatures if they use SparrowWallet for signing. I don't know of other wallets supporting it at all. 

I see that Sparrow wallet has BIP322 (simple) as an option, but I am still unable to sign with a taproot address (verification seems to work).

**Comment by craigraw** [comment]
It is certainly possible to sign a message using BIP322 and a taproot address with Sparrow. Is the wallet you are using a software/hot wallet?

**Comment by craigraw** [comment]
Side note: Closing this issue as solved - BIP322 support was added (both signing and verification) in Sparrow v1.7.8.

**Comment by Czino** [comment]
After I restarted Sparrow, signing works now 👍.
It was a hot wallet as I just wanted to test the feature real quick
