### ISSUE TITLE
Show Labels instead of TXids

### ISSUE THREAD

**Issue by AsiaLeone** [sparrowwallet/sparrow#697]
In a Stonewall tx with many inputs, a couple of them get squeezed. Passing on - _N more -_ shows TXids and not label. This makes harder a quick look on the UTXOs involved in the tx. 

![Screenshot 2022-10-07 at 14 45 30](https://user-images.githubusercontent.com/115263199/194589405-9bb88368-981b-4e4b-aacf-8d9f207b9ba1.png)

There should be enough space to get the overlapped window bigger, avoiding UTXOs to get squeezed

**Comment by craigraw** [comment]
Fair enough - as of 22408103 labels will now be shown in the tooltip if present.
