### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by prayank23** [sparrowwallet/sparrow#7]
How do we use sparrow with testnet?

**Comment by craigraw** [comment]
No testnet support yet - may add in future depending on the need.

**Comment by sgeisler** [comment]
I think for integration testing at least having regtest support would be super useful. You could test the entire system (bitcoind, electrum server, sparrow) with custom scenarios fully automatically. I think there are even ui test libraries for Java, so you could emulate user behavior and test if everything works as intended automatically.

**Comment by java4tech** [comment]
I think testnet could be a nice addition, it'll allow devs and non-devs to test features and also test edge cases without taking risk with bitcoin which they might be reluctant to use since this software is new in the market. Testnet allows real world testing on the public blockchain.

**Comment by djpnewton** [comment]
I agree testnet is necessary so we can test functionality without risking bitcoin

**Comment by craigraw** [comment]
Testnet has now been implemented over a series of recent commits, but mostly https://github.com/sparrowwallet/sparrow/commit/c68cda5b2fc6add9fa50e2463e9c80e03f3a6049 and https://github.com/sparrowwallet/sparrow/commit/ff7a35e68b22fc96ac124bd969812e70ac1b9b51.

See the notes at https://github.com/sparrowwallet/sparrow#configuration for running Sparrow on testnet.

Thanks to @djpnewton for the PR and discussion!
