### ISSUE TITLE
Postmix transactions have disappeared

### ISSUE THREAD

**Issue by emeklund** [sparrowwallet/sparrow#700]
Hello! I was mixing multiple UTXOs this past week and my postmix transactions have disappeared. The postmix account balance shows as zero. The postmix transactions view says "Error loading transactions: Failed to subscribe to paths: [m/1/0-m/1/7917]"

Aside from the balance in the badbank, it's as though my mixing coins have evaporated. I have tried reinstalling Sparrow, and exporting/reimporting the wallet. This is on a dedicated Linux Mint OS connecting through Tor/VPN with nothing else running but an internet browser. 

Do you have any suggestions on how to retrieve my coins?

**Comment by emeklund** [comment]
The team at Sparrow Wallet has been extremely responsive. For most issues of this type, they recommend using resolverpanel.com/en

**Comment by craigraw** [comment]
Hey - I am the team at Sparrow Wallet.

It looks like you have been contacted by a scammer. Please do NOT use resolverpanel.com!

With respect to your original issue, increase the gap limit on your Postmix wallet (Settings > Advanced)

**Comment by emeklund** [comment]
Thanks for reaching out to me! You're right, I was contact by scammers. I realized my mistake only after I entered my seed phrase. Fortunately, I didn't share my BIP39 passphrase or wallet password.

I set the gap limit to 9999 and the "transactions" section in the post-mix tab shows that it's "Finding transactions..." and doesn't progress or find the UTXOs or show any transactions.

I have attached a screenshot.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by emeklund** [comment]
One other possible clue. When I open the Sparrow log, I see a message that says "Store header is corrupt"

**Comment by craigraw** [comment]
I'm glad you didn't get your funds stolen!

What server are you connected to? It sounds like the server you are using is not able to cope with the increased gap limit.

**Comment by emeklund** [comment]
Thanks! I'm using a public server connected to Tor.

**Comment by emeklund** [comment]
I cranked up my internet speed to see if that will help. It's been running for about an hour and is "Finding transactions"

**Comment by craigraw** [comment]
You might want to try connecting to the following server, run by someone in the Sparrow community:

Type: Private Electrum
URL: `rqcbvkan255wranepdrxqzwq2wexy6dpzpltsc7rir4epkz7itufwvqd.onion`
Port: `50021`

**Comment by emeklund** [comment]
Thanks! I'll give that a try.

**Comment by emeklund** [comment]
THANK YOU THANK YOU SO MUCH! I have recovered all of the coins. I have also learned the importance of not running too many UTXOs simultaneously and overwhelming my server capacity. I can't tell you how thankful I am for your responsiveness and innovation with this wallet. My cortisol levels were through the roof thinking I had lost my coins, but I actually have more confidence in the network than ever now! I hope to continue using more BTC and perhaps one day even running my own node.

**Comment by emeklund** [comment]
Also, it will be a cold day before I go typing my seed phrase into someone's random website again. ROFL I really took leave of my senses for a minute there.

**Comment by emeklund** [comment]
Thanks again!!!

**Comment by craigraw** [comment]
Great - definitely consider running your own node!
