### ISSUE TITLE
document all RPC calls

### ISSUE THREAD

**Issue by nyxnor** [sparrowwallet/sparrow#703]
I wish to set `rpcwhitelist` for only certain calls to the sparrow rpc user.

Can you please document all RPC calls so I can use as reference?

**Comment by nyxnor** [comment]
Also please consider separating the wallet commands of watching-only vs hot wallets, but this is not necessary, I can check manually, would just be good if separated.

**Comment by craigraw** [comment]
> Can you please document all RPC calls so I can use as reference?

Simplest way to get this info is to turn on DEBUG logging  (`-l DEBUG`) and filtering for the relevant bwt `bitcoincore_rpc` logging lines. See FAQ for details on command line arguments.

e.g.
```
DEBUG bitcoincore_rpc                   > JSON-RPC request: estimatesmartfee [1]
DEBUG bitcoincore_rpc                   > JSON-RPC request: getrawmempool [true]
DEBUG bitcoincore_rpc                   > JSON-RPC request: getmempoolinfo []
```

**Comment by nyxnor** [comment]
I mean, I've already been doing that, the problem is I don't want to miss anything and that method is prone to mistakes as if I don't do ever wallet action, maybe one command is not included in my list.

I've already tried that with Fulcrum and missed some commands. It also seems more logical to connect to electrum server as it requires less RPC calls and don't require wallet RPC calls.

Just to add to the debuggining process, on bitcoin.conf user `debug=rpc`, it shows accepted and denied calls per user.

**Comment by craigraw** [comment]
I'm a little confused - Sparrow does not connect to Bitcoin Core if an Electrum server like Fulcrum is configured. The commands that Fulcrum issues to Bitcoin Core are of course specific to that project, not Sparrow. 

Regarding Bitcoin Core connections via BWT, as I'm not the author of that project I can't offer better guidance than what I've suggested above, other than a search through https://github.com/bwt-dev/bwt for calls using the rust-bitcoincore-rpc library.

**Comment by nyxnor** [comment]
> I'm a little confused - Sparrow does not connect to Bitcoin Core if an Electrum server like Fulcrum is configured. The commands that Fulcrum issues to Bitcoin Core are of course specific to that project, not Sparrow.

I was comparing RPC calls of connecting Sparrow to an electrum server, which then already has a limited number of calls that don't involve wallet commands, to connecting Sparrow directly to bitcoin core rpc, which then has more commands that need to be allowed.

> Regarding Bitcoin Core connections via BWT, as I'm not the author of that project I can't offer better guidance than what I've suggested above, other than a search through https://github.com/bwt-dev/bwt for calls using the rust-bitcoincore-rpc library.

Closing the issue as completed, will see what I can get from upstream bwt.
