### ISSUE TITLE
Connect to other servers than asked.

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#71]
![image](https://user-images.githubusercontent.com/388716/110186406-22cf6f00-7de3-11eb-88dc-19c2b000508d.png)
Select lukechild

![image](https://user-images.githubusercontent.com/388716/110186416-2d8a0400-7de3-11eb-9c10-8b3405e129af.png)
tried to connect to lukechild

![image](https://user-images.githubusercontent.com/388716/110186419-324eb800-7de3-11eb-889f-1132c2788deb.png)
Switch to ???

Still doesn't sync anything

![image](https://user-images.githubusercontent.com/388716/110186466-5ca07580-7de3-11eb-8efe-9c079c7d7682.png)

And server select is page is disabled.

**Comment by 2pac1** [comment]
Test connection button? Try if few times

**Comment by craigraw** [comment]
> Switch to ???

Sparrow automatically switches to a different public server if it can't connect.

> And server select is page is disabled.

Just below the crop of this screenshot, there is an 'Edit Connection' button. Sparrow allows only one connection at a time for simplicity.

Public servers are provided as a public good, but have real resource costs and limitations, and come with no guarantees on availability. Consider installing your own node if you are struggling to connect.
