### ISSUE TITLE
Make "Find Mix Partner" window to highlight

### ISSUE THREAD

**Issue by rapidlab309** [sparrowwallet/sparrow#712]
Make it highlight, the very same as passphrase window is, when a request for Soroban communication is found.

**Comment by craigraw** [comment]
Not sure I follow - do you mean bring the window to the foreground?

**Comment by craigraw** [comment]
Implemented in f2b0f8ca. Unfortunately, this functionality is not well supported in Java and only works in OSX, bouncing the Sparrow icon in the taskbar if the application is not currently focussed. Hopefully wider support will be implemented in the framework at a later date.
