### ISSUE TITLE
connection refused on tails

### ISSUE THREAD

**Issue by tailssparrow** [sparrowwallet/sparrow#713]
i have installed sparrow on tails as per this tutorial 
https://sovrnbitcoiner.com/sparrow-wallet-and-tails/

however when i try to to connect i get an error saying 'Connection failed: Connect Error (Connection refused)'
this is when trying to connect to a public server such as bitcoin.lukechilds.co or any other of the available options. when i hit Test Connection i get an error 
'Could not connect:

Connection refused'
i am not very tech literate, so any help would be much appreciated
thanks!

**Comment by craigraw** [comment]
Tails requires all connections to go through Tor, so it is better to connect to a public server running as a hidden service on Tor. A community member runs a server here you can try (configure as a Private Electrum server in Server Preferences):

> rqcbvkan255wranepdrxqzwq2wexy6dpzpltsc7rir4epkz7itufwvqd.onion, Port 50021 for TCP and 50022 for SSL.

If you are concerned enough about privacy to be using Tails, definitely consider running your own node.

**Comment by sign21m** [comment]
Hi, 

I'm getting the same message 'Connection failed: Connect Error (Connection refused)' whilst trying to connect to private electrum server. Oddly it wasn't happening previously and nothing has changed. I can ssh into the node perfectly fine.

Thanks for any help at all!

**Comment by tailssparrow** [comment]
> Tails requires all connections to go through Tor, so it is better to connect to a public server running as a hidden service on Tor. A community member runs a server here you can try (configure as a Private Electrum server in Server Preferences):
> 
> > rqcbvkan255wranepdrxqzwq2wexy6dpzpltsc7rir4epkz7itufwvqd.onion, Port 50021 for TCP and 50022 for SSL.
> 
> If you are concerned enough about privacy to be using Tails, definitely consider running your own node.

this server also gives me a similar error
Could not connect:

Could not setup Tor

how do i go about setting up my own node?

**Comment by craigraw** [comment]
In Sparrow, make sure you have enabled the Use Proxy toggle, and set the Proxy URL to 127.0.0.1 and the port to 9050. 

Tails starts a Tor proxy externally when you connect it to the internet.

**Comment by craigraw** [comment]
> In Sparrow, make sure you have enabled the Use Proxy toggle, and set the Proxy URL to 127.0.0.1 and the port to 9050.

The guide linked above has now been updated with this information.

**Comment by tailssparrow** [comment]
hi craig, sorry to be a bother but i am having connection issues again. i was connecting fine a few weeks ago but now cannot connect
i have tried using the private server details
rqcbvkan255wranepdrxqzwq2wexy6dpzpltsc7rir4epkz7itufwvqd.onion, Port 50021 for TCP and 50022 for SSL.
with Proxy URL 127.0.0.1 and the port 9050
and usually get the following error

> Could not connect:
> 
> SOCKS: Host unreachable. Check if the proxy server is running.

if i connect just to public server with proxy toggled, it will occasionally connect and show a yellow toggle in the bottom right to indicate connection, but wallet transactions never load and funds cannot be sent

any help is greatly appreciated!

**Comment by tailssparrow** [comment]
currently i am able to connect via public server blockstream.info with proxy toggled, transactions have loaded. 
but again, it is inconsitent and i cannot figure out why it has connected this time and not others

**Comment by satoshi0770** [comment]
Can successfully connect to some public nodes.
Cant connect to the local core node running inside tails. Any idea what might help? Tried with cookie or with rpcuser/pass both send back refused to connect. Tried with/without proxy.
