### ISSUE TITLE
Didn´t receive funds

### ISSUE THREAD

**Issue by kld67** [sparrowwallet/sparrow#714]
Hello, I would love to ask for advice:
 I installed a sparrow wallet on my desktop and sent BTC onchain funds from Kraken to sparrow. The transaction was successful on Kraken´s side, and I have the transactions ID, and looked it up on mempool, where its also confirmed. I have the correct receiving/withdrawal address at hand which is still visible on both sides, Kraken and Sparrow as withdrawal/receiving address but no transaction was confirmed on Sparrow. Nothing. Not pending or  anything. Sparrow didn´t even "start" to recognise that there was a fund send to the receiving address shown in it´s receiving window. Does anyone have an idea where I might have overseen something or made a mistake? Thanks!!

**Comment by RequestPrivacy** [comment]
Sound like an issue with your connection or the server you're connecting to.

Do you run your own server? Maybe you could try to use a public one. You might want to consider to use the tor proxy or else the public server might connect your IP address with the requested address...

**Comment by kld67** [comment]
Thank you!! ... also for reminding me of using Tor...:I just tried the test connection using a public server and it seems to work, that´s what it says: "Connected to electrs-esplora 0.4.1 on protocol version 1.4 "

**Comment by RequestPrivacy** [comment]
Awesome! So Sparrow was able to pull the transaction data from the server? If so, you have do do the troubleshooting on your node packages github repo - although you also might find hints to your problems in the mentioned closed issues here.

**Comment by kld67** [comment]
YESS!! After testeing the connection sparrow needed to be restarted and now shows the transaction!!

**Comment by kld67** [comment]
...and I will also look up the closed issues!! Thanks again!!
