### ISSUE TITLE
Add Blockstream Jade to "Airgapped Hardware Wallet" List

### ISSUE THREAD

**Issue by bitcoinhelp** [sparrowwallet/sparrow#717]
Blockstream Jade will support QR/airgapped communications in the next firmware release.

Would be great to get Jade added to the "AIrgapped Hardware Wallet" list with the `scan` function.

Jade will display a `ur:crypto-account` for the user's selected path (m/84', m/49', m/48h/0h/0h/1h, m/48h/0h/0h/2h). This already works fine when simply scanning from the 'xpub/watch only' option - but again, would be helpful to have the option in that list

**Comment by craigraw** [comment]
Great news - will be happy to do so as soon as I can test it out. Let me know if there is a beta release I can test.

**Comment by craigraw** [comment]
Jade has been added as an airgapped keystore importer in 467b8349.

<img width="762" alt="Screenshot 2022-10-25 at 14 41 54" src="https://user-images.githubusercontent.com/862166/197775778-e1ddc187-b04d-41cf-9da4-40982a4b2bcb.png">
