### ISSUE TITLE
Connect hardware wallet

### ISSUE THREAD

**Issue by orangesurf** [sparrowwallet/sparrow#718]
When signing with a hot key in a multisig this pop up for a hardware wallet appears after clicking the sign button. After closing the pop up things work fine

![sparrow](https://user-images.githubusercontent.com/91332210/197595125-507a78c1-ad5d-4a22-a1ee-756315a7d0be.png)

**Comment by craigraw** [comment]
Is one of the other keystores in the multisig a connected hardware wallet?

**Comment by craigraw** [comment]
As of 29cd3217, Sparrow will avoid showing the USB signing dialog for watch only keystores in multisig wallets.
