### ISSUE TITLE
No display detected. Use Sparrow Server on a headless (no display) system

### ISSUE THREAD

**Issue by johnongit** [sparrowwallet/sparrow#721]
On a rock pi 4 (armbian) against the following binary https://github.com/sparrowwallet/sparrow/releases/download/1.7.0/sparrow-1.7.0-aarch64.tar.gz.

I cannot start terminal mode through ssh. Sparrow returns the following message.
No display detected. Use Sparrow Server on a headless (no display) system

**Comment by craigraw** [comment]
Use the Sparrow Server download a little further down the page. Probably you want https://github.com/sparrowwallet/sparrow/releases/download/1.7.0/sparrow-server-1.7.0-aarch64.tar.gz

**Comment by johnongit** [comment]
thx the server one is working.
