### ISSUE TITLE
SOCKS error when connecting to server with Tailscale IP

### ISSUE THREAD

**Issue by acronymy** [sparrowwallet/sparrow#723]
When connecting to Raspiblitz electrs with Tailscale 100.xx.xxx.xx address with Use Proxy toggled on, Sparrow gives the following error:

"Connection failed: Socket Error (SOCKS server general failure)

This does not occur when connecting with local IP or Zerotier 172.xx.xxx.xx address.

+shyfire131 stated in Telegram group:

"Wow OK, I figured it out. I'm connecting to my Electrum server over a Tailscale VPN, and Sparrow picks up the 100.blah IP address of the electrum server as an external address and then tries to connect to it over tor instead of directly, which is why it shows the SOCKS error."

**Comment by craigraw** [comment]
What is the desired behaviour? I assume it is for Sparrow to connect directly to the 100.xx IP, but use Tor for everything else? It is possible that someone wants to use Tor to connect to their node on a clearnet IP address, although I suspect that is not what was intended here.

It appears that IANA assigned the range 100.64.0.0/10 (i.e. IP addresses from 100.64.0.0 to 100.127.255.255) as a 'carrier-grade NAT' internal range in 2012. Does this match your Tailscale IP address?

**Comment by acronymy** [comment]
The desired behaviour is to connect to my Electrum server with Tailscale and through a tor proxy for external addresses at the same time - this is possible when using local IP or Zerotier IP. (172.23.xxx.xx)

"You can also configure a Tor proxy. Sparrow won’t use the proxy to connect to Bitcoin Core unless you specify a .onion address in the URL. But, it will use the proxy for all other external addresses, such as fetching exchange rates or [using Whirlpool](https://www.sparrowwallet.com/docs/mixing-whirlpool.html)."

This does work correctly for me if I use local IP (192.168.xx.xxx or Zerotier IP 172.23.xxx.xx. 
Tailscale performance/reliability is noticeably better than Zerotier for me when I am outside of my local network, Tor is the worst of the three. 

My Tailscale address is 100.90.xxx.xx

**Comment by craigraw** [comment]
Thanks for the info - as of 3faf8171 Sparrow will now consider the IP range `100.64.0.0/10` as referring to local network addresses, and not connect to them via Tor.

**Comment by craigraw** [comment]
@acronymy If you are up for trying an official build including this fix, I've just created one here: https://github.com/craigraw/beta/releases/tag/1.7.0-disable-assistive

**Comment by acronymy** [comment]
Am traveling at the moment but will be able to give it a go in a couple of days - thank you!




Nov 1, 2022, 06:33 by ***@***.***:

**Comment by acronymy** [comment]
Craig - any chance you could provide an rpm build?

https://github.com/craigraw/beta/releases/tag/1.7.0-disable-assistive

**Comment by craigraw** [comment]
Sure - added an .rpm to the binaries.

**Comment by acronymy** [comment]
Works perfectly now - external Tor proxy connects when I connect to my personal Electrum server using Tailscale 100.90.xxx.xx IP. (black icon, blue solid toggle, all wallets load correctly)

Very much appreciated, thanks again!

**Comment by craigraw** [comment]
Great, thanks for the feedback!
