### ISSUE TITLE
[Docs] Add "Mixing with Sparrow Terminal" to toggle menu

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#726]
In the documentation the chapter about [Mixing with Sparrow Terminal](http://sparrowa7io5pz6ud3ehqzosvepbxbxt2zphmkjsylp2zgxooko23pqd.onion/docs/mixing-whirlpool.html#mixing-with-sparrow-terminal) isn't incorporated into the quick access toggle menu reachable at the sides top.

**Comment by craigraw** [comment]
Thanks! Fixed.
