### ISSUE TITLE
BitBox02: Device not paired yet

### ISSUE THREAD

**Issue by marienvo** [sparrowwallet/sparrow#727]
I've reset the seed of my BitBox02; and all works well with the BitBox app on Android. All worked fine with Sparrow when using the first seed (before resetting). But when I try to use Sparrow again with the new seed on the BitBox02, I get this error message:

![image](https://user-images.githubusercontent.com/8506573/198877757-ad3cbb4c-f063-42c7-94a5-ee372000807a.png)

I tried 1.6.6, then updated to 1.7.0, and tried two different systems (laptop and desktop), all gave the same error.

**Comment by craigraw** [comment]
That error is coming from Bitbox via HWI, not from Sparrow itself. It appears something on the device has been reset to a pre-initialisation state. Have you tried running the BitBoxApp on a PC? It may be worth reaching out to Bitbox on this, as they will know more.

**Comment by marienvo** [comment]
Thanks! The BitBox02 desktop app asked me to verify a pairing code. After verifying, all works well again with Sparrow :)

Would be even nicer if any 3rd party (foss) app like Sparrow could handle this as well though; since I really do not like being dependent on apps from hardware wallets themselves (since they only seem to handle their own device most of the times).

**Comment by craigraw** [comment]
I agree, but these kind of integrations are proprietary and poorly documented, if at all.

Wallets that depend on QR codes for communication (and the Coldcard, to be fair) do not have these setup requirements and can be a better choice as a result.
