### ISSUE TITLE
Electrs not running 

### ISSUE THREAD

**Issue by lupn3** [sparrowwallet/sparrow#731]
I would first like to thank you again for your quick feedback on https://github.com/sparrowwallet/sparrow/issues/729 and add the following:

Now it says "Electrum not running" without further action. The command sudo journalctl -f -u electrs leads to:

sudo journalctl -f -u electrs
-- Journal begins at Tue 2022-11-01 05:40:59 GMT. --
Nov 01 13:21:04 raspberrypi electrs[2726027]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 01 13:21:04 raspberrypi electrs[2726027]: [2022-11-01T13:21:04.795Z INFO  electrs::db] closing DB at /mnt/hdd/app-storage/electrs/db/bitcoin
Nov 01 13:21:04 raspberrypi electrs[2726027]: Error: electrs failed
Nov 01 13:21:04 raspberrypi electrs[2726027]: Caused by:
Nov 01 13:21:04 raspberrypi electrs[2726027]:     0: sync failed
Nov 01 13:21:04 raspberrypi electrs[2726027]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 01 13:21:04 raspberrypi electrs[2726027]:     2: receiving on an empty and disconnected channel
Nov 01 13:21:04 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 13:21:04 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 01 13:21:04 raspberrypi systemd[1]: electrs.service: Consumed 8.091s CPU time.
Nov 01 13:22:04 raspberrypi systemd[1]: electrs.service: Scheduled restart job, restart counter is at 138.
Nov 01 13:22:04 raspberrypi systemd[1]: Stopped Electrs.
Nov 01 13:22:04 raspberrypi systemd[1]: electrs.service: Consumed 8.091s CPU time.

I would be infinitely grateful for any further advice.

**Comment by craigraw** [comment]
I actually don't know for certain, and but since this affects Electrs and not Sparrow I ask that you raise the issue at https://github.com/romanz/electrs rather than here.

My suspicion though is that there is something wrong with your Bitcoin Core, or the connection Electrs has to it.
