### ISSUE TITLE
[build.gradle] Change method of detecting the operating system during build

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#732]
New to Gradle but I try to understand how the build tool works.

While browsing the build.gradle file of sparrow I noticed the following line but I couldn't find the method call in the official gradle API: 

https://github.com/sparrowwallet/sparrow/blob/6481d83b0c13a6a134a9a1b8033ecec95a6c95f2/build.gradle#L11

After some research I found the following statement by gradle:

> [Avoid using internal Gradle APIs](https://docs.gradle.org/current/userguide/authoring_maintainable_build_scripts.html#sec:avoiding_gradle_internal_apis)
>
> Use of Gradle internal APIs in plugins and build scripts has the potential to break builds when either Gradle or plugins change.
> [...]
> Instead of `org.gradle.internal.os.OperatingSystem`, use another method to detect operating system, such as [Apache commons-lang SystemUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/SystemUtils.html) or System.getProperty("os.name").

It's also discussed here [https://stackoverflow.com/a/31443955](https://stackoverflow.com/a/31443955).

So with my 5% gradle knowledge this is potentially a minor issue and maybe you're fully aware / you've got other reasons to use this internal package...if so, feel free to close this issue.

**Comment by craigraw** [comment]
Yes, `org.gradle.internal.os.OperatingSystem` is internal, but there is still a lack of public API alternatives. So, we wait to see if Gradle ever officially supports detection of the current operating system in a public API. I'm not concerned though - the Gradle version is explictly defined in the Gradle wrapper, which is the recommended way to interact with Gradle/Sparrow. If the internal API is removed in a future Gradle release this issue can be handled then.
