### ISSUE TITLE
Cannot Use Sparrow-server on Raspberry Pi OS 64-Bit

### ISSUE THREAD

**Issue by BTCNautilus** [sparrowwallet/sparrow#733]
I was hoping to get sparrow-server up on a spare rpi4 I have laying around. It was running a fresh install of 64bit Raspberry Pi OS Lite at the time, so I just had a go at running it there. For whatever reason, I can’t get it to work, either with the .deb or with the .tar.gz. 

Steps to reproduce on Raspberry OS 64 bit, fresh install. Only installed service is Tailscale.

- Download sparrow-server-1.7.0-aarch64.tar.gz
- Extract with $ tar -xzf sparrow-server-1.7.0-aarch64.tar.gz
- Navigate to Sparrow/bin
- bash Sparrow

Error message:
Sparrow: Sparrow: cannot execute binary file

The .deb gave some kind of dependency error the first time I ran it, and after that each attempt to fix gives me some errors, and the same message when I try to run the binary. The errors in installation aren't helpful:

dpkg: error processing package sparrow (--configure):
 installed sparrow package post-installation script subprocess returned error exit status 3

and

Errors were encountered while processing:
 sparrow
E: Sub-process /usr/bin/dpkg returned an error code (1)

The original dependency issue I saw I can't get to show again, so not sure what to report there. 

Any ideas?

**Comment by RequestPrivacy** [comment]
Can you confirm that `./Sparrow/bin/Sparrow` isn't working for you? I'm on the same hardware, running the same OS and downloaded the same tar file and it works...

What is `uname -a` saying?

**Comment by BTCNautilus** [comment]
Well, it seems I simply didn’t know how to launch the app. ./Sparrow/bin/Sparrow works from the tar.gz

I suppose I can run it that way.

Probably not critical for me personally to chase the .deb issue. But happy to troubleshoot if it’s helpful.

**Comment by BTCNautilus** [comment]
Closing for now as my immediate problem is solved

**Comment by craigraw** [comment]
If you are keen to try figure out the problem with `dpkg`, we'll need to see what the original dependency error was:

> The .deb gave some kind of dependency error the first time I ran it

It may be possible to get this by removing sparrow using dpkg and then reinstalling it:
```
sudo dpkg -r sparrow-server_1.7.0_arm64.deb
sudo dpkg -i sparrow-server_1.7.0_arm64.deb
```

**Comment by BTCNautilus** [comment]
I removed it earlier after getting things going with the tar.gz. But hadn't tried again. 

Upon reinstallation, this is what I saw.

dpkg: dependency problems prevent configuration of sparrow:
 sparrow depends on xdg-utils; however:
  Package xdg-utils is not installed.

> dpkg: error processing package sparrow (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  sparrow

I installed xdg-utils, then re-attempted the install with:

sudo dpkg -i sparrow-server_1.7.0_arm64.deb

But got a different error.

> xdg-desktop-menu: No writable system menu directory found.
> dpkg: error processing package sparrow (--install):
>  installed sparrow package post-installation script subprocess returned error exit status 3
> Errors were encountered while processing:
>  sparrow

**Comment by craigraw** [comment]
Thanks for this. The sparrow-server* debs should not have a dependence on `xdg-utils` (or `xdg-desktop-menu`) which are desktop-related package utilities. Fixed in b7992ae9.

**Comment by haromz** [comment]
Hi @craigraw, I'm unable to run the sparrow server on a raspberry pi 4.

If I untar the standalone package, I get the following error: 
`bash: ./Sparrow/bin/Sparrow: cannot execute binary file: Exec format error`

If I try to install the .deb file with `dpkg -i`, I get this error: 
`dpkg: error processing archive sparrow-server_1.7.1-1_arm64.deb (--install):
 package architecture (arm64) does not match system (armhf)`

My `lscpu` command output is:
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

Not sure what's going on, what I'm missing?

**Comment by haromz** [comment]
It seems you can play with the package architecture on the `dpkg` command, as written on this [blog](https://monicagranbois.com/blog/raspberrypi/error-package-architecture-arm-does-not-match-system-armhf/).

So I run the following command:
`sudo dpkg --force-architecture -i sparrow-server_1.7.1-1_arm64.deb`

Output:
```
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: package architecture (arm64) does not match system (armhf)
Selecting previously unselected package sparrow:arm64.
(Reading database ... 40703 files and directories currently installed.)
Preparing to unpack sparrow-server_1.7.1-1_arm64.deb ...
Unpacking sparrow:arm64 (1.7.1-1) ...
dpkg: dependency problems prevent configuration of sparrow:arm64:
 sparrow:arm64 depends on libc6.
 sparrow:arm64 depends on zlib1g.

dpkg: error processing package sparrow:arm64 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 sparrow:arm64
```
 
I checked the /opt/sparrow dir to see if it installed something, the executable is there but I can't run it:
```
/opt/sparrow/bin $ ./Sparrow
-bash: ./Sparrow: cannot execute binary file: Exec format error
```

**Comment by haromz** [comment]
I think I'm running the 32 bit version of the operating system and that's the issue. At least I documented my problem and found the root cause by my own :))

**Comment by craigraw** [comment]
> I think I'm running the 32 bit version of the operating system and that's the issue.

Correct, the `armv7l` indicates the 32-bit arch.
