### ISSUE TITLE
Recent Transaction Not Appearing

### ISSUE THREAD

**Issue by 712Jefferson** [sparrowwallet/sparrow#739]
Last night, I used Sparrow to receive funds from my exchange wallet to my air-gapped Coldcard hardware wallet, as I always do.  Normally, I can see the transaction come in via Sparrow's UI a minute or two after initiating the send from my exchange wallet and then watch as it's fully confirmed over the course of an hour or so.

Last night, however, I received an email notice from the exchange after initiating the send that the transaction was being delayed for 72 hours as a security measure unless I completed a KYC verification process.  I went ahead and completed their verification process and was notified that it was successful and that the transaction would be processed.  It's now about 24 hours later, however, and there still is no transaction showing in my Sparrow wallet.  On Blockchain Explorer, I can verify that indeed the transaction was processed and that the particular wallet derivation I used from Sparrow last night contains the sent funds... just no record of it anywhere in the actual Sparrow UI.  I double checked to make sure that the wallet address used was accurate.

Any idea what might be going on and/or how to troubleshoot?  I just upgraded to v1.70 but the issue still persists.  Thank you for your time.

**Comment by craigraw** [comment]
You can try refreshing the wallet (View menu) although the real question is why your connected server did not notify Sparrow of the new transaction. I don't know what server you are using to comment further though. 

BTW, support requests like these are better handled in the Telegram group https://t.me/SparrowWallet.
