### ISSUE TITLE
KeystoreController `derivationMatchesAnotherScriptType()` check prevents wallet import

### ISSUE THREAD

**Issue by jimbojw** [sparrowwallet/sparrow#740]
When setting up a Software Wallet Keystore, the dialog permits specifying a custom derivation path. However the wallet Settings tap will not allow a derivation path if it matches a default for another script type. The help icon explains as much:

> The derivation path to the xpub from the master private key.
> For safety, derivations that match defaults for other script types are not valid.

This feature is enforced in the `KeystoneController.java`, line 150, where it checks `derivationMatchesAnotherScriptType()`:

```java
derivation.textProperty().addListener((observable, oldValue, newValue) -> {
    if(KeyDerivation.isValid(newValue) && !walletForm.getWallet().derivationMatchesAnotherScriptType(newValue)) {
        keystore.setKeyDerivation(new KeyDerivation(keystore.getKeyDerivation().getMasterFingerprint(), newValue));
        EventManager.get().post(new SettingsChangedEvent(walletForm.getWallet(), SettingsChangedEvent.Type.KEYSTORE_DERIVATION));
    }
});
```

And on line 249 in the setup for the derivation validator:

```java
validationSupport.registerValidator(derivation, Validator.combine(
        Validator.createEmptyValidator("Derivation is required"),
        (Control c, String newValue) -> ValidationResult.fromErrorIf( c, "Derivation is invalid", !KeyDerivation.isValid(newValue)),
        (Control c, String newValue) -> ValidationResult.fromErrorIf( c, "Derivation matches another script type", walletForm.getWallet().derivationMatchesAnotherScriptType(newValue))
));
```

Unfortunately, this feature prevents importing wallets created by other software which does not have this restriction. For example, bisq uses derivation path `m/44'/0'/1'` for its [native SegWit wallets](https://bisq.wiki/Wallet#Understanding_the_Bisq_Wallet). The KeystoreController derivation check appears to prevent importing these wallets into Sparrow.

Note: The KeystoreController check does not stop non-standard xpub/zpub entry or use. It is possible to paste the zpub that bisq presents and import it as a watch only wallet in Sparrow. The form field for the derivation path is outlined red to show the problem, but the Apply button is enabled, and clicking it works to initialize the watch only wallet.

Recommendation: Offer a checkbox to allow the user to override this check in special circumstances.

**Comment by craigraw** [comment]
> Recommendation: Offer a checkbox to allow the user to override this check in special circumstances.

You can disable derivation path validation in the Preferences.

**Comment by craigraw** [comment]
@kiwihodl I don't think it's worth complicating the UI in this way. Further, this is intended friction - reusing derivation paths across different script types risks the reuse of public keys and loss of privacy, apart from the issues that result from trying to restore wallets with non-default configuations.
