### ISSUE TITLE
[FEATURE + BUG]

### ISSUE THREAD

**Issue by AsiaLeoneCvr** [sparrowwallet/sparrow#742]
Feature - MacOs: Would be cool if once "minimized to system tray" - menu bar - the sparrow icon on the dock disappear, appearing again if the app is open. In line with the standard behaviour on MacOs. 

Bug - MacOs. If the app is "minimized to system tray" - menu bar - and there is any app open and active, a click on the sparrow icon in the menu bar will open a Sparrow in the background. In line with the standard behaviour of MacOs, the windows should be opened in foreground.

**Comment by craigraw** [comment]
> Feature - MacOs: Would be cool if once "minimized to system tray" - menu bar - the sparrow icon on the dock disappear

Unfortunately dynamically hiding the dock icon does not appear to be supported: https://bugs.openjdk.org/browse/JDK-8092032

>  In line with the standard behaviour of MacOs, the windows should be opened in foreground.

Implemented in 7e779519.
