### ISSUE TITLE
[Feature] Mix to cold wallet without requiring device to stay connected

### ISSUE THREAD

**Issue by nurviro** [sparrowwallet/sparrow#747]
Leaving a hardware wallet connected during mixing presents a security risk. Perhaps an appropriate amount of segwit addresses could be pre-fetched from the hardware wallet at the start of mixing, and then allow the device to be unplugged. UTXOs would be mixed to those addresses, and if we run out of addresses: stop mixing? I could certainly be missing something here but wanted to float the idea.

**Comment by craigraw** [comment]
You don't need to leave the device connected while mixing out. It only needs to be connected to sign transactions spending from the wallet. Sparrow has everything it needs to mix to the hardware wallet once it has been created.
