### ISSUE TITLE
Unit Format not working

### ISSUE THREAD

**Issue by tychsen** [sparrowwallet/sparrow#749]
It seems that the Unit Format function is broken.

Switching between the two formats does not have any effect.

(Sparrow 1.7.0 on Mac)

<img width="383" alt="image" src="https://user-images.githubusercontent.com/42609900/201993610-ca47c011-ef83-4dd3-8f76-f77d53c06dac.png">

**Comment by craigraw** [comment]
Thanks, already fixed in https://github.com/sparrowwallet/sparrow/commit/6481d83b0c13a6a134a9a1b8033ecec95a6c95f2.
