### ISSUE TITLE
Windows version 1.7.1 connects to Core and finds old wallet but with no UTXOs

### ISSUE THREAD

**Issue by icheyne** [sparrowwallet/sparrow#750]
I just installed 1.7.1 on Windows. (I had been running a dev build from @craigraw as we were troubleshooting a java bug).

It will not find my old wallet on Bitcoin core. I backed up the wallet and followed the instructions in #724 , but still no UTXOs in Postmix. 

An empty wallet with the right name opens. Core scans but finds nothing. After a few seconds it scans again.

A paynym that I connected to and sent bitcoin to is visible.

I then connected to a public Electrum server and saw my UTXOs.

**Comment by craigraw** [comment]
I'd recommend when you start using multiple wallets like this that you install an Electrum Server like Fulcrum or Electrs. The architecture is simply much more flexible for Sparrow to work with.

That said, is there anything in the log file that may help?

**Comment by icheyne** [comment]
1. Run Bitcoin Core
2. I deleted "C:\Users\iain\AppData\Roaming\Bitcoin\wallets\sparrow"
3. I cloned the repository and ran the latest Sparrow
4. Disconnected the electrum server
5. Switched to Core
The output is here:
[output.txt](https://github.com/sparrowwallet/sparrow/files/10045387/output.txt)
It seems to indicate a bad block, but I've done nothing and there's nothing showing in the UI?

**Comment by craigraw** [comment]
Unfortunately one of the other downsides of using Bitcoin Core is that if you delete your `wallet.dat` file and your wallet birthday is before your earliest pruned date, you will have to redownload the blockchain to recreate the wallet file. Looking at the Core log, it's probable that's the case here.
