### ISSUE TITLE
This is not an issue but a question

### ISSUE THREAD

**Issue by SequoiaB** [sparrowwallet/sparrow#751]
I don't really comprehend how the software works so here's the question:

Is my wallet in danger if my pc is infected by a virus?
So the question is: is the private key is stored in the sparrow file?

**Comment by icheyne** [comment]
Yes
Yes

**Comment by SequoiaB** [comment]
> > Is my wallet in danger if my pc is infected by a virus?
> 
> 
> 
> It depends. If your wallet is protected by a strong password, it is very difficult for a virus to get your private keys. Sparrow wallet files use strong encryption. I have never had a report of the private keys in Sparrow being compromised.

Okay thanks, this was exactly what I was looking for

**Comment by craigraw** [comment]
> Then if I use sparrow as a cold wallet I can even delete the real file and just keep a watch only wallet to deposit, so no risks involved right?

Yes, so long as you have the seed words stored somewhere safe.
