### ISSUE TITLE
[Bug -Sparrow Server] Unresponsive test connection page

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#754]
#### Config
- Pi4 aarch64
- running unpacked [Sparrow Server 1.7.1 aarch64 ](https://github.com/sparrowwallet/sparrow/releases/download/1.7.1/sparrow-server-1.7.1-aarch64.tar.gz)

#### Steps to reproduce
- Have a connection to a Private Electrum server
- If Sparrow is started verify it connects successfully to the server
- Go to -> Preferences -> Server -> Edit
- Note Private Electrum is still applied as Server type
- Click continue
- On next page click \<Test\>
- Test page is shown but if unable to connect, user is stuck on test page (no way to move to the "buttons" via arrow keys, no reaction to clicking with mouse on \<Back\>\<Test\>\<Done\>)
- Sometimes the same for successful connection test
- User has to exit Sparrow e.g. via ^C

#### Expected behavior 
Being able to interact with the 3 mentioned buttons to cancel or proceed from the test page onward.

**Comment by emeklund** [comment]
I'm having a similar issue running Sparrow 1.7.1 on Linux and connecting to a Private Electrum Server. Sparrow keeps trying to connect without success. I haven't changed any settings since it was running properly. The message is "IO Error (Cannot connect to hidden service)."

The test function seems to operate - it just won't connect.

I welcome suggestions!

**Comment by craigraw** [comment]
> Test page is shown but if unable to connect, user is stuck on test page (no way to move to the "buttons" via arrow keys, no reaction to clicking with mouse on <Back><Test><Done>)

Have you tried the Tab key? The connection attempt is done in an entirely different thread, so the UI should be responsive.

**Comment by RequestPrivacy** [comment]
> The message is "IO Error (Cannot connect to hidden service)."

I think this is rather an issue with your server backend and its hidden service. Alternatively could be a tor related issue. Try and restart tor on both machines @emeklund.

> Have you tried the Tab key?

Was the solution. I was so accustomed to being able to move just with arrow keys that I didn't think of the tab key. Might be an issue for others too?! Can you pre-select one of the options (`<Back><Test><Done>`) so that no tabulator is  needed to start navigating?

**Comment by craigraw** [comment]
> Can you pre-select one of the options

Added in 3cbe8d15 - the `<Done>` button takes initial focus.

**Comment by emeklund** [comment]
Thanks for your feedback, @RequestPrivacy
