### ISSUE TITLE
[Bug - Sparrow Server] Cancel on wallet creation not working properly

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#755]
#### Config
- Pi4 aarch64
- running unpacked [Sparrow Server 1.7.1 aarch64 ](https://github.com/sparrowwallet/sparrow/releases/download/1.7.1/sparrow-server-1.7.1-aarch64.tar.gz)

#### Steps to reproduce
- Start Sparrow 
- Select `<Wallets>` -> `<Create Wallet...>`
- On naming page click `Cancel`

#### Expected behavior
Bring user back to `Main` or `Wallets` page

#### Encountered behavior
Continues to `Create Wallet | Choose the type of wallet` page

**Comment by craigraw** [comment]
Thanks, fixed in 47f7b887.
