### ISSUE TITLE
Signing error with Trezor T and Multi-sig 2-of 3

### ISSUE THREAD

**Issue by wbrussell** [sparrowwallet/sparrow#756]
Using legacy P2SH multi-sig 2of3 wallet in v1.7.1 sparrow on Linux.  Using Trezor model T to sign with latest firmware 2.5.3.

When signing with Trezor I get the error "Data Error:  Multisig field provided but not expected".

Not sure if this is a Trezor error or Sparrow, but I can sign fine using Electrum on the same PC using same wallet.

**Comment by craigraw** [comment]
This is actually an HWI issue. It has been reported and fixed, but HWI has not yet had a release with the fix. See https://github.com/bitcoin-core/HWI/issues/624.
