### ISSUE TITLE
Sparrow terminal crashes.

### ISSUE THREAD

**Issue by michaelsmolka** [sparrowwallet/sparrow#758]
Hi, as already mentioned few minutes ago 
on telegram:
just tried to setup sparrow terminal. I can open wallet file, access the settings, but when I try to open either Transactions or UTXOs, it crashes showing „Exception in Application init method“ in the terminal window.
Tried several wallet files, always the same behaviour.
I run it on a rapberry pi (raspiblitz).

Any idea what to do to solve this?

[sparrow.log](https://github.com/sparrowwallet/sparrow/files/10057023/sparrow.log)

**Comment by michaelsmolka** [comment]
Thanks. Now I can open it.
But I have another issue: When i choose "Start Mixing", i see "Starting Mixing..." for a second or two, after that ist goes back to "Start Mixing".
The "Mixing To" wallet is configured and opened.

[sparrow.log](https://github.com/sparrowwallet/sparrow/files/10058115/sparrow.log)

**Comment by craigraw** [comment]
You are getting the response of "Connection refused" on all outgoing connections (rate API calls, Whirlpool calls). Looks like something is misconfigured on your node network-wise.

**Comment by michaelsmolka** [comment]
Thank you.
That's strange. I double checked the settings. They are exactly the same as on sparrow desktop. And there everything works fine.
Do you have any tip for me where to look in my raspiblitz configuration?
Unfortunately I'm not really tech savy, especially not on Linux and the comand line.

**Comment by craigraw** [comment]
I would check the proxy settings, since all external calls are made through the proxy if configured.
