### ISSUE TITLE
Scanning signed transactions from Jade QRs is very difficult

### ISSUE THREAD

**Issue by eliasnaur** [sparrowwallet/sparrow#760]
With a recent firmware, Jade is now able to run in stateless mode comparable to a SeedSigner. It can scan a SeedQR and a PSBT from Sparrow through the camera. However, I've yet to succeed in making Sparrow scan the signed transaction back from the animated QR code displayed on the Jade.

My system is a Macbook Pro M1 12.6.1, I'm using the laptop camera. From my untrained eye, it seems that the QR is too small at a distance, but out of focus at closer distances. Perhaps an auto-focus or just focusing the camera to closer point would help.

Scanning signed transactions from a SeedSigner is easy.

**Comment by craigraw** [comment]
There is unfortunately not much Sparrow can do about this - it is a problem that Jade suffers from its screen capabilities. Macbook cameras are pretty good, but there is no control over their focus. Changing the lighting the in room can help.
