### ISSUE TITLE
Becomes very slow, 100% cpu usage, after trying to reconnect

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#761]
1.7.1
Sparrow has been left on of for 2 days, The connection toggle was slow blinking, I clicked it to trigger a reconnect.

Every part of the wallet would take about 20 seconds to change.

This lasted 12 minutes of 100% CPU, after which sparrow was responsive again.

The post mix history show a large 3min gap between last activity and "Finished Loading"

I suspect the app was struggling to process the sync so much that the UI was not responsive.

After this long process, I notice the network toggle looks to be blinking extremely fast at random. 
![sparrow toggle](https://user-images.githubusercontent.com/388716/203898427-cd64738d-ae14-49b0-947e-44cc88a13850.gif)

I then disconnected and toggled back on, The app cannot achieve connection to any server.
Log (non-verbose) do not show anything useful like connection failed attempts.

Issue ends in the same way as https://github.com/sparrowwallet/sparrow/issues/716

**Comment by craigraw** [comment]
Please can you rather add to #716 - it's difficult to keep track with a new issue every time. Closing this one off.
