### ISSUE TITLE
Question: Is Sparrow Terminal going to be daemonized?

### ISSUE THREAD

**Issue by s373nZ** [sparrowwallet/sparrow#762]
Do I need to keep an SSH session open to my server and the terminal application open in order to keep my mixing going using Sparrow Terminal? I find the prospect of "set it and forget it" attractive for mixing and was hoping this was the intent for Sparrow Terminal.

Current documentation doesn't seem to address this directly, so I'm curious if I'm missing some info, or whether it is on the roadmap...

**Comment by RequestPrivacy** [comment]
Yeah I think it was mentioned somewhere that there will be a daemon.

Until then you could use a terminal multiplexer like tmux or screen. Both provide the functionality to start terminal sessions in your machine which keeps running even if you log out of the current ssh session (i.e. they are persistent in the background).

SSH normally into your machine and if you are on linux e.g. ubuntu
```
sudo apt update && sudo apt upgrade -y && sudo apt install tmux
```
Start a new session named sparrow
```
tmux new -s sparrow
```
You will see a "new" terminal (to identify it worked by default you should see a green bar at the bottom) which is persistent as long as your machine doesn't reboot.  

In that terminal start Sparrow in terminal mode like you always did.

If you want to detach from the persistent terminal just press `Ctrl+b` and immediately afterwards `d` for detach. You will be back to the "original" terminal. Now you can close your ssh session and Sparrow will still run in the background terminal of your remote machine.

If you want to re-attach to Sparrow at a later date, ssh into your machine again and type
```
tmux a -t sparrow
```
Make sure you use the same name as in the `tmux new -s NAME` command above.

tmux will bring you back to Sparrow where you left it before detaching. To be clear, if you have Sparrow mixing, it will continue to mix, so detaching and re-attaching doesn't "pause" Sparrow just do what the words suggest: attach or detach your current terminal to the "sparrow session" so you can interact with it again via your terminal!

tmux is a neat tool for all bitcoin related terminal things. You might want to search the web or youtube for a more thorough understanding...

**Comment by rapidlab309** [comment]
That's an awesome guide for new users, thanks for writing this!

**Comment by InnocuousFinch** [comment]
@s373nZ The use of tmux and Sparrow Terminal is also covered in this guide: https://sovrnbitcoiner.com/an-iphone-enters-the-poolside-chat/

**Comment by craigraw** [comment]
The answer is yes - Sparrow Terminal is useful in its own right, but it's primarily intended as a configuration utility for running Sparrow as a server daemon - coming in a future release.

That said, I use Sparrow Terminal with `tmux` regularly.
