### ISSUE TITLE
[Feature - Sparrow Server] Add current block height

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#764]
Maybe I haven't identified where I can find the current block-height in Sparrow Server 1.7.1 but it would be nice to have the information displayed at the upper right hand corner (behind the `Connected` status).

**Comment by rapidlab309** [comment]
Hover your mouse on the connection indicator on bottom right corner. It will display your connection's block height.

**Comment by RequestPrivacy** [comment]
In the `server` version?

**Comment by rapidlab309** [comment]
![Untitled](https://user-images.githubusercontent.com/96245140/204150649-30e138cf-cb02-48de-8700-734c8b0b6b4a.jpg)

**Comment by InnocuousFinch** [comment]
I believe @RequestPrivacy is referring to Sparrow Terminal.

**Comment by rapidlab309** [comment]
Facepalm. Long day.

**Comment by craigraw** [comment]
Added in ff90a2c3.
