### ISSUE TITLE
No option for "offline" wallet as Java packages complain and stop if no internet access

### ISSUE THREAD

**Issue by genechuah** [sparrowwallet/sparrow#766]
Cold-storage implementation, no go?
Linux build -- Java packages error out if no internet access.

**Comment by craigraw** [comment]
Can you explain what you mean here? Sparrow certainly supports offline usage. Building Sparrow does naturally require the source code and dependencies to be retrieved though.

**Comment by genechuah** [comment]
Hi Craig,

Thanks for your response and sorry for my lack of specificity.

After the initial build on Debian, I can use it (although I can't click on any of the menu items, so I have to use the Alt key to get there, but that's a separate issue).

However if I take the system offline, then on subsequent launches, sometimes the Java packages it's built on try to connect online but complain that they can't, then stop, so the app never launches.

I'll try to capture the exact messages when they happen again so that I can give you more details.

Thank you.

**Comment by genechuah** [comment]
@craigraw here are the screenshots. Again, these are errors NOT from the initial build (which has already been done) but subsequent launches of the app. Errors due to being offline :
![image](https://user-images.githubusercontent.com/19858965/205503607-d653e0be-7d3d-4be6-a276-40b63f888789.png)
![image](https://user-images.githubusercontent.com/19858965/205503609-ac99f110-d2eb-4846-8fff-db198b29c260.png)

**Comment by craigraw** [comment]
Looking at the screenshot, I'm not sure where the path `src/sparrow/sparrow` comes from.

As noted in https://github.com/sparrowwallet/sparrow/blob/master/docs/reproducible.md, a build will appear in `build/jpackage/Sparrow` - you would run it with `build/jpackage/Sparrow/bin/Sparrow`.

Re the menu items, what window manager are you using?

**Comment by genechuah** [comment]
@craigraw thank you, that seems to have solved the issue. 
Mouse clicks still don't work for top-level-menu items -- they only flicker on/off once per click. But that's another issue and I think I will try something else to solve that. 
Thanks for your help!

**Comment by craigraw** [comment]
Re menus, see #170.

Closing this off.
