### ISSUE TITLE
Derivation path not allowed - cannot import CoolWallet S BTC Paths

### ISSUE THREAD

**Issue by jordan-public** [sparrowwallet/sparrow#767]
## How to reproduce:
1. Create new wallet, connect Ledger (any) and Import Derivation path m/44'/0'/0' when connecting
2. Select "Script Type": "Nested Segwit (P2SH-P2WPKH)"
3. Problem: "Apply" button is greyed as the "Derivation" field has red border. Apparently this is a standard path for another Script Type. However, (right or wrong) this makes it impossible to use Ledger to reproduce BTC addresses that CoolWallet S uses. 

## Description of CoolWallet S address derivation path:
Description link: [How are CoolWallet S/Pro BTC addresses derived?](https://help.coolwallet.io/article/890-how-are-coolwallet-s-pro-2nd-generation-btc-addresses-derived)

## Suggestion
Instead of making it impossible to use such path, warn the user, but allow them to proceed anyway.

**Comment by jordan-public** [comment]
Please ignore - in preferences "Validate Derivations" can be turned off. Maybe you can just warn the user with:

"Please turn off "Validate Derivations" in preferences if you want to do this."

I spent a couple of hours before I discovered this option (not obvious).

**Comment by craigraw** [comment]
Added to the derivation path help tooltip in 0e26f8fc:

<img width="620" alt="Screenshot 2022-12-03 at 07 41 09" src="https://user-images.githubusercontent.com/862166/205426186-4eaababf-88e7-47e2-a925-22996274e24a.png">
