### ISSUE TITLE
Can't scan for hardware wallets

### ISSUE THREAD

**Issue by Morning24** [sparrowwallet/sparrow#769]
Sparrow isn't able to scan for hardware wallets. If the 'scan'-button is hit Sparrow shows 'scanning' and nothing else happens.
Problem is the same with BitBox02 and Ledger Nano S, both hardware wallets work fine with their native software.
Due to a successful test on another Laptop it seems to be a problem of the specific combination of Sparrow wallet and my (self build) computer.
All softwares are up to date (I run on Windows 10 home), I tested with and without USB-cable. The settings of my pc and the tested laptop (also W10 home) are identical (defender/system security...), no problems in device-manager.

In the Sparrow Wallet telegram channel someone instructed me to delete hwi folder -> no change.
Then I was supposed to run 'hwi-xxx enumerate' on command line in hwi folder but the cursor only jumps in the next row and stays there blinking.
He said that that's the problem, something on my system appears to be hanging when queried. I disconnected all USB-peripherals except keyboard and mouse, deleted hwi folder again and gave it another try -> same as before.

Something seems to prevent hwi from scanning for USB devices...

**Comment by craigraw** [comment]
Thanks for this, but as our testing determined, it's actually a problem with HWI, the utility Sparrow uses to communicate with connected USB devices. So I can't help with this directly - it needs to reported to the HWI project.

I suggest the following:
- Download the latest HWI release (which Sparrow uses, but just to be sure): https://github.com/bitcoin-core/HWI/releases/tag/2.1.1 (see [hwi-2.1.1-windows-amd64.zip](https://github.com/bitcoin-core/HWI/releases/download/2.1.1/hwi-2.1.1-windows-amd64.zip))
- Extract the .zip and attempt to run the extracted `hwi.exe` on the command line
- If the same behaviour occurs, report it at https://github.com/bitcoin-core/HWI/issues

**Comment by Morning24** [comment]
Oh yes, that's exactly what you told me on telegram. But unfortunately I didn't read it proper and thought you meant an issue on Sparrow, sorry for that! 
It shows the same behaviour, I will report it to HWI-issue then...

**Comment by Morning24** [comment]
To bring this to an end:

I was told to check if anything is listening on ports 2222, 21324, 11044 or 9999.
And realy, I found out that port 9999 was listed several times with "aakore.exe" wich is a process from Acronics True Image. After uninstalling this program sparrow finaly found my BitBox02!
