### ISSUE TITLE
Mix Selected button not present on UTXOs tab

### ISSUE THREAD

**Issue by ntosme** [sparrowwallet/sparrow#771]
After transferring coins into a new software hot wallet, there doesn't appear to be a way to use Mix Coins after selection on the UTXOs page. The wallet was created with Taproot; is this type not yet supported by whirlpool?

**Comment by ntosme** [comment]
After some digging, I found the following comment:

sparrow/src/main/java/com/sparrowwallet/sparrow/whirlpool/WhilpoolServices.java: 165
`                && wallet.getScriptType() != ScriptType.P2TR    //Taproot not yet supported`

Also in "Preparing the wallet" in the Whirlpool section of the docs it does actually mention that it's not supported.

**Comment by craigraw** [comment]
> Does that factor into mixing being available or not?

It does not. 

I suggest recreating your wallet from the seed words, following the Quick Start guide in the docs.
