### ISSUE TITLE
[Feature Request] Import/Export UTXO Labels

### ISSUE THREAD

**Issue by heredia21** [sparrowwallet/sparrow#772]
If we can get the ability to backup and restore UTXO labels I think it will really help when installing Sparrow on a separate machine. Will allow us to keep our UTXOs organized as well.

**Comment by craigraw** [comment]
I agree! Trying to do this right and have a BIP standard, but progress is slow: https://github.com/bitcoin/bips/pull/1383

Fwiw though, you can just copy Sparrow wallet files across, even with different OSes.

**Comment by heredia21** [comment]
Interesting. I was not aware of this. I was expecting it to be part of "Open Wallet". Copying the ~/.sparrow directory acts differently than using the open wallet option in the dropdown menu? I only see a config file and sparrow.log in there. Need to test it some more.

**Comment by craigraw** [comment]
I'm unclear what you mean. Note that Sparrow home differs on Windows (it is `~./sparrow` on Linux and OSX, see FAQ). The `wallets` folder should be contained inside once you have created a wallet.

**Comment by Transisto** [comment]
Funny I was just onto that page, https://bitcointalk.org/index.php?topic=5411159.0

There should definitely be a standard to import and export utxo labels.

**Comment by craigraw** [comment]
Sparrow v1.7.2 has been released with wallet label export as per BIP329.
