### ISSUE TITLE
Add Blockstream Jade option to multisig 'Export' device list

### ISSUE THREAD

**Issue by bitcoinhelp** [sparrowwallet/sparrow#773]
In the next Jade firmware version, we will support registering a multisig wallet on device using the camera. Can we get a Jade option added to the "Export" list for multisigs? Using the same format as "keystone" will be fine for example, Jade can read that.

Somewhat related, is there a way to rename the multisig from Sparrow? When scanned by Jade, it will automatically be named "Deposit" - not sure where Sparrow is adding that name from and it's also in the export file

**Comment by craigraw** [comment]
> Can we get a Jade option added to the "Export" list for multisigs?

Happy to do so if I can test it first.

> When scanned by Jade, it will automatically be named "Deposit" - not sure where Sparrow is adding that name from and it's also in the export file

Can you describe the steps you followed here? "Deposit" is simply the name of the first (0th) account in a Sparrow wallet, but I'm not sure which export file you're referring to.

PS: This is unrelated, but I've had a query about using using a personal .onion pin server with Jade. Does HWI support this?

**Comment by bitcoinhelp** [comment]
> Happy to do so if I can test it first.
Sound great, I'll ping you here when the release is out so you can try it
> Can you describe the steps you followed here? "Deposit" is simply the name of the first (0th) account in a Sparrow wallet, but I'm not sure which export file you're referring to.
Sorry please ignore this, I just realized you can rename the account (i.e. "deposit") from the side panel....
> PS: This is unrelated, but I've had a query about using using a personal .onion pin server with Jade. Does HWI support this?
I believe so but I'll have one of our devs confirm, will get back shortly

**Comment by JamieDriver** [comment]
Hi, 
I'll try to assist re: personal pin server.  
Jade supports personal pinservers, and while HWI should be able to use standard tls/https routes, I don't think it handles tor/onions.

There is a call on Jade to setup the pinserver details to use - eg. tls url (if desired), onion, server-pubkey, etc.
I assume this would have already been done by the user already   ?  But of course it's the companion application that actually has to handle the networking side, and HWI is not very network-savvy (deliberately so, I believe).

When it needs to authenticate the user, HWI will try to use the default 'requests' module - I do not believe this supports the Tor protocol.  (If 'requests' is not available [eg the user has a firewalled/offline signing machine with no networking dependencies] then Jade must be unlocked some other way, for example using the 'Recovery Phrase Login'.

Mitigations:
1. Use Recovery Phrase Login to scan a QR code to unlock/initialise Jade
2. Use an https pinserver endpoint, or use a socks proxy to bounce requests onto Tor
3. In an upcoming release it should be possible to communicate with a pinserver and unlock Jade using only QR codes.

I will also raise an internal ticket to have HWI/jadepy look for a 'torpy' dependency before it looks for 'requests' - as I think if it found/used that module Tor/onions would be supported.

**Comment by craigraw** [comment]
> But of course it's the companion application that actually has to handle the networking side

Thanks @JamieDriver. Sparrow is not currently doing anything regarding PIN servers (and I don't believe there is any interface with HWI to allow it to do so), so I assume everything is handled by HWI. Also, I don't think there is any way to configure HWI to use a socks proxy.

**Comment by JamieDriver** [comment]
ok, scratch that one then ;-)

No, HWI itself is deliberately 'network-unfriendly' as it (the standalone `hwi.py` command-line tool at least) is supposed to work on an offline signing machine with no networking capability/no networking packages installed.

The Jade plugin/adapter part will try to use the `requests` module to contact the pinserver if it is present, otherwise falls back to 'offline' mode (where you must use 'Recovery Phrase Login' to enter your seed phrase).

As I say above, I could look to use a Tor-aware networking dependency if it's available - but again how would one 'tell' HWI what you want it to do.  But I'll give it some thought.

**Comment by craigraw** [comment]
Implemented in e7ed8269. Keystone (and thus Jade) are actually using the Coldcard multisig export format. 

<img width="541" alt="Screenshot 2023-01-18 at 13 26 15" src="https://user-images.githubusercontent.com/862166/213159664-f2c68637-3ca1-4fb2-8382-e2921e1cb916.png">

Thanks for the info about the PIN server!
