### ISSUE TITLE
multisig with Ledger Nano S

### ISSUE THREAD

**Issue by FTPLSMSF** [sparrowwallet/sparrow#780]
I need clear instructions how to create cold wallet using a sparrow on a Windows laptop with 2 USB ports. I have 3 Ledger Nano S and want to create 2/3 multisig.
There are many instructions there but I face the following problems:
1. Most instructions out there are for single wallet and when there is one for multisig, they dont have one for three Cold wallets like Ledger or Trezor. For example:

-Click File/new wallet
-Select Settings on the left side tab
-Select the drop-down menu Policy Type: choose Multi signature
-Cosigners bar: select 2 and 3 (M of N should state: 2/3)
-Script Type: Leave as default (Native Segwit (P2WSH))
-Script Policy: Leave as default
-Keystores: These are a list of the keys (hardware devices) that you will be using to create the multi signature wallet. For -Ledger Nano S, select the option Connected Hardware Wallet.
-Connect your hardware wallet and click Scan.
-Your wallet should show up (Ledger Nano S) with a drop-down menu next to it. Click Import Keystore.
-Change the label on Keystore 1 to something that makes sense to you, Eg. Hardware Wallet 001 (Ledger Nano S).
-Repeat for Keystores 2 and 3.

2. When I disconnect one Ledger to connect another, the one disconnected disapear from the tabs. Does it stay in the wallet?

**Comment by craigraw** [comment]
Support requests are better handled in the Telegram group: https://t.me/SparrowWallet. That said:

1. Your notes look correct.
2. Sparrow has imported the relevant public key from the hardware wallet, so it can be disconnected, and only needs to be reconnected for signing later.
