### ISSUE TITLE
No mixing option

### ISSUE THREAD

**Issue by newbie22222** [sparrowwallet/sparrow#781]
Started up two new wallets yesterday and no mixing option is available for my UTXO's. Please advise.

**Comment by RequestPrivacy** [comment]
Hard to guess with the little info you provided.

Are both hot wallets? You need them hot to mix. 
Are they native segwit (i.e. addresses start with bc1....)? 
Did you create the wallets in Sparrow or do you try to import via a seed?

Can you confirm that for mixing you go to the UTXOs tab, select utxos and there is no mix button in said tab?

**Comment by newbie22222** [comment]
Thanks for the reply. I was not using hot wallets and that fixed that problem. However, I am getting an error called "error fetching pools". It appears to be timing out. I am using Tor and that seems to be working fine, and the network test pinging my bitcoin core is coming back fine as well. Please let me know if I can give any other information that may be helpful

**Comment by newbie22222** [comment]
After letting it sit for a bit I retried it again and it worked this time. I imagine that happens from time to time?

**Comment by newbie22222** [comment]
Got it, that's good to know. Appreciate your help.
