### ISSUE TITLE
Is resolverdex.com safe to use? What is it?

### ISSUE THREAD

**Issue by newbie22222** [sparrowwallet/sparrow#782]
Was given the recommendation to go to this website and connect my wallet. That was from the official Telegram group. Seems very odd and suspicious, can anyone here confirm? The mixing service is still only randomly connecting, getting a lot of time dropouts.

**Comment by newbie22222** [comment]
Also why does the sparrowwallet.com website have an official Telegram link that takes you to a scam Sparrow group?

**Comment by craigraw** [comment]
> Also why does the sparrowwallet.com website have an official Telegram link that takes you to a scam Sparrow group?

It doesn't. sparrowwallet.com links to the correct Telegram group @SparrowWallet. Please explain how you came to this conclusion?

> Was given the recommendation to go to this website and connect my wallet.

This indeed sounds very suspicious. What was the handle of the group that gave this advice?

**Comment by newbie22222** [comment]
Fake Telegram groups asking for this info include sparrowwalletchat and sparrowwalletcommunity. The sparrowwallet.com website telegram link is good, I was mistaken and apologize for the false alarm. Thanks for reply
