### ISSUE TITLE
Why does Sparrow website take you to a fake Telegram group?

### ISSUE THREAD

**Issue by newbie22222** [sparrowwallet/sparrow#783]
The Telegram link on the Sparrow website takes you to a scam group. Trying to understand why that is the case and why it has not been removed?

**Comment by newbie22222** [comment]
Be careful folks, I ended in scam groups even when watching my step.

**Comment by craigraw** [comment]
> The Telegram link on the Sparrow website takes you to a scam group. 

This is not true - the correct link (as indicated on sparrowwallet.com) is https://t.me/SparrowWallet.
