### ISSUE TITLE
Implement BIP 69

### ISSUE THREAD

**Issue by Scalena** [sparrowwallet/sparrow#784]
[BIP 69](https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki) specifies that transaction inputs and outputs should always be ordered lexicographically to make transactions less easy to fingerprint. Presumably, it would be a privacy improvement to all users, if Sparrow also implemented this.

**Comment by craigraw** [comment]
Sparrow randomly shuffles inputs and outputs already, so it's not clear that BIP69 provides any privacy advantage. There is a discussion over at https://togithub.com/bitcoin/bitcoin/issues/12457 on this, which was eventually closed without implementing the BIP.
