### ISSUE TITLE
[Bug - Sparrow Server] Rejected mix UTXO due to unconfirmed status 

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#788]
### Description

While waiting for confirmation, Sparrow Server seems to re-register an utxo in the 5.000.000 sats pool postmix although it has an unconfirmed status. Its input therefore gets rejected frequently (the mix progress bar resets the error message but  once it re-registers it gets rejected again).
```
<DATE> ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-85] c.s.w.c.m.MixClient[1672074727137] [null:-1] ERROR: Waiting for first mix confirmation
<DATE> ERROR [Whirlpool-HttpClient-COORDINATOR_WEBSOCKET-85] c.s.w.c.w.WhirlpoolWallet [null:-1]  - [MIX] 0.05btc ⣿ WHIRLPOOL FAILED ⣿ Input rejected ; Waiting for first mix confirmation

```

Some more background:

- It's the only utxo of the wallet in said pool denomination.
- The balance increased by an additional 5.000.000 sats as Sparrow shows the old utxo with _mixesDone_ and the unconfirmed one with _mixesDone+1_
- This behavior hasn't been observed with other pool denominations.
- Sparrow is connected to a fulcrum server and receives block updates
- Restart doesn't stop the behavior.

I'm pretty confident that this isn't a back-end issue...

UPDATE:

After hitting `<Refresh>` in the Postmix UTXO section the balance decreased by 5.000.000 back to the correct amount. Now there is only the "old" i.e. already confirmed utxo with _mixesDone_. Yet, the input still gets rejected, so there is still the unconfirmed transaction sitting in the mempool somewhere but apparently Sparrow Server doesn't know about it and keeps trying to re-register...

UPDATE 2:

The unconfirmed (and in the UI not visible utxo) has been confirmed and Sparrow has now been informed correctly over the fact, i.e. the mix count has been increased to _mixesDone+1_, the balance has the correct amount and the "old" utxo with the error messages has been replaced by the new one and isn't getting rejected anymore.

I see two problems on Sparrow's side:

1. Somehow Sparrow tries to re-register an unconfirmed remixer UTXO
2. Hitting `<Refresh>` drops the formerly shown unconfirmed utxo from the UI while problem no. 1 still exists.

**Comment by craigraw** [comment]
Thanks for the detailed report.

Sounds like a temporary miscommunication between Sparrow and Fulcrum resulting in incorrect wallet history, which was then picked up by the Whirlpool client (which has it's own history cache that updates on a different schedule). Could be a bug in Fulcrum or Sparrow, more likely just a missed notification due to network issues. Could also be reorg, although they are rare so that is less likely.

**Comment by RequestPrivacy** [comment]
Thanks for the info. I will keep an eye on it and report back if it happens again.

**Comment by RequestPrivacy** [comment]
Going to close this off as it didn't happen again.
