### ISSUE TITLE
QR scanning Specter export (multisig wallet)

### ISSUE THREAD

**Issue by ostermayer** [sparrowwallet/sparrow#79]
Specter wallet generates a pdf with export functionality and derivation paths.  This pdf also includes a QR code which contains json data for multisig.

Using sparrow QR code scanning to import a multisig of specter wallet generated error "not in json format"

**Comment by craigraw** [comment]
I've tried to reproduce this using Specter 1.2.2, and I haven't been able to.

I'm able to create a multisig 2of2 wallet on Specter and successfully import it to Sparrow using the Specter PDF export (both non-SLIP and SLIP versions) by scanning the QR code using File > Import Wallet > Specter Desktop > Scan in Sparrow.

If you use the "Export To Wallet Software" feature in the Settings > Export Wallet area of the Specter wallet, does the JSON file import to Sparrow? The contents of the JSON file should match the contents of the QR code in the PDF, if you use a QR code reader.

**Comment by craigraw** [comment]
Closing this off, but feel free to add more information.
