### ISSUE TITLE
Can't sign Transaction with ledger nano s, popup close and nothing appear 

### ISSUE THREAD

**Issue by Tiri92** [sparrowwallet/sparrow#790]
Hello i have a bug when i try to sign with nano, the popup disappear and nothing happen, my nano have a passphrase and when i try with nano without passphrase it work ! so how to deal with a nano that have a passphrase ? how to sign transaction ? i have imported my wallet that is on the nano with passphrase and sparrow never ask for it

**Comment by craigraw** [comment]
For a Ledger Nano, the passphrase is set on the device. See https://support.ledger.com/hc/en-us/articles/115005214529-How-to-set-up-a-passphrase-?docs=true

**Comment by Tiri92** [comment]
I know this ! but how to sign transaction on sparrow ??? it doesn't work when nano have passphrase, so how can i sign tx on sparrow  with my nano ??????

**Comment by craigraw** [comment]
Let's handle this on the Telegram channel. Github is for bugs and feature requests.
