### ISSUE TITLE
Public Server fallback as an option

### ISSUE THREAD

**Issue by Transisto** [sparrowwallet/sparrow#791]
I use a specific public server and Sparrow would constantly switch to another public one should any connection issue arise.

I've since entered the details as a private sever to avoid this but I think there should be a way to disable auto-switching to public servers.

It's a bigger privacy concern to eventually connect to every public server in the selection than selecting one.

![image](https://user-images.githubusercontent.com/388716/209893634-54d77778-516d-4a75-b0fb-85076f9105fd.png)

**Comment by craigraw** [comment]
We've had this discussion several times before, but you've never provided a reason why you are:
1. Concerned with privacy
2. Using public servers

Given there is an easy workaround to this conflicting set of priorities, I'm not inclined to implement this. Bitcoin is a journey of personal responsibility, and I would prefer to encourage people to run their own node if they are genuinely concerned about privacy. Fwiw I have good confidence that none of the listed public servers are tracking anything anyway.

**Comment by Transisto** [comment]
I'm sorting out technical issues with connecting to my own fulcrum server on raspiBlitz. 

In the meantime, only blockstream servers can eventually sync my older Samourai wallet.

It takes about 10 minutes instead of 10 seconds on electrum but it works. (Low time preference)

**Comment by craigraw** [comment]
Ok. Once you have Fulcrum running, it will be interesting to see if the other issues you have created here are still present.
