### ISSUE TITLE
Transaction confirmed but no show in Sparrow

### ISSUE THREAD

**Issue by FTPLSMSF** [sparrowwallet/sparrow#792]
Transaction confirmed in https://www.blockchain.com/explorer/transactions/btc/e9b29c2297bf368922826046c4c530fbeee9bc7738a3fa8d72670c7e1ec9fea3

 but no show in Sparrow
e9b29c2297bf368922826046c4c530fbeee9bc7738a3fa8d72670c7e1ec9fea3

**Comment by craigraw** [comment]
Check Sparrow is connected (toggle bottom right corner). If necessary, refresh the wallet (View menu). Make sure the wallet is loading without errors in the loading log (Transactions tab).

**Comment by FTPLSMSF** [comment]
@craigraw I appreciate your help with my issues. Sadly I was banned from the Telegram group, so can't there.
My problem is that the confirmation of a sent transaction from a Sparrow multisig with ledgers takes an infinity to complete, mean in git never does, Keeps going as a blue bar from side to side

**Comment by craigraw** [comment]
This indicates a problem with your connected server (either the connection to it or the server itself) since it never notifies Sparrow that the transaction has been broadcasted. Try restarting it as a first step.

**Comment by FTPLSMSF** [comment]
@craigraw I tried that broadcast a few times. Some suggests that it may takes hours or days depends on the blocks and fees. Is that correct.
What do you mean by "connected server"?

**Comment by FTPLSMSF** [comment]
@craigraw how do I "Try restarting it as a first step." Just to run it all over again? Do my ledger must be both connected to Sparrow while its running or I can have them disconnected once they authorised it?

**Comment by FTPLSMSF** [comment]
@craigraw it looks like i have issues connecting to the server or the node?. 
At the bottom right the button is toggled to the right, the yellow is flashing and when hovering over it says Connecting....

**Comment by FTPLSMSF** [comment]
@craigraw so, in preferences, server, public server under any of the url options in dropdown menu All I get is "Connecting to ssl://..." and it never connects

**Comment by craigraw** [comment]
I've just tested all the public servers Sparrow lists - they are all working fine. So perhaps your internet connection is at fault?
