### ISSUE TITLE
[Feature - Sparrow desktop client] Make auto-start of mixing optional

### ISSUE THREAD

**Issue by RequestPrivacy** [sparrowwallet/sparrow#793]
### Use case
I have following use case in mind:

- Mixing 24/7 via Sparrow Server "backend" on a dedicated remote device.
- Managing of everything else in the wallet via Sparrow desktop client on local machine due to the greatly superior feature set of Sparrow compared to Sparrow server.

I know the limited features of Sparrow server are (for now) intentional, so I guess you can relate to the described use case.

### Feature request
Currently whirlpool auto-starts  if one opens a wallet with whirlpool accounts in Sparrow desktop. I know there is a feature to mix to odd and even so that both, Sparrow desktop and Sparrow Server can mix simultaneously to the same wallet postmix account.

My understanding is that this increases the address use by a factor of 2 though. Also, I see no need/rush to have both clients mixing at the same time if Sparrow Server keeps humming along in the backend anyway.

So right now a user with described use case always needs to stop the mixing in Sparrow desktop. A per wallet setting to disable the automatic whirlpool starting would greatly improve the UX. 

It would also remove the need to preventive specify odd/even mixing in both clients for the possibility that one forgets to stop the mix process in Sparrow desktop after opening the wallet (otherwise with default configuration both clients would mix to the full address range with possible address re-use if I understand correctly).

**Comment by craigraw** [comment]
> A per wallet setting to disable the automatic whirlpool starting would greatly improve the UX.

This is actually currently the case. If mixing is stopped, Sparrow remembers and doesn't try to restart it (for example on relaunching the app).

**Comment by RequestPrivacy** [comment]
Oh nice, I haven't noticed. I keep underestimating how much Sparrow already adapts to the user flow. 

Awesome :heart:
