### ISSUE TITLE
UX: Avoid user confusion with accounts from different hardware wallets in one wallet

### ISSUE THREAD

**Issue by alaznem** [sparrowwallet/sparrow#796]
I noticed that it's possible to add new accounts from different hardware wallets/ passphrase combinations into the same wallet.

This might confuse people not aware how to properly segregate their seeds and/or passphrases.

I think the import of accounts with different seeds/passphrases can't be detected on the sparrow side, but can the sparrow UX do something to help avoid confusion?

**Comment by craigraw** [comment]
> I think the import of accounts with different seeds/passphrases can't be detected on the sparrow side

Correct - other than putting up warning dialogs, which I'm generally averse to, I can't see any way for Sparrow's UX to help here?

**Comment by craigraw** [comment]
Closing this off as unsolvable.
