### ISSUE TITLE
SEnt transaction unspent

### ISSUE THREAD

**Issue by FTPLSMSF** [sparrowwallet/sparrow#797]
Created a sent transaction from Sparrow multi sig and successfully confirmed with 2 hard wallets. All I get after multiple attempts is that the amount sent is **unspent**. It is like its blocked and I cannot send or retrieve any BTC out of the Sparrow multi sig wallet

**Comment by craigraw** [comment]
It's not clear to me what you mean by "multiple attempts".

That said, please use Github for bugs or feature requests, and support queries on Telegram at https://t.me/SparrowWallet.
