### ISSUE TITLE
UI Bug when Editting Labels

### ISSUE THREAD

**Issue by apemithrandir** [sparrowwallet/sparrow#798]
In Sparrow if you click on a label (either in transactions or UTXOs) and press the up/down arrow keys on your keyboard you will navigate cursor focus up/down a row.
The bug appears if I have selected a row then edit that label (either via F2 or by clicking the label) and then hit ENTER after completing my label edit. Now when I press the up/down arrows on my keyboard instead of navigating between rows I will be navigating between open wallets.
It seems as though hitting ENTER to complete a label edit switches the focus from the rows of a given wallet to the tabs of the open wallets.

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 5f96570c. The table will now retain focus after the label edit.
