### ISSUE TITLE
client_loop: send disconnect: Broken pipe - Sparrow Terminal

### ISSUE THREAD

**Issue by kanoo2** [sparrowwallet/sparrow#799]
I frequently receive this error when using Sparrow Server. This error occurs every time I SSH into Sparrow Terminal.
I have successfully opened a wallet, but eventually the error occurs within a few minutes. My wallets all have passwords which could be contributing to the error occurrence?  I have now tried reinstalling both the OS and Sparrow Server to see if this resolves the issue. Unfortunately I am still having the same issue.

I have edited the config file with a change suggested in #3391below:
EDIT: config updated with   "preventSleep": true, 

No other changes to the config file have been made.

Hardware used: Raspberry Pi 3b with no other software installed.
Operating system: Raspberry Pi OS Lite (64 bit)
Software: sparrow-server_1.7.1-1_arm64.deb

![image](https://user-images.githubusercontent.com/121717300/210135495-67fb6498-e808-4364-b9c4-0c8c49ff8b18.png)

**Comment by craigraw** [comment]
This is an SSH issue, not a Sparrow one. Take a look at https://unix.stackexchange.com/questions/602518/ssh-connection-client-loop-send-disconnect-broken-pipe-or-connection-reset. Also consider using tmux.

**Comment by kanoo2** [comment]
> This is an SSH issue, not a Sparrow one. Take a look at https://unix.stackexchange.com/questions/602518/ssh-connection-client-loop-send-disconnect-broken-pipe-or-connection-reset. Also consider using tmux.

It seems my issue related to my non standard power supply to the Raspberry Pi. After replacing this with the official charger, Sparrow Server is working flawlessly.

**Comment by craigraw** [comment]
Yes, the RPi is surprisingly sensitive to it's power supply, particularly when an external hard drive is attached. Glad it's working.
