### ISSUE TITLE
Ledger Blue

### ISSUE THREAD

**Issue by resipsadude** [sparrowwallet/sparrow#8]
Ledger Blue support possible?

Currently Sparrow Wallet does not detect Ledger Blue over USB as HWI does not appear to support Ledger Blue (https://github.com/sparrowwallet/HWI#device-support). Ledger Nano S/X work perfectly.

https://github.com/LedgerHQ/blue-loader-python
https://pypi.org/project/ledgerblue/
https://github.com/spesmilo/electrum/blob/master/electrum/plugins/ledger/ledger.py#L98-L106

Thanks :)

**Comment by craigraw** [comment]
Probably not given Ledger Blue is discontinued, sorry. Rebuilding all the HWI stuff is a lot of work for one wallet.
