### ISSUE TITLE
Applying signer keystore requires Sparrow Restart

### ISSUE THREAD

**Issue by ostermayer** [sparrowwallet/sparrow#80]
After applying a change to the sparrow wallet keystore, the sparrow wallet needs to be restarted, otherwise when composing a transaction the sign button will be inaccessable.

This was evident with hardware wallets after importing from an outside wallet and having the hardware wallets listed as "watch only".  After replacing with a "connected hardware wallet" and applying the changes, the sign button is inaccessible without first quitting the app.

**Comment by craigraw** [comment]
Fixed in 8d9e253.

The app reference to the wallet was not updated on this "minor" change - now the reference is updated regardless of whether a wallet refresh is required or not.
