### ISSUE TITLE
Can't Connect to Bitcoin Core

### ISSUE THREAD

**Issue by Cotchwoldt** [sparrowwallet/sparrow#802]
Bitcoin 24.0.1
Sparrow 1.7.1
Using Ubuntu (Pop Os)

Using all default settings, running core from Bitcoin-Qt graphical interface. 
URL: 27.0.0.1        8332
Have copied and pasted bitcoin.conf into /.bitcoin with the only change being the removal of # in front of "server = 1"
Have cheched that disablewallet was still a comment and not active. 

Bitcoin core can seemingly see Sparrow as it's heading changes from Bitcoin Core to Bitcoin Core - Sparrow. 
Strangely Bitcoin Core then looks to create a wallet with nothing in it. The screen changes from the no wallet is loaded screen to one with 0.0000 Btc etc. 

Was able to successfully do a test connection once but it has not worked since. 
It was never able to toggle on and create a steady connection. 

Have tried:
Uninstalling Sparrow and reinstalling. 
Opening Core first then Sparrow and vice versa. 
Making a dummy hot wallet and connecting to public server and then back to trying with Bitcoin Core. 
Restarting computer.

**Comment by Cotchwoldt** [comment]
Hi Craig, 

If it was reported, it wasn't reported by me. 

I didn't get as far as attempting to even create a wallet yet so not sure if it's the same taproot issue. 

I'll have a look and make sure I wasn't inadvertently adding a taproot wallet/setting somewhere. 

Cheers

**Comment by craigraw** [comment]
Ok happy to reopen the issue - unfortunately some users try every approach to get help resulting in multiple queries.

Check your Sparrow log (Help menu) for clues.

**Comment by Cotchwoldt** [comment]
Hi Craig, 

I was finally able to get it to work by going into the Bitcoin Core wallets folder and deleting the wallet called Sparrow, which presumably was created when I was testing the first connection. So there must have been some strange setting in there tripping it up. 

All works now. 

Thanks
