### ISSUE TITLE
Multisig account tab rename doesn't save the first time

### ISSUE THREAD

**Issue by mariaa144** [sparrowwallet/sparrow#805]
Creating several account with multiple keystores and then renaming them seems to work. However, after closing the wallet and then reloading the account again say `Account #1`, `Account #2` ... 

On the second load, renaming the account tabs once again will correctly save the account names for the next session.

I expected the account tab names to be correctly saved the first time or for there to be an error that the name didn't get saved.

**Comment by craigraw** [comment]
Thanks for the bug report. Fixed in d1a1bd57. Wallet account renaming and deletion will now be persisted properly when the account is newly created (not loaded).
