### ISSUE TITLE
Transactions tab shows previously open wallet's transactions on launch, even if different wallet is opened at startup

### ISSUE THREAD

**Issue by akarve** [sparrowwallet/sparrow#808]
Thus rendering duress wallets ineffective

**Comment by craigraw** [comment]
Do you mean when using a passphrase? Please see https://github.com/sparrowwallet/sparrow/issues/786#issuecomment-1365045596. It is impossible to store nothing derived from the passphrase, support offline usage, and the use case you have described all at the same time. The best Sparrow can do is detect when loading the wallet that the entire wallet history has changed, and refresh the wallet. Consider creating a duress wallet system by specifying the location of Sparrow home on start (see FAQ for details).

**Comment by akarve** [comment]
Yes, a passphrase. I understand the tradeoff you're making and concur that the app can't do all three.

One thing that could help, without breaking your tradeoff: **if the user launches with Command-R (refresh) or some other key combo pressed then the previous wallet is never shown**. I noticed that Command-R doesn't always kick in immediately and can leave data on the screen to be scraped.

As you intimate, Sparrow _could_ store the hash of the passphrase and that wouldn't be insecure, but it would violate "store nothing from BIP39" and would also be detectable by a clever attacker. I suppose the question is how important is offline mode relative to not leaking data from the last open wallet.

Thanks for your efforts and great app.

**Comment by craigraw** [comment]
> As you intimate, Sparrow could store the hash of the passphrase and that wouldn't be insecure

It would make brute forcing of the passphrase at least 10x easier by my estimation. Currently you need to perform a blockchain lookup to see if there are any funds for a given passphrase.

> I suppose the question is how important is offline mode

I consider the ability to use Sparrow in an offline setting to be a hard requirement.

> if the user launches with Command-R (refresh) or some other key combo pressed then the previous wallet is never shown

This is a possibility, but does it really help in a duress situation? You're counting on the attacker not knowing this.
