### ISSUE TITLE
Need to pass '--chain' argument to HWI v2.2.0 enumerate call for Jade devices to work with testnet/signet

### ISSUE THREAD

**Issue by strangebit** [sparrowwallet/sparrow#809]
HWI v2.2.0 adds the following change:  
https://github.com/bitcoin-core/HWI/pull/651

This change was needed for the ability to properly find a Jade device which has been set up for use with testnet/signet (which you can do by initializing the Jade first with a testnet wallet with the Green Desktop application). Before this change, `hwi enumerate` would return this error for the Jade device: `JadeError: -32003 - Network type inconsistent with prior usage (Data: None)`.

HWI already worked with other commands like `displayaddress`, because HWI made use of its `--chain` command-line argument in those cases appropriately, but up until v2.2.0 it did not do that for the `enumerate` command which the Jade uniquely needed.

The current version of Sparrow (v1.7.1 with HWI v2.1.1) running with `--network testnet` encounters this error when clicking 'Scan' for hardware wallet devices (i.e. when a Jade device is present and it is already properly initialized for use with testnet). Naturally, Sparrow does not let you proceed to use that Jade device because of this error.

Now that HWI has this change in its latest release, when Sparrow chooses to upgrade to use HWI v2.2.0, I believe it should also pass the `--chain` argument to HWI when calling `enumerate` as well, which it currently doesn't do. That way it _should_ hopefully stop encountering the error.

I believe it would work regardless of which test network the user is trying to use, i.e. testnet or signet, even though the Green Desktop application only mentions testnet specifically. See the following:

https://github.com/bitcoin-core/HWI/blob/f7e612697385c97e95014f191879f1d454ecca78/hwilib/devices/jade.py#L94-L97

Thanks!

**Comment by craigraw** [comment]
Thanks for the explanation! Implemented in 68cd3673 with the upgrade to HWI 2.2.0.

However, I'm not sure yet how to configure the Jade for testnet, so I am still getting the same `Network type inconsistent` error regardless of whether the `--chain` parameter is supplied. I've tried unsuccessfully to add a testnet wallet to the device in Blockstream Green.

**Comment by strangebit** [comment]
That's great, thanks!

So in Blockstream Green Desktop, there's something under `App Settings` to `Enable testnet'. Then when you click on Blockstream Jade on the sidebar, you can setup a testnet wallet from there. You might have to increase the size of the window to see it though. I had that trouble at first as there are unfortunately no scrollbars. See this comment here for before/after I increased the window size:

https://github.com/Blockstream/Jade/issues/13#issuecomment-1333931315

**Comment by craigraw** [comment]
Ok, I've factory reset my Jade and confirmed it's working on testnet.

A bit frustrating one has to factory reset the device and re-initialize it just to change from mainnet to testnet, but at least it's confirmed working now. Closing this off.
