### ISSUE TITLE
Sparrow test net coldcard issues when verifying addresses

### ISSUE THREAD

**Issue by hbadger321** [sparrowwallet/sparrow#810]
Was testing testnet with Sparrow and coldcard and there seems to be an issue in either Coldcard or Sparrow. 
When verifying receive address or address you spend to on coldcard via Sparrow I do not see the testnet address on my coldcard but the addresses associated with mainnet. 
1. Sparrow >tools >testnet
2. Open account via coldcard
3. send 
4. paste testnet address
5. 'create transaction
6. finalize > sign 
7. see that the address doesnt match and you see a mainnet address on your coldcard.

**Comment by craigraw** [comment]
I can assure you this setup works well, I use it very regularly :)

Did you configure the Coldcard for testnet use? It buried deep in the menus (Advanced menu: https://coldcard.com/docs/advanced)

**Comment by craigraw** [comment]
No reply, closing this off.
