### ISSUE TITLE
[Feature Request] Config option to disable internal Tor

### ISSUE THREAD

**Issue by AngusP** [sparrowwallet/sparrow#811]
Had a few frustrating moments where Sparrow has dropped its connection to the electrum server, or my local Tor service (`localhost:9050`) has restarted and Sparrow seems to decide to start a Tor itself, which then ?conflicts with the already running Tor daemon. In the UI it' thens pretty fiddly trying to convince Sparrow to stop doing this by editing the connection back to using the proxy.

Best solution I've found so-far is quitting and editing `~/.sparrow/config` to turn `"useProxy": true,` again; But ideally there'd be an option (config file only rather than UI would be fine) to disable Sparrow from ever trying to start Tor itself and just disconnect instead. My guess is Linux users with a tor daemon running are probably comfortable with editing a config file

**Comment by craigraw** [comment]
Added in d84f3bf8. The config property `autoSwitchProxy` can be set to `false` in the Sparrow config file, which will cause Sparrow to not try attempting to start the internal Tor client on connection failure.
