### ISSUE TITLE
Disappearing Wallet Address

### ISSUE THREAD

**Issue by vitokb** [sparrowwallet/sparrow#814]
I had an issue where I transferred from Cash app to my main Sparrow wallet. When I loaded the wallet and let the sync finish, the coins never showed up. I could see the coins on blockchain.io but never hit my wallet. The day after I went in to find the address and it wasn't listed. After several attempts to recover, all of a sudden, the missing address showed up and all of my coins came in. First time experiencing this on Arch Linux as my other laptops running Arch never had this issue.

Also, as a new feature, it would be nice to have watch-address option so I don't have more than one wallet app

**Comment by craigraw** [comment]
> The day after I went in to find the address and it wasn't listed. 

Are you using a passphrase? Entering an incorrect passphrase is the only way a wallet might display different addresses.

> Also, as a new feature, it would be nice to have watch-address option so I don't have more than one wallet app

You can setup a watch only wallet by choosing that option when creating a new wallet. Enter in the xpub and the wallet addresses will be created.
