### ISSUE TITLE
Trezor One slow to connect or not at all

### ISSUE THREAD

**Issue by VegArchie** [sparrowwallet/sparrow#815]
I see an issue on multiple PCs running Windows 10 where a Trezor One will be slow to connect (30-60sec) at every step. It will also fail to recognize a correct PIN.

This does not occur on every PC, however, I think the common factor between the two that it failed on is Bitdefender Total Security (Virus Scan). 

I tried entering in all Sparrow folders in the exceptions settings as well as disabling virus scan. I also tried running Sparrow as admin. However the issue persists. It seems as though something is high-jacking the USB connection to the Trezor One. 

Note: Trezor T and Ledger X do NOT have this problem. 

For example: Trying to add a Trezor One in the "connect hardware screen" and runing a scan will take over 30sec to find the Trezor. Clicking "Unlock" will take another 30+sec for the pin entry graphic to show. Entereing the correct pin (either manually in the text field or using the dots) will result in an immediate failure with the error message "LIBUSB_ERROR_ACCESS [-3]"
The pin numbers will remain on the Trezor One screen. 

![image](https://user-images.githubusercontent.com/123763252/215156212-40eeaff2-53a5-494c-80d1-ea947d0290e8.png)

**Comment by VegArchie** [comment]
Note: About 1 in every 10 tries the Trezor One will connect.

**Comment by craigraw** [comment]
Unfortunately there's not much Sparrow can do about an anti-virus, but you can set the anti-virus to exclude the internal utility Sparrow runs to communicate with the hardware wallet. Configure the anti-virus to ignore the `hwi` folder in Sparrow Home. See this FAQ to find it: https://sparrowwallet.com/docs/faq.html#where-does-sparrow-store-data

**Comment by VegArchie** [comment]
I had already excluded that folder. it didn't make a difference.

Considering that other apps, including the Trezor suite, don't have access problems, is there some other reason why sparrow would have difficulty with only the Trezor one?

**Comment by craigraw** [comment]
Any update here? If there's nothing that can be done on the Sparrow side, I'd like to close this off.

**Comment by craigraw** [comment]
It is in the hwi folder I mentioned previously, although the name is longer as it is extracted from the Sparrow install on use. You can still call it as normal though: `hwi-2.1.1.xxxxx...exe enumerate`.

**Comment by VegArchie** [comment]
I think this may be part of the problem. The only file (including hidden files) that appears in **C:\Users\USER\AppData\Roaming\Sparrow\hwi**  is _hwi-2.1.18667571028405941001.tmp_.   I even tried calling `hwi-2.1.18667571028405941001.exe enumerate` in command prompt anyway, and it said it doesn't exist.

**Comment by craigraw** [comment]
Try calling `hwi-2.1.18667571028405941001.tmp enumerate` - sorry, I wasn't near a Window machine previously to check.

**Comment by VegArchie** [comment]
Figured it out. It's the bitdefender firewall. Excluding in virus scan section did nothing, nor did allowing sparrow.exe full access through firewall. I had to turn the feature off completely. Once I do, HWI enumerate went from 45 seconds delay to 5 seconds. 

Thank you.
