### ISSUE TITLE
[BUG] Copy Script Output Bytes command shouldn't strip initial bytes

### ISSUE THREAD

**Issue by GregTonoski** [sparrowwallet/sparrow#819]
There should be the initial "5120" in the following example included in the copied string:
scriptPubKey = 5120a60869f0dbcf1dc659c9cecbaf8050135ea9e8cdc487053f1dc6880949dc684c

![image](https://user-images.githubusercontent.com/111286121/215846368-08345e67-ca74-4aa7-a9d6-80aff7e93b61.png)
 Precondition:
Sparrow 1.7.1 portable, Windows 11

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in 7590d786. The menu option will now output the entire ScriptPubKey.

**Comment by GregTonoski** [comment]
The fix has been verified positively in version 1.7.2. Thanks.
