### ISSUE TITLE
[Feature Request] Save proxy information along with Private Electrum Server alias profiles

### ISSUE THREAD

**Issue by s373nZ** [sparrowwallet/sparrow#822]
A user has a collection of private Electrum aliases for use under different contexts. For example, one hostname references a node on a private LAN, another alias accesses a node over Tor when on a foreign network. When the user Edits their existing connection and selects a different custom server, they must remember to manually change the proxy information to suit the network settings. The user would like the proxy settings to be saved and remembered between custom server profiles.

**Comment by craigraw** [comment]
Sparrow will not use the proxy for private network IPs which will include servers configured on the local LAN. Just configure the proxy and switch server URLs using the Tools menu.

**Comment by s373nZ** [comment]
In my case, I've registered the servers by LAN DNS name instead of private IP address.

**Comment by s373nZ** [comment]
Ok, I just tested it again. Seems to be working. Thanks!
