### ISSUE TITLE
.deb package puts Sparrow in the "Other" category of the application menu

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#823]
The .deb package puts Sparrow in the "Other" category of the application menu. Consider placing Sparrow in the "Internet" or "Office" category.

**Comment by craigraw** [comment]
What download are you using? The control file for the 1.7.1 .deb lists Sparrow under 'utils':

```
 Package: sparrow
 Version: 1.7.1-1
 Section: utils
 Maintainer: Unknown <mail@sparrowwallet.com>
 Priority: optional
 Architecture: amd64
 Provides: sparrow
 Description: Sparrow
 Depends: libc6, xdg-utils, zlib1g 
 Installed-Size: 132003
```

**Comment by AndySchroder** [comment]
1.7.1

I'm using XFCE. I tried it on multiple versions of XFCE.

**Comment by craigraw** [comment]
Perhaps XFCE does not respect the `Section` directive. It is certainly the correct way to do it AFAIK.

**Comment by AndySchroder** [comment]
Doing a little research, I *think* that you need to specify a Category in the Sparrow.desktop file (https://github.com/sparrowwallet/sparrow/blob/master/src/main/deploy/package/linux/Sparrow.desktop). See https://specifications.freedesktop.org/menu-spec/latest/apa.html .

**Comment by AndySchroder** [comment]
Bitcoin Core uses `Categories=Office;Finance;P2P;Network;Qt;`

**Comment by craigraw** [comment]
Thanks. I've used `Categories=Finance;Network;` in 24e75603 which matches Electrum.

**Comment by AndySchroder** [comment]
Looks like that option put it in the "Internet" category.
