### ISSUE TITLE
Display total *effective* fee rate when constructing CPFP txs

### ISSUE THREAD

**Issue by kdmukai** [sparrowwallet/sparrow#825]
Low fee tx is in the mempool but will have a long wait to be confirmed.

User creates a CPFP tx to move it along but naively sets their fee rate target thinking that's the fee rate the miners will prioritize on. Whereas in reality, it's the child + parent combination's total effective fee rate that determines miners' priority.

Naive user (okay, me) is disappointed to learn that they should have put more fees into their CPFP tx to hit their ETA goal.

**Comment by kdmukai** [comment]
Got it.

Is there value in showing the tx's individual fee rate instead of the effective? I can't think of a scenario where the individual tx fee rate would be more important, but I don't have much depth here.

If effective were to become the primary, it could be communicated in the display w/out too much extra space:

`33.81 sats/vB (effective) => CPFP`

And put the individual tx's rate in the tooltip.

**Comment by craigraw** [comment]
> Is there value in showing the tx's individual fee rate instead of the effective?

The problem is that the user expects the displayed fee rate to match the slider above. If it doesn't, it looks like Sparrow is broken - I've tried it and found it to be surprising and uncomfortable.

Happy to hear other suggestions as I still feel this can be improved somehow.

**Comment by weirdwhala** [comment]
i agree with @kdmukai , sparrow should always use effective fee as primary display, including the slider bar

**Comment by craigraw** [comment]
I've taken another look at this, and found a way to display the effective rate next to the transaction rate:

<img width="456" alt="Screenshot 2024-01-18 at 09 49 27" src="https://github.com/sparrowwallet/sparrow/assets/862166/75fa5b77-64ae-4548-86f2-3e12b3a7b05f">

6fc52fdc
