### ISSUE TITLE
You can't receive stowaways in postmix wallets

### ISSUE THREAD

**Issue by 4rkad** [sparrowwallet/sparrow#828]
It's not possible receive stowaways in postmix wallets.
I got this error (tested several times)

![12](https://user-images.githubusercontent.com/55397917/217837426-104709e7-2f3d-469e-9226-d96ae56cbb84.jpeg)

**Comment by craigraw** [comment]
I think this is more due to the specific UTXOs available in the Postmix wallet, than a general issue receiving. Not to say there isn't a bug in the in the Samourai cahoots library, but it's often difficult to find because of the specific conditions that need to be present. (Sparrow and Samourai use the same client to create Stowaways).

**Comment by 4rkad** [comment]
Samourai fixed this issue recently. This issue not appear in SW anymore.
It was tested several times in both wallets and it is not fixed in SP

**Comment by craigraw** [comment]
Ok great, I'll find out what they did. Appreciate the heads up.

**Comment by 4rkad** [comment]
If I get it I will share the commit. Thanks Craig as always

**Comment by 4rkad** [comment]
Maybe this can help

https://code.samourai.io/wallet/ExtLibJ/-/commit/0788528c2224f0344b6e08c2d50a1249fa8ad542

**Comment by craigraw** [comment]
Ok so after some discussion: It was a Samourai protocol decision to disallow receiving Stowaways to postmix wallets. This is actually reflected in the commit linked above, which sets the account number to 0 (`SamouraiAccountIndex.DEPOSIT`) for all Stowaways receives.

Sparrow follows this protocol decision, setting the wallet to the first or master wallet if the cahoots type is Stowaway and the selected receive wallet is Postmix. Generally, this will be the Deposit wallet as well, however Sparrow's ability to receive Stowaways to Account 1 etc is unchanged.

As a result, the error no longer appears. e3799cd0.

**Comment by 4rkad** [comment]
Now it seems another problem appeared. If I choose funds from postmix wallet to make an stowaway like receiver, Sparrow is choosing funds from deposit account. 

I am testing 1.7.3...
