### ISSUE TITLE
Unable to install the latest deb package

### ISSUE THREAD

**Issue by iWarpBTC** [sparrowwallet/sparrow#829]
The latest deb package (sparrow_1.7.2-1_amd64.deb) cannot be installed on up-to-date stable Debian 11, because of its dpkg (1.20.12) doesn't support zstd compression (apparently added at 1.21.18).

**Comment by craigraw** [comment]
Does it happen with v1.7.1? https://github.com/sparrowwallet/sparrow/releases/tag/1.7.1

**Comment by iWarpBTC** [comment]
No, sir. I have successfully installed both `sparrow_1.7.0_amd64.deb` and `sparrow_1.7.1-1_amd64.deb` as they were coming out.

**Comment by craigraw** [comment]
It looks like zstd compression is standard when building on Ubuntu 22.04. I'll revert this, thanks for reporting.

**Comment by craigraw** [comment]
Just adding your script here for others who run across this issue:
```
> cat ./script 
#!/bin/sh
ar x sparrow_1.7.2-1_amd64.deb
unzstd control.tar.zst
unzstd data.tar.zst
xz control.tar
xz data.tar
rm sparrow_1.7.2-1_amd64.deb
ar cr sparrow_1.7.2-1_amd64.deb debian-binary control.tar.xz data.tar.xz
```

**Comment by craigraw** [comment]
Update for v2.2.0, which is now built with Ubuntu 22.04 by default:

```
> cat ./script 
#!/bin/sh
ar x sparrowwallet_2.2.0-1_amd64.deb
unzstd control.tar.zst
unzstd data.tar.zst
xz control.tar
xz data.tar
rm sparrowwallet_2.2.0-1_amd64.deb
ar cr sparrowwallet_2.2.0-1_amd64.deb debian-binary control.tar.xz data.tar.xz
```
