### ISSUE TITLE
VirusTotal Detects as Malicious Files

### ISSUE THREAD

**Issue by Cryptaveli** [sparrowwallet/sparrow#830]
Why does VirusTotal detect a virus for the Windows installer and Windows Standalone files? Downloaded directly from Sparrowwallet.com. I'm assuming it's a false positive but just wanted to bring to attention.

![image](https://user-images.githubusercontent.com/106595349/218257009-d9cfedb6-2092-4943-8ac6-24b1fd3cef17.png)

![image](https://user-images.githubusercontent.com/106595349/218257032-79284559-3743-464f-ba1f-bacaa312620c.png)

**Comment by craigraw** [comment]
I've seen this before - it's definitely a false positive, but I'm unclear why VirusTotal has this issue. It looks like a fuzzy ML check though. Might be worth reporting to them.
