### ISSUE TITLE
UTXO confirmed block but no funds in sparrow wallet

### ISSUE THREAD

**Issue by Craigy88** [sparrowwallet/sparrow#840]
Hello!
I have recently installed Sparrow wallet and have just installed my RaspBlitz Node. I have sent some BTC to the Sparrow wallet ( first recieved transaction). The block is confirmed but its says unspent transaction. Very new to this and learning to bare with me :). The funds are not in the wallet but I can see them in block explorer confirmed? any help would be great! 

Thank you

**Comment by craigraw** [comment]
Make sure Sparrow is properly connected to the Raspiblitz (use Test Connection to check) and that the wallet is loading without errors.

Please use the Telegram group for support, not Github. https://t.me/SparrowWallet.
