### ISSUE TITLE
server connection error with bitcoin core

### ISSUE THREAD

**Issue by djbeniswift** [sparrowwallet/sparrow#841]
Hello, I installed bitcoin core and when i attemp to test connection with the server i get this error

Cannot find Bitcoin Core cookie file

I followed the instructions about creating a bitcoin.conf file, but that doesn't help

Thanks

**Comment by craigraw** [comment]
Make sure you have correctly configured the Bitcoin Core data directory. Read the documentation to check.

Please use the Telegram group for support, not Github. https://t.me/SparrowWallet.
