### ISSUE TITLE
Sparrow not recognizing .local (mDNS) hostnames  as LAN addresses

### ISSUE THREAD

**Issue by shyfire-131** [sparrowwallet/sparrow#842]
Using start9 embassyOS they use http headers to proxy requests to the relevant service running on the device (e.g. bitcoind/electrs/etc) and the headers contain the hostname of the request e.g. sdhjidshuidshfuscygxuydsbyudsf.local

I suspect that Sparrow is not recognizing this hostname as a LAN address.

The below settings work:

![image](https://user-images.githubusercontent.com/116033104/218916348-b9914eef-f21d-4cc0-b237-f87b27dddcd5.png)

However as soon as I enable the proxy, I get an error:

![image](https://user-images.githubusercontent.com/116033104/218916432-194ab394-77ad-4bda-9694-dd88e67d5011.png)

Yikes @ giant retina screenshots.

Anyway - yeah, the tor proxy is definitely running since if I stop the service I get "connection refused", so pretty confident in my diagnosis?

https://en.wikipedia.org/wiki/.local

**Comment by craigraw** [comment]
Thanks for the bug report - your diagnosis is correct, and this issue was fixed in https://github.com/sparrowwallet/sparrow/commit/eff0e201f3d7f9c2150dbb4db46004ab910ad63d.

For now, you can set `useLegacyCoreWallet` to `true` in the config file (close Sparrow first).

**Comment by shyfire-131** [comment]
OK, great!

p.s. setting `useLegacyCoreWallet` to `true` doesn't work, but no rush - happy to wait for this fix to make its way into a release.
