### ISSUE TITLE
[Feature Request] Bitcoin Core non-descriptors BIP32 HD wallet import

### ISSUE THREAD

**Issue by edxszymonski** [sparrowwallet/sparrow#846]
Bitcoin Core supports dumpwallet command for BIP32 HD wallets (non-descriptors wallets) which dumps "extended private masterkey" (xprv...). This key can be imported to Sparrow using File, New Wallet, New or Imported Software Wallet, Master Private Key (BIP32). Sparrow also allows to set Custom Derivation Keystore path which yields proper xpub. However, if one actually tries importing xprv exported from Bitcoin Core they will be surprised that Sparrow doesn't discover their addresses properly and funds from imported Bitcoin Core wallet are not available with Sparrow. This is because Bitcoin Core, at least when it comes to non-descriptors wallets, uses hardened derivation with simple keypaths, first key being at m/0'/0'/0' whereas Sparrow uses unhardened derivation and external + internal chains so the first key being at m/0'/0'/0/0. Currently, a user cannot customize these two behaviors, which unfortunately is required to get access to private keys from imported Bitcoin Core wallet via xprv import.

Use case: migration from Bitcoin Core non-descriptors BIP32 HD wallet to Sparrow.

I understand that Sparrow also supports "importing" private keys by sweeping individual WIFs (Tools, Sweep Private Key) and therefore a Bitcoin Core user can just dump the whole wallet and then sweep WIFs of funded addresses one by one in Sparrow. This is however, only feasible solution in the case of wallets with just a handful of transactions. In the case of a very active user (dozens or hundreds of previously used addresses) it will be easy to miss a WIF this way, even if the WIF Sweep feature in Sparrow allows importing from multiple WIFs at once (but does it?). Perhaps an alternative would be to implement a parsing mechanism for Bitcoin Core dumpwallet file format or even a wallet.dat format. However, this is rather very specific and a global solution to this kind of problems (importing xprv from a third party wallet, I mean) is IMHO allow customizing derivation type and paths.

Note: some more details in my discussion in https://github.com/sparrowwallet/sparrow/issues/58

**Comment by craigraw** [comment]
Unfortunately this is not likely to be implemented.

The amount of work required to do this is non trivial, and the amount of complexity it adds to the codebase is similarly non trivial. The feature would only assist those importing pre-BIP32, legacy wallets - certainly a small minority of users. Having separate receive and change chains is widely recognised as good practice, to the extent that Core descriptor wallets follow this practice and it is even likely to become part of the output descriptor specification (see BIP389).

I would suggest the best approach to migrate is to send all the UTXOs from the Core wallet to Sparrow (ideally separately to maintain privacy) - in this way one can modernise the wallet setup to one that is broadly compatible and potentially of a more modern script type.
