### ISSUE TITLE
re-broadcast unconfirmed transactions

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#847]
At times, the mempool can get filled up and low fee, low priority transactions can get pushed out and forgotten. Sometimes we have a transaction that we can be patient waiting days or weeks to get through. I think we need an option on unconfirmed transactions to re-broadcast them without needing to do a replace by fee. It's possible that Sparrow wallet is doing this automatically in the background, but I have no reason to know if it is.

**Comment by craigraw** [comment]
It's an interesting idea, but also one with significant challenges. The RBF transaction will need to be created, possibly adding a new UTXO, signed and broadcast. This assumes Sparrow is online, is sufficiently trusted to spend arbitrary outputs, and has access to the private keys to sign (not possible for hardware wallets). It is also difficult to predict the fee rate, which can drop quickly, resulting in overpaying on fees.

**Comment by AndySchroder** [comment]
I was thinking that Sparrow could just save a cached copy of any signed transaction that it already received from a hardware, software wallet, or multi-sig setup. If it sees there are cached signed transactions that aren't confirmed in a block yet, then keep allowing to resend that already signed transaction periodically (or manually as I was trying to suggest above). Once it's in a block, the cached local copy can be deleted because it's public.

**Comment by AndySchroder** [comment]
Also, there should be a way to forget about a transaction too if we want to abandon it. That should delete the locally cached signed transaction and remove it from the transaction history that is cached. Right now I don't know how to get rid of an unconfirmed transaction that never processed because its fee was way too low and all the nodes pushed it out of their mempools.

**Comment by craigraw** [comment]
This is not how the mempool works. You can't get a node to accept a transaction that is below its purge fee rate, and there's no point in sending a transaction to a node that already has it.

> Right now I don't know how to get rid of an unconfirmed transaction that never processed because its fee was way too low and all the nodes pushed it out of their mempools.

You can't "get rid of it". Some node with a larger configured mempool (than the default 300Mb) may still have it, and it will be rebroadcast to other nodes if and when the mempool decreases in size. Once broadcast, a transaction should be considered permanent unless it is replaced.

**Comment by AndySchroder** [comment]
Okay, it seems as though you are definitely right. My test transaction finally went through about 3.5 weeks later.
