### ISSUE TITLE
double spend a single input

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#848]
Right now we have the ability to cancel a transaction with a double spend of the same inputs (UTXO's) somewhere else, or increase the fee with a double spend to the same inputs and outputs. This is nice, but if we have a large transaction with many inputs with a very low fee rate, we may want to just double spend a single input with a larger fee rate and have a much lower overall fee. It would be nice to be able to select individual UTXO's when doing a cancel double spend and not be required to select all of the original inputs (UTXO's). If the fee rate for the original transaction was way to low, it's very possible the original transaction is wiped out of most node's mempools and a miner will prefer to first process the smaller transaction with the higher fee rate.

**Comment by craigraw** [comment]
It's possible to remove UTXOs from a created RBF transaction by clicking on the X icon that appears next to them when hovering over the UTXO in the transaction diagram.

**Comment by AndySchroder** [comment]
Okay, so right now if I try to do a replace by fee, it brings up the send screen. The transaction diagram does not come up. The Amount and Fee are red and it says insufficient funds. Also, the fee slider is in a place that is not matching the original fee. If I slightly move the slider, then the Amount jumps down and the Fee jumps up, then the transaction diagram comes up and I can try to do what I want with it.

However, it's hard to always force the same input UTXO's to stay. It's a bit finicky. As you change sending parameters, the UTXO's selected seem to automatically adjust (it might be nice to have a lock an input UTXO option). With some trial and error with the GUI, I was able to successfully do a double spend selecting only a single input UTXO that I wanted (getting rid of the other input UTXO's). However, in the Transactions tab, the label for the replaced double spent transaction is attached to the replacing double spend transaction, whereas the UTXO's tab does actually show the label I put in for the double spend.

**Comment by craigraw** [comment]
The behaviour you have described has been fixed in https://github.com/sparrowwallet/sparrow/commit/af9fb8694efafde6c7d0acea503a8ab48f797fee (and others). The minimum required fee for relay is now set, and the proposed transaction that appears immediately on selecting the RBF function can be broadcast.
