### ISSUE TITLE
huge issue with addresses changing every time i close the sparrow app. whY????

### ISSUE THREAD

**Issue by turk123-git** [sparrowwallet/sparrow#849]
and every time i open the sparrow wallet, my addresses change, and someone just sent me 2 very high priced ordinals to two different labeled wallet addys' in my sparrow wallet and they're not there. and when i closed sparrow and reopened it, the labeled addresses for the two ordinals i was expected to receive have changed.

**Comment by craigraw** [comment]
Discussed elsewhere, incorrect passphrase used.
