### ISSUE TITLE
Can't use Trezor One as non-passphrase Keystore due to "Passphrase Required"

### ISSUE THREAD

**Issue by jimbojw** [sparrowwallet/sparrow#85]
Description: I'm trying to use a Trezor One as a Keystore without a passphrase, but Sparrow seems to demand that I supply a non-empty string.

Procedure: I updated my Trezor One firmware to 1.9.4, wiped it, and then restored from a never-before-used bip39 seed (24 word). In Sparrow, choose File -> New Wallet, enter a name.

In Sparrow's Settings window I choose Keystores -> Keystore 1 -> Connected Hardware Wallet. In the dialog, I hit Scan, and it finds the Trezor One, but says "Passphrase Required".

I click Set Passphrase, enter nothing in the box that drops down, then hit Send Passphrase.

Expected: Sparrow allows me to use the Trezor One as a Keystore without a passphrase.

Actual: Sparrow dialog shows "Passphrase send failed".

**Comment by jimbojw** [comment]
Workaround:

Apparently Trezor One is modal with respect to passphrase. It can either be in passphrase mode or not. If it is in passphrase mode, then Sparrow will demand a passphrase. The workaround is to toggle the passphrase on the device.

You can toggle passphrase mode with the Trezor Suite: https://suite.trezor.io/

In the Trezor Suite, click the gear icon to go to settings. Choose the Device tab. Scroll down and uncheck the Passphrase option. The Trezor One will ask you to confirm this choice on the hardware.

After disabling the passphrase on the device with the Trezor Suite, you can now add the Trezor One without a passphrase as a Keystore in Sparrow.

**Comment by craigraw** [comment]
Toggling the passphrase on and off for the Trezor One has been implemented in e524396.

Toggling the passphrase on is still somewhat hidden however - the accordion panel needs to be expanded after unlocking the device for the button to become visible. This will be looked again at when considering initial device setup functionality.
