### ISSUE TITLE
[Feature Request]: BIP351 Private Payments Support

### ISSUE THREAD

**Issue by privatepayments** [sparrowwallet/sparrow#850]
Private Payments ([BIP351](https://github.com/bitcoin/bips/blob/master/bip-0351.mediawiki)) is a stealth address system for Bitcoin that allows the user to post a static code and receive payments to a separate address space for each sender.

There are multiple [use cases](https://privatepayments.org/use-cases/) for Private Payments, but the static donation code seems to be the most compelling. A user wishing so solicit donations from the public may safely associate a payment code with her identity and receive funds in a relatively private manner.

The user story is similar to BIP47:

- Receiver posts their payment code
- Sender creates a notification payload and either posts it to the chain as an `OP_RETURN` or to some other bulletin board system
- Receiver scans the chain for these notification payloads and upon finding one, generates the chain of stealth addresses

Improvements over BIP47:

- Supports multiple address types
- Better notification payload privacy
- Smaller notification payloads

For more context, check out [privatepayments.org](https://privatepayments.org/) and the Rust [reference implementation](https://github.com/private-payments/rust-private-payments).

This would not replace the existing BIP47 support, as the protocols are not mutually exclusive.

**Comment by craigraw** [comment]
Private payments (BIP351) is not light client compatible, and therefore not a good fit for Sparrow or any other light client wallet (which is essentially all except for full node implementations like Bitcoin Core). The same problem is shared by Silent Payments, and IMO not sufficiently discussed as a disadvantage when compared to BIP47 in either proposal.

The workaround described in Appendix B (Potential OP_RETURN services) is not available in any sufficiently decentralised form to be a workable alternative, and in addition adds further complication for the user, requiring a UI for configuring these services, considering privacy etc. 

For these reasons I don't think this approach is currently a practical alternative to BIP47, so I'm closing this off for now.

**Comment by privatepayments** [comment]
I've opened a [related issue](https://github.com/spesmilo/electrumx/issues/206) in ElectrumX to support an `OP_RETURN` index, which would enable more light client support.
