### ISSUE TITLE
Cannot install on Debian anymore due to Debian bug

### ISSUE THREAD

**Issue by 4NobleTruths** [sparrowwallet/sparrow#851]
Debian 11

dpkg error on install:

> dpkg-deb: error: archive 'sparrow_1.7.2-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up

I think caused by:
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664](url)

**Comment by craigraw** [comment]
Duplicate of #829. Please see that issue for a workaround to repackage the .deb.
