### ISSUE TITLE
Proxy won't work. SOCKS server general failure

### ISSUE THREAD

**Issue by pants101** [sparrowwallet/sparrow#853]
Hi! This is my first post on Github. I did try to search for the issue and implement the solutions where posts had been resolved but nothing seems to be working and I decided after 2 days of trying to start a new issue. 

I run a Bitcoin core RPC that is connected to sparrow with tor. I have used sparrow for about 1-2 months with no issue. I stopped using it for about 1-2 weeks, when I logged back on there was an error showing up saying, Connection failed: Socket error (SOCKS server general failure). I haven't made any changes at all, and looking at past issues my setup should IMO work. In my server preferences I have my proxy on and my proxy URL:localhost 9150. I don't know how to move forward tbh. Also, when I logged in I had 1.7.1 running. at first I thought that was the issue, but I now run the latast version with the same problem :( all help is much appreciated!

**Comment by craigraw** [comment]
This is a known bug with v1.7.2, and has been fixed in https://github.com/sparrowwallet/sparrow/commit/eff0e201f3d7f9c2150dbb4db46004ab910ad63d. A new release will be out soon.

**Comment by pants101** [comment]
great! tnx for the response. Can I ask... of I choose to not wait until the release is out and make transactions etc without proxy enabled, what can be the downside? Isn't sparrow running its own tor anyway? I'm kinda new to this space so be kind lol

**Comment by pants101** [comment]
> This is a known bug with v1.7.2, and has been fixed in [eff0e20](https://github.com/sparrowwallet/sparrow/commit/eff0e201f3d7f9c2150dbb4db46004ab910ad63d). A new release will be out soon.

great! tnx for the response. Can I ask... of I choose to not wait until the release is out and make transactions etc without proxy enabled, what can be the downside? Isn't sparrow running its own tor anyway? I'm kinda new to this space so be kind lol

**Comment by pants101** [comment]
> The only downside is that transaction broadcasting, and services like mempool.space or the Whirlpool coordinator, will be used without Tor. You can certainly use Sparrow without Tor, and many prefer a VPN given how poorly Tor is performing these days.

I currently use a VPN aswell,  but i wanted to use it over tor just to be safe. is a VPN enough or am I being to paranoid. I have a new fresh wallet ready to receive transactions and go trough whirlpool but I want to make sure everything is done correctly from the start. I can wait for the new update to come along, but that can take a while

**Comment by craigraw** [comment]
A VPN and Tor are not exactly the same, but I know many privacy proponents who are confident enough in their VPN to use it without Tor. I agree with them.

**Comment by RequestPrivacy** [comment]
This is really OT now but using a VPN + tor might NOT be the best in regards to your privacy. Check the following [link](https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TorPlusVPN).

The Tor Project advises against using tor with a VPN see [here](https://support.torproject.org/faq/faq-5/#topic_faq-5):

> Generally speaking, we don't recommend using a VPN with Tor unless you're an advanced user who knows how to configure both in a way that doesn't compromise your privacy.

**Comment by pants101** [comment]
> This is really OT now but using a VPN + tor might NOT be the best in regards to your privacy. Check the following [link](https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TorPlusVPN).
> 
> The Tor Project advises against using tor with a VPN see [here](https://support.torproject.org/faq/faq-5/#topic_faq-5):
> 
> > Generally speaking, we don't recommend using a VPN with Tor unless you're an advanced user who knows how to configure both in a way that doesn't compromise your privacy.

Late response... in regards of privacy for a beginner like med, how does one navigate this tsunami of eyes when using bitcoin? Any specific thread already on this or should I just create one regarding this somewhere else. My Q will still be connected to sparrow someway. I thought VPN + tor + whirlpool was enough, this keeps getting deeper and deeper.
