### ISSUE TITLE
Using "Mix to XXX Post mix" overwrites existing account at m/84'/0'/1'

### ISSUE THREAD

**Issue by NoSandMan** [sparrowwallet/sparrow#854]
Issue:
Using "mix to" feature to mix from hot wallet to cold / watch only wallet overwrote an existing account in the cold wallet. 

To recreate:

1. Load cold wallet.
2. Create two accounts in the cold wallet. Account 0 - m/84'/0'/0' & Account 1 - m/84'/0'/1'
3. Use hot wallet "Mix to" feature and select "Cold Wallet Post-Mix"
4. Check cold wallet ad see Account 0 & Post-Mix.

Proposed fix:

When using "mix to" and suggesting Post-Mix, check if an account exists at n=0 in m/84'/0'/n'. If an account already exists, move to n+1 and check again.

**Comment by craigraw** [comment]
I have read this several times and cannot make sense of it. Where did the "Cold Wallet Post-Mix" come from? The mix to dialog has no ability to "overwrite" or change the name of an account in another wallet.

**Comment by craigraw** [comment]
Closing this off, no response.
