### ISSUE TITLE
[BUG] Error Connecting SATSCARD | MacOS Ventura 13.1

### ISSUE THREAD

**Issue by confettimoney** [sparrowwallet/sparrow#856]
Hi Craig,

When I try to set up my SATSCARD it is initially recognized as a SATSCARD, as expected. However, after providing the PIN it gives an Import Error message:

"Please use a Tapsigner card."

When I in fact hold my TAPSIGNER on the NFC reader it gives another Import Error message:

"Please use a Satscard card."

Noteworthy:

- I am using the HID OMNIKEY 5022 CL as an NFC reader
- macOS Ventura 13.1
- Initializing the TAPSIGNER minutes before worked flawlessly

What are your thoughts on this? Would you require further info, please let me know.

Thanks a lot,

CM

**Comment by craigraw** [comment]
It's probable that you have left the card you are not using too close to the reader, and it's picking up the wrong card. I encountered this myself during testing. Leave the correct card on the reader, move the other some distance away, and try again.

**Comment by confettimoney** [comment]
Hi Craig,

Thank you for your response. Will try it again in the upcoming days and I'll inform you about the outcome.

**Comment by confettimoney** [comment]
Tested my SATSCARDs again:

- SATSCARD on the reader
- HID OMNIKEY 5022 CL as an NFC reader
- macOS Ventura 13.1
- any other SATSCARD and TAPSIGNER meters away/in another room

Unfortunately still getting the same Import Error:

"Please use a Satscard card."

**Comment by craigraw** [comment]
Can describe what you are doing in Sparrow when this error occurs?

**Comment by confettimoney** [comment]
1/ File > New Wallet > Provide Wallet Name > Create Wallet

2/ Settings > Connected Hardware Wallet > Scan > SATSCARD is recognized (while SATSCARD being on the NFC reader)

Up until this, everything goes as expected. However, when I continue:

3/ Import Keystore > Provide PIN > Import Error: "Please use a Tapsigner card." 

The name and icon of the "Connected Hardware Wallet" are still the ones related to Satscard though (and not Tapsigner).

So it seems like it starts the initializing flow of a SATSCARD and the card is recognized as such, but after the PIN of the SATSCARD has been provided it expects a TAPSIGNER instead for some unknown reason to me.

**Comment by craigraw** [comment]
A Satscard doesn't have the functionality of an HD wallet. It is a single address wallet, like the Opendime. In Sparrow, you can:
1. Retrieve the current address to send to (Send tab, drop down, NFC card)
2. Sweep all the funds in the current address to any HD wallet you have open, unsealing the private key necessary to do so (Tools > Sweep Private Key > NFC icon)
3. Initialise a new address on the Satscard, a maximum of 9 times (Send tab, drop down, NFC card)

**Comment by confettimoney** [comment]
Just checked the three steps you mention with one of my SATSCARDs and this seems to work flawlessly. I will close this issue.

Thank you!
