### ISSUE TITLE
Payjoin request `&minfeerate=` query param unset despite enforced minimum relay fee

### ISSUE THREAD

**Issue by DanGould** [sparrowwallet/sparrow#857]
Seems like Sparrow rejects the response payjoin PSBT having fee rate below the minimum relay fee. However, the sender does not specify `minfeerate=` despite [contributing additional fee to pay for the receiver contribution](https://github.com/sparrowwallet/sparrow/blob/04a516d56b60d0ed8a5b6e2de07638cce02e9d20/src/main/java/com/sparrowwallet/sparrow/payjoin/Payjoin.java#L70-L76). Looks also as though sparrow accepts a fee rate below the one set by the sender.

I don't think this has shown up in failed payments yet because receiver implementations enforce the same min relay fee as Sparrow even if sparrow does not pass the parameter.

In my estimation, Sparrow should at least send `minfeerate=<Sparrow's minrelayfee>` in the request parameters so that the receiver knows why a payjoin has failed in the case of minimum relay fee rate as opposed to the current silent failure.

Sparrow may also want to set `minfeerate` to the rate specified in the UI.

[see the relevant section of the bip78 spec](https://github.com/bitcoin/bips/blob/master/bip-0078.mediawiki#respecting-the-minimum-relay-fee-policy)

**Comment by craigraw** [comment]
Thanks for the bug report. As of 9fc09656, Sparrow will include the `minfeerate` parameter, set to whatever the minimum relay fee rate is for the server it is connected to (or 1 sat/vb otherwise).
