### ISSUE TITLE
[Feature Request] Open transactions in block explorer of choice

### ISSUE THREAD

**Issue by InnocuousFinch** [sparrowwallet/sparrow#858]
This feature request has two components:
1. Adding a button that opens a given transaction in a block explorer
2. The ability to customize the block explorer URL so you can, for example, use your own mempool.space instance

Below is where I think it makes sense to put the button:
<img width="747" alt="Screenshot" src="https://user-images.githubusercontent.com/118941419/220747991-1dacc95a-f1b2-427d-8cc2-25ed40019176.png">

You might be able to put it elsewhere, like for example in the right click context menu when right clicking on a transaction.

If using the default block explorer (I assume mempool.space), a warning should pop up when the user clicks to open the tx in a block explorer, telling the user that by opening this transaction on the default block explorer, they are exposing their IP address and transaction details to a 3rd party.

If they're using a custom block explorer, this warning popup is not necessary.

**Comment by craigraw** [comment]
I'm not against this, but I am curious to know what Sparrow lacks wrt to exploring a transaction that a block explorer provides.

**Comment by InnocuousFinch** [comment]
This is what I typically do after pasting the TXID into my own instance of mempool.space that you cannot do in Sparrow:
- Look to see what the confirmation ETA is. If it's in the current block, being able to see where it is in the block is nice.
- Confirm fee cost in USD
- Check overall state of mempool, like how many blocks are in mempool, what fee rates range estimates are for next few blocks
- Occasionally I will click on one of the input addresses of existing TXID to look at that address's history, possibly following the chain backwards
- Leave mempool open as it will chime precisely when the transaction is confirmed

**Comment by craigraw** [comment]
Sparrow does offer some of this (confirmation ETA in the transactions table tooltip for the Unconfirmed cell, going backwards through the chain via inputs in the transaction tab) but I can see how this feature can be useful.

I don't have a local instance of mempool.space, as I don't run a pre-packaged node. Do the URLs work the same as the public instance?

**Comment by feelancer21** [comment]
> I don't have a local instance of mempool.space, as I don't run a pre-packaged node. Do the URLs work the same as the public instance?

Yes it's the same scheme. I have already connected my private mempool.space with Electrum and Lndg.

**Comment by InnocuousFinch** [comment]
Yep. Btcpayserver allows you to choose whatever block explorer you want to use, you just have to specify where you want the TXID to go using the `{0}` variable.

<img width="820" alt="btcpay mempool settings" src="https://user-images.githubusercontent.com/118941419/221317586-f98b1bda-54c4-4c4c-aa1b-fcc1d9bdad81.png">

**Comment by craigraw** [comment]
Implemented in dfe1f164.

You can now configure mempool.space, blockstream.info, or a custom block explorer in the General Preferences. 

<img width="430" alt="Screenshot 2023-02-28 at 14 03 38" src="https://user-images.githubusercontent.com/862166/221849595-642f6c8f-8878-4981-ba6f-e16e70e5c3b0.png">


The block explorer can be opened from any transaction tab for a finalized transaction, or from the context menu for a transaction in the Transactions tab. This functionality can also be disabled.

<img width="724" alt="Screenshot 2023-02-28 at 14 01 28" src="https://user-images.githubusercontent.com/862166/221849324-d0932c8e-3ddb-48cc-8061-b029607e2205.png">
