### ISSUE TITLE
PSBT file not exported as binary following BIP-174

### ISSUE THREAD

**Issue by bjarnemagnussen** [sparrowwallet/sparrow#86]
I just wanted to mention that Sparrow does not follow [BIP-174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#encoding) by exporting the PSBT-file with a base64 string instead of as binary. Is there a reason for that? 

I think it would be nice if Sparrow would export the PSBT file as binary, but with the option to copy the base64 string also.

See also the similar issue from cryptoadvance/specter-desktop#486

**Comment by craigraw** [comment]
To be fair, BIP-174 does specify both the hex and base64 formats for examples, so seems to be ambivalent.

The major reason for choosing base64 is so you can copy paste the PSBT (for example to the `bitcoin-cli decodepsbt` command, which only accepts base64 format).

There is a cost in terms of UI complication to try adding both formats. What is the use case for the binary format (in addition to base64)? I assume you mean a true binary and not the hex representation as used in BIP-174 examples.

**Comment by bjarnemagnussen** [comment]
Regarding the BIP-174 specification I refer to the [Encoding section](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#encoding) that defines the `.psbt` file extension as true binary (not hex represented). 

This may be important for compatibility, as e.g. Coldcard can read a `.psbt` file and figure out by itself if it is binary or containing a PSBT as base64 string, but maybe that is not to be expected by all hardware wallets.

Regarding UI I think Electrum solved it quite elegantly. The "Save PSBT" button could open a sub-menu where one can click on "Save to file" or "Copy as text". Likewise, the "Load PSBT" button could open sub-menus "From file" and "From text".

**Comment by craigraw** [comment]
Submenus are UI complications though. 

Copy pasting PSBTs is probably mostly for developers, but it is handy. Given that you can already load a PSBT from base64 via the File > Load Transaction menu, I would prefer to avoid submenus on the buttons, and rather move to a binary format when saving. A further File menu item can display the base64 PSBT in a dialog for copy paste.

**Comment by craigraw** [comment]
Implemented in 08edc04.

There is now a submenu in the File menu to save either in binary format or base64. The "Save PSBT" button on the transaction signing screen now saves a binary format PSBT.

**Comment by bjarnemagnussen** [comment]
Wow, that was fast! Amazing!

**Comment by jaonoctus** [comment]
quick tip, if you do have a binary psbt in hands:

```shell
base64 binary.psbt | tr -d '\n\r'
```
