### ISSUE TITLE
BTC PayServer - BIP78 Payjoin not populating

### ISSUE THREAD

**Issue by apemithrandir** [sparrowwallet/sparrow#862]
I was testing out paying to a BTC PayServer with it's PayJoin link using Sparrow (implemented: https://github.com/sparrowwallet/sparrow/issues/31). When I opened the link which should include the PayJoin it didn't populate the PayJoin in Sparrow instead it showed a regular StoneWall x2.

This could easily be user error as it was my first time attempting a PayJoin. My work flow was: 

- Generate BTC PayServer Invoice
- Switch to Pay with Bitcoin from Pay with Lightning
- Go to Copy Tab
- Click on the Payment link with PayJoin support
- Paste that link into browser
- Open in Wallet
- Choose wallet+account to pay from
- Fill out label

After doing the above I don't see any PayJoin input in the transaction construction.

**Comment by craigraw** [comment]
You need to go a little further - create the transaction, sign it and you will see the Payjoin button appear that requests the payjoin PSBT from the server, which you then need to sign (again) and broadcast. Note that BTCPayServer broadcasts your original transaction if you don't do the second signing within a fairly short period.

**Comment by craigraw** [comment]
The link should look like
```
bitcoin:tb1q9rqunzxpf7a7mgvrgn3e4znewcvmrmfqdnuedf?amount=0.00004278&pj=https://testnet.demo.btcpayserver.org/BTC/pj
```
Note the `pj` parameter. Paste this into the Pay to field in the Send tab.

**Comment by craigraw** [comment]
It's working for me:

<img width="872" alt="Screenshot 2023-02-27 at 13 55 55" src="https://user-images.githubusercontent.com/862166/221557613-96a9bc8e-0c7e-44aa-a605-66d6dbba880b.png">
