### ISSUE TITLE
why is a derivation path required for a watching only wallet with an xpub?

### ISSUE THREAD

**Issue by AndySchroder** [sparrowwallet/sparrow#863]
If I create a watching only wallet and input an xpub, I must define a derivation path. Why do I need to input a derivation path? I thought that the xpub was created AT the derivation path relative to the original/root xpriv, so it doesn't make sense to me. I've tried putting in any derivation path and under Addresses it gives the same address list and all the addresses have the same output descriptor. This is also the same for watch only multi-sig wallets.

Is the derivation path actually needed? If not, can we not be required to input it in order to avoid confusion. If it is actually needed, what for?

**Comment by craigraw** [comment]
It is required to construct a valid PSBT - and it is not uncommon that a user may setup a purely watch only wallet and construct a PSBT from it. It's also required to construct a valid output descriptor. Moving away from the xpub/ypub/zpub legacy wallet setups towards a better standard based on output descriptors has always been goal.

**Comment by AndySchroder** [comment]
Interesting. I guess I was thinking that the wallet that created the xpub would know what path it created the xpub at, but maybe it won't necessarily remember that?

It seems like providing all this derivation path information in a PSBT is a privacy issue if you are doing a collaborative transactions like a coinjoin. Or, maybe that's a different kind of PSBT? Are there BIP32 and non-BIP32 PSBT formats or something?

BIP 174 defined the PSBT file keytypes, but it doesn't explain how to actually create a valid PSBT (only shows a bunch of final examples in hex/base64 format), so I'm struggling to understand this.

**Comment by craigraw** [comment]
> I guess I was thinking that the wallet that created the xpub would know what path it created the xpub

It probably would, but we're referring to importing an xpub here, not creating one.

> It seems like providing all this derivation path information in a PSBT is a privacy issue if you are doing a collaborative transactions

It is, but you can copy a PSBT without that information using the File > Save Transaction menu. Of course, in that case a signer has less information to check against though.
