### ISSUE TITLE
Build fails on ArchLinux 6.1.12

### ISSUE THREAD

**Issue by menkaur** [sparrowwallet/sparrow#864]
I just checked out the project using git with `git clone --recurse-submodules https://github.com/sparrowwallet/sparrow `
and started the build process with ` ./gradlew jpackage`

Here is the log of the build:
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Project : => 'com.sparrowwallet.sparrow' Java module

> Task :createDelegatingModules
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.antlr.antlr4.runtime/module-info.java:2: warning: [module] module name component antlr4 should avoid terminal digits
open module org.antlr.antlr4.runtime {
                     ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.apache.commons.lang3/module-info.java:2: warning: [module] module name component lang3 should avoid terminal digits
open module org.apache.commons.lang3 {
                              ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/de.mkammerer.argon2/module-info.java:2: warning: [module] module name component argon2 should avoid terminal digits
open module de.mkammerer.argon2 {
                        ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/io.reactivex.rxjava2/module-info.java:2: warning: [module] module name component rxjava2 should avoid terminal digits
open module io.reactivex.rxjava2 {
                        ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.jdbi.v3.sqlobject/module-info.java:2: warning: [module] module name component v3 should avoid terminal digits
open module org.jdbi.v3.sqlobject {
                    ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.jdbi.v3.core/module-info.java:2: warning: [module] module name component v3 should avoid terminal digits
open module org.jdbi.v3.core {
                    ^
1 warning

> Task :prepareModulesDir FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareModulesDir'.
> Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 6s
16 actionable tasks: 16 executed

Below is the output of java -version:
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7)
OpenJDK 64-Bit Server VM (build 19.0.2+7, mixed mode)

Here is the scan: https://scans.gradle.com/s/psd5uenh4riou

**Comment by craigraw** [comment]
Upgraded the jlink plugin to 2.26.0 to support Java 19 in 80dd5992. You can retry with the latest HEAD.

**Comment by menkaur** [comment]
I'm still having an issue

> Configure project :
Project : => 'com.sparrowwallet.sparrow' Java module

> Task :createDelegatingModules
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.antlr.antlr4.runtime/module-info.java:2: warning: [module] module name component antlr4 should avoid terminal digits
open module org.antlr.antlr4.runtime {
                     ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.apache.commons.lang3/module-info.java:2: warning: [module] module name component lang3 should avoid terminal digits
open module org.apache.commons.lang3 {
                              ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/de.mkammerer.argon2/module-info.java:2: warning: [module] module name component argon2 should avoid terminal digits
open module de.mkammerer.argon2 {
                        ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/io.reactivex.rxjava2/module-info.java:2: warning: [module] module name component rxjava2 should avoid terminal digits
open module io.reactivex.rxjava2 {
                        ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.jdbi.v3.sqlobject/module-info.java:2: warning: [module] module name component v3 should avoid terminal digits
open module org.jdbi.v3.sqlobject {
                    ^
1 warning
/home/menkaur/bitcoin/sparrow/build/jlinkbase/tmpjars/org.jdbi.v3.core/module-info.java:2: warning: [module] module name component v3 should avoid terminal digits
open module org.jdbi.v3.core {
                    ^
1 warning

> Task :jlink
WARNING: signed modular JAR /home/menkaur/bitcoin/sparrow/build/jlinkbase/jlinkjars/bcprov-jdk15on-1.64.jar is currently not supported

> Task :jpackage FAILED
Error: Invalid or unsupported type: [rpm]


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jpackage'.
> Process 'command '/usr/lib/jvm/java-19-openjdk/bin/jpackage'' finished with non-zero exit value 1

**Comment by craigraw** [comment]
Install the `rpm` package to your OS, or disable that package in `build.gradle`.
