### ISSUE TITLE
Question: Connect to H2 via RazorSQL - How can I convert walletNode.addressData from binary?

### ISSUE THREAD

**Issue by mrjbj** [sparrowwallet/sparrow#865]
I'm accessing a watch-only wallet using a tool called RazorSQL that can read H2 databases directly in an attempt to download  transaction history from Sparrow Wallet for tax purposes.  In the H2 database, there are many fields (like `walletNode.addressData`) that are stored in as BINARY, so I'm trying to figure out how to convert them back into strings in the hope that I can see things like blockchain transaction ids to help me match-up self transfers across wallets easily.  

Do you have any tips on how these binary fields are encoded and if they contain one piece of data per field (or are they compressed or store a bunch of proprietary other stuff used by the application natively)?   Any tips would be appreciated.  Thanks!

**Comment by mrjbj** [comment]
Update: I think we might have to use the `rawtohex()` function.  I tried this on `blockTransaction` table and it appears to return same info I see in the UI on screen.

**Comment by craigraw** [comment]
These binary fields are converted to byte arrays in Java after retrieval. Does the transaction CSV (icon next to transaction count in the Transactions tab) not provide what you need?

Closing this off as a support request.
