### ISSUE TITLE
Inefficient QR encoding of out descriptor in PDF exports

### ISSUE THREAD

**Issue by eliasnaur** [sparrowwallet/sparrow#867]
In PDF exports of the wallet output descriptor the QR is encoded in lower-case. Encoding in upper case, as described by [Blockchain Commons](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md), will result in smaller QR codes that are easier to scan.

Note that the animated QR code in the export dialog where "Save PDF..." is available does encode in upper case for maximal efficiency.

**Comment by craigraw** [comment]
Good catch, fixed in 5fe6a719.
