### ISSUE TITLE
Sparrow Crashing when opening webcam to scan QR code

### ISSUE THREAD

**Issue by imotep007** [sparrowwallet/sparrow#87]
Hi all,

I am new to Sparrow, looks great so far!

I am having 2 issues
1) Program crashing on me every time I open the camera to scan a QR code to either get a send address or airgapped QR enabled hardware wallet. I uninstalled and reinstalled the software. Seems to fix the problem for a few minutes and happens again.  On version 1.3.1, running on mac 11.2.3, connect to my own umbrel node.

2) Also get an error when export wallet file under sparrow.
Error: Cannot invoke "com.sparrowwallet.sparrow.io.Storage.getWalletFile()"
because "<local3>" is null

Not sure if they are related?

Sorry, I am beginner here.

Thanks in advance!

**Comment by craigraw** [comment]
Thanks for the report.

On issue 1, can you try editing the file at ~/.sparrow/config and changing the following line to the opposite of whatever it is:
```
"hdCapture": true,
```
Set `true` to `false` or vice versa, and restart this app. This will get Sparrow to try a different resolution for scanning. Please let me know if it works, and what the value is if so.

Issue 2 has been fixed recently, and is unrelated.

**Comment by imotep007** [comment]
Thanks so much! 

For issue 1:

It did work when I switched from false to true.

However, it does switch back to false automatically when disconnecting/reconnecting to my server, thus crashing again. When change it back to true, it works again

Is there a way to keep as true all the time?

For issue 2:
I am guessing the fix will be included in the next update?


I appreciate the help!

**Comment by craigraw** [comment]
I should have been clearer - before changing `hdCapture` to true, close Sparrow. Then change the field from false to true, and then restart Sparrow. It should not switch back.

It should have actually been true already, unless you upgraded from an earlier version of Sparrow? New installs of 1.3.1 default to HD capture on OSX.

Issue 2 will be fixed in the next release yes. For now, you can copy your wallet file directly from the ~/.sparrow/wallets folder (which is effectively all that export does).

**Comment by imotep007** [comment]
Thank you!

**Comment by imotep007** [comment]
Happy Sunday, 

A quick update. Even after switch hdCapture field from false to true while Sparrow is closed. It does still switch back to false on some occasions. Not sure why.

I am running lastest OSX and Sparrow 1.3.1.

Thanks!

**Comment by craigraw** [comment]
I've just added in 38b8fa3 a View menu item to switch the hdCapture field from true/false, so editing the config file will no longer be necessary.

It's not clear why that field is changing for you though - the only other way to change it is on the QR Scan dialog itself, via a button at the bottom.

**Comment by imotep007** [comment]
Thank you!

**Comment by 100millionsat** [comment]
I am having the same issue with web cam. My config file did not have the HD capture, true in it at all so I added it, but  still no help. then I saw you above comment with view menu item and I have toggled function with no avail. I am on the latest version (1.3.2) thanks,
![image](https://user-images.githubusercontent.com/82336277/114318148-4caa3e80-9ad1-11eb-9739-a9acd54f2377.png)
![image](https://user-images.githubusercontent.com/82336277/114318166-63e92c00-9ad1-11eb-9ebd-7c09bb389daf.png)

**Comment by craigraw** [comment]
This is actually a different problem - for some reason the native image camera capture library is not being loaded. We should really tackle this in a different issue. Can you provide details of your operating system?

**Comment by 6102bitcoin** [comment]
Outstanding Action: None (bug appears to be solved, separate issue has been split out)
Proposed Priority: NA

**Comment by craigraw** [comment]
Agree, closing this off.
