### ISSUE TITLE
Error signing with Ledger on Sparrow 1.7.1, 1.7.2 & 1.7.3

### ISSUE THREAD

**Issue by jafri** [sparrowwallet/sparrow#870]
Signing with Taproot wallet at path 86'/0'/0'

Get error on both 1.7.2 and 1.7.3 (unreleased built from latest 5fe6a7196acc4172416025f3de383b1dfaa41feb) 

Card initialization error, response was 0x6a82

On >= 1.7.2 doesnt even prompt on ledger device. On 1.7.1, prompts on ledger device but after transaction confirmation on device, fails with:

![image](https://user-images.githubusercontent.com/13677357/222041058-8ea888e7-e6f7-4560-95f8-54fec98def6b.png)

Simple transfer from 1 address to another, attached PSBT (extension changed to .txt for github upload)

[aa.txt](https://github.com/sparrowwallet/sparrow/files/10856954/aa.txt)

Same transaction works using Ledger Live

**Comment by craigraw** [comment]
You'll need to upgrade to the Ledger Bitcoin app v2.1.0, which should be out later today. This version is already available in the Bitcoin testnet app and works well there.
