### ISSUE TITLE
Custom block explorer does not support a port

### ISSUE THREAD

**Issue by resignedScientist** [sparrowwallet/sparrow#872]
I have my own mempool instance on a raspberry pi in the local network at: https://192.168.178.161:4081

When I use this as the custom block explorer the error appears: "Invalid URL"

If I remove the port, no error appears, but obviously I need the port for it to work.

**Comment by craigraw** [comment]
It does support a port.

Make sure to enter the full URL, including the protocol. I was able to use your example of https://192.168.178.161:4081 to open the following link in the browser.

<img width="324" alt="Screenshot 2023-03-01 at 13 45 26" src="https://user-images.githubusercontent.com/862166/222130501-3595ee43-095e-492b-a108-1a7ab32d4db5.png">

**Comment by resignedScientist** [comment]
<img width="372" alt="Bildschirm­foto 2023-03-01 um 17 59 31" src="https://user-images.githubusercontent.com/11232656/222209404-ce8cf2cb-e4cf-4630-926f-70a50c3e01c3.png">

Does not work for me

**Comment by resignedScientist** [comment]
oh but without the /tx/{0} it does work… maybe this hint is a bit misleading?
<img width="392" alt="Bildschirm­foto 2023-03-01 um 18 02 12" src="https://user-images.githubusercontent.com/11232656/222210006-d79986ec-3cea-4a7c-84f3-d70ea784ad29.png">

**Comment by craigraw** [comment]
Yes you're right - there is a bug when using a port and a `{0}` path. I'll get this fixed.

If others come across this, dropping the path from the URL is a quick workaround.

**Comment by craigraw** [comment]
Fixed in dd3b980c.
