### ISSUE TITLE
Can't see numbers in the interface

### ISSUE THREAD

**Issue by kalkulusrampage** [sparrowwallet/sparrow#882]
letters shown correctly but numbers are invisible, tried also with dark theme

os: arch
wm: qtile

![2023-03-03_1588x307](https://user-images.githubusercontent.com/121094221/222684876-a0c020ba-4519-4b65-be17-ed3fc2b67dcb.png)

**Comment by craigraw** [comment]
It appears your system may be lacking a serif TTF font. The following resources may help:

https://bbs.archlinux.org/viewtopic.php?id=248524
https://wiki.archlinux.org/title/Java_Runtime_Environment_fonts
