### ISSUE TITLE
Can't sign PSBT with connected Ledger hardware taproot wallet

### ISSUE THREAD

**Issue by jamesprorok** [sparrowwallet/sparrow#883]
I'm trying to sign a PSBT in Sparrow with my connected Ledger hardware taproot wallet.
When I click 'sign' with my Ledger in Sparrow, I see no prompt on my Ledger and there is no error messages in the Sparrow log. Nothing happens. 

The taproot wallet was created inside Ledger Live and imported to Sparrow.

I have successfully used my Ledger segwit wallet with Sparrow.

Sparrow 1.7.3, Ledger Bitcoin app 2.1.1. Firmware up to date.

The PSBT:

`cHNidP8BAF4CAAAAAX27a/e1mkAGq+wqtUtzW6YCn5q5PNYDibpP4Yh64lwxAAAAAAD/////AQDh9QUAAAAAIlEgHyLoQu8pJTiotEfmdgAhn2RTQ+SKtYVGLDf0gKdYKjIAAAAAAAEAXgEAAAABPWUqcfTHaU5Bagp+RsbqwDUMuRl8G5hI9nFBvf8CMrgAAAAAAP3///8BVCUAAAAAAAAiUSAfIuhC7yklOKi0R+Z2ACGfZFND5Iq1hUYsN/SAp1gqMgAAAAABAwSDAAAAAAA=`

Thank you

**Comment by jamesprorok** [comment]
I should add, when I try to create a send txn with the same wallet, I can sign that fine with my ledger.

**Comment by craigraw** [comment]
I believe the failure may either be because there are required fields missing from the PSBT (which I understand to have been created externally to Sparrow), or that Ledger does not support this sighash flag on Taproot signatures.

Here is some debugging output from this PSBT:
```
Transaction with txid: 69b4a9d519a529e39d9bde5e74373adf23036d06202b1b4364807f1a4a44ed3d version 2 size 94 locktime 0
 Transaction input references txid: 315ce27a88e14fba8903d63cb99a9f02a65b734bb52aecab06409ab5f76bbb7d vout 0 with script 
 Transaction output value: 100000000 to addresses [bc1pru3wssh09yjn3295gln8vqppnaj9xsly326c233vxl6gpf6c9geql6sct5] with script hex 51201f22e842ef292538a8b447e67600219f645343e48ab585462c37f480a7582a32 to script OP_1 1f22e842ef292538a8b447e67600219f645343e48ab585462c37f480a7582a32
Found input non witness utxo with txid: 315ce27a88e14fba8903d63cb99a9f02a65b734bb52aecab06409ab5f76bbb7d version 1 size 94 locktime 0
 Transaction input references txid: b83202ffbd4171f648981b7c19b90c35c0eac6467e0a6a414e69c7f4712a653d vout 0 with script 
 Transaction output value: 9556 to address bc1pru3wssh09yjn3295gln8vqppnaj9xsly326c233vxl6gpf6c9geql6sct5 with script hex 51201f22e842ef292538a8b447e67600219f645343e48ab585462c37f480a7582a32 to script OP_1 1f22e842ef292538a8b447e67600219f645343e48ab585462c37f480a7582a32
Found input sighash_type Single + Anyone Can Pay
```

Compare this to the example in https://github.com/bitcoin-core/HWI/issues/608, particularly the lack of the taproot internal key field. The sighash flag is also unusual - you may wish to try signing a PSBT created in Sparrow with this sighash to narrow things down.

**Comment by WXTux** [comment]
I have experienced exactly the same issue. It doesn't seem possible to sign a PBST in Sparrow with connected Ledger taproot wallet.

**Comment by craigraw** [comment]
> I have experienced exactly the same issue. It doesn't seem possible to sign a PBST in Sparrow with connected Ledger taproot wallet.

Note this issue specifically addresses a PSBT created *externally* to Sparrow. You need to upgrade the Bitcoin app on Ledger to 2.1.1 for Taproot support.

**Comment by WXTux** [comment]
I have Bitcoin app 2.1.1 on Ledger. When I use a software Taproot wallet on Sparrow I can sign a PSBT. When I use a Ledger I can't.

**Comment by craigraw** [comment]
> I have Bitcoin app 2.1.1 on Ledger. When I use a software Taproot wallet on Sparrow I can sign a PSBT. When I use a Ledger I can't.

Ok - can you create a separate issue with the details?
