### ISSUE TITLE
Blank Screen when open Sparrow Wallet

### ISSUE THREAD

**Issue by July-Jio** [sparrowwallet/sparrow#884]
can't see anything once open sparrow wallet on windows 10 Pro.
<img width="654" alt="image" src="https://user-images.githubusercontent.com/80434227/222769443-1d1fc942-5a55-4aeb-b457-e5eff88e9a66.png">

**Comment by craigraw** [comment]
It looks from the screenshot that you previously managed to create a wallet on Sparrow?

Was there any change that may have caused this behaviour?

**Comment by craigraw** [comment]
No response, closing.
