### ISSUE TITLE
[Feature Request] Update internal Tor library

### ISSUE THREAD

**Issue by InnocuousFinch** [sparrowwallet/sparrow#885]
Hi Craig,

Starting off with a fresh install of Sparrow v1.7.3, and noticed this messaging when starting up a Tor node connection stating that Sparrow is not using a stable version of Tor, and to "expect more bugs than usual."

<img width="569" alt="Tor log data from Sparrow" src="https://user-images.githubusercontent.com/118941419/223281791-77cf7909-5d47-4e9e-bd36-3e9c3b9fdf95.png">

This issue is a request to update the Tor libraries to the most recent stable release of Tor.

**Comment by craigraw** [comment]
Tor has been upgraded to 0.4.7.13 on all platforms, replacing the existing Java/Kotlin library with [kmp-tor](https://github.com/05nelsonm/kmp-tor).
