### ISSUE TITLE
Blank screen - File Menu > New Wallet

### ISSUE THREAD

**Issue by rezaq9** [sparrowwallet/sparrow#886]
<img width="1064" alt="Screen Shot 2023-03-07 at 2 15 04 pm" src="https://user-images.githubusercontent.com/127173309/223319629-883f1c5c-05f3-4366-a818-512321952def.png">
Seem to be stuck on this page, how do I get in and set up a software wallet.

**Comment by craigraw** [comment]
Use the File menu at the top of the screen.
