### ISSUE TITLE
Forgot my pass word Sparrow Wallet

### ISSUE THREAD

**Issue by mirnamaria** [sparrowwallet/sparrow#887]
It wont let me import or reset my wallet

**Comment by craigraw** [comment]
There is not much information to go on here, but you if you have forgotten your password you need to recreate your wallet using your seed words or hardware wallet.

**Comment by ofcaah** [comment]
ok, not to open another similar issue: there's a wallet with somewhat forgotten password. Most of the password is known, so there are few thousand possible combinations. Friend managed to enter a correct password once, but couldn't repeat the feat again to transfer funds out. Recovery from seed doesn't discover any wallets for some reason - perhaps seed is password protected? One of the addresses that should correspond to the seed is known.

Is there a way to use hashcat to brute force either the seed or wallet password given that most of characters in password are known? Any other ideas? Thanks.

**Comment by craigraw** [comment]
Note: Passwords just protect the wallet file. Passphrases change the actual seed. Glad you recovered the funds.
