### ISSUE TITLE
Label import seems to ignore UTXO tab

### ISSUE THREAD

**Issue by MyNameIsOka** [sparrowwallet/sparrow#889]
First of all, thank you so much for all the work you put into this awesome software, Craig!

I tried importing my labels from Specter to Sparrow and did the following:
- export labels of UTXOs from Specter via Transactions --> UTXO --> Export
- bring the labels in the format as described in BIP329
- Import the file into Sparrow using File --> Import Wallet --> Wallet Labels

The transactions in the Transactions tab then get labels but not the UTXOs. I tried it with txIds, addresses and outputs but everytime it was the same.

**Comment by MyNameIsOka** [comment]
The exported data from Specter was in the following format
```
Date | Label | Category | Amount (BTC) | Value (USD) | Rate (BTC/USD) | TxID | Address | Block Height | Timestamp
2022-01-01 | myLabel1 | receive | 0.001 | not supported | not supported | f91d0a8a78462bc59398f2c5d7a84fcff491c26ba54c4833478b202796c8aafd | bc1q34aq5drpuwy3wgl9lhup9892qp6svr8ldzyy7c | 700000 | 2022-01-01 01:01:01
2021-01-01 | myLabel2 | receive | 0.002 | not supported | not supported | 8120a2181680d8703ea4a3a057d9607237875570e342b42acd5da4058be5616f | 37jAAWEdJ9D9mXybRobcveioxSkt7Lkwog | 70000 | 2022-01-02 01:01:01
```
I converted the data to the format:
```
{ "type": "tx", "ref": "f91d0a8a78462bc59398f2c5d7a84fcff491c26ba54c4833478b202796c8aafd", "label": "myLabel1" }
{ "type": "tx", "ref": "8120a2181680d8703ea4a3a057d9607237875570e342b42acd5da4058be5616f", "label": "myLabel2" }
```
And respectively for address:
```
{ "type": "addr", "ref": "bc1q34aq5drpuwy3wgl9lhup9892qp6svr8ldzyy7c", "label": "myLabel1" }
{ "type": "addr", "ref": "37jAAWEdJ9D9mXybRobcveioxSkt7Lkwog", "label": "myLabel2" }
```

and output:
```
{ "type": "output", "ref": "f91d0a8a78462bc59398f2c5d7a84fcff491c26ba54c4833478b202796c8aafd:0", "label": "myLabel1" }
{ "type": "output", "ref": "f91d0a8a78462bc59398f2c5d7a84fcff491c26ba54c4833478b202796c8aafd:0", "label": "myLabel2" }
```
In order to get the data for the output version, I manually copied the outputs that were shown in the UTXO view in Sparrow Wallet for the corresponding addresses.

**Comment by MyNameIsOka** [comment]
Nevermind, it worked now! Must have been a copy/paste miss from my side. I wish there would be a proper export function in Specter already...

**Comment by craigraw** [comment]
Great.

> I wish there would be a proper export function in Specter already...

Why not add a feature request issue there to add it?
