### ISSUE TITLE
Bitcoin Core, SOCKS: Connection refused 

### ISSUE THREAD

**Issue by initCCG** [sparrowwallet/sparrow#892]
Trying to connect to own node Bitcoin Core on Ronin Dojo.
Can connect to it with Samourai and Bisq. 

In Sparrow, using proxy 127.0.0.1:9050, the same onion address as used for Bisq, and RPC credentials, including non-standard Bitcoind port, that RoninDojo provides.

Still getting socks connection refused.
What to check?

**Comment by craigraw** [comment]
If you're running Ronin Dojo, it makes more sense (privacy and efficiency) to use either Electrs or Fulcrum. See https://wiki.ronindojo.io/en/setup/sparrow-wallet

**Comment by initCCG** [comment]
Electrs on Rpi 4 with Ronin Dojo is basically unusable in our experience. Most of the time, it wouldn't even finish the wallet refresh.
Fulcrum more often than not cannot survive even a momentary power interruption without corrupting its database, which takes more than a week to fix by resyncing.

It's a travel node. So, traveling with a UPS is not an option, and buying a UPS hat for it is unaffordable in our part of the world.
Where it goes, there are power interruptions almost every day.

**Comment by craigraw** [comment]
Fair enough, I can understand those challenges - I experience them myself. ElectrumX strikes a balance between the two BTW - it's more power interruption tolerant, and a lot faster than Electrs.

Wrt Bitcoin Core - connecting to Bitcoin Core over Tor isn't a great option, since anyone who gets hold of your onion address can determine your balance. But Sparrow does support this. Have you checked the Bitcoin Core debug.log to see if anything is logged?

**Comment by initCCG** [comment]
In there Bitcoind or tor logs, there is nothing. Not sure where to look in their container mess to figure this out.

Their bitcoind onion address changes after each reboot or power interruption. So, anyone who gets it, would only have it that long.
And if they can determine balance just by having an onion address, then they can determine balance on any onion address from which there is bitcoind traffic. No?

**Comment by craigraw** [comment]
> And if they can determine balance just by having an onion address, then they can determine balance on any onion address from which there is bitcoind traffic. No?

No - don't confuse P2P traffic on port 8333 with RPC calls on port 8332. Only the RPC calls can interact with wallets.

Are you able to connect to the Bitcoin Core instance on port 8332 using the onion address with Bisq?
