### ISSUE TITLE
Gap limit increasemnt on crossing it

### ISSUE THREAD

**Issue by rapidlab309** [sparrowwallet/sparrow#896]
Users who press multiply times (higher than the configured gap limit) the `Get Next Address` on `Receive` tab generate deeper addresses compared to the current gap limit.

Reeving TX to such addresses while Sparrow is closed may result with "missing" TXs.

**Comment by craigraw** [comment]
Thanks, this behaviour is improved in 4f6981b8, which ensures the wallet gap limit is increased and new addresses are subscribed to if an address beyond the current gap limit range is requested.
