### ISSUE TITLE
Wallet import flow could be improved by making the blue button pulse

### ISSUE THREAD

**Issue by nostitos** [sparrowwallet/sparrow#900]
I don't think it's clear what step is next when importing a seed.

Create Keystore?

Import Keystore?

At this point shouldn't we select or check for accounts on different address types?

By default it suggest to import 84' segwit derivation path,

Then we chose legacy from the script type up top?

Derivation is highlighted, in red, No way to edit it?

Then we expect the user to find the Replace button top right.
Not sure what it's replacing by what, The derivation box still show 84'

Then we start from scratch, Entering 12 words again

Import keystore...

Assume everything is fine on this page,  Find and click the bottom Apply button.

Contrast this with Electrum, that shows a "Detect existing account" right after entering the seed and present them all as such.
![image](https://user-images.githubusercontent.com/388716/225780706-33270c99-a1e7-4388-beeb-a6204543b9f9.png)

I honestly don't know understand what we're supposed to do at most of these preliminary steps so I don't think I can suggest an alternative that isn't a major change.

Ok, so I've hit a wall, Seems like we can't add a custom account number OR more than 10 accounts.

![image](https://user-images.githubusercontent.com/388716/225781359-af536ec6-2e09-42f8-b41f-1e3f5ce8a90e.png)

**Comment by nostitos** [comment]
I just stated from scratch, enter the words then enter my Derivation path of /44'/0'/9'

Why does it highlight it in red?  I don't want to replace it I want this one, 

But up top it say Native Segwit, 

It's pretty weird that the wallet assume a derivation path, show me some red warning that I need to replace, Instead of just asking me what derivation path I want.

It's very confuting to have this large page of information and button where more than half of them cannot be edited,

Like how am I supposed to know what can be edited?
Label? I already wrote a name to this wallet, what's BIP39 label?
So I can edit, BIP39, ok let's do that,,,?

Can edit Fingerprint, Same white box, 
Can't edit derivation, Same white box,
Can't change XPUB

Why do the boxes turn blue when clicking on them if nothing can be done about them?
![image](https://user-images.githubusercontent.com/48504624/225783185-45b0f2f1-04ee-4c25-8703-9957aa1cdde4.png)


Same white box, 

![image](https://user-images.githubusercontent.com/48504624/225782884-080eb54d-f9bd-4bf2-b00e-6a21734b5ce9.png)

Ok same thing, can't go higher than 9' even if starting at 9'.

It'd be great if we could just type the account number we want here.
![image](https://user-images.githubusercontent.com/48504624/225783425-95ffff44-5a1f-4322-8e02-020c186aa1b0.png)

**Comment by craigraw** [comment]
If you want to search for used accounts on a seed, use the File > Import Wallet > BIP39 option, and click Discover. Note Sparrow searches the first 10 accounts (as per BIP32) for every supported script type.

If you would like to use any arbitrary derivation path when importing your seed words, change the derivation path after you have entered the seed, but before you import:

![image](https://user-images.githubusercontent.com/862166/225961893-868fb0b1-97ed-4f89-84d2-4ed92ea5d0ba.png)
