### ISSUE TITLE
Sparrow Terminal: Freezing UTXOs

### ISSUE THREAD

**Issue by apemithrandir** [sparrowwallet/sparrow#901]
Could we add the ability to freeze UTXOs in Sparrow Terminal?

**Comment by craigraw** [comment]
Implemented in cb06e1aa. Pressing the `f` key on a UTXO will freeze and unfreeze it, indicated by `(f)` in the UI.

<img width="212" alt="Screenshot 2023-11-01 at 19 36 04" src="https://github.com/sparrowwallet/sparrow/assets/862166/cc069fba-1891-4853-864b-a8378d2b642c">
