### ISSUE TITLE
“ error fetching pools”

### ISSUE THREAD

**Issue by Kokorodom** [sparrowwallet/sparrow#902]
Having issues mixing coins. Getting “ error fetching pools” I’m connected to electrum w new hot wallet. Made a new one today and tried that too. I can receive and send but not mix.

**Comment by craigraw** [comment]
Are you using Tor? You can check if there is a Tor icon in the status bar.

**Comment by Kokorodom** [comment]
Yes my toggle is blue

**Comment by craigraw** [comment]
Can you try without Tor? It may be a Tor related issue.

**Comment by Kokorodom** [comment]
When I hover over the red onion icon beside blue toggle it says “ connection refused”. But toggle is blue …

**Comment by Kokorodom** [comment]
Can you tell me how to get out of tor?

**Comment by craigraw** [comment]
The red onion icon is Sparrow telling you your connection to the Tor proxy is not working.

There are two paths forward you can try:
1. Try a different Tor proxy. I suggest installing Tor Browser (if you haven't already) and configuring it to be the Tor proxy. Read this section of the docs for details: https://sparrowwallet.com/docs/mixing-whirlpool.html#starting-the-mix (note the port is `9150`). 
2. Disable Tor. I'm not sure if you are connecting to the Electrum server via an onion address or not. If connecting without an onion address, you can just disable the Use Proxy toggle. If connecting via an onion address, you'll need to find the IP of the server and use that instead (also disable Use Proxy in this case).

**Comment by craigraw** [comment]
Reported fixed on TG, closing.
