### ISSUE TITLE
Connection to Electrum Server (Raspiblitz) interrupted after succesfull mix

### ISSUE THREAD

**Issue by oPFGKk9gtuw8nuHkzrQn** [sparrowwallet/sparrow#903]
Using Sparrow 1.7.3 on Win 10.
Connected to Electrum on Raspiblitz via SSL and local IP address.

Lately, after a successful mix on Sparrow (as seen in log-file), within a minute or so, the connection to my Raspiblitz is lost and 
![grafik](https://user-images.githubusercontent.com/121948323/226206632-6848b46d-f646-44ca-b112-19563134c1c3.png)

It is possible to reconnect. However, all transactions and addresses have to be reloaded, which takes a lot of time and resources.
Sometimes even the reconnect does not work.

On the Raspiblitz, everything is fine, sparrow terminal remains connected and keeps mixing while Electrum Server is running.

**Comment by craigraw** [comment]
This is almost certainly an Electrs issue. Electrs struggles with deep wallets (see https://sparrowwallet.com/docs/server-performance.html) and could probably use a restart at this point. If the problem persists, rather install Fulcrum: https://openoms.github.io/bitcoin-tutorials/fulcrum.html
