### ISSUE TITLE
No TX or UTXO History 

### ISSUE THREAD

**Issue by kryptokarma** [sparrowwallet/sparrow#904]
Hi there guys
I loaded my Sparrow wallet a few days ago and noticed that no transaction history or UTXO was being displayed.
I had numerous addresses with inscriptions on them and they all seem to have gone….Ive updated the wallet but still its not displaying any history whatsoever and no sign of any inscriptions..Ive tried to load the wallet on another laptop but strangely when I input my seed and try to import the wallet…the message i get says no wallet exists..has anyone else had a similar issue? Would appreciate any help with this 

Thank you

**Comment by craigraw** [comment]
Are you using a passphrase? You have probably entered it incorrectly.

**Comment by kryptokarma** [comment]
Hi there…thank you for the quick response…yes I am using a pass phrase and it is entered correctly. The wallet loads but wont show any tx/UTXO  history

**Comment by kryptokarma** [comment]
Heres the screenshots / 
![696FC489-7924-4A6D-A565-2FED44737B1F](https://user-images.githubusercontent.com/47984652/226340428-78b638ff-6dce-4bcc-90b7-06b516d62b87.jpeg)
![5E1FC9F3-8037-4B7C-899F-2C177E177A4A](https://user-images.githubusercontent.com/47984652/226340456-6532a1d2-dce7-45ef-ad72-2ff1a76b8255.jpeg)
