### ISSUE TITLE
Antivirus notification using Sparrow tor, qwhw.com

### ISSUE THREAD

**Issue by Xaspr** [sparrowwallet/sparrow#907]
When connecting Sparrow to my node via tor I get the following message in antivirus software Bitdefender: 

> Suspicious web page detected
> X minutes ago
> Feature:
> Online Threat Prevention
> The page https://www.qwhw.com/ has been detected with suspicious activity. It is not recommended to continue browsing this website.
> Accessed by: tor.exe

I don't run tor on the computer, only the version via Sparrow, and was not doing anything else on the computer. It's running Windows 11 Pro. 

Any idea what this could be?

**Comment by craigraw** [comment]
No idea. Never seen that address before. Possibly another app is trying to connect to it when it detects Tor coming online?

**Comment by Xaspr** [comment]
Thank you. I'll check where this is coming from and post here when I find something.
