### ISSUE TITLE
Import wallet from coldcard made paperwallet

### ISSUE THREAD

**Issue by moskusminer** [sparrowwallet/sparrow#91]
Hi, how do i import wallet from paperwallet made with coldcard?
i have WIF

**Comment by craigraw** [comment]
Unfortunately, this is not yet implemented. Given the many documented issues with paper wallets, I'm not sure it's worth implementing, especially since these keys are not deterministic, or follow BIP32.

**Comment by moskusminer** [comment]
how about just watch only, its useful to have for following transactions to
paperwallet/ opendime?

tir. 6. apr. 2021, 08:28 skrev craigraw ***@***.***>:

**Comment by craigraw** [comment]
Unfortunately that's not really any easier to implement. I'd like to support this, but it's a lot of work for a relatively niche use case.

**Comment by 6102bitcoin** [comment]
Outstanding Action: Implement WIF import (paper wallet)
Proposed Priority: V. Low / NACK

**Comment by craigraw** [comment]
Agree, closing this off.
