### ISSUE TITLE
coin lost due to a potential bug

### ISSUE THREAD

**Issue by jleo** [sparrowwallet/sparrow#910]
I created a software wallet ,the script type was taproot, and then back up the seed and wallet. and I changed the script type to nested segwit, the wallet show me a new address and i sent some coin to that address, when I tried to send the coin out, it failed. So I tried to sign and verfify the message, it cannot pass the verfication. For now, I can only see the balance but can do nothing to send the coin out.
balance:
![image](https://user-images.githubusercontent.com/88640/226579268-58bac2ea-818d-4093-a3e3-2af257d3cb2f.png)
verification:
![image](https://user-images.githubusercontent.com/88640/226579503-d45fa60c-2a57-4790-afd8-6b132a032cb6.png)

I tried to debug and found that the signing address is not equal to the address which i send the coin to, but how is it possible that the wallet give me an address which cannot sign or send coin out?

i have the wallet.mv.db file and I can reproduce this procedure as many times as i want.

any suggestion would help,thanks

**Comment by craigraw** [comment]
Please send a screenshot of the Settings tab (obscure the xpub).

**Comment by jleo** [comment]
and even if the underlying path is m/86'/0'/0', when signing the message it still use the one i submit when changing the script type, so this is the biggest inconsistancy i think.
