### ISSUE TITLE
Error creating wallet on regtest network

### ISSUE THREAD

**Issue by somoza** [sparrowwallet/sparrow#912]
I am able to connect successfully to my regtest local network. Test connection shows success, and bottom-right icon is green.

![image](https://user-images.githubusercontent.com/1144980/227388996-15347baa-3ea4-4ced-9a99-5e317033799a.png)
![image](https://user-images.githubusercontent.com/1144980/227389037-17b82153-f016-4590-8525-c0fc8133c770.png)

As soon I create or open a wallet, I receive this error:
![image](https://user-images.githubusercontent.com/1144980/227389130-3b463257-3899-4361-94a3-2acc193a19d4.png)

I tried sparrow as mainnet and testnet mode using the Tools menu.

I tried curl commands like `bitcoin-cli -getinfo --rpcuser=testnet --rpcpassword=xxxx` and everything is ok...

What could be happen?

**Comment by craigraw** [comment]
As the error message suggests, upgrade Bitcoin Core to v24 or later for Taproot support. This will use Sparrow's new Cormorant library which leverages Bitcoin Core's descriptor wallet support.
