### ISSUE TITLE
Sparrow Window resize (in Windows 7+)

### ISSUE THREAD

**Issue by walitys** [sparrowwallet/sparrow#914]
On a small screen laptops (under 14") the Sparrow window does not fit into the screen. 
Thus the app window can not be resized or moved (for example aside). 
The app window can not be closed with the click on the "X" (top right of the window).

**Comment by craigraw** [comment]
See https://sparrowwallet.com/docs/faq.html#im-running-on-a-high-resolution-screen-and-sparrow-icons-and-text-are-tiny (set environment variable to 80%).
