### ISSUE TITLE
Can't sign partial taproot PSBT with connected Ledger hardware

### ISSUE THREAD

**Issue by kusan-thana** [sparrowwallet/sparrow#915]
I have same issue than people in issue https://github.com/sparrowwallet/sparrow/issues/883 :  can't seem to sign a partial transaction with the sighash type: Single + Anyone Can Pay

The transaction I try to sign: 
`cHNidP8BAF4CAAAAAfMW63lC/Wv5tXFLKCdKNnqhZuxCS++9ezsPev8j3LKuAAAAAAD/////AQDKmjsAAAAAIlEgT07EhbQ8+wkDlcB65GBJ40UA1jJba/q5fG6FICj7jsEAAAAAAAEA/TgBAgAAAAABApTnRDNzpcgSlJJGISoAod1WqRAXjVNfPEomaoBu13CjAgAAAAD/////yxPl4zn9Vx6SAT2z6okM2qLLqMcsbGq+vDiqvRnw7uECAAAAAP////8CECcAAAAAAAAiUSBPTsSFtDz7CQOVwHrkYEnjRQDWMltr+rl8boUgKPuOwXvQbAAAAAAAIlEgRH5IIvzrYt08CxvrEnBbJH6yGCJxm3tEWmFl2o5mNCYBQIzTnDlzr/07vczWAkAyMj6KWXQLF+Anb35TBpjc39LfY4rXkLCMcTCCCOpTNYK8qTFa85936uC/byLez7bknmMBQExOZyvIRQ4p4NjF2aWyPcBsYrw6skwLQBzgEEHe8XdZq7QXSN3CEMFepymF8Xd0z3Vucf9nXvewzkjhAxqqXaMAAAAAAQErECcAAAAAAAAiUSBPTsSFtDz7CQOVwHrkYEnjRQDWMltr+rl8boUgKPuOwQEDBIMAAAABFyAYVieBBfIHAp5fAO5iHy/WWgRzUGTR0Ui8XFL4Q6bDNgAA`

I think this is the related issue on the ledger side: https://github.com/LedgerHQ/app-bitcoin-new/issues/124

I think the issue in sparrow is that we don't get any result, no popup or message indicating any error after selection the ledger.

**Comment by craigraw** [comment]
Have you checked the Sparrow log file for any errors there?

**Comment by kusan-thana** [comment]
Yes, I have nothing in the log file.

I click The "Sign" button and the popup disappear and nothing on the ledger device:

![image](https://user-images.githubusercontent.com/14549979/227784074-4d923571-b67e-45ce-b5e3-1a6e7f038022.png)

**Comment by craigraw** [comment]
If there's nothing in the log file, then HWI is not returning an error response, it's just returning the unsigned PSBT. Suggest you open an issue there: https://github.com/bitcoin-core/HWI/issues
