### ISSUE TITLE
Feature Request: Send UTXOs in Postmix wallet back through whirlpool

### ISSUE THREAD

**Issue by InnocuousFinch** [sparrowwallet/sparrow#918]
Currently, if I want to mix some change outputs from Postmix spends, I have to send those UTXOs back to Deposit wallet, then send them through whirlpool again separately.

It would be nice if I could just select the UTXOs from Postmix that I want to run back through whirlpool. Samourai Wallet has this functionality.

**Comment by RequestPrivacy** [comment]
That would be great! 

I thought a show-stopper for this feature would be that if Sparrow is the only wallet allowing this, Sparrow users would be easily identifiable on-chain. But if Samourai is already having this.

Just think about multi-user Tx0's directly from postmix :heart: :eyes:

**Comment by nostitos** [comment]
I think a better feature would be to send all change from postmix spent to Badbank, 

Currently my wallet has been reusing the same large postmix change output in over 10 transactions into a long peel chain.
I'm puzzled why higher privacy is not an option, Seems like sparrow mixing only cares about breaking the link with pre-mix but doesn't care much about linking transaction post-mix together.

I don't want to risk my privacy to save on fees or something, I only want to spend sufficiently remixed utxo.

**Comment by checkuon** [comment]
> think a better feature would be to send all change from postmix spent to Badbank,

This would be a bad move in my opinion since those outputs might then be spent with unmixed change from tx0's. In any case forcibly moving users UTXOs from one account to another is a no go. 


> It would be nice if I could just select the UTXOs from Postmix that I want to run back through whirlpool. Samourai Wallet has this functionality.

Very much agree! Would be great if Sparrow could implement this.

**Comment by craigraw** [comment]
As of 31346e2a, the Mix Selected button has been added to the Postmix account UTXOs tab in both Sparrow desktop and terminal.

**Comment by RequestPrivacy** [comment]
Oh nice, thanks for your work!

**Comment by InnocuousFinch** [comment]
Thank you @craigraw!
