### ISSUE TITLE
Menu Dropdowns Not Functioning in Ubuntu

### ISSUE THREAD

**Issue by SometimesVishnu** [sparrowwallet/sparrow#920]
File, View, ect drop-down menus are not opening. I have tried reinstalling sparrow and installing older versions of the .deb file. Ubuntu is up to date and a fresh install. 

I found one other issue close to mine, but not exactly the same problem. Any help would be appreciated! 

https://github.com/sparrowwallet/sparrow/issues/170

**Comment by craigraw** [comment]
What window manager are you using? Ubuntu is extremely well tested, so it sounds like something is unusual with your setup.

**Comment by SometimesVishnu** [comment]
Probably so. I am struggling to find a solution though. Thanks for the response. 

wmctrl output:

Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF

**Comment by craigraw** [comment]
Same output from `wmctrl` here. I don't have any good suggestions unfortunately - is this a stock Ubuntu install? Which version?

**Comment by SometimesVishnu** [comment]
No problem. I appreciate the responses. Version 22.04.2 LTS. I have only installed a couple of programs so far. No major changes. I've tried uninstalling sparrow and reinstalling no luck their either. 

I'll close the issue though. I'm sure it's something on my side.
