### ISSUE TITLE
allow non randomize input/output orders

### ISSUE THREAD

**Issue by satoshi0770** [sparrowwallet/sparrow#921]
sparrow wallet being a privacy first wallet, has randomizing input and output orders by default.
sparrow wallet has very good coin control, thus being an excellent wallet for ordinal theory and inscriptions.
ordinal theory follows first in first out principles for inputs and outputs.
would be a great feature to allow non randomize for input and output ordering.

example, 
1
if wanting to send 5 utxos of 10k sats each to specific addresses.
5 x 10k sat inputs + another input for fees.
5 x 10k sat outputs + another output for change of fees.
its important that the fee and change fee output is the last in the ordering, otherwise it will mess up with ordinal theory principles of first in first out.
2
if someone has a combined inscriptions into 1 utxo, and the inscription ordinals are at different offset in this utxo.
it would be extremely difficult to order the outputs properly when the output orders are being randomized each attempt.

conclusion, sparrow wallet having amazing coin control, is an extremely good wallet for ordinal/inscription enthusiasts.
allowing an option to non randomize input and outputs can be very powerful tool.
(possible to have this under advanced settings, with a disclaimer that removing randomization will hurt privacy and only power users that know how to use this feature will even use it.)

thank you

**Comment by rapidlab309** [comment]
Nay. Would be harmful for new users.

**Comment by Psifour** [comment]
I already do this in my local fork, but having it as an option (maybe even at the time of creating the transaction) makes much more sense. Doing so would enable users to choose which of the two behaviors was better for their specific use-case.

**Comment by dannybabbev** [comment]
I agree, this is an important feature. Advanced users would want full control of the transaction building.

**Comment by RobertClarke** [comment]
+1

**Comment by donnlee** [comment]
Sparrow really needs this IMO. Many ordinals/inscriptions tutorials suggest using Sparrow because it has good coin control and utxo freezing/labelling.
And ordinals use is growing.

I once had 6 outputs that needed a single unique order for ordinals. I had to re-roll the random outputs over 200 times. It was hypnotizing, but no fun.
Next time I may have to write a bitcoinjs script. Ug.
But Sparrow can make this an advanced setting and make bitcoining better for thousands of us.

**Comment by RobertClarke** [comment]
This is a good fix, even if you don't acknowledge ordinal theory. For applications such as being dependent on specific output ordering to send funds further onwards, programmatically.

**Comment by craigraw** [comment]
As of Sparrow v1.8.2 it is possible to reorder inputs and outputs before the transaction is finalized by dragging and dropping them in the transaction tree on the left of the transaction tab. Labelled inputs will make this simpler.
