### ISSUE TITLE
NFC hardware wallet option should be visible regardless of the required hardware presence

### ISSUE THREAD

**Issue by streamofstars** [sparrowwallet/sparrow#923]
According to issue https://github.com/sparrowwallet/sparrow/issues/535 Sparrow Wallet since 1.7.2 supports NFC wallets e.g. Tapsigner or CoinKite MK4. I have Sparrow 1.7.3 and don't see that option. This is probably because I have no required hardware (NFC reader). Seems logical, one would say. IMHO actually it is not. Again IMHO, all options should be visible regardless of the hardware presence. If the required hardware is absent then the software should make related features inactive and grayed out but still visible to the user. A tooltip may be added with appropriate info about the option's inaviability because of missing hardware. Why like this? Because when I first heard about solutions like Tapsigner I just opened my Sparrow Wallet software and looked for NFC on the list of airgapped hardware wallets which was not there. Only after I googled that I found out that it is actually supported and the option shows up when the NFC reader is connected and NFC wallet/card present on the reader.

**Comment by craigraw** [comment]
> Again IMHO, all options should be visible regardless of the hardware presence.

Do you also think all supported USB hardware wallets should be shown regardless of whether they are connected or not?

**Comment by streamofstars** [comment]
OK, you are right about this part. But NFC ones go on the airgapped hardware wallets list which are explicitly listed. I know there is a technical reason to listing those wallets explicitly but it is not necessarily obvious to a random user.

**Comment by craigraw** [comment]
That's a fair point. I've made this change in 483e4c8f - Tapsigner will now always appear in the airgapped options, but an error will be shown if the Import button is clicked and no card reader is connected.

<img width="453" alt="Screenshot 2023-04-05 at 08 25 50" src="https://user-images.githubusercontent.com/862166/229998343-eb71dee9-9c08-42d1-9307-6bd0ca778a31.png">
