### ISSUE TITLE
Border Wallet grid import

### ISSUE THREAD

**Issue by nostitos** [sparrowwallet/sparrow#927]
![image](https://user-images.githubusercontent.com/48504624/230181885-f76d9cf8-bef6-413c-9f6d-deefbc2647ad.png)

Import PDF
Select 11 words
Clicking OK, 

Nothing happen.

**Comment by craigraw** [comment]
The Number grid is not supported in v.1.7.4, but I've just added support in 04145bde. Thanks for reporting.
