### ISSUE TITLE
Unable to connect because cormorant database already exists

### ISSUE THREAD

**Issue by nR2Cncdm** [sparrowwallet/sparrow#931]
I'm seeing this error when loading Sparrow. 

Connection failed: Wallet file verification failed. Failed to create database path '/Users/admin/Library/Application Support/Bitcoin/cormorant'. Database already exists.

I'm running Bitcoin Core version v24.0.1 on a Mac M1, and the Bitcoin data directory is on an external drive symbolic linked to  /Users/admin/Library/Application Support/Bitcoin.

I've deleted the cormorant folder, restarted Sparrow, and still see the same error. A new cormorant folder is created within my Bitcoin data directory, and then the error happens in Sparrow moments later.

Thanks in advance for your help!

**Comment by craigraw** [comment]
This error is coming from bitcoind directly, probably due to the symbolic link. I would try to get the creation and loading of Bitcoin wallets working via `bitcoin-cli` - it may be that a different approach to wallet data location is needed.
