### ISSUE TITLE
Problem to import  tapsigner key error 0x6a80

### ISSUE THREAD

**Issue by d6n13l0l1v3r** [sparrowwallet/sparrow#936]
when I try to import my tapsigner key I got the follow error 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/25048143/231156398-ca524ee9-f836-45b0-b58f-a24dba6f3b09.png">

`2023-04-11 14:00:12,798 ERROR [Thread-134] c.s.s.i.c.CardTransport [null:-1] Card initialization error, response was 0x6a80
2023-04-11 14:00:16,277 ERROR [JavaFX Application Thread] c.s.s.i.c.CardTransport [null:-1] Card initialization error, response was 0x6a80`

the the card is working fine I check it with the cktap tool 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/25048143/231155438-d13eab6a-6fb3-47b3-961a-dc5ca97f735d.png">

NFC Reader : ACR122U
Sparrow: 1.7.4
MacOS 13.3.1

**Comment by d6n13l0l1v3r** [comment]
Hi. I found the issue 

I my computer I have other smart card reader to handled a personal certificate in cloud (UKC SignCloud PC) and look like the sparrow only check reader 01 and not give the alternative to tell what need to use

```

~ pcsctest -f

MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: UKCVReader
Reader 02: ACS ACR122U
Enter the reader number          : 


```
after uninstall this  smart card reader, 

```
pcsctest -f

MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: ACS ACR122U
Enter the reader number          : 
```

work property ok 

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/25048143/231389942-9c5da4a0-2344-4012-af25-e98c1fd7bdf5.png">


Anyway in my personal point of view this is a error that need to be fix, don't have sense to me that I need to uninstall other smart card reader in order to be detect by sparrow , if it can no be automatic at lease give us the alternative to specify the  reader need to use

**Comment by craigraw** [comment]
Multiple card terminal support added in 98d9a688. Sparrow will now try all connected card terminals for supported cards, and use the correct one when a supported card is found.
