### ISSUE TITLE
Unable to create transaction on Taproot wallet

### ISSUE THREAD

**Issue by Novenqingtang** [sparrowwallet/sparrow#937]
Wallet type: mnemonic generate by sparrow
Script Type: Taproot (P2TR)
Path: m/86'/0'/0'/0/10
OS: macOS (Monterey)

Steps to reproduce:

1. Create wallet by mnemonic which generate by sparrow, and wallet script is default (P2WPKH)
2. Send some btc to bench32 address index 0 - bc1qngcfag0hvc8d0v7m2m88hxu5fvg65uffen55qz
3. Switch script type to Taproot (P2TR) , get address index 10 - bc1prgl5pn3nwh4tue7vfxr2hclt6fmuxd96s9p8zr836gn8g5p5s68qp4md5w
4. Send some btc from bech32 index 0 to taproot index 10,  and the balance is correct shown in taproot index 10
5. Try sending to bench32 address index 1 from  taproot index 10, can not **create transaction**!

<img width="1268" alt="t1" src="https://user-images.githubusercontent.com/20578889/231367013-34aadd8a-01ab-4797-a9b6-c9e9152806e3.png">
<img width="1271" alt="t2" src="https://user-images.githubusercontent.com/20578889/231367037-805dd83f-684e-4498-89dd-4bdd0947fa43.png">

Why, and how to transfer out from the taproot address, please 🙏

**Comment by Novenqingtang** [comment]
More informations, the taproot address generated by Sparrow does not match the address produced by bitcoinjs-lib with the same mnemonic which generated by Sparrow wallet, and It cannot be used for ord wallets either. 
I don't know what their differences are.

**Comment by craigraw** [comment]
I suggest recreating the Taproot wallet as a new wallet, but with the original derivation path (probably m/84’/0’/0’). You will need to disable derivation path validation in the General Preferences to do this. 

If you changed the script type, you probably changed the derivation path too which would cause these issues. Also, make sure you are using Sparrow v1.7.4.
