### ISSUE TITLE
One of the Taprot addresses is different from the one calculated by the program

### ISSUE THREAD

**Issue by Novenqingtang** [sparrowwallet/sparrow#938]
- Mnemonic is same
- Only index 10 is different

Correct is    bc1p9jwrj4gtmgm53dqvpa6n20yfxh6gjpu9uy45wepkkrxs8yc0w4rs0zrfdg
Sparrow wallet is   bc1p9jwrj4gtmgm53dqvpa6n20yfxh6gjpu9uy45wepkkrxs8yc0w4rs0zrfdg

<img width="1724" alt="t4" src="https://user-images.githubusercontent.com/20578889/231423146-5aa3a23b-7102-41b0-b579-44fe61c15265.png">

**Comment by craigraw** [comment]
Please don’t open multiple issues.
