### ISSUE TITLE
Unable to import json from Specter Desktop

### ISSUE THREAD

**Issue by freddiemacd** [sparrowwallet/sparrow#939]
I tried to import a wallet using the json file generated from specter desktop but when I try it gives an import error saying the file is not in json format. I looked at the file and it is a json.

**Comment by craigraw** [comment]
The only logical reason for this to occur is that the JSON is not correctly formatted. Iirc Sparrow already does some cleaning up of the Specter provided JSON in the import code. If you can find out what’s wrong I can try to add to it.

**Comment by freddiemacd** [comment]
I've anonymized what the json file looks like here.

`{
    "name": "wallet1",
    "alias": "wallet1",
    "description": "Single (Segwit)",
    "address_type": "bech32",
    "address": "bc1qxxx",
    "address_index": 1,
    "change_address": "bc1qyyy",
    "change_index": 0,
    "keypool": 300,
    "change_keypool": 300,
    "recv_descriptor": "wpkh([abcdefg/84h/0h/0h]xpub6xxx/0/*)#zjt496g5",
    "change_descriptor": "wpkh([abcdefg/84h/0h/0h]xpub6yyy/1/*)#nxw5c0cv",
    "keys": [
        {
            "original": "zpub6xxx",
            "fingerprint": "abcdefg",
            "derivation": "m/84h/0h/0h",
            "type": "wpkh",
            "purpose": "Single (Segwit)",
            "xpub": "xpub6xxx"
        }
    ],
    "devices": [
        "a"
    ],
    "sigs_required": 1,
    "blockheight": 707381,
    "pending_psbts": {},
    "frozen_utxo": [],
    "last_block": "000000000000000000034b0dc6f7221b8a91f1eefd545d3935b082d791efc91f"
}`
