### ISSUE TITLE
BSMS import does not create a usable wallet

### ISSUE THREAD

**Issue by Brice123456789** [sparrowwallet/sparrow#940]
Hello,

I am trying to import a BSMS file (2of3 multisig) produced by Nunchuk (Android) into Sparrow.

Almost all the "Settings" page is there (except I can't export the wallet), but the other ones are grey ("Transactions", "Send", etc.), as you can see on the screenshot.

I expected to be able to use it as any wallet. Have I missed something?

Sparrow 1.7.4
Kubuntu 22.04 LTS
![Sparrow](https://user-images.githubusercontent.com/51496446/231474859-90c56e8e-a176-46ef-83a2-95f8566a00cf.png)

**Comment by craigraw** [comment]
As indicated by the red outlined text, there is a problem with Keystore 3 - a missing or invalid field, or perhaps a non-standard derivation path. If it’s the latter you can turn off derivation path validation in the General Preferences.

**Comment by Brice123456789** [comment]
Thank you. It works with your trick.

The problem may come from Nunchuk.
