### ISSUE TITLE
Feature request: printable backup

### ISSUE THREAD

**Issue by freddiemacd** [sparrowwallet/sparrow#943]
I have been a multi-year user of Specter Desktop but was prompted to try out Sparrow Wallet due to an almost unusable Specter Desktop update to v2. After now using both wallets, I think that Sparrow is better than the v1 version of Specter, but there is a feature that Specter has that I could not find in Sparrow. If it exists, let me know.

Specter allows me to export a pdf with the QR code to recreate the wallet, Specter raw wallet data, and the bitcoin core descriptors. I actually had to use that to get Sparrow to import by using the QR code because Sparrow could not recognize the Specter json file for unknown reasons. I think having a printout is a great redundant backup solution for my multi-sig wallet. I keep a copy of it with each secretly and separately stored seed words so that the wallet can be restored from that if necessary.

If this does not already exist, I think it would be a great addition.

**Comment by craigraw** [comment]
Check the QR button on the right of the Descriptor field on the Settings tab. The dialog contains a PDF export function.
