### ISSUE TITLE
In order to build the binaries from source in ubuntu, I needed to add 'installerType = "deb"' for linux in build.gradlew

### ISSUE THREAD

**Issue by freddiemacd** [sparrowwallet/sparrow#945]
I had an error with jpackage when trying to build the binaries from source on ubuntu. `Error: Invalid or unsupported type: [rpm]`

I added in `installerType = 'deb'` under `if(os.linux)` and then it built the binary.

**Comment by craigraw** [comment]
Did you run
```
sudo apt install -y rpm
```

as instructed?

**Comment by freddiemacd** [comment]
> Did you run
> 
> ```
> sudo apt install -y rpm
> ```
> 
> as instructed?

I don't think I did and looking through my terminal history, I did not.

**Comment by craigraw** [comment]
Please take care to read the instructions before opening issues. This is not a support desk - Github issues are for reporting bugs or feature requests.
