### ISSUE TITLE
Info Request: Timelocks

### ISSUE THREAD

**Issue by abradshaw** [sparrowwallet/sparrow#946]
Can sparrow wallet use timelocks and if so can you point me to the docs please?

I tried the setting under Absolute Locktime, I selected date and set it 1 day in the future but I got an error about "rejected by the network"

Many thanks, love Sparrow Wallet

**Comment by craigraw** [comment]
Can’t broadcast a tx with future dated absolute timelock. Read https://medium.com/summa-technology/bitcoins-time-locks-27e0c362d7a1
