### ISSUE TITLE
Can't create a watch only MultiSignature wallet with XPubs alone

### ISSUE THREAD

**Issue by BTCBellyButton** [sparrowwallet/sparrow#947]
The derivation path is mandatory when creating a "MutiSignature watch only wallet" for each XPub.
But that shouldn't be the case since, for example, Electrum does it with no problem just with the 3 xpubs of a 2of3 msig. 

If you have an Unchained Capital IRA vault (2of3) you do not know their xpub derivation path: 

```
 "extendedPublicKeys": [
    {
      "name": "Unchained",
      "xpub": "xpub6......",
      "bip32Path": "Unknown",
      "xfp": "fb73200b"
    },
    {
      "name": "Key 1",
      "xpub": "xpub6.....",
      "bip32Path": "m/45'/0'/0'/0",
      "xfp": "aead8e67"
    },
    {
      "name": "Key 2",
      "xpub": "xpub6....",
      "bip32Path": "m/45'/0'/0'/0",
      "xfp": "646a963d"
    }
  ]
```

So you can't have a watch only with Sparrow in this kind of cases.

**Comment by craigraw** [comment]
You can fill in the suggested default path (shown when the field is empty), or any other legal path. The derivation path is present in any PSBTs, and used by signers to verify before signing. Because you don’t need to sign for the Unchained keystore, the derivation path is less important.

Many ppl use Unchained wallets in Sparrow for watch only and signing transactions.

**Comment by BTCBellyButton** [comment]
Well, I tried that again.

It doesn't work, no matter what derivation I put:

![image](https://user-images.githubusercontent.com/68573637/232339220-d492d3a2-6d13-4fc9-b730-3459c7b666a2.png)

![image](https://user-images.githubusercontent.com/68573637/232339104-71a855bd-2069-4c74-a4be-cb2dc90787d3.png)

**Comment by craigraw** [comment]
You are using the wrong script type. Unchained wallets use a Legacy (P2SH) script type.

**Comment by BTCBellyButton** [comment]
Dammit.
You're right. Thx!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
