### ISSUE TITLE
RBF Failure Error Message

### ISSUE THREAD

**Issue by apemithrandir** [sparrowwallet/sparrow#949]
Could the error message dialog box for RBF failure be improved by grabbing the output of the log file.
Currently when you have sent insufficient fees you get as far as the broadcast tx dialog and this Error Box pops up:
![errorB](https://user-images.githubusercontent.com/99969638/233765387-3c737e72-1fc9-4736-a99d-7efdb914292d.png)
Checking the logs will reveal a message like this:
`less fees than conflicting txs; 0.0000xxxx < 0.0000yyyy`
Or potentially like this:
`not enough additional fees to relay; 0.0000xxxx < 0.0000yyyy`

This might only occur in the case where the outputs of the tx you are trying to RBF has been used in a subsequent tx (I'm not sure how it would appear otherwise). But it could be nice if the in-app dialog box included something like:
`Your tx has been used in a another tx you must pay at least yyyy sats to be successful.`
I also don't know if information like this can be worked out earlier in the process like during the transaction construction menu or if the information only becomes available once you try to broadcast the tx.

**Comment by craigraw** [comment]
Good idea, implemented in 3cf99961.

<img width="472" alt="Screenshot 2023-05-25 at 14 49 50" src="https://github.com/sparrowwallet/sparrow/assets/862166/ed09e483-6400-40fb-9e63-78e627047655">
