### ISSUE TITLE
UX glitch is causing address reuse when receiving

### ISSUE THREAD

**Issue by alpha-centauri-21** [sparrowwallet/sparrow#95]
On the [Receive] tab Sparrow should never propose an address if there is any hint this address has been used.

Currently, when incoming tx is unconfirmed, Sparrow continues to show the old address by default, at least for a while. Yes, there is a red warning icon below but that is very easy to miss and it does not follow the "privacy by default" rule.

The expected behavior is to *always* generate a new address on any suspicion the previous one was used.

**Comment by craigraw** [comment]
I've tried to follow the generally accepted advice of not changing things in the UI without the user specifically requesting it, and changing the receive address certainly breaks that rule IMO. In fact, it could easily cause user consternation - (where did my address go? Are my funds now lost?). I had thought the red warning was pretty obvious. Happy to consider further warnings, but I don't think replacing the currently displayed address with a new one is a good idea.

**Comment by alpha-centauri-21** [comment]
The way I see it by this time (incoming tx) the past address value is simply incorrect.

Maybe a middle ground is Electrum's approach. Make the input field **itself** red and put the ~"get fresh address" button right there?

I personally missed the visually detached warning and did reuse the address today when testing Sparrow (testnet, no big deal).

Hope this helps!

**Comment by craigraw** [comment]
Implemented in d52bade - when Sparrow detects the address has been used, it highlights the address field in red (the failing validation textfield appearance).

I'm going to close this off - I think it would be very difficult to miss now.
