### ISSUE TITLE
Wallet birth date reverts

### ISSUE THREAD

**Issue by Gfawkes** [sparrowwallet/sparrow#950]
Ive recently used Wasabi to increase my privacy with coinjoins. Ive noticed a significant difference (23%) between Wasabi and Sparrow balances. 
I believe this might be because Sparrow Wallet is not using Taproot but Wasabi does. So the wallet was imported again but this time using Taproot. This seems to work fine until I want to change the wallet birth date to include any former transactions that have been taking place before yesterday. The software saves the new birth date but once loading the transactions, reverts to the former birth date, which is yesterday (22.4.2023). Is this know?

EDIT:
It seems that there is a gap between the older p2wpkh and taproot since the balances of the two wallets add up to the amount shown in wasabi wallet. Is there a way to combine these?

**Comment by craigraw** [comment]
The wallet birthdate is set to the date of the earliest found transaction. There is no way to combine balances currently.
