### ISSUE TITLE
Multisig transaction signing error with Ledger on M1 Mac

### ISSUE THREAD

**Issue by GambolingPangolin** [sparrowwallet/sparrow#951]
## Version details

M1 Mac @ Ventura 13.3.1

Ledger Nano S Plus
- Firmware: 1.1.0
- Bitcoin App: 2.1.1

Sparrow version: 1.7.6 (via Sparrow-1.7.6-aarch64.dmg)

## Description

When we attempt to sign a PSBT for a 2-of-4 native segwit multisignature output, it fails.  Here are the steps:

- Open Sparrow and relevant wallet
- Open PSBT
- Connect and unlock Ledger; enter Bitcoin App
- Sign Transaction, Scan, Sign
- Go through Register Wallet workflow
- Drop back to Sparrow and see the error `('0xb007' , 'Error in <BitcoinInsType.REGISTER_WALLET:2> command' , ")`

**Comment by craigraw** [comment]
Where was the PSBT created? Can you reproduce this if Sparrow creates the PSBT?

**Comment by GambolingPangolin** [comment]
> Where was the PSBT created? Can you reproduce this if Sparrow creates the PSBT?

We used Sparrow 1.7.6 on Ubuntu 22.04 to create the PSBT.  I used Bitcoin Core's `decodepsbt` and `analyzepsbt` commands to inspect the PSBT and all expected fields are populated, including `GLOBAL_XPUB`.

**Comment by craigraw** [comment]
Are all keystores using the default derivation path? m/48’/0’/0’/2’

Some hardware wallets are restrictive about which derivations they will allow.

**Comment by GambolingPangolin** [comment]
> Are all keystores using the default derivation path? m/48’/0’/0’/2’

In this particular instance, yes.

**Comment by craigraw** [comment]
Is there any further information in the log file regarding the error? See Help menu to find the log.

Multisig signing using a Ledger is well tested (including registering a wallet) so this error is unusual, and seems to be related to the structure of this multisig setup.

**Comment by GambolingPangolin** [comment]
Here are the relevant log lines.  I don't see anything illuminating, myself.

```
2023-04-26 12:55:57,969 ERROR [JavaFX Application Thread] c.s.s.c.DevicePane [null:-1] Signing Error: ('0xb007', 'Error in <BitcoinInsType.REGISTER_WALLET: 2> command', '')
com.sparrowwallet.sparrow.io.SignTransactionException: ('0xb007', 'Error in <BitcoinInsType.REGISTER_WALLET: 2> command', '')
	at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.io.Hwi.signPSBT(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.6/com.sparrowwallet.sparrow.io.Hwi$SignPSBTService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by craigraw** [comment]
Just checking something obvious - you imported the Ledger as a keystore in this wallet prior to signing?

Also, can you verify in the Sparrow config file that the `hwi` variable is pointing to HWI 2.2.1? The version will be somewhere in the path, or you can execute `hwi --version`.

**Comment by GambolingPangolin** [comment]
I am happy to report that one of the keystores was badly misconfigured.  Ordinarily, we set up wallets in Sparrow by setting the descriptor, then can sign with a ledger that matches the keystore even if we skip the import step.  When I had my user import their ledger it completely changed the keystore.  So I consider this particular issue resolved.

Do you have an opinion on [BIP 129](https://github.com/bitcoin/bips/blob/master/bip-0129.mediawiki) and its suitability for Sparrow?  Having a first class workflow for setting up a multisig where the signers are all remote would make a big difference in my quality of life!

**Comment by craigraw** [comment]
Good to hear you found the issue. BIP 129 is already implemented - when creating a multisig wallet and after importing a keystore, an Export button is shown on the keystore tab panel which exports a Round 1 BSMS file to share with other signers. The Round 2 BSMS file can be exported from the File > Export Wallet dialog after the multisig wallet setup is complete.

**Comment by GambolingPangolin** [comment]
Wow!  That is a very nice surprise.  It is quite impressive how you are able to deliver such a huge feature set.  Keep up the good work @craigraw !

**Comment by GambolingPangolin** [comment]
Playing around with the BSMS functionality, I have a few questions:

- Is the Sparrow implementation of BSMS documented anywhere?
- What is the coordinator supposed to do with the round 1 files?  It seems like it should be an option to import the file in the keystore setup panel.

I tried to use File > Import Wallet with the attached file and got an error:

```
Caused by: java.lang.IllegalArgumentException: Unrecognised extended key header for mainnet: 00
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.ExtendedKey$Header.fromExtendedKey(Unknown Source)
	at com.sparrowwallet.drongo/com.sparrowwallet.drongo.OutputDescriptor.getOutputDescriptor(Unknown Source)
	... 130 common frames omitted
```
[bip39.bsms.txt](https://github.com/sparrowwallet/sparrow/files/11359683/bip39.bsms.txt)

Is that supposed to work or should the Import Wallet workflow only succeed for round 2 documents?

**Comment by craigraw** [comment]
You can import the Round 1 BSMS exports using the BSMS option in the Airgapped panel for keystore imports when setting up a multisig wallet.

And yes, this needs a guide - I'm planning on writing one :)

**Comment by GambolingPangolin** [comment]
Ok cool.  It does make sense to have it as an Airgapped keystore, and that import flow worked for me.  Thanks for the help!
