### ISSUE TITLE
can sparrow customize the transaction output?

### ISSUE THREAD

**Issue by walterliang** [sparrowwallet/sparrow#956]
HI,DEV:
How to customize the output, for example, I want to take 10 UTXOs under address A as input, output 10 UTXOs to address B in full, and specify the 11th UTXO as fee to consume.

after Odinals, Transferring UTXOs in bulk has become a huge demand.

**Comment by rapidlab309** [comment]
Sparrow never meant to be an Ordinals wallet.

**Comment by craigraw** [comment]
> How to customize the output, for example, I want to take 10 UTXOs under address A as input, output 10 UTXOs to address B in full, and specify the 11th UTXO as fee to consume.

This is not how Bitcoin works. All input UTXOs are consumed completely in every transaction, and new outputs are created. Bitcoin has no concept of "use this UTXO for the fee".
