### ISSUE TITLE
Connection error to full bitcoin node running in raspi 4 8GB, OS on external UDB-Disk

### ISSUE THREAD

**Issue by franjea** [sparrowwallet/sparrow#957]
I run 3 full synced bitcoin core nodes on raspberry pie's, installed following the (excellent) guide **_raspibolt_** done by STADICUS (V3)

I can connect Sparrow without any problem to 2 of the nodes, but for the 3rd, I get the following error when I try to test the conncetion:

_Could not connect:

Error getting fee estimates_

What can cause this in my blochchain?

Franz

![Sparrow connection error](https://user-images.githubusercontent.com/8944865/236169340-c8b9b474-6cca-4c8a-b5ec-eda2c6e78159.png)

Please help me! Thanks in advance!

**Comment by craigraw** [comment]
Are you still experiencing this error? My guess is that it was related to the full mempool, and Bitcoin Core struggling to provide fee estimates based on so much data. Things may have improved now.

**Comment by craigraw** [comment]
No response, closing this off.
