### ISSUE TITLE
Error while trying to import simple "word" QR code

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#958]
Create a new wallet, and:

1. Click "New or Imported Software Wallet"
2. Drop-down -> Click "Scan QR"
3. Scan a simple QR containing plain words.
4. Error: Invalid QR Code.

Example QR containing:

calm mind moral shock mad maid moment sport supreme mosquito huge region secret flash dignity control credit defense left pitch author school walnut mention

<img width="287" alt="image" src="https://user-images.githubusercontent.com/93251679/236620541-cd68459e-43c0-4c08-9ad2-a13a5b0f08ce.png">

**Comment by craigraw** [comment]
I imagine this will be simple to add - will address it soon.

**Comment by craigraw** [comment]
Implemented in b52be27a.
