### ISSUE TITLE
Password issue for login

### ISSUE THREAD

**Issue by rcardlesmalldick** [sparrowwallet/sparrow#960]
Hi team, I want to ask that I create my wallet and I didn't set the password before, and after I restart computer and then open wallet. It told me I need to input my password, and now I cannot login, can you help? Thank you.

**Comment by craigraw** [comment]
You may be confusing a passphrase with a password. See the FAQ: https://sparrowwallet.com/docs/faq.html#all-my-addresses-have-changed
