### ISSUE TITLE
how to send brc-20 in sparrow wallet 

### ISSUE THREAD

**Issue by Valuebai** [sparrowwallet/sparrow#961]
hey, bro, help, how to send brc-20/$ordi to unisat or exchange in sparrow wallet, can you send some guide? i can't find any guide in sparrow wallet website

i import my recovery words into sparrow wallet , and the wallet has some brc-20 in it, but I don't know how to send it to exchange or unisat to trade

**Comment by craigraw** [comment]
I'm no expert on BRC-20, so I'll just provide the general advice for sending ordinals:

In the UTXOs tab select only the ordinal UTXO. Click the Send Selected button. The Send tab will open and you can enter the destination address and label. Make sure in the transaction diagram you are only spending one input! Click Create Transaction, finalize, sign and broadcast.
