### ISSUE TITLE
Block explorer option should display protocol and port

### ISSUE THREAD

**Issue by climardo** [sparrowwallet/sparrow#962]
When entering a block explorer address in preferences, Sparrow automatically uses `https`. When running mempool locally, it runs on `http`. Also the interface does not display the port, but this is also often set to a non-default value when running mempool locally. As a workaround, users can set this value in `~/.sparrow/config`.

**Comment by craigraw** [comment]
I try to keep the interface simple and uncluttered. Is there a particular need to show this information on the drop-down? You can enter the full URL, including the protocol and port in the Custom... entry dialog - no need to directly edit the config file.

**Comment by climardo** [comment]
When i entered `http://10.0.0.3:4080` it tried using `https://10.0.0.3:4080` until I changed it in the config file

**Comment by craigraw** [comment]
I can't reproduce this - entering `http://10.0.0.3:4080` results in that same value entered into the config file, and then passed to the browser. Possibly there is a redirect in the browser to `https`?

**Comment by climardo** [comment]
I wouldn't be surprised if it's just me, but it worked fine with the same browser (Firefox), with no changes to the browser setting, after setting it in the config. Thanks for engaging on this. And eager to hear you on RHR today. let's to close this.

**Comment by climardo** [comment]
p.s. i must have not entered the protocol `https://`. i just was also unable to reproduce just now. thanks again for all of your hard work on making this software virtually dummy proof
