### ISSUE TITLE
Unconfirmed (Spendable) although RBF transaction is already confirmed 

### ISSUE THREAD

**Issue by stebystep** [sparrowwallet/sparrow#963]
Hi Guys,

I have one transaction that was created but rejected by my node due to the initial low fee defined. I then applied RBF successfully and the new transaction is now confirmed. However Sparrow is keeping the initial UTXO as spendable, leading to a wrong balance account and also is still showing the initial transaction as Unconfirmed, although RBF transaction is already with hundreds of confirmations.

Sparrow 1.7.6

Any thoughts on how I can get rid of the Unconfirmed transaction ? This unconfirmed transaction can't be found in mempool since my node never broadcasted it due to min relay threshold.

**Comment by craigraw** [comment]
Refresh the wallet. View menu. The server you are connected to did not notify Sparrow correctly.

**Comment by stebystep** [comment]
Thank. you Craigraw, this worked.
