### ISSUE TITLE
Child Pays For Parent (CPFP) Error

### ISSUE THREAD

**Issue by Odellian** [sparrowwallet/sparrow#965]
Hi, I received the following error when attempting Child Pays For Parent (CPFP) transaction.  

"ERROR [JavaFX Application Thread] c.s.s.t.HeadersController [null:-1] Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: the transaction was rejected by network rules.

bad-txns-inputs-missingorspent

..."  

Based on my research this _may_ be an easy fix.  In Bitcoin core I never added the following to my bitcoin.conf file.  "mempoolfullrbf=1".  Do I need to add that, shutdown core, restart, and try to broadcast the transaction again?

Note, I would include the full log file and more details, but I'd rather not if the issue could be an easy fix.  

Any advice is appreciated.  Perhaps there is some documentation you could recommend that I read. 

Thanks.

**Comment by craigraw** [comment]
No, that won't help. Simply put, the message from your node indicates that you are spending UTXOs that have already been spent, or are otherwise invalid. (That said, messages from Core can be misleading sometimes, so it's possible it's something else). Try refreshing your wallet - it may be that Sparrow did not receive updated information from the server.

**Comment by Odellian** [comment]
Hi Craig,

Thanks for your assistance.  Based on your guidance I performed the following:
 - clicked "file"
 - clicked "open wallet"
 - selected receiving wallet
 - clicked on "view" in the menu
 - clicked "refresh wallet"
 
In Sparrow, this resulted in _removal_ of the Mempool value and the unconfirmed transaction that previously appeared.  Also, I no longer see the txid in mempool.space.  My conclusion is that the transaction was purged from the network.  

**Additional Background**
I was the sender and recipient of the transaction, using two offline signing device, managed by Sparrow.  

When I originally sent the transaction, and if memory serves me right, I noticed:
- The Mempool value shown in Sparrow of the _sending_ signing device (SD1) registered amount X.
- The Mempool value shown in Sparrow of the _receiving_ signing device (SD2) registered amount X.

A few days later I noticed:
- The Mempool value in Sparrow of the _sending_ signing device (SD1) had gone to 0.  
- The Mempool value in Sparrow of the _receiving_ signing device (SD2) remained X.  

Thus I tried the CPFP transaction, which failed.  Your recommendation fixed this in Sparrow.  Thanks again.  

**Question**
Regarding signing device (SD2), I see in Sparrow that my _next_ receiving address is the _original_ address that was sent to, and is the same address I tried to spend from using CPFP.  This is because my offline signing device will sign any UTXO that is a valid address associated with with my seed whether or not funds exist, because an offline signing device doesn't have knowledge of the state of the blockchain.  So, I'm in good shape and can resend to the same address and not skip it.  Does that sound about right?  Thanks again.
