### ISSUE TITLE
Proposal: Improved QR scanning - Scanning of inverted QR

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/sparrow#968]
It seems like scanning of inverted QR (white QR on darker background) is not supported in the current version.

It is a very desirable feature in order to be able to scan steel plates created on the SeedHammer machine.

Example (that scans on the SeedHammer controller):

<img width="359" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/93251679/607c83d8-1665-40b0-a53b-bad2c5e3e1bb">
<img width="359" alt="image" src="https://github.com/sparrowwallet/sparrow/assets/93251679/eaf9fed2-6bb7-439a-8fde-7f279366c9c0">

**Comment by craigraw** [comment]
Implemented in 5d99eee8. Sparrow will now invert the cropped frame (area within the dotted line box) and scan for inverted QRs. The output descriptor above scans correctly.

**Comment by seedhammer** [comment]
Thank you!
