### ISSUE TITLE
Can Sparrow Wallet be packaged to run on a start9 embassy?

### ISSUE THREAD

**Issue by OrangeGrasshopper** [sparrowwallet/sparrow#969]
In reviewing previous issues I came across #371 where you talked about packaging sparrow into a debian repository. Has anyone given thought to also packaging Sparrow so that it could run on a start9 embassy? I think that would be great because then I wouldn't have to have my laptop running 24/7 for running whirlpool through sparrow.  I'd simply leave it running and open on the embassy.

Love the wallet BTW. It's never failed me.
Thanks for looking!

**Comment by craigraw** [comment]
You should be able to download and install the Sparrow .deb packages to Start9 already, assuming it is running a Debian-based distro. Use the appropriate Sparrow Server package if there is no GUI.
