### ISSUE TITLE
Timeout 

### ISSUE THREAD

**Issue by rein1111** [sparrowwallet/sparrow#971]
Upon startup the wallet is trying to connect to a bad full node ip. It will just timeout forever and not allow me to change the IP in settings.i cannot get past the initial screen.  I've deleted the app and redownload but it will still just to connect to old IP from the last download.

**Comment by craigraw** [comment]
You can change the configured server in the config file - see the FAQ to find it.

**Comment by rein1111** [comment]
I see nothing in the faq about the config file setting can you post a link please?

**Comment by craigraw** [comment]
Close Sparrow, go Sparrow home (see https://sparrowwallet.com/docs/faq.html#where-does-sparrow-store-data) and edit the file `config` in a text editor. Or just delete it.

**Comment by rein1111** [comment]
Here is what i'v done, it's not working I appreciate your help, I know its frustrating for you.

Applications folder/show package contents/contents folder/runtime folder/contents folder /home/conf (tried to edit conf, no ip info available)

App folder/ app/sparrow.cfg  tried to edit no ip info in config file.

**Comment by craigraw** [comment]
It sounds like you are using MacOS. 

Open the folder `~/.sparrow` (can use Go To Folder in the Go menu in Finder). You will then see the `config` file. It's safe to delete it, Sparrow will recreate it on launching.

**Comment by rein1111** [comment]
Yes! thank you so much

I wasn't right clicking on finder, that combined with the Go To ~/.sparrow, got me to the right config file! 

Thanks again
