### ISSUE TITLE
Black screen / Flickering issues - Fedora Linux

### ISSUE THREAD

**Issue by Roninpus** [sparrowwallet/sparrow#973]
Sparrow 1.7.6

This happens constantly, and Sparrow is unusable. This never happened with previous versions of Fedora Linux.
![sparrow1](https://github.com/sparrowwallet/sparrow/assets/121465923/f1c202aa-1f8d-4fe6-a550-f2ba0e7d6ae1)
![sparrow2](https://github.com/sparrowwallet/sparrow/assets/121465923/c9c6c889-9c92-42f1-a923-fe8e4f7e8626)

OS: Fedora Linux (38)
Windowing System: Wayland
Kernel Version: Linux 6.2.15-300.fc38.x86_64

**Comment by craigraw** [comment]
Try running with 
```
_JAVA_OPTIONS=-Dprism.order=sw /opt/sparrow/bin/Sparrow
```

Some systems have hardware acceleration bugs - this uses a software pipeline.

**Comment by craigraw** [comment]
Thanks for updating, but as a Nvidia driver bug I'm going to close this here.
