### ISSUE TITLE
Feature request: Keyboard shortcut for switching between BTC/sats display

### ISSUE THREAD

**Issue by kangu** [sparrowwallet/sparrow#974]
Would be nice to have a quick way to change or toggle between display in sats or BTC.

There are already menu items under View > Bitcoin Unit > BTC/sats, some shortcuts could be added to those elements. Or even nicer would be to have a toggle shortcut like Cmd/Ctrl+. so you can press only one key and quickly switch between the two denominations.

My scenario is I'm keeping the display in sats, but every now and then I interact with BTC in another place and I need to quickly double checks the value there, so I need a quick way to see the BTC, then go back to sats. Currently I'm using the menu items but it feels clumsy and there's a lot of clicking involved.

The platform I'm working on is OSX, but I think the same concept can be applied to all the others.

**Comment by craigraw** [comment]
Good idea. Implemented in 742727d6. 

The keyboard shortcut is Ctrl/Cmd+B (depending on OS).
