### ISSUE TITLE
Loading wallet fails when connected to Electrs

### ISSUE THREAD

**Issue by Funman2** [sparrowwallet/sparrow#976]
Electrs with Sparrow very often does not connect to Umbrel (using tailscale or local ip) , then I have to toggle on/off for connection in sparrow and close my wallet (I have many derived accounts and tx this wallet) when it's connected, often loading of path fails. 
I can circumvent this by closing the wallet and reopening it when sparrow is connected. 
I heard this is a very common bug with electrs from umbrel and I always get the advice by Craig Raw himself and others to use fulcrum instead. It is that elects does not scan deep enough or to little or something...
I just wonder why other apps like nunchuk, blue wallet, trezor suite, blockstream green always connect fine...

Electrs fully synced of course and connecting other apps like blue wallet, nunchuk, blockstream green never fails actually. 

This issue is happening in all versions of sparrow since 1.5 years. Closing and reopening of wallet usually helps.
Also I found out connecting to Electrs works just fine when the wallet file is not open, thenI open the wallet, loading of paths usually fails, then close it again and reopen, loading usually is successful. Any Ideas ( Its a big wallet file)

**Comment by craigraw** [comment]
All these symptoms indicate that Electrs is not coping with the load placed on it. When Sparrow loads a wallet, it must subscribe each address in the wallet to receive notifications from the Electrum server if there is a new transaction at that address. In doing so, the Electrum protocol specifies that the transaction history at that address must be calculated, hashed and returned. 

Electrs needs to calculate this hash by retrieving affected blocks from Bitcoin Core (unlike Fulcrum or ElectrumX, which do not). This process is very bandwidth and CPU intensive if there are many blocks covering all the transactions in the wallet - many Gbs of data may need to transferred and parsed. If Sparrow waits to long for this to occur, it times out, and you see the error in the loading log.

With deep wallets, Electrs simply does not scale. Read https://sparrowwallet.com/docs/server-performance.html for a more detailed explanation.

**Comment by Funman2** [comment]
Dear Craig, thank you very much for this very detailed answer. This way I was able to understand fully what's going on!

I will then try to connect via local network, not vpn, maybe this helps with bandwidth, also i freed up some Ram memory on umbrel...
Anyhow second time I try I can always load successfully my deep wallet.
 So i also heard umbrel might integrate fulcrum, or maybe i just set up my own fulcrum server...
Thanks for all your efforts and for clearing this up.
Sparrow is indeed the best desktop wallet so far.
