### ISSUE TITLE
Wrong labeling when sending a transaction to multiple wallets

### ISSUE THREAD

**Issue by dluvian** [sparrowwallet/sparrow#979]
When I create a transaction with two outputs, the first to Wallet A labeled as "Tx A" and the rest to Wallet B labeled as "Tx B" leaving no change, the transaction in Wallet B will have the label "Tx A". I would have expected the label to be "Tx B" and not "Tx A". 
When I expand this transaction the received output is correctly labeled as "Tx B (received)" though.

**Comment by craigraw** [comment]
This is intentional. The label for the transaction is applied consistently throughout the wallets in Sparrow (it is, after all, the same transaction). The UTXOs receive individual labels as you have noted.
