### ISSUE TITLE
Ledger Nano S Plus with latest BTC version (2.1.1) can't sign tx

### ISSUE THREAD

**Issue by allegro25** [sparrowwallet/sparrow#981]
I get an error "-31461" when trying to sign with the Ledger.

Latest Sparrow version 1.7.6 and latest BTC app version 2.1.1

Log file attached
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/11642617/sparrow.log)

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in https://github.com/sparrowwallet/drongo/commit/d3e003f76e15e2808a30107e040d519c84393bfa.
