### ISSUE TITLE
Can't sign with Passport (founder's edition)

### ISSUE THREAD

**Issue by allegro25** [sparrowwallet/sparrow#984]
I used the Passport to import the watch-only wallet into Sparrow. When I went to sign it didn't work: "invalid QR code". 
![Screenshot 2023-06-05 at 11 23 45](https://github.com/sparrowwallet/sparrow/assets/32033686/4e13acc1-f452-4fda-8a08-54e59b12ebc3)

Logs and screenshot attached. Not sure if a Sparrow issue or an issue with Passport. 
[sparrow.log](https://github.com/sparrowwallet/sparrow/files/11651501/sparrow.log)

**Comment by allegro25** [comment]
Yes, I used the airgapped option to import the watch-only wallet.

**Comment by craigraw** [comment]
Are you also seeking assistance on the Telegram chat?

**Comment by allegro25** [comment]
Not really. In the Telegram group there was another issue related to passport, but not this. The failed signing with the Passport I just posted here.

**Comment by craigraw** [comment]
From the log file it appears this was due to the same bug you recently reported. Marking as a duplicate of #981.
