### ISSUE TITLE
Question: tr(WIF) import?

### ISSUE THREAD

**Issue by miketwenty1** [sparrowwallet/sparrow#986]
Does Sparrow support importing tr(wif)? I don't want to sweep wif.

**Comment by craigraw** [comment]
No, Sparrow does not support transacting from single key wallets to discourage address reuse.

**Comment by miketwenty1** [comment]
Agree on address reuse.

@craigraw the idea would be preventing 2 transactions where 1 is fine. 
If I have an unused privkey/wif and want to import it within sparrow you first have to sweep it. Instead if you could import it and use as an input for a future tx it would avoid making the unnecessary sweep.

**Comment by craigraw** [comment]
Yes, that would be more efficient, but it's quite a bit of work to do with good UX, and (as I see it) it's a rare need. Always need to find a balance between simple to use UI and supporting every possible use case in it. Not ruling it out entirely, but it would probably need to build on another feature like multi-account spends.

**Comment by miketwenty1** [comment]
@craigraw appreciate your ack.
