### ISSUE TITLE
Export Specter Desktop giving error in 1.7.6

### ISSUE THREAD

**Issue by tadeubas** [sparrowwallet/sparrow#987]
Sequence of steps:
- Install Sparrow 1.7.6 and start in offline mode
- File > Import Wallet > SeedSigner > Scan
- Scanned XPUB
- After Wallet was imported click on `Export...`
- Select Specter Desktop gives error for `Show...` or `Export File...` (all other export options worked fine, problem is only with Specter)

![image](https://github.com/sparrowwallet/sparrow/assets/5518496/aca78612-e30a-4cb9-b0f0-ccbfe0a0e7d5)

![image](https://github.com/sparrowwallet/sparrow/assets/5518496/0b7a6fa6-c203-4ca4-9069-cb03ed4a328a)

**Comment by craigraw** [comment]
Thanks for the bug report. Fixed in 0745d217.
