### ISSUE TITLE
Can use m/84'/0'/0' as derivation path on a multisig keystore

### ISSUE THREAD

**Issue by nikospamp** [sparrowwallet/sparrow#988]
I am testing multisig using sparrow. The flow that I have tested is
* Create 2 wallets using blue wallet
* Create a multisig 2/2 using the xpubs

The issue is that I cant use `m/84'/0'/0'` as a derivation path when I am on the Keystores section of the multisig account.

Here is a screenshot.

![image](https://github.com/sparrowwallet/sparrow/assets/10252329/f2d6d2df-3ce0-4ba3-8a0b-b4e94154f116)

**Comment by craigraw** [comment]
You are using the default derivation path for a Native Segwit singlesig wallet while trying to create a multisig wallet. Sparrow discourages you from doing this to reduce the chance of key reuse. If you want to proceed however, you can disable derivation path validation in the General Preferences.
