### ISSUE TITLE
I can't connect to bitcoin core

### ISSUE THREAD

**Issue by lazzyRabbit** [sparrowwallet/sparrow#990]
I built a node of my own, and it can run through bitcoin-cli, but sparrow can’t connect, and there are various reasons for the error. I hope to solve this issue

**Comment by lazzyRabbit** [comment]
There are two types of errors that are often reported, one is:
retries exhausted
And there is:
Unexpected end-of-input: was expecting closing quote for a string value
  at [Source: (StringReader); line: 1, column: 2785168]
or:
Unexpected end-of-input in field name

**Comment by lazzyRabbit** [comment]
The above error is reported by the test connection of the server.

I didn't connect any wallet, I just made a test connection, and my Bitcoin Core retried many times, and then the configuration is probably like this

**Comment by lazzyRabbit** [comment]
I can't find relevant documentation to deal with this thing.
I am now trying to print the debug log according to what you said

**Comment by craigraw** [comment]
Can you upload the log file here?

**Comment by lazzyRabbit** [comment]
The log is very long, which part of the log should I provide?

**Comment by craigraw** [comment]
You can upload the log as a file, so the length is not really a problem. If you want to excerpt it, you can take the part where you started the DEBUG logging.

**Comment by lazzyRabbit** [comment]
If I upload a log file, I am afraid that some of my private information will be exposed to others. Will others see this file?

**Comment by craigraw** [comment]
Issue was server response was being truncated, possibly by the hosting provider. Recommended a switch to an Electrum server like Fulcrum. Closing this off.

**Comment by lazzyRabbit** [comment]
Hello，i meet new issue
