### ISSUE TITLE
I can't connect private electrum

### ISSUE THREAD

**Issue by lazzyRabbit** [sparrowwallet/sparrow#993]
When I installed electrs as private electrum, I still can’t connect, I can’t connect directly, and the error is
Could not connect:

Retries exhausted
The administrator told me that I need to use the tor proxy to connect. Is it necessary to use the tor proxy to connect? But it is said that installing private electrum can solve this problem, but it does not actually solve this problem

**Comment by craigraw** [comment]
It is not necessary to use Tor to connect. I suggest trying without Tor first. Connect directly to the IP on 50001.

Make sure Electrs has finished indexing - this usually takes a day or two depending on the hardware.

Also make sure you have configured Electrs to bind to the IP, and that firewall has been configured to accept connections on port 50001.
