### ISSUE TITLE
Windows UI bug if system fonts sizes are not standard

### ISSUE THREAD

**Issue by spastad** [sparrowwallet/sparrow#994]
Windows 10, 100% dpi scale, but custom system font sizes for readability (used https://www.wintools.info/index.php/system-font-size-changer ).

It's working for 99% of windows apps, except Sparrow.
The fonts are big, but UI don't resize AND you can't resize most dialog windows. 

![ff2](https://github.com/sparrowwallet/sparrow/assets/136962729/bede08da-04de-4577-a556-d00802b6e291)

![ff3](https://github.com/sparrowwallet/sparrow/assets/136962729/1460f868-18bb-4cf8-b604-ce14b532c796)

**Comment by craigraw** [comment]
Have you tried resizing the UI explicitly? See [I’m running on a high resolution screen and Sparrow icons and text are tiny](https://sparrowwallet.com/docs/faq.html#im-running-on-a-high-resolution-screen-and-sparrow-icons-and-text-are-tiny)

**Comment by spastad** [comment]
Tried setting _glass.win.uiScale_, Sparrow don't start at all (window hidden?).

For now I'll load default font sizes profile before starting Sparrow.

**Comment by craigraw** [comment]
Just checking - did you mean `125%`? The `%` character is required.

**Comment by spastad** [comment]
Thanks, I missed %. Now it's working.
