### ISSUE TITLE
Sparrow Multisig Trezor Model T "no matching devices found"

### ISSUE THREAD

**Issue by bjunjo** [sparrowwallet/sparrow#995]
Somewhat similar to [this issue](https://github.com/sparrowwallet/sparrow/issues/440) but with a multi-sig wallet.

Basically, I am using the Trezor T as one of the devices to sign a multi-sig hardware wallet.

I attempted to send some sats to my hot wallet, but I encountered an issue. Sparrow displayed the message "no matching devices found" even when I connected the correct Trezor T to the Sparrow multi-sig wallet. Interestingly, another device (Cold Card) with a psbt file worked perfectly fine, but the Trezor T, which is connected via USB cable, did not allow me to sign in and complete the transaction.

The xpub from my Trezor (single sig) and one of the expected key stores' xpub on Sparrow do not match. Could this mismatch be the reason why it says "no matching devices found"? It doesn't seem like that is the issue because the Cold Card works without any problems, despite the xpubs not matching.

**Comment by craigraw** [comment]
The message "No matching devices found" is displayed if Sparrow cannot detect the Trezor, or if the master fingerprint of the Trezor does not match that in the Sparrow wallet. The latter could happen if the multisig wallet has been setup incorrectly, or if a passphrase was applied during setup but not signing (or vice versa), or if an incorrect passphrase was applied in either.

You can check the master fingerprint of the connected Trezor by reimporting it, either into the existing multisig wallet or a new wallet.

**Comment by bjunjo** [comment]
Thank you. 

I checked my Trezor master fingerprint. And it doesn't match the one I have with a multi-sig. 

So I tried different passphrases to get the same master fingerprint. But so far no luck...what should I do in this case? Is there a way to find out which wallet is associated with the master fingerprint?

If not, can I replace this keystore with the correct one? What would happen if I replace it? Would I lose my BTC?

**Comment by bjunjo** [comment]
Thank you @craigraw.

I checked my Trezor master fingerprint. And it doesn't match the one I have with a multi-sig.

So I tried different passphrases to get the same master fingerprint. But so far no luck...what should I do in this case? Is there a way to find out which wallet is associated with the master fingerprint?

If not, can I replace this keystore with the correct one? What would happen if I replace it? Would I lose my BTC?

**Comment by craigraw** [comment]
You can't replace the keystore without changing the addresses/losing access to the funds. Best answer is to keep trying until you find the right passphrase - it's probably a typo somewhere. 

You can also move the funds using the other signers (if for example it's a 2 of 3).
