### ISSUE TITLE
Preferences menu, Fiat drop down list is blank; fiat value of balance doesn't appear on wallet tab

### ISSUE THREAD

**Issue by Epic-Sandwich** [sparrowwallet/sparrow#998]
Sparrow Wallet version 1.7.6 for Windows. 

I'll open a wallet, connection to my private electrum server is good, BTC balance shows fine, but the fiat value is totally blank/missing where it should normally be on my wallet tab. I go to File > Preferences > Fiat and the drop down list is blank with zero entries to select from. Changing the Exchange Rate Source from Coinbase to Coingecko doesn't help.

If I close the wallet, close the Sparrow client, then reopen the client and reopen the wallet, the fiat price will reappear, and the Preferences > Fiat drop down list will repopulate, but not for long. It'll shortly disappear again.

**Comment by Epic-Sandwich** [comment]
Update: sometimes changing the Exchange Rate Source from Coinbase to Coingecko will repopulate the Fiat drop down list, but now always. And even if it repopulates, closing and reopening the Preferences window will cause the Fiat drop down list to depopulate again.

**Comment by craigraw** [comment]
Are you using Tor? It sounds like you are having connectivity issues to the exchange rate providers.

**Comment by Epic-Sandwich** [comment]
Yes I am using Tor. You think that is the problem? Does this mean the problem might be with Tor and/or the exchange rate providers rather than a problem with the Sparrow client?

**Comment by craigraw** [comment]
It's definitely a problem with Tor. I looked for onion addresses alternatives for the exchange rate API endpoints, but unfortunately neither Coinbase nor Coingecko offer them AFAIK.

Try testing without Tor (you can close your wallets first).

**Comment by Epic-Sandwich** [comment]
Alright since this ain't a Sparrow problem I'm going to close it. Thanks for helping me out!
