### ISSUE TITLE
add to FAQ, What NFC readers model are supported by Sparrow?

### ISSUE THREAD

**Issue by nostitos** [sparrowwallet/sparrow#999]
I've no idea of the nfc standard and drivers, But if there could be list of a few cheap model that'd be great.

Not paying 100$ for a coil and USB chip.

This one isn't detected
https://www.amazon.com/dp/B083FN977D

**Comment by craigraw** [comment]
It's less about what card terminals Sparrow supports, and more about what terminals the cards themselves support, which is a shorter list. For the Tapsigner/Satscard, Coinkite list their recommended readers: https://github.com/coinkite/coinkite-tap-proto#requirements

I've added this to the FAQ: https://sparrowwallet.com/docs/faq.html#what-nfc-readers-are-supported
